### PR TITLE
fix(button): extra width when loading=false

### LINKED ISSUE #14060: FluentUIv0 - Button with loading=false has slightly more padding than loading=undefined
### Environment Information

- **Package version(s)**: `@fluentui/react-northstar@0.50.0`
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluentui-button-loading-false-issue-rtfb6?file=/example.js

#### Actual behavior:

The following usages of button should yield the same result.

```
<Button loading={false} content="Click here" />
<Button content="Click here" />
```

#### Expected behavior:

There are padding differences between the two implementations - 

image

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable) NA

### PR DESCRIPTION
**Pull request by YuanboXue-Amber**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #14060
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Check if loading is false before applying `loadingMinWidth` to button

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/themes/teams/components/Button/buttonStyles.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export const buttonStyles: ComponentSlotStylesPrepared<ButtonStylesProps, Button
 
     return {
       height: v.height,
-      minWidth: _.isNil(p.loading) ? v.minWidth : v.loadingMinWidth,
+      minWidth: _.isNil(p.loading) || !p.loading ? v.minWidth : v.loadingMinWidth,
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/themes/teams/components/Button/buttonStyles.ts:26]:
```suggestion
      minWidth: p.loading ? v.loadingMinWidth : v.minWidth,
```

I am not sure about usage of `_.isNil()`. Can you please check?

Comment (YuanboXue-Amber) [reply packages/fluentui/react-northstar/src/themes/teams/components/Button/buttonStyles.ts]: It returns true when undefined or null. So your change actually makes more sense.

**Review by layershifter — APPROVED** [review]
