### PR TITLE
fix: Fixing the styles of Buttons rendered as anchor tags

### LINKED ISSUE #23849: [Bug]: Button component looks different when changing the type to an anchor with href
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Package.json - {
  "name": "custom-slots-type-repo",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "main": "src/index.tsx",
  "dependencies": {
    "@fluentui/react-components": "9.0.1",
    "@fluentui/react-icons": "2.0.174",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-scripts": "4.0.3"
  },
  "devDependencies": {
    "@types/react": "17.0.20",
    "@types/react-dom": "17.0.9",
    "typescript": "4.4.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/custom-slots-type-repo-rjyqk5?file=/src/App.tsx

## Actual Behavior
When changing the `Button` component type from `button` to `a` using the `as property the component is visually different than just the default `Button` element. The default size is bigger for some reason.

Also when the `href` prop is defined all the `Button` content is underlined.

image

## Expected Behavior
The visual output of the `Button` component should be the same regardless of the underlying type used - unless this is by design.

### Logs

_No response_

### Requested priority

High

### Products/sites affected

Any product trying to use a default Button component as a anchor

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by khmakoto**
## Previous Behavior

`Buttons` had some different styles when rendered as `anchor` tags than when rendered as `button` tags:

image

## New Behavior

`Buttons` now have the same styles whether they're rendered as `anchor` tags or `button` tags:

image

This PR also adds a vr test to catch this kind of inconsistencies in the future.

## Related Issue(s)

Fixes #23849

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                  Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `84.575 kB`<br />`21.195 kB` |  `84.688 kB`<br />`21.233 kB` | `113 B` <br />`38 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `36.736 kB`<br />`9.845 kB` |   `36.849 kB`<br />`9.907 kB` | `113 B` <br />`62 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `43.761 kB`<br />`11.061 kB` |  `43.874 kB`<br />`11.123 kB` | `113 B` <br />`62 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `39.43 kB`<br />`10.745 kB` |  `39.543 kB`<br />`10.807 kB` | `113 B` <br />`62 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `46.876 kB`<br />`12.129 kB` |  `46.989 kB`<br />`12.192 kB` | `113 B` <br />`63 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `52.603 kB`<br />`11.317 kB` |  `52.716 kB`<br />`11.381 kB` | `113 B` <br />`64 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `62.827 kB`<br />`17.599 kB` |   `62.94 kB`<br />`17.663 kB` | `113 B` <br />`64 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.375 kB`<br />`52.561 kB` | `189.488 kB`<br />`52.587 kB` | `113 B` <br />`26 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                     | `67.216 kB`<br />`19.304 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                               |  `62.898 kB`<br />`18.22 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |   `8.607 kB`<br />`3.622 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |    `9.65 kB`<br />`3.962 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |   `8.708 kB`<br />`3.678 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `33.446 kB`<br />`11.033 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                              |   `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4f7430e2fa321b96ce6022882a42aa897fcf67c9'>4f7430e2fa321b96ce6022882a42aa897fcf67c9</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/Avatar-mount_base.html">1310</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/Avatar-mount.html">1315</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/Button-mount_base.html">954</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/Button-mount.html">948</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/FluentProvider-mount_base.html">1574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/FluentProvider-mount.html">1598</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/FluentProviderWithTheme-mount_base.html">640</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/FluentProviderWithTheme-mount.html">634</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">593</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">599</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">636</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/MakeStyles-mount_base.html">1917</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/MakeStyles-mount.html">1914</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/SpinButton-mount_base.html">2554</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25250/perf-test-react-components/SpinButton-mount.html">2515</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts [hunk 1]
```diff
@@ -19,8 +19,10 @@ const useRootStyles = makeStyles({
   // Base styles
   base: {
     alignItems: 'center',
+    boxSizing: 'border-box',
```
Comment (sopranopillow) [inline packages/react-components/react-button/src/components/Button/useButtonStyles.ts:22]: Is this needed? I think `display: inline-flex` already makes the box-sizing `border-box`.

**Review by sopranopillow — APPROVED** [review]

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts (hunk 1 above)
Comment (spmonahan) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:22]: Do you have a source for this? I don't think `inline-flex` applies `border-box`: https://codepen.io/seanms/pen/gOzEmgE

**Review by spmonahan — APPROVED** [review]

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts (hunk 1 above)
Comment (khmakoto) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:22]: Yeah, this is needed for `anchor` tags, otherwise, the button grows by a ton
