### PR TITLE
fix(Datepicker): type in input is broken

### LINKED ISSUE #19156: Northstar DatePicker manual input is broken
### Environment Information

- **Package version(s)**: fluent-ui/react-northstar 0.57.0

### Please provide a reproduction of the bug in a codepen:

Not needed, use the first example in documentation: https://fluentsite.z22.web.core.windows.net/0.57.0/components/datepicker

#### Actual behavior:

Does not change value

#### Expected behavior:

Supports manual input

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: internal customer project

### PR DESCRIPTION
**Pull request by YuanboXue-Amber**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #19156
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Datepicker typing is broken because of PR #17644, which introduced a useEffect, that has an unstable object as its dependency.
This PR fixed it and added e2e tests

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6a28e3e4cc5660f3b77f311564a132344816c751'>6a28e3e4cc5660f3b77f311564a132344816c751</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Avatar-mount_base.html">870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Avatar-mount.html">900</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/BaseButton-mount_base.html">993</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/BaseButton-mount.html">1022</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Breadcrumb-mount_base.html">2712</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Breadcrumb-mount.html">2803</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ButtonNext-mount_base.html">441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ButtonNext-mount.html">496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Checkbox-mount_base.html">1659</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Checkbox-mount.html">1683</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/CheckboxBase-mount_base.html">1452</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/CheckboxBase-mount.html">1471</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ChoiceGroup-mount_base.html">5229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ChoiceGroup-mount.html">5266</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ComboBox-mount_base.html">1053</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ComboBox-mount.html">1094</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/CommandBar-mount_base.html">10867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/CommandBar-mount.html">10795</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ContextualMenu-mount_base.html">6556</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ContextualMenu-mount.html">6416</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DefaultButton-mount_base.html">1270</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DefaultButton-mount.html">1246</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DetailsRow-mount_base.html">4049</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DetailsRow-mount.html">4025</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DetailsRowFast-mount_base.html">4111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DetailsRowFast-mount.html">4102</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DetailsRowNoStyles-mount_base.html">3806</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DetailsRowNoStyles-mount.html">3867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Dialog-mount_base.html">2284</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Dialog-mount.html">2261</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DocumentCardTitle-mount_base.html">168</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/DocumentCardTitle-mount.html">156</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Dropdown-mount_base.html">3685</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Dropdown-mount.html">3958</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/FluentProviderNext-mount_base.html">7280</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/FluentProviderNext-mount.html">7410</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/FocusTrapZone-mount_base.html">1867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/FocusTrapZone-mount.html">1916</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/FocusZone-mount_base.html">1841</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/FocusZone-mount.html">1890</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/IconButton-mount_base.html">1926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/IconButton-mount.html">1946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Label-mount_base.html">361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Label-mount.html">368</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Layer-mount_base.html">1952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Layer-mount.html">1974</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Link-mount_base.html">503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Link-mount.html">502</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/MakeStyles-mount_base.html">1862</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/MakeStyles-mount.html">1844</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/MenuButton-mount_base.html">1629</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/MenuButton-mount.html">1622</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/MessageBar-mount_base.html">2108</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/MessageBar-mount.html">2156</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Nav-mount_base.html">3521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Nav-mount.html">3546</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/OverflowSet-mount_base.html">1114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/OverflowSet-mount.html">1098</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Panel-mount_base.html">2162</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Panel-mount.html">2201</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Persona-mount_base.html">894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Persona-mount.html">920</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Pivot-mount_base.html">1527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Pivot-mount.html">1496</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/PrimaryButton-mount_base.html">1396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/PrimaryButton-mount.html">1406</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Rating-mount_base.html">8661</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Rating-mount.html">8547</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/SearchBox-mount_base.html">1481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/SearchBox-mount.html">1454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Shimmer-mount_base.html">2872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Shimmer-mount.html">2717</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Slider-mount_base.html">2075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Slider-mount.html">2102</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/SpinButton-mount_base.html">5478</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/SpinButton-mount.html">5410</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Spinner-mount_base.html">475</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Spinner-mount.html">442</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/SplitButton-mount_base.html">3402</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/SplitButton-mount.html">3404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Stack-mount_base.html">561</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Stack-mount.html">571</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/StackWithIntrinsicChildren-mount_base.html">1695</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/StackWithIntrinsicChildren-mount.html">1720</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/StackWithTextChildren-mount_base.html">5063</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/StackWithTextChildren-mount.html">5083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/SwatchColorPicker-mount_base.html">11037</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/SwatchColorPicker-mount.html">11161</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Tabs-mount_base.html">1529</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Tabs-mount.html">1539</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/TagPicker-mount_base.html">2796</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/TagPicker-mount.html">2800</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/TeachingBubble-mount_base.html">12449</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/TeachingBubble-mount.html">12770</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Text-mount_base.html">469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Text-mount.html">467</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/TextField-mount_base.html">1524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/TextField-mount.html">1510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ThemeProvider-mount_base.html">1316</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ThemeProvider-mount.html">1285</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ThemeProvider-virtual-rerender_base.html">673</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/ThemeProvider-virtual-rerender.html">629</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Toggle-mount_base.html">895</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/Toggle-mount.html">870</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/buttonNative-mount_base.html">136</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test/buttonNative-mount.html">125</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
RefMinimalPerf.default | [259](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/RefMinimalPerf.default.html) | [237](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.09:1
PortalMinimalPerf.default | [193](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/PortalMinimalPerf.default.html) | [181](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.07:1
AlertMinimalPerf.default | [309](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AlertMinimalPerf.default.html) | [291](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.06:1
LabelMinimalPerf.default | [432](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/LabelMinimalPerf.default.html) | [409](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.06:1
TreeWith60ListItems.default | [204](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TreeWith60ListItems.default.html) | [193](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.06:1
AttachmentSlotsPerf.default | [1185](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1133](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.05:1
TooltipMinimalPerf.default | [1154](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TooltipMinimalPerf.default.html) | [1097](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.05:1
VideoMinimalPerf.default | [696](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/VideoMinimalPerf.default.html) | [661](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.05:1
ProviderMergeThemesPerf.default | [1813](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1736](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.04:1
ChatMinimalPerf.default | [719](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ChatMinimalPerf.default.html) | [695](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.03:1
DialogMinimalPerf.default | [843](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DialogMinimalPerf.default.html) | [821](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.03:1
FormMinimalPerf.default | [474](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/FormMinimalPerf.default.html) | [462](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.03:1
HeaderMinimalPerf.default | [396](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/HeaderMinimalPerf.default.html) | [383](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.03:1
InputMinimalPerf.default | [1361](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/InputMinimalPerf.default.html) | [1321](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [379](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/SegmentMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
TextMinimalPerf.default | [395](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TextMinimalPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.03:1
BoxMinimalPerf.default | [388](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/BoxMinimalPerf.default.html) | [380](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1888](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1844](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [524](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/CarouselMinimalPerf.default.html) | [513](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
ChatDuplicateMessagesPerf.default | [325](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [319](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.02:1
DatepickerMinimalPerf.default | [5879](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5774](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.02:1
DropdownMinimalPerf.default | [3313](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DropdownMinimalPerf.default.html) | [3260](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.02:1
GridMinimalPerf.default | [380](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/GridMinimalPerf.default.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [761](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/LoaderMinimalPerf.default.html) | [746](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
RadioGroupMinimalPerf.default | [509](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [498](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.02:1
SkeletonMinimalPerf.default | [397](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/SkeletonMinimalPerf.default.html) | [390](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.02:1
TreeMinimalPerf.default | [863](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TreeMinimalPerf.default.html) | [849](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.02:1
CardMinimalPerf.default | [638](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/CardMinimalPerf.default.html) | [629](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2945](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2905](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
DividerMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DividerMinimalPerf.default.html) | [400](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [763](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DropdownManyItemsPerf.default.html) | [755](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [1326](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1310](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
ListCommonPerf.default | [695](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ListCommonPerf.default.html) | [689](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [924](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/MenuMinimalPerf.default.html) | [916](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
SliderMinimalPerf.default | [1720](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/SliderMinimalPerf.default.html) | [1700](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [2203](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TableManyItemsPerf.default.html) | [2183](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
AttachmentMinimalPerf.default | [174](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AttachmentMinimalPerf.default.html) | [174](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1:1
ButtonMinimalPerf.default | [190](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ButtonMinimalPerf.default.html) | [190](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1:1
ButtonSlotsPerf.default | [616](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ButtonSlotsPerf.default.html) | [616](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1:1
ChatWithPopoverPerf.default | [382](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ChatWithPopoverPerf.default.html) | [381](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4463](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/EmbedMinimalPerf.default.html) | [4470](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
ListWith60ListItems.default | [701](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ListWith60ListItems.default.html) | [703](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ListWith60ListItems.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1818](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1812](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [643](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/PopupMinimalPerf.default.html) | [644](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ReactionMinimalPerf.default | [419](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ReactionMinimalPerf.default.html) | [417](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1:1
TextAreaMinimalPerf.default | [593](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TextAreaMinimalPerf.default.html) | [591](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [4257](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/CustomToolbarPrototype.default.html) | [4271](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
ToolbarMinimalPerf.default | [1043](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1047](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1:1
HeaderSlotsPerf.default | [850](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/HeaderSlotsPerf.default.html) | [857](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.99:1
ImageMinimalPerf.default | [403](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ImageMinimalPerf.default.html) | [409](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.99:1
ListMinimalPerf.default | [555](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ListMinimalPerf.default.html) | [560](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.99:1
RosterPerf.default | [1266](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/RosterPerf.default.html) | [1283](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/RosterPerf.default_base.html) | 0.99:1
StatusMinimalPerf.default | [754](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/StatusMinimalPerf.default.html) | [762](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.99:1
IconMinimalPerf.default | [682](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/IconMinimalPerf.default.html) | [687](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.99:1
AnimationMinimalPerf.default | [434](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AnimationMinimalPerf.default.html) | [441](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.98:1
FlexMinimalPerf.default | [311](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/FlexMinimalPerf.default.html) | [317](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/FlexMinimalPerf.default_base.html) | 0.98:1
SplitButtonMinimalPerf.default | [4278](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4387](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 0.98:1
AccordionMinimalPerf.default | [166](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AccordionMinimalPerf.default.html) | [171](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.97:1
LayoutMinimalPerf.default | [391](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/LayoutMinimalPerf.default.html) | [402](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.97:1
AvatarMinimalPerf.default | [211](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AvatarMinimalPerf.default.html) | [219](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.96:1
ListNestedPerf.default | [593](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ListNestedPerf.default.html) | [619](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ListNestedPerf.default_base.html) | 0.96:1
ProviderMinimalPerf.default | [1094](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ProviderMinimalPerf.default.html) | [1141](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.96:1
TableMinimalPerf.default | [447](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TableMinimalPerf.default.html) | [466](https://fluentuipr.z22.web.core.windows.net/pull/19261/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.96:1

</details><div id="perfComment9423"/>

File: packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx [hunk 1]
```diff
@@ -216,10 +216,25 @@ export const Datepicker: ComponentWithAs<'div', DatepickerProps> &
...
+
+  const valueFormatter = React.useCallback(
+    date =>
+      date
+        ? formatMonthDayYear(date, {
+            months: dateFormatting.months,
+            shortMonths: dateFormatting.shortMonths,
+            days: dateFormatting.days,
+            shortDays: dateFormatting.shortDays,
+          })
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx:228]: Is there a reason for this change? I mean a change from `(date ? formatMonthDayYear(date, dateFormatting) : '')`.

**Review by layershifter — APPROVED** [review]

File: packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx (hunk 1 above)
Comment (YuanboXue-Amber) [reply packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx:228]: Heyy, so `dateFormatting` is always re-created on each render, and it's a pretty huge object, so no point in memo :/ 

For this specific bug, when user type in the `input`, Datepicker re-renders, `dateFormatting` is recreated, so: 
`valueFormatter = date ? formatMonthDayYear(date, dateFormatting) : ''` is recreated, 
and the below useEffect is re-run because of `valueFormatter` is new:
```tsx
  React.useEffect(() => {
    setFormattedDate(valueFormatter(selectedDate));
  }, [selectedDate, valueFormatter]);
```
This useEffect will try to set value in `input`, so user cannot change `input` when they type things
