### PR TITLE
fix: SpinButton buttons now show correct visuals at bounds

### LINKED ISSUE #30234: [Bug]: SpinButton increment / decrement button bounds behaving improperly.
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-spinbutton--default#bounds

### Bug Description

1. increase to 20
2. decrease to 19

Then, incrementButton has the disabled style.

3. decrease to 0
4. increase to 1

Then, decrementButton has the disabled style.

---

I think only when 0 / 20 should have the disabled style but it didn't.

### Logs

_No response_

### Requested priority

Low

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by spmonahan**
## Previous Behavior

It was possible to get `SpinButton` buttons in the wrong visual state.

## New Behavior

`SpinButton` buttons now show the correct visual state.

## Related Issue(s)

- Fixes #30234

### CODE REVIEW

File: packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx [hunk 1]
```diff
@@ -245,6 +245,24 @@ export const useSpinButton_unstable = (props: SpinButtonProps, ref: React.Ref<HT
...
+  if (textValue !== undefined) {
+    valueToDisplay = textValue;
+  } else if (value === null || currentValue === null) {
+    valueToDisplay = displayValue ?? '';
+    internalState.current.value = null;
+    internalState.current.atBound = 'none';
+  } else {
+    const roundedValue = precisionRound(currentValue, precision);
+    internalState.current.value = roundedValue;
+    internalState.current.atBound = getBound(roundedValue, min, max);
```
Comment (spmonahan) [inline packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx:258]: The change is that we need to set this internal state before setting the `SpinButtonState` below.

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports | Baseline (minified/GZIP) | PR    | Change     |
| :---------------- | -----------------------: | ----: | ---------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ReactComponents.fixture.js'>react-components: entire library</abbr> | `1.056 MB`<br />`257.496 kB` | `1.056 MB`<br />`257.494 kB` | `6 B` <br />`-2 B` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr> | `36.774 kB`<br />`11.789 kB` | `36.78 kB`<br />`11.789 kB` | `6 B` <br />|

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `71.104 kB`<br />`20.52 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `221.098 kB`<br />`62.406 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `43.591 kB`<br />`14.356 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> | `7.944 kB`<br />`2.588 kB` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/60756381e1f61c1b8e2021cf7ec4ab506c954e21'>60756381e1f61c1b8e2021cf7ec4ab506c954e21</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/Avatar-mount_base.html">647</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/Avatar-mount.html">620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/Button-mount_base.html">293</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/Button-mount.html">306</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/Field-mount_base.html">1142</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/Field-mount.html">1131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/FluentProvider-mount_base.html">721</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/FluentProvider-mount.html">723</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/FluentProviderWithTheme-mount_base.html">85</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/FluentProviderWithTheme-mount.html">80</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">33</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">42</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">69</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">82</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/MakeStyles-mount_base.html">865</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/MakeStyles-mount.html">860</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/Persona-mount_base.html">1761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/Persona-mount.html">1710</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/SpinButton-mount_base.html">1346</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/SpinButton-mount.html">1390</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/SwatchPicker-mount_base.html">1523</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31126/perf-test-react-components/SwatchPicker-mount.html">1538</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by khmakoto — APPROVED** [review]
