### PR TITLE
fix(Popup): Call onClick from trigger when popup on includes hover

### LINKED ISSUE #13545: Popup with 'hover' and 'hover+focus': Trigger's onClick is not executed when user presses Enter
### Environment Information

- **Package version(s)**: 0.49
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:

```
  <Popup
    on={['hover']}
    trigger={<Button icon={<MoreIcon />} onClick={() => alert('a')} content="Click me!" />}
```
and 
```
  <Popup
    on={['hover', 'focus']}
    trigger={<Button icon={<MoreIcon />} onClick={() => alert('a')} content="Click me!" />}
```
#### Actual behavior:
User navigates to the trigger button and presses enter to execute onClick. Alert does not appear.

#### Expected behavior:
Alert appears, similarly to when mouse is used.

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #13545
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Add `click` behaviour to the trigger to call `onClick`  when `Entre | Space` are pressed without changing previous behaviours. 

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/components/Popup/Popup.tsx [hunk 1]
```diff
@@ -188,6 +188,10 @@ const Popup: React.FC<PopupProps> &
         e.preventDefault();
         setPopupOpen(true, e);
       },
+      click: e => {
+        e.stopPropagation();
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Popup/Popup.tsx:192]: If there is a reason to `stopPropagation()` let's add a comment why

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Popup/Popup.tsx]: Not really, removed!
