### PR TITLE
Fix(CarouselPaddles): add CarouselPaddlesContainer to fix vertical centering

### LINKED ISSUE #14168: Fluent v0 [Carousel] Paddles are not centered when content varies in height
Environment - https://fluentsite.z22.web.core.windows.net/components/carousel/definition

When carousel content height varies, the paddle navigation are not centered.  

#### Actual behavior:

image

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #14168
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Adding `CarouselPaddlesContainer` to fix paddles not centering with for different height content.

# ⚠️ Possible breaking changes

This PR changes `Carousel` final DOM structure by wrapping the paddles with a new div container:

```html
<div class="ui-carousel">
	...
	<button class="ui-carousel__paddle ui-carousel__paddleprevious">
		...
        </button>
        <button tabindex="-1" class="ui-carousel__paddle ui-carousel__paddlenext">
		...
	</button>
	...
</div>
```

after:

```html
<div class="ui-carousel">
	...
        <div class="ui-carrouselpaddles_container">
    	    <button class="ui-carousel__paddle ui-carousel__paddleprevious">
		...
             </button>
             <button tabindex="-1" class="ui-carousel__paddle ui-carousel__paddlenext">
		...
	     </button>
        </div>
	...
</div>
```

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Avatar-mount_base.html">807</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Avatar-mount.html">829</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/BaseButtonCompat-mount_base.html">934</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/BaseButtonCompat-mount.html">926</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Breadcrumb-mount_base.html">40046</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Breadcrumb-mount.html">40923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Checkbox-mount_base.html">1583</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Checkbox-mount.html">1519</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/CheckboxBase-mount_base.html">1343</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/CheckboxBase-mount.html">1270</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ChoiceGroup-mount_base.html">4822</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ChoiceGroup-mount.html">4823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ComboBox-mount_base.html">945</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ComboBox-mount.html">972</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/CommandBar-mount_base.html">9747</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/CommandBar-mount.html">9905</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ContextualMenu-mount_base.html">5919</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ContextualMenu-mount.html">5946</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DefaultButtonCompat-mount_base.html">1126</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DefaultButtonCompat-mount.html">1128</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DetailsRow-mount_base.html">3673</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DetailsRow-mount.html">3661</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DetailsRowFast-mount_base.html">3670</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DetailsRowFast-mount.html">3649</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DetailsRowNoStyles-mount_base.html">3531</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DetailsRowNoStyles-mount.html">3497</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Dialog-mount_base.html">1497</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Dialog-mount.html">1491</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DocumentCardTitle-mount_base.html">1737</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/DocumentCardTitle-mount.html">1747</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Dropdown-mount_base.html">3326</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Dropdown-mount.html">3319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/FocusTrapZone-mount_base.html">1757</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/FocusTrapZone-mount.html">1742</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/FocusZone-mount_base.html">1753</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/FocusZone-mount.html">1767</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/IconButtonCompat-mount_base.html">1791</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/IconButtonCompat-mount.html">1805</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Label-mount_base.html">326</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Label-mount.html">332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Layer-mount_base.html">1752</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Layer-mount.html">1769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Link-mount_base.html">440</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Link-mount.html">461</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/MakeStyles-mount_base.html">1924</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/MakeStyles-mount.html">1927</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/MenuButtonCompat-mount_base.html">1524</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/MenuButtonCompat-mount.html">1536</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/MessageBar-mount_base.html">1962</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/MessageBar-mount.html">1945</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Nav-mount_base.html">3312</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Nav-mount.html">3284</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/OverflowSet-mount_base.html">1045</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/OverflowSet-mount.html">1029</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Panel-mount_base.html">1399</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Panel-mount.html">1413</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Persona-mount_base.html">850</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Persona-mount.html">867</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Pivot-mount_base.html">1385</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Pivot-mount.html">1420</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/PrimaryButtonCompat-mount_base.html">1331</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/PrimaryButtonCompat-mount.html">1287</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Rating-mount_base.html">7822</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Rating-mount.html">8144</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/SearchBox-mount_base.html">1363</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/SearchBox-mount.html">1307</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Shimmer-mount_base.html">2608</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Shimmer-mount.html">2623</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Slider-mount_base.html">1925</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Slider-mount.html">1990</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/SpinButton-mount_base.html">4943</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/SpinButton-mount.html">4867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Spinner-mount_base.html">412</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Spinner-mount.html">398</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/SplitButtonCompat-mount_base.html">3163</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/SplitButtonCompat-mount.html">3173</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Stack-mount_base.html">514</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Stack-mount.html">522</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1596</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/StackWithIntrinsicChildren-mount.html">1505</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/StackWithTextChildren-mount_base.html">4582</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/StackWithTextChildren-mount.html">4704</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/SwatchColorPicker-mount_base.html">10045</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/SwatchColorPicker-mount.html">10228</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Tabs-mount_base.html">1479</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Tabs-mount.html">1483</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/TagPicker-mount_base.html">3014</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/TagPicker-mount.html">2974</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/TeachingBubble-mount_base.html">11388</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/TeachingBubble-mount.html">11738</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Text-mount_base.html">428</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Text-mount.html">431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/TextField-mount_base.html">1395</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/TextField-mount.html">1410</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ThemeProvider-mount_base.html">2125</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ThemeProvider-mount.html">2111</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ThemeProvider-virtual-rerender_base.html">617</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/ThemeProvider-virtual-rerender.html">616</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Toggle-mount_base.html">800</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/Toggle-mount.html">785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/button-mount_base.html">713</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/button-mount.html">707</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/buttonNative-mount_base.html">115</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test/buttonNative-mount.html">104</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
CarouselMinimalPerf.default | [501](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CarouselMinimalPerf.default.html) | [454](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.1:1 | [analysis](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CarouselMinimalPerf.default.regression.txt)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.18](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Avatar.Fluent.html) | 0.5 | 0.36:1 | 2000 | 360
🦄 | Button.Fluent | [0.13](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Button.Fluent.html) | 0.21 | 0.62:1 | 5000 | 627
🔧 | Checkbox.Fluent | [0.63](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Checkbox.Fluent.html) | 0.36 | 1.75:1 | 1000 | 630
🎯 | Dialog.Fluent | [0.17](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Dialog.Fluent.html) | 0.22 | 0.77:1 | 5000 | 827
🔧 | Dropdown.Fluent | [2.88](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Dropdown.Fluent.html) | 0.41 | 7.02:1 | 1000 | 2883
🔧 | Icon.Fluent | [0.14](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Icon.Fluent.html) | 0.06 | 2.33:1 | 5000 | 714
🦄 | Image.Fluent | [0.09](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Image.Fluent.html) | 0.13 | 0.69:1 | 5000 | 425
🔧 | Slider.Fluent | [1.52](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Slider.Fluent.html) | 0.44 | 3.45:1 | 1000 | 1515
🔧 | Text.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.67:1 | 5000 | 407
🦄 | Tooltip.Fluent | [0.11](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Tooltip.Fluent.html) | 0.87 | 0.13:1 | 5000 | 567
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ButtonMinimalPerf.default | [197](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonMinimalPerf.default.html) | [176](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.12:1
AttachmentMinimalPerf.default | [176](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AttachmentMinimalPerf.default.html) | [165](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.07:1
AvatarMinimalPerf.default | [223](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AvatarMinimalPerf.default.html) | [208](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.07:1
DropdownManyItemsPerf.default | [807](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DropdownManyItemsPerf.default.html) | [757](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.07:1
Text.Fluent | [407](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Text.Fluent.html) | [382](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Text.Fluent_base.html) | 1.07:1
FlexMinimalPerf.default | [331](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/FlexMinimalPerf.default.html) | [313](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.06:1
GridMinimalPerf.default | [401](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/GridMinimalPerf.default.html) | [379](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.06:1
AnimationMinimalPerf.default | [439](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AnimationMinimalPerf.default.html) | [417](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.05:1
CardMinimalPerf.default | [610](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CardMinimalPerf.default.html) | [583](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.05:1
ChatMinimalPerf.default | [664](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ChatMinimalPerf.default.html) | [633](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.05:1
ImageMinimalPerf.default | [439](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ImageMinimalPerf.default.html) | [419](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.05:1
ToolbarMinimalPerf.default | [1014](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ToolbarMinimalPerf.default.html) | [965](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.05:1
LayoutMinimalPerf.default | [448](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/LayoutMinimalPerf.default.html) | [429](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
RefMinimalPerf.default | [232](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/RefMinimalPerf.default.html) | [223](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.04:1
SegmentMinimalPerf.default | [405](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/SegmentMinimalPerf.default.html) | [389](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.04:1
Icon.Fluent | [714](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Icon.Fluent.html) | [684](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Icon.Fluent_base.html) | 1.04:1
HeaderMinimalPerf.default | [419](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/HeaderMinimalPerf.default.html) | [408](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.03:1
ItemLayoutMinimalPerf.default | [1311](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1269](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
LabelMinimalPerf.default | [460](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/LabelMinimalPerf.default.html) | [447](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.03:1
MenuMinimalPerf.default | [941](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/MenuMinimalPerf.default.html) | [911](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.03:1
PortalMinimalPerf.default | [165](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/PortalMinimalPerf.default.html) | [160](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.03:1
IconMinimalPerf.default | [714](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/IconMinimalPerf.default.html) | [691](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.03:1
TextMinimalPerf.default | [389](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TextMinimalPerf.default.html) | [377](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.03:1
AccordionMinimalPerf.default | [174](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AccordionMinimalPerf.default.html) | [171](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.02:1
ButtonSlotsPerf.default | [609](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonSlotsPerf.default.html) | [598](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [829](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DialogMinimalPerf.default.html) | [809](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
HeaderSlotsPerf.default | [858](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/HeaderSlotsPerf.default.html) | [842](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.02:1
ListCommonPerf.default | [697](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ListCommonPerf.default.html) | [685](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ListCommonPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [539](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ListMinimalPerf.default.html) | [531](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
ListNestedPerf.default | [614](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ListNestedPerf.default.html) | [604](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ListNestedPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [725](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/LoaderMinimalPerf.default.html) | [708](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [3923](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3833](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [847](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TooltipMinimalPerf.default.html) | [831](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
Avatar.Fluent | [360](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Avatar.Fluent.html) | [353](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Avatar.Fluent_base.html) | 1.02:1
ChatWithPopoverPerf.default | [449](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ChatWithPopoverPerf.default.html) | [444](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2839](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2814](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [2918](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DropdownMinimalPerf.default.html) | [2881](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [1297](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/InputMinimalPerf.default.html) | [1289](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [1529](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1517](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
StatusMinimalPerf.default | [780](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/StatusMinimalPerf.default.html) | [770](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [2177](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TableManyItemsPerf.default.html) | [2155](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
VideoMinimalPerf.default | [675](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/VideoMinimalPerf.default.html) | [666](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.01:1
Image.Fluent | [425](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Image.Fluent.html) | [419](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Image.Fluent_base.html) | 1.01:1
Tooltip.Fluent | [567](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Tooltip.Fluent.html) | [560](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Tooltip.Fluent_base.html) | 1.01:1
AlertMinimalPerf.default | [320](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AlertMinimalPerf.default.html) | [321](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1:1
AttachmentSlotsPerf.default | [1245](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1246](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1:1
BoxMinimalPerf.default | [405](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/BoxMinimalPerf.default.html) | [404](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1:1
ButtonUseCssPerf.default | [859](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonUseCssPerf.default.html) | [857](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 1:1
DividerMinimalPerf.default | [413](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DividerMinimalPerf.default.html) | [415](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1:1
ListWith60ListItems.default | [677](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ListWith60ListItems.default.html) | [679](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ListWith60ListItems.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1657](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1650](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
SkeletonMinimalPerf.default | [407](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/SkeletonMinimalPerf.default.html) | [405](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1554](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/SliderMinimalPerf.default.html) | [1552](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3568](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CustomToolbarPrototype.default.html) | [3558](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
TreeMinimalPerf.default | [826](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TreeMinimalPerf.default.html) | [827](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1:1
Button.Fluent | [627](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Button.Fluent.html) | [629](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Button.Fluent_base.html) | 1:1
Checkbox.Fluent | [630](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Checkbox.Fluent.html) | [632](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Checkbox.Fluent_base.html) | 1:1
Dialog.Fluent | [827](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Dialog.Fluent.html) | [824](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Dialog.Fluent_base.html) | 1:1
Slider.Fluent | [1515](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Slider.Fluent.html) | [1519](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Slider.Fluent_base.html) | 1:1
ButtonOverridesMissPerf.default | [1661](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1685](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
ButtonUseCssNestingPerf.default | [1070](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1084](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 0.99:1
FormMinimalPerf.default | [473](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/FormMinimalPerf.default.html) | [477](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.99:1
PopupMinimalPerf.default | [696](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/PopupMinimalPerf.default.html) | [705](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.99:1
RadioGroupMinimalPerf.default | [483](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [486](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.99:1
TableMinimalPerf.default | [446](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TableMinimalPerf.default.html) | [450](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.99:1
Dropdown.Fluent | [2883](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Dropdown.Fluent.html) | [2906](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/Dropdown.Fluent_base.html) | 0.99:1
ChatDuplicateMessagesPerf.default | [371](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [377](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.98:1
EmbedMinimalPerf.default | [4097](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/EmbedMinimalPerf.default.html) | [4198](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.98:1
ProviderMinimalPerf.default | [902](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ProviderMinimalPerf.default.html) | [925](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.98:1
RosterPerf.default | [1240](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/RosterPerf.default.html) | [1293](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/RosterPerf.default_base.html) | 0.96:1
TextAreaMinimalPerf.default | [544](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TextAreaMinimalPerf.default.html) | [566](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.96:1
ReactionMinimalPerf.default | [434](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ReactionMinimalPerf.default.html) | [457](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.95:1
TreeWith60ListItems.default | [175](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TreeWith60ListItems.default.html) | [184](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.95:1
DatepickerMinimalPerf.default | [47175](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DatepickerMinimalPerf.default.html) | [50188](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16477/merge/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.94:1

</details><div id="perfComment9423"/>

**Comment by ling1726** [comment]
Is the alignment change of pagination expected ? 

image

File: packages/fluentui/react-northstar/src/components/Carousel/CarouselPaddlesContainer.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+  accessibility?: Accessibility<never>;
+}
+
+export type CarouselPaddlesContainerStylesProps = never;
+export const carouselPaddlesContainerClassName = 'ui-carrouselpaddles_container';
+
+/**
+ * A CarouselPaddlesContainer is a container for the Carousel Paddles.
+ */
+export const CarouselPaddlesContainer: ComponentWithAs<'span', CarouselPaddlesContainerProps> &
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Carousel/CarouselPaddlesContainer.tsx:32]: From what I can see, this is not actually a span ? 

```suggestion
export const CarouselPaddlesContainer: ComponentWithAs<'div', CarouselPaddlesContainerProps> &
```

File: packages/fluentui/react-northstar/src/components/Carousel/CarouselPaddlesContainer.tsx [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+import { FluentComponentStaticProps } from '../../types';
+import { Accessibility } from '@fluentui/accessibility';
+
+export interface CarouselPaddlesContainerProps extends UIComponentProps, ContentComponentProps, ChildrenComponentProps {
+  /** Accessibility behavior if overridden by the user. */
+  accessibility?: Accessibility<never>;
+}
+
+export type CarouselPaddlesContainerStylesProps = never;
+export const carouselPaddlesContainerClassName = 'ui-carrouselpaddles_container';
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Carousel/CarouselPaddlesContainer.tsx:27]: Can you add a before/after of the DOM structure ? Just to communicate that that the two buttons are no longer direct children of the carousel container

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Carousel/CarouselPaddlesContainer.tsx:27]: There wouldn't be visual changes so not sure if I get the point for having screenshot

Comment (ling1726) [reply packages/fluentui/react-northstar/src/components/Carousel/CarouselPaddlesContainer.tsx:27]: they wouldn't be visual changes, but can definitely raise questions why applied styles might suddenly be different or why E2E tests fail because of a selector that relies on only one div container before the button

File: packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselNavigationStyles.ts [hunk 3]
```diff
@@ -16,6 +16,7 @@ export const carouselNavigationStyles: ComponentSlotStylesPrepared<
       display: 'flex',
       minHeight: pxToRem(24),
       margin: 0,
+
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselNavigationStyles.ts:19]: nit: empty line

Comment (ling1726) [reply packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselNavigationStyles.ts:19]:
```suggestion
```

File: packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselPaddleStyles.ts [hunk 4]
```diff
@@ -7,8 +7,9 @@ import { CarouselVariables } from './carouselVariables';
 import { getBorderFocusStyles } from '../../getBorderFocusStyles';
 import { getIconFillOrOutlineStyles } from '../../getIconFillOrOutlineStyles';
 import { paddleIndicatorUrl } from './paddleIndicatorUrl';
-import { pxToRem } from '../../../../utils';
+
 import { faster, ultraFast } from '../../animations/durations';
+import { pxToRem } from '../../../../utils/index';
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselPaddleStyles.ts:12]: why did you import from `index` ?

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselPaddleStyles.ts:12]: Automatic... Removing it

File: packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselNavigationStyles.ts (hunk 3 above)
Comment (assuncaocharles) [inline packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselNavigationStyles.ts:19]:
```suggestion
```

**Review by layershifter — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]

File: packages/fluentui/react-northstar/src/components/Carousel/CarouselPaddlesContainer.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Carousel/CarouselPaddlesContainer.tsx:27]: Not really, all our components have `ui` as prefix
