### PR TITLE
fix: FloatingPeoplePicker roles should be listbox/option

### LINKED ISSUE #25538: FloatingPicker: Aria Parent issue because suggestions have option without parent
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by smhigley**
Fixes #25538

Previously, the FloatingPeoplePicker had this role structure:

- list
  - listitem
    - option
  - listitem
    - option
  - etc.

We want just a plain:
- listbox
  - option
  - option
  - etc.

The `option` role already comes from the `SuggestionsItem` used internally, so this PR updates the floating control to just wrap SuggestionsItems in a `listbox` with no list/listitem roles.

### CODE REVIEW

File: packages/react/src/components/FloatingPicker/BaseFloatingPicker.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ export class BaseFloatingPicker<T, P extends IBaseFloatingPickerProps<T>>
   public onQueryStringChanged = (queryString: string): void => {
     if (queryString !== this.state.queryString) {
       this.setState({
-        queryString: queryString,
+        queryString,
```
Comment (smhigley) [inline packages/react/src/components/FloatingPicker/BaseFloatingPicker.tsx:75]: This was a linting change; I was probably the first to touch this file in a while.

File: packages/react/src/components/FloatingPicker/BaseFloatingPicker.tsx [hunk 2]
```diff
@@ -281,7 +281,7 @@ export class BaseFloatingPicker<T, P extends IBaseFloatingPickerProps<T>>
         if (
           this.props.onRemoveSuggestion &&
           this.suggestionsControl.current &&
-          this.suggestionsControl.current.hasSuggestionSelected &&
+          this.suggestionsControl.current.hasSuggestionSelected() &&
```
Comment (smhigley) [inline packages/react/src/components/FloatingPicker/BaseFloatingPicker.tsx:284]: Needed to make this change to run without errors; not calling the function seems like a pretty clear bug.

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/06d0d5598c28ac70e07d9b9e7d1b77151369d193'>06d0d5598c28ac70e07d9b9e7d1b77151369d193</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/BaseButton-mount_base.html">1204</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/BaseButton-mount.html">1200</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Breadcrumb-mount_base.html">2785</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Breadcrumb-mount.html">2775</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Checkbox-mount_base.html">2651</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Checkbox-mount.html">2658</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/CheckboxBase-mount_base.html">2362</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/CheckboxBase-mount.html">2339</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ChoiceGroup-mount_base.html">4281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ChoiceGroup-mount.html">4299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ComboBox-mount_base.html">1152</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ComboBox-mount.html">1172</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/CommandBar-mount_base.html">9246</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/CommandBar-mount.html">9202</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ContextualMenu-mount_base.html">10190</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ContextualMenu-mount.html">10180</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DefaultButton-mount_base.html">1363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DefaultButton-mount.html">1378</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DetailsRow-mount_base.html">3412</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DetailsRow-mount.html">3347</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DetailsRowFast-mount_base.html">3411</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DetailsRowFast-mount.html">3334</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DetailsRowNoStyles-mount_base.html">3285</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DetailsRowNoStyles-mount.html">3241</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Dialog-mount_base.html">2970</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Dialog-mount.html">2998</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DocumentCardTitle-mount_base.html">580</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/DocumentCardTitle-mount.html">590</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Dropdown-mount_base.html">3182</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Dropdown-mount.html">3174</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/FocusTrapZone-mount_base.html">1955</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/FocusTrapZone-mount.html">1932</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/FocusZone-mount_base.html">1948</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/FocusZone-mount.html">1927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedList-mount_base.html">1818</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedList-mount.html">2031</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedList-virtual-rerender_base.html">1108</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedList-virtual-rerender.html">1101</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">1609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedList-virtual-rerender-with-unmount.html">1618</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedListV2-mount_base.html">552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedListV2-mount.html">568</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedListV2-virtual-rerender_base.html">539</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedListV2-virtual-rerender.html">533</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">564</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">568</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/IconButton-mount_base.html">1795</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/IconButton-mount.html">1759</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Label-mount_base.html">744</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Label-mount.html">744</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Layer-mount_base.html">4225</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Layer-mount.html">4253</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Link-mount_base.html">840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Link-mount.html">860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/MenuButton-mount_base.html">1614</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/MenuButton-mount.html">1622</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/MessageBar-mount_base.html">2366</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/MessageBar-mount.html">2318</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Nav-mount_base.html">3320</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Nav-mount.html">3096</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/OverflowSet-mount_base.html">1394</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/OverflowSet-mount.html">1404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Panel-mount_base.html">2542</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Panel-mount.html">2449</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Persona-mount_base.html">1272</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Persona-mount.html">1218</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Pivot-mount_base.html">1544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Pivot-mount.html">1514</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/PrimaryButton-mount_base.html">1483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/PrimaryButton-mount.html">1456</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Rating-mount_base.html">6919</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Rating-mount.html">6917</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/SearchBox-mount_base.html">1474</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/SearchBox-mount.html">1492</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Shimmer-mount_base.html">2892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Shimmer-mount.html">2902</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Slider-mount_base.html">2094</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Slider-mount.html">2101</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/SpinButton-mount_base.html">4244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/SpinButton-mount.html">4229</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Spinner-mount_base.html">823</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Spinner-mount.html">809</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/SplitButton-mount_base.html">2862</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/SplitButton-mount.html">2841</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Stack-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Stack-mount.html">862</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/StackWithIntrinsicChildren-mount_base.html">2332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/StackWithIntrinsicChildren-mount.html">2337</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/StackWithTextChildren-mount_base.html">5020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/StackWithTextChildren-mount.html">5051</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/SwatchColorPicker-mount_base.html">9473</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/SwatchColorPicker-mount.html">10299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/TagPicker-mount_base.html">2316</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/TagPicker-mount.html">2320</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/TeachingBubble-mount_base.html">75250</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/TeachingBubble-mount.html">74816</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Text-mount_base.html">812</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Text-mount.html">828</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/TextField-mount_base.html">1540</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/TextField-mount.html">1535</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ThemeProvider-mount_base.html">1441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ThemeProvider-mount.html">1451</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ThemeProvider-virtual-rerender_base.html">1123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ThemeProvider-virtual-rerender.html">1127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2014</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2028</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Toggle-mount_base.html">1173</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/Toggle-mount.html">1122</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/buttonNative-mount_base.html">554</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25641/perf-test/buttonNative-mount.html">546</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by khmakoto — APPROVED** [review]
