### PR TITLE
fix(ToolbarMenuItem): missing aria-haspopup when it has submenu

### LINKED ISSUE #17279: react-northstar Toolbar menu item is missing aria-haspopup when it has a submenu
### Environment Information

- **Package version(s)**: 0.52.1
- **Browser and OS versions**:  all

### Please provide a reproduction of the bug in a codepen:
https://fluentsite.z22.web.core.windows.net/0.52.1/components/toolbar/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#content-menu-with-submenu

#### Actual behavior:

Item with submenu is missing `aria-haspopup={true}`

#### Expected behavior:

Item with submenu has `aria-haspopup={true}`

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by YuanboXue-Amber**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #17279
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Before:
Notice item 'Play' has submenu, but its DOM does not have `aria-haspopup`
image

After:
image

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/accessibility/src/behaviors/Toolbar/toolbarMenuItemBehavior.ts [hunk 1]
```diff
@@ -27,8 +27,8 @@ export const toolbarMenuItemBehavior: Accessibility<ToolbarMenuItemBehaviorProps
 };
 
 export type ToolbarMenuItemBehaviorProps = {
-  /** Indicated if menu item has submenu. TODO: fix types for all behaviours */
-  menu?: any;
+  /** Indicated if menu item has submenu */
+  hasMenu?: boolean;
```
Comment (ling1726) [inline packages/fluentui/accessibility/src/behaviors/Toolbar/toolbarMenuItemBehavior.ts:31]: would it make more sense just to intersect `Pick<MenuItemBehaviourProps, 'hasMenu'> ?

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Avatar-mount_base.html">882</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Avatar-mount.html">875</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/BaseButton-mount_base.html">859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/BaseButton-mount.html">855</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Breadcrumb-mount_base.html">40638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Breadcrumb-mount.html">40761</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ButtonNext-mount_base.html">544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ButtonNext-mount.html">553</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Checkbox-mount_base.html">1458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Checkbox-mount.html">1449</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/CheckboxBase-mount_base.html">1201</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/CheckboxBase-mount.html">1230</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ChoiceGroup-mount_base.html">4429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ChoiceGroup-mount.html">4377</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ComboBox-mount_base.html">920</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ComboBox-mount.html">912</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/CommandBar-mount_base.html">9429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/CommandBar-mount.html">9457</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ContextualMenu-mount_base.html">5854</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ContextualMenu-mount.html">5825</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DefaultButton-mount_base.html">1071</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DefaultButton-mount.html">1045</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DetailsRow-mount_base.html">3449</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DetailsRow-mount.html">3446</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DetailsRowFast-mount_base.html">3496</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DetailsRowFast-mount.html">3450</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DetailsRowNoStyles-mount_base.html">3298</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DetailsRowNoStyles-mount.html">3294</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Dialog-mount_base.html">1356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Dialog-mount.html">1368</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DocumentCardTitle-mount_base.html">1749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/DocumentCardTitle-mount.html">1726</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Dropdown-mount_base.html">3125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Dropdown-mount.html">3135</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/FocusTrapZone-mount_base.html">1688</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/FocusTrapZone-mount.html">1692</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/FocusZone-mount_base.html">1749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/FocusZone-mount.html">1747</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/IconButton-mount_base.html">1689</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/IconButton-mount.html">1615</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Label-mount_base.html">326</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Label-mount.html">316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Layer-mount_base.html">1676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Layer-mount.html">1693</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Link-mount_base.html">447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Link-mount.html">425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/MakeStyles-mount_base.html">1720</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/MakeStyles-mount.html">1708</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/MenuButton-mount_base.html">1359</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/MenuButton-mount.html">1371</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/MessageBar-mount_base.html">1866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/MessageBar-mount.html">1935</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Nav-mount_base.html">3065</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Nav-mount.html">3092</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/OverflowSet-mount_base.html">1005</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/OverflowSet-mount.html">968</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Panel-mount_base.html">1345</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Panel-mount.html">1375</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Persona-mount_base.html">776</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Persona-mount.html">775</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Pivot-mount_base.html">1309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Pivot-mount.html">1382</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/PrimaryButton-mount_base.html">1192</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/PrimaryButton-mount.html">1205</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Rating-mount_base.html">7213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Rating-mount.html">7238</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/SearchBox-mount_base.html">1237</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/SearchBox-mount.html">1231</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Shimmer-mount_base.html">2356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Shimmer-mount.html">2463</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Slider-mount_base.html">1859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Slider-mount.html">1853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/SpinButton-mount_base.html">4668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/SpinButton-mount.html">4679</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Spinner-mount_base.html">397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Spinner-mount.html">388</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/SplitButton-mount_base.html">2949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/SplitButton-mount.html">2953</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Stack-mount_base.html">465</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Stack-mount.html">458</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/StackWithIntrinsicChildren-mount_base.html">1468</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/StackWithIntrinsicChildren-mount.html">1452</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/StackWithTextChildren-mount_base.html">4278</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/StackWithTextChildren-mount.html">4299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/SwatchColorPicker-mount_base.html">10668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/SwatchColorPicker-mount.html">9637</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Tabs-mount_base.html">1304</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Tabs-mount.html">1308</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/TagPicker-mount_base.html">2695</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/TagPicker-mount.html">2693</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/TeachingBubble-mount_base.html">10977</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/TeachingBubble-mount.html">10971</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Text-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Text-mount.html">401</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/TextField-mount_base.html">1286</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/TextField-mount.html">1312</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ThemeProvider-mount_base.html">1129</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ThemeProvider-mount.html">1110</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ThemeProvider-virtual-rerender_base.html">569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ThemeProvider-virtual-rerender.html">563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ThemeProviderNext-mount_base.html">15160</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/ThemeProviderNext-mount.html">15183</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Toggle-mount_base.html">771</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/Toggle-mount.html">769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/buttonNative-mount_base.html">111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test/buttonNative-mount.html">112</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.16](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Avatar.Fluent.html) | 0.46 | 0.35:1 | 2000 | 324
🦄 | Button.Fluent | [0.11](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Button.Fluent.html) | 0.19 | 0.58:1 | 5000 | 525
🔧 | Checkbox.Fluent | [0.6](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Checkbox.Fluent.html) | 0.33 | 1.82:1 | 1000 | 598
🎯 | Dialog.Fluent | [0.14](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Dialog.Fluent.html) | 0.2 | 0.7:1 | 5000 | 701
🔧 | Dropdown.Fluent | [2.98](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Dropdown.Fluent.html) | 0.39 | 7.64:1 | 1000 | 2979
🔧 | Icon.Fluent | [0.12](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Icon.Fluent.html) | 0.05 | 2.4:1 | 5000 | 581
🦄 | Image.Fluent | [0.07](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Image.Fluent.html) | 0.12 | 0.58:1 | 5000 | 360
🔧 | Slider.Fluent | [1.51](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Slider.Fluent.html) | 0.42 | 3.6:1 | 1000 | 1510
🔧 | Text.Fluent | [0.07](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.33:1 | 5000 | 339
🦄 | Tooltip.Fluent | [0.13](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Tooltip.Fluent.html) | 0.85 | 0.15:1 | 5000 | 658
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
TreeWith60ListItems.default | [187](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TreeWith60ListItems.default.html) | [169](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.11:1
AvatarMinimalPerf.default | [208](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AvatarMinimalPerf.default.html) | [190](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.09:1
CarouselMinimalPerf.default | [449](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/CarouselMinimalPerf.default.html) | [423](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.06:1
GridMinimalPerf.default | [341](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/GridMinimalPerf.default.html) | [321](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.06:1
AttachmentMinimalPerf.default | [163](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AttachmentMinimalPerf.default.html) | [155](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.05:1
ButtonSlotsPerf.default | [543](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonSlotsPerf.default.html) | [518](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.05:1
CardMinimalPerf.default | [544](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/CardMinimalPerf.default.html) | [525](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.04:1
DividerMinimalPerf.default | [356](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DividerMinimalPerf.default.html) | [342](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.04:1
HeaderSlotsPerf.default | [725](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/HeaderSlotsPerf.default.html) | [695](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.04:1
TableMinimalPerf.default | [393](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TableMinimalPerf.default.html) | [378](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.04:1
VideoMinimalPerf.default | [627](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/VideoMinimalPerf.default.html) | [602](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.04:1
Avatar.Fluent | [324](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Avatar.Fluent.html) | [311](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Avatar.Fluent_base.html) | 1.04:1
Checkbox.Fluent | [598](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Checkbox.Fluent.html) | [575](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Checkbox.Fluent_base.html) | 1.04:1
AttachmentSlotsPerf.default | [1130](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1092](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [346](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/SegmentMinimalPerf.default.html) | [337](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
TextAreaMinimalPerf.default | [477](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TextAreaMinimalPerf.default.html) | [462](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.03:1
FlexMinimalPerf.default | [289](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/FlexMinimalPerf.default.html) | [282](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.02:1
InputMinimalPerf.default | [1218](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/InputMinimalPerf.default.html) | [1189](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.02:1
PortalMinimalPerf.default | [165](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/PortalMinimalPerf.default.html) | [161](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.02:1
IconMinimalPerf.default | [602](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/IconMinimalPerf.default.html) | [592](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.02:1
TextMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TextMinimalPerf.default.html) | [338](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [939](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TooltipMinimalPerf.default.html) | [922](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
Dropdown.Fluent | [2979](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Dropdown.Fluent.html) | [2933](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Dropdown.Fluent_base.html) | 1.02:1
Icon.Fluent | [581](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Icon.Fluent.html) | [572](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Icon.Fluent_base.html) | 1.02:1
Text.Fluent | [339](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Text.Fluent.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Text.Fluent_base.html) | 1.02:1
ButtonUseCssPerf.default | [762](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonUseCssPerf.default.html) | [758](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 1.01:1
ChatWithPopoverPerf.default | [372](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ChatWithPopoverPerf.default.html) | [368](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [679](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/LoaderMinimalPerf.default.html) | [669](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
MenuButtonMinimalPerf.default | [1475](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1458](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.01:1
RadioGroupMinimalPerf.default | [425](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [421](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.01:1
SkeletonMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/SkeletonMinimalPerf.default.html) | [346](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.01:1
SliderMinimalPerf.default | [1519](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/SliderMinimalPerf.default.html) | [1504](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1799](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TableManyItemsPerf.default.html) | [1784](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
CustomToolbarPrototype.default | [3634](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/CustomToolbarPrototype.default.html) | [3596](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.01:1
Button.Fluent | [525](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Button.Fluent.html) | [520](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Button.Fluent_base.html) | 1.01:1
Dialog.Fluent | [701](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Dialog.Fluent.html) | [694](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Dialog.Fluent_base.html) | 1.01:1
AlertMinimalPerf.default | [267](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AlertMinimalPerf.default.html) | [268](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1:1
AnimationMinimalPerf.default | [399](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AnimationMinimalPerf.default.html) | [398](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1627](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1624](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
ButtonUseCssNestingPerf.default | [1030](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1026](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 1:1
ChatDuplicateMessagesPerf.default | [289](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [288](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1:1
DialogMinimalPerf.default | [712](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DialogMinimalPerf.default.html) | [711](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [2952](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DropdownMinimalPerf.default.html) | [2954](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
ItemLayoutMinimalPerf.default | [1198](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1195](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [374](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/LabelMinimalPerf.default.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
LayoutMinimalPerf.default | [357](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/LayoutMinimalPerf.default.html) | [358](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1:1
ListWith60ListItems.default | [604](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ListWith60ListItems.default.html) | [602](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ListWith60ListItems.default_base.html) | 1:1
MenuMinimalPerf.default | [835](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/MenuMinimalPerf.default.html) | [839](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [685](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/PopupMinimalPerf.default.html) | [683](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [959](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ProviderMinimalPerf.default.html) | [956](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3534](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3533](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [646](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/StatusMinimalPerf.default.html) | [644](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
TreeMinimalPerf.default | [752](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TreeMinimalPerf.default.html) | [754](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1:1
Tooltip.Fluent | [658](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Tooltip.Fluent.html) | [658](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Tooltip.Fluent_base.html) | 1:1
AccordionMinimalPerf.default | [150](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AccordionMinimalPerf.default.html) | [151](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.99:1
BoxMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/BoxMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/BoxMinimalPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [581](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ChatMinimalPerf.default.html) | [589](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [2599](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2619](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
DatepickerMinimalPerf.default | [41687](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DatepickerMinimalPerf.default.html) | [41904](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.99:1
DropdownManyItemsPerf.default | [647](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DropdownManyItemsPerf.default.html) | [654](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [3924](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/EmbedMinimalPerf.default.html) | [3944](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
FormMinimalPerf.default | [393](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/FormMinimalPerf.default.html) | [397](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.99:1
ImageMinimalPerf.default | [359](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ImageMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.99:1
ListMinimalPerf.default | [480](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ListMinimalPerf.default.html) | [484](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.99:1
ReactionMinimalPerf.default | [367](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ReactionMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.99:1
Slider.Fluent | [1510](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Slider.Fluent.html) | [1531](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Slider.Fluent_base.html) | 0.99:1
HeaderMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/HeaderMinimalPerf.default.html) | [351](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.98:1
ListCommonPerf.default | [583](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ListCommonPerf.default.html) | [592](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ListCommonPerf.default_base.html) | 0.98:1
ListNestedPerf.default | [533](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ListNestedPerf.default.html) | [544](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ListNestedPerf.default_base.html) | 0.98:1
ProviderMergeThemesPerf.default | [1565](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1597](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.98:1
RefMinimalPerf.default | [226](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/RefMinimalPerf.default.html) | [232](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.97:1
RosterPerf.default | [1099](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/RosterPerf.default.html) | [1140](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/RosterPerf.default_base.html) | 0.96:1
ToolbarMinimalPerf.default | [891](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ToolbarMinimalPerf.default.html) | [930](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.96:1
Image.Fluent | [360](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Image.Fluent.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/Image.Fluent_base.html) | 0.96:1
ButtonMinimalPerf.default | [166](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonMinimalPerf.default.html) | [177](https://fluentuipr.z22.web.core.windows.net/pull/17646/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.94:1

</details><div id="perfComment9423"/>

File: packages/fluentui/accessibility/src/behaviors/Toolbar/toolbarMenuItemBehavior.ts (hunk 1 above)
Comment (YuanboXue-Amber) [reply packages/fluentui/accessibility/src/behaviors/Toolbar/toolbarMenuItemBehavior.ts:31]: This is a great suggestion, after checking MenuItemBehavior, I changed toolbarMenuItemBehaviorProp to:
```tsx
export type ToolbarMenuItemBehaviorProps = Omit<MenuItemBehaviorProps, 'vertical'>;
```

**Review by ling1726 — APPROVED** [review]
