### PR TITLE
Updated color styles and values for Label. Fix padding for circular Label.

### LINKED ISSUE #15538: Some labels in Northstar don't have the correct label color and text color
### Environment Information

- **Package version(s)**: @fluentui/react-northstar 0.51.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug:
1. Go to https://fluentsite.z22.web.core.windows.net/components/label/definition#variations-color to see where all the label colors are.
2. Change between light mode, dark mode, and high-constrast mode to see the text colors.

#### Actual behavior:
These would also be accessibility issues I guess. Depending on the label `color` and the theme, the text does not have the proper color. More specifically:

In light mode:
1. The text for `color="orange"` is invisible.
2. The text for `color="green"` does not have enough contrast.
3. The text for `color="yellow"` does not have enough contrast.
image

In dark mode:
1. The text for `color="brand"` white and the label color is lighter than it is in light mode.
2. The text for `color="orange"` is invisible.
3. The text for `color="green"` is invisible.
4. The text for `color="yellow"` does not have enough contrast.
image

In high-contrast mode:
1. The text for `color="orange"` is invisible.
2. The text for `color="green"` is invisible.
3. The text for `color="yellow"` is invisible.
4. The label colors are inconsistent, as some are white, one is yellow, and one is black.
image

#### Expected behavior:
In light mode:
1. The text for `color="orange"` should be visible.
2. The text for `color="green"` should have more contrast.
3. The text for `color="yellow"` should have more contrast.

In dark mode:
1. I thought the label and text color would match the color of a `primary` button. If the label color is to remain the same, then I guess the text color should be changed to black.
2. The text for `color="orange"` should be visible.
3. The text for `color="green"` should be visible.
4. The text for `color="yellow"` should have more contrast.

In high-contrast mode:
1. The text for `color="orange"` should be visible.
2. The text for `color="green"` should be visible.
3. The text for `color="yellow"` should be visible.
4. I'm not sure what the expected behavior _should_ be, but I'm guessing they shouldn't all be white and only one yellow and one black.

### Priorities and help requested:

Are you willing to submit a PR to fix? Not at the moment.

Requested priority: Normal

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by TanelVari**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #15538

#### Description of changes

Updated color scheme to match latest from design team.
Fixed left and right padding for circular Label.

### CODE REVIEW

**Comment by TanelVari** [comment]
image
image
image

**Review by ling1726 — APPROVED** [review]
The changes look fine to me, just not sure whether these kinds of changes should be categorized as fixes or breaking changes

File: packages/fluentui/react-northstar/src/themes/teams-dark/components/Label/labelVariables.ts [hunk 1]
```diff
@@ -6,11 +6,41 @@ export const labelVariables = (siteVars: SiteVariablesPrepared): Partial<LabelVa
...
+          foreground: siteVars.colorScheme.red.foreground1,
+          background: siteVars.colorScheme.red.background,
+        },
+        green: {
+          foreground: siteVars.colorScheme.green.foreground3,
+          background: siteVars.colorScheme.green.background,
+        },
+        yellow: {
+          foreground: siteVars.colorScheme.yellow.foreground3,
+          background: siteVars.colorScheme.yellow.background,
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/themes/teams-dark/components/Label/labelVariables.ts:43]: Can we please remove `colorScheme` magic there and perform a small refactor?

`labelVariables.ts`

```tsx
yellowForeground: siteVars.colorScheme.yellow.foreground3,
yellowBackground: siteVars.colorScheme.yellow.background,
```

`labelStyles.ts`

```
...p.color === 'yellow' && {
  color: v.yellowForeground,
  backgroundColor: v.yellowBackground,
}
```

Please contact me offline if something is unclear

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Avatar-mount_base.html">937</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Avatar-mount.html">943</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/BaseButtonCompat-mount_base.html">1034</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/BaseButtonCompat-mount.html">1046</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Breadcrumb-mount_base.html">42467</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Breadcrumb-mount.html">46910</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Checkbox-mount_base.html">1546</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Checkbox-mount.html">1583</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/CheckboxBase-mount_base.html">1325</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/CheckboxBase-mount.html">1327</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ChoiceGroup-mount_base.html">4925</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ChoiceGroup-mount.html">4953</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ComboBox-mount_base.html">964</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ComboBox-mount.html">1057</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/CommandBar-mount_base.html">11714</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/CommandBar-mount.html">11102</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ContextualMenu-mount_base.html">7163</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ContextualMenu-mount.html">7092</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DefaultButtonCompat-mount_base.html">1147</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DefaultButtonCompat-mount.html">1192</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DetailsRow-mount_base.html">3783</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DetailsRow-mount.html">3770</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DetailsRowFast-mount_base.html">3701</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DetailsRowFast-mount.html">3705</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DetailsRowNoStyles-mount_base.html">4010</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DetailsRowNoStyles-mount.html">3566</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Dialog-mount_base.html">1522</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Dialog-mount.html">1529</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DocumentCardTitle-mount_base.html">1781</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/DocumentCardTitle-mount.html">1789</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Dropdown-mount_base.html">3484</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Dropdown-mount.html">3442</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/FocusTrapZone-mount_base.html">1817</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/FocusTrapZone-mount.html">1846</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/FocusZone-mount_base.html">1810</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/FocusZone-mount.html">1843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/IconButtonCompat-mount_base.html">2001</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/IconButtonCompat-mount.html">1852</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Label-mount_base.html">366</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Label-mount.html">372</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Layer-mount_base.html">1979</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Layer-mount.html">1951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Link-mount_base.html">523</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Link-mount.html">510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/MenuButtonCompat-mount_base.html">1533</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/MenuButtonCompat-mount.html">1646</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/MessageBar-mount_base.html">2052</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/MessageBar-mount.html">2036</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Nav-mount_base.html">3705</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Nav-mount.html">3597</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/OverflowSet-mount_base.html">1136</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/OverflowSet-mount.html">1101</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Panel-mount_base.html">1554</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Panel-mount.html">1641</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Persona-mount_base.html">910</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Persona-mount.html">900</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Pivot-mount_base.html">1494</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Pivot-mount.html">1473</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/PrimaryButtonCompat-mount_base.html">1326</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/PrimaryButtonCompat-mount.html">1328</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Rating-mount_base.html">7883</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Rating-mount.html">8042</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/SearchBox-mount_base.html">1335</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/SearchBox-mount.html">1383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Shimmer-mount_base.html">2643</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Shimmer-mount.html">2642</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Slider-mount_base.html">2041</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Slider-mount.html">1975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/SpinButton-mount_base.html">5598</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/SpinButton-mount.html">5504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Spinner-mount_base.html">472</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Spinner-mount.html">453</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/SplitButtonCompat-mount_base.html">3494</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/SplitButtonCompat-mount.html">3518</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Stack-mount_base.html">557</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Stack-mount.html">553</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1651</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/StackWithIntrinsicChildren-mount.html">1663</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/StackWithTextChildren-mount_base.html">5133</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/StackWithTextChildren-mount.html">5210</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/SwatchColorPicker-mount_base.html">11535</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/SwatchColorPicker-mount.html">11658</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Tabs-mount_base.html">1455</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Tabs-mount.html">1402</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/TagPicker-mount_base.html">2843</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/TagPicker-mount.html">2810</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/TeachingBubble-mount_base.html">12894</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/TeachingBubble-mount.html">13212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Text-mount_base.html">462</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Text-mount.html">463</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/TextField-mount_base.html">1490</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/TextField-mount.html">1498</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ThemeProvider-mount_base.html">2269</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ThemeProvider-mount.html">2326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ThemeProvider-virtual-rerender_base.html">683</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/ThemeProvider-virtual-rerender.html">697</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Toggle-mount_base.html">845</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/Toggle-mount.html">853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/button-mount_base.html">707</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/button-mount.html">734</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/buttonNative-mount_base.html">114</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test/buttonNative-mount.html">121</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🎯 | Avatar.Fluent | [0.54](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Avatar.Fluent.html) | 0.57 | 0.95:1 | 2000 | 1073
🦄 | Button.Fluent | [0.14](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Button.Fluent.html) | 0.23 | 0.61:1 | 5000 | 723
🔧 | Checkbox.Fluent | [0.74](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Checkbox.Fluent.html) | 0.41 | 1.8:1 | 1000 | 737
🎯 | Dialog.Fluent | [0.19](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Dialog.Fluent.html) | 0.25 | 0.76:1 | 5000 | 935
🔧 | Dropdown.Fluent | [3.61](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Dropdown.Fluent.html) | 0.46 | 7.85:1 | 1000 | 3606
🔧 | Icon.Fluent | [0.17](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Icon.Fluent.html) | 0.07 | 2.43:1 | 5000 | 856
🦄 | Image.Fluent | [0.1](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Image.Fluent.html) | 0.15 | 0.67:1 | 5000 | 482
🔧 | Slider.Fluent | [1.91](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Slider.Fluent.html) | 0.51 | 3.75:1 | 1000 | 1914
🔧 | Text.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.67:1 | 5000 | 416
🦄 | Tooltip.Fluent | [0.13](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Tooltip.Fluent.html) | 0.98 | 0.13:1 | 5000 | 645
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ButtonMinimalPerf.default | [237](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonMinimalPerf.default.html) | [204](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.16:1
CarouselMinimalPerf.default | [568](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/CarouselMinimalPerf.default.html) | [492](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.15:1
DropdownMinimalPerf.default | [3505](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DropdownMinimalPerf.default.html) | [3129](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.12:1
HeaderMinimalPerf.default | [492](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/HeaderMinimalPerf.default.html) | [445](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.11:1
ProviderMinimalPerf.default | [1253](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ProviderMinimalPerf.default.html) | [1143](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.1:1
TextMinimalPerf.default | [483](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TextMinimalPerf.default.html) | [439](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.1:1
FlexMinimalPerf.default | [371](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/FlexMinimalPerf.default.html) | [346](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.07:1
TableMinimalPerf.default | [528](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TableMinimalPerf.default.html) | [494](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.07:1
ChatDuplicateMessagesPerf.default | [516](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [488](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.06:1
DropdownManyItemsPerf.default | [942](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DropdownManyItemsPerf.default.html) | [888](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.06:1
PopupMinimalPerf.default | [853](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/PopupMinimalPerf.default.html) | [801](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.06:1
RefMinimalPerf.default | [284](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/RefMinimalPerf.default.html) | [267](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.06:1
FormMinimalPerf.default | [524](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/FormMinimalPerf.default.html) | [498](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.05:1
ItemLayoutMinimalPerf.default | [1535](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1466](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.05:1
MenuButtonMinimalPerf.default | [1901](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1810](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.05:1
SkeletonMinimalPerf.default | [535](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/SkeletonMinimalPerf.default.html) | [511](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.05:1
StatusMinimalPerf.default | [907](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/StatusMinimalPerf.default.html) | [862](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.05:1
AvatarMinimalPerf.default | [580](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AvatarMinimalPerf.default.html) | [560](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.04:1
ButtonUseCssNestingPerf.default | [1331](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1283](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 1.04:1
LabelMinimalPerf.default | [531](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/LabelMinimalPerf.default.html) | [513](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.04:1
PortalMinimalPerf.default | [191](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/PortalMinimalPerf.default.html) | [183](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.04:1
SliderMinimalPerf.default | [1893](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/SliderMinimalPerf.default.html) | [1824](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.04:1
Avatar.Fluent | [1073](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Avatar.Fluent.html) | [1028](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Avatar.Fluent_base.html) | 1.04:1
Button.Fluent | [723](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Button.Fluent.html) | [695](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Button.Fluent_base.html) | 1.04:1
Icon.Fluent | [856](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Icon.Fluent.html) | [820](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Icon.Fluent_base.html) | 1.04:1
ButtonOverridesMissPerf.default | [2089](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [2030](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.03:1
CardMinimalPerf.default | [686](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/CardMinimalPerf.default.html) | [668](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.03:1
HeaderSlotsPerf.default | [950](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/HeaderSlotsPerf.default.html) | [922](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [1119](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1084](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
VideoMinimalPerf.default | [768](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/VideoMinimalPerf.default.html) | [745](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.03:1
Dialog.Fluent | [935](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Dialog.Fluent.html) | [912](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Dialog.Fluent_base.html) | 1.03:1
AccordionMinimalPerf.default | [200](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AccordionMinimalPerf.default.html) | [196](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.02:1
BoxMinimalPerf.default | [440](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/BoxMinimalPerf.default.html) | [430](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
ButtonSlotsPerf.default | [716](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonSlotsPerf.default.html) | [699](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.02:1
ChatWithPopoverPerf.default | [585](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ChatWithPopoverPerf.default.html) | [572](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.02:1
CheckboxMinimalPerf.default | [3252](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/CheckboxMinimalPerf.default.html) | [3192](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.02:1
LayoutMinimalPerf.default | [512](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/LayoutMinimalPerf.default.html) | [503](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [863](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/LoaderMinimalPerf.default.html) | [846](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [4427](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4341](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
TreeMinimalPerf.default | [957](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TreeMinimalPerf.default.html) | [935](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.02:1
AttachmentSlotsPerf.default | [1396](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1378](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.01:1
ChatMinimalPerf.default | [770](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ChatMinimalPerf.default.html) | [762](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [61871](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DatepickerMinimalPerf.default.html) | [61205](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
EmbedMinimalPerf.default | [4842](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/EmbedMinimalPerf.default.html) | [4801](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.01:1
ListMinimalPerf.default | [613](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ListMinimalPerf.default.html) | [604](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.01:1
ListWith60ListItems.default | [1174](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ListWith60ListItems.default.html) | [1157](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.01:1
MenuMinimalPerf.default | [1056](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/MenuMinimalPerf.default.html) | [1047](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
CustomToolbarPrototype.default | [4725](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/CustomToolbarPrototype.default.html) | [4691](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.01:1
InputMinimalPerf.default | [1544](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/InputMinimalPerf.default.html) | [1541](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/InputMinimalPerf.default_base.html) | 1:1
ReactionMinimalPerf.default | [488](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ReactionMinimalPerf.default.html) | [488](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1:1
SegmentMinimalPerf.default | [447](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/SegmentMinimalPerf.default.html) | [445](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1:1
TextAreaMinimalPerf.default | [606](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TextAreaMinimalPerf.default.html) | [608](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1:1
TooltipMinimalPerf.default | [894](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TooltipMinimalPerf.default.html) | [893](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
Checkbox.Fluent | [737](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Checkbox.Fluent.html) | [735](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Checkbox.Fluent_base.html) | 1:1
ButtonUseCssPerf.default | [1017](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonUseCssPerf.default.html) | [1025](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 0.99:1
DialogMinimalPerf.default | [926](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DialogMinimalPerf.default.html) | [937](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.99:1
DividerMinimalPerf.default | [461](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DividerMinimalPerf.default.html) | [466](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [2321](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [2342](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
RadioGroupMinimalPerf.default | [506](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [510](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.99:1
IconMinimalPerf.default | [822](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/IconMinimalPerf.default.html) | [832](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.99:1
Slider.Fluent | [1914](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Slider.Fluent.html) | [1934](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Slider.Fluent_base.html) | 0.99:1
Tooltip.Fluent | [645](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Tooltip.Fluent.html) | [651](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Tooltip.Fluent_base.html) | 0.99:1
AttachmentMinimalPerf.default | [205](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AttachmentMinimalPerf.default.html) | [210](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.98:1
ListNestedPerf.default | [710](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ListNestedPerf.default.html) | [727](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ListNestedPerf.default_base.html) | 0.98:1
TableManyItemsPerf.default | [2551](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TableManyItemsPerf.default.html) | [2596](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TableManyItemsPerf.default_base.html) | 0.98:1
Dropdown.Fluent | [3606](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Dropdown.Fluent.html) | [3698](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Dropdown.Fluent_base.html) | 0.98:1
Image.Fluent | [482](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Image.Fluent.html) | [493](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Image.Fluent_base.html) | 0.98:1
AlertMinimalPerf.default | [378](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AlertMinimalPerf.default.html) | [391](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.97:1
ListCommonPerf.default | [809](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ListCommonPerf.default.html) | [834](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ListCommonPerf.default_base.html) | 0.97:1
AnimationMinimalPerf.default | [468](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AnimationMinimalPerf.default.html) | [486](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.96:1
Text.Fluent | [416](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Text.Fluent.html) | [432](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/Text.Fluent_base.html) | 0.96:1
GridMinimalPerf.default | [406](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/GridMinimalPerf.default.html) | [429](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.95:1
TreeWith60ListItems.default | [257](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TreeWith60ListItems.default.html) | [270](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.95:1
ImageMinimalPerf.default | [464](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ImageMinimalPerf.default.html) | [503](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16160/merge/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.92:1

</details><div id="perfComment9423"/>

File: packages/fluentui/react-northstar/src/themes/teams/colors.ts [hunk 2]
```diff
@@ -456,6 +462,7 @@ export const colorScheme: ColorSchemeMapping<ColorScheme, TeamsColorNames> = {
     foreground: colors.yellow[300],
     foreground1: colors.grey[800],
     foreground2: colors.white,
+    foreground3: colors.grey[750],
```
Comment (codepretty) [inline packages/fluentui/react-northstar/src/themes/teams/colors.ts:465]: Did you verify with Kay/Daisy that we should be adding values into the color schemes?

**Review by layershifter — APPROVED** [review]

File: packages/fluentui/react-northstar/src/themes/teams/components/Label/labelVariables.ts [hunk 3]
```diff
@@ -1,43 +1,68 @@
...
-
 export interface LabelVariables {
-  colorScheme: LabelColorSchemeMapping;
   circularRadius: string;
   iconSize: string;
   padding: string;
   startPaddingLeft: string;
   endPaddingRight: string;
   height: string;
+
```
Comment (assuncaocharles) [inline packages/fluentui/react-northstar/src/themes/teams/components/Label/labelVariables.ts:11]: nit
```suggestion
```

**Review by assuncaocharles — APPROVED** [review]

File: packages/fluentui/react-northstar/src/themes/teams/components/Label/labelVariables.ts (hunk 3 above)
Comment (TanelVari) [reply packages/fluentui/react-northstar/src/themes/teams/components/Label/labelVariables.ts:11]: fxd

File: packages/fluentui/react-northstar/src/themes/teams/colors.ts (hunk 2 above)
Comment (TanelVari) [reply packages/fluentui/react-northstar/src/themes/teams/colors.ts:472]: yes

File: packages/fluentui/react-northstar/src/themes/teams/components/Label/labelStyles.ts [hunk 4]
```diff
@@ -35,9 +66,17 @@ export const labelStyles: ComponentSlotStylesPrepared<LabelStylesProps, LabelVar
       ...(hasStartElement && {
         marginLeft: pxToRem(3),
       }),
+      ...(!hasStartElement &&
+        p.circular && {
+          marginLeft: pxToRem(4),
+        }),
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/themes/teams/components/Label/labelStyles.ts:72]: Could you please summarize the margin changes in the changelog ? It would be beneficial in the future for adoption notes

Comment (TanelVari) [reply packages/fluentui/react-northstar/src/themes/teams/components/Label/labelStyles.ts:72]: WDYM by summarizing?

Comment (ling1726) [reply packages/fluentui/react-northstar/src/themes/teams/components/Label/labelStyles.ts:72]: The PR description currently only mentions fixing color schemes. Unless you looked at the code in PR, you would not expect spacing changes

Comment (ling1726) [reply packages/fluentui/react-northstar/src/themes/teams/components/Label/labelStyles.ts:72]: Perhaps something like

`Added left padding for circular label`

Comment (TanelVari) [reply packages/fluentui/react-northstar/src/themes/teams/components/Label/labelStyles.ts:72]: Dang. I did that but it was lost somewhere during rebasing I think. Will fix.

Comment (ling1726) [reply packages/fluentui/react-northstar/src/themes/teams/components/Label/labelStyles.ts:72]: To be clear, I'm talking about the PR description, not the changelog. We can accept simple change statements in the log. But when reading the PR description in github we should see more details on the change without having to scan the code as much as possible

Comment (TanelVari) [reply packages/fluentui/react-northstar/src/themes/teams/components/Label/labelStyles.ts:72]: Thank you. Could you be more specific next time when talking about changelog though.
