### PR TITLE
fix(react-motion): improve element validation to work with React 19

### LINKED ISSUE #33404: [Bug]:  @fluentui/react-motion: Invalid child element.
### Component

Drawer

### Package version

^9.56.3

### React version

19.0.0-rc-66855b96-20241106

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.00GHz
    Memory: 2.34 GB / 15.65 GB
  Browsers:
    Edge: Chromium (130.0.2849.52)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @fluentui/react-components: ^9.56.3 => 9.56.3
    @fluentui/react-icons: ^2.0.266 => 2.0.266
    @types/react: ^18.3.12 => 18.3.12
    @types/react-dom: ^18.3.1 => 18.3.1
    react: 19.0.0-rc-66855b96-20241106 => 19.0.0-rc-66855b96-20241106
    react-dom: 19.0.0-rc-66855b96-20241106 => 19.0.0-rc-66855b96-20241106
```

### Current Behavior

**Crashing application**
- when im trying to use Drawer in next.js 15. it's saying
`Error: @fluentui/react-motion: Invalid child element.
Motion factories require a single child element to be passed. That element element should support ref forwarding i.e. it should be either an intrinsic element (e.g. div) or a component that uses React.forwardRef().`

Image

### Expected Behavior

it's should work.

### Reproduction

don't have the link

### Steps to reproduce

Install next.js 15.
Use the fluent ui 9 latest version
and try to use the drawer

### Are you reporting an Accessibility issue?

None

### Suggested severity

Urgent - No workaround and Products/sites are affected

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by layershifter**
## New Behavior

- Improves validation to work properly with React 19: `getChildElement()` was refactored to be a hook `useChildElement()`, validation now happens in `useEffect`
- Avoids accessing `.ref` (see #31534)

## Related Issue(s)

Fixes #33404.

### CODE REVIEW

File: packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts [hunk 1]
```diff
@@ -223,11 +221,20 @@ export function createPresenceComponent<MotionParams extends Record<string, Moti
         },
         // Excluding `isFirstMount` from deps to prevent re-triggering the animation on subsequent renders
         // eslint-disable-next-line react-hooks/exhaustive-deps
-        [animateAtoms, handleRef, isReducedMotion, handleMotionFinish, handleMotionStart, handleMotionCancel, visible],
+        [
+          animateAtoms,
+          childRef,
```
Comment (spmonahan) [inline packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts:226]: Should this be `childRef.current`? `childRef` should never change but `.current` might?

Comment (layershifter) [reply packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts:226]: No, it should not. The only dependency that triggers changes is `visible`.

File: packages/react-components/react-motion/library/src/utils/useChildElement.ts [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+  } catch {
+    /* empty */
+  }
+
+  throw new Error(
+    [
+      '@fluentui/react-motion: Invalid child element.',
+      '\n',
+      'Motion factories require a single child element to be passed. ',
+      'That element element should support ref forwarding i.e. it should be either an intrinsic element (e.g. div) or a component that uses React.forwardRef().',
```
Comment (robertpenner) [inline packages/react-components/react-motion/library/src/utils/useChildElement.ts:59]: Let's DRY up the error messages into a constant.

File: packages/react-components/react-motion/library/src/utils/useChildElement.ts [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+ */
+function getRefFromReactElement<T>(element: React.ReactElement): React.Ref<T> | undefined {
+  if (IS_REACT_19) {
+    return element.props.ref;
+  }
+
+  return (element as React.ReactElement & { ref: React.Ref<T> | undefined }).ref;
+}
+
+export function useChildElement(
```
[the remark this answers is not in the document]
Comment (layershifter) [reply packages/react-components/react-motion/library/src/utils/useChildElement.ts:29]: Added JSDoc 👍

**Review by robertpenner — APPROVED** [review]
