### PR TITLE
fix(react-combobox): Wrong positioning of the listbox when there's not enough space

### LINKED ISSUE #29050: [Bug]: Cannot select last item in full-width combobox/dropdown
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 8.06 GB / 31.85 GB
  Browsers:
    Chrome: 116.0.5845.141
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @fluentui/react: 8.110.11 => 8.110.11
    @fluentui/react-components: 9.30.1 => 9.30.1
    @fluentui/react-migration-v8-v9: 9.3.11 => 9.3.11
    @fluentui/react-portal-compat: 9.0.72 => 9.0.72
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/heuristic-moser-vttv3x?file=/example.tsx

## Actual Behavior
1. Have a combobox/dropdown with the following properties:
   - Full width
   - Not at the top of the page
   - More items than fit on the screen
2. Open the combobox
3. Scroll to the bottom, and select the last item
4. Instead of selecting the last item, the list scrolls up a little

The problem seems to be that it wants to open the list to the right side of the combobox but can't.
If you remove the width: 100%, the list opens to the right and has a certain height.
If you now keep the width, but remove the autoSize, it will have that exact same height, and cause a scrollbar in the page.
How much the list moves down because of the width 100% is close to how much the list scrolls when trying to select the last item.

## Expected Behavior
Be able to select the last item in a longer full-width combobox.

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ValentinaKozlova**
## Previous Behavior
The listbox is shown from the right or left side when there's no enough space

image

## New Behavior
The listbox is not changing its position

image

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/Avatar-mount_base.html">614</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/Avatar-mount.html">647</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/Button-mount_base.html">316</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/Button-mount.html">305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/Field-mount_base.html">1099</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/Field-mount.html">1127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/FluentProvider-mount_base.html">722</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/FluentProvider-mount.html">730</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/FluentProviderWithTheme-mount_base.html">100</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/FluentProviderWithTheme-mount.html">100</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">38</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">35</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">89</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">90</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/MakeStyles-mount_base.html">873</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/MakeStyles-mount.html">884</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/Persona-mount_base.html">1772</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/Persona-mount.html">1713</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/SpinButton-mount_base.html">1421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/SpinButton-mount.html">1425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/SwatchPicker-mount_base.html">1649</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31891/perf-test-react-components/SwatchPicker-mount.html">1662</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports | Baseline (minified/GZIP) | PR    | Change     |
| :---------------- | -----------------------: | ----: | ---------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr> | `103.571 kB`<br />`33.978 kB` | `103.501 kB`<br />`33.954 kB` | `-70 B` <br />`-24 B` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr> | `104.157 kB`<br />`33.888 kB` | `104.087 kB`<br />`33.865 kB` | `-70 B` <br />`-23 B` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ReactComponents.fixture.js'>react-components: entire library</abbr> | `1.094 MB`<br />`270.794 kB` | `1.094 MB`<br />`270.757 kB` | `-70 B` <br />`-37 B` |
| <samp>react-timepicker-compat</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr> | `106.559 kB`<br />`35.517 kB` | `106.489 kB`<br />`35.49 kB` | `-70 B` <br />`-27 B` |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `69.141 kB`<br />`20.157 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `211.741 kB`<br />`60.957 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `44.442 kB`<br />`14.607 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> | `8.39 kB`<br />`2.64 kB` |
| <samp>react-tag-picker</samp> <br /> <abbr title='bundle-size/Package.fixture.js'>@fluentui/react-tag-picker - package</abbr> | `181.187 kB`<br />`54.484 kB` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8bb37742a9b8e7e134aa4d926b2112a1f5f1deed'>8bb37742a9b8e7e134aa4d926b2112a1f5f1deed</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-components/react-combobox/library/src/utils/useComboboxPositioning.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { PositioningShorthandValue, resolvePositioningShorthand, usePositioning } from '@fluentui/react-positioning';
+import { resolvePositioningShorthand, usePositioning } from '@fluentui/react-positioning';
```
Comment (fabricteam) [inline packages/react-components/react-combobox/library/src/utils/useComboboxPositioning.ts:1]: ## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=31891&commitId=d9695a22e1c086b017e17595589ea1bf3177312d&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar Converged</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.badgeMask - RTL.normal.chromium.png|3| Changed|

</details>


  <details><summary><b>Card Converged - Selectable</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Card Converged - Selectable.appearance selectable - Subtle - High Contrast.click.chromium.png|0| Added|
|Card Converged - Selectable.appearance selectable - Subtle - High Contrast.hover.chromium.png|0| Added|
|Card Converged - Selectable.appearance selectable - Subtle - High Contrast.normal.chromium.png|0| Added|
|Card Converged - Selectable.appearance selectable - Subtle - High Contrast.selected.chromium.png|0| Added|

</details>


  <details><summary><b>SwatchPicker Converged</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|SwatchPicker Converged.spacing.default.chromium.png|0| Removed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

File: packages/react-components/react-combobox/library/src/utils/useComboboxPositioning.ts [hunk 2]
```diff
@@ -10,15 +10,11 @@ export function useComboboxPositioning(props: ComboboxBaseProps): [
 ] {
   const { positioning } = props;
 
-  // Set a default set of fallback positions to try if the dropdown does not fit on screen
-  const fallbackPositions: PositioningShorthandValue[] = ['above', 'after', 'after-top', 'before', 'before-top'];
```
Comment (smhigley) [inline packages/react-components/react-combobox/library/src/utils/useComboboxPositioning.ts:14]: I think changing the fallbackPositions would need to be a larger conversation, since it'd be a breaking change. The current `fallbackPositions` values matches what we have in v8, which also allows the combobox/dropdown popup to render to the left or right of the trigger.

If we do change this, I think it should include `above` as a fallback to allow the popup to position above/below based on screen size. In general, I'm a bit leery of this change though, since it could make selection on short screens (and especially with zoom) a lot harder.

Teams can also currently override this through the `positioning` prop already.

**Review by smhigley — CHANGES_REQUESTED** [review]

File: packages/react-components/react-combobox/library/src/utils/useComboboxPositioning.ts (hunk 2 above)
Comment (layershifter) [reply packages/react-components/react-combobox/library/src/utils/useComboboxPositioning.ts:14]: > Teams can also currently override this through the positioning prop already.

@smhigley FYI this is _partially_ true: it works in JS land, but we don't expose `fallbackPositions` in `positioning` prop - it will cause a TS error:

image

Comment (ValentinaKozlova) [reply packages/react-components/react-combobox/library/src/utils/useComboboxPositioning.ts]: I exported `fallbackPositions` prop. Hope it's a right fix

File: packages/react-components/react-combobox/stories/src/Dropdown/index.stories.tsx [hunk 3]
```diff
@@ -18,6 +18,7 @@ export { Disabled } from './DropdownDisabled.stories';
 export { TruncatedValue } from './DropdownTruncation.stories';
 export { ActiveOptionChange } from './DropdownActiveOptionChange.stories';
 export { ControllingOpenAndClose } from './DropdownControllingOpenAndClose.stories';
+export { DropdownFallbackPositions } from './DropdownFallbackPositions.stories';
```
Comment (layershifter) [inline packages/react-components/react-combobox/stories/src/Dropdown/index.stories.tsx:21]: @ValentinaKozlova let's add docs there instead https://react.fluentui.dev/?path=/docs/concepts-developer-positioning-components--default as this page documents all positioning options

Comment (ValentinaKozlova) [reply packages/react-components/react-combobox/stories/src/Dropdown/index.stories.tsx:21]: fixed :)

**Review by smhigley — APPROVED** [review]

**Review by layershifter — APPROVED** [review]
