### PR TITLE
fix(TreeTitle): only prevents default for selectable tree title

### LINKED ISSUE #14883: Fluent UI doc site - User is not able navigate into the component when is filtered
Repro steps:

1. Navigate to the Fluent UI doc page
http://localhost:8080/
2. Press TAB several times to get into the Search
3. find "button" component
4. press tab /// focus goes into filtered components
5. press enter key on filtered component

Actual: no action happen
Expected: user goes into the component (navigation happens), URL change to this component 

Environment:
curently tested from localhost (version 0.51.0):
Chrome Version 84.0.4147.89 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #14883
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

We are currently preventing default for the `TreeTitle` `keyDown` but this seems to be needed only for `space`  and it bugs the other cases for example the docs side bar on pressing enter. 
#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx [hunk 1]
```diff
@@ -120,7 +121,9 @@ export const TreeTitle: ComponentWithAs<'a', TreeTitleProps> & FluentComponentSt
     debugName: TreeTitle.displayName,
     actionHandlers: {
       performClick: e => {
-        e.preventDefault();
+        if (getCode(e) === SpacebarKey) {
```
Comment (assuncaocharles) [inline packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx:124]: We can't remove `SpaceKey` from `treeTitleBehavior` because it should work for selectable `Tree` and it seems only makes sense to `preventDefault` for space to avoid page scroll. :( I don't like it but I am out of ideas

Comment (layershifter) [reply packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx:124]: Let's fix instead `shouldPreventDefaultOnKeyDown` to respect `a` tag & <kbd>Space</kbd> combination

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx]: Done

File: packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts [hunk 2]
```diff
@@ -23,6 +23,23 @@ describe('shouldPreventDefaultOnKeyDown', () => {
     expect(shouldPreventDefaultOnKeyDown(textareaEvent)).toBe(false);
   });
 
+  it('ignores for anchor targets', () => {
+    const anchorEvent = new KeyboardEvent('keydown', { key: 'Enter' });
+
+    document.createElement('a').dispatchEvent(anchorEvent);
```
Comment (layershifter) [inline packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts:29]:
```suggestion
    const anchorEvent = new KeyboardEvent('keydown', { key: 'Enter' });
    document.createElement('a').dispatchEvent(anchorEvent);
```

File: packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts [hunk 3]
```diff
@@ -23,6 +23,23 @@ describe('shouldPreventDefaultOnKeyDown', () => {
...
+
+    expect(shouldPreventDefaultOnKeyDown(anchorEvent)).toBe(false);
+  });
+
+  it('ignores for anchor targets when key == Space', () => {
+    // 'Space' or 'Spacebar' doesn't work https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
+    const anchorEvent = new KeyboardEvent('keydown', { key: ' ' });
+
+    document.createElement('a').dispatchEvent(anchorEvent);
```
Comment (layershifter) [inline packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts:38]:
```suggestion
    const anchorEvent = new KeyboardEvent('keydown', { key: ' ' });
    document.createElement('a').dispatchEvent(anchorEvent);
```

File: packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts [hunk 4]
```diff
@@ -23,6 +23,23 @@ describe('shouldPreventDefaultOnKeyDown', () => {
     expect(shouldPreventDefaultOnKeyDown(textareaEvent)).toBe(false);
   });
 
+  it('ignores for anchor targets', () => {
```
Comment (layershifter) [inline packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts:26]:
```suggestion
  it('handles "Enter" for anchor targets', () => {
```

File: packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts [hunk 5]
```diff
@@ -23,6 +23,23 @@ describe('shouldPreventDefaultOnKeyDown', () => {
...
+    const anchorEvent = new KeyboardEvent('keydown', { key: 'Enter' });
+
+    document.createElement('a').dispatchEvent(anchorEvent);
+
+    expect(shouldPreventDefaultOnKeyDown(anchorEvent)).toBe(false);
+  });
+
+  it('ignores for anchor targets when key == Space', () => {
```
Comment (layershifter) [inline packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts:34]:
```suggestion
  it('ignores "Space" for anchor targets', () => {
```

File: packages/fluentui/react-northstar/src/utils/shouldPreventDefaultOnKeyDown.ts [hunk 6]
```diff
@@ -10,7 +10,10 @@ export function shouldPreventDefaultOnKeyDown(e: KeyboardEvent | React.KeyboardE
 
   const matchesByKey = code === SpacebarKey || code === EnterKey;
   const ignoredByTag =
-    target?.tagName === 'INPUT' || target?.tagName === 'TEXTAREA' || target?.isContentEditable === true;
+    target?.tagName === 'INPUT' ||
+    target?.tagName === 'TEXTAREA' ||
+    target?.isContentEditable === true ||
+    (target?.tagName === 'A' && code !== SpacebarKey);
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/utils/shouldPreventDefaultOnKeyDown.ts:16]: Let's restore this one and handle it earlier

```tsx
if (target?.tagName === 'A') {
  return code === SpacebarKey
}
```

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/utils/shouldPreventDefaultOnKeyDown.ts]: Done

**Review by layershifter — APPROVED** [review]
