### PR TITLE
fix(Link): Handle "tabIndex" from user's input

### LINKED ISSUE #26313: [Bug]: tabindex not propagated for Link control
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Same as CodeSandbox examples on Fluent v9 page
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/broken-snow-uybukv?file=/example.tsx

## Actual Behavior
Set tabIndex={-1} on Link. Rendered tabindex property on corresponding HTML element is 0.

## Expected Behavior
Rendered tabindex property should be -1.

The usage scenario is to hide the link from screen readers but show it to visual users. This is usually done by setting tabindex=-1 and aria-hidden=true.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

Microsoft Power Apps canvas apps

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by layershifter**
## Previous Behavior

```tsx
<Link tabIndex={-1} href="https://www.bing.com" />
```

⬇️⬇️⬇️

```html
<a href="https://www.bing.com" tabindex="0"></a>
```

💣 

## New Behavior

```tsx
<Link tabIndex={-1} href="https://www.bing.com" />
```

⬇️⬇️⬇️

```html
<a href="https://www.bing.com" tabindex="-1"></a>
```

User's input should always win over our defaults ✅ 

## Related Issue(s)

Fixes #26313

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                     |    Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                 Change |
| :------------------------------------------------------------------------------------ | --------------------------: | --------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr> | `12.285 kB`<br />`5.063 kB` | `12.306 kB`<br />`5.074 kB` | `21 B` <br />`11 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `59.888 kB`<br />`16.652 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `187.586 kB`<br />`52.65 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `34.379 kB`<br />`11.322 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `6.069 kB`<br />`2.053 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/86a28f6ebcc84819c695f12b841b9377736fb5f7'>86a28f6ebcc84819c695f12b841b9377736fb5f7</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/Avatar-mount_base.html">1582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/Avatar-mount.html">1590</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/Button-mount_base.html">1085</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/Button-mount.html">1127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/FluentProvider-mount_base.html">1916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/FluentProvider-mount.html">1889</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/FluentProviderWithTheme-mount_base.html">775</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/FluentProviderWithTheme-mount.html">787</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">695</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">714</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">765</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">735</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/InfoButton-mount_base.html">666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/InfoButton-mount.html">694</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/MakeStyles-mount_base.html">2299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/MakeStyles-mount.html">2322</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/Persona-mount_base.html">3540</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/Persona-mount.html">3597</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/SpinButton-mount_base.html">2979</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26456/perf-test-react-components/SpinButton-mount.html">3077</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

File: packages/react-components/react-link/src/components/Link/useLinkState.ts [hunk 1]
```diff
@@ -8,12 +8,12 @@ import type { LinkState } from './Link.types';
  */
 export const useLinkState_unstable = (state: LinkState): LinkState => {
   const { disabled, disabledFocusable } = state;
-  const { onClick, onKeyDown, role, type } = state.root;
+  const { onClick, onKeyDown, role, type, tabIndex } = state.root;
```
Comment (khmakoto) [inline packages/react-components/react-link/src/components/Link/useLinkState.ts:11]: _nit:_ Maintain alphabetical order

```suggestion
  const { onClick, onKeyDown, role, tabIndex, type} = state.root;
```

**Review by khmakoto — APPROVED** [review]
