### PR TITLE
fix(positioning): handle case when directionalHintFixed and alignTargetEdge are true

### LINKED ISSUE #20460: Callout component doesn't show scrollbar when callout content is too tall
### Environment Information

- **Package version(s)**: **8.39.0**
- **Browser and OS versions**: Edge, on both Windows and MacOS

### Please provide a reproduction of the bug in a codepen:

When a `Callout` content is very tall, exceeding the screen height, AND the following properties are set to `true`, the scrollbar is not showing. This is a regression, which is caused by this recent commit #19472.

```jsx
<Callout
      directionalHintFixed={true}
      alignTargetEdge={true}
 >
     // very tall content inside here
</Callout>   
```

Here's the codepen which repro the bug: https://codepen.io/campbellowen/pen/zYdPeqM

I found that if either of the two properties is `false`, then it works fine.

#### Actual behavior:

Scrollbar does NOT show inside the Callout.

#### Expected behavior:

Scrollbar should show inside the Callout.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Word Online, PowerPoint Online

### PR DESCRIPTION
**Pull request by smhigley**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #20460
- [x] Include a change request file using `$ yarn change`

#### Description of changes

There was a missed logic step when both `directionalHintFixed` and `alignTargetEdge` are true, when the callout wasn't forcing itself within bounds. Currently, if both are true, the positioning utility will fully adhere to the passed-in directional hint, and not switch the callout to a different edge, no matter the available space. It will still add the correct dimensions to force the callout on screen, no matter how tiny it needs to be.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/c704b87055127d4544a6fd8a5fb2343fba26bfbd'>c704b87055127d4544a6fd8a5fb2343fba26bfbd</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Avatar-mount_base.html">988</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Avatar-mount.html">951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/BaseButton-mount_base.html">970</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/BaseButton-mount.html">924</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Breadcrumb-mount_base.html">2638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Breadcrumb-mount.html">2657</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ButtonNext-mount_base.html">545</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ButtonNext-mount.html">544</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Checkbox-mount_base.html">1599</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Checkbox-mount.html">1548</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/CheckboxBase-mount_base.html">1345</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/CheckboxBase-mount.html">1356</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ChoiceGroup-mount_base.html">4892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ChoiceGroup-mount.html">4676</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ComboBox-mount_base.html">988</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ComboBox-mount.html">971</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/CommandBar-mount_base.html">10447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/CommandBar-mount.html">10627</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ContextualMenu-mount_base.html">6608</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ContextualMenu-mount.html">6488</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DefaultButton-mount_base.html">1182</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DefaultButton-mount.html">1179</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DetailsRow-mount_base.html">3911</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DetailsRow-mount.html">3838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DetailsRowFast-mount_base.html">3838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DetailsRowFast-mount.html">3783</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DetailsRowNoStyles-mount_base.html">3687</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DetailsRowNoStyles-mount.html">3736</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Dialog-mount_base.html">2634</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Dialog-mount.html">2652</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DocumentCardTitle-mount_base.html">164</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/DocumentCardTitle-mount.html">179</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Dropdown-mount_base.html">3297</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Dropdown-mount.html">3311</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FluentProviderNext-mount_base.html">3944</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FluentProviderNext-mount.html">3995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FluentProviderWithTheme-mount_base.html">241</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FluentProviderWithTheme-mount.html">216</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">98</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FluentProviderWithTheme-virtual-rerender.html">90</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">262</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">279</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FocusTrapZone-mount_base.html">1904</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FocusTrapZone-mount.html">1875</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FocusZone-mount_base.html">1904</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/FocusZone-mount.html">1916</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/IconButton-mount_base.html">1866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/IconButton-mount.html">1841</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Label-mount_base.html">371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Label-mount.html">380</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Layer-mount_base.html">3086</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Layer-mount.html">3082</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Link-mount_base.html">483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Link-mount.html">490</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/MakeStyles-mount_base.html">1849</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/MakeStyles-mount.html">1923</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/MenuButton-mount_base.html">1541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/MenuButton-mount.html">1584</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/MessageBar-mount_base.html">2041</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/MessageBar-mount.html">2035</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Nav-mount_base.html">3453</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Nav-mount.html">3471</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/OverflowSet-mount_base.html">1146</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/OverflowSet-mount.html">1158</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Panel-mount_base.html">2618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Panel-mount.html">2535</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Persona-mount_base.html">886</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Persona-mount.html">867</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Pivot-mount_base.html">1422</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Pivot-mount.html">1449</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/PrimaryButton-mount_base.html">1339</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/PrimaryButton-mount.html">1333</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Rating-mount_base.html">7877</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Rating-mount.html">7925</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/SearchBox-mount_base.html">1330</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/SearchBox-mount.html">1375</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Shimmer-mount_base.html">2590</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Shimmer-mount.html">2533</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Slider-mount_base.html">1965</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Slider-mount.html">2024</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/SpinButton-mount_base.html">5211</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/SpinButton-mount.html">5047</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Spinner-mount_base.html">455</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Spinner-mount.html">446</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/SplitButton-mount_base.html">3281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/SplitButton-mount.html">3267</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Stack-mount_base.html">512</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Stack-mount.html">534</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/StackWithIntrinsicChildren-mount_base.html">1690</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/StackWithIntrinsicChildren-mount.html">1764</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/StackWithTextChildren-mount_base.html">4668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/StackWithTextChildren-mount.html">4729</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/SwatchColorPicker-mount_base.html">10580</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/SwatchColorPicker-mount.html">10767</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/TagPicker-mount_base.html">2677</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/TagPicker-mount.html">2689</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/TeachingBubble-mount_base.html">13299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/TeachingBubble-mount.html">13250</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Text-mount_base.html">448</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Text-mount.html">441</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/TextField-mount_base.html">1473</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/TextField-mount.html">1391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ThemeProvider-mount_base.html">1218</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ThemeProvider-mount.html">1188</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ThemeProvider-virtual-rerender_base.html">619</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ThemeProvider-virtual-rerender.html">647</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1947</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1940</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Toggle-mount_base.html">833</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/Toggle-mount.html">860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/buttonNative-mount_base.html">136</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test/buttonNative-mount.html">130</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AttachmentMinimalPerf.default | [173](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AttachmentMinimalPerf.default.html) | [155](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.12:1
TextMinimalPerf.default | [373](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TextMinimalPerf.default.html) | [337](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.11:1
AlertMinimalPerf.default | [295](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AlertMinimalPerf.default.html) | [268](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.1:1
AvatarMinimalPerf.default | [207](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AvatarMinimalPerf.default.html) | [193](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.07:1
DividerMinimalPerf.default | [375](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DividerMinimalPerf.default.html) | [352](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.07:1
ChatWithPopoverPerf.default | [408](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ChatWithPopoverPerf.default.html) | [387](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.05:1
LayoutMinimalPerf.default | [378](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/LayoutMinimalPerf.default.html) | [362](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
PopupMinimalPerf.default | [600](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/PopupMinimalPerf.default.html) | [576](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.04:1
TableMinimalPerf.default | [423](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TableMinimalPerf.default.html) | [408](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.04:1
TreeMinimalPerf.default | [829](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TreeMinimalPerf.default.html) | [799](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [565](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ButtonSlotsPerf.default.html) | [550](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
CarouselMinimalPerf.default | [480](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/CarouselMinimalPerf.default.html) | [468](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.03:1
ReactionMinimalPerf.default | [385](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ReactionMinimalPerf.default.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [959](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ToolbarMinimalPerf.default.html) | [931](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
BoxMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/BoxMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
ButtonMinimalPerf.default | [177](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ButtonMinimalPerf.default.html) | [173](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.02:1
HeaderMinimalPerf.default | [373](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/HeaderMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.02:1
InputMinimalPerf.default | [1332](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/InputMinimalPerf.default.html) | [1311](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [524](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ListMinimalPerf.default.html) | [513](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
RefMinimalPerf.default | [250](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/RefMinimalPerf.default.html) | [245](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.02:1
SegmentMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/SegmentMinimalPerf.default.html) | [343](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [1949](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TableManyItemsPerf.default.html) | [1916](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [1067](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TooltipMinimalPerf.default.html) | [1043](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
AttachmentSlotsPerf.default | [1082](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1067](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.01:1
CardMinimalPerf.default | [560](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/CardMinimalPerf.default.html) | [552](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.01:1
ChatDuplicateMessagesPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [301](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5597](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5565](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [3247](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DropdownMinimalPerf.default.html) | [3223](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
FlexMinimalPerf.default | [292](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/FlexMinimalPerf.default.html) | [289](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [717](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/LoaderMinimalPerf.default.html) | [707](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
RosterPerf.default | [1219](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/RosterPerf.default.html) | [1205](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/RosterPerf.default_base.html) | 1.01:1
PortalMinimalPerf.default | [187](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/PortalMinimalPerf.default.html) | [185](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.01:1
AnimationMinimalPerf.default | [423](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AnimationMinimalPerf.default.html) | [421](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2841](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2841](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
DialogMinimalPerf.default | [756](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DialogMinimalPerf.default.html) | [756](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
DropdownManyItemsPerf.default | [716](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DropdownManyItemsPerf.default.html) | [716](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1:1
HeaderSlotsPerf.default | [748](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/HeaderSlotsPerf.default.html) | [748](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1:1
ListCommonPerf.default | [644](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ListCommonPerf.default.html) | [643](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ListCommonPerf.default_base.html) | 1:1
ListNestedPerf.default | [556](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ListNestedPerf.default.html) | [558](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ListNestedPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1667](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1666](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [1139](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ProviderMinimalPerf.default.html) | [1134](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1761](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/SliderMinimalPerf.default.html) | [1759](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [669](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/StatusMinimalPerf.default.html) | [671](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [4228](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/CustomToolbarPrototype.default.html) | [4225](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
ChatMinimalPerf.default | [658](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ChatMinimalPerf.default.html) | [665](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [4331](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/EmbedMinimalPerf.default.html) | [4360](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
LabelMinimalPerf.default | [389](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/LabelMinimalPerf.default.html) | [393](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.99:1
SplitButtonMinimalPerf.default | [4293](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4330](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 0.99:1
TextAreaMinimalPerf.default | [493](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TextAreaMinimalPerf.default.html) | [496](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.99:1
TreeWith60ListItems.default | [178](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TreeWith60ListItems.default.html) | [179](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.99:1
ButtonOverridesMissPerf.default | [1792](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1834](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.98:1
ImageMinimalPerf.default | [362](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ImageMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.98:1
ItemLayoutMinimalPerf.default | [1223](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1245](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.98:1
MenuMinimalPerf.default | [851](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/MenuMinimalPerf.default.html) | [869](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/MenuMinimalPerf.default_base.html) | 0.98:1
ProviderMergeThemesPerf.default | [1741](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1769](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.98:1
RadioGroupMinimalPerf.default | [439](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [449](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.98:1
IconMinimalPerf.default | [618](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/IconMinimalPerf.default.html) | [630](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.98:1
GridMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/GridMinimalPerf.default.html) | [356](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.97:1
VideoMinimalPerf.default | [635](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/VideoMinimalPerf.default.html) | [652](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.97:1
FormMinimalPerf.default | [391](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/FormMinimalPerf.default.html) | [407](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.96:1
ListWith60ListItems.default | [636](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ListWith60ListItems.default.html) | [684](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.93:1
SkeletonMinimalPerf.default | [337](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/SkeletonMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.93:1
AccordionMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AccordionMinimalPerf.default.html) | [185](https://fluentuipr.z22.web.core.windows.net/pull/20514/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.84:1

</details><div id="perfComment9423"/>

File: packages/react/src/utilities/positioning/positioning.ts [hunk 1]
```diff
@@ -339,6 +339,9 @@ function _adjustFitWithinBounds(
     elementEstimate = _flipToFit(element, target, bounding, positionData, gap);
   }
   const outOfBounds = _getOutOfBoundsEdges(elementEstimate.elementRectangle, bounding);
+  // if directionalHintFixed is specified, we need to force the target edge to not change
+  // we need *-1 because targetEdge refers to the target's edge; the callout edge is the opposite
+  const fixedEdge = directionalHintFixed ? elementEstimate.targetEdge * -1 : undefined;
```
Comment (dotnetjunky) [inline packages/react/src/utilities/positioning/positioning.ts:344]: nitpick: `elementEstimage.targetEdge * -1` is better written as `-elementEstimate.targetEdge`

**Review by khmakoto — APPROVED** [review]
