### PR TITLE
chore: fix `no-context-default-value` lint violations for teams-prg

### LINKED ISSUE #21338: react-shared-context multiple instances cause problems with multiple dependency versions
### Environment Information

- **Package version(s)**: 9.0.0-beta.3, 9.0.0-beta.4
- **Browser and OS versions**: N/A

### Problem

When an application ends up depending on multiple versions of the react-shared-context package, each version creates a different context instance.  In this case, the theme from FluentProvider ended up undefined on one of the instances. 

This issue points out a problem we need to solve with applications that end up with multiple versions of a shared fluent package that creates context. It could easily happen when an application takes a dependency on another package depending on fluent.

### Solutions to consider

- It might be helpful to de-dupe the instances by putting the instance on the window so that multiple versions could check if the instance is already created.  
- Different instances from different versions could be put onto the context with schema/version.  [satcheljs](https://github.com/microsoft/satcheljs/blob/master/src/globalContext.ts) takes this approach.
- Ensuring that packages take fluent as a peer dependency with caret upgrade.  
- Detecting multiple instances and warning developers to update the package.json resolutions to remove the duplicate packages.
 
### Priorities and help requested:

This is very important to upgrade, especially while we ask partners to be trying to flight beta components that have breaking changes between versions.

### PR DESCRIPTION
**Pull request by ling1726**
Addresses #21338

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4ba03b2e704668cb253f8ad16e8995a8a44b3d22'>4ba03b2e704668cb253f8ad16e8995a8a44b3d22</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/Avatar-mount_base.html">1254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/Avatar-mount.html">1273</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/Button-mount_base.html">950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/Button-mount.html">972</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/FluentProvider-mount_base.html">1554</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/FluentProvider-mount.html">1576</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/FluentProviderWithTheme-mount_base.html">636</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/FluentProviderWithTheme-mount.html">636</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">595</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">589</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">623</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">629</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/MakeStyles-mount_base.html">1935</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/MakeStyles-mount.html">1935</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/SpinButton-mount_base.html">2481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-react-components/SpinButton-mount.html">2513</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: 2 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
AlertMinimalPerf.default | [218](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AlertMinimalPerf.default.html) | [214](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.02:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AlertMinimalPerf.default.regression.txt)
AttachmentSlotsPerf.default | [913](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AttachmentSlotsPerf.default.html) | [895](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.02:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AttachmentSlotsPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ChatWithPopoverPerf.default | [321](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ChatWithPopoverPerf.default.html) | [298](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.08:1
ImageMinimalPerf.default | [321](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ImageMinimalPerf.default.html) | [297](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.08:1
AttachmentMinimalPerf.default | [130](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AttachmentMinimalPerf.default.html) | [121](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.07:1
SegmentMinimalPerf.default | [301](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/SegmentMinimalPerf.default.html) | [284](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.06:1
ReactionMinimalPerf.default | [320](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ReactionMinimalPerf.default.html) | [306](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.05:1
ButtonSlotsPerf.default | [465](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ButtonSlotsPerf.default.html) | [446](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
LabelMinimalPerf.default | [324](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/LabelMinimalPerf.default.html) | [311](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.04:1
MenuMinimalPerf.default | [735](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/MenuMinimalPerf.default.html) | [709](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.04:1
PortalMinimalPerf.default | [147](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/PortalMinimalPerf.default.html) | [142](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.04:1
AvatarMinimalPerf.default | [155](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AvatarMinimalPerf.default.html) | [151](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.03:1
BoxMinimalPerf.default | [280](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/BoxMinimalPerf.default.html) | [272](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.03:1
LayoutMinimalPerf.default | [296](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/LayoutMinimalPerf.default.html) | [286](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.03:1
ListWith60ListItems.default | [520](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ListWith60ListItems.default.html) | [505](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.03:1
PopupMinimalPerf.default | [536](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/PopupMinimalPerf.default.html) | [520](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.03:1
ProviderMinimalPerf.default | [341](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ProviderMinimalPerf.default.html) | [332](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.03:1
RadioGroupMinimalPerf.default | [380](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [370](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.03:1
StatusMinimalPerf.default | [569](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/StatusMinimalPerf.default.html) | [552](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.03:1
VideoMinimalPerf.default | [536](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/VideoMinimalPerf.default.html) | [518](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.03:1
AnimationMinimalPerf.default | [443](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AnimationMinimalPerf.default.html) | [434](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.02:1
ChatDuplicateMessagesPerf.default | [243](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [238](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.02:1
DividerMinimalPerf.default | [303](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DividerMinimalPerf.default.html) | [298](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.02:1
GridMinimalPerf.default | [275](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/GridMinimalPerf.default.html) | [270](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.02:1
TextMinimalPerf.default | [284](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TextMinimalPerf.default.html) | [278](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.02:1
ToolbarMinimalPerf.default | [777](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ToolbarMinimalPerf.default.html) | [763](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [944](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TooltipMinimalPerf.default.html) | [922](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1266](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1257](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
CarouselMinimalPerf.default | [391](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/CarouselMinimalPerf.default.html) | [387](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [4943](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4910](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
HeaderMinimalPerf.default | [300](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/HeaderMinimalPerf.default.html) | [298](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [1069](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1062](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
SkeletonMinimalPerf.default | [277](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/SkeletonMinimalPerf.default.html) | [275](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3668](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3631](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
DialogMinimalPerf.default | [641](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DialogMinimalPerf.default.html) | [644](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [3463](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/EmbedMinimalPerf.default.html) | [3468](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
FlexMinimalPerf.default | [230](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/FlexMinimalPerf.default.html) | [231](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1:1
HeaderSlotsPerf.default | [635](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/HeaderSlotsPerf.default.html) | [632](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1:1
ItemLayoutMinimalPerf.default | [986](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [985](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1:1
ListCommonPerf.default | [515](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ListCommonPerf.default.html) | [516](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ListCommonPerf.default_base.html) | 1:1
ListMinimalPerf.default | [430](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ListMinimalPerf.default.html) | [430](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1407](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1414](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
TableManyItemsPerf.default | [1575](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TableManyItemsPerf.default.html) | [1577](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1:1
TextAreaMinimalPerf.default | [403](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TextAreaMinimalPerf.default.html) | [402](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1:1
TreeMinimalPerf.default | [674](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TreeMinimalPerf.default.html) | [673](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1:1
TreeWith60ListItems.default | [139](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TreeWith60ListItems.default.html) | [139](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1:1
ButtonMinimalPerf.default | [136](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ButtonMinimalPerf.default.html) | [138](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [608](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ChatMinimalPerf.default.html) | [615](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [2243](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2258](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
DropdownManyItemsPerf.default | [558](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DropdownManyItemsPerf.default.html) | [564](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.99:1
FormMinimalPerf.default | [331](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/FormMinimalPerf.default.html) | [336](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1075](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/InputMinimalPerf.default.html) | [1085](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
ListNestedPerf.default | [453](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ListNestedPerf.default.html) | [458](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/ListNestedPerf.default_base.html) | 0.99:1
LoaderMinimalPerf.default | [561](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/LoaderMinimalPerf.default.html) | [564](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.99:1
SliderMinimalPerf.default | [1393](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/SliderMinimalPerf.default.html) | [1411](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.99:1
TableMinimalPerf.default | [329](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TableMinimalPerf.default.html) | [332](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.99:1
CustomToolbarPrototype.default | [2297](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/CustomToolbarPrototype.default.html) | [2319](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.99:1
CardMinimalPerf.default | [440](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/CardMinimalPerf.default.html) | [447](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.98:1
DropdownMinimalPerf.default | [2600](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DropdownMinimalPerf.default.html) | [2645](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.98:1
RefMinimalPerf.default | [184](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/RefMinimalPerf.default.html) | [187](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.98:1
AccordionMinimalPerf.default | [118](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AccordionMinimalPerf.default.html) | [122](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.97:1
RosterPerf.default | [902](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/RosterPerf.default.html) | [931](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/RosterPerf.default_base.html) | 0.97:1
IconMinimalPerf.default | [485](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/IconMinimalPerf.default.html) | [524](https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.93:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/BaseButton-mount_base.html">775</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/BaseButton-mount.html">786</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Breadcrumb-mount_base.html">2379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Breadcrumb-mount.html">2426</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Checkbox-mount_base.html">2235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Checkbox-mount.html">2244</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/CheckboxBase-mount_base.html">1948</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/CheckboxBase-mount.html">1942</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ChoiceGroup-mount_base.html">4032</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ChoiceGroup-mount.html">4070</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ComboBox-mount_base.html">834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ComboBox-mount.html">838</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/CommandBar-mount_base.html">9051</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/CommandBar-mount.html">9077</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ContextualMenu-mount_base.html">10224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ContextualMenu-mount.html">10050</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DefaultButton-mount_base.html">1005</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DefaultButton-mount.html">995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DetailsRow-mount_base.html">3352</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DetailsRow-mount.html">3243</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DetailsRowFast-mount_base.html">3270</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DetailsRowFast-mount.html">3260</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DetailsRowNoStyles-mount_base.html">3163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DetailsRowNoStyles-mount.html">3152</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Dialog-mount_base.html">2450</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Dialog-mount.html">2445</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DocumentCardTitle-mount_base.html">138</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/DocumentCardTitle-mount.html">141</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Dropdown-mount_base.html">2834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Dropdown-mount.html">2858</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/FocusTrapZone-mount_base.html">1626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/FocusTrapZone-mount.html">1681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/FocusZone-mount_base.html">1569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/FocusZone-mount.html">1549</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/IconButton-mount_base.html">1529</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/IconButton-mount.html">1535</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Label-mount_base.html">297</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Label-mount.html">299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Layer-mount_base.html">2684</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Layer-mount.html">2698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Link-mount_base.html">396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Link-mount.html">409</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/MenuButton-mount_base.html">1271</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/MenuButton-mount.html">1275</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/MessageBar-mount_base.html">1913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/MessageBar-mount.html">1881</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Nav-mount_base.html">2829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Nav-mount.html">2833</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/OverflowSet-mount_base.html">936</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/OverflowSet-mount.html">928</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Panel-mount_base.html">1898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Panel-mount.html">1890</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Persona-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Persona-mount.html">856</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Pivot-mount_base.html">1277</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Pivot-mount.html">1245</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/PrimaryButton-mount_base.html">1114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/PrimaryButton-mount.html">1127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Rating-mount_base.html">6635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Rating-mount.html">6703</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/SearchBox-mount_base.html">1110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/SearchBox-mount.html">1110</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Shimmer-mount_base.html">2146</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Shimmer-mount.html">2143</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Slider-mount_base.html">1693</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Slider-mount.html">1663</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/SpinButton-mount_base.html">4323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/SpinButton-mount.html">4338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Spinner-mount_base.html">390</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Spinner-mount.html">383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/SplitButton-mount_base.html">2793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/SplitButton-mount.html">2753</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Stack-mount_base.html">466</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Stack-mount.html">453</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/StackWithIntrinsicChildren-mount_base.html">1995</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/StackWithIntrinsicChildren-mount.html">1971</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/StackWithTextChildren-mount_base.html">4485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/StackWithTextChildren-mount.html">4489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/SwatchColorPicker-mount_base.html">10084</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/SwatchColorPicker-mount.html">10082</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/TagPicker-mount_base.html">2346</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/TagPicker-mount.html">2330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/TeachingBubble-mount_base.html">82153</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/TeachingBubble-mount.html">81620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Text-mount_base.html">367</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Text-mount.html">368</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/TextField-mount_base.html">1187</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/TextField-mount.html">1215</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ThemeProvider-mount_base.html">1049</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ThemeProvider-mount.html">1045</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ThemeProvider-virtual-rerender_base.html">583</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ThemeProvider-virtual-rerender.html">592</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1562</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Toggle-mount_base.html">712</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/Toggle-mount.html">665</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/buttonNative-mount_base.html">116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24276/perf-test/buttonNative-mount.html">112</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: packages/react-components/react-menu/src/contexts/menuContext.ts [hunk 1]
```diff
@@ -4,8 +4,11 @@ import type { ContextSelector, Context } from '@fluentui/react-context-selector'
 import type { MenuListProps } from '../components/index';
 import type { MenuState } from '../components/Menu/index';
 
-// eslint-disable-next-line @fluentui/no-context-default-value
-export const MenuContext: Context<MenuContextValue> = createContext<MenuContextValue>({
+export const MenuContext: Context<MenuContextValue | undefined> = createContext<MenuContextValue | undefined>(
+  undefined,
+);
+
+const menuContextDefaultValue = {
```
Comment (layershifter) [inline packages/react-components/react-menu/src/contexts/menuContext.ts:11]:
```suggestion
const menuContextDefaultValue: MenuContextValue = {
```

nit: I would explicitly type it

File: packages/react-components/react-menu/src/contexts/menuGroupContext.ts [hunk 2]
```diff
@@ -1,7 +1,10 @@
 import * as React from 'react';
 
-// eslint-disable-next-line @fluentui/no-context-default-value
-const MenuGroupContext = React.createContext<MenuGroupContextValue>({ headerId: '' });
+const MenuGroupContext = React.createContext<MenuGroupContextValue | undefined>(undefined);
+
+const menuGroupContextDefaultValue = {
```
Comment (layershifter) [inline packages/react-components/react-menu/src/contexts/menuGroupContext.ts:5]:
```suggestion
const menuGroupContextDefaultValue: MenuGroupContextValue = {
```

File: packages/react-components/react-menu/src/contexts/menuListContext.tsx [hunk 3]
```diff
@@ -4,16 +4,19 @@ import type { ContextSelector, Context } from '@fluentui/react-context-selector'
 import type { SelectableHandler } from '../selectable/index';
 import type { MenuListProps } from '../components/index';
 
-// eslint-disable-next-line @fluentui/no-context-default-value
-export const MenuListContext: Context<MenuListContextValue> = createContext<MenuListContextValue>({
+export const MenuListContext: Context<MenuListContextValue | undefined> = createContext<
+  MenuListContextValue | undefined
+>(undefined);
+
+const menuListContextDefaultValue = {
```
Comment (layershifter) [inline packages/react-components/react-menu/src/contexts/menuListContext.tsx:11]:
```suggestion
const menuListContextDefaultValue: MenuListContextValue = {
```

File: packages/react-components/react-overflow/src/overflowContext.ts [hunk 4]
```diff
@@ -9,14 +9,15 @@ export interface OverflowContextValue {
   updateOverflow: (padding?: number) => void;
 }
 
-// eslint-disable-next-line @fluentui/no-context-default-value
-export const OverflowContext = createContext<OverflowContextValue>({
+export const OverflowContext = createContext<OverflowContextValue | undefined>(undefined);
+
+const overflowContextDefaultValue = {
```
Comment (layershifter) [inline packages/react-components/react-overflow/src/overflowContext.ts:14]:
```suggestion
const overflowContextDefaultValue: OverflowContextValue = {
```

File: packages/react-components/react-popover/src/popoverContext.ts [hunk 5]
```diff
@@ -2,8 +2,11 @@ import { createContext, useContextSelector } from '@fluentui/react-context-selec
 import type { ContextSelector, Context } from '@fluentui/react-context-selector';
 import type { PopoverState } from './components/Popover/index';
 
-// eslint-disable-next-line @fluentui/no-context-default-value
-export const PopoverContext: Context<PopoverContextValue> = createContext<PopoverContextValue>({
+export const PopoverContext: Context<PopoverContextValue | undefined> = createContext<PopoverContextValue | undefined>(
+  undefined,
+);
+
+const popoverContextDefaultValue = {
```
Comment (layershifter) [inline packages/react-components/react-popover/src/popoverContext.ts:9]:
```suggestion
const popoverContextDefaultValue: PopoverContextValue = {
```

File: packages/react-components/react-popover/etc/react-popover.api.md [hunk 6]
```diff
@@ -60,7 +60,7 @@ export type PopoverProps = Pick<PortalProps, 'mountNode'> & {
 };
 
 // @public (undocumented)
-export const PopoverProvider: Provider<PopoverContextValue> & FC<ProviderProps<PopoverContextValue>>;
+export const PopoverProvider: Provider<PopoverContextValue | undefined> & FC<ProviderProps<PopoverContextValue | undefined>>;
```
Comment (layershifter) [inline packages/react-components/react-popover/etc/react-popover.api.md:63]: Unrelated: is it okay that we export this at all?

File: packages/react-components/react-portal-compat-context/src/PortalCompatContext.ts [hunk 7]
```diff
@@ -1,13 +1,12 @@
 import * as React from 'react';
 import type { RegisterPortalFn } from './types';
 
-const PortalCompatContext = React.createContext<RegisterPortalFn>(
-  // eslint-disable-next-line @typescript-eslint/no-empty-function, @fluentui/no-context-default-value
-  () => () => {},
-);
+const PortalCompatContext = React.createContext<RegisterPortalFn | undefined>(undefined);
+
+const portalCompatContextDefaultValue = () => () => {};
```
Comment (layershifter) [inline packages/react-components/react-portal-compat-context/src/PortalCompatContext.ts:6]:
```suggestion
const portalCompatContextDefaultValue: RegisterPortalFn = () => () => {};
```

File: packages/react-components/react-portal-compat-context/etc/react-portal-compat-context.api.md [hunk 8]
```diff
@@ -3,10 +3,11 @@
 > Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).
 
 ```ts
+
 import * as React_2 from 'react';
 
 // @public (undocumented)
-export const PortalCompatContextProvider: React_2.Provider<RegisterPortalFn>;
+export const PortalCompatContextProvider: React_2.Provider<RegisterPortalFn | undefined>;
```
Comment (layershifter) [inline packages/react-components/react-portal-compat-context/etc/react-portal-compat-context.api.md:10]: This does not seem correct to me, can you please type cast it to a previous value? (otherwise it's possible to do `<PortalCompatContextProvider value={undefined} />`

File: packages/react-components/react-shared-contexts/src/ProviderContext/ProviderContext.ts [hunk 9]
```diff
@@ -11,17 +11,18 @@ export type ProviderContextValue = {
 /**
  * @internal
  */
-// eslint-disable-next-line @fluentui/no-context-default-value
-const ProviderContext = React.createContext<ProviderContextValue>({
+const ProviderContext = React.createContext<ProviderContextValue | undefined>(undefined);
+
+const providerContextDefaultValue = {
```
Comment (layershifter) [inline packages/react-components/react-shared-contexts/src/ProviderContext/ProviderContext.ts:16]:
```suggestion
const providerContextDefaultValue: ProviderContextValue = {
```

This probably will remove need in `as 'ltr'` below

File: packages/react-components/react-toolbar/src/components/Toolbar/ToolbarContext.tsx [hunk 10]
```diff
@@ -1,9 +1,10 @@
...
 import type { ToolbarContextValue } from './Toolbar.types';
 
-// eslint-disable-next-line @fluentui/no-context-default-value
-export const ToolbarContext = React.createContext<ToolbarContextValue>({
-  size: 'medium',
-});
+export const ToolbarContext = React.createContext<ToolbarContextValue | undefined>(undefined);
 
-export const useToolbarContext = () => React.useContext(ToolbarContext);
+const toolbarContextDefaultValue = {
```
Comment (layershifter) [inline packages/react-components/react-toolbar/src/components/Toolbar/ToolbarContext.tsx:6]:
```suggestion
const toolbarContextDefaultValue: ToolbarContextValue = {
```

**Comment by layershifter** [comment]
FYI:

```
ERR! Warning: You have changed the public API signature for this project. Please copy the file "temp/react-menu.api.md" to "etc/react-menu.api.md", or perform a local build (which does this automatically). See the Git repo documentation for more info.
ERR! [6:15:41 AM] x Error detected while running 'api-extractor:default'
ERR! [6:15:41 AM] x ------------------------------------
ERR! [6:15:41 AM] x Error: The public API file is out of date. Please run the API snapshot and commit the updated API file.
```

I would avoid updating any API files in this PR as much as possible as we don't expect changes in APIs.

File: packages/react-components/react-portal-compat-context/etc/react-portal-compat-context.api.md (hunk 8 above)
Comment (ling1726) [reply packages/react-components/react-portal-compat-context/etc/react-portal-compat-context.api.md]: You're right, the type casting is a good idea 👍 I've done that for all changes in this PR

File: packages/react-components/react-popover/etc/react-popover.api.md (hunk 6 above)
Comment (ling1726) [reply packages/react-components/react-popover/etc/react-popover.api.md]: I don't understand, why shouldn't we export it ?

File: packages/react-components/react-shared-contexts/src/ProviderContext/ProviderContext.ts [hunk 11]
```diff
@@ -11,17 +11,20 @@ export type ProviderContextValue = {
...
-const ProviderContext = React.createContext<ProviderContextValue>({
+const ProviderContext = React.createContext<ProviderContextValue | undefined>(
+  undefined,
+) as React.Context<ProviderContextValue>;
+
+const providerContextDefaultValue: ProviderContextValue = {
   targetDocument: typeof document === 'object' ? document : undefined,
-  dir: 'ltr',
-});
+  dir: 'ltr' as 'ltr',
```
Comment (layershifter) [inline packages/react-components/react-shared-contexts/src/ProviderContext/ProviderContext.ts:20]: Is it need at all?

P.S. May be `as const`?

```suggestion
  dir: 'ltr' as const,
```

File: packages/react-components/react-popover/etc/react-popover.api.md (hunk 6 above)
Comment (layershifter) [reply packages/react-components/react-popover/etc/react-popover.api.md]: It's not documented publicly so I decided to ask 🐱

**Review by layershifter — APPROVED** [review]

**Review by bsunderhus — APPROVED** [review]
LGTM 💪🏼
