### PR TITLE
Fix v9 switch bug in renderedPosition

### LINKED ISSUE #21699: V9 controlled Switch is uncontrolled until it's toggled once manually
Controlled switches are supposed to update their state anytime that the 'checked' value changes. It appears that there's a bug where switches only slip into 'controlled' mode after the switch is toggled once.

### Repro steps
Open example. Toggle one switch and notice the other does not toggle. Now toggle the other, and notice that they both follow stage properly. 

https://codesandbox.io/s/switch-repro-forked-ff9xb?file=/src/App.js

### PR DESCRIPTION
**Pull request by micahgodbolt**
Bug in controlled switches where renderedPosition does not change if state change only comes from state (not a click/enter)

In switch logic renderedPosition is set to undefined on `setChecked`, which then allows `currentPosition` to be based off of `checked` value vs `renderedPosition` value. With default value of `renderedPosition` at 0 or 100, incoming state changes can never affect the `currentPosition`, and it stays at that default value.

This is a bit of a bandaid as we'll probably do some major changes to the control before actual release. 

fixes #21699

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                          |    Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                                                   Change |
| :----------------------------------------------------------------------------------------- | --------------------------: | --------------------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr> | `25.387 kB`<br />`8.204 kB` | `25.381 kB`<br />`8.201 kB` | `-6 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/Decrease.svg" /><br />`-3 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/Decrease.svg" /> |

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0b7d30b6ecb6f20d2ac4d4edbfb327a8f8f915a0'>0b7d30b6ecb6f20d2ac4d4edbfb327a8f8f915a0</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">157</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">179</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Avatar-mount_base.html">769</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Avatar-mount.html">770</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/BaseButton-mount_base.html">797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/BaseButton-mount.html">796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Breadcrumb-mount_base.html">2247</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Breadcrumb-mount.html">2291</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ButtonNext-mount_base.html">404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ButtonNext-mount.html">427</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Checkbox-mount_base.html">1349</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Checkbox-mount.html">1338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/CheckboxBase-mount_base.html">1112</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/CheckboxBase-mount.html">1151</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ChoiceGroup-mount_base.html">4109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ChoiceGroup-mount.html">4147</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ComboBox-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ComboBox-mount.html">861</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/CommandBar-mount_base.html">8827</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/CommandBar-mount.html">8708</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ContextualMenu-mount_base.html">7189</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ContextualMenu-mount.html">7176</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DefaultButton-mount_base.html">985</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DefaultButton-mount.html">1001</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DetailsRow-mount_base.html">3236</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DetailsRow-mount.html">3207</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DetailsRowFast-mount_base.html">3268</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DetailsRowFast-mount.html">3196</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DetailsRowNoStyles-mount_base.html">3060</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DetailsRowNoStyles-mount.html">3086</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Dialog-mount_base.html">1914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Dialog-mount.html">1936</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DocumentCardTitle-mount_base.html">151</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/DocumentCardTitle-mount.html">157</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Dropdown-mount_base.html">2794</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Dropdown-mount.html">2788</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderNext-mount_base.html">1679</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderNext-mount.html">1683</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-mount_base.html">131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-mount.html">111</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">97</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-virtual-rerender.html">104</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">157</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">179</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FocusTrapZone-mount_base.html">1584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FocusTrapZone-mount.html">1644</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FocusZone-mount_base.html">1592</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/FocusZone-mount.html">1601</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/IconButton-mount_base.html">1517</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/IconButton-mount.html">1503</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Label-mount_base.html">319</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Label-mount.html">327</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Layer-mount_base.html">2574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Layer-mount.html">2572</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Link-mount_base.html">441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Link-mount.html">432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/MakeStyles-mount_base.html">1470</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/MakeStyles-mount.html">1479</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/MenuButton-mount_base.html">1308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/MenuButton-mount.html">1297</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/MessageBar-mount_base.html">1734</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/MessageBar-mount.html">1760</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Nav-mount_base.html">2815</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Nav-mount.html">2837</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/OverflowSet-mount_base.html">970</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/OverflowSet-mount.html">980</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Panel-mount_base.html">1896</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Panel-mount.html">1858</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Persona-mount_base.html">753</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Persona-mount.html">735</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Pivot-mount_base.html">1236</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Pivot-mount.html">1250</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/PrimaryButton-mount_base.html">1118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/PrimaryButton-mount.html">1109</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Rating-mount_base.html">6600</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Rating-mount.html">6598</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/SearchBox-mount_base.html">1174</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/SearchBox-mount.html">1163</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Shimmer-mount_base.html">2196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Shimmer-mount.html">2218</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Slider-mount_base.html">1710</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Slider-mount.html">1702</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/SpinButton-mount_base.html">4277</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/SpinButton-mount.html">4328</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Spinner-mount_base.html">408</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Spinner-mount.html">389</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/SplitButton-mount_base.html">2717</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/SplitButton-mount.html">2715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Stack-mount_base.html">465</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Stack-mount.html">472</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/StackWithIntrinsicChildren-mount_base.html">1987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/StackWithIntrinsicChildren-mount.html">2000</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/StackWithTextChildren-mount_base.html">4480</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/StackWithTextChildren-mount.html">4515</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/SwatchColorPicker-mount_base.html">9893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/SwatchColorPicker-mount.html">9909</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/TagPicker-mount_base.html">2255</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/TagPicker-mount.html">2261</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/TeachingBubble-mount_base.html">11309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/TeachingBubble-mount.html">11262</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Text-mount_base.html">397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Text-mount.html">393</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/TextField-mount_base.html">1218</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/TextField-mount.html">1221</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ThemeProvider-mount_base.html">1049</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ThemeProvider-mount.html">1041</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ThemeProvider-virtual-rerender_base.html">548</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ThemeProvider-virtual-rerender.html">549</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1617</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Toggle-mount_base.html">708</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/Toggle-mount.html">724</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/buttonNative-mount_base.html">128</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21704/perf-test/buttonNative-mount.html">128</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9423"/>

File: packages/react-switch/src/components/Switch/useSwitchState.ts [hunk 1]
```diff
@@ -46,7 +46,7 @@ export const useSwitchState = (state: SwitchState) => {
     initialState: false,
   });
   const [thumbAnimation, { setTrue: showThumbAnimation, setFalse: hideThumbAnimation }] = useBoolean(true);
-  const [renderedPosition, setRenderedPosition] = React.useState<number | undefined>(currentValue === true ? 100 : 0);
+  const [renderedPosition, setRenderedPosition] = React.useState<number | undefined>(undefined);
```
Comment (micahgodbolt) [inline packages/react-switch/src/components/Switch/useSwitchState.ts:49]: renderedPosition does not need to start defined. If you pass in a currentValue there's a check below that looks for that before rendering the switch position.

**Review by khmakoto — APPROVED** [review]
