### PR TITLE
fix(DropdownSelectedItem): Fix render imagen passing children on DropdownSelectedItem

### LINKED ISSUE #13351: DropdownSelectedItems not rendering image using children
### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/fluent-ui-example-ymknn?file=/example.js

image

#### Actual behavior:

SelectedItem element doesn't render image using `children` props the same way it does for with `render` props

#### Expected behavior:

SelectedItem element renders image using `children` props the same way it does for with `render` props

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #13351
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

This PR fix the error preventing `DropdownSelectedItem` to render the selected image using `children`

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx [hunk 1]
```diff
@@ -155,19 +155,21 @@ const DropdownSelectedItem: React.FC<WithAsProp<DropdownSelectedItemProps>> &
...
-  const imageProps = _.isNil(image)
-    ? image
-    : {
-        children: (ComponentType, props) =>
-          Image.create(image, {
-            defaultProps: () => ({
-              avatar: true,
-              className: dropdownSelectedItemSlotClassNames.image,
-              styles: resolvedStyles.image,
+  const imageChildren = _.get(image, 'children');
```
Comment (assuncaocharles) [inline packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:158]: I tried in previously commit to solve it using `childrenExist` but it will be true for text only and then not working as expected. If you don't agree with this solution, have any other idea? @layershifter and @pompomon

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx [hunk 2]
```diff
@@ -155,19 +155,20 @@ const DropdownSelectedItem: React.FC<WithAsProp<DropdownSelectedItemProps>> &
...
-    ? image
-    : {
-        children: (ComponentType, props) =>
-          Image.create(image, {
-            defaultProps: () => ({
-              avatar: true,
-              className: dropdownSelectedItemSlotClassNames.image,
-              styles: resolvedStyles.image,
+  const imageProps =
+    _.isNil(image) || image?.hasOwnProperty('children')
```
Comment (assuncaocharles) [inline packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:159]: I tried in previously commit to solve it using childrenExist but it will be true for text only and then not working as expected. If you don't agree with this solution, have any other idea? @layershifter and @pompomon

Comment (layershifter) [reply packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:159]: Expected fix there is to remove `Label` component from there like it was done with `DropdownItem`

https://github.com/microsoft/fluent-ui-react/pull/2382/

Comment (layershifter) [reply packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:159]: In this case there is no need to call factories for `imageProps`

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx]: Done

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx [hunk 3]
```diff
@@ -132,57 +135,61 @@ const DropdownSelectedItem: React.FC<WithAsProp<DropdownSelectedItemProps>> &
...
+      }),
+    },
+  );
+
+  const iconElement = Box.create(icon, {
     defaultProps: () => ({
-      as: 'span',
-      className: dropdownSelectedItemSlotClassNames.header,
-      styles: resolvedStyles.header,
+      'aria-label': `Remove ${header} from selection.`, // TODO: Extract this in a behaviour.
```
Comment (jurokapsiar) [inline packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:156]: how would the user customize the label? Is it through Dropdown's `getA11ySelectionMessage`?

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:156]: Resolving this to focus the discussion on the PR #13410

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx [hunk 4]
```diff
@@ -132,57 +135,61 @@ const DropdownSelectedItem: React.FC<WithAsProp<DropdownSelectedItemProps>> &
...
-            defaultProps: () => ({
-              avatar: true,
-              className: dropdownSelectedItemSlotClassNames.image,
-              styles: resolvedStyles.image,
-            }),
-            overrideProps: props,
-          }),
-      };
+  const imageElement = Box.create(
+    Image.create(image, {
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:164]: This should be under `overrideProps`:

```
Box.create(media, {
  overrideProps: {
    children: Image.create()
  }
}

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx [hunk 5]
```diff
@@ -132,57 +135,61 @@ const DropdownSelectedItem: React.FC<WithAsProp<DropdownSelectedItemProps>> &
...
-          Image.create(image, {
-            defaultProps: () => ({
-              avatar: true,
-              className: dropdownSelectedItemSlotClassNames.image,
-              styles: resolvedStyles.image,
-            }),
-            overrideProps: props,
-          }),
-      };
+  const imageElement = Box.create(
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:163]:
```suggestion
  const mediaElement = Box.create(
```

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx [hunk 6]
```diff
@@ -132,57 +135,61 @@ const DropdownSelectedItem: React.FC<WithAsProp<DropdownSelectedItemProps>> &
...
+      defaultProps: () => ({
+        avatar: true,
+        className: dropdownSelectedItemSlotClassNames.image,
+        styles: resolvedStyles.image,
+      }),
+    }),
+    {
+      defaultProps: () => ({
+        className: dropdownSelectedItemSlotClassNames.image,
+        styles: resolvedStyles.media,
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:174]: I don't see styles for this element. Is it required to have it in markup?

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx (hunk 4 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:164]: Moved

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx (hunk 6 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:174]: Removed

**Comment by assuncaocharles** [comment]
@layershifter Implemented the solution you proposed, can you have a 2nd look? 😁

File: packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx [hunk 7]
```diff
@@ -132,57 +135,63 @@ const DropdownSelectedItem: React.FC<WithAsProp<DropdownSelectedItemProps>> &
...
 
   const element = (
     <Ref innerRef={itemRef}>
-      <Label
+      <ElementType
         className={classes.root}
         tabIndex={active ? 0 : -1}
-        styles={resolvedStyles.root}
-        circular
+        styles={resolvedStyles.main}
```
Comment (pompomon) [inline packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:186]: Please why do you use `main` style here? And where is it defined, I don't see it in `dropdownSelectedItemStyles`

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx:186]: Changed by @layershifter
