### PR TITLE
fix: Wrapping long text in Button components

### LINKED ISSUE #23129: Button with long text
The "With Long Text" button example is currently not truncating 😄
screenshot showing a button with long text showing a snippet of text in the middle of the button, with both the first and last part of the text abruptly cut off by the button border

That said, I don't think truncation is a good default -- it's not clear how we would expose that text to screen readers. We should probably make the text wrap by default, and let teams apply truncation styles themselves if they prefer that approach.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

`Button` components used to truncate long text when it was longer than the width of the button. This changed a while ago but the stories stayed in the documentation, which are effectively broken.

## New Behavior

`Button` components now wrap long text when it is longer than the width of the button. The stories have also been updated to reflect this and visual regression tests added to test this.

As part of this change, the `min-height` styles in `Button` components have been replaced by their `padding` + `border` + `line-height` calculation equivalent so the padding is always the same independent of how many lines of text the `Button` has.

## Related Issue(s)

Fixes #23129

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                   Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `83.797 kB`<br />`20.853 kB` |  `83.761 kB`<br />`20.852 kB` |  `-36 B` <br />`-1 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `36.405 kB`<br />`9.588 kB` |   `36.369 kB`<br />`9.565 kB` | `-36 B` <br />`-23 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `43.431 kB`<br />`10.804 kB` |  `43.395 kB`<br />`10.785 kB` | `-36 B` <br />`-19 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |  `39.023 kB`<br />`10.467 kB` |  `38.987 kB`<br />`10.443 kB` | `-36 B` <br />`-24 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `46.553 kB`<br />`11.85 kB` |  `46.517 kB`<br />`11.828 kB` | `-36 B` <br />`-22 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `51.919 kB`<br />`11.011 kB` |  `51.883 kB`<br />`10.988 kB` | `-36 B` <br />`-23 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.317 kB`<br />`52.005 kB` | `189.281 kB`<br />`51.995 kB` | `-36 B` <br />`-10 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                     | `67.516 kB`<br />`19.291 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                               | `63.198 kB`<br />`18.202 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |   `8.519 kB`<br />`3.582 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |   `9.562 kB`<br />`3.922 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |    `8.62 kB`<br />`3.639 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `33.317 kB`<br />`10.983 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/25d52af8e3204a5f90816364a37226cc240b24e6'>25d52af8e3204a5f90816364a37226cc240b24e6</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts [hunk 1]
```diff
@@ -24,7 +27,6 @@ const useRootStyles = makeStyles({
 
     ...shorthands.overflow('hidden'),
     textOverflow: 'ellipsis',
```
Comment (spmonahan) [inline packages/react-components/react-button/src/components/Button/useButtonStyles.ts:29]: Will text ever overflow now that it wraps?

Comment (khmakoto) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:29]: Good catch! I'll remove the style.

**Review by spmonahan — APPROVED** [review]
