### PR TITLE
Fix: trigger button id should no longer be used as aria label

### LINKED ISSUE #21887: aria-labelledby on Dropdown is set to Dropdown itself if no id provided
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/tv5h0?module=/example.js&file=/example.js

#### Actual behavior:

aria-labelledby is set to id of dropdown button and macOS voiceover does not read text, insteand says button

#### Expected behavior:
 instead should ignore and read text from span in dropdown

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by aubreyquinn**
Fix for Bug #21887 aria-labelledby on Dropdown is set to Dropdown itself if no id provided

The solution has been tested with the keyboard, JAWS, and NVDA.

Please verify that:
* [x] Code is up-to-date with the `master` branch
* [x] Your changes are covered by tests (if possible)
* [x] You've run `yarn change` locally

## Current Behaviour

Currently, the aria-labelledby is being passed down to the trigger button along with the id label of the trigger button. It's causing issues for some screen readers including Mac's VoiceOver.
https://codesandbox.io/s/tv5h0?module=/example.js

e.g.

`<button role="button" data-aa-class="Button" class="ui-button ui-dropdown__trigger-button" id="dropdown-trigger-button-1" type="button" aria-haspopup="true" data-toggle="true" aria-labelledby="dropdown-trigger-button-1"><span dir="auto" class="ui-button__content jg ji jj bq jk jl">Select your hero</span></button>`
 
## New Behavior

If no aria-labelledby prop is provided, then it will not be present in the DOM.

`<button role="button" data-aa-class="Button" class="ui-button ui-dropdown__trigger-button" id="dropdown-trigger-button-1" type="button" aria-haspopup="true" data-toggle="true"><span dir="auto" class="ui-button__content jg ji jj bq jk jl">Select your hero</span></button>`

## Related Issue(s)

Fixes #21887

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0f9ff01aa2f58a2352e86fa8b4a67a8bce7c513a'>0f9ff01aa2f58a2352e86fa8b4a67a8bce7c513a</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AvatarMinimalPerf.default | [170](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AvatarMinimalPerf.default.html) | [144](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.18:1
SkeletonMinimalPerf.default | [305](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/SkeletonMinimalPerf.default.html) | [260](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.17:1
CarouselMinimalPerf.default | [415](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/CarouselMinimalPerf.default.html) | [362](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.15:1
LoaderMinimalPerf.default | [593](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/LoaderMinimalPerf.default.html) | [516](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.15:1
PopupMinimalPerf.default | [546](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/PopupMinimalPerf.default.html) | [473](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.15:1
SegmentMinimalPerf.default | [300](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/SegmentMinimalPerf.default.html) | [261](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.15:1
BoxMinimalPerf.default | [287](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/BoxMinimalPerf.default.html) | [254](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.13:1
DialogMinimalPerf.default | [644](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DialogMinimalPerf.default.html) | [572](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.13:1
TableMinimalPerf.default | [346](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TableMinimalPerf.default.html) | [305](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.13:1
CardMinimalPerf.default | [475](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/CardMinimalPerf.default.html) | [428](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.11:1
ItemLayoutMinimalPerf.default | [1009](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [907](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.11:1
AlertMinimalPerf.default | [227](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AlertMinimalPerf.default.html) | [207](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.1:1
RadioGroupMinimalPerf.default | [369](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [335](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.1:1
DropdownManyItemsPerf.default | [571](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DropdownManyItemsPerf.default.html) | [522](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.09:1
TreeMinimalPerf.default | [689](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TreeMinimalPerf.default.html) | [638](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.08:1
TreeWith60ListItems.default | [170](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TreeWith60ListItems.default.html) | [157](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.08:1
AttachmentMinimalPerf.default | [129](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AttachmentMinimalPerf.default.html) | [121](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.07:1
GridMinimalPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/GridMinimalPerf.default.html) | [284](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.07:1
RefMinimalPerf.default | [192](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/RefMinimalPerf.default.html) | [179](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.07:1
TextAreaMinimalPerf.default | [381](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TextAreaMinimalPerf.default.html) | [356](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.07:1
DatepickerMinimalPerf.default | [4703](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4448](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.06:1
MenuMinimalPerf.default | [694](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/MenuMinimalPerf.default.html) | [655](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.06:1
HeaderSlotsPerf.default | [598](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/HeaderSlotsPerf.default.html) | [575](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.04:1
ListWith60ListItems.default | [531](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ListWith60ListItems.default.html) | [509](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.04:1
TooltipMinimalPerf.default | [867](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TooltipMinimalPerf.default.html) | [831](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.04:1
ChatDuplicateMessagesPerf.default | [273](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [264](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.03:1
DividerMinimalPerf.default | [280](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DividerMinimalPerf.default.html) | [272](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.03:1
LabelMinimalPerf.default | [326](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/LabelMinimalPerf.default.html) | [317](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.03:1
SliderMinimalPerf.default | [1371](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/SliderMinimalPerf.default.html) | [1332](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.03:1
TextMinimalPerf.default | [266](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TextMinimalPerf.default.html) | [260](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.02:1
AnimationMinimalPerf.default | [475](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AnimationMinimalPerf.default.html) | [468](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.01:1
FlexMinimalPerf.default | [245](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/FlexMinimalPerf.default.html) | [243](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1449](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TableManyItemsPerf.default.html) | [1429](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
FormMinimalPerf.default | [339](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/FormMinimalPerf.default.html) | [339](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/FormMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3157](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/CustomToolbarPrototype.default.html) | [3158](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
AttachmentSlotsPerf.default | [908](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AttachmentSlotsPerf.default.html) | [919](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.99:1
ButtonSlotsPerf.default | [415](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ButtonSlotsPerf.default.html) | [420](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [621](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ChatMinimalPerf.default.html) | [626](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
HeaderMinimalPerf.default | [302](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/HeaderMinimalPerf.default.html) | [304](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.99:1
LayoutMinimalPerf.default | [282](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/LayoutMinimalPerf.default.html) | [284](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.99:1
ListNestedPerf.default | [418](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ListNestedPerf.default.html) | [424](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ListNestedPerf.default_base.html) | 0.99:1
SplitButtonMinimalPerf.default | [3547](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3582](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 0.99:1
VideoMinimalPerf.default | [525](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/VideoMinimalPerf.default.html) | [532](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [3318](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/EmbedMinimalPerf.default.html) | [3373](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.98:1
MenuButtonMinimalPerf.default | [1289](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1311](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.98:1
ProviderMinimalPerf.default | [900](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ProviderMinimalPerf.default.html) | [921](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.98:1
ReactionMinimalPerf.default | [281](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ReactionMinimalPerf.default.html) | [286](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.98:1
StatusMinimalPerf.default | [518](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/StatusMinimalPerf.default.html) | [527](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.98:1
CheckboxMinimalPerf.default | [2134](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2201](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.97:1
ImageMinimalPerf.default | [299](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ImageMinimalPerf.default.html) | [311](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.96:1
InputMinimalPerf.default | [1045](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/InputMinimalPerf.default.html) | [1083](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.96:1
IconMinimalPerf.default | [463](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/IconMinimalPerf.default.html) | [481](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.96:1
AccordionMinimalPerf.default | [132](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AccordionMinimalPerf.default.html) | [139](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.95:1
ProviderMergeThemesPerf.default | [1337](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1401](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.95:1
ToolbarMinimalPerf.default | [766](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ToolbarMinimalPerf.default.html) | [812](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.94:1
ButtonOverridesMissPerf.default | [1345](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1448](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.93:1
ChatWithPopoverPerf.default | [285](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ChatWithPopoverPerf.default.html) | [306](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.93:1
DropdownMinimalPerf.default | [2342](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DropdownMinimalPerf.default.html) | [2514](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.93:1
ListCommonPerf.default | [491](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ListCommonPerf.default.html) | [526](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ListCommonPerf.default_base.html) | 0.93:1
RosterPerf.default | [863](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/RosterPerf.default.html) | [927](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/RosterPerf.default_base.html) | 0.93:1
PortalMinimalPerf.default | [141](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/PortalMinimalPerf.default.html) | [152](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/PortalMinimalPerf.default_base.html) | 0.93:1
ListMinimalPerf.default | [379](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ListMinimalPerf.default.html) | [431](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.88:1
ButtonMinimalPerf.default | [126](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ButtonMinimalPerf.default.html) | [149](https://fluentuipr.z22.web.core.windows.net/pull/22173/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.85:1

</details><div id="perfComment9424"/>

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -552,8 +552,10 @@ export const Dropdown = (React.forwardRef<HTMLDivElement, DropdownProps>((props,
       },
       'aria-invalid': ariaInvalid,
       'aria-label': undefined,
-      'aria-labelledby': [ariaLabelledby, triggerButtonId].filter(l => !!l).join(' '),
-      ...(open && { 'aria-expanded': true }),
+      ...(ariaLabelledby && {
+        'aria-labelledby': [ariaLabelledby].filter(l => !!l).join(' '),
+        ...(open && { 'aria-expanded': true }),
```
Comment (YuanboXue-Amber) [inline packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx:557]: Before the change, `aria-expanded` is applied regardless of the `ariaLabelledby` value.
With this change, `aria-expanded` won't be applied unless `ariaLabelledby` is defined. Is this intentional?

Comment (aubreyquinn) [reply packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx]: Updated. I wonder if we should add a unit test for that.

**Comment by YuanboXue-Amber** [comment]
I accepted screener:
Screenshot 2022-03-22 at 11 45 03
No idea why the wrong screenshot was checked in ¯\_(ツ)_/¯

**Comment by YuanboXue-Amber** [comment]
https://user-images.githubusercontent.com/28751745/159466343-e7550183-685f-4b20-9767-c88b01d948be.mov

Tested on VoiceOver works great. The left side is with the code change (on PR docsite). The right side is the current docsite without the code change.

**Review by YuanboXue-Amber — APPROVED** [review]

**Comment by aubreyquinn** [comment]
NVDA speech viewer history showing the placeholder text being annouced
NVDA

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx [hunk 2]
```diff
@@ -552,7 +552,9 @@ export const Dropdown = (React.forwardRef<HTMLDivElement, DropdownProps>((props,
       },
       'aria-invalid': ariaInvalid,
       'aria-label': undefined,
-      'aria-labelledby': [ariaLabelledby, triggerButtonId].filter(l => !!l).join(' '),
+      ...(ariaLabelledby && {
+        'aria-labelledby': [ariaLabelledby].filter(l => !!l).join(' '),
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx:556]: since you're removing the `triggerButtonId` there's no more reason to keep the array operations

```suggestion
      ...(ariaLabelledby && {
        'aria-labelledby': ariaLanelledby,
```

**Review by ling1726 — APPROVED** [review]

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx (hunk 2 above)
Comment (aubreyquinn) [reply packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx]: updated
