### PR TITLE
fix (react-dialog): Use consistent rounding for clientHeight and innerHeight

### LINKED ISSUE #32481: [Bug]: react-dialog shifting layout when body is a fractional height
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.6
    CPU: (14) arm64 Apple M3 Max
    Memory: 104.70 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.120
    Edge: 128.0.2739.67
    Firefox: 129.0.2
    Safari: 17.6
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/u47vqq?file=index.html

## Actual Behavior
When calculating whether scrollbars are present, we compare the body's clientHeight to the window's innerHeight.

In the case when this height is a fractional value, clientHeight rounds to the nearest integer whereas innerHeight always rounds down. This means when the body is set to 100% height and the browser is at a fractional height (usually due to a non-100% zoom factor), clientHeight often reports being 1 pixel taller than innerHeight.

This causes the scrollbar-gutter: stable style to be added, which reserves space for the non-existent scrollbar, shifting the layout.
## Expected Behavior
The scrollbar is not present, so `scrollbar-gutter: stable` should not be applied and shift the layout
image

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by CampbellOwen**
## Previous Behavior

When calculating whether scrollbars are present, we compare the body's clientHeight to the window's innerHeight.

In the case when this height is a fractional value, `clientHeight` rounds to the nearest integer whereas `innerHeight` always rounds down. This means when the body is set to 100% height and the browser is at a fractional height (usually due to a non-100% zoom factor), clientHeight often reports being 1 pixel taller than innerHeight. 

This causes the `scrollbar-gutter: stable` style to be added, which reserves space for the non-existent scrollbar, shifting the layout.

Repro: 

https://stackblitz.com/edit/u47vqq?file=index.html

image
image

## New Behavior

Match `innerHeight`'s rounding behaviour by using `body.getBoundingClientRect().height` and manually rounding down.

According to mdn, `getBoundingClientRect()` is the equivalent to `clientHeight` except it returns the real fractional value: https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight

Fixes #32481

### CODE REVIEW

**Review by khmakoto — APPROVED** [review]

**Review by micahgodbolt — APPROVED** [review]

File: packages/react-components/react-dialog/library/src/utils/useDisableBodyScroll.ts [hunk 1]
```diff
@@ -20,7 +20,9 @@ export function useDisableBodyScroll(): {
       return;
     }
     const isHorizontalScrollbarVisible =
-      targetDocument.body.clientHeight > (targetDocument.defaultView?.innerHeight ?? 0);
+      // When the window is a fractional height, `innerHeight` always rounds down but `clientHeight` rounds either up or down depending on the value.
+      // To properly compare the body clientHeight to the window innerHeight, manually round down the fractional value to match innerHeight's calculation.
+      Math.floor(targetDocument.body.getBoundingClientRect().height) > (targetDocument.defaultView?.innerHeight ?? 0);
```
Comment (bsunderhus) [inline packages/react-components/react-dialog/library/src/utils/useDisableBodyScroll.ts:25]: We have to keep in mind that calling `getBoundingClientRect` forces layout recalc ⚠️.

I don't think this is a big issue for Dialog as this is not being called frequently (only on dialog open). But it's a good thing to keep in mind if we do hit any performance gates one day

**Review by bsunderhus — APPROVED** [review]
LGTM ✅ I'm not a big fan of the extra style recalc that this introduces but I believe it is unavoidable if we want to fix  https://github.com/microsoft/fluentui/issues/32481

Thanks for the PR @CampbellOwen  💪🏻
