### PR TITLE
fix(TreeTitle): arrow left navigation

### LINKED ISSUE #15134: Left Arrow doesn't work on last level of expanded Tree
### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.0
- **Browser and OS versions**: Chrome Version 85.0.4183.102 

### Please provide a reproduction of the bug in a CodeSandbox: https://codesandbox.io/s/4or8j?module=/example.js

The bug seems to be on the `TreeTitle` component behaving different from `TreeItem` since in the last level the focusable element is the `TreeTitle`. ( Maybe it's a good opportunity to merge both components in one and simplify it ) 

#### Actual behavior:

Using keyboard, focus first level and press right arrow to expand and reach the last level then press arrow left, it stuck in the last level. 

#### Expected behavior:

When focus in the last level and pressing left arrow focus should go to parent and subsequent arrow left press should collapse parent. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #15134
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

We are always rendering `TreeTitle` for the last level in the `Tree` ( read "non-expandable" items )  and we were missing left arrow navigation to focus parent for it. This PR fixes it and adds e2e tests to avoid regression.

TKFRbsewN0

This fixes the issue with the current implementation but I believe a proper fix should be getting rid of `TreeTitle` and having only `TreeItem`

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by assuncaocharles** [comment]
@pompomon @layershifter please check this one

File: packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+const navigateToLastLevel = async () => {
+  await e2e.focusOn(selectors.treeItemAt(1));
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(1), 'ArrowRight'); // Expand first level item
+  await e2e.expectCount(selectors.treeItem, 3);
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(1), 'ArrowRight'); // Focus first child  2nd level
+  await e2e.isFocused(selectors.treeItemAt(2));
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(2), 'ArrowRight'); // Expand second level item
+  await e2e.expectCount(selectors.treeItem, 4);
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(2), 'ArrowRight'); // Focus first child 3rd level
+  await e2e.isFocused(selectors.treeTitleAt(3)); // last levet has always tree title focused
```
Comment (layershifter) [inline packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts:19]:
```suggestion
  await e2e.isFocused(selectors.treeTitleAt(3)); // last level has always tree title focused
```

File: packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+  treeItem: `.${treeItemClassName}`,
+  treeTitleAt: (itemIndex: number) => `.${treeItemClassName}:nth-of-type(${itemIndex}) .${treeTitleClassName}`,
+  treeItemAt: (itemIndex: number) => `.${treeItemClassName}:nth-of-type(${itemIndex}) `,
+};
+
+const navigateToLastLevel = async () => {
+  await e2e.focusOn(selectors.treeItemAt(1));
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(1), 'ArrowRight'); // Expand first level item
+  await e2e.expectCount(selectors.treeItem, 3);
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(1), 'ArrowRight'); // Focus first child  2nd level
```
Comment (layershifter) [inline packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts:14]:
```suggestion

  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(1), 'ArrowRight'); // Focus first child  2nd level
```

File: packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+  await e2e.isFocused(selectors.treeItemAt(2));
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(2), 'ArrowRight'); // Expand second level item
+  await e2e.expectCount(selectors.treeItem, 4);
```
Comment (layershifter) [inline packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts:17]:
```suggestion
  await e2e.expectCount(selectors.treeItem, 4);

```

File: packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+  treeTitleAt: (itemIndex: number) => `.${treeItemClassName}:nth-of-type(${itemIndex}) .${treeTitleClassName}`,
+  treeItemAt: (itemIndex: number) => `.${treeItemClassName}:nth-of-type(${itemIndex}) `,
+};
+
+const navigateToLastLevel = async () => {
+  await e2e.focusOn(selectors.treeItemAt(1));
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(1), 'ArrowRight'); // Expand first level item
+  await e2e.expectCount(selectors.treeItem, 3);
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(1), 'ArrowRight'); // Focus first child  2nd level
+  await e2e.isFocused(selectors.treeItemAt(2));
```
Comment (layershifter) [inline packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts:15]:
```suggestion
  await e2e.isFocused(selectors.treeItemAt(2));

```

File: packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+  tree: `.${treeClassName}`,
+  treeItem: `.${treeItemClassName}`,
+  treeTitleAt: (itemIndex: number) => `.${treeItemClassName}:nth-of-type(${itemIndex}) .${treeTitleClassName}`,
+  treeItemAt: (itemIndex: number) => `.${treeItemClassName}:nth-of-type(${itemIndex}) `,
+};
+
+const navigateToLastLevel = async () => {
+  await e2e.focusOn(selectors.treeItemAt(1));
+  await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(1), 'ArrowRight'); // Expand first level item
+  await e2e.expectCount(selectors.treeItem, 3);
```
Comment (layershifter) [inline packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts:13]:
```suggestion
  await e2e.expectCount(selectors.treeItem, 3);

```

File: packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+    await navigateToLastLevel();
+  });
+
+  it('Should navigate up with left arrow', async () => {
+    await navigateToLastLevel();
+
+    await e2e.waitForSelectorAndPressKey(selectors.treeTitleAt(3), 'ArrowLeft'); // Focus parent 2nd level
+    await e2e.isFocused(selectors.treeItemAt(2));
+    await e2e.expectCount(selectors.treeItem, 4);
+    await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(2), 'ArrowLeft'); // Focus parent 1nd level and closes 3rd level
```
Comment (layershifter) [inline packages/fluentui/e2e/tests/treeKeyboardNavigation-test.ts:37]:
```suggestion

    await e2e.waitForSelectorAndPressKey(selectors.treeItemAt(2), 'ArrowLeft'); // Focus parent 1nd level and closes 3rd level
```

File: packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx [hunk 7]
```diff
@@ -26,6 +26,7 @@ import {
   shouldPreventDefaultOnKeyDown,
 } from '../../utils';
 import { ComponentEventHandler, FluentComponentStaticProps, ShorthandValue } from '../../types';
+import { TreeContext } from './utils/index';
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx:29]:
```suggestion
import { TreeContext } from './utils';
```

File: packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx [hunk 8]
```diff
@@ -127,6 +133,12 @@ export const TreeTitle: ComponentWithAs<'a', TreeTitleProps> & FluentComponentSt
         e.stopPropagation();
         handleClick(e);
       },
+      focusParent: e => {
+        e.preventDefault();
+        e.stopPropagation();
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx:138]:
```suggestion
```

Is it required?

File: packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx [hunk 9]
```diff
@@ -117,6 +118,11 @@ export const TreeTitle: ComponentWithAs<'a', TreeTitleProps> & FluentComponentSt
     indeterminate,
   } = props;
 
+  const handleFocusParent = e => {
+    _.invoke(props, 'onFocusParent', e, props);
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx:122]:
```suggestion
```

There is no `onFocusParent` in `TreeTitleProps`

File: packages/fluentui/react-northstar/src/components/Tree/TreeItem.tsx [hunk 10]
```diff
@@ -262,6 +263,7 @@ export const TreeItem: ComponentWithAs<'div', TreeItemProps> & FluentComponentSt
                 index,
                 selected,
                 selectable,
+                parent,
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Tree/TreeItem.tsx:266]: `parent` should be added to `TreeTitleProps` and `TreeTitle.propTypes`

**Review by layershifter — CHANGES_REQUESTED** [review]
Please address comments before merging

File: packages/fluentui/react-northstar/src/components/Tree/TreeItem.tsx (hunk 10 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Tree/TreeItem.tsx:266]: Done

**Comment by assuncaocharles** [comment]
> Please address comments before merging

Done

**Comment by assuncaocharles** [comment]
Ready to merge @layershifter ?

File: packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx [hunk 11]
```diff
@@ -127,6 +135,10 @@ export const TreeTitle: ComponentWithAs<'a', TreeTitleProps> & FluentComponentSt
         e.stopPropagation();
         handleClick(e);
       },
+      focusParent: e => {
+
+        handleFocusParent(e);
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx:140]:
```suggestion
        onFocusParent(props.parent);
```

File: packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx [hunk 12]
```diff
@@ -117,6 +121,10 @@ export const TreeTitle: ComponentWithAs<'a', TreeTitleProps> & FluentComponentSt
     indeterminate,
   } = props;
 
+  const handleFocusParent = e => {
+    onFocusParent(props.parent);
+  };
+
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Tree/TreeTitle.tsx:127]:
```suggestion
```

**Review by layershifter — APPROVED** [review]
