### PR TITLE
babel-make-styles: Correctly handling sequence expressions

### LINKED ISSUE #21009: makeStyles: Does not correctly handle sequence expressions
This problem affected #20918 and #20657:

```
ERROR in /mnt/vss/_work/1/s/packages/react-switch/src/components/Switch/useSwitchStyles.ts
Module build failed (from /mnt/vss/_work/1/s/packages/make-styles-webpack-loader/lib/index.js):
SyntaxError: /mnt/vss/_work/1/s/packages/react-switch/src/components/Switch/useSwitchStyles.ts: We met an unhandled case, this is a bug, please include a stacktrace and report it at https://github.com/microsoft/fluentui
  56 |     verticalAlign: 'bottom'
  57 |   },
> 58 |   unchecked: (_a = {}, _a[":hover ." + thumbClassName] = {
     |   ^
  59 |     ':before': {
  60 |       backgroundColor: react_theme_1.tokens.colorNeutralStrokeAccessibleHover
  61 |     }
    at File.buildCodeFrameError (/mnt/vss/_work/1/s/node_modules/@babel/core/lib/transformation/file/file.js:244:12)
    at NodePath.buildCodeFrameError (/mnt/vss/_work/1/s/node_modules/@babel/traverse/lib/path/index.js:133:21)
```

@layershifter and I traced it down to a minimal repro:

```tsx
import { makeStyles, MakeStylesStyle } from '@fluentui/react-make-styles';

const switchClassName = 'fui-Switch';
let _a: Record<string, MakeStylesStyle>;

export const useStyles = makeStyles({
  root:
    ((_a = {}),
    (_a[':hover .' + switchClassName] = {
      ':before': {
        backgroundColor: 'red',
      },
    }),
    _a),
});
```

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #21009
- [x] Include a change request file using `$ yarn change`

#### Description of changes

This PR adds the ability to the `babel-make-styles` plugin to handle sequence expressions like the one below:

```ts
import { makeStyles, MakeStylesStyle } from '@fluentui/react-make-styles';

const switchClassName = 'fui-Switch';
let _a: Record<string, MakeStylesStyle>;

export const useStyles = makeStyles({
  root:
    ((_a = {}),
    (_a[':hover .' + switchClassName] = {
      ':before': {
        backgroundColor: 'red',
      },
    }),
    _a),
});
```

A new fixture to test this was also added

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `55.684 kB`<br />`17.641 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |   `46.459 kB`<br />`13.39 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `23.702 kB`<br />`7.008 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |    `24.57 kB`<br />`7.308 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |   `22.209 kB`<br />`6.524 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |    `28.16 kB`<br />`8.088 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |    `33.495 kB`<br />`9.06 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `30.243 kB`<br />`8.801 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |    `36.39 kB`<br />`9.873 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `37.397 kB`<br />`8.682 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `48.473 kB`<br />`14.375 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `43.871 kB`<br />`13.166 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `7.587 kB`<br />`3.227 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `8.895 kB`<br />`3.675 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `7.778 kB`<br />`3.355 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `169.082 kB`<br />`47.656 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |   `32.184 kB`<br />`10.58 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |    `14.924 kB`<br />`5.39 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |   `10.035 kB`<br />`3.941 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |    `19.38 kB`<br />`6.365 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.294 kB`<br />`3.472 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `11.028 kB`<br />`4.487 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `103.621 kB`<br />`31.866 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `105.878 kB`<br />`32.212 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `95.761 kB`<br />`29.129 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |    `6.249 kB`<br />`2.163 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePopper</abbr>                                                                         |   `22.808 kB`<br />`7.935 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `13.687 kB`<br />`5.174 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/RangedSlider.fixture.js'>RangedSlider</abbr>                                                                        |  `41.101 kB`<br />`11.737 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |  `34.529 kB`<br />`10.573 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `27.042 kB`<br />`8.561 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `10.716 kB`<br />`4.213 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `14.018 kB`<br />`4.555 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `44.566 kB`<br />`15.426 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b43683a0936a3641c91d0c9cef24cb2bc1c9e5f0'>b43683a0936a3641c91d0c9cef24cb2bc1c9e5f0</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Avatar-mount_base.html">785</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Avatar-mount.html">822</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/BaseButton-mount_base.html">832</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/BaseButton-mount.html">812</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Breadcrumb-mount_base.html">2365</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Breadcrumb-mount.html">2380</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ButtonNext-mount_base.html">466</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ButtonNext-mount.html">459</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Checkbox-mount_base.html">1320</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Checkbox-mount.html">1341</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/CheckboxBase-mount_base.html">1117</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/CheckboxBase-mount.html">1149</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ChoiceGroup-mount_base.html">4185</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ChoiceGroup-mount.html">4099</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ComboBox-mount_base.html">873</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ComboBox-mount.html">859</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/CommandBar-mount_base.html">9484</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/CommandBar-mount.html">9723</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ContextualMenu-mount_base.html">7855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ContextualMenu-mount.html">7728</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DefaultButton-mount_base.html">1005</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DefaultButton-mount.html">995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DetailsRow-mount_base.html">3309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DetailsRow-mount.html">3241</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DetailsRowFast-mount_base.html">3370</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DetailsRowFast-mount.html">3322</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DetailsRowNoStyles-mount_base.html">3134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DetailsRowNoStyles-mount.html">3192</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Dialog-mount_base.html">2252</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Dialog-mount.html">2258</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DocumentCardTitle-mount_base.html">174</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/DocumentCardTitle-mount.html">158</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Dropdown-mount_base.html">2803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Dropdown-mount.html">2840</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FluentProviderNext-mount_base.html">1706</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FluentProviderNext-mount.html">1728</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FluentProviderWithTheme-mount_base.html">161</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FluentProviderWithTheme-mount.html">162</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">99</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FluentProviderWithTheme-virtual-rerender.html">99</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">182</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">184</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FocusTrapZone-mount_base.html">1603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FocusTrapZone-mount.html">1594</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FocusZone-mount_base.html">1594</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/FocusZone-mount.html">1561</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/IconButton-mount_base.html">1546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/IconButton-mount.html">1525</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Label-mount_base.html">336</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Label-mount.html">326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Layer-mount_base.html">2681</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Layer-mount.html">2559</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Link-mount_base.html">444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Link-mount.html">430</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/MakeStyles-mount_base.html">1611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/MakeStyles-mount.html">1643</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/MenuButton-mount_base.html">1296</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/MenuButton-mount.html">1299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/MessageBar-mount_base.html">1770</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/MessageBar-mount.html">1797</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Nav-mount_base.html">2860</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Nav-mount.html">2880</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/OverflowSet-mount_base.html">980</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/OverflowSet-mount.html">990</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Panel-mount_base.html">2220</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Panel-mount.html">2188</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Persona-mount_base.html">754</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Persona-mount.html">739</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Pivot-mount_base.html">1287</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Pivot-mount.html">1283</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/PrimaryButton-mount_base.html">1160</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/PrimaryButton-mount.html">1142</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Rating-mount_base.html">6679</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Rating-mount.html">6680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/SearchBox-mount_base.html">1158</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/SearchBox-mount.html">1172</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Shimmer-mount_base.html">2229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Shimmer-mount.html">2233</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Slider-mount_base.html">1746</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Slider-mount.html">1730</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/SpinButton-mount_base.html">4358</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/SpinButton-mount.html">4369</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Spinner-mount_base.html">399</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Spinner-mount.html">405</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/SplitButton-mount_base.html">2728</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/SplitButton-mount.html">2739</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Stack-mount_base.html">462</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Stack-mount.html">454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/StackWithIntrinsicChildren-mount_base.html">1490</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/StackWithIntrinsicChildren-mount.html">1488</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/StackWithTextChildren-mount_base.html">3976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/StackWithTextChildren-mount.html">3963</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/SwatchColorPicker-mount_base.html">9164</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/SwatchColorPicker-mount.html">9035</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/TagPicker-mount_base.html">2382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/TagPicker-mount.html">2323</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/TeachingBubble-mount_base.html">11491</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/TeachingBubble-mount.html">11431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Text-mount_base.html">385</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Text-mount.html">380</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/TextField-mount_base.html">1206</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/TextField-mount.html">1234</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ThemeProvider-mount_base.html">1043</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ThemeProvider-mount.html">1058</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ThemeProvider-virtual-rerender_base.html">569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ThemeProvider-virtual-rerender.html">545</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1627</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1582</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Toggle-mount_base.html">739</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/Toggle-mount.html">753</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/buttonNative-mount_base.html">137</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test/buttonNative-mount.html">127</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
ButtonMinimalPerf.default | [159](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ButtonMinimalPerf.default.html) | [148](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.07:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ButtonMinimalPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
SegmentMinimalPerf.default | [319](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/SegmentMinimalPerf.default.html) | [294](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.09:1
ChatWithPopoverPerf.default | [362](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ChatWithPopoverPerf.default.html) | [336](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.08:1
AvatarMinimalPerf.default | [195](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AvatarMinimalPerf.default.html) | [185](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.05:1
DividerMinimalPerf.default | [326](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DividerMinimalPerf.default.html) | [311](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.05:1
IconMinimalPerf.default | [556](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/IconMinimalPerf.default.html) | [528](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.05:1
FlexMinimalPerf.default | [258](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/FlexMinimalPerf.default.html) | [247](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.04:1
LabelMinimalPerf.default | [351](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/LabelMinimalPerf.default.html) | [339](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.04:1
GridMinimalPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/GridMinimalPerf.default.html) | [294](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.03:1
ListNestedPerf.default | [487](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ListNestedPerf.default.html) | [475](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ListNestedPerf.default_base.html) | 1.03:1
RadioGroupMinimalPerf.default | [395](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.03:1
SkeletonMinimalPerf.default | [312](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/SkeletonMinimalPerf.default.html) | [304](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.03:1
TextMinimalPerf.default | [306](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TextMinimalPerf.default.html) | [297](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.03:1
AlertMinimalPerf.default | [251](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AlertMinimalPerf.default.html) | [246](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.02:1
AttachmentMinimalPerf.default | [144](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AttachmentMinimalPerf.default.html) | [141](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.02:1
ButtonSlotsPerf.default | [482](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ButtonSlotsPerf.default.html) | [472](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.02:1
CardMinimalPerf.default | [496](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/CardMinimalPerf.default.html) | [486](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.02:1
DropdownManyItemsPerf.default | [603](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DropdownManyItemsPerf.default.html) | [589](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.02:1
HeaderSlotsPerf.default | [659](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/HeaderSlotsPerf.default.html) | [649](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.02:1
ImageMinimalPerf.default | [320](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ImageMinimalPerf.default.html) | [313](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [597](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/LoaderMinimalPerf.default.html) | [587](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
MenuButtonMinimalPerf.default | [1445](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1418](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.02:1
RefMinimalPerf.default | [213](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/RefMinimalPerf.default.html) | [209](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.02:1
AttachmentSlotsPerf.default | [919](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AttachmentSlotsPerf.default.html) | [909](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2300](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2280](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5466](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5413](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [2614](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DropdownMinimalPerf.default.html) | [2598](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
HeaderMinimalPerf.default | [316](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/HeaderMinimalPerf.default.html) | [312](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [1124](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/InputMinimalPerf.default.html) | [1116](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
LayoutMinimalPerf.default | [326](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/LayoutMinimalPerf.default.html) | [323](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3728](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3688](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
TableMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TableMinimalPerf.default.html) | [362](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.01:1
BoxMinimalPerf.default | [300](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/BoxMinimalPerf.default.html) | [299](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1497](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1501](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
DialogMinimalPerf.default | [669](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DialogMinimalPerf.default.html) | [666](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [3555](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/EmbedMinimalPerf.default.html) | [3545](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
ListMinimalPerf.default | [439](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ListMinimalPerf.default.html) | [441](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
MenuMinimalPerf.default | [746](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/MenuMinimalPerf.default.html) | [747](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
PortalMinimalPerf.default | [160](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/PortalMinimalPerf.default.html) | [160](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [1009](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ProviderMinimalPerf.default.html) | [1010](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1:1
ReactionMinimalPerf.default | [330](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ReactionMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1451](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/SliderMinimalPerf.default.html) | [1453](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [583](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/StatusMinimalPerf.default.html) | [582](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
TableManyItemsPerf.default | [1630](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TableManyItemsPerf.default.html) | [1636](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3668](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/CustomToolbarPrototype.default.html) | [3674](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
ToolbarMinimalPerf.default | [824](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ToolbarMinimalPerf.default.html) | [820](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1:1
TooltipMinimalPerf.default | [910](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TooltipMinimalPerf.default.html) | [908](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
AccordionMinimalPerf.default | [133](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AccordionMinimalPerf.default.html) | [135](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.99:1
AnimationMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AnimationMinimalPerf.default.html) | [368](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [576](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ChatMinimalPerf.default.html) | [582](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
ListWith60ListItems.default | [563](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ListWith60ListItems.default.html) | [566](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1479](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1497](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
CarouselMinimalPerf.default | [412](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/CarouselMinimalPerf.default.html) | [421](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.98:1
ChatDuplicateMessagesPerf.default | [263](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [268](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.98:1
ItemLayoutMinimalPerf.default | [1022](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1045](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.98:1
PopupMinimalPerf.default | [516](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/PopupMinimalPerf.default.html) | [529](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.98:1
TreeMinimalPerf.default | [696](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TreeMinimalPerf.default.html) | [712](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.98:1
TreeWith60ListItems.default | [162](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TreeWith60ListItems.default.html) | [166](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.98:1
VideoMinimalPerf.default | [558](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/VideoMinimalPerf.default.html) | [570](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.98:1
FormMinimalPerf.default | [351](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/FormMinimalPerf.default.html) | [363](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.97:1
ListCommonPerf.default | [533](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ListCommonPerf.default.html) | [550](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/ListCommonPerf.default_base.html) | 0.97:1
RosterPerf.default | [1010](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/RosterPerf.default.html) | [1039](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/RosterPerf.default_base.html) | 0.97:1
TextAreaMinimalPerf.default | [431](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TextAreaMinimalPerf.default.html) | [446](https://fluentuipr.z22.web.core.windows.net/pull/21010/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.97:1

</details><div id="perfComment9423"/>

File: packages/babel-make-styles/src/plugin.ts [hunk 1]
```diff
@@ -434,6 +435,20 @@ function processDefinitions(
         state.styleNodes?.push({ kind: 'LAZY_MEMBER', nodePath: stylesPath });
         return;
       }
+
+      /**
+       * A scenario when slots styles are represented by a function call that eventually evaluates to an object.
```
Comment (layershifter) [inline packages/babel-make-styles/src/plugin.ts:440]:
```suggestion
       * A scenario when slots styles are represented by a sequence expression.
```

**Review by layershifter — APPROVED** [review]
