### PR TITLE
Combobox: Fix issue where getActiveDescendantValue would sometimes return -listundefined

### LINKED ISSUE #12556: ComboBox with placeholder does not have valid aria-attr-value
### Environment Information

- **Package version(s)**: 7.98.0
- **Browser and OS versions**: Chrome, Edge

### Describe the issue:

When using ComboBox with placeholder prop, there is an accessibility issue when using App Insights - Fast Pass. See below:

image

### Please provide a reproduction of the issue in a codepen:

Code pen: https://codepen.io/kejatura/pen/YzXmWXa?editors=1010
1. Enable drop down in combobox, and leave drop down list as is.
2. Run App Insights - Fast Pass, and notice error in input field.

#### Actual behavior:

There is an invalid aria attribute: aria-activedescendant, where combobox has a '-listundefined' in its value.  

#### Expected behavior:

'-listundefined' should contain the number of items in list, i.e: '-list4', besides undefined; to ensure this passes the accessibility fast pass test.

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #12556
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Combobox: Fix an issue where getActiveDescendantValue would sometimes return <listId>-listundefined

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui/pull/12599)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -77,14 +77,14 @@ enum HoverStatus {
   default = -1,
 }
 
-const ScrollIdleDelay = 250 /* ms */;
+const ScrollIdleDelay = 250; /* ms */
```
Comment (khmakoto) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx:80]: 🤣

File: change/office-ui-fabric-react-2020-04-07-16-18-40-fix-combobox-activedescendant.json [hunk 2]
```diff
@@ -0,0 +1,9 @@
+{
+  "type": "patch",
+  "comment": "Combobox: Fix getActiveDescendantValue",
```
Comment (khmakoto) [inline change/office-ui-fabric-react-2020-04-07-16-18-40-fix-combobox-activedescendant.json:3]:
```suggestion
  "comment": "Combobox: Fix getActiveDescendantValue would sometimes return -listundefined.",
```
