### PR TITLE
fix(Portal|useId): make implementation compatible with SSR

### LINKED ISSUE #17892: @fluentui/react-utilities: useId() is not SSR safe
### Environment Information

- **Package version(s)**: @fluentui/react-utilities@9.0.0-alpha.17
- **Browser and OS versions**: NA

#### Actual behavior:

Any usage of `useId()` produces hydration error, for example:

```tsx
Warning: Prop `className` did not match. Server: "theme-provider1 __7assp50 f16th3vw fpnz0vo0 f1kx028l flcnb000 f1du0uop" Client: "theme-provider0 __7assp50 f16th3vw fpnz0vo0 f1kx028l flcnb000 f1du0uop"
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: Normal
Products/sites affected: (if applicable)

### LINKED ISSUE #17901: @fluentui/react-tooltip: throws an error during SSR
### Environment Information

- **Package version(s)**: @fluentui/react-tooltip@alpha
- **Browser and OS versions**: NA

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/pensive-agnesi-9o8mx

#### Actual behavior:

Warning is produced 🚨

```
react-dom.development.js:67 Warning: Expected server HTML to contain a matching <div> in <div>.
    at div
    at Tooltip (http://localhost:3000/_next/static/chunks/pages/index.js?ts=1619013336321:15686:79)
    at TooltipTrigger (http://localhost:3000/_next/static/chunks/pages/index.js?ts=1619013336321:16261:93)
    at div
    at MenuStory
    at TabsterProvider (http://localhost:3000/_next/static/chunks/pages/index.js?ts=1619013336321:13197:17)
    at TooltipProvider (http://localhost:3000/_next/static/chunks/pages/index.js?ts=1619013336321:15947:95)
```

It happens because we always render `Tooltip`, but `.createPortal()` is conditional:

https://github.com/microsoft/fluentui/blob/7feded422987e9c82f3250f419ab62118a52f9d4/packages/react-tooltip/src/components/TooltipTrigger/renderTooltipTrigger.tsx#L17-L19

#### from client

image

#### from server

image

(the same place but from server's response)

#### Expected behavior:

No warnings 🤟

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by layershifter**
- [X] Addresses an existing issue: Fixes #17892 opens a way to solve #17901
- [x] Include a change request file using `$ yarn change`

## Description of changes

This PR updates implementation of `Portal` component and `useId()` hook to make them compatible with server side rendering i.e. avoid warnings.

### `<SSRProvider />`

When using SSR with Fluent UI, applications must be wrapped in an `<SSRProvider />`. The auto incrementing id counter is stored in a context, this ensures that auto generated ids are consistent between the client and server.

[`@react-aria`](https://github.com/adobe/react-spectrum/blob/1e2b7f280a04ead83e21b27fa580eb189e5f4186/packages/%40react-aria/ssr/src/SSRProvider.tsx) uses similar implementation.

### `<Portal />`

`.createPortal()` is a DOM-related API and can't be used in SSR, currently we are will render `null` during SSR:

https://github.com/microsoft/fluentui/blob/256048ed68e394caa6415a6132a0baa8905629d5/packages/react-portal/src/components/Portal/renderPortal.tsx#L8-L12

This produces warnings as results of SSR and client rendering are not consistent 😥 _This affects only `Portal`s that are initially rendered by a server._

```
Warning: Did not expect server HTML to contain a <button> in <div>.
    at div
    at Tooltip (webpack-internal:///./node_modules/@fluentui/react-tooltip/lib/components/Tooltip/Tooltip.js:18:79)
    at TooltipTrigger (webpack-internal:///./node_modules/@fluentui/react-tooltip/lib/components/TooltipTrigger/TooltipTrigger.js:13:93)
```

(see #17901, for more details)

When `SSRProvider` is used, we will skip initial rendering of `Portal` on client to match server's output i.e. `Portal`'s content will be rendered after hydration. In the same time, it avoids double rendering for client side only apps 🚀

Prototypes of this behavior you can check on following Codesandboxes:
- Next.js app: https://codesandbox.io/s/crazy-meitner-943qz (no warnings 🤘)
- Create React App: https://codesandbox.io/s/zen-lalande-smgeu

---

Tests that are using `useId()` hook have been updated to reset ids (this affected snapshots).

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Avatar-mount_base.html">893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Avatar-mount.html">912</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/BaseButton-mount_base.html">915</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/BaseButton-mount.html">909</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Breadcrumb-mount_base.html">44000</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Breadcrumb-mount.html">43991</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ButtonNext-mount_base.html">521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ButtonNext-mount.html">521</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Checkbox-mount_base.html">1559</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Checkbox-mount.html">1563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/CheckboxBase-mount_base.html">1278</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/CheckboxBase-mount.html">1304</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ChoiceGroup-mount_base.html">4676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ChoiceGroup-mount.html">4743</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ComboBox-mount_base.html">976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ComboBox-mount.html">1024</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/CommandBar-mount_base.html">10286</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/CommandBar-mount.html">10212</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ContextualMenu-mount_base.html">6116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ContextualMenu-mount.html">6067</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DefaultButton-mount_base.html">1136</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DefaultButton-mount.html">1121</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DetailsRow-mount_base.html">3587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DetailsRow-mount.html">3686</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DetailsRowFast-mount_base.html">3658</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DetailsRowFast-mount.html">3683</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DetailsRowNoStyles-mount_base.html">3474</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DetailsRowNoStyles-mount.html">3517</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Dialog-mount_base.html">1479</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Dialog-mount.html">1493</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DocumentCardTitle-mount_base.html">1922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/DocumentCardTitle-mount.html">1853</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Dropdown-mount_base.html">3238</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Dropdown-mount.html">3252</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/FocusTrapZone-mount_base.html">1825</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/FocusTrapZone-mount.html">1840</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/FocusZone-mount_base.html">1793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/FocusZone-mount.html">1769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/IconButton-mount_base.html">1694</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/IconButton-mount.html">1710</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Label-mount_base.html">341</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Label-mount.html">339</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Layer-mount_base.html">1790</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Layer-mount.html">1814</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Link-mount_base.html">464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Link-mount.html">485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/MakeStyles-mount_base.html">1826</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/MakeStyles-mount.html">1817</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/MenuButton-mount_base.html">1439</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/MenuButton-mount.html">1496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/MessageBar-mount_base.html">2037</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/MessageBar-mount.html">2033</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Nav-mount_base.html">3294</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Nav-mount.html">3257</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/OverflowSet-mount_base.html">1049</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/OverflowSet-mount.html">1045</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Panel-mount_base.html">1413</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Panel-mount.html">1427</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Persona-mount_base.html">830</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Persona-mount.html">821</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Pivot-mount_base.html">1441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Pivot-mount.html">1387</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/PrimaryButton-mount_base.html">1296</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/PrimaryButton-mount.html">1275</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Rating-mount_base.html">7609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Rating-mount.html">7645</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/SearchBox-mount_base.html">1346</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/SearchBox-mount.html">1338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Shimmer-mount_base.html">2508</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Shimmer-mount.html">2551</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Slider-mount_base.html">1967</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Slider-mount.html">2004</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/SpinButton-mount_base.html">4946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/SpinButton-mount.html">5020</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Spinner-mount_base.html">413</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Spinner-mount.html">424</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/SplitButton-mount_base.html">3265</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/SplitButton-mount.html">3158</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Stack-mount_base.html">492</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Stack-mount.html">514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/StackWithIntrinsicChildren-mount_base.html">1511</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/StackWithIntrinsicChildren-mount.html">1514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/StackWithTextChildren-mount_base.html">4524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/StackWithTextChildren-mount.html">4494</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/SwatchColorPicker-mount_base.html">11123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/SwatchColorPicker-mount.html">10212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Tabs-mount_base.html">1429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Tabs-mount.html">1389</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/TagPicker-mount_base.html">2431</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/TagPicker-mount.html">2405</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/TeachingBubble-mount_base.html">11969</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/TeachingBubble-mount.html">11936</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Text-mount_base.html">415</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Text-mount.html">421</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/TextField-mount_base.html">1323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/TextField-mount.html">1366</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ThemeProvider-mount_base.html">1184</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ThemeProvider-mount.html">1194</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ThemeProvider-virtual-rerender_base.html">618</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ThemeProvider-virtual-rerender.html">611</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ThemeProviderNext-mount_base.html">9217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/ThemeProviderNext-mount.html">9214</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Toggle-mount_base.html">847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/Toggle-mount.html">808</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/buttonNative-mount_base.html">116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test/buttonNative-mount.html">103</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
ListWith60ListItems.default | [689](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListWith60ListItems.default.html) | [644](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.07:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListWith60ListItems.default.regression.txt)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.17](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Avatar.Fluent.html) | 0.47 | 0.36:1 | 2000 | 340
🦄 | Button.Fluent | [0.1](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Button.Fluent.html) | 0.2 | 0.5:1 | 5000 | 519
🔧 | Checkbox.Fluent | [0.63](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Checkbox.Fluent.html) | 0.35 | 1.8:1 | 1000 | 629
🦄 | Dialog.Fluent | [0.15](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Dialog.Fluent.html) | 0.22 | 0.68:1 | 5000 | 746
🔧 | Dropdown.Fluent | [3.06](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Dropdown.Fluent.html) | 0.39 | 7.85:1 | 1000 | 3063
🔧 | Icon.Fluent | [0.13](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Icon.Fluent.html) | 0.06 | 2.17:1 | 5000 | 655
🦄 | Image.Fluent | [0.08](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Image.Fluent.html) | 0.13 | 0.62:1 | 5000 | 395
🔧 | Slider.Fluent | [1.57](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Slider.Fluent.html) | 0.44 | 3.57:1 | 1000 | 1568
🔧 | Text.Fluent | [0.07](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Text.Fluent.html) | 0.04 | 1.75:1 | 5000 | 359
🦄 | Tooltip.Fluent | [0.15](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Tooltip.Fluent.html) | 0.9 | 0.17:1 | 5000 | 730
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
DividerMinimalPerf.default | [394](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DividerMinimalPerf.default.html) | [350](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.13:1
Image.Fluent | [395](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Image.Fluent.html) | [357](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Image.Fluent_base.html) | 1.11:1
RefMinimalPerf.default | [271](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/RefMinimalPerf.default.html) | [248](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.09:1
Icon.Fluent | [655](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Icon.Fluent.html) | [599](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Icon.Fluent_base.html) | 1.09:1
IconMinimalPerf.default | [668](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/IconMinimalPerf.default.html) | [619](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.08:1
TreeWith60ListItems.default | [194](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TreeWith60ListItems.default.html) | [180](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.08:1
AnimationMinimalPerf.default | [433](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AnimationMinimalPerf.default.html) | [406](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.07:1
ButtonMinimalPerf.default | [182](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonMinimalPerf.default.html) | [170](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.07:1
ButtonSlotsPerf.default | [572](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonSlotsPerf.default.html) | [535](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.07:1
PortalMinimalPerf.default | [181](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/PortalMinimalPerf.default.html) | [169](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.07:1
AlertMinimalPerf.default | [286](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AlertMinimalPerf.default.html) | [269](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.06:1
GridMinimalPerf.default | [362](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/GridMinimalPerf.default.html) | [341](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.06:1
ListNestedPerf.default | [591](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListNestedPerf.default.html) | [555](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListNestedPerf.default_base.html) | 1.06:1
ReactionMinimalPerf.default | [399](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ReactionMinimalPerf.default.html) | [380](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.05:1
SkeletonMinimalPerf.default | [386](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/SkeletonMinimalPerf.default.html) | [367](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.05:1
VideoMinimalPerf.default | [679](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/VideoMinimalPerf.default.html) | [649](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.05:1
Tooltip.Fluent | [730](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Tooltip.Fluent.html) | [693](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Tooltip.Fluent_base.html) | 1.05:1
ItemLayoutMinimalPerf.default | [1303](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1257](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [386](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/LayoutMinimalPerf.default.html) | [371](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [490](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TextAreaMinimalPerf.default.html) | [470](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
AttachmentSlotsPerf.default | [1158](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1129](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.03:1
DialogMinimalPerf.default | [752](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DialogMinimalPerf.default.html) | [728](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.03:1
ListMinimalPerf.default | [523](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListMinimalPerf.default.html) | [507](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.03:1
AttachmentMinimalPerf.default | [171](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AttachmentMinimalPerf.default.html) | [168](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.02:1
CheckboxMinimalPerf.default | [2802](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2754](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.02:1
ImageMinimalPerf.default | [372](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ImageMinimalPerf.default.html) | [363](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.02:1
InputMinimalPerf.default | [1283](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/InputMinimalPerf.default.html) | [1257](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.02:1
PopupMinimalPerf.default | [719](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/PopupMinimalPerf.default.html) | [703](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.02:1
SegmentMinimalPerf.default | [366](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/SegmentMinimalPerf.default.html) | [359](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [1913](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TableManyItemsPerf.default.html) | [1881](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
TextMinimalPerf.default | [357](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TextMinimalPerf.default.html) | [350](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.02:1
Checkbox.Fluent | [629](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Checkbox.Fluent.html) | [616](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Checkbox.Fluent_base.html) | 1.02:1
Dialog.Fluent | [746](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Dialog.Fluent.html) | [731](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Dialog.Fluent_base.html) | 1.02:1
AvatarMinimalPerf.default | [212](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AvatarMinimalPerf.default.html) | [209](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.01:1
ChatWithPopoverPerf.default | [393](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ChatWithPopoverPerf.default.html) | [390](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [696](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DropdownManyItemsPerf.default.html) | [691](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.01:1
FormMinimalPerf.default | [420](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/FormMinimalPerf.default.html) | [417](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [701](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/LoaderMinimalPerf.default.html) | [693](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3718](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3699](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
Dropdown.Fluent | [3063](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Dropdown.Fluent.html) | [3026](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Dropdown.Fluent_base.html) | 1.01:1
ButtonUseCssPerf.default | [798](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonUseCssPerf.default.html) | [801](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 1:1
CarouselMinimalPerf.default | [478](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/CarouselMinimalPerf.default.html) | [477](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [45453](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DatepickerMinimalPerf.default.html) | [45399](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4123](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/EmbedMinimalPerf.default.html) | [4128](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
FlexMinimalPerf.default | [302](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/FlexMinimalPerf.default.html) | [301](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/LabelMinimalPerf.default.html) | [405](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1546](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1548](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [688](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/StatusMinimalPerf.default.html) | [690](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
Avatar.Fluent | [340](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Avatar.Fluent.html) | [339](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Avatar.Fluent_base.html) | 1:1
Slider.Fluent | [1568](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Slider.Fluent.html) | [1565](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Slider.Fluent_base.html) | 1:1
Text.Fluent | [359](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Text.Fluent.html) | [359](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Text.Fluent_base.html) | 1:1
ButtonOverridesMissPerf.default | [1649](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1660](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
ButtonUseCssNestingPerf.default | [1056](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1067](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 0.99:1
ChatDuplicateMessagesPerf.default | [289](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [3017](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DropdownMinimalPerf.default.html) | [3040](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
HeaderSlotsPerf.default | [770](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/HeaderSlotsPerf.default.html) | [776](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.99:1
ListCommonPerf.default | [626](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListCommonPerf.default.html) | [633](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ListCommonPerf.default_base.html) | 0.99:1
MenuMinimalPerf.default | [851](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/MenuMinimalPerf.default.html) | [859](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/MenuMinimalPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1649](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1673](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
TableMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TableMinimalPerf.default.html) | [409](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.99:1
CustomToolbarPrototype.default | [3734](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/CustomToolbarPrototype.default.html) | [3764](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.99:1
TooltipMinimalPerf.default | [959](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TooltipMinimalPerf.default.html) | [966](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.99:1
Button.Fluent | [519](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Button.Fluent.html) | [526](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/Button.Fluent_base.html) | 0.99:1
BoxMinimalPerf.default | [346](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/BoxMinimalPerf.default.html) | [353](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/BoxMinimalPerf.default_base.html) | 0.98:1
ChatMinimalPerf.default | [615](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ChatMinimalPerf.default.html) | [630](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.98:1
SliderMinimalPerf.default | [1542](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/SliderMinimalPerf.default.html) | [1567](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.98:1
TreeMinimalPerf.default | [793](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TreeMinimalPerf.default.html) | [812](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.98:1
CardMinimalPerf.default | [545](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/CardMinimalPerf.default.html) | [562](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.97:1
HeaderMinimalPerf.default | [364](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/HeaderMinimalPerf.default.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.97:1
RosterPerf.default | [1151](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/RosterPerf.default.html) | [1191](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/RosterPerf.default_base.html) | 0.97:1
ProviderMinimalPerf.default | [964](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ProviderMinimalPerf.default.html) | [998](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.97:1
ToolbarMinimalPerf.default | [939](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ToolbarMinimalPerf.default.html) | [978](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.96:1
RadioGroupMinimalPerf.default | [431](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [458](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.94:1
AccordionMinimalPerf.default | [157](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AccordionMinimalPerf.default.html) | [175](https://fluentuipr.z22.web.core.windows.net/pull/17924/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.9:1

</details><div id="perfComment9423"/>

File: packages/react-utilities/src/ssr/SSRContext.tsx [hunk 1]
```diff
@@ -0,0 +1,58 @@
+import * as React from 'react';
+import { isSSR } from './isSSR';
+
+/**
+ * To support SSR, the auto incrementing id counter is stored in a context. This allows it to be reset on every request
+ * to ensure the client and server are consistent. There is also a prefix counter that is used to support async loading
+ * components.
+ *
+ * Each async boundary must be wrapped in an SSR provider, which increments the prefix and resets the current id
+ * counter. This ensures that async loaded components have consistent ids regardless of the loading order.
```
Comment (layershifter) [inline packages/react-utilities/src/ssr/SSRContext.tsx:10]:
```suggestion
 * To support SSR, the auto incrementing id counter is stored in a context. This allows it to be reset on every request
 * to ensure the client and server are consistent.
```

File: packages/react-portal/src/components/Portal/Portal.types.ts [hunk 2]
```diff
@@ -10,6 +10,13 @@ export interface PortalProps {
    * @defaultValue a new element on document.body without any styling
    */
   mountNode?: HTMLDivElement | null;
+  /**
+   * Has an affect only when server side rendering is used. Indicates that a Portal will be rendered only on client and
+   * it's fine to skip initial null render. Useful for Dialogs and similar components that are never rendered initially.
+   *
+   * @defaultValue false
+   */
+  isRenderedOnlyOnClient?: boolean;
```
Comment (ling1726) [inline packages/react-portal/src/components/Portal/Portal.types.ts:19]: It might be clearer to use invert the prop and set a `true` default value

```suggestion
  /**
   * This component supports Server Side Rendering (SSR) with a null render on the server
   * For components like Dialogs which are never rendered initially set this to `false` to skip the initial null render
   * NOTE: This prop has no effect on non-SSR apps
   *
   * @defaultValue false
   */
  requireServerRender?: boolean;
```

File: packages/react-portal/src/components/Portal/Portal.types.ts [hunk 3]
```diff
@@ -18,4 +25,7 @@ export interface PortalProps {
   // disableEventBubbling?: 'first' | 'last';
 }
 
-export interface PortalState extends PortalProps {}
+export interface PortalState extends PortalProps {
+  /** Indicates if a Portal can be rendered. */
```
Comment (ling1726) [inline packages/react-portal/src/components/Portal/Portal.types.ts:29]: nit: consistency

```suggestion
  /** Indicates if a Portal should be rendered. */
```

File: packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts [hunk 4]
```diff
@@ -1,5 +1,5 @@
 import * as React from 'react';
-import { isSSR } from '../utils/index';
+import { isSSR } from '../ssr/index';
```
Comment (ling1726) [inline packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts:2]: what do you think about using `useIsSSR` instead that also reads from context in addition to the `document` and `window` checks ?

**Review by ling1726 — APPROVED** [review]

File: packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts (hunk 4 above)
Comment (layershifter) [reply packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts:2]: I was thinking about, but then we will still need a function for cases like this:

```tsx
export const useIsomorphicLayoutEffect: typeof React.useEffect = isSSR() ? React.useEffect : React.useLayoutEffect;
```

Comment (ling1726) [reply packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts:2]: what if `isSSR` stays internal to utilities ? I can't imagine components really needing the pure function over context

File: packages/react-portal/src/components/Portal/Portal.types.ts (hunk 2 above)
Comment (layershifter) [reply packages/react-portal/src/components/Portal/Portal.types.ts:19]: TBH I don't know what is a better option there 😅 @miroslavstastny @behowell do you have any suggestions?

File: packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts (hunk 4 above)
Comment (layershifter) [reply packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts:2]: I am thinking about pure `canUseDOM()` that can be used in utils and `useIsSSR()` for components? WDYT?

Comment (ling1726) [reply packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts:2]: Nice, that would remove the double SSR with `useIsSSR` I approve 👍👍

Comment (layershifter) [reply packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts]: Done in bf6fb05.

File: packages/react-portal/src/components/Portal/Portal.types.ts (hunk 2 above)
Comment (layershifter) [reply packages/react-portal/src/components/Portal/Portal.types.ts]: I removed this for now, we can add it later if it will become an issue for perf.

File: packages/react-tooltip/src/components/TooltipTrigger/renderTooltipTrigger.tsx [hunk 5]
```diff
@@ -14,7 +14,7 @@ export const renderTooltipTrigger = (state: TooltipTriggerState) => {
   return (
     <>
       {state.children}
-      {isSSR() || state.tooltipContainer === undefined
+      {!canUseDOM() || state.tooltipContainer === undefined
```
Comment (layershifter) [inline packages/react-tooltip/src/components/TooltipTrigger/renderTooltipTrigger.tsx:17]: I will integrate `Portal` there in a follow up PR.

File: packages/react-portal/src/components/Portal/usePortalMountNode.ts [hunk 6]
```diff
@@ -17,7 +17,7 @@ export const usePortalMountNode = (options: UsePortalMountNodeOptions) => {
   const { targetDocument, dir } = useFluent();
 
   const element = React.useMemo(() => {
-    if (isSSR() || targetDocument === undefined || options.disabled) {
+    if (!canUseDOM() || targetDocument === undefined || options.disabled) {
```
Comment (ling1726) [inline packages/react-portal/src/components/Portal/usePortalMountNode.ts:20]: why can't you use `useIsSSR` here ? there's no global scope to worry about here

**Review by ling1726 — APPROVED** [review]

File: packages/react-utilities/src/ssr/SSRContext.tsx [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+ */
+export const SSRProvider: React.FC = props => {
+  const value: SSRContextValue = React.useMemo(() => ({ current: 0 }), []);
+
+  return <SSRContext.Provider value={value}>{props.children}</SSRContext.Provider>;
+};
+
+/**
+ * Returns whether the component is currently being server side rendered or hydrated on the client. Can be used to delay
+ * browser-specific rendering until after hydration.
```
Comment (layershifter) [inline packages/react-utilities/src/ssr/SSRContext.tsx:46]:
```suggestion
 * browser-specific rendering until after hydration. May cause re-renders on a client when is used within SSRProvider.
```

File: packages/react-portal/src/components/Portal/usePortalMountNode.ts (hunk 6 above)
Comment (layershifter) [reply packages/react-portal/src/components/Portal/usePortalMountNode.ts:20]: Technically, we don't this check there at all as `targetDocument` will be `undefined` in SSR.

---

> why can't you use `useIsSSR` here ? there's no global scope to worry about here

- `useIsSSR()` is a hook, so I can't use inside `.useMemo()` 😯
- `useIsSSR()` can cause a re-render 😐
- we don't care there about SSR, we can if we can use DOM 😋

Comment (ling1726) [reply packages/react-portal/src/components/Portal/usePortalMountNode.ts:20]: > targetDocument will be undefined in SSR.

That's a good point, let's remove it... the `targetDocument` check is for TS to narrow the type from `undefined`. I don't really see a case for `canUseDOM` at least in components since you'd be pulling the target document from fluent context

Comment (layershifter) [reply packages/react-portal/src/components/Portal/usePortalMountNode.ts:20]: Done 😉

**Review by behowell — APPROVED** [review]

File: packages/react-utilities/src/hooks/useId.ts [hunk 8]
```diff
@@ -1,31 +1,25 @@
...
-  return (prefix || '') + id++;
-}
+import { defaultSSRContextValue, useSSRContext } from '../ssr/index';
 
+/**
+ * Resets generated IDs, should be used only in tests.
+ *
+ * @private
+ */
 export function resetIds(): void {
```
[the remark this answers is not in the document]
Comment (layershifter) [reply packages/react-utilities/src/hooks/useId.ts:9]: Good idea, renamed 👍

File: packages/react-utilities/src/ssr/SSRContext.tsx [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+}
+
+/**
+ * When using SSR with Fluent UI, applications must be wrapped in an SSRProvider. This ensures that auto generated ids
+ * are consistent between the client and server.
+ *
+ * @public
+ */
+export const SSRProvider: React.FC = props => {
+  const value: SSRContextValue = React.useMemo(() => ({ current: 0 }), []);
```
[the remark this answers is not in the document]
Comment (layershifter) [reply packages/react-utilities/src/ssr/SSRContext.tsx:39]: Good call, yeah, it should be 👍

File: packages/react-portal/src/components/Portal/usePortal.ts [hunk 10]
```diff
@@ -7,19 +8,17 @@ const mergeProps = makeMergeProps<PortalState>();
...
  *
  * @param props - props from this instance of Portal
- * @param ref - reference to root HTMLElement of Portal
  * @param defaultProps - (optional) default prop values provided by the implementing type
- *
  */
 export const usePortal = (props: PortalProps, defaultProps?: PortalProps): PortalState => {
-  const state = mergeProps(defaultProps ?? {}, props);
-
+  const state = mergeProps((defaultProps ?? {}) as PortalState, props);
```
[the remark this answers is not in the document]
Comment (layershifter) [reply packages/react-portal/src/components/Portal/usePortal.ts:17]: Applied, thanks 👍
