### PR TITLE
fix(react-storybook-addon-export-to-sandbox):  adjust selector to support SB 10

### LINKED ISSUE #35789: [Bug]: Storybook 10 private API changes affecting you
### Area

storybook

### Environment

```shell
n/a
```

### Current Behavior

You currently rely on some Storybook internals to power `react-storybook-addon-export-to-sandbox`:
* Stories in docs using an `#anchor--*` ID
* The specific formatting of the ActionBar under each story canvas

Those are undergoing changes in Storybook 10 minor releases.

### Expected Behavior

The '#anchor--' ID can now sometimes be `#anchor--primary-` to avoid a duplicate ID accessibility violation on primary stories (https://github.com/storybookjs/storybook/issues/33363). You will need to adjust your selectors accordingly for the primary story of each docs page.

We are replacing the ActionBar area inside Previews by Button components under Preview, you could reuse `storybook/internal/components`'s Button for matching styling going forward. You will probably need to adjust your selectors to correctly identify the Button area.

### Reproduction

https://storybooks.fluentui.dev/react/?path=/docs/components-checkbox--docs

### Steps to reproduce

1. Navigate to any autodocs page on your Storybook, post SB10 migration
2. Notice that your package fails to add buttons to primary stories
3. Notice that there likely are styling / selector errors

### Suggested severity

Low - Has or doesn't need a workaround

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by mainframev**
Storybook 10 changes anchor IDs for primary stories in docs mode. In SB9, all story containers use id="anchor--{storyId}". In SB10, the primary block renders the primary story with id="anchor--primary--{storyId}" (https://github.com/storybookjs/storybook/pull/33384).

## Previous Behavior

tested in separate SB 10 setup

`Error: css selector: #anchor--example-button--primary .docs-story, doesn't exist` 

Screenshot 2026-02-27 at 21 33 49

## New Behavior

Screenshot 2026-02-27 at 20 37 35

## Related Issue(s)

- Fixes #35789

### CODE REVIEW

File: packages/react-components/react-storybook-addon-export-to-sandbox/src/sandbox-utils.ts [hunk 1]
```diff
@@ -14,7 +14,9 @@ export function addHiddenInput(form: HTMLFormElement, name: string, value: strin
 }
 
 export function prepareSandboxContainers(context: StoryContext) {
-  const docsSelector = `#anchor--${context.id} .docs-story`;
+  // Support both SB9 (#anchor--{id}) and SB10 (#anchor--primary--{id}) anchor ID formats
```
Comment (Hotell) [inline packages/react-components/react-storybook-addon-export-to-sandbox/src/sandbox-utils.ts]:
```suggestion
  // Support anchor ID formats for our Storybook major versions range. 
  // 10< `#anchor--{id}`
  // >=10 `#anchor--primary--{id}`
```
