### PR TITLE
fix(TreeTitle): Selectable TreeTitle should have background hover

### LINKED ISSUE #15135: Selectable Tree should have hover background for items
### Environment Information

- **Package version(s): @fluentui/react-northstar@0.51.0
- **Browser and OS versions: Chrome Version 85.0.4183.102

#### Actual behavior:

Hovering items as no style change or indicator. 

#### Expected behavior:

As per spec, item should have background to indicate ( Similar to selectable list ).

Screen Shot 2020-09-19 at 13 17 18

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #15135
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

This PR adds background hover to selectable `Tree` and proper right padding following design specs. 

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/themes/teams/components/Tree/treeTitleStyles.ts [hunk 1]
```diff
@@ -13,6 +13,12 @@ export const treeTitleStyles: ComponentSlotStylesPrepared<TreeTitleStylesProps,
     cursor: 'pointer',
     color: v.color,
     position: 'relative',
+    paddingRight: v.paddingRight,
+    ...(p.selectable && {
+      ':hover': {
+        background: v.hoverBackground,
+      },
+    }),
```
Comment (pompomon) [inline packages/fluentui/react-northstar/src/themes/teams/components/Tree/treeTitleStyles.ts:21]:
```suggestion
```

File: packages/fluentui/react-northstar/src/themes/teams/components/Tree/treeTitleStyles.ts [hunk 2]
```diff
@@ -13,6 +13,12 @@ export const treeTitleStyles: ComponentSlotStylesPrepared<TreeTitleStylesProps,
...
     ...(p.selectable && {
       display: 'flex',
```
Comment (pompomon) [inline packages/fluentui/react-northstar/src/themes/teams/components/Tree/treeTitleStyles.ts:23]:
```suggestion
    ...(p.selectable && {
        ':hover': {
          background: v.hoverBackground,
       },
      display: 'flex',
```
_nit_

**Review by pompomon — APPROVED** [review]

File: packages/fluentui/react-northstar/src/themes/teams/components/Tree/treeTitleStyles.ts (hunk 2 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/themes/teams/components/Tree/treeTitleStyles.ts:18]: Done
