### PR TITLE
Remove additional focus ring from `Input`, `SpinButton`, and `Textarea` when using macOS safari

### LINKED ISSUE #23167: [Bug]: Safari on macOS has additional focus ring on inputs
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://react.fluentui.dev/

### Bug Description

Safari renders the default webkit focus outline on Textarea, Spinbutton, and Input. We should add the vendor-prefixed `-webkit-` style to remove it:
Input component showing an inner light blue focus ring
textarea showing a light blue focus ring around the control
spinbutton showing the same focus ring as input

Related issue: #21296

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by sopranopillow**
## Current Behavior

Additional focus ring is shown in native input/textarea element when using macOS safari.

## New Behavior

No focus ring is shown in native input/textarea element.

## Related Issue(s)

Fixes #23167

### CODE REVIEW

File: packages/react-components/react-input/src/components/Input/useInputStyles.ts [hunk 1]
```diff
@@ -176,6 +176,8 @@ const useInputElementStyles = makeStyles({
       color: tokens.colorNeutralForeground4,
       opacity: 1, // browser style override
     },
+
+    outlineStyle: 'none',
     ':focus-visible': {
```
Comment (smhigley) [inline packages/react-components/react-input/src/components/Input/useInputStyles.ts:181]: should we remove the `:focus-visible` selector, since it's redundant now?

**Review by smhigley — APPROVED** [review]
Works on Safari on macOS for me!

Just the one comment on the double Input styles, and otherwise looks good to merge
