### PR TITLE
fix(storybook-llms-extractor): extract only serializable component props before page.evaluate

### LINKED ISSUE #35766: [Bug]: Function-type React components lose __docgenInfo across page.evaluate() serialization in storybook-llms-extractor
### Area

storybook

### Environment

```shell
- `@fluentui/storybook-llms-extractor`: `0.0.3`
- Storybook: `9.1.5`
- Playwright: `1.52.0`
- Node.js: `v22.x`
- React: `18.x` (also reproducible with React 19)
```

### Current Behavior

- Function-type components (`typeof meta.component === 'function'`) lose `__docgenInfo` after `page.evaluate()` return.
- As a result, generated `llms/*.txt` files are missing Props tables for those components.
- In our project, **55 out of 87 components (63%)** lost Props due to this issue.
- Note: Related but different from #35578 (different root cause: `page.evaluate()` serialization of function-type `meta.component`, causing `__docgenInfo` loss).
- Note: With React 19 reducing the need for `forwardRef`, more components are expected to be plain functions, so the impact of this issue may grow over time.

### Expected Behavior

Props should be extracted for all components regardless of runtime JS type.

`__docgenInfo` itself is a plain serializable object.  
Only the component function container is not JSON-serializable.

Storybook Docs tab correctly shows Props for all components (including function-type), which indicates `react-docgen-typescript` output is correct and the issue is at extractor serialization boundary.

### Reproduction

https://gist.github.com/shrimp1box/4633994163f6b8c9a3cca3ddb4db3a60

### Steps to reproduce

1. Create a Storybook project with React function components (arrow/function declaration, no `forwardRef`).
2. Build Storybook:
```
yarn build-storybook
```
3. Run extractor:
```
npx @fluentui/storybook-llms-extractor --distPath ./storybook-static
```
4. Inspect generated llms/*.txt: components where typeof meta.component === 'function' have no Props table.
5. Open Storybook Docs for the same components: Props are displayed correctly.

### Suggested severity

Medium - Has workaround

### Products/sites affected

Any Storybook project using function-type React components.

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by shrimp1box**
## Previous Behavior

`extractAllStoriesFromStorybook()` returned `Object.values(storyStore.cachedCSFFiles)` directly from `page.evaluate()`.

Across the `page.evaluate()` boundary, function values are not JSON-serializable, so when `meta.component` was a function (arrow/function declaration), it was dropped during serialization.  
This caused `meta.component.__docgenInfo` to be lost, which removed Props tables from generated `llms/*.txt`.

Components wrapped with `forwardRef` / `memo` / `styled` often appeared as objects and were serialized successfully, creating inconsistent Props output across components.

## New Behavior

`__docgenInfo` is now extracted inside browser context (within `page.evaluate()`) before serialization.

A `serializeComponent()` helper normalizes component metadata into a serializable shape (`displayName`, `__docgenInfo`) for both function-type and object-type components.  
The same handling is applied to `meta.subcomponents`.

Result: Props extraction is now consistent regardless of component runtime type, while existing working cases continue unchanged.

## Related Issue(s)

- Fixes #35766

### CODE REVIEW

**Comment by shrimp1box** [comment]
@microsoft-github-policy-service agree company="kakaostyle"

File: tools/storybook-llms-extractor/src/utils.ts [hunk 1]
```diff
@@ -210,7 +210,49 @@ async function extractAllStoriesFromStorybook(context: BrowserContext, distPath:
       throw new Error('Unable to find cached CSF files in Storybook store');
     }
 
-    return Object.values(storyStore.cachedCSFFiles);
+    // Extract __docgenInfo inside browser context before serialization.
+    // Function-type components cannot be JSON-serialized by page.evaluate(),
+    // so we extract the serializable props data here.
+    return Object.values(storyStore.cachedCSFFiles).map(item => {
```
Comment (dmytrokirpa) [inline tools/storybook-llms-extractor/src/utils.ts]: 1) Could we extract this to a named function(s) in the  `page.evaluate` scope to make it more readable?
2) We should pick only fields we need and get rid of non-serializable fields completely

something like this maybe:

```ts
// Picks only serializable fields before returning across the browser→Node
    // boundary. cachedCSFFiles contains functions (React components, story
    // functions, decorators, etc.) that would cause structured-clone to fail.
    const serializeCSFFile = (item: StorybookStoreItem): StorybookStoreItem => ({
      meta: {
        id: item.meta.id,
        title: item.meta.title,
        parameters: {
          fileName: item.meta.parameters?.fileName,
          docs: item.meta.parameters?.docs
            ? { description: item.meta.parameters.docs.description }
            : undefined,
        },
        component: item.meta.component
          ? { displayName: item.meta.component.displayName, __docgenInfo: item.meta.component.__docgenInfo }
          : undefined,
        subcomponents: item.meta.subcomponents
          ? Object.fromEntries(
              Object.entries(item.meta.subcomponents).map(([key, comp]) => [
                key,
                { displayName: comp.displayName, __docgenInfo: comp.__docgenInfo },
              ])
            )
          : undefined,
      },
      stories: Object.fromEntries(
        Object.entries(item.stories).map(([key, story]) => [
          key,
          {
            id: story.id,
            name: story.name,
            parameters: {
              docs: story.parameters?.docs,
              fullSource: story.parameters?.fullSource,
              docsOnly: story.parameters?.docsOnly,
            },
          },
        ])
      ),
    });
```

Comment (shrimp1box) [reply tools/storybook-llms-extractor/src/utils.ts]: I agree your suggestion is clearer.

File: change/@fluentui-storybook-llms-extractor-7854ed7a-82d4-4927-99ed-df996613e32a.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
+  "comment": "Fix props extraction for function-type components by extracting __docgenInfo before page.evaluate() serialization",
```
Comment (dmytrokirpa) [inline change/@fluentui-storybook-llms-extractor-7854ed7a-82d4-4927-99ed-df996613e32a.json]: nit:

```suggestion
  "comment": "fix: extract only serializable component props before page.evaluate",
```

Additionally we could update the PR title as well. 

Thank you!

Comment (shrimp1box) [reply change/@fluentui-storybook-llms-extractor-7854ed7a-82d4-4927-99ed-df996613e32a.json]: Done, updated the change file comment and PR title. Thanks for the review!

**Comment by shrimp1box** [comment]
Hi @dmytrokirpa thanks for merging! Could you trigger a release for `@fluentui/storybook-llms-extractor` when you get a chance?
The current npm version is still 0.0.3. Thanks!
