### PR TITLE
fix(react-tooltip): use useIsomorphicLayoutEffect to avoid SSR warnings

### LINKED ISSUE #17891: @fluentui/react-tooltip: warning about useLayoutEffect in SSR
- **Package version(s)**: @fluentui/react-tooltip@9.0.0-alpha.22
- **Browser and OS versions**: NA

#### Actual behavior:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, u
seLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at TooltipProvider (@fluentui\react-tooltip\lib-commonjs\components\TooltipProvider\TooltipProvider.js:12:38)
    at div
    at ThemeProvider (@fluentui\react-theme-provider\lib-commonjs\components\ThemeProvider\ThemeProvider.js:8:36)
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: Normal
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by layershifter**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #17891
- [x] Include a change request file using `$ yarn change`

#### Description of changes

This PR replaces `React.useLayoutEffect` with `useIsomorphicLayoutEffect` as it produces warnings during SSR.
Also modifies ESLint preset to prevent future usages. Warnings in existing places of v8 code have been suppressed.

See more details: https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a

### CODE REVIEW

**Review by ling1726 — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Avatar-mount_base.html">871</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Avatar-mount.html">861</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/BaseButton-mount_base.html">832</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/BaseButton-mount.html">853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Breadcrumb-mount_base.html">42898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Breadcrumb-mount.html">43066</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ButtonNext-mount_base.html">529</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ButtonNext-mount.html">527</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Checkbox-mount_base.html">1492</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Checkbox-mount.html">1471</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/CheckboxBase-mount_base.html">1274</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/CheckboxBase-mount.html">1230</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ChoiceGroup-mount_base.html">4586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ChoiceGroup-mount.html">4580</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ComboBox-mount_base.html">1019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ComboBox-mount.html">939</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/CommandBar-mount_base.html">9809</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/CommandBar-mount.html">9801</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ContextualMenu-mount_base.html">6184</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ContextualMenu-mount.html">6097</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DefaultButton-mount_base.html">1087</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DefaultButton-mount.html">1098</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DetailsRow-mount_base.html">3656</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DetailsRow-mount.html">3604</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DetailsRowFast-mount_base.html">3626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DetailsRowFast-mount.html">3599</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DetailsRowNoStyles-mount_base.html">3435</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DetailsRowNoStyles-mount.html">3423</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Dialog-mount_base.html">1441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Dialog-mount.html">1444</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DocumentCardTitle-mount_base.html">1815</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/DocumentCardTitle-mount.html">1816</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Dropdown-mount_base.html">3216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Dropdown-mount.html">3144</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/FocusTrapZone-mount_base.html">1749</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/FocusTrapZone-mount.html">1690</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/FocusZone-mount_base.html">1768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/FocusZone-mount.html">1785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/IconButton-mount_base.html">1654</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/IconButton-mount.html">1688</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Label-mount_base.html">315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Label-mount.html">319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Layer-mount_base.html">1732</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Layer-mount.html">1757</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Link-mount_base.html">445</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Link-mount.html">447</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/MakeStyles-mount_base.html">1742</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/MakeStyles-mount.html">1724</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/MenuButton-mount_base.html">1380</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/MenuButton-mount.html">1408</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/MessageBar-mount_base.html">1958</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/MessageBar-mount.html">1967</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Nav-mount_base.html">3215</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Nav-mount.html">3225</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/OverflowSet-mount_base.html">1023</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/OverflowSet-mount.html">1013</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Panel-mount_base.html">1376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Panel-mount.html">1406</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Persona-mount_base.html">775</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Persona-mount.html">800</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Pivot-mount_base.html">1358</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Pivot-mount.html">1372</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/PrimaryButton-mount_base.html">1217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/PrimaryButton-mount.html">1243</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Rating-mount_base.html">7418</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Rating-mount.html">7422</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/SearchBox-mount_base.html">1284</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/SearchBox-mount.html">1229</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Shimmer-mount_base.html">2478</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Shimmer-mount.html">2418</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Slider-mount_base.html">1939</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Slider-mount.html">1904</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/SpinButton-mount_base.html">4839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/SpinButton-mount.html">4847</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Spinner-mount_base.html">416</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Spinner-mount.html">422</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/SplitButton-mount_base.html">3033</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/SplitButton-mount.html">3107</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Stack-mount_base.html">488</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Stack-mount.html">477</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/StackWithIntrinsicChildren-mount_base.html">1481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/StackWithIntrinsicChildren-mount.html">1496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/StackWithTextChildren-mount_base.html">4343</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/StackWithTextChildren-mount.html">4390</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/SwatchColorPicker-mount_base.html">10118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/SwatchColorPicker-mount.html">9939</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Tabs-mount_base.html">1409</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Tabs-mount.html">1403</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/TagPicker-mount_base.html">2343</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/TagPicker-mount.html">2389</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/TeachingBubble-mount_base.html">11732</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/TeachingBubble-mount.html">11729</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Text-mount_base.html">401</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Text-mount.html">400</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/TextField-mount_base.html">1303</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/TextField-mount.html">1348</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ThemeProvider-mount_base.html">1161</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ThemeProvider-mount.html">1173</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ThemeProvider-virtual-rerender_base.html">588</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ThemeProvider-virtual-rerender.html">609</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ThemeProviderNext-mount_base.html">9066</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/ThemeProviderNext-mount.html">8953</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Toggle-mount_base.html">797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/Toggle-mount.html">775</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/buttonNative-mount_base.html">121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test/buttonNative-mount.html">114</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.17](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Avatar.Fluent.html) | 0.45 | 0.38:1 | 2000 | 341
🦄 | Button.Fluent | [0.11](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Button.Fluent.html) | 0.19 | 0.58:1 | 5000 | 559
🔧 | Checkbox.Fluent | [0.6](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Checkbox.Fluent.html) | 0.34 | 1.76:1 | 1000 | 597
🎯 | Dialog.Fluent | [0.14](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Dialog.Fluent.html) | 0.2 | 0.7:1 | 5000 | 711
🔧 | Dropdown.Fluent | [3.03](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Dropdown.Fluent.html) | 0.38 | 7.97:1 | 1000 | 3028
🔧 | Icon.Fluent | [0.12](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Icon.Fluent.html) | 0.06 | 2:1 | 5000 | 602
🦄 | Image.Fluent | [0.07](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Image.Fluent.html) | 0.12 | 0.58:1 | 5000 | 368
🔧 | Slider.Fluent | [1.58](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Slider.Fluent.html) | 0.44 | 3.59:1 | 1000 | 1580
🔧 | Text.Fluent | [0.07](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.33:1 | 5000 | 350
🦄 | Tooltip.Fluent | [0.14](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Tooltip.Fluent.html) | 0.86 | 0.16:1 | 5000 | 675
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
FlexMinimalPerf.default | [303](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/FlexMinimalPerf.default.html) | [280](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.08:1
Button.Fluent | [559](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Button.Fluent.html) | [516](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Button.Fluent_base.html) | 1.08:1
DividerMinimalPerf.default | [369](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DividerMinimalPerf.default.html) | [347](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.06:1
LayoutMinimalPerf.default | [378](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/LayoutMinimalPerf.default.html) | [356](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.06:1
PortalMinimalPerf.default | [179](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/PortalMinimalPerf.default.html) | [169](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.06:1
AvatarMinimalPerf.default | [215](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AvatarMinimalPerf.default.html) | [205](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.05:1
Avatar.Fluent | [341](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Avatar.Fluent.html) | [325](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Avatar.Fluent_base.html) | 1.05:1
BoxMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/BoxMinimalPerf.default.html) | [352](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.04:1
GridMinimalPerf.default | [349](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/GridMinimalPerf.default.html) | [336](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.04:1
RefMinimalPerf.default | [250](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/RefMinimalPerf.default.html) | [240](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.04:1
ToolbarMinimalPerf.default | [940](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ToolbarMinimalPerf.default.html) | [908](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.04:1
TreeWith60ListItems.default | [188](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TreeWith60ListItems.default.html) | [181](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.04:1
VideoMinimalPerf.default | [631](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/VideoMinimalPerf.default.html) | [608](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [550](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonSlotsPerf.default.html) | [535](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
CarouselMinimalPerf.default | [472](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/CarouselMinimalPerf.default.html) | [458](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.03:1
ChatMinimalPerf.default | [633](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ChatMinimalPerf.default.html) | [614](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.03:1
ListNestedPerf.default | [548](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ListNestedPerf.default.html) | [533](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ListNestedPerf.default_base.html) | 1.03:1
LoaderMinimalPerf.default | [690](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/LoaderMinimalPerf.default.html) | [672](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.03:1
ProviderMinimalPerf.default | [1004](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ProviderMinimalPerf.default.html) | [975](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.03:1
SkeletonMinimalPerf.default | [356](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/SkeletonMinimalPerf.default.html) | [345](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.03:1
StatusMinimalPerf.default | [680](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/StatusMinimalPerf.default.html) | [659](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.03:1
IconMinimalPerf.default | [617](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/IconMinimalPerf.default.html) | [598](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.03:1
TreeMinimalPerf.default | [779](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TreeMinimalPerf.default.html) | [758](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.03:1
AnimationMinimalPerf.default | [419](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AnimationMinimalPerf.default.html) | [411](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.02:1
ButtonMinimalPerf.default | [180](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonMinimalPerf.default.html) | [176](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [736](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DialogMinimalPerf.default.html) | [721](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
LabelMinimalPerf.default | [390](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/LabelMinimalPerf.default.html) | [384](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.02:1
PopupMinimalPerf.default | [721](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/PopupMinimalPerf.default.html) | [709](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [3686](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3629](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [1850](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TableManyItemsPerf.default.html) | [1821](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [959](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TooltipMinimalPerf.default.html) | [944](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
AttachmentMinimalPerf.default | [165](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AttachmentMinimalPerf.default.html) | [164](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.01:1
AttachmentSlotsPerf.default | [1144](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1131](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.01:1
ButtonUseCssNestingPerf.default | [1081](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1066](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 1.01:1
ChatWithPopoverPerf.default | [398](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ChatWithPopoverPerf.default.html) | [393](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [44712](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DatepickerMinimalPerf.default.html) | [44196](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [678](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DropdownManyItemsPerf.default.html) | [670](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.01:1
FormMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/FormMinimalPerf.default.html) | [402](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [1251](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1236](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
MenuButtonMinimalPerf.default | [1527](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1519](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.01:1
SegmentMinimalPerf.default | [348](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/SegmentMinimalPerf.default.html) | [346](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.01:1
TextMinimalPerf.default | [343](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TextMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.01:1
TextAreaMinimalPerf.default | [481](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TextAreaMinimalPerf.default.html) | [474](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.01:1
Image.Fluent | [368](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Image.Fluent.html) | [364](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Image.Fluent_base.html) | 1.01:1
Slider.Fluent | [1580](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Slider.Fluent.html) | [1559](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Slider.Fluent_base.html) | 1.01:1
ChatDuplicateMessagesPerf.default | [308](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [307](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1:1
HeaderMinimalPerf.default | [362](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/HeaderMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
ListCommonPerf.default | [615](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ListCommonPerf.default.html) | [615](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ListCommonPerf.default_base.html) | 1:1
ListMinimalPerf.default | [500](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ListMinimalPerf.default.html) | [498](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
ListWith60ListItems.default | [634](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ListWith60ListItems.default.html) | [635](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ListWith60ListItems.default_base.html) | 1:1
MenuMinimalPerf.default | [866](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/MenuMinimalPerf.default.html) | [867](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1646](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1639](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
RadioGroupMinimalPerf.default | [435](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [433](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1556](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/SliderMinimalPerf.default.html) | [1554](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
TableMinimalPerf.default | [401](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TableMinimalPerf.default.html) | [401](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/TableMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3747](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/CustomToolbarPrototype.default.html) | [3747](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
Dropdown.Fluent | [3028](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Dropdown.Fluent.html) | [3040](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Dropdown.Fluent_base.html) | 1:1
Icon.Fluent | [602](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Icon.Fluent.html) | [601](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Icon.Fluent_base.html) | 1:1
AccordionMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AccordionMinimalPerf.default.html) | [158](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.99:1
ButtonOverridesMissPerf.default | [1673](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1686](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
ButtonUseCssPerf.default | [800](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonUseCssPerf.default.html) | [806](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 0.99:1
CardMinimalPerf.default | [548](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/CardMinimalPerf.default.html) | [551](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [2744](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2763](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [3071](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DropdownMinimalPerf.default.html) | [3102](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [4108](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/EmbedMinimalPerf.default.html) | [4137](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
Dialog.Fluent | [711](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Dialog.Fluent.html) | [715](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Dialog.Fluent_base.html) | 0.99:1
Text.Fluent | [350](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Text.Fluent.html) | [352](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Text.Fluent_base.html) | 0.99:1
Tooltip.Fluent | [675](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Tooltip.Fluent.html) | [681](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Tooltip.Fluent_base.html) | 0.99:1
InputMinimalPerf.default | [1217](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/InputMinimalPerf.default.html) | [1241](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.98:1
ReactionMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ReactionMinimalPerf.default.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.98:1
HeaderSlotsPerf.default | [738](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/HeaderSlotsPerf.default.html) | [763](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.97:1
AlertMinimalPerf.default | [273](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AlertMinimalPerf.default.html) | [283](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.96:1
Checkbox.Fluent | [597](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Checkbox.Fluent.html) | [619](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/Checkbox.Fluent_base.html) | 0.96:1
RosterPerf.default | [1093](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/RosterPerf.default.html) | [1155](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/RosterPerf.default_base.html) | 0.95:1
ImageMinimalPerf.default | [342](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ImageMinimalPerf.default.html) | [367](https://fluentuipr.z22.web.core.windows.net/pull/17894/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.93:1

</details><div id="perfComment9423"/>

**Review by ling1726 — APPROVED** [review]

**Review by behowell — APPROVED** [review]

File: packages/react-hooks/src/useMountSync.ts [hunk 1]
```diff
@@ -12,6 +12,7 @@ import * as React from 'react';
 export const useMountSync = (callback: () => void) => {
```
Comment (ecraig12345) [inline packages/react-hooks/src/useMountSync.ts:12]: Can you also mark this as `@deprecated`? It's not used anywhere and is fundamentally problematic due to useLayoutEffect usage.

File: packages/react-tabs/src/utilities/useOverflow.ts [hunk 2]
```diff
@@ -75,6 +75,7 @@ export const useOverflow = ({ onOverflowItemsChanged, rtl, pinnedIndex }: Overfl
     return () => containerRef(null);
   });
 
+  // eslint-disable-next-line no-restricted-properties
```
Comment (ecraig12345) [inline packages/react-tabs/src/utilities/useOverflow.ts:78]: @behowell FYI, might be good to look into whether this could safely be updated to use `useIsomorphicLayoutEffect`, or how to handle SSR properly if that's not possible. (no need for changes in this PR though)

**Review by ecraig12345 — APPROVED** [review]

File: packages/react-tabs/src/utilities/useOverflow.ts (hunk 2 above)
Comment (behowell) [reply packages/react-tabs/src/utilities/useOverflow.ts:78]: I'm not familiar enough with SSR to know offhand. Basically this needs to happen at some point--it's ok if it's delayed on the first render after SSR, but it would be bad if it never happened. Is that what `useIsomorphicLayoutEffect` achieves?

Comment (ecraig12345) [reply packages/react-tabs/src/utilities/useOverflow.ts:78]: `useIsomorphicLayoutEffect` does `useLayoutEffect` normally, and `useEffect` if server-rendered. For most things that's okay, but depending on what it's being used for, could cause issues like flashing on first render (or maybe bugs in a few cases that are particularly dependent on the timing).

I'm not sure what a good way is to validate SSR. I'm not sure how to manually test it (would have to look that up). For v8 we have an ssr-tests package, but it's limited to extremely basic verification that the components render.

Comment (layershifter) [reply packages/react-tabs/src/utilities/useOverflow.ts:78]: Things that are related to DOM calculations/operations probably should never executed on server at all as there is no DOM 🙄

It depends on use case, but sometimes we can simply exclude `useLayoutEffect` based on environment, for example, it's how it's done in Emotion:
https://github.com/emotion-js/emotion/blob/6c4a9e50f177900f54f7b3368a55b1a7d5e3c002/packages/react/src/global.js#L83-L86

File: packages/react-hooks/src/useMountSync.ts (hunk 1 above)
Comment (layershifter) [reply packages/react-hooks/src/useMountSync.ts:12]: Sure, marked it by JSDoc & in README.md 👍
