### PR TITLE
Change combobox aria-autocomplete to 'list' when autoComplete is off

### LINKED ISSUE #22084: ComboBox input has "none" as default value of aria-autocomplete
### Environment Information

- **Package version(s)**: All (Codepen is on v8)
- **Browser and OS versions**: Edge (Tested on 99.0.1150.36) [Note that this [setting](https://www.tenforums.com/tutorials/160845-enable-disable-save-fill-personal-info-microsoft-edge.html) must be enabled]

### Please provide a reproduction of the bug in a codepen:
[Overlapping Menus Issue](https://codepen.io/dengeorge/pen/qBpEZwv)

#### Actual behavior:
Edge shows autofill info for ComboBox inputs having id or aria-label starting with "name", which isn't the desired behavior for comboboxes since it will result in two overlapping menus. On investigating the attributes, [aria-autocomplete flag](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-autocomplete) seems to be initialized incorrectly for the underlying [autofill](https://github.com/microsoft/fluentui/blob/83a08f167c8d8535f4e15ab2b760bec1a1a486be/packages/react/src/components/ComboBox/ComboBox.tsx#L2344). I feel it should be "list" here rather than "none" as per the definition of the values of this attribute.

#### Expected behavior:

aria-autocomplete should be "list" in case of allowFreeform==true && autoComplete==false
When this attribute is changed, Edge does not display the autofill.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

### PR DESCRIPTION
**Pull request by dennis-pg**
Pull request checklist
* [x]  Addresses an existing issue: Fixes https://github.com/microsoft/fluentui/issues/22084
* [x] Code is up-to-date with the `master` branch
* [x] Your changes are covered by tests (skipped - very minor change)
* [x] You've run `yarn change` locally

## Current behavior

Edge shows autofill info for ComboBox inputs having id or aria-label starting with "name", which isn't the desired behavior for combo boxes since it will result in two overlapping menus. On investigating the attributes, [aria-autocomplete flag](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-autocomplete) seems to be initialized incorrectly for the underlying [autofill](https://github.com/microsoft/fluentui/blob/83a08f167c8d8535f4e15ab2b760bec1a1a486be/packages/react/src/components/ComboBox/ComboBox.tsx#L2344). It should be "list" here rather than "none" as per the definition of the values of this attribute.

## New Behavior

aria-autocomplete should be "list" in case of allowFreeform==true && autoComplete==false
When this attribute is changed, Edge does not display the autofill.

## Related Issue(s)

Fixes #22084

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/e7bcacd2bf95c0188e66d300109759d13a795663'>e7bcacd2bf95c0188e66d300109759d13a795663</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/BaseButton-mount_base.html">761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/BaseButton-mount.html">773</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Breadcrumb-mount_base.html">2377</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Breadcrumb-mount.html">2412</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Checkbox-mount_base.html">1281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Checkbox-mount.html">1293</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/CheckboxBase-mount_base.html">1097</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/CheckboxBase-mount.html">1062</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ChoiceGroup-mount_base.html">4022</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ChoiceGroup-mount.html">4062</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ComboBox-mount_base.html">828</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ComboBox-mount.html">793</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/CommandBar-mount_base.html">8847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/CommandBar-mount.html">9112</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ContextualMenu-mount_base.html">10310</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ContextualMenu-mount.html">10139</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DefaultButton-mount_base.html">982</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DefaultButton-mount.html">993</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DetailsRow-mount_base.html">3179</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DetailsRow-mount.html">3243</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DetailsRowFast-mount_base.html">3110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DetailsRowFast-mount.html">3285</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DetailsRowNoStyles-mount_base.html">3191</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DetailsRowNoStyles-mount.html">3008</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Dialog-mount_base.html">1922</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Dialog-mount.html">1941</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DocumentCardTitle-mount_base.html">134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/DocumentCardTitle-mount.html">141</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Dropdown-mount_base.html">2767</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Dropdown-mount.html">2839</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/FocusTrapZone-mount_base.html">1569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/FocusTrapZone-mount.html">1613</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/FocusZone-mount_base.html">1575</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/FocusZone-mount.html">1493</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/IconButton-mount_base.html">1410</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/IconButton-mount.html">1501</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Label-mount_base.html">305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Label-mount.html">305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Layer-mount_base.html">2447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Layer-mount.html">2504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Link-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Link-mount.html">411</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/MenuButton-mount_base.html">1171</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/MenuButton-mount.html">1226</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/MessageBar-mount_base.html">1643</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/MessageBar-mount.html">1834</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Nav-mount_base.html">2840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Nav-mount.html">2822</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/OverflowSet-mount_base.html">913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/OverflowSet-mount.html">890</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Panel-mount_base.html">1839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Panel-mount.html">1817</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Persona-mount_base.html">855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Persona-mount.html">878</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Pivot-mount_base.html">1256</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Pivot-mount.html">1188</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/PrimaryButton-mount_base.html">1125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/PrimaryButton-mount.html">1122</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Rating-mount_base.html">6634</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Rating-mount.html">6646</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/SearchBox-mount_base.html">1127</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/SearchBox-mount.html">1115</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Shimmer-mount_base.html">2114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Shimmer-mount.html">2179</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Slider-mount_base.html">1673</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Slider-mount.html">1665</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/SpinButton-mount_base.html">4356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/SpinButton-mount.html">4342</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Spinner-mount_base.html">363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Spinner-mount.html">385</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/SplitButton-mount_base.html">2745</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/SplitButton-mount.html">2716</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Stack-mount_base.html">438</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Stack-mount.html">447</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/StackWithIntrinsicChildren-mount_base.html">1990</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/StackWithIntrinsicChildren-mount.html">1967</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/StackWithTextChildren-mount_base.html">4524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/StackWithTextChildren-mount.html">4503</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/SwatchColorPicker-mount_base.html">10033</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/SwatchColorPicker-mount.html">9976</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/TagPicker-mount_base.html">2362</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/TagPicker-mount.html">2285</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/TeachingBubble-mount_base.html">87367</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/TeachingBubble-mount.html">87811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Text-mount_base.html">381</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Text-mount.html">358</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/TextField-mount_base.html">1190</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/TextField-mount.html">1192</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ThemeProvider-mount_base.html">1021</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ThemeProvider-mount.html">1024</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ThemeProvider-virtual-rerender_base.html">552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ThemeProvider-virtual-rerender.html">559</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1556</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1581</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Toggle-mount_base.html">695</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/Toggle-mount.html">682</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/buttonNative-mount_base.html">123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22271/perf-test/buttonNative-mount.html">115</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by smhigley — APPROVED** [review]
This looks like it fundamentally boils down to an edge bug, since `aria-autocomplete="none"` vs. `="list"` is technically about whether the results filter and not about whether or not there's a dropdown attached to the combobox. Since our default Combobox behavior is not to filter, `none` is actually the most spec-accurate based on this wording:

> Authors SHOULD either omit specifying a value for aria-autocomplete or set aria-autocomplete to none if an input element provides one or more input proposals where none of the proposals are dependent on the specific input provided by the user. For instance, a combobox where the value of aria-autocomplete would be none is a search field that displays suggested values by listing the 5 most recently used search terms without any filtering of the list based on the user's input. 

That said, I'm generally in favor of practical support over theoretical hair-splitting, and I don't think there are any practical drawbacks to making the default be `list`. So I'm fine with this change going in 😄

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -2337,11 +2337,11 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
   /**
    * Get the aria autocomplete value for the combo box
    * @returns 'inline' if auto-complete automatically dynamic, 'both' if we have a list of possible values to pick from
-   * and can dynamically populate input, and 'none' if auto-complete is not enabled as we can't give user inputs.
+   * and can dynamically populate input, and 'list' if auto-complete is not enabled as selection is the only option.
```
Comment (smhigley) [inline packages/react/src/components/ComboBox/ComboBox.tsx:2340]: Could you actually drop a comment in here about the Edge behavior so we know why we chose `list` over `none` in the future?

Comment (dennis-pg) [reply packages/react/src/components/ComboBox/ComboBox.tsx:2340]: Added

**Review by raghavthind2005 — APPROVED** [review]
