### PR TITLE
fix: overflow observer disconnect should reset all state

### LINKED ISSUE #27046: [Bug]: Tablist with Overflow breaks when orientation is changed from vertical to horizontal & vice versa
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components": "9.15.6"
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/priceless-surf-viocof?file=/example.tsx

## Actual Behavior
Tablist with Overflow breaks when orientation is changed from vertical to horizontal & vice versa.
In the codesandbox sample, change the orientation to vertical by enabling the switch and select Agenda tab.
Control breaks with an error "Cannot read properties of undefined (reading 'element')"

## Expected Behavior
Tablist with Overflow should not break even if orientation is changed dynamically.

### Logs

```shell
The issue found in OverflowManager.js file where at one point itemB is undefined. 

 const visibleItemQueue = priorityQueue_1.createPriorityQueue((a, b) => {
    const itemA = overflowItems[a];
    const itemB = overflowItems[b];
 // Lower priority at the top of the queue
    const priority = itemA.priority - itemB.priority;
    if (priority !== 0) {
      return priority;
    }
```

### Requested priority

Blocking

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ling1726**
Originally the overflow observer implement `disconnect` with one goal - avoid memory leaks. This meant that after a disconnect there was still leftover state from previous observations. If a user re-observes, then strange things could happen, especially when changing options like `overflowAxis`.

This PR disposes the overflow observer cleanly and resets all state to original defaults.

Fixes #27046

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                        |    Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                  Change |
| :----------------------------------------------------------------------------------------------------------------------- | --------------------------: | --------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr> |  `4.162 kB`<br />`1.735 kB` |  `4.334 kB`<br />`1.787 kB` | `172 B` <br />`52 B`  |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                          | `12.419 kB`<br />`4.687 kB` | `12.647 kB`<br />`4.755 kB` | `228 B` <br />`68 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `69.227 kB`<br />`19.584 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `206.783 kB`<br />`59.085 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `40.793 kB`<br />`13.521 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |     `6.503 kB`<br />`2.22 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/5ddea119dcc0dbace2484f78f1e933424b46ba8c'>5ddea119dcc0dbace2484f78f1e933424b46ba8c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

File: packages/react-components/react-overflow/src/useOverflowContainer.ts [hunk 1]
```diff
@@ -126,3 +82,41 @@ export const updateVisibilityAttribute: OnUpdateItemVisibility = ({ item, visibl
     item.element.setAttribute(DATA_OVERFLOWING, '');
   }
 };
+
+const createReactBindings = (overflowManager: OverflowManager | null) => ({
```
Comment (ling1726) [inline packages/react-components/react-overflow/src/useOverflowContainer.ts:86]: My attempt to try a binding technique that does not involve repeated construct/destruct of instances

File: packages/react-components/react-overflow/src/Overflow.cy.tsx [hunk 2]
```diff
@@ -19,25 +20,36 @@ const selectors = {
   menu: 'data-test-menu',
 };
 
-const Container: React.FC<{ children?: React.ReactNode; width?: number } & Omit<OverflowProps, 'children'>> = ({
-  children,
-  width,
-  ...overflowProps
-}) => {
+const Container: React.FC<
+  { children?: React.ReactNode; width?: number; overflowAxis?: OverflowAxis } & Omit<OverflowProps, 'children'>
```
Comment (layershifter) [inline packages/react-components/react-overflow/src/Overflow.cy.tsx:24]:
```suggestion
  { children?: React.ReactNode; width?: number } & Omit<OverflowProps, 'children'>
```

`overflowAxis` is under `OverflowProps`

File: packages/react-components/react-overflow/src/Overflow.cy.tsx [hunk 3]
```diff
@@ -19,25 +20,36 @@ const selectors = {
...
       <div
         {...selector}
         style={{
-          width: width ?? 500,
+          ...(overflowProps.overflowAxis === 'horizontal' && {
+            width,
+          }),
+          ...(overflowProps.overflowAxis === 'vertical' && {
+            height: width,
+            display: 'flex',
```
Comment (layershifter) [inline packages/react-components/react-overflow/src/Overflow.cy.tsx:46]: Let's apply `display: flex` always

File: packages/react-components/react-overflow/src/Overflow.cy.tsx [hunk 4]
```diff
@@ -19,25 +20,36 @@ const selectors = {
...
-}) => {
+const Container: React.FC<
+  { children?: React.ReactNode; width?: number; overflowAxis?: OverflowAxis } & Omit<OverflowProps, 'children'>
+> = ({ children, width, ...userProps }) => {
   const selector = {
     [selectors.container]: '',
   };
 
+  const overflowProps = {
+    overflowAxis: 'horizontal' as const,
```
Comment (layershifter) [inline packages/react-components/react-overflow/src/Overflow.cy.tsx:31]: Let's just do:

```
{
  children,
  overflowAxis = 'horizontal',
  width,
  ...userProps
}
```

- It removes `overflowProps`
- It simplifies `resize: overflowProps.overflowAxis ?? 'horizontal',` to `resize: overflowAxis,`

File: packages/react-components/react-overflow/src/useOverflowContainer.ts [hunk 5]
```diff
@@ -126,3 +82,41 @@ export const updateVisibilityAttribute: OnUpdateItemVisibility = ({ item, visibl
...
+      item.element.removeAttribute(DATA_OVERFLOWING);
+      item.element.removeAttribute(DATA_OVERFLOW_ITEM);
+      overflowManager?.removeItem(item.id);
+    };
+  },
+
+  registerDivider: (divider: OverflowDividerEntry) => {
+    const el = divider.element;
+    overflowManager?.addDivider(divider);
+    el && el.setAttribute(DATA_OVERFLOW_DIVIDER, '');
```
Comment (layershifter) [inline packages/react-components/react-overflow/src/useOverflowContainer.ts:101]:
```suggestion
    el.setAttribute(DATA_OVERFLOW_DIVIDER, '');
```

?

File: packages/react-components/react-overflow/src/useOverflowContainer.ts [hunk 6]
```diff
@@ -65,57 +69,9 @@ export const useOverflowContainer = <TElement extends HTMLElement>(
...
-  );
-
   return {
+    ...bindingsRef.current,
     containerRef,
-    registerItem,
-    updateOverflow,
-    registerOverflowMenu,
-    registerDivider,
   };
```
Comment (layershifter) [inline packages/react-components/react-overflow/src/useOverflowContainer.ts:75]: I don't understand `bindingsRef.current`, it should be just:

```ts
return React.useMemo(() => ({
  ...createReactBindings(overflowManager),
  containerRef
}, [containerRef, overflowManager])
```

Comment (ling1726) [reply packages/react-components/react-overflow/src/useOverflowContainer.ts:75]: The memo won't work, because the register functions need to be recreated. The register functions are callback ref  which need to be re-called when overflow options change. The easiest way to do this is to make sure they change reference

**Review by layershifter — APPROVED** [review]

File: packages/react-components/react-overflow/src/useOverflowContainer.ts (hunk 6 above)
Comment (ling1726) [reply packages/react-components/react-overflow/src/useOverflowContainer.ts]: So this works because when the overflow manager starts observing it triggers a render - because ResizeObserver is built to dispatch an event on initial observe to get the initial size.

I've updated the bindings to be stored in state anyway now so that from a React PoV it follows the render cycle correctly
