### PR TITLE
fix(ContextualMenu): item.onClick is called when SplitMenuItem checkmark is clicked

### LINKED ISSUE #31817: [Bug]: Contextual menu, clicking on check icon sometimes causes a dismiss rather than an onClick to uncheck the item
### Library

React / v8 (@fluentui/react)

### System Info

```shell
On 8.114.4 version of fluent but can also reproduce on fluent site.
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu

### Bug Description

From the fluent site, go to the "ContextualMenu with checkable menu items and toggleable split button" example and click on where the check icon should be for any of the contextual menu items with icons or a divider on the same line.

## Actual Behavior
Doesn't check/uncheck the item and dismisses the menu

## Expected Behavior
Should check/uncheck the item and keep the contextual menu open

### Logs

_No response_

### Requested priority

Low

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by smhigley**
## Previous Behavior

Because `item.onClick` was not passed through to the item data on the split menu item's primary button, it was not called in `onCheckmarkClick`. This resulted in the default menu-level `onItemClick` was called, and dismissed the menu instead of toggling selection:

https://github.com/microsoft/fluentui/assets/3819570/73644f29-a3f3-455e-b76e-194b193e8561

## New Behavior

`onCheckmarkClick` calls `item.onClick` when available, still defaulting to `onItemClick` when not.

## Related Issue(s)

- Fixes #31817

### CODE REVIEW

File: packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx [hunk 1]
```diff
@@ -183,6 +183,7 @@ export class ContextualMenuSplitButton extends ContextualMenuItemWrapper {
       checked: item.checked,
       iconProps: item.iconProps,
       id: this._dismissLabelId,
+      onClick: item.onClick,
```
Comment (spmonahan) [inline packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx:186]: Would love to see a test since tests are part of the way you investigated the existing behavior :)

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports | Baseline (minified/GZIP) | PR    | Change     |
| :---------------- | -----------------------: | ----: | ---------: |
| <samp>react</samp> <br /> <abbr title='bundle-size/Breadcrumb.fixture.js'>Breadcrumb</abbr> | `202.005 kB`<br />`60.362 kB` | `202.023 kB`<br />`60.364 kB` | `18 B` <br />`2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr> | `195.473 kB`<br />`56.558 kB` | `195.491 kB`<br />`56.565 kB` | `18 B` <br />`7 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ButtonGrid.fixture.js'>ButtonGrid</abbr> | `180.416 kB`<br />`54.61 kB` | `180.434 kB`<br />`54.614 kB` | `18 B` <br />`4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ComboBox.fixture.js'>ComboBox</abbr> | `251.89 kB`<br />`72.222 kB` | `251.908 kB`<br />`72.225 kB` | `18 B` <br />`3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/CommandBar.fixture.js'>CommandBar</abbr> | `203.042 kB`<br />`60.075 kB` | `203.06 kB`<br />`60.077 kB` | `18 B` <br />`2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ContextualMenu.fixture.js'>ContextualMenu</abbr> | `154.998 kB`<br />`48.158 kB` | `155.016 kB`<br />`48.159 kB` | `18 B` <br />`1 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog</abbr> | `211.329 kB`<br />`63.082 kB` | `211.347 kB`<br />`63.085 kB` | `18 B` <br />`3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DocumentCard.fixture.js'>DocumentCard</abbr> | `217.014 kB`<br />`64.363 kB` | `217.032 kB`<br />`64.369 kB` | `18 B` <br />`6 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown</abbr> | `233.935 kB`<br />`68.547 kB` | `233.953 kB`<br />`68.55 kB` | `18 B` <br />`3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Facepile.fixture.js'>Facepile</abbr> | `210.59 kB`<br />`63.132 kB` | `210.608 kB`<br />`63.136 kB` | `18 B` <br />`4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/FloatingPicker.fixture.js'>FloatingPicker</abbr> | `242.06 kB`<br />`68.931 kB` | `242.078 kB`<br />`68.933 kB` | `18 B` <br />`2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Grid.fixture.js'>Grid</abbr> | `180.416 kB`<br />`54.61 kB` | `180.434 kB`<br />`54.614 kB` | `18 B` <br />`4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/MessageBar.fixture.js'>MessageBar</abbr> | `190.52 kB`<br />`57.042 kB` | `190.538 kB`<br />`57.047 kB` | `18 B` <br />`5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Nav.fixture.js'>Nav</abbr> | `187.998 kB`<br />`56.464 kB` | `188.016 kB`<br />`56.467 kB` | `18 B` <br />`3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Panel.fixture.js'>Panel</abbr> | `201.04 kB`<br />`59.952 kB` | `201.058 kB`<br />`59.956 kB` | `18 B` <br />`4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Pickers.fixture.js'>Pickers</abbr> | `293.75 kB`<br />`82.262 kB` | `293.768 kB`<br />`82.267 kB` | `18 B` <br />`5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Pivot.fixture.js'>Pivot</abbr> | `188.912 kB`<br />`57.213 kB` | `188.93 kB`<br />`57.215 kB` | `18 B` <br />`2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/React.fixture.js'>Fluent UI React (entire library)</abbr> | `1.013 MB`<br />`281.426 kB` | `1.013 MB`<br />`281.431 kB` | `18 B` <br />`5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SearchBox.fixture.js'>SearchBox</abbr> | `188.795 kB`<br />`56.649 kB` | `188.813 kB`<br />`56.653 kB` | `18 B` <br />`4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SelectedItemsList.fixture.js'>SelectedItemsList</abbr> | `232.559 kB`<br />`67.863 kB` | `232.577 kB`<br />`67.867 kB` | `18 B` <br />`4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr> | `192.523 kB`<br />`57.748 kB` | `192.541 kB`<br />`57.753 kB` | `18 B` <br />`5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SwatchColorPicker.fixture.js'>SwatchColorPicker</abbr> | `190.742 kB`<br />`58.094 kB` | `190.76 kB`<br />`58.098 kB` | `18 B` <br />`4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/TeachingBubble.fixture.js'>TeachingBubble</abbr> | `205.795 kB`<br />`60.984 kB` | `205.813 kB`<br />`60.989 kB` | `18 B` <br />`5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr> | `241.694 kB`<br />`69.983 kB` | `241.712 kB`<br />`69.986 kB` | `18 B` <br />`3 B` |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react</samp> <br /> <abbr title='bundle-size/ActivityItem.fixture.js'>ActivityItem</abbr> | `71.147 kB`<br />`23.33 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Announced.fixture.js'>Announced</abbr> | `38.419 kB`<br />`13.288 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Autofill.fixture.js'>Autofill</abbr> | `15.365 kB`<br />`4.743 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Calendar.fixture.js'>Calendar</abbr> | `121.67 kB`<br />`36.976 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Callout.fixture.js'>Callout</abbr> | `84.236 kB`<br />`27.607 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Check.fixture.js'>Check</abbr> | `53.091 kB`<br />`17.837 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr> | `59.879 kB`<br />`19.865 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ChoiceGroup.fixture.js'>ChoiceGroup</abbr> | `65.404 kB`<br />`21.469 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ChoiceGroupOption.fixture.js'>ChoiceGroupOption</abbr> | `58.659 kB`<br />`19.356 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Coachmark.fixture.js'>Coachmark</abbr> | `93.065 kB`<br />`29.412 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Color.fixture.js'>Color</abbr> | `7.737 kB`<br />`3.106 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ColorPicker.fixture.js'>ColorPicker</abbr> | `133.113 kB`<br />`41.536 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DatePicker.fixture.js'>DatePicker</abbr> | `184.067 kB`<br />`56.121 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DateTimeUtilities.fixture.js'>DateTimeUtilities</abbr> | `5.244 kB`<br />`1.849 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DetailsList.fixture.js'>DetailsList</abbr> | `229.445 kB`<br />`65.681 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr> | `19.531 kB`<br />`6.862 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DragDrop.fixture.js'>DragDrop</abbr> | `8.343 kB`<br />`2.724 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DraggableZone.fixture.js'>DraggableZone</abbr> | `34.241 kB`<br />`11.491 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ExtendedPicker.fixture.js'>ExtendedPicker</abbr> | `96.693 kB`<br />`27.85 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Fabric.fixture.js'>Fabric</abbr> | `41.665 kB`<br />`14.358 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/FocusTrapZone.fixture.js'>FocusTrapZone</abbr> | `16.979 kB`<br />`5.921 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/FocusZone.fixture.js'>FocusZone</abbr> | `54.972 kB`<br />`17.442 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/GroupedList.fixture.js'>GroupedList</abbr> | `134.762 kB`<br />`40.629 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/GroupedListV2.fixture.js'>GroupedListV2</abbr> | `122.379 kB`<br />`37.737 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/HoverCard.fixture.js'>HoverCard</abbr> | `97.097 kB`<br />`30.782 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Icon.fixture.js'>Icon</abbr> | `51.772 kB`<br />`17.252 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Icons.fixture.js'>Icons</abbr> | `66.309 kB`<br />`24.381 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr> | `46.829 kB`<br />`15.701 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Keytip.fixture.js'>Keytip</abbr> | `81.61 kB`<br />`26.75 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/KeytipData.fixture.js'>KeytipData</abbr> | `13.973 kB`<br />`4.573 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/KeytipLayer.fixture.js'>KeytipLayer</abbr> | `103.406 kB`<br />`32.004 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Keytips.fixture.js'>Keytips</abbr> | `106.174 kB`<br />`33.006 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr> | `38.266 kB`<br />`13.244 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Layer.fixture.js'>Layer</abbr> | `48.015 kB`<br />`16.337 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Link.fixture.js'>Link</abbr> | `39.616 kB`<br />`13.649 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/List.fixture.js'>List</abbr> | `39.304 kB`<br />`12.441 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/MarqueeSelection.fixture.js'>MarqueeSelection</abbr> | `74.449 kB`<br />`22.441 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Modal.fixture.js'>Modal</abbr> | `93.568 kB`<br />`30.235 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/OverflowSet.fixture.js'>OverflowSet</abbr> | `33.319 kB`<br />`11.317 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Overlay.fixture.js'>Overlay</abbr> | `40.822 kB`<br />`14.083 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr> | `114.745 kB`<br />`36.478 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/PersonaCoin.fixture.js'>PersonaCoin</abbr> | `114.745 kB`<br />`36.478 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/PersonaPresence.fixture.js'>PersonaPresence</abbr> | `57.961 kB`<br />`19.359 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Popup.fixture.js'>Popup</abbr> | `12.242 kB`<br />`4.181 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Positioning.fixture.js'>Positioning</abbr> | `22.736 kB`<br />`7.685 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/PositioningContainer.fixture.js'>PositioningContainer</abbr> | `73.775 kB`<br />`23.762 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ProgressIndicator.fixture.js'>ProgressIndicator</abbr> | `39.414 kB`<br />`13.548 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Rating.fixture.js'>Rating</abbr> | `81.89 kB`<br />`26.097 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ResizeGroup.fixture.js'>ResizeGroup</abbr> | `13.286 kB`<br />`4.365 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ResponsiveMode.fixture.js'>ResponsiveMode</abbr> | `8.078 kB`<br />`2.95 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ScrollablePane.fixture.js'>ScrollablePane</abbr> | `55.457 kB`<br />`17.735 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SelectableOption.fixture.js'>SelectableOption</abbr> | `724 B`<br />`413 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Selection.fixture.js'>Selection</abbr> | `42.38 kB`<br />`12.255 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Separator.fixture.js'>Separator</abbr> | `35.315 kB`<br />`12.157 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Shimmer.fixture.js'>Shimmer</abbr> | `49.177 kB`<br />`16.256 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ShimmeredDetailsList.fixture.js'>ShimmeredDetailsList</abbr> | `240.22 kB`<br />`68.444 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr> | `57.577 kB`<br />`19.194 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr> | `41.609 kB`<br />`14.458 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Stack.fixture.js'>Stack</abbr> | `41.675 kB`<br />`14.283 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Sticky.fixture.js'>Sticky</abbr> | `32.541 kB`<br />`10.49 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Styling.fixture.js'>Styling</abbr> | `45.981 kB`<br />`15.121 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Text.fixture.js'>Text</abbr> | `36.851 kB`<br />`12.828 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/TextField.fixture.js'>TextField</abbr> | `80.683 kB`<br />`25.303 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Theme.fixture.js'>Theme</abbr> | `43.449 kB`<br />`14.169 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ThemeGenerator.fixture.js'>ThemeGenerator</abbr> | `12.34 kB`<br />`4.106 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Toggle.fixture.js'>Toggle</abbr> | `46.148 kB`<br />`15.96 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr> | `87.264 kB`<br />`28.207 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Utilities.fixture.js'>Utilities</abbr> | `82.623 kB`<br />`25.106 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Viewport.fixture.js'>Viewport</abbr> | `23.831 kB`<br />`7.638 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/WeeklyDayPicker.fixture.js'>WeeklyDayPicker</abbr> | `101.814 kB`<br />`31.796 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/WindowProvider.fixture.js'>WindowProvider</abbr> | `1.059 kB`<br />`541 B` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2ccb9dd0764a3b4fbfbb43910c1b1fe20c9460be'>2ccb9dd0764a3b4fbfbb43910c1b1fe20c9460be</a></sub>
<div id="bundleSizeComment9423"/>

File: change/@fluentui-react-31dc521a-eeaf-47a8-b020-ffb9b3a9db8d.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (fabricteam) [inline change/@fluentui-react-31dc521a-eeaf-47a8-b020-ffb9b3a9db8d.json:1]: ## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=31908&commitId=a3a61ccb3947b21862a9cabb4591f6a805a80059&env=prod&clientType=FLUENTUI)


  <details><summary><b>Pivot - Overflow</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Removed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/BaseButton-mount_base.html">641</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/BaseButton-mount.html">622</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Breadcrumb-mount_base.html">1680</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Breadcrumb-mount.html">1690</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Checkbox-mount_base.html">1683</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Checkbox-mount.html">1714</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/CheckboxBase-mount_base.html">1507</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/CheckboxBase-mount.html">1489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ChoiceGroup-mount_base.html">2992</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ChoiceGroup-mount.html">2985</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ComboBox-mount_base.html">666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ComboBox-mount.html">672</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/CommandBar-mount_base.html">6520</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/CommandBar-mount.html">6520</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ContextualMenu-mount_base.html">12511</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ContextualMenu-mount.html">12178</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DefaultButton-mount_base.html">758</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DefaultButton-mount.html">795</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DetailsRow-mount_base.html">2233</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DetailsRow-mount.html">2207</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DetailsRowFast-mount_base.html">2231</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DetailsRowFast-mount.html">2233</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DetailsRowNoStyles-mount_base.html">2046</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DetailsRowNoStyles-mount.html">2012</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Dialog-mount_base.html">2644</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Dialog-mount.html">2689</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DocumentCardTitle-mount_base.html">227</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/DocumentCardTitle-mount.html">230</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Dropdown-mount_base.html">1997</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Dropdown-mount.html">2032</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/FocusTrapZone-mount_base.html">1131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/FocusTrapZone-mount.html">1123</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/FocusZone-mount_base.html">1103</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/FocusZone-mount.html">1056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedList-mount_base.html">37631</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedList-mount.html">41880</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedList-virtual-rerender_base.html">18011</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedList-virtual-rerender.html">20139</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">51204</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedList-virtual-rerender-with-unmount.html">51423</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedListV2-mount_base.html">223</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedListV2-mount.html">226</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedListV2-virtual-rerender_base.html">211</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedListV2-virtual-rerender.html">213</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">226</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">218</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/IconButton-mount_base.html">1134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/IconButton-mount.html">1115</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Label-mount_base.html">343</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Label-mount.html">335</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Layer-mount_base.html">2764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Layer-mount.html">2720</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Link-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Link-mount.html">388</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/MenuButton-mount_base.html">1004</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/MenuButton-mount.html">998</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/MessageBar-mount_base.html">21264</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/MessageBar-mount.html">21340</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Nav-mount_base.html">2032</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Nav-mount.html">2049</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/OverflowSet-mount_base.html">794</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/OverflowSet-mount.html">767</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Panel-mount_base.html">1855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Panel-mount.html">1829</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Persona-mount_base.html">760</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Persona-mount.html">782</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Pivot-mount_base.html">920</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Pivot-mount.html">897</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/PrimaryButton-mount_base.html">952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/PrimaryButton-mount.html">923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Rating-mount_base.html">4649</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Rating-mount.html">4657</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/SearchBox-mount_base.html">901</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/SearchBox-mount.html">919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Shimmer-mount_base.html">1919</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Shimmer-mount.html">1846</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Slider-mount_base.html">1322</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Slider-mount.html">1337</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/SpinButton-mount_base.html">2948</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/SpinButton-mount.html">2990</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Spinner-mount_base.html">404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Spinner-mount.html">393</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/SplitButton-mount_base.html">1864</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/SplitButton-mount.html">1820</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Stack-mount_base.html">422</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Stack-mount.html">431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/StackWithIntrinsicChildren-mount_base.html">868</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/StackWithIntrinsicChildren-mount.html">850</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/StackWithTextChildren-mount_base.html">2768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/StackWithTextChildren-mount.html">2747</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/SwatchColorPicker-mount_base.html">6491</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/SwatchColorPicker-mount.html">6330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/TagPicker-mount_base.html">1486</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/TagPicker-mount.html">1540</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Text-mount_base.html">378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Text-mount.html">394</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/TextField-mount_base.html">950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/TextField-mount.html">937</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ThemeProvider-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ThemeProvider-mount.html">850</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ThemeProvider-virtual-rerender_base.html">575</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ThemeProvider-virtual-rerender.html">580</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1294</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1275</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Toggle-mount_base.html">607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/Toggle-mount.html">591</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/buttonNative-mount_base.html">189</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31908/perf-test/buttonNative-mount.html">193</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by khmakoto — APPROVED** [review]

File: packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx (hunk 1 above)
Comment (smhigley) [reply packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx:186]: done!

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

File: packages/react/src/components/ContextualMenu/ContextualMenu.test.tsx [hunk 3]
```diff
@@ -570,6 +570,54 @@ describe('ContextualMenu', () => {
...
+    const menuItem = document.getElementsByTagName('button')[0] as HTMLButtonElement;
+
+    ReactTestUtils.act(() => {
+      ReactTestUtils.Simulate.click(menuItem);
+    });
+
+    const checkIcon = document.querySelector('.ms-ContextualMenu-checkmarkIcon') as HTMLElement;
+
+    expect(checkIcon).toBeTruthy();
+    expect(onPrimaryClick).toHaveBeenCalled();
```
Comment (spmonahan) [inline packages/react/src/components/ContextualMenu/ContextualMenu.test.tsx:610]: Should we be asserting about `onItemClick` here as well?

File: packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx (hunk 1 above)
Comment (spmonahan) [reply packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx:186]: Awesome! Added a comment but approving.

**Review by spmonahan — APPROVED** [review]

File: packages/react/src/components/ContextualMenu/ContextualMenu.test.tsx (hunk 3 above)
Comment (smhigley) [reply packages/react/src/components/ContextualMenu/ContextualMenu.test.tsx:610]: the `.not.toHaveBeenCalled` at the end should work to assert that it wasn't called either time, since the mock isn't reset between clicks.

Comment (spmonahan) [reply packages/react/src/components/ContextualMenu/ContextualMenu.test.tsx:610]: Oh yeah 🤦

**Review by spmonahan — APPROVED** [review]
