### PR TITLE
fix(storybook): use typescript entrypoint in react-storybook-addon preset

### LINKED ISSUE #20474: react-storybook-addon: Needs to be built before running storybook
`@fluentui/react-storybook-addon` needs to be built before running storybook.

Running `yarn storybook`  in `react-components` package will give the following error

### PR DESCRIPTION
**Pull request by ling1726**
#### Pull request checklist

- [x] Addresses an existing issue: fixes #20474 and works around #18357 
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Since our storybook is configured with babel to work with typescript, there's no problem with this and will allow no-build DX for storybook

This would have some nasty implications if we ever decided to publish
this addon. However, currently in the monorepo this will enable `yarn
storybook` without building the addon first
#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/react-storybook-addon/src/theme.ts [hunk 1]
```diff
@@ -5,9 +5,10 @@ import {
   teamsLightTheme,
   teamsDarkTheme,
   teamsHighContrastTheme,
-  Theme,
 } from '@fluentui/react-theme';
 
+import type { Theme } from '@fluentui/react-theme';
```
Comment (ling1726) [inline packages/react-storybook-addon/src/theme.ts:10]: babel will warn on imports and exports of types

File: packages/react-storybook-addon/src/theme.ts [hunk 2]
```diff
@@ -24,4 +25,4 @@ export const defaultTheme = themes[0];
 export type ThemeIds = typeof themes[number]['id'];
 export type ThemeLabels = typeof themes[number]['label'];
 
-export { Theme };
+export type { Theme };
```
Comment (ling1726) [inline packages/react-storybook-addon/src/theme.ts:28]: babel will warn on imports and exports of types

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `169.727 kB`<br />`48.148 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.208 kB`<br />`10.672 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/e42f50656c1b703d88c398b114f225ba5f1f5f22'>e42f50656c1b703d88c398b114f225ba5f1f5f22</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Avatar-mount_base.html">944</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Avatar-mount.html">950</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/BaseButton-mount_base.html">946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/BaseButton-mount.html">972</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Breadcrumb-mount_base.html">2576</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Breadcrumb-mount.html">2592</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ButtonNext-mount_base.html">508</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ButtonNext-mount.html">510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Checkbox-mount_base.html">1612</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Checkbox-mount.html">1624</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/CheckboxBase-mount_base.html">1365</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/CheckboxBase-mount.html">1354</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ChoiceGroup-mount_base.html">4865</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ChoiceGroup-mount.html">4918</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ComboBox-mount_base.html">1012</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ComboBox-mount.html">966</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/CommandBar-mount_base.html">10035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/CommandBar-mount.html">9967</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ContextualMenu-mount_base.html">6364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ContextualMenu-mount.html">6318</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DefaultButton-mount_base.html">1141</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DefaultButton-mount.html">1167</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DetailsRow-mount_base.html">3826</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DetailsRow-mount.html">3773</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DetailsRowFast-mount_base.html">3856</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DetailsRowFast-mount.html">3780</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DetailsRowNoStyles-mount_base.html">3700</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DetailsRowNoStyles-mount.html">3718</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Dialog-mount_base.html">2534</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Dialog-mount.html">2675</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DocumentCardTitle-mount_base.html">171</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/DocumentCardTitle-mount.html">180</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Dropdown-mount_base.html">3313</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Dropdown-mount.html">3292</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FluentProviderNext-mount_base.html">3154</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FluentProviderNext-mount.html">3140</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FluentProviderWithTheme-mount_base.html">190</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FluentProviderWithTheme-mount.html">194</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">95</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FluentProviderWithTheme-virtual-rerender.html">95</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">219</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">226</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FocusTrapZone-mount_base.html">1769</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FocusTrapZone-mount.html">1792</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FocusZone-mount_base.html">1743</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/FocusZone-mount.html">1760</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/IconButton-mount_base.html">1813</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/IconButton-mount.html">1777</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Label-mount_base.html">347</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Label-mount.html">355</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Layer-mount_base.html">3067</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Layer-mount.html">3018</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Link-mount_base.html">476</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Link-mount.html">498</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/MakeStyles-mount_base.html">1734</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/MakeStyles-mount.html">1753</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/MenuButton-mount_base.html">1522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/MenuButton-mount.html">1524</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/MessageBar-mount_base.html">1978</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/MessageBar-mount.html">1985</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Nav-mount_base.html">3325</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Nav-mount.html">3409</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/OverflowSet-mount_base.html">1125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/OverflowSet-mount.html">1087</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Panel-mount_base.html">2481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Panel-mount.html">2467</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Persona-mount_base.html">843</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Persona-mount.html">847</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Pivot-mount_base.html">1485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Pivot-mount.html">1464</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/PrimaryButton-mount_base.html">1305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/PrimaryButton-mount.html">1330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Rating-mount_base.html">8170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Rating-mount.html">8053</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/SearchBox-mount_base.html">1442</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/SearchBox-mount.html">1391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Shimmer-mount_base.html">2651</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Shimmer-mount.html">2669</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Slider-mount_base.html">1985</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Slider-mount.html">1988</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/SpinButton-mount_base.html">5055</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/SpinButton-mount.html">5106</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Spinner-mount_base.html">429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Spinner-mount.html">423</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/SplitButton-mount_base.html">3244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/SplitButton-mount.html">3216</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Stack-mount_base.html">538</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Stack-mount.html">526</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/StackWithIntrinsicChildren-mount_base.html">1811</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/StackWithIntrinsicChildren-mount.html">1814</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/StackWithTextChildren-mount_base.html">4983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/StackWithTextChildren-mount.html">5014</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/SwatchColorPicker-mount_base.html">10750</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/SwatchColorPicker-mount.html">10885</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/TagPicker-mount_base.html">2728</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/TagPicker-mount.html">2749</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/TeachingBubble-mount_base.html">12762</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/TeachingBubble-mount.html">12719</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Text-mount_base.html">428</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Text-mount.html">445</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/TextField-mount_base.html">1444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/TextField-mount.html">1432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ThemeProvider-mount_base.html">1164</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ThemeProvider-mount.html">1171</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ThemeProvider-virtual-rerender_base.html">609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ThemeProvider-virtual-rerender.html">617</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1948</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1993</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Toggle-mount_base.html">816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/Toggle-mount.html">834</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/buttonNative-mount_base.html">144</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test/buttonNative-mount.html">129</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
PortalMinimalPerf.default | [182](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/PortalMinimalPerf.default.html) | [162](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.12:1
TreeWith60ListItems.default | [203](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TreeWith60ListItems.default.html) | [182](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.12:1
BoxMinimalPerf.default | [397](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/BoxMinimalPerf.default.html) | [359](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.11:1
ListNestedPerf.default | [605](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ListNestedPerf.default.html) | [562](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ListNestedPerf.default_base.html) | 1.08:1
AttachmentMinimalPerf.default | [187](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AttachmentMinimalPerf.default.html) | [175](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.07:1
ButtonMinimalPerf.default | [201](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ButtonMinimalPerf.default.html) | [187](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.07:1
ListWith60ListItems.default | [701](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ListWith60ListItems.default.html) | [654](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.07:1
AvatarMinimalPerf.default | [211](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AvatarMinimalPerf.default.html) | [200](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.06:1
ChatWithPopoverPerf.default | [426](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ChatWithPopoverPerf.default.html) | [403](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.06:1
DividerMinimalPerf.default | [394](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DividerMinimalPerf.default.html) | [370](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.06:1
LoaderMinimalPerf.default | [738](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/LoaderMinimalPerf.default.html) | [697](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.06:1
TooltipMinimalPerf.default | [1102](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TooltipMinimalPerf.default.html) | [1042](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.06:1
AttachmentSlotsPerf.default | [1144](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1090](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.05:1
ChatMinimalPerf.default | [701](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ChatMinimalPerf.default.html) | [666](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.05:1
AnimationMinimalPerf.default | [428](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AnimationMinimalPerf.default.html) | [411](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.04:1
ChatDuplicateMessagesPerf.default | [314](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [301](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [393](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/LayoutMinimalPerf.default.html) | [377](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
ListMinimalPerf.default | [549](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ListMinimalPerf.default.html) | [529](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.04:1
SkeletonMinimalPerf.default | [373](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/SkeletonMinimalPerf.default.html) | [359](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [571](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ButtonSlotsPerf.default.html) | [557](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
CheckboxMinimalPerf.default | [2805](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2727](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.03:1
FlexMinimalPerf.default | [300](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/FlexMinimalPerf.default.html) | [290](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.03:1
ButtonOverridesMissPerf.default | [1840](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1808](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.02:1
MenuButtonMinimalPerf.default | [1715](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1685](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.02:1
RefMinimalPerf.default | [231](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/RefMinimalPerf.default.html) | [226](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.02:1
TextAreaMinimalPerf.default | [546](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TextAreaMinimalPerf.default.html) | [536](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.02:1
ToolbarMinimalPerf.default | [989](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ToolbarMinimalPerf.default.html) | [972](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.02:1
CardMinimalPerf.default | [587](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/CardMinimalPerf.default.html) | [579](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5619](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5546](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [755](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DropdownManyItemsPerf.default.html) | [751](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.01:1
EmbedMinimalPerf.default | [4356](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/EmbedMinimalPerf.default.html) | [4303](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.01:1
GridMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/GridMinimalPerf.default.html) | [346](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.01:1
HeaderSlotsPerf.default | [802](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/HeaderSlotsPerf.default.html) | [791](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [867](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/MenuMinimalPerf.default.html) | [860](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
ReactionMinimalPerf.default | [400](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ReactionMinimalPerf.default.html) | [397](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.01:1
SegmentMinimalPerf.default | [370](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/SegmentMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [2023](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TableManyItemsPerf.default.html) | [1998](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TableMinimalPerf.default | [415](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TableMinimalPerf.default.html) | [411](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.01:1
CustomToolbarPrototype.default | [4083](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/CustomToolbarPrototype.default.html) | [4027](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.01:1
FormMinimalPerf.default | [439](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/FormMinimalPerf.default.html) | [440](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/FormMinimalPerf.default_base.html) | 1:1
HeaderMinimalPerf.default | [377](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/HeaderMinimalPerf.default.html) | [378](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [415](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/LabelMinimalPerf.default.html) | [413](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [580](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/PopupMinimalPerf.default.html) | [582](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
RadioGroupMinimalPerf.default | [456](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [454](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [4426](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4417](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [698](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/StatusMinimalPerf.default.html) | [698](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
TextMinimalPerf.default | [358](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TextMinimalPerf.default.html) | [359](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TextMinimalPerf.default_base.html) | 1:1
CarouselMinimalPerf.default | [478](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/CarouselMinimalPerf.default.html) | [485](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.99:1
DialogMinimalPerf.default | [764](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DialogMinimalPerf.default.html) | [768](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [3139](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DropdownMinimalPerf.default.html) | [3183](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
ImageMinimalPerf.default | [402](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ImageMinimalPerf.default.html) | [406](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1329](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/InputMinimalPerf.default.html) | [1343](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
RosterPerf.default | [1277](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/RosterPerf.default.html) | [1287](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/RosterPerf.default_base.html) | 0.99:1
SliderMinimalPerf.default | [1697](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/SliderMinimalPerf.default.html) | [1712](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.99:1
IconMinimalPerf.default | [639](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/IconMinimalPerf.default.html) | [646](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.99:1
TreeMinimalPerf.default | [819](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TreeMinimalPerf.default.html) | [830](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.99:1
AlertMinimalPerf.default | [284](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AlertMinimalPerf.default.html) | [291](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.98:1
ItemLayoutMinimalPerf.default | [1292](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1323](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.98:1
ProviderMergeThemesPerf.default | [1621](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1646](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.98:1
VideoMinimalPerf.default | [651](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/VideoMinimalPerf.default.html) | [664](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.98:1
ListCommonPerf.default | [656](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ListCommonPerf.default.html) | [676](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ListCommonPerf.default_base.html) | 0.97:1
ProviderMinimalPerf.default | [1108](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ProviderMinimalPerf.default.html) | [1142](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.97:1
AccordionMinimalPerf.default | [153](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AccordionMinimalPerf.default.html) | [174](https://fluentuipr.z22.web.core.windows.net/pull/20473/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.88:1

</details><div id="perfComment9423"/>

**Review by Hotell — APPROVED** [review]
