### PR TITLE
fix(tools): properly check for javascript files within isJs helper

### LINKED ISSUE #20748: migrate-converged-pkg: generator considers react-components as JS project
I ran generator for `@fluentui/react-components` and `yarn build` fails then:

image

This happens because TS emits nothing. I checked configs and generator for unknown reason considers this project as JS only and generates wrong configs:

image

### PR DESCRIPTION
**Pull request by Hotell**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #20748
- ~[ ] Include a change request file using `$ yarn change`~

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8a141d14f3a14de2e1c4691dad908622f310a9d1'>8a141d14f3a14de2e1c4691dad908622f310a9d1</a></sub>
<div id="bundleSizeComment9423"/>

File: tools/generators/migrate-converged-pkg/index.ts [hunk 1]
```diff
@@ -559,6 +559,7 @@ function setupStorybook(tree: Tree, options: NormalizedSchema) {
   };
 
   const js = isJs(tree, options);
+  console.log({ js, options });
```
Comment (layershifter) [inline tools/generators/migrate-converged-pkg/index.ts:562]:
```suggestion
```

Oops?

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Avatar-mount_base.html">788</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Avatar-mount.html">857</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/BaseButton-mount_base.html">892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/BaseButton-mount.html">908</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Breadcrumb-mount_base.html">2362</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Breadcrumb-mount.html">2208</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ButtonNext-mount_base.html">494</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ButtonNext-mount.html">533</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Checkbox-mount_base.html">1388</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Checkbox-mount.html">1397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/CheckboxBase-mount_base.html">1217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/CheckboxBase-mount.html">1133</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ChoiceGroup-mount_base.html">4091</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ChoiceGroup-mount.html">4010</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ComboBox-mount_base.html">917</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ComboBox-mount.html">933</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/CommandBar-mount_base.html">8913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/CommandBar-mount.html">9064</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ContextualMenu-mount_base.html">7367</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ContextualMenu-mount.html">7439</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DefaultButton-mount_base.html">1068</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DefaultButton-mount.html">1103</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DetailsRow-mount_base.html">3337</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DetailsRow-mount.html">3378</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DetailsRowFast-mount_base.html">3361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DetailsRowFast-mount.html">3372</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DetailsRowNoStyles-mount_base.html">3162</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DetailsRowNoStyles-mount.html">3217</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Dialog-mount_base.html">2261</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Dialog-mount.html">2297</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DocumentCardTitle-mount_base.html">258</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/DocumentCardTitle-mount.html">248</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Dropdown-mount_base.html">2685</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Dropdown-mount.html">2804</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FluentProviderNext-mount_base.html">3609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FluentProviderNext-mount.html">3565</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FluentProviderWithTheme-mount_base.html">317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FluentProviderWithTheme-mount.html">301</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FluentProviderWithTheme-virtual-rerender.html">185</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">319</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">331</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FocusTrapZone-mount_base.html">1631</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FocusTrapZone-mount.html">1647</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FocusZone-mount_base.html">1678</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/FocusZone-mount.html">1698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/IconButton-mount_base.html">1607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/IconButton-mount.html">1570</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Label-mount_base.html">411</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Label-mount.html">401</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Layer-mount_base.html">2627</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Layer-mount.html">2643</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Link-mount_base.html">504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Link-mount.html">524</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/MakeStyles-mount_base.html">1698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/MakeStyles-mount.html">1681</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/MenuButton-mount_base.html">1375</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/MenuButton-mount.html">1383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/MessageBar-mount_base.html">1801</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/MessageBar-mount.html">1817</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Nav-mount_base.html">2950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Nav-mount.html">2890</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/OverflowSet-mount_base.html">1075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/OverflowSet-mount.html">1056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Panel-mount_base.html">2235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Panel-mount.html">2174</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Persona-mount_base.html">840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Persona-mount.html">829</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Pivot-mount_base.html">1341</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Pivot-mount.html">1346</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/PrimaryButton-mount_base.html">1180</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/PrimaryButton-mount.html">1223</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Rating-mount_base.html">6757</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Rating-mount.html">6726</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/SearchBox-mount_base.html">1246</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/SearchBox-mount.html">1226</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Shimmer-mount_base.html">2295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Shimmer-mount.html">2307</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Slider-mount_base.html">1760</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Slider-mount.html">1780</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/SpinButton-mount_base.html">4391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/SpinButton-mount.html">4397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Spinner-mount_base.html">485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Spinner-mount.html">469</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/SplitButton-mount_base.html">2849</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/SplitButton-mount.html">2808</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Stack-mount_base.html">536</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Stack-mount.html">533</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/StackWithIntrinsicChildren-mount_base.html">1577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/StackWithIntrinsicChildren-mount.html">1555</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/StackWithTextChildren-mount_base.html">4055</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/StackWithTextChildren-mount.html">4065</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/SwatchColorPicker-mount_base.html">9260</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/SwatchColorPicker-mount.html">9063</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/TagPicker-mount_base.html">2414</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/TagPicker-mount.html">2386</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/TeachingBubble-mount_base.html">11429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/TeachingBubble-mount.html">11438</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Text-mount_base.html">470</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Text-mount.html">455</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/TextField-mount_base.html">1247</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/TextField-mount.html">1282</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ThemeProvider-mount_base.html">1107</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ThemeProvider-mount.html">1125</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ThemeProvider-virtual-rerender_base.html">641</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ThemeProvider-virtual-rerender.html">624</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1675</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1675</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Toggle-mount_base.html">808</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/Toggle-mount.html">825</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/buttonNative-mount_base.html">207</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test/buttonNative-mount.html">204</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
ChatDuplicateMessagesPerf.default | [236](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [254](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.93:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ChatDuplicateMessagesPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
CardMinimalPerf.default | [476](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/CardMinimalPerf.default.html) | [412](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.16:1
ChatWithPopoverPerf.default | [332](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ChatWithPopoverPerf.default.html) | [296](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.12:1
LabelMinimalPerf.default | [340](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/LabelMinimalPerf.default.html) | [304](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.12:1
TreeWith60ListItems.default | [166](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TreeWith60ListItems.default.html) | [149](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.11:1
AvatarMinimalPerf.default | [161](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AvatarMinimalPerf.default.html) | [147](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.1:1
HeaderMinimalPerf.default | [311](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/HeaderMinimalPerf.default.html) | [287](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.08:1
ListCommonPerf.default | [539](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ListCommonPerf.default.html) | [506](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ListCommonPerf.default_base.html) | 1.07:1
EmbedMinimalPerf.default | [3492](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/EmbedMinimalPerf.default.html) | [3341](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.05:1
ImageMinimalPerf.default | [328](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ImageMinimalPerf.default.html) | [312](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.05:1
MenuButtonMinimalPerf.default | [1377](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1327](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.04:1
RadioGroupMinimalPerf.default | [388](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.04:1
ReactionMinimalPerf.default | [330](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ReactionMinimalPerf.default.html) | [318](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.04:1
AlertMinimalPerf.default | [238](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AlertMinimalPerf.default.html) | [232](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.03:1
CarouselMinimalPerf.default | [407](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/CarouselMinimalPerf.default.html) | [395](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.03:1
DatepickerMinimalPerf.default | [4797](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4668](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.03:1
FlexMinimalPerf.default | [253](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/FlexMinimalPerf.default.html) | [245](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.03:1
InputMinimalPerf.default | [1113](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/InputMinimalPerf.default.html) | [1084](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.03:1
SliderMinimalPerf.default | [1424](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/SliderMinimalPerf.default.html) | [1384](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.03:1
BoxMinimalPerf.default | [297](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/BoxMinimalPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
HeaderSlotsPerf.default | [627](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/HeaderSlotsPerf.default.html) | [615](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [590](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/LoaderMinimalPerf.default.html) | [581](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
MenuMinimalPerf.default | [733](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/MenuMinimalPerf.default.html) | [722](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.02:1
RosterPerf.default | [1023](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/RosterPerf.default.html) | [1000](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/RosterPerf.default_base.html) | 1.02:1
SegmentMinimalPerf.default | [296](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/SegmentMinimalPerf.default.html) | [291](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [3569](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3499](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
IconMinimalPerf.default | [489](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/IconMinimalPerf.default.html) | [478](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.02:1
TextMinimalPerf.default | [301](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TextMinimalPerf.default.html) | [295](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.02:1
CustomToolbarPrototype.default | [3469](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/CustomToolbarPrototype.default.html) | [3401](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.02:1
AccordionMinimalPerf.default | [136](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AccordionMinimalPerf.default.html) | [135](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.01:1
ButtonSlotsPerf.default | [478](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ButtonSlotsPerf.default.html) | [474](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.01:1
PortalMinimalPerf.default | [157](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/PortalMinimalPerf.default.html) | [155](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.01:1
TextAreaMinimalPerf.default | [417](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TextAreaMinimalPerf.default.html) | [412](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.01:1
TreeMinimalPerf.default | [683](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TreeMinimalPerf.default.html) | [674](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.01:1
VideoMinimalPerf.default | [521](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/VideoMinimalPerf.default.html) | [517](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.01:1
ChatMinimalPerf.default | [559](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ChatMinimalPerf.default.html) | [558](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [2493](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DropdownMinimalPerf.default.html) | [2500](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
ListMinimalPerf.default | [438](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ListMinimalPerf.default.html) | [436](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [509](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/PopupMinimalPerf.default.html) | [511](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [976](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ProviderMinimalPerf.default.html) | [977](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [566](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/StatusMinimalPerf.default.html) | [565](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
TableManyItemsPerf.default | [1560](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TableManyItemsPerf.default.html) | [1559](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1:1
TableMinimalPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TableMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TableMinimalPerf.default_base.html) | 1:1
ToolbarMinimalPerf.default | [798](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ToolbarMinimalPerf.default.html) | [800](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1:1
TooltipMinimalPerf.default | [886](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TooltipMinimalPerf.default.html) | [882](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
AnimationMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AnimationMinimalPerf.default.html) | [352](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.99:1
DropdownManyItemsPerf.default | [528](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DropdownManyItemsPerf.default.html) | [535](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [2212](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2258](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.98:1
DialogMinimalPerf.default | [633](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DialogMinimalPerf.default.html) | [643](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.98:1
AttachmentSlotsPerf.default | [884](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AttachmentSlotsPerf.default.html) | [923](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.96:1
ListWith60ListItems.default | [524](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ListWith60ListItems.default.html) | [544](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.96:1
ButtonOverridesMissPerf.default | [1349](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1441](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.94:1
ItemLayoutMinimalPerf.default | [892](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [964](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.93:1
FormMinimalPerf.default | [320](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/FormMinimalPerf.default.html) | [353](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.91:1
RefMinimalPerf.default | [181](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/RefMinimalPerf.default.html) | [199](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.91:1
SkeletonMinimalPerf.default | [268](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/SkeletonMinimalPerf.default.html) | [296](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.91:1
ListNestedPerf.default | [424](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ListNestedPerf.default.html) | [471](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ListNestedPerf.default_base.html) | 0.9:1
LayoutMinimalPerf.default | [278](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/LayoutMinimalPerf.default.html) | [314](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.89:1
GridMinimalPerf.default | [258](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/GridMinimalPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.88:1
ProviderMergeThemesPerf.default | [1297](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1475](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.88:1
ButtonMinimalPerf.default | [128](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ButtonMinimalPerf.default.html) | [147](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.87:1
DividerMinimalPerf.default | [279](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DividerMinimalPerf.default.html) | [321](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.87:1
AttachmentMinimalPerf.default | [110](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AttachmentMinimalPerf.default.html) | [133](https://fluentuipr.z22.web.core.windows.net/pull/20762/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.83:1

</details><div id="perfComment9423"/>

File: tools/generators/migrate-converged-pkg/index.ts [hunk 2]
```diff
@@ -477,7 +477,7 @@ function getPackageType(tree: Tree, options: NormalizedSchema) {
 function isJs(tree: Tree, options: NormalizedSchema) {
   const jsSourceFiles: string[] = [];
   visitNotIgnoredFiles(tree, options.paths.sourceRoot, treePath => {
-    if (treePath.includes('.js') || treePath.includes('.jsx')) {
```
Comment (ling1726) [inline tools/generators/migrate-converged-pkg/index.ts:480]: was the problem that this check detected `package.json` as having `.js` ?

**Review by ling1726 — APPROVED** [review]

File: tools/generators/migrate-converged-pkg/index.ts (hunk 1 above)
Comment (Hotell) [reply tools/generators/migrate-converged-pkg/index.ts:562]: dammmn ! :D

File: tools/generators/migrate-converged-pkg/index.ts (hunk 2 above)
Comment (Hotell) [reply tools/generators/migrate-converged-pkg/index.ts:480]: yes sir ( package.json, tsconfig.json )
