### PR TITLE
Table/DataGrid: fix visuals for overflow

### LINKED ISSUE #27570: [Bug]: DataGrid / Table: Row border does not extend horizontally when rows overflow horizontally
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components": "9.18.6"
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/fluent-ui-v9-datagrid-h13r52?file=/example.tsx

## Actual Behavior
Recording_20230414T164059
image

## Expected Behavior
The row borders should extend horizontally.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### LINKED ISSUE #28941: [Bug]: Table/DataGrid when overflows parent, the borders don't fill the whole table
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A - internal bug report

## Actual Behavior
Screenshot 2023-08-22 at 12 50 48

## Expected Behavior
Borders reach the end.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by george-cz**
## Previous Behavior

Previously when Table or DataGrid component was inside a component which didn't have enough space for it and it would overflow, the borders on the rows didn't quite reach to the end, since the table was technically the width of the parent. This resulted in a UI like this:

Screenshot 2023-08-22 at 12 50 48

## New Behavior

The new behavior allows for a parent with `overflow: auto` and makes sure the rows always reach the end of the table as they should:

Screenshot 2023-08-22 at 12 52 18

## Related Issue(s)

- Fixes #28941
- Fixes #27570

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/Avatar-mount_base.html">609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/Avatar-mount.html">613</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/Button-mount_base.html">319</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/Button-mount.html">310</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/Field-mount_base.html">1085</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/Field-mount.html">1078</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/FluentProvider-mount_base.html">697</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/FluentProvider-mount.html">693</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/FluentProviderWithTheme-mount_base.html">80</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/FluentProviderWithTheme-mount.html">86</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">66</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">71</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">73</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">71</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/InfoButton-mount_base.html">11</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/InfoButton-mount.html">9</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/MakeStyles-mount_base.html">839</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/MakeStyles-mount.html">843</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/Persona-mount_base.html">1687</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/Persona-mount.html">1669</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/SpinButton-mount_base.html">1316</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/28940/perf-test-react-components/SpinButton-mount.html">1333</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-table/src/hooks/useTableColumnSizing.tsx [hunk 1]
```diff
@@ -77,14 +77,16 @@ function useTableColumnSizingState<TItem>(
       getColumnWidths: columnResizeState.getColumns,
       getTableHeaderCellProps: (columnId: TableColumnId) => {
         const col = columnResizeState.getColumnById(columnId);
+        const isLastColumn = columns[columns.length - 1]?.columnId === columnId;
 
-        const aside = (
+        const aside = isLastColumn ? null : (
```
Comment (george-cz) [inline packages/react-components/react-table/src/hooks/useTableColumnSizing.tsx:82]: having this here for the last columns means that it _always_ overflows it's parent. Since it is not needed (it doesn't do anything), just get rid of it altogether.

File: change/@fluentui-react-table-1a06bc91-0c0f-464f-a1c3-4523427d45a1.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (fabricteam) [inline change/@fluentui-react-table-1a06bc91-0c0f-464f-a1c3-4523427d45a1.json:1]: ## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=28940&commitId=8af5f09741638631821ebde23f5934f54e1febc3&env=prod&clientType=FLUENTUI)


  <details><summary><b>Table layout flex - truncate</b> 3 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Table layout flex - truncate.true.chromium.png|6919| Changed|
|Table layout flex - truncate.false.chromium.png|11832| Changed|
|Table layout flex - truncate.default (disabled).chromium.png|11832| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

File: apps/vr-tests-react-components/src/stories/Table.stories.tsx [hunk 3]
```diff
@@ -634,6 +684,85 @@ const Truncate: React.FC<SharedVrTestArgs & { truncate?: boolean }> = ({ noNativ
...
+      items,
+    },
+    [
+      useTableColumnSizing_unstable({
+        columnSizingOptions,
+      }),
+    ],
+  );
+  return (
+    <div style={{ width: '500px', overflow: 'auto' }}>
```
Comment (ling1726) [inline apps/vr-tests-react-components/src/stories/Table.stories.tsx:710]: Since headless browsers don't display scrollbars by default it might be nice to add a dashed border around the overflow container

**Review by ling1726 — APPROVED** [review]

File: apps/vr-tests-react-components/src/stories/Table.stories.tsx (hunk 3 above)
Comment (george-cz) [reply apps/vr-tests-react-components/src/stories/Table.stories.tsx:710]: sounds good :)
