### PR TITLE
fix(react-dialog): DialogContent scrollbar always visible

### LINKED ISSUE #27347: [Bug]: DialogContent new padding makes scrollbar always visible.
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 7.73 GB / 15.67 GB
  Browsers:
    Chrome: 111.0.5563.111
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-dialog--default

## Actual Behavior
The scroll bar is always visible
image

## Expected Behavior
The scroll bar should not be visible if there is enough room.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

@fluentui/react-dialog

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by bsunderhus**
## Previous Behavior

PR https://github.com/microsoft/fluentui/pull/27248  introduced a regression where the scrollbar would always be visible due to a negative margin.

image

## New Behavior

1. removes declaration of the `height: 100%` from `DialogContent`, which makes height `auto`, which will properly vary `DialogContent` height taking into account the negative margin in cases where the scrollbar should be visible or not 
2. removes unnecessary `height` and  `width` styles from `DialogContent`, `DialogBody` and `DialogSurface` 

## Related Issue(s)

- Fixes #27347

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                          |     Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                   Change |
| :------------------------------------------------------------------------------------------------------------------------- | ---------------------------: | --------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr> | `93.616 kB`<br />`27.452 kB` | `93.571 kB`<br />`27.44 kB` | `-45 B` <br />`-12 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `67.994 kB`<br />`18.395 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `207.4 kB`<br />`57.516 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `38.819 kB`<br />`12.351 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `6.446 kB`<br />`2.185 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4f76849de438f2ee7842121ac3b8176ba1c0a2a5'>4f76849de438f2ee7842121ac3b8176ba1c0a2a5</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.ts [hunk 1]
```diff
@@ -14,7 +14,6 @@ export const dialogContentClassNames: SlotClassNames<DialogContentSlots> = {
 const useStyles = makeStyles({
   root: {
     width: '100%',
```
Comment (ling1726) [inline packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.ts:16]: in general do we need all these `width: 100%` and `height: 100%`  values across the dialog styles? AFAIK `auto` does the same thing in most cases

File: change/@fluentui-react-dialog-19f431ea-3879-40f6-bf2a-177d37d60310.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (fabricteam) [inline change/@fluentui-react-dialog-19f431ea-3879-40f6-bf2a-177d37d60310.json:1]: ## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 4 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=27367&commitId=0816eb2b2f495ff8cd3a602fa570191bba876925&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1899 screenshots unchanged, 0 screenshots with different dimensions and 4 screenshots with visible difference.


  <details><summary><b>unknown</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Dialog.scroll long content - Dark Mode.chromium.png|38| Changed|
|Dialog.scroll long content - High Contrast.chromium.png|45| Changed|
|Dialog.scroll long content - RTL.chromium.png|39| Changed|
|Dialog.scroll long content.chromium.png|39| Changed|

</details>


<div id="vrtCommentfluentuiv9"/>

File: packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.ts (hunk 1 above)
Comment (bsunderhus) [reply packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.ts:16]: I'll see to remove both then 👍🏻

**Comment by lekoaf** [comment]
This seems to work. Did some quick testing on the Codesandbox.

I'm gonna have to do some changes to _my_ code though because I add padding-top and padding-bottom to the `<DialogContent/>` which makes the scrollbars appear again. I felt that the dialog didn't have enough padding when you only use it for a small piece of text.

```jsx
const useDialogStyles = makeStyles({
  sections: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: tokens.spacingVerticalL,
    paddingTop: tokens.spacingVerticalS,
    paddingBottom: tokens.spacingVerticalXXXL,
  },
  title: {
    overflowWrap: 'break-word',
  },
})

function MyCustomDialog({
  open = true,
  onClose,
  title,
  children,
}) {
  const dialogStyles = useDialogStyles()

  return (
    <Dialog
      open={open}
      onOpenChange={(_event, data) => !data.open && onClose?.()}
    >
      <DialogSurface>
        <DialogBody>
          <DialogTitle className={dialogStyles.title}>{title}</DialogTitle>
          <DialogContent className={dialogStyles.sections}>{children}</DialogContent>
          <DialogActions>
            <DialogTrigger disableButtonEnhancement><Button /></DialogTrigger>
            <Button />
          </DialogActions>
        </DialogBody>
      </DialogSurface>
    </Dialog>
  )
}
```
