### PR TITLE
react-button: Removing flex gap from button components and fixing spacing to better align with design spec

### LINKED ISSUE #22867: [Bug]: Split button and Menu button padding issue
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
v9
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://61b7c406fa7cd4003a8a07ec-tfmcclkdkx.chromatic.com/?path=/docs/components-splitbutton--default

## Actual Behavior
Screen Shot 2022-05-05 at 3 51 09 PM
In Button design spec and Web UI kits, the padding in the arrow icon in Split button is 4px but the padding in storybook seems bigger than 4px. Also, the padding on the left of arrow in Menu button should be 4px and the right padding should be 12px. 

## Expected Behavior
The padding around arrow icon in Split and Menu buttons should be the same as Design spec and Web UI kits.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

- `Button` components use `flex gap`, which is not available on some browsers in our support matrix.
- The spacing in `Button` components does not align exactly to the design spec.
- The size of the menu icon in `MenuButton` and `SplitButton` is not the one specified in the design spec.

## New Behavior

- `Button` components do not use `flex` gap anymore, and instead use a combination of `margin` styles.
- The spacing in `Button` components aligns exactly to the design spec.
- - The size of the menu icon in `MenuButton` and `SplitButton` is the one specified in the design spec.

## Related Issue(s)

Fixes #22867 and part of #22704

_Note:_ This PR only removes `flex gap` in the components, we still need to remove it from stories.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                   Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `32.487 kB`<br />`9.024 kB` |   `32.688 kB`<br />`9.084 kB` |  `201 B` <br />`60 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `38.736 kB`<br />`10.178 kB` |  `39.123 kB`<br />`10.311 kB` | `387 B` <br />`133 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `34.281 kB`<br />`9.614 kB` |   `34.871 kB`<br />`9.835 kB` | `590 B` <br />`221 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `41.562 kB`<br />`10.917 kB` |  `42.225 kB`<br />`11.151 kB` | `663 B` <br />`234 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `43.418 kB`<br />`9.953 kB` |  `43.619 kB`<br />`10.024 kB` |  `201 B` <br />`71 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `179.667 kB`<br />`50.151 kB` | `179.868 kB`<br />`50.199 kB` |  `201 B` <br />`48 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                         | `45.608 kB`<br />`13.312 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                     | `59.002 kB`<br />`16.923 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                               | `54.287 kB`<br />`15.672 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |   `7.793 kB`<br />`3.327 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |   `9.363 kB`<br />`3.841 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |    `7.765 kB`<br />`3.35 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `34.078 kB`<br />`11.098 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/44062b15587c3a18b7f02d2beb3ba19fa793fb9c'>44062b15587c3a18b7f02d2beb3ba19fa793fb9c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/Avatar-mount_base.html">1066</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/Avatar-mount.html">1131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/Button-mount_base.html">653</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/Button-mount.html">663</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/FluentProvider-mount_base.html">2229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/FluentProvider-mount.html">2244</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/FluentProviderWithTheme-mount_base.html">333</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/FluentProviderWithTheme-mount.html">353</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">287</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">293</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">403</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/MakeStyles-mount_base.html">1911</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23091/perf-test-react-components/MakeStyles-mount.html">1844</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts [hunk 1]
```diff
@@ -175,7 +175,7 @@ const useRootStyles = makeStyles({
 
   // Size variations
   small: {
-    ...shorthands.padding('0', '8px'),
+    ...shorthands.padding(tokens.spacingHorizontalNone, tokens.spacingHorizontalS),
```
Comment (spmonahan) [inline packages/react-components/react-button/src/components/Button/useButtonStyles.ts:178]: I believe the first token should be `spacingVerticalNone`.

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts [hunk 2]
```diff
@@ -187,7 +187,7 @@ const useRootStyles = makeStyles({
     lineHeight: tokens.lineHeightBase200,
   },
   medium: {
-    ...shorthands.padding('0', '12px'),
+    ...shorthands.padding(tokens.spacingHorizontalNone, tokens.spacingHorizontalM),
```
Comment (spmonahan) [inline packages/react-components/react-button/src/components/Button/useButtonStyles.ts:190]: Same as above.

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts [hunk 3]
```diff
@@ -199,7 +199,7 @@ const useRootStyles = makeStyles({
     lineHeight: tokens.lineHeightBase300,
   },
   large: {
-    ...shorthands.padding('0', '16px'),
+    ...shorthands.padding(tokens.spacingHorizontalNone, tokens.spacingHorizontalL),
```
Comment (spmonahan) [inline packages/react-components/react-button/src/components/Button/useButtonStyles.ts:202]: Same as above.

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts [hunk 4]
```diff
@@ -14,6 +14,8 @@ export const buttonClassNames: SlotClassNames<ButtonSlots> = {
  */
 export const buttonClassName = buttonClassNames.root;
 
+const iconSpacingVar = '--fui-Button__icon--spacing';
```
Comment (spmonahan) [inline packages/react-components/react-button/src/components/Button/useButtonStyles.ts:17]: This CSS var name is consistent with the way we name CSS classes on slots but is different from the way we name our token CSS vars. Should the name be changed to align with token CSS vars?

**Review by spmonahan — APPROVED** [review]
Looks good overall, left a few comments.

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts (hunk 4 above)
Comment (khmakoto) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:17]: I used the approach we have in `useSliderStyles` since that's the only other place I'm aware that we're using tokens.

Comment (khmakoto) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:17]: I've created a follow-up issue to figure out our naming convention for component-level css variables, so we don't block this PR on that. It can be found at #23095.
