### PR TITLE
fix: overflowManager should always dispatch initial state

### LINKED ISSUE #27656: [Bug]: useIsOverflowItemVisible returns incorrect at initial state
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 51.85 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/admiring-feather-mtyojz?file=/example.tsx

## Actual Behavior
At initial state when there is enough space for all items to show, useIsOverflowItemVisible returns false for each item. As the screenshot shows, and you can also check it in the reproduction codesandbox. It feels like at initial state, and the space is enough, items are not registered to the overflow or the initial context set to false; and the state in context changes only after resize happens. (Let me know if my guess is correct, thank you 😊) 

image

## Expected Behavior
Expect the useIsOverflowItemVisible returns true when initial state the items are really showing.

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ling1726**
Fixes #27656 which was caused by a priority queue edge case.

On initial mount the resize observer will always run. If there is already overflow then the tops of the visibility queues will be different from the initial state (all items are considered visible by default).

In the cause where there is no overflow initially the queue tops will not change, which does not trigger a dispatch to the react bindings so the `useIsOverflowItemVisible` hook will always return `false` until overflow occurs.

The fix is quite simple: set the initial value of flag `forceDispatch` to be `true` which will always trigger a dispatch for initial mount.

### CODE REVIEW

File: packages/react-components/react-overflow/src/components/Overflow.tsx [hunk 1]
```diff
@@ -24,21 +30,27 @@ export const Overflow = React.forwardRef((props: OverflowProps, ref) => {
...
+    itemVisibility: {},
+    groupVisibility: {},
+  });
 
   // useOverflowContainer wraps this method in a useEventCallback.
-  // TODO: Do we need a useEventCallback here too?
   const update: OnUpdateOverflow = data => {
-    setHasOverflow(() => data.invisibleItems.length > 0);
-    setItemVisibility(() => {
-      const newState: Record<string, boolean> = {};
```
Comment (ling1726) [inline packages/react-components/react-overflow/src/components/Overflow.tsx:36]: These seperate states were always updated togeter, it makes no sense to have them separate

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                        |   Baseline (minified/GZIP) |                         PR |                                                                                                Change |
| :----------------------------------------------------------------------------------------------------------------------- | -------------------------: | -------------------------: | ----------------------------------------------------------------------------------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr> | `3.194 kB`<br />`1.314 kB` | `3.194 kB`<br />`1.315 kB` | <br />`1 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `65.31 kB`<br />`17.931 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `204.34 kB`<br />`57.141 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |   `36.086 kB`<br />`11.9 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                                                               |  `11.214 kB`<br />`4.271 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `6.446 kB`<br />`2.186 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/f0b05741d812ad90c52754b0b4035d5554cf2aa0'>f0b05741d812ad90c52754b0b4035d5554cf2aa0</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-components/react-overflow/src/Overflow.cy.tsx [hunk 2]
```diff
@@ -539,4 +540,35 @@ describe('Overflow', () => {
...
+          <Item key={i} id={i.toString()}>
+            {i}
+          </Item>
+        ))}
+        <Menu />
+        <Assert />
+      </Container>,
+    );
+
+    setContainerSize(500);
```
Comment (miroslavstastny) [inline packages/react-components/react-overflow/src/Overflow.cy.tsx:571]: What is the `setContainerSize()` good for in the test?

**Review by miroslavstastny — APPROVED** [review]

File: packages/react-components/react-overflow/src/Overflow.cy.tsx (hunk 2 above)
Comment (ling1726) [reply packages/react-components/react-overflow/src/Overflow.cy.tsx:571]:
```suggestion
```
