### PR TITLE
fix(tools): bump northstar packages v9 deps on dep mismatch resolution

### LINKED ISSUE #25316: dependency-mismatch generator doesn't handle portal compat and northstar
Affected release: https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=271198&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=a5e45ad2-7904-508f-791a-1a783f6a099f

The dependency mismatch generator hit an edge case and failed to update the northstar dependency. Investigate this and avoid future recurrenct

### PR DESCRIPTION
**Pull request by Hotell**
## Related Issue(s)

* Fixes #25316

### CODE REVIEW

File: tools/utils.ts [hunk 1]
```diff
@@ -197,7 +197,7 @@ export function isPackageVersionConverged(versionString: string) {
 
 export function isPackageVersionPrerelease(versionString: string) {
   const version = semver.parse(versionString);
-  return version?.prerelease?.length && version?.prerelease?.length > 0;
+  return Boolean(version?.prerelease?.length && version?.prerelease?.length > 0);
```
Comment (Hotell) [inline tools/utils.ts:200]: casted to explicitly return `boolean` instead of undefined/number/boolean

File: tools/generators/dependency-mismatch/index.ts [hunk 2]
```diff
@@ -2,31 +2,32 @@ import * as semver from 'semver';
...
-    // Ignore northstar packages
-    if (tags.includes('react-northstar')) {
-      return;
-    }
+    const scope = getProjectScope(config);
 
     updateJson(tree, config.paths.packageJson, (packageJson: PackageJson) => {
       if (packageJson.dependencies) {
-        packageJson.dependencies = getUpdatedDependencies(tree, packageJson.dependencies);
+        packageJson.dependencies = getUpdatedDependencies(tree, { dependencies: packageJson.dependencies, scope });
```
Comment (Hotell) [inline tools/generators/dependency-mismatch/index.ts:16]: more args needed -> refactored to options pattern

File: tools/generators/dependency-mismatch/index.spec.ts [hunk 3]
```diff
@@ -125,7 +125,7 @@ describe('dependency-mismatch generator', () => {
     });
     await generator(appTree);
 
-    const packageJson: PackageJson = await readTargetPackageJson();
```
Comment (Hotell) [inline tools/generators/dependency-mismatch/index.spec.ts:128]: these awaits dont do anything as readTargetPackageJson is sync

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0da8d7556d18b42a7c702c513e702ba3723d64d3'>0da8d7556d18b42a7c702c513e702ba3723d64d3</a></sub>
<div id="bundleSizeComment9423"/>

File: tools/generators/dependency-mismatch/index.ts [hunk 4]
```diff
@@ -73,3 +84,11 @@ function getUpdatedDependencies(tree: Tree, dependencies: Record<string, string>
     return acc;
   }, dependencies);
 }
+
+function getProjectScope(project: ReturnType<typeof getProjectConfig>) {
```
Comment (ling1726) [inline tools/generators/dependency-mismatch/index.ts:88]: move this to utils?

**Review by ling1726 — APPROVED** [review]
`scope` is a nice idea, future generators should use this option if we need specific handling by library 👍

File: tools/generators/dependency-mismatch/index.ts (hunk 4 above)
Comment (Hotell) [reply tools/generators/dependency-mismatch/index.ts:88]: yeah I was hesitant about that :D , we can do that later if we find shared usage for this

Comment (Hotell) [reply tools/generators/dependency-mismatch/index.ts:88]: will do a follow - normalizing all tags and tweaking this to utils
