### PR TITLE
fix(react-portal): replace Node.ELEMENT_NODE with hardcoded value for SSR compatibility

### LINKED ISSUE #35349: [Bug]: react-portal: Node.ELEMENT_NODE causes SSR failures
### Component

Portal

### Package version

9.72.2

### React version

18.3.0

### Environment

```shell
System:
    OS: macOS 26.0.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 10.88 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 141.0.7390.108
    Edge: 141.0.3537.85
    Safari: 26.0.1
```

### Current Behavior

When using `@fluentui/react-portal` in an SSR environment, the build/tooling fails with a reference error because `Node.ELEMENT_NODE` is referenced in the code. Even though this code is inside a React hook (`useModernElementFactory`), the Proxy getter trap is defined during component render on the server, causing the browser-only `Node` API to be evaluated in a Node.js environment where it doesn't exist.

### Expected Behavior

The portal should work correctly in both SSR and client-side rendering environments without throwing reference errors during the build or runtime.

### Reproduction

https://stackblitz.com/

### Steps to reproduce

1. Use `@fluentui/react-portal` in a Next.js, Remix, or other SSR application
2. Attempt to build or run the application with server-side rendering enabled
3. Observe the error: `ReferenceError: Node is not defined`

### Are you reporting an Accessibility issue?

None

### Suggested severity

High - No workaround

### Products/sites affected

Loop

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by dmytrokirpa**
## Previous Behavior

Users reported that their SSR tooling was failing with errors when encountering the `Node.ELEMENT_NODE` reference in the portal mount node hook. Even though the code is inside a hook, the Proxy's `get` trap function is defined during component render, and the reference to `Node.ELEMENT_NODE` (a browser-only API) was being evaluated on the server where the `Node` global is not available.

## New Behavior

Replace the `Node.ELEMENT_NODE` constant with its literal value `1` and add a comment explaining why. This maintains the same functionality while ensuring compatibility with SSR environments.

## Related Issue(s)

- Fixes #35349

### CODE REVIEW

File: packages/react-components/react-portal/library/src/components/Portal/usePortalMountNode.ts [hunk 1]
```diff
@@ -134,7 +134,8 @@ const useModernElementFactory: UseElementFactory = options => {
         // before mounting the portal. We hardcode the value to `Node.ELEMENT_NODE` to pass this check and avoid
         // premature node creation
         if (property === 'nodeType') {
-          return Node.ELEMENT_NODE;
+          // Can't use the `Node.ELEMENT_NODE` as it's a browser API and  not available in all environments, e.g SSR
```
Comment (Hotell) [inline packages/react-components/react-portal/library/src/components/Portal/usePortalMountNode.ts:137]: we need to automate this -> lets add `NODE` to restrictedGlobals `packages/eslint-plugin/src/shared/restricted-globals.js`

Comment (Hotell) [reply packages/react-components/react-portal/library/src/components/Portal/usePortalMountNode.ts:137]: https://github.com/microsoft/fluentui/issues/35356

**Review by Hotell — APPROVED** [review]
