### PR TITLE
fix(RadioGroupItem): do not always `preventDefault()`

### LINKED ISSUE #13065: @fluentui/react-northstar: Spacebar not detected in custom RadioGroup input
### Environment Information

- **Package version(s)**: react-northstar 0.48.0

### Describe the issue:
Spacebar not detected in custom RadioGroup input, reprodicuble even within docs 

#### Actual behavior:
When you try to input text in custom field spacebar does not causes change to input field

#### Expected behavior:
Of course one should be able to input custom text in custom field

### If applicable, please provide a codepen repro:
https://fluentsite.z22.web.core.windows.net/components/radio-group/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#types-radio-group

https://codesandbox.io/s/6yuww?module=/example.js

### Priorities and help requested (not applicable if asking question):

Requested priority: ( Normal)

### PR DESCRIPTION
**Pull request by layershifter**
#### Description of changes

This PR fixes #13065. Adds a shared `shouldPreventDefaultOnKeyDown()` that should determine if `preventDefault()` should be called as for <kbd>Space</kbd> it also prevents user input in text fields.

### CODE REVIEW

File: packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import { shouldPreventDefaultOnKeyDown } from '../../../src/utils/shouldPreventDefaultOnKeyDown';
+
+describe('fontSizeUtility', () => {
```
Comment (miroslavstastny) [inline packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts:3]: `fontSizeUtility`? 🤔

**Review by miroslavstastny — APPROVED** [review]

File: packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts (hunk 1 above)
Comment (layershifter) [reply packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts:3]:
```suggestion
describe('shouldPreventDefaultOnKeyDown', () => {
```

Comment (layershifter) [reply packages/fluentui/react-northstar/test/specs/utils/shouldPreventDefaultOnKeyDown-test.ts:3]: Copy-paste is evil 😈
