### PR TITLE
fix(makeStyles): DOM renderer should not throw in SSR

### LINKED ISSUE #17902: @fluentui/make-styles: createDOMRenderer() throws an error in SSR
### Environment Information

- **Package version(s)**: @fluentui/make-styles@9.0.0-alpha.12
- **Browser and OS versions**: NA

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/pensive-agnesi-9o8mx

#### Actual behavior:

An error 🚨

```
ReferenceError: document is not defined
    at Object.createDOMRenderer (/sandbox/node_modules/@fluentui/make-styles/lib-commonjs/renderer/createDOMRenderer.js:55:30)
    at /sandbox/node_modules/@fluentui/react-make-styles/lib-commonjs/useRenderer.js:7:30
    at Object.useMemo (/sandbox/node_modules/react-dom/cjs/react-dom-server.node.development.js:1239:19)
    at Object.useMemo (/sandbox/node_modules/react/cjs/react.development.js:1521:21)
```

We are using `document` as a default value, it's undefined in SSR:

https://github.com/microsoft/fluentui/blob/7feded422987e9c82f3250f419ab62118a52f9d4/packages/make-styles/src/renderer/createDOMRenderer.ts#L78

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: Normal
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by layershifter**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #17902
- [x] Include a change request file using `$ yarn change`

#### Description of changes

This PR makes existing renderer compatible with SSR apps. We still need to introduce a renderer/an approach for generating styles on server, but at least it will not throw after this PR.

### CODE REVIEW

File: packages/make-styles/src/renderer/createDOMRenderer.ts [hunk 1]
```diff
@@ -114,15 +122,17 @@ export function createDOMRenderer(target: Document = document): MakeStylesDOMRen
...
-
-        try {
-          sheet.insertRule(ruleCSS, sheet.cssRules.length);
-        } catch (e) {
-          // We've disabled these warnings due to false-positive errors with browser prefixes
-          if (process.env.NODE_ENV !== 'production' && !ignoreSuffixesRegex.test(ruleCSS)) {
-            // eslint-disable-next-line no-console
-            console.error(`There was a problem inserting the following rule: "${ruleCSS}"`, e);
+        if (target) {
+          const sheet = getStyleSheetForBucket(bucketName, target, renderer);
```
Comment (ling1726) [inline packages/make-styles/src/renderer/createDOMRenderer.ts:126]: why not have `getStyleSheetForBucket` return undefined/null ?

**Review by ling1726 — APPROVED** [review]

File: packages/make-styles/src/renderer/createDOMRenderer.ts (hunk 1 above)
Comment (layershifter) [reply packages/make-styles/src/renderer/createDOMRenderer.ts:126]: Then we will need to have a condition on `sheet` usage, i.e. `sheet?.insertRule`. From my POV it's less obvious 😯

Comment (ling1726) [reply packages/make-styles/src/renderer/createDOMRenderer.ts:126]: I guess it's personal preference, your call

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Avatar-mount_base.html">967</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Avatar-mount.html">959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/BaseButton-mount_base.html">989</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/BaseButton-mount.html">994</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Breadcrumb-mount_base.html">43417</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Breadcrumb-mount.html">43681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ButtonNext-mount_base.html">575</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ButtonNext-mount.html">611</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Checkbox-mount_base.html">1680</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Checkbox-mount.html">1680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/CheckboxBase-mount_base.html">1396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/CheckboxBase-mount.html">1399</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ChoiceGroup-mount_base.html">5224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ChoiceGroup-mount.html">5132</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ComboBox-mount_base.html">1035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ComboBox-mount.html">1021</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/CommandBar-mount_base.html">10908</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/CommandBar-mount.html">10353</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ContextualMenu-mount_base.html">6382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ContextualMenu-mount.html">6434</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DefaultButton-mount_base.html">1165</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DefaultButton-mount.html">1234</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DetailsRow-mount_base.html">3777</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DetailsRow-mount.html">3879</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DetailsRowFast-mount_base.html">3878</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DetailsRowFast-mount.html">3884</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DetailsRowNoStyles-mount_base.html">3742</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DetailsRowNoStyles-mount.html">3724</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Dialog-mount_base.html">1571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Dialog-mount.html">1625</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DocumentCardTitle-mount_base.html">1880</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/DocumentCardTitle-mount.html">1841</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Dropdown-mount_base.html">3444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Dropdown-mount.html">3468</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/FocusTrapZone-mount_base.html">1882</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/FocusTrapZone-mount.html">1838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/FocusZone-mount_base.html">1830</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/FocusZone-mount.html">1851</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/IconButton-mount_base.html">1903</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/IconButton-mount.html">1867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Label-mount_base.html">349</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Label-mount.html">334</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Layer-mount_base.html">1910</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Layer-mount.html">1864</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Link-mount_base.html">502</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Link-mount.html">510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/MakeStyles-mount_base.html">1801</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/MakeStyles-mount.html">1838</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/MenuButton-mount_base.html">1569</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/MenuButton-mount.html">1614</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/MessageBar-mount_base.html">2074</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/MessageBar-mount.html">2090</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Nav-mount_base.html">3584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Nav-mount.html">3530</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/OverflowSet-mount_base.html">1113</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/OverflowSet-mount.html">1130</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Panel-mount_base.html">1411</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Panel-mount.html">1515</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Persona-mount_base.html">832</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Persona-mount.html">868</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Pivot-mount_base.html">1571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Pivot-mount.html">1497</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/PrimaryButton-mount_base.html">1323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/PrimaryButton-mount.html">1366</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Rating-mount_base.html">8339</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Rating-mount.html">8239</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/SearchBox-mount_base.html">1421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/SearchBox-mount.html">1426</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Shimmer-mount_base.html">2748</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Shimmer-mount.html">2790</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Slider-mount_base.html">2117</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Slider-mount.html">2067</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/SpinButton-mount_base.html">5326</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/SpinButton-mount.html">5273</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Spinner-mount_base.html">478</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Spinner-mount.html">467</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/SplitButton-mount_base.html">3343</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/SplitButton-mount.html">3352</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Stack-mount_base.html">534</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Stack-mount.html">553</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/StackWithIntrinsicChildren-mount_base.html">1703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/StackWithIntrinsicChildren-mount.html">1716</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/StackWithTextChildren-mount_base.html">4992</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/StackWithTextChildren-mount.html">4965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/SwatchColorPicker-mount_base.html">10863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/SwatchColorPicker-mount.html">10815</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Tabs-mount_base.html">1470</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Tabs-mount.html">1500</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/TagPicker-mount_base.html">2594</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/TagPicker-mount.html">2678</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/TeachingBubble-mount_base.html">12207</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/TeachingBubble-mount.html">12046</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Text-mount_base.html">464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Text-mount.html">455</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/TextField-mount_base.html">1461</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/TextField-mount.html">1488</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ThemeProvider-mount_base.html">1244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ThemeProvider-mount.html">1199</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ThemeProvider-virtual-rerender_base.html">597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ThemeProvider-virtual-rerender.html">605</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ThemeProviderNext-mount_base.html">8865</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/ThemeProviderNext-mount.html">8776</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Toggle-mount_base.html">835</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/Toggle-mount.html">838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/buttonNative-mount_base.html">109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test/buttonNative-mount.html">113</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.19](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Avatar.Fluent.html) | 0.49 | 0.39:1 | 2000 | 377
🦄 | Button.Fluent | [0.13](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Button.Fluent.html) | 0.22 | 0.59:1 | 5000 | 654
🔧 | Checkbox.Fluent | [0.65](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Checkbox.Fluent.html) | 0.38 | 1.71:1 | 1000 | 645
🎯 | Dialog.Fluent | [0.16](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Dialog.Fluent.html) | 0.23 | 0.7:1 | 5000 | 779
🔧 | Dropdown.Fluent | [3.19](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Dropdown.Fluent.html) | 0.42 | 7.6:1 | 1000 | 3187
🔧 | Icon.Fluent | [0.14](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Icon.Fluent.html) | 0.07 | 2:1 | 5000 | 692
🦄 | Image.Fluent | [0.08](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Image.Fluent.html) | 0.13 | 0.62:1 | 5000 | 415
🔧 | Slider.Fluent | [1.7](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Slider.Fluent.html) | 0.5 | 3.4:1 | 1000 | 1695
🔧 | Text.Fluent | [0.08](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Text.Fluent.html) | 0.04 | 2:1 | 5000 | 411
🦄 | Tooltip.Fluent | [0.16](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Tooltip.Fluent.html) | 0.97 | 0.16:1 | 5000 | 814
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
LabelMinimalPerf.default | [466](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/LabelMinimalPerf.default.html) | [409](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.14:1
TextMinimalPerf.default | [434](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TextMinimalPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.13:1
TreeWith60ListItems.default | [222](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TreeWith60ListItems.default.html) | [196](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.13:1
FormMinimalPerf.default | [508](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/FormMinimalPerf.default.html) | [461](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.1:1
GridMinimalPerf.default | [426](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/GridMinimalPerf.default.html) | [388](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.1:1
RadioGroupMinimalPerf.default | [521](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [477](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.09:1
TextAreaMinimalPerf.default | [618](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TextAreaMinimalPerf.default.html) | [568](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.09:1
ButtonMinimalPerf.default | [213](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonMinimalPerf.default.html) | [197](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.08:1
Tooltip.Fluent | [814](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Tooltip.Fluent.html) | [754](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Tooltip.Fluent_base.html) | 1.08:1
AnimationMinimalPerf.default | [468](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AnimationMinimalPerf.default.html) | [437](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.07:1
ListMinimalPerf.default | [588](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ListMinimalPerf.default.html) | [551](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.07:1
PortalMinimalPerf.default | [181](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/PortalMinimalPerf.default.html) | [169](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.07:1
SplitButtonMinimalPerf.default | [4261](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3968](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.07:1
BoxMinimalPerf.default | [414](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/BoxMinimalPerf.default.html) | [392](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.06:1
AlertMinimalPerf.default | [318](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AlertMinimalPerf.default.html) | [302](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.05:1
AttachmentMinimalPerf.default | [192](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AttachmentMinimalPerf.default.html) | [182](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.05:1
AttachmentSlotsPerf.default | [1258](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1199](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.05:1
FlexMinimalPerf.default | [351](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/FlexMinimalPerf.default.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.05:1
IconMinimalPerf.default | [714](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/IconMinimalPerf.default.html) | [677](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.05:1
DialogMinimalPerf.default | [828](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DialogMinimalPerf.default.html) | [798](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.04:1
DropdownManyItemsPerf.default | [786](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DropdownManyItemsPerf.default.html) | [754](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.04:1
TableManyItemsPerf.default | [2166](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TableManyItemsPerf.default.html) | [2077](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.04:1
AvatarMinimalPerf.default | [225](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AvatarMinimalPerf.default.html) | [219](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.03:1
ButtonSlotsPerf.default | [616](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonSlotsPerf.default.html) | [596](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
CarouselMinimalPerf.default | [533](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/CarouselMinimalPerf.default.html) | [517](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.03:1
ChatMinimalPerf.default | [678](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ChatMinimalPerf.default.html) | [659](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.03:1
DatepickerMinimalPerf.default | [49980](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DatepickerMinimalPerf.default.html) | [48540](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.03:1
HeaderMinimalPerf.default | [431](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/HeaderMinimalPerf.default.html) | [417](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.03:1
HeaderSlotsPerf.default | [922](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/HeaderSlotsPerf.default.html) | [893](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [403](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/SegmentMinimalPerf.default.html) | [391](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [1063](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1036](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
TooltipMinimalPerf.default | [1066](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TooltipMinimalPerf.default.html) | [1037](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.03:1
Button.Fluent | [654](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Button.Fluent.html) | [633](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Button.Fluent_base.html) | 1.03:1
ButtonUseCssPerf.default | [904](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonUseCssPerf.default.html) | [885](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 1.02:1
InputMinimalPerf.default | [1375](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/InputMinimalPerf.default.html) | [1346](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.02:1
RosterPerf.default | [1332](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/RosterPerf.default.html) | [1307](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/RosterPerf.default_base.html) | 1.02:1
ReactionMinimalPerf.default | [422](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ReactionMinimalPerf.default.html) | [415](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.02:1
VideoMinimalPerf.default | [684](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/VideoMinimalPerf.default.html) | [673](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.02:1
ListCommonPerf.default | [699](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ListCommonPerf.default.html) | [692](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
ListNestedPerf.default | [610](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ListNestedPerf.default.html) | [605](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ListNestedPerf.default_base.html) | 1.01:1
MenuButtonMinimalPerf.default | [1734](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1722](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.01:1
PopupMinimalPerf.default | [753](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/PopupMinimalPerf.default.html) | [748](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [1704](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1682](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
RefMinimalPerf.default | [260](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/RefMinimalPerf.default.html) | [258](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.01:1
CustomToolbarPrototype.default | [4030](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/CustomToolbarPrototype.default.html) | [3974](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.01:1
Checkbox.Fluent | [645](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Checkbox.Fluent.html) | [636](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Checkbox.Fluent_base.html) | 1.01:1
Icon.Fluent | [692](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Icon.Fluent.html) | [682](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Icon.Fluent_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1796](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1791](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4660](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/EmbedMinimalPerf.default.html) | [4663](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
ItemLayoutMinimalPerf.default | [1382](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1382](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1:1
LoaderMinimalPerf.default | [739](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/LoaderMinimalPerf.default.html) | [737](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1:1
Avatar.Fluent | [377](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Avatar.Fluent.html) | [377](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Avatar.Fluent_base.html) | 1:1
Text.Fluent | [411](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Text.Fluent.html) | [410](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Text.Fluent_base.html) | 1:1
ButtonUseCssNestingPerf.default | [1127](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1142](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 0.99:1
CardMinimalPerf.default | [617](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/CardMinimalPerf.default.html) | [623](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.99:1
ChatWithPopoverPerf.default | [425](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ChatWithPopoverPerf.default.html) | [428](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.99:1
StatusMinimalPerf.default | [736](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/StatusMinimalPerf.default.html) | [742](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.99:1
TableMinimalPerf.default | [466](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TableMinimalPerf.default.html) | [473](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.99:1
TreeMinimalPerf.default | [859](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TreeMinimalPerf.default.html) | [866](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.99:1
AccordionMinimalPerf.default | [187](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AccordionMinimalPerf.default.html) | [190](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.98:1
ChatDuplicateMessagesPerf.default | [317](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [323](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.98:1
LayoutMinimalPerf.default | [409](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/LayoutMinimalPerf.default.html) | [419](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.98:1
MenuMinimalPerf.default | [974](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/MenuMinimalPerf.default.html) | [991](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/MenuMinimalPerf.default_base.html) | 0.98:1
ProviderMinimalPerf.default | [1065](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ProviderMinimalPerf.default.html) | [1091](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.98:1
Image.Fluent | [415](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Image.Fluent.html) | [422](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Image.Fluent_base.html) | 0.98:1
CheckboxMinimalPerf.default | [2913](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2989](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.97:1
DropdownMinimalPerf.default | [3144](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DropdownMinimalPerf.default.html) | [3250](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.97:1
Dropdown.Fluent | [3187](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Dropdown.Fluent.html) | [3296](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Dropdown.Fluent_base.html) | 0.97:1
Slider.Fluent | [1695](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Slider.Fluent.html) | [1740](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Slider.Fluent_base.html) | 0.97:1
ImageMinimalPerf.default | [417](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ImageMinimalPerf.default.html) | [434](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.96:1
SliderMinimalPerf.default | [1626](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/SliderMinimalPerf.default.html) | [1686](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.96:1
Dialog.Fluent | [779](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Dialog.Fluent.html) | [812](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/Dialog.Fluent_base.html) | 0.96:1
DividerMinimalPerf.default | [414](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DividerMinimalPerf.default.html) | [435](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.95:1
ListWith60ListItems.default | [698](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ListWith60ListItems.default.html) | [732](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.95:1
SkeletonMinimalPerf.default | [402](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/SkeletonMinimalPerf.default.html) | [425](https://fluentuipr.z22.web.core.windows.net/pull/17904/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.95:1

</details><div id="perfComment9423"/>
