### PR TITLE
fix(react-context-selector): fix React warnings about setState()

### LINKED ISSUE #16569: react-northstar error: Warning: Cannot update a component (`MenuItem`) while rendering a different component
I'm not sure why this is happening. I'm using the HashRouter with Menu and it's giving this error whenever the link changes. The error is really cryptic and I'm wondering why it may be happening. If necessary, I can provide a simple example repo.

```
react-dom.development.js:88 Warning: Cannot update a component (`MenuItem`) while rendering a different component (`ContextSelector.Provider`). To locate the bad setState() call inside `ContextSelector.Provider`, follow the stack trace as described in https://fb.me/setstate-in-render
    in ContextSelector.Provider (created by Menu)
    in ul (created by FocusZone)
    in FocusZone (created by Menu)
    in Menu (at frame.jsx:36)
    in div (created by Flex)
    in Flex (at frame.jsx:35)
    in FrameHeader (at frame.jsx:101)
    in div (at frame.jsx:95)
    in div (created by Provider)
    in RendererProvider (created by Provider)
    in Provider (created by Provider)
    in Provider (at frame.jsx:94)
    in Router (created by HashRouter)
    in HashRouter (at frame.jsx:93)
    in FrameLayout (at App.jsx:57)
    in App (at main-inner.jsx:9)
```

### PR DESCRIPTION
**Pull request by assuncaocharles**
Fixes #16569.

#### Description of changes

Refactor how context selectors handle updates to use `unstable_runWithPriority()`. Removes `changeBits=0` usage, so no longer depends on this undocumented feature.

See https://github.com/dai-shi/use-context-selector/commit/a188a450d09872c87045b5fa86c643ce6789b448 for reference.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Avatar-mount_base.html">745</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Avatar-mount.html">791</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/BaseButtonCompat-mount_base.html">841</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/BaseButtonCompat-mount.html">847</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Breadcrumb-mount_base.html">40395</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Breadcrumb-mount.html">40288</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Checkbox-mount_base.html">1403</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Checkbox-mount.html">1350</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/CheckboxBase-mount_base.html">1180</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/CheckboxBase-mount.html">1169</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ChoiceGroup-mount_base.html">4431</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ChoiceGroup-mount.html">4381</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ComboBox-mount_base.html">1007</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ComboBox-mount.html">925</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/CommandBar-mount_base.html">9458</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/CommandBar-mount.html">9572</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ContextualMenu-mount_base.html">5676</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ContextualMenu-mount.html">5654</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DefaultButtonCompat-mount_base.html">1041</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DefaultButtonCompat-mount.html">1038</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DetailsRow-mount_base.html">3365</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DetailsRow-mount.html">3377</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DetailsRowFast-mount_base.html">3354</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DetailsRowFast-mount.html">3342</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DetailsRowNoStyles-mount_base.html">3173</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DetailsRowNoStyles-mount.html">3179</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Dialog-mount_base.html">1336</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Dialog-mount.html">1343</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DocumentCardTitle-mount_base.html">1723</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/DocumentCardTitle-mount.html">1712</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Dropdown-mount_base.html">3074</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Dropdown-mount.html">3059</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/FocusTrapZone-mount_base.html">1715</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/FocusTrapZone-mount.html">1653</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/FocusZone-mount_base.html">1673</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/FocusZone-mount.html">1661</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/IconButtonCompat-mount_base.html">1602</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/IconButtonCompat-mount.html">1645</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Label-mount_base.html">314</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Label-mount.html">313</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Layer-mount_base.html">1685</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Layer-mount.html">1636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Link-mount_base.html">426</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Link-mount.html">444</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/MakeStyles-mount_base.html">1817</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/MakeStyles-mount.html">1818</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/MenuButtonCompat-mount_base.html">1355</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/MenuButtonCompat-mount.html">1363</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/MessageBar-mount_base.html">1847</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/MessageBar-mount.html">1905</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Nav-mount_base.html">3045</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Nav-mount.html">3047</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/OverflowSet-mount_base.html">965</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/OverflowSet-mount.html">982</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Panel-mount_base.html">1302</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Panel-mount.html">1314</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Persona-mount_base.html">793</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Persona-mount.html">794</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Pivot-mount_base.html">1305</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Pivot-mount.html">1279</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/PrimaryButtonCompat-mount_base.html">1194</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/PrimaryButtonCompat-mount.html">1212</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Rating-mount_base.html">6890</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Rating-mount.html">6928</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/SearchBox-mount_base.html">1204</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/SearchBox-mount.html">1190</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Shimmer-mount_base.html">2369</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Shimmer-mount.html">2316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Slider-mount_base.html">1770</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Slider-mount.html">1737</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/SpinButton-mount_base.html">4596</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/SpinButton-mount.html">4689</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Spinner-mount_base.html">387</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Spinner-mount.html">385</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/SplitButtonCompat-mount_base.html">2914</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/SplitButtonCompat-mount.html">2916</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Stack-mount_base.html">453</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Stack-mount.html">466</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1425</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/StackWithIntrinsicChildren-mount.html">1405</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/StackWithTextChildren-mount_base.html">4123</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/StackWithTextChildren-mount.html">4146</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/SwatchColorPicker-mount_base.html">9532</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/SwatchColorPicker-mount.html">9562</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Tabs-mount_base.html">1319</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Tabs-mount.html">1290</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/TagPicker-mount_base.html">2599</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/TagPicker-mount.html">2563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/TeachingBubble-mount_base.html">10818</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/TeachingBubble-mount.html">10843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Text-mount_base.html">384</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Text-mount.html">388</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/TextField-mount_base.html">1278</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/TextField-mount.html">1263</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ThemeProvider-mount_base.html">1334</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ThemeProvider-mount.html">1308</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ThemeProvider-virtual-rerender_base.html">567</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ThemeProvider-virtual-rerender.html">564</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ThemeProviderNext-mount_base.html">2036</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/ThemeProviderNext-mount.html">2009</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Toggle-mount_base.html">737</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/Toggle-mount.html">736</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/button-mount_base.html">627</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/button-mount.html">615</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/buttonNative-mount_base.html">107</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test/buttonNative-mount.html">104</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.17](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Avatar.Fluent.html) | 0.48 | 0.35:1 | 2000 | 336
🦄 | Button.Fluent | [0.1](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Button.Fluent.html) | 0.18 | 0.56:1 | 5000 | 524
🔧 | Checkbox.Fluent | [0.61](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Checkbox.Fluent.html) | 0.33 | 1.85:1 | 1000 | 614
🎯 | Dialog.Fluent | [0.15](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Dialog.Fluent.html) | 0.2 | 0.75:1 | 5000 | 747
🔧 | Dropdown.Fluent | [2.91](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Dropdown.Fluent.html) | 0.38 | 7.66:1 | 1000 | 2911
🔧 | Icon.Fluent | [0.13](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Icon.Fluent.html) | 0.05 | 2.6:1 | 5000 | 649
🦄 | Image.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Image.Fluent.html) | 0.12 | 0.67:1 | 5000 | 391
🔧 | Slider.Fluent | [1.49](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Slider.Fluent.html) | 0.41 | 3.63:1 | 1000 | 1487
🔧 | Text.Fluent | [0.07](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.33:1 | 5000 | 344
🦄 | Tooltip.Fluent | [0.11](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Tooltip.Fluent.html) | 0.83 | 0.13:1 | 5000 | 550
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
TreeWith60ListItems.default | [179](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TreeWith60ListItems.default.html) | [162](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.1:1
AvatarMinimalPerf.default | [204](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AvatarMinimalPerf.default.html) | [187](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.09:1
RefMinimalPerf.default | [240](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/RefMinimalPerf.default.html) | [224](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.07:1
ListMinimalPerf.default | [490](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ListMinimalPerf.default.html) | [463](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.06:1
ButtonMinimalPerf.default | [173](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonMinimalPerf.default.html) | [164](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.05:1
CardMinimalPerf.default | [549](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/CardMinimalPerf.default.html) | [525](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.05:1
ChatWithPopoverPerf.default | [431](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ChatWithPopoverPerf.default.html) | [410](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.05:1
FlexMinimalPerf.default | [308](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/FlexMinimalPerf.default.html) | [294](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.05:1
TableMinimalPerf.default | [412](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TableMinimalPerf.default.html) | [391](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.05:1
Image.Fluent | [391](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Image.Fluent.html) | [372](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Image.Fluent_base.html) | 1.05:1
AccordionMinimalPerf.default | [144](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AccordionMinimalPerf.default.html) | [138](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.04:1
DividerMinimalPerf.default | [375](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DividerMinimalPerf.default.html) | [360](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.04:1
PortalMinimalPerf.default | [163](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/PortalMinimalPerf.default.html) | [156](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.04:1
SegmentMinimalPerf.default | [362](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/SegmentMinimalPerf.default.html) | [349](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.04:1
SkeletonMinimalPerf.default | [365](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/SkeletonMinimalPerf.default.html) | [351](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.04:1
TextMinimalPerf.default | [359](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TextMinimalPerf.default.html) | [346](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [494](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TextAreaMinimalPerf.default.html) | [477](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
Checkbox.Fluent | [614](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Checkbox.Fluent.html) | [593](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Checkbox.Fluent_base.html) | 1.04:1
AttachmentMinimalPerf.default | [158](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AttachmentMinimalPerf.default.html) | [154](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.03:1
FormMinimalPerf.default | [412](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/FormMinimalPerf.default.html) | [399](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.03:1
IconMinimalPerf.default | [665](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/IconMinimalPerf.default.html) | [647](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [918](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ToolbarMinimalPerf.default.html) | [890](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
VideoMinimalPerf.default | [625](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/VideoMinimalPerf.default.html) | [604](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.03:1
AttachmentSlotsPerf.default | [1163](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1144](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.02:1
BoxMinimalPerf.default | [358](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/BoxMinimalPerf.default.html) | [350](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
DropdownManyItemsPerf.default | [696](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DropdownManyItemsPerf.default.html) | [680](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.02:1
GridMinimalPerf.default | [346](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/GridMinimalPerf.default.html) | [338](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.02:1
ImageMinimalPerf.default | [380](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ImageMinimalPerf.default.html) | [372](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.02:1
InputMinimalPerf.default | [1240](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/InputMinimalPerf.default.html) | [1221](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.02:1
LayoutMinimalPerf.default | [400](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/LayoutMinimalPerf.default.html) | [392](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.02:1
MenuMinimalPerf.default | [855](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/MenuMinimalPerf.default.html) | [838](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.02:1
ReactionMinimalPerf.default | [397](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ReactionMinimalPerf.default.html) | [389](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [796](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TooltipMinimalPerf.default.html) | [783](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
Tooltip.Fluent | [550](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Tooltip.Fluent.html) | [540](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Tooltip.Fluent_base.html) | 1.02:1
AnimationMinimalPerf.default | [398](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AnimationMinimalPerf.default.html) | [395](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.01:1
ButtonSlotsPerf.default | [550](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonSlotsPerf.default.html) | [547](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.01:1
EmbedMinimalPerf.default | [4043](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/EmbedMinimalPerf.default.html) | [4011](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.01:1
HeaderSlotsPerf.default | [748](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/HeaderSlotsPerf.default.html) | [739](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [1170](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1158](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [707](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/LoaderMinimalPerf.default.html) | [698](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
StatusMinimalPerf.default | [690](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/StatusMinimalPerf.default.html) | [680](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1920](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TableManyItemsPerf.default.html) | [1908](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
CustomToolbarPrototype.default | [3523](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/CustomToolbarPrototype.default.html) | [3504](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.01:1
Avatar.Fluent | [336](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Avatar.Fluent.html) | [334](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Avatar.Fluent_base.html) | 1.01:1
Icon.Fluent | [649](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Icon.Fluent.html) | [642](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Icon.Fluent_base.html) | 1.01:1
ChatDuplicateMessagesPerf.default | [353](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [353](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [42735](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DatepickerMinimalPerf.default.html) | [42697](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
DialogMinimalPerf.default | [753](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DialogMinimalPerf.default.html) | [751](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [2914](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DropdownMinimalPerf.default.html) | [2908](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
HeaderMinimalPerf.default | [368](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/HeaderMinimalPerf.default.html) | [367](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [671](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/PopupMinimalPerf.default.html) | [669](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
RadioGroupMinimalPerf.default | [421](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [422](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3560](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3566](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
Dialog.Fluent | [747](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Dialog.Fluent.html) | [749](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Dialog.Fluent_base.html) | 1:1
Dropdown.Fluent | [2911](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Dropdown.Fluent.html) | [2897](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Dropdown.Fluent_base.html) | 1:1
Text.Fluent | [344](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Text.Fluent.html) | [345](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Text.Fluent_base.html) | 1:1
ButtonOverridesMissPerf.default | [1580](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1595](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
ButtonUseCssPerf.default | [773](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonUseCssPerf.default.html) | [777](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 0.99:1
ButtonUseCssNestingPerf.default | [1012](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1020](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [587](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ChatMinimalPerf.default.html) | [595](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [2668](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2686](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
LabelMinimalPerf.default | [409](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/LabelMinimalPerf.default.html) | [414](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.99:1
ListCommonPerf.default | [627](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ListCommonPerf.default.html) | [631](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ListCommonPerf.default_base.html) | 0.99:1
ListNestedPerf.default | [531](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ListNestedPerf.default.html) | [536](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ListNestedPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1508](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1516](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
ProviderMinimalPerf.default | [880](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ProviderMinimalPerf.default.html) | [889](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.99:1
SliderMinimalPerf.default | [1502](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/SliderMinimalPerf.default.html) | [1522](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.99:1
AlertMinimalPerf.default | [283](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AlertMinimalPerf.default.html) | [288](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.98:1
MenuButtonMinimalPerf.default | [1463](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1500](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.98:1
Slider.Fluent | [1487](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Slider.Fluent.html) | [1510](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Slider.Fluent_base.html) | 0.98:1
CarouselMinimalPerf.default | [450](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/CarouselMinimalPerf.default.html) | [466](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.97:1
Button.Fluent | [524](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Button.Fluent.html) | [539](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/Button.Fluent_base.html) | 0.97:1
ListWith60ListItems.default | [578](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ListWith60ListItems.default.html) | [606](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.95:1
TreeMinimalPerf.default | [718](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TreeMinimalPerf.default.html) | [760](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.94:1
RosterPerf.default | [1076](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/RosterPerf.default.html) | [1155](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16714/merge/perf-test-northstar/RosterPerf.default_base.html) | 0.93:1

</details><div id="perfComment9423"/>

File: packages/fluentui/react-context-selector/src/createContext.ts [hunk 1]
```diff
@@ -38,31 +42,14 @@ const createProvider = <Value>(Original: React.Provider<ContextValue<Value>>) =>
...
-          );
-        }
-
-        /* istanbul ignore next */
-        return () => () => {};
-      },
-      value: defaultValue,
+export const createContext = <Value>(defaultValue: Value): Context<Value> => {
+  const context = React.createContext<ContextValue<Value>>({
+    STRUCT: {
```
Comment (ling1726) [inline packages/fluentui/react-context-selector/src/createContext.ts:47]: why `STRUCT` ?

File: packages/fluentui/react-context-selector/src/useContextSelector.ts [hunk 2]
```diff
@@ -18,39 +12,70 @@ export const useContextSelector = <Value, SelectedValue>(
   context: Context<Value>,
   selector: ContextSelector<Value, SelectedValue>,
 ): SelectedValue => {
-  const { subscribe, value } = React.useContext((context as unknown) as Context<ContextValue<Value>>);
-  const [, forceUpdate] = React.useReducer((c: number) => c + 1, 0) as [never, () => void];
+  const contextValue = React.useContext((context as unknown) as Context<ContextValue<Value>>);
```
Comment (ling1726) [inline packages/fluentui/react-context-selector/src/useContextSelector.ts:15]: what kind of error do you get without this cast ?

File: packages/fluentui/react-context-selector/src/useContextSelector.ts [hunk 3]
```diff
@@ -18,39 +12,70 @@ export const useContextSelector = <Value, SelectedValue>(
   context: Context<Value>,
```
Comment (ling1726) [inline packages/fluentui/react-context-selector/src/useContextSelector.ts:12]: This shares quite a lot with `useContextSelectors` could we make this use the other hook and simply return a single value ? i.e.

```typescript
useContextSelector = (context, selector) => {
  const selectors = { single: selector };
  const {single}  = useContextSelectors(context, selectors)
  return single;
}
```

Comment (ling1726) [reply packages/fluentui/react-context-selector/src/useContextSelector.ts:12]: not to mention that the plural version has a lot more readable conditions like `stateHasChanged` 😄

File: packages/fluentui/react-context-selector/src/useContextSelector.ts [hunk 4]
```diff
@@ -18,39 +12,70 @@ export const useContextSelector = <Value, SelectedValue>(
...
-  useIsomorphicLayoutEffect(() => {
-    ref.current = {
-      selector,
-      value,
-      selected,
-    };
-  });
-  useIsomorphicLayoutEffect(() => {
-    const callback = (nextState: Value) => {
+  const [state, dispatch] = React.useReducer(
```
Comment (ling1726) [inline packages/fluentui/react-context-selector/src/useContextSelector.ts:26]: would this be more appropriate ? 
```suggestion
  const [state, rerender] = React.useReducer(
```

File: packages/fluentui/react-context-selector/src/useContextSelector.ts (hunk 3 above)
Comment (assuncaocharles) [reply packages/fluentui/react-context-selector/src/useContextSelector.ts:12]: I don't think that is the goal, WDYT @layershifter ?

File: packages/fluentui/react-context-selector/src/createContext.ts (hunk 1 above)
Comment (assuncaocharles) [reply packages/fluentui/react-context-selector/src/createContext.ts:47]: Why not?

File: packages/fluentui/react-context-selector/src/useContextSelector.ts (hunk 2 above)
Comment (assuncaocharles) [reply packages/fluentui/react-context-selector/src/useContextSelector.ts:15]: Conversion of type 'Context<Value>' to type 'Context<ContextValue<Value>>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

File: packages/fluentui/react-context-selector/src/useContextSelector.ts (hunk 4 above)
Comment (layershifter) [reply packages/fluentui/react-context-selector/src/useContextSelector.ts:26]: It's not `rerender` as it _will not perform_ re-render

Comment (assuncaocharles) [reply packages/fluentui/react-context-selector/src/useContextSelector.ts:26]: I think `dispatch` is fine, it's what `useReducer` return

Comment (ling1726) [reply packages/fluentui/react-context-selector/src/useContextSelector.ts:26]: oh really ? it is literally commented with `schedule a rerender`

File: packages/fluentui/react-context-selector/src/useContextSelector.ts (hunk 2 above)
Comment (assuncaocharles) [reply packages/fluentui/react-context-selector/src/useContextSelector.ts:15]: @layershifter 

If we do this change:
```typescript
export const useContextSelector = <Value, SelectedValue>(
  context: Context<ContextValue<Value>>,
```

We don't need this cast, WDYT?

File: packages/fluentui/CHANGELOG.md [hunk 5]
```diff
@@ -41,6 +41,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - Fix `Embed` playback control visuals. @TanelVari ([#16611](https://github.com/microsoft/fluentui/pull/16611))
 - Fixes for `Dropdown`. Fix clear indicator visual styles (focus border, using `CloseIcon`). Fix empty search result text style. Fix left/right padding for multiple selection labels. Using `ChevronDownIcon` for toggle indicator. @TanelVari ([#16522](https://github.com/microsoft/fluentui/pull/16522))
 - Fix docsite header colors for all themes. `ExampleSnippet` now honors theme colors for background and foreground. @TanelVari ([#16643](https://github.com/microsoft/fluentui/pull/16643))
+- Refactor `react-context-selector` to run update with prioriy and removed strict option. @assuncaocharles ([#16714](https://github.com/microsoft/fluentui/pull/16714))
```
Comment (layershifter) [inline packages/fluentui/CHANGELOG.md:44]:
```suggestion
- Refactor `react-context-selector` to avoid React warnings @assuncaocharles ([#16714](https://github.com/microsoft/fluentui/pull/16714))
```

File: packages/fluentui/react-context-selector/src/types.ts [hunk 6]
```diff
@@ -5,15 +5,22 @@ export type Context<Value> = React.Context<Value> & {
...
-export type ContextListener<Value> = (value: Value) => void;
-
 export type ContextSelector<Value, SelectedValue> = (value: Value) => SelectedValue;
 
+export type ContextVersion = number;
+
 export type ContextValue<Value> = {
-  subscribe: (listener: ContextListener<Value>) => any;
-  value: Value;
+  /** List of listners to publish changes */
```
Comment (layershifter) [inline packages/fluentui/react-context-selector/src/types.ts:13]:
```suggestion
  /** Holds a set of subscribers from components. */
```

?

File: packages/fluentui/react-context-selector/src/types.ts [hunk 7]
```diff
@@ -5,15 +5,22 @@ export type Context<Value> = React.Context<Value> & {
...
+  listeners: ((payload: readonly [ContextVersion, Value]) => void)[];
+
+  /** Current state value */
```
Comment (layershifter) [inline packages/fluentui/react-context-selector/src/types.ts:16]:
```suggestion
  /** Holds an actual value of React's context that will be propagated down for computations. */
```

File: packages/fluentui/react-context-selector/package.json [hunk 8]
```diff
@@ -5,13 +5,15 @@
   "author": "Oleksandr Fediashov <a@fedyashov.com>",
   "bugs": "https://github.com/microsoft/fluentui/issues",
   "dependencies": {
-    "@babel/runtime": "^7.10.4"
+    "@babel/runtime": "^7.10.4",
+    "scheduler": "^0.20.1"
```
[the remark this answers is not in the document]
Comment (assuncaocharles) [reply packages/fluentui/react-context-selector/package.json:9]: Done

File: packages/fluentui/react-context-selector/src/types.ts [hunk 9]
```diff
@@ -5,15 +5,22 @@ export type Context<Value> = React.Context<Value> & {
...
+  value: React.MutableRefObject<Value>;
+
+  /** Version to compare if it should run dispatch ( publish ) */
```
Comment (layershifter) [inline packages/fluentui/react-context-selector/src/types.ts:19]:
```suggestion
  /** A version field is used to sync a context value and consumers. */
```

File: packages/fluentui/react-context-selector/src/createContext.ts [hunk 10]
```diff
@@ -1,33 +1,35 @@
...
-    const subscribe = React.useCallback((listener: ContextListener<Value>) => {
-      listeners.current.push(listener);
-
-      const unsubscribe = () => {
-        const index = listeners.current.indexOf(listener);
-        listeners.current.splice(index, 1);
+    // TODO: write better descriptions
+    const valueRef = React.useRef(props.value); // value from props.value
+    const versionRef = React.useRef(0); // render/effect counter
+    const contextValue = React.useRef<ContextValue<Value>>(); // stable object to avoid context updates
```
Comment (layershifter) [inline packages/fluentui/react-context-selector/src/createContext.ts:11]:
```suggestion
    // Holds an actual "props.value"
    const valueRef = React.useRef(props.value);
    // Used to sync context updates and avoid stale values, can be considered as render/effect counter of Provider.
    const versionRef = React.useRef(0);
    
    // A stable object, is used to avoid context updates via mutation of its values.
    const contextValue = React.useRef<ContextValue<Value>>();
```

File: packages/fluentui/react-context-selector/src/useContextSelector.ts (hunk 3 above)
Comment (layershifter) [reply packages/fluentui/react-context-selector/src/useContextSelector.ts:12]: Let's keep these things separate now...

File: packages/fluentui/react-context-selector/src/useContextSelector.ts [hunk 11]
```diff
@@ -18,39 +12,68 @@ export const useContextSelector = <Value, SelectedValue>(
...
+    (
+      prevState: readonly [Value /* contextValue */, SelectedValue /* selector(value) */],
+      payload:
+        | undefined // undefined from render below
+        | readonly [ContextVersion, Value], // from provider effect
+    ) => {
+      if (!payload) {
```
Comment (layershifter) [inline packages/fluentui/react-context-selector/src/useContextSelector.ts:31]:
```suggestion
      if (!payload) { // early bail out when is dispatched during render
```

File: packages/fluentui/react-context-selector/package.json [hunk 12]
```diff
@@ -9,16 +9,19 @@
...
     "lerna-alias": "^3.0.3-0",
     "react": "16.8.6",
     "react-is": "^16.6.3",
+    "scheduler": "^0.20.1",
     "typescript": "3.7.2"
   },
   "peerDependencies": {
-    "react": "^16.8.0"
+    "react": "^16.8.0",
+    "scheduler": "^0.20.1"
```
Comment (layershifter) [inline packages/fluentui/react-context-selector/package.json:24]:
```suggestion
    "scheduler": ">=0.19.0"
```

Comment (layershifter) [reply packages/fluentui/react-context-selector/package.json:24]: Please also run `yarn` to regenerate `yarn.lock`

**Review by layershifter — APPROVED** [review]

**Review by ecraig12345 — APPROVED** [review]
