### PR TITLE
fix: Update `useId` to work correctly in React 18 and React 18 strictmode

### LINKED ISSUE #23620: [Bug]: v9's Provider doesn’t hydrate from SSR properly in StrictMode
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 4.38 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
    Safari: 15.5

My project uses PNPM so envinfo might have missed: @fluentui/react-components v9.0.0-rc.14
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/OfficeDev/fluent-blocks/tree/feat/sample-app

## Actual Behavior

The Provider won’t apply styles in certain situations when it’s been rehydrated. Sometimes when hot reloading certain styles aren’t applied, and certain styles are always missing from tooltips and menus which v9 renders in a sibling provider with a different-numbered class name from the primary provider (e.g. the primary will have `fui-FluentProvider1`, but tooltip & menu providers will have `fui-FluentProvider2`).

pr

This could possibly be construed as an accessibility bug since it causes tooltips & menus to blur and unmount right after mounting.

## Expected Behavior

In Storybook and other SPA situations the Provider behaves as expected – it seems aware that other providers have been rendered, and when new tooltips or menus appear they appear in a provider element with the same `n` in their class name as their relevant provider sibling, e.g. `57` in `fui-FluentProvider57`.

## Steps to reproduce

I'm working on getting a truly minimal reproduction running on Vercel (this can’t be reproduced on CodeSandbox since it’s an SSR issue) but wanted to log this in case I missed something and this is easily resolved.

### Logs

```shell
> @fluent-blocks/react-sample-app@0.1.0 dev /Users/willshown/Projects/fluent-blocks/packages/react-sample-app
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
event - compiled client and server successfully in 5.7s (2167 modules)
wait  - compiling / (client and server)...
wait  - compiling...
event - compiled client and server successfully in 1479 ms (2174 modules)
```

### Requested priority

High

### Products/sites affected

Fluent Blocks, Teams Developer Portal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by sopranopillow**
## Previous Behavior

We generate our own ids and use a context to keep track of server vs client id generation.

## New Behavior

We still have the previous behavior, but we now check if `React.useId` is available (React 18+) and use it when available. This will help fix issues with React 18+ when using SSR and/or strictmode. This is due to `React.useId` being aware of strictmode and SSR.

> **Note**: React's `useId` hook uses `:` for its generated id, this is a problem for us since we use ids as class names when loading up our theme css vars. To fix this issue, we have to add a backslash to the className when inserting it into the style tag turning `:` to `\:`.

## Related Issue(s)

* Fixes #23620

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                 Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `85.912 kB`<br />`21.686 kB` |   `85.956 kB`<br />`21.71 kB` | `44 B` <br />`24 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `52.812 kB`<br />`14.689 kB` |  `52.856 kB`<br />`14.713 kB` | `44 B` <br />`24 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                                  |   `69.03 kB`<br />`18.984 kB` |   `69.074 kB`<br />`19.01 kB` | `44 B` <br />`26 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `45.488 kB`<br />`11.501 kB` |  `45.532 kB`<br />`11.532 kB` | `44 B` <br />`31 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `77.975 kB`<br />`22.496 kB` |  `78.019 kB`<br />`22.528 kB` | `44 B` <br />`32 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |   `10.805 kB`<br />`4.443 kB` |   `10.849 kB`<br />`4.475 kB` | `44 B` <br />`32 B`  |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr>                                                                              |  `32.658 kB`<br />`10.169 kB` |  `32.702 kB`<br />`10.201 kB` | `44 B` <br />`32 B`  |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/CheckboxField.fixture.js'>CheckboxField</abbr>                                                                    |  `39.456 kB`<br />`11.993 kB` |    `39.5 kB`<br />`12.025 kB` | `44 B` <br />`32 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                                                 |  `80.935 kB`<br />`25.855 kB` |  `80.979 kB`<br />`25.878 kB` | `44 B` <br />`23 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/ComboboxField.fixture.js'>ComboboxField</abbr>                                                                    |  `78.821 kB`<br />`25.999 kB` |  `78.865 kB`<br />`26.023 kB` | `44 B` <br />`24 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>                                                 |  `79.721 kB`<br />`25.651 kB` |  `79.765 kB`<br />`25.668 kB` | `44 B` <br />`17 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `59.888 kB`<br />`16.652 kB` |  `59.932 kB`<br />`16.682 kB` | `44 B` <br />`30 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `187.586 kB`<br />`52.65 kB` |  `187.63 kB`<br />`52.674 kB` | `44 B` <br />`24 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `34.379 kB`<br />`11.322 kB` |  `34.423 kB`<br />`11.352 kB` | `44 B` <br />`30 B`  |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |  `83.464 kB`<br />`24.916 kB` |  `83.508 kB`<br />`24.945 kB` | `44 B` <br />`29 B`  |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `16.938 kB`<br />`6.103 kB` |   `16.982 kB`<br />`6.132 kB` | `44 B` <br />`29 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        | `118.469 kB`<br />`36.003 kB` | `118.513 kB`<br />`36.028 kB` | `44 B` <br />`25 B`  |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/InputField.fixture.js'>InputField</abbr>                                                                             |   `34.606 kB`<br />`10.91 kB` |   `34.65 kB`<br />`10.939 kB` | `44 B` <br />`29 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `118.035 kB`<br />`36.483 kB` |  `118.079 kB`<br />`36.51 kB` | `44 B` <br />`27 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `121.104 kB`<br />`36.991 kB` | `121.148 kB`<br />`37.019 kB` | `44 B` <br />`28 B`  |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                                                               |   `11.033 kB`<br />`4.198 kB` |   `11.077 kB`<br />`4.224 kB` | `44 B` <br />`26 B`  |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                                                                 |  `58.849 kB`<br />`16.348 kB` |  `58.893 kB`<br />`16.373 kB` | `44 B` <br />`25 B`  |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `105.587 kB`<br />`32.519 kB` | `105.631 kB`<br />`32.546 kB` | `44 B` <br />`27 B`  |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressField.fixture.js'>ProgressField</abbr>                                                                    |   `23.595 kB`<br />`8.242 kB` |   `23.639 kB`<br />`8.269 kB` | `44 B` <br />`27 B`  |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `16.446 kB`<br />`6.127 kB` |    `16.49 kB`<br />`6.156 kB` | `44 B` <br />`29 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `32.247 kB`<br />`10.468 kB` |  `32.291 kB`<br />`10.497 kB` | `44 B` <br />`29 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |   `14.718 kB`<br />`5.886 kB` |   `14.762 kB`<br />`5.915 kB` | `44 B` <br />`29 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroupField.fixture.js'>RadioGroupField</abbr>                                                                   |   `24.731 kB`<br />`8.947 kB` |   `24.775 kB`<br />`8.976 kB` | `44 B` <br />`29 B`  |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/SelectField.fixture.js'>SelectField</abbr>                                                                          |  `32.933 kB`<br />`10.601 kB` |   `32.977 kB`<br />`10.63 kB` | `44 B` <br />`29 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |  `32.663 kB`<br />`10.403 kB` |  `32.707 kB`<br />`10.434 kB` | `44 B` <br />`31 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/SliderField.fixture.js'>SliderField</abbr>                                                                          |  `42.398 kB`<br />`13.259 kB` |  `42.442 kB`<br />`13.287 kB` | `44 B` <br />`28 B`  |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButtonField.fixture.js'>SpinButtonField</abbr>                                                              |  `53.982 kB`<br />`15.414 kB` |  `54.026 kB`<br />`15.442 kB` | `44 B` <br />`28 B`  |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `20.445 kB`<br />`6.621 kB` |    `20.489 kB`<br />`6.65 kB` | `44 B` <br />`29 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `27.791 kB`<br />`8.605 kB` |   `27.835 kB`<br />`8.637 kB` | `44 B` <br />`32 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/SwitchField.fixture.js'>SwitchField</abbr>                                                                          |  `34.482 kB`<br />`10.425 kB` |  `34.526 kB`<br />`10.455 kB` | `44 B` <br />`30 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                                                                                 | `129.317 kB`<br />`35.207 kB` | `129.361 kB`<br />`35.239 kB` | `44 B` <br />`32 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>                                                                 | `127.563 kB`<br />`32.864 kB` |  `127.608 kB`<br />`32.89 kB` | `45 B` <br />`26 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr>                                                         |      `81 kB`<br />`20.124 kB` |  `81.044 kB`<br />`20.155 kB` | `44 B` <br />`31 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>                                                                   |   `80.429 kB`<br />`19.97 kB` |  `80.473 kB`<br />`20.001 kB` | `44 B` <br />`31 B`  |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/TextareaField.fixture.js'>TextareaField</abbr>                                                                    |  `36.089 kB`<br />`11.313 kB` |  `36.133 kB`<br />`11.343 kB` | `44 B` <br />`30 B`  |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `43.537 kB`<br />`15.226 kB` |  `43.581 kB`<br />`15.247 kB` | `44 B` <br />`21 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                   |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContext.fixture.js'>createContext</abbr>                          |         `533 B`<br />`341 B` |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContextSelector.fixture.js'>createContextSelector</abbr>          |         `554 B`<br />`348 B` |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr> | `80.097 kB`<br />`24.712 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                |   `15.42 kB`<br />`6.167 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                             |   `23.78 kB`<br />`7.542 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                               |   `24.67 kB`<br />`7.825 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                             |  `25.728 kB`<br />`7.439 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                          |  `33.354 kB`<br />`8.779 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                          | `40.384 kB`<br />`10.127 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                  | `38.043 kB`<br />`10.096 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                              | `49.184 kB`<br />`10.875 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                |  `72.92 kB`<br />`21.108 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                    |    `9.04 kB`<br />`3.807 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                  |   `9.847 kB`<br />`4.159 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                             |  `11.259 kB`<br />`4.473 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                             |  `24.673 kB`<br />`8.065 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                             |   `9.817 kB`<br />`4.067 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                               |  `12.285 kB`<br />`5.063 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                          |   `11.13 kB`<br />`4.103 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>               |   `6.069 kB`<br />`2.053 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePositioning</abbr>                          |  `20.856 kB`<br />`7.766 kB` |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressBar.fixture.js'>ProgressBar</abbr>                              |  `13.573 kB`<br />`5.232 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                          |  `23.963 kB`<br />`8.206 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                              | `44.989 kB`<br />`12.975 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>                  | `42.971 kB`<br />`11.781 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                              |  `12.261 kB`<br />`4.819 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                            |   `15.571 kB`<br />`5.23 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                    |  `26.156 kB`<br />`8.508 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                             |         `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2331c9314cd1440ab413e404bdf1da8da0de7e05'>2331c9314cd1440ab413e404bdf1da8da0de7e05</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/Avatar-mount_base.html">1506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/Avatar-mount.html">1550</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/Button-mount_base.html">1117</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/Button-mount.html">1109</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/FluentProvider-mount_base.html">1932</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/FluentProvider-mount.html">1899</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/FluentProviderWithTheme-mount_base.html">723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/FluentProviderWithTheme-mount.html">752</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">722</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">724</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">743</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">735</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/InfoButton-mount_base.html">673</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/InfoButton-mount.html">671</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/MakeStyles-mount_base.html">2338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/MakeStyles-mount.html">2260</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/Persona-mount_base.html">3521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/Persona-mount.html">3566</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/SpinButton-mount_base.html">3090</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26465/perf-test-react-components/SpinButton-mount.html">3053</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

File: packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ export const useFluentProviderThemeStyleTag = (options: Pick<FluentProviderState
       : '';
   }, [theme]);
 
-  const rule = `.${styleTagId} { ${cssVarsAsString} }`;
+  const rule = `.${styleTagId.replace(/:/g, '\\:')} { ${cssVarsAsString} }`;
```
Comment (ling1726) [inline packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts:65]: The  original `styleTagId` is going to be different than what's in the rule?

Comment (ling1726) [reply packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts:65]: OK TIL https://twitter.com/simonw/status/1060672343188549633?lang=en

Comment (layershifter) [inline packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts:65]: > Note: React's useId hook uses : for its generated id, this is a problem for us since we use ids as class names when loading up our theme css vars. To fix this issue, we have to replace : with another string, in this case --.

This does not match PR's description :) Can you please update the description and a small comment there? 🙏

File: packages/react-components/react-utilities/src/hooks/useId.ts [hunk 2]
```diff
@@ -19,11 +19,20 @@ export function resetIdsForTests(): void {
 export function useId(prefix: string = 'fui-', providedId?: string): string {
   const contextValue = useSSRContext();
 
-  return React.useMemo(() => {
-    if (providedId) {
-      return providedId;
-    }
+  // Checking if useId is available on React, if it is, we use it to generate the id. String concatenation is used to
+  // prevent bundlers from complaining with older versions of React.
+  const _useId: () => string = (React as never)['use' + 'Id'];
```
Comment (layershifter) [inline packages/react-components/react-utilities/src/hooks/useId.ts:24]:
```suggestion
  const _useId: (() => string) | undefined = (React as never)['use' + 'Id'];
```

nit: Let's make types more accurate

File: packages/react-components/react-utilities/src/hooks/useId.ts [hunk 3]
```diff
@@ -19,11 +19,20 @@ export function resetIdsForTests(): void {
...
+  return _useId
+    ? providedId || `${prefix}${_useId()}`
+    : // eslint-disable-next-line react-hooks/rules-of-hooks
+      React.useMemo(() => {
+        if (providedId) {
+          return providedId;
+        }
+
+        return `${prefix}${++contextValue.current}`;
+      }, [prefix, providedId, contextValue]);
```
Comment (layershifter) [inline packages/react-components/react-utilities/src/hooks/useId.ts:37]:
```js
if (_useId) {
  return providedId || `${prefix}${_useId()}`
}

return React.useMemo(() => {
 if (providedId) {
   return providedId;
 }

 return `${prefix}${++contextValue.current}`;
}, [prefix, providedId, contextValue]);
```

nit: Let's write a normal `if` condition there :)

**Review by layershifter — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]
