### PR TITLE
fix: replace deprecated element.ref usages to support react 19

### LINKED ISSUE #31534: [Bug]: React 19, Accessing element.ref is no longer supported
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

## Actual Behavior

Accessing `element.ref` is deprecated: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#deprecated-element-ref

We have various places where we work with elements directly and access refs:

https://github.com/microsoft/fluentui/blob/fc5f6f5a47d1992c1fe44b6b0aab8965a1dc8230/packages/react-components/react-toast/src/components/ToastTrigger/useToastTrigger.ts#L33
https://github.com/microsoft/fluentui/blob/fc5f6f5a47d1992c1fe44b6b0aab8965a1dc8230/packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx#L263
https://github.com/microsoft/fluentui/blob/fc5f6f5a47d1992c1fe44b6b0aab8965a1dc8230/packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts#L39

We should check all locations and:
- modify `getTriggerChild` to return a ref i.e. `const [child, childRef] = getTriggerChild()`
- or add a separate helper

A compat helper will decide what accessor to use, a naive example:

```
function getElementRef(element: any) {
  return (React as any)
    // React 19 has new internals
    .__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE
    ? element.props.ref
    : element.ref;
}
```

POC https://stackblitz.com/edit/vitejs-vite-5nghj2?file=package.json,src%2FApp.tsx&terminal=dev

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by dmytrokirpa**
## Previous Behavior

Accessing `element.ref` is deprecated: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#deprecated-element-ref

We have various places where we work with elements directly and access refs:

https://github.com/microsoft/fluentui/blob/fc5f6f5a47d1992c1fe44b6b0aab8965a1dc8230/packages/react-components/react-toast/src/components/ToastTrigger/useToastTrigger.ts#L33
https://github.com/microsoft/fluentui/blob/fc5f6f5a47d1992c1fe44b6b0aab8965a1dc8230/packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx#L263
https://github.com/microsoft/fluentui/blob/fc5f6f5a47d1992c1fe44b6b0aab8965a1dc8230/packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts#L39
etc

## New Behavior

- added a new helper `getReactElementRef` that returns element's ref in a backward compatible way
- replaced usages of `element?.ref` with `getReactElementRef(element)`

## Related Issue(s)

- Fixes #31534

### CODE REVIEW

File: packages/react-components/react-utilities/src/utils/getReactElementRef.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import * as React from 'react';
+
+const IS_REACT_19 = React.version.startsWith('19.');
```
Comment (layershifter) [inline packages/react-components/react-utilities/src/utils/getReactElementRef.ts]: Probably should be

```suggestion
const IS_REACT_19_OR_HIGHER= parseInt(React.version.slice(0, 2), 10) >= 19;
```

**Review by layershifter — APPROVED** [review]

File: packages/react-components/react-utilities/src/utils/getReactElementRef.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
+import * as React from 'react';
+
+const IS_REACT_19_OR_HIGHER = parseInt(React.version, 10) > 19;
```
Comment (layershifter) [inline packages/react-components/react-utilities/src/utils/getReactElementRef.ts]:
```suggestion
const IS_REACT_19_OR_HIGHER = parseInt(React.version, 10) >= 19;
```

?

**Review by mainframev — APPROVED** [review]
