### PR TITLE
fix(CI): include type-check in lage config to have all packages type checked again

### LINKED ISSUE #25245: Package type-check commands are not being executed in PR and CI pipelines
## Issue:
- PR and CI pipeline checks are not executing the `type-check` command of each affected package in the tree.

Last time it executed correctly in CI: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=268563&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=8250ef03-1890-59ab-a6a8-5d0b4c2baa1b

### PR DESCRIPTION
**Pull request by TristanWatanabe**
## Current Behavior

- Right now, whenever `lage type-check` is ran, only the `react-18-tests-v8` package's `type-check` executes so other packages are not getting proper type checking in local builds or CI. It seems we need to explicitly declare a `type-check` for all packages in the `lage.config` before having one scoped to just a single package to ensure proper type-checking for all packages.

## New Behavior

- Re-enables type-check of packages in the repo
- Fixes type-check errors that were introduced to master

## Related Issue(s)

Fixes #25245

### CODE REVIEW

File: apps/stress-test/src/shared/react/TestMount.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ const debouncedOnRender: DebouncedOnRender = () => {
           end: performance.now(),
         });
       });
-    }, 250);
+    }, 250) as unknown) as number;
```
Comment (TristanWatanabe) [inline apps/stress-test/src/shared/react/TestMount.tsx:30]: Fixes this error:
image

File: package.json [hunk 2]
```diff
@@ -151,6 +151,7 @@
     "@types/lerna__project": "5.1.0",
     "@types/loader-utils": "2.0.3",
     "@types/markdown-table": "2.0.0",
+    "@types/micromatch": "4.0.2",
```
Comment (TristanWatanabe) [inline package.json:154]: Added to fix this error in scripts:

image

File: packages/react-components/react-overflow/src/useOverflowContainer.test.ts [hunk 3]
```diff
@@ -8,10 +8,12 @@ jest.mock('@fluentui/priority-overflow');
 const mockOverflowManager = (options: Partial<OverflowManager> = {}) => {
   const defaultMock: OverflowManager = {
     addItem: jest.fn(),
+    addOverflowMenu: jest.fn(),
     disconnect: jest.fn(),
     forceUpdate: jest.fn(),
     observe: jest.fn(),
     removeItem: jest.fn(),
+    removeOverflowMenu: jest.fn(),
```
Comment (TristanWatanabe) [inline packages/react-components/react-overflow/src/useOverflowContainer.test.ts:16]: fixes error below:
image

File: scripts/tasks/storybook.ts [hunk 4]
```diff
@@ -4,7 +4,7 @@ import * as path from 'path';
 import { findGitRoot } from '../monorepo';
 
 // TODO: this should be replaced with `'@storybook/core-server';` API
-// @ts-expect-error - standalone.js is basically private API/thus doesn't ship types. NOTE: Storybook can be run standalone from Node, although it should be noted this isn't officially supported any more. - https://github.com/storybookjs/storybook/blob/master/lib/core/docs/standalone.md#standalone-mode
+// @ts-ignore- standalone.js is basically private API/thus doesn't ship types. NOTE: Storybook can be run standalone from Node, although it should be noted this isn't officially supported any more. - https://github.com/storybookjs/storybook/blob/master/lib/core/docs/standalone.md#standalone-mode
```
Comment (TristanWatanabe) [inline scripts/tasks/storybook.ts:7]: Was throwing this error:

image

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                   |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContext.fixture.js'>createContext</abbr>                          |          `533 B`<br />`341 B` |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContextSelector.fixture.js'>createContextSelector</abbr>          |          `554 B`<br />`348 B` |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr>            |    `3.153 kB`<br />`1.299 kB` |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr> |  `79.083 kB`<br />`24.079 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                          |  `48.874 kB`<br />`13.864 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                |   `14.996 kB`<br />`6.013 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                        |  `68.842 kB`<br />`19.205 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                             |   `22.646 kB`<br />`7.228 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                               |   `23.536 kB`<br />`7.512 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                             |    `24.096 kB`<br />`7.09 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                          |   `36.736 kB`<br />`9.845 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                          |  `43.761 kB`<br />`11.061 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                  |   `39.43 kB`<br />`10.745 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                |  `46.876 kB`<br />`12.129 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                              |  `52.603 kB`<br />`11.317 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                      |  `67.216 kB`<br />`19.304 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                |   `62.898 kB`<br />`18.22 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                    |    `8.607 kB`<br />`3.622 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                    |     `9.65 kB`<br />`3.962 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                  |    `8.708 kB`<br />`3.678 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>       |  `75.141 kB`<br />`24.428 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>       |  `74.869 kB`<br />`24.385 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>          |  `82.626 kB`<br />`24.504 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                       |   `16.505 kB`<br />`5.925 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                             |   `10.826 kB`<br />`4.286 kB` |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                              |    `7.742 kB`<br />`3.265 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                             |   `23.808 kB`<br />`7.729 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                             |    `9.384 kB`<br />`3.883 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                               |   `11.852 kB`<br />`4.888 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                | `116.668 kB`<br />`35.792 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>   | `119.737 kB`<br />`36.316 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                     |   `11.004 kB`<br />`4.188 kB` |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                       |   `53.992 kB`<br />`15.25 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                       | `102.864 kB`<br />`31.542 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                          |   `10.628 kB`<br />`3.899 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePositioning</abbr>                          |   `19.724 kB`<br />`7.415 kB` |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/Progress.fixture.js'>Progress</abbr>                                    |    `11.66 kB`<br />`4.619 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                        |   `15.807 kB`<br />`5.909 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                             |  `36.436 kB`<br />`12.126 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                   |   `14.294 kB`<br />`5.723 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                          |   `20.892 kB`<br />`7.367 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                          |  `31.805 kB`<br />`10.085 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                              |  `44.228 kB`<br />`12.454 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                       |   `20.023 kB`<br />`6.461 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                          |  `33.388 kB`<br />`10.578 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                              |   `11.828 kB`<br />`4.627 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                            |   `15.138 kB`<br />`5.064 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                    |   `25.064 kB`<br />`8.158 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>              |            `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                        |    `29.65 kB`<br />`6.444 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                      |   `17.486 kB`<br />`5.057 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                       |  `41.718 kB`<br />`14.687 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                             |          `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4f7430e2fa321b96ce6022882a42aa897fcf67c9'>4f7430e2fa321b96ce6022882a42aa897fcf67c9</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/Avatar-mount_base.html">1284</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/Avatar-mount.html">1289</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/Button-mount_base.html">934</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/Button-mount.html">919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/FluentProvider-mount_base.html">1524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/FluentProvider-mount.html">1460</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/FluentProviderWithTheme-mount_base.html">570</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/FluentProviderWithTheme-mount.html">572</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">548</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">554</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">583</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/MakeStyles-mount_base.html">1969</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/MakeStyles-mount.html">1989</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/SpinButton-mount_base.html">2346</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-react-components/SpinButton-mount.html">2334</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
RefMinimalPerf.default | [214](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/RefMinimalPerf.default.html) | [199](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.08:1
ImageMinimalPerf.default | [393](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ImageMinimalPerf.default.html) | [366](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.07:1
PopupMinimalPerf.default | [643](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/PopupMinimalPerf.default.html) | [609](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.06:1
AnimationMinimalPerf.default | [538](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AnimationMinimalPerf.default.html) | [514](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.05:1
MenuMinimalPerf.default | [862](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/MenuMinimalPerf.default.html) | [824](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.05:1
MenuButtonMinimalPerf.default | [1744](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1664](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.05:1
RosterPerf.default | [2185](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/RosterPerf.default.html) | [2072](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/RosterPerf.default_base.html) | 1.05:1
RadioGroupMinimalPerf.default | [450](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [430](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.05:1
TextAreaMinimalPerf.default | [470](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TextAreaMinimalPerf.default.html) | [449](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.05:1
ChatDuplicateMessagesPerf.default | [279](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [268](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.04:1
FlexMinimalPerf.default | [283](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/FlexMinimalPerf.default.html) | [271](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.04:1
ListCommonPerf.default | [650](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ListCommonPerf.default.html) | [625](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ListCommonPerf.default_base.html) | 1.04:1
ProviderMinimalPerf.default | [412](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ProviderMinimalPerf.default.html) | [395](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.04:1
HeaderSlotsPerf.default | [766](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/HeaderSlotsPerf.default.html) | [744](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.03:1
PortalMinimalPerf.default | [165](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/PortalMinimalPerf.default.html) | [160](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.03:1
AttachmentMinimalPerf.default | [149](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AttachmentMinimalPerf.default.html) | [146](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.02:1
ButtonMinimalPerf.default | [161](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ButtonMinimalPerf.default.html) | [158](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1296](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1274](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [452](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/CarouselMinimalPerf.default.html) | [442](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
ChatWithPopoverPerf.default | [375](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ChatWithPopoverPerf.default.html) | [367](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.02:1
CheckboxMinimalPerf.default | [2110](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2075](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.02:1
LabelMinimalPerf.default | [378](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/LabelMinimalPerf.default.html) | [372](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.02:1
SkeletonMinimalPerf.default | [334](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/SkeletonMinimalPerf.default.html) | [327](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [1860](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TableManyItemsPerf.default.html) | [1819](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
ToolbarMinimalPerf.default | [924](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ToolbarMinimalPerf.default.html) | [904](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [2350](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TooltipMinimalPerf.default.html) | [2294](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
ChatMinimalPerf.default | [727](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ChatMinimalPerf.default.html) | [717](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5811](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5775](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
GridMinimalPerf.default | [325](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/GridMinimalPerf.default.html) | [322](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.01:1
LayoutMinimalPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/LayoutMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.01:1
ReactionMinimalPerf.default | [359](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ReactionMinimalPerf.default.html) | [354](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.01:1
SegmentMinimalPerf.default | [338](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/SegmentMinimalPerf.default.html) | [334](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.01:1
SliderMinimalPerf.default | [1580](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/SliderMinimalPerf.default.html) | [1568](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [671](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DropdownManyItemsPerf.default.html) | [670](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [3707](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/EmbedMinimalPerf.default.html) | [3721](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [4306](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4327](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [660](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/StatusMinimalPerf.default.html) | [663](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [2673](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/CustomToolbarPrototype.default.html) | [2665](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
TreeWith60ListItems.default | [153](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TreeWith60ListItems.default.html) | [153](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1:1
AccordionMinimalPerf.default | [145](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AccordionMinimalPerf.default.html) | [146](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.99:1
AlertMinimalPerf.default | [266](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AlertMinimalPerf.default.html) | [270](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.99:1
AttachmentSlotsPerf.default | [1109](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1124](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.99:1
AvatarMinimalPerf.default | [175](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AvatarMinimalPerf.default.html) | [176](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.99:1
BoxMinimalPerf.default | [331](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/BoxMinimalPerf.default.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/BoxMinimalPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [2649](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DropdownMinimalPerf.default.html) | [2678](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
FormMinimalPerf.default | [370](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/FormMinimalPerf.default.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.99:1
ListNestedPerf.default | [542](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ListNestedPerf.default.html) | [550](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ListNestedPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1253](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1262](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
CardMinimalPerf.default | [547](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/CardMinimalPerf.default.html) | [557](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.98:1
HeaderMinimalPerf.default | [345](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/HeaderMinimalPerf.default.html) | [351](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.98:1
IconMinimalPerf.default | [638](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/IconMinimalPerf.default.html) | [649](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.98:1
TreeMinimalPerf.default | [796](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TreeMinimalPerf.default.html) | [816](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.98:1
ButtonSlotsPerf.default | [528](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ButtonSlotsPerf.default.html) | [542](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.97:1
DialogMinimalPerf.default | [763](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DialogMinimalPerf.default.html) | [784](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.97:1
InputMinimalPerf.default | [1105](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/InputMinimalPerf.default.html) | [1137](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.97:1
ItemLayoutMinimalPerf.default | [1130](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1170](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.97:1
ListMinimalPerf.default | [497](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ListMinimalPerf.default.html) | [512](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.97:1
ListWith60ListItems.default | [601](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ListWith60ListItems.default.html) | [618](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.97:1
LoaderMinimalPerf.default | [660](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/LoaderMinimalPerf.default.html) | [679](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.97:1
VideoMinimalPerf.default | [719](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/VideoMinimalPerf.default.html) | [738](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.97:1
DividerMinimalPerf.default | [341](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DividerMinimalPerf.default.html) | [354](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.96:1
TableMinimalPerf.default | [388](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TableMinimalPerf.default.html) | [406](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.96:1
TextMinimalPerf.default | [339](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TextMinimalPerf.default.html) | [355](https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.95:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/BaseButton-mount_base.html">1439</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/BaseButton-mount.html">1402</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Breadcrumb-mount_base.html">3437</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Breadcrumb-mount.html">3501</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Checkbox-mount_base.html">3120</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Checkbox-mount.html">3223</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/CheckboxBase-mount_base.html">2802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/CheckboxBase-mount.html">2796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ChoiceGroup-mount_base.html">5258</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ChoiceGroup-mount.html">5257</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ComboBox-mount_base.html">1483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ComboBox-mount.html">1496</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/CommandBar-mount_base.html">11309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/CommandBar-mount.html">11335</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ContextualMenu-mount_base.html">12816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ContextualMenu-mount.html">12912</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DefaultButton-mount_base.html">1671</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DefaultButton-mount.html">1640</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DetailsRow-mount_base.html">4319</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DetailsRow-mount.html">4337</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DetailsRowFast-mount_base.html">4276</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DetailsRowFast-mount.html">4219</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DetailsRowNoStyles-mount_base.html">4086</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DetailsRowNoStyles-mount.html">4156</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Dialog-mount_base.html">3642</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Dialog-mount.html">3694</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DocumentCardTitle-mount_base.html">684</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/DocumentCardTitle-mount.html">707</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Dropdown-mount_base.html">3815</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Dropdown-mount.html">3809</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/FocusTrapZone-mount_base.html">2383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/FocusTrapZone-mount.html">2381</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/FocusZone-mount_base.html">2402</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/FocusZone-mount.html">2288</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedList-mount_base.html">62351</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedList-mount.html">69673</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedList-virtual-rerender_base.html">29522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedList-virtual-rerender.html">28927</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">108989</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedList-virtual-rerender-with-unmount.html">107133</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedListV2-mount_base.html">669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedListV2-mount.html">674</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedListV2-virtual-rerender_base.html">647</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedListV2-virtual-rerender.html">658</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">680</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">656</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/IconButton-mount_base.html">2295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/IconButton-mount.html">2249</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Label-mount_base.html">873</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Label-mount.html">867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Layer-mount_base.html">5006</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Layer-mount.html">4988</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Link-mount_base.html">982</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Link-mount.html">1001</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/MenuButton-mount_base.html">1945</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/MenuButton-mount.html">1961</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/MessageBar-mount_base.html">2804</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/MessageBar-mount.html">2771</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Nav-mount_base.html">3965</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Nav-mount.html">3955</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/OverflowSet-mount_base.html">1635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/OverflowSet-mount.html">1573</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Panel-mount_base.html">3008</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Panel-mount.html">3027</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Persona-mount_base.html">1512</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Persona-mount.html">1514</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Pivot-mount_base.html">1917</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Pivot-mount.html">1938</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/PrimaryButton-mount_base.html">1790</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/PrimaryButton-mount.html">1792</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Rating-mount_base.html">8273</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Rating-mount.html">8227</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/SearchBox-mount_base.html">1820</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/SearchBox-mount.html">1807</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Shimmer-mount_base.html">3361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Shimmer-mount.html">3402</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Slider-mount_base.html">2461</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Slider-mount.html">2472</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/SpinButton-mount_base.html">5508</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/SpinButton-mount.html">5481</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Spinner-mount_base.html">973</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Spinner-mount.html">927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/SplitButton-mount_base.html">3703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/SplitButton-mount.html">3650</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Stack-mount_base.html">1019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Stack-mount.html">1022</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/StackWithIntrinsicChildren-mount_base.html">2768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/StackWithIntrinsicChildren-mount.html">2766</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/StackWithTextChildren-mount_base.html">5609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/StackWithTextChildren-mount.html">5658</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/SwatchColorPicker-mount_base.html">12315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/SwatchColorPicker-mount.html">12411</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/TagPicker-mount_base.html">3073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/TagPicker-mount.html">3125</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/TeachingBubble-mount_base.html">102230</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/TeachingBubble-mount.html">99801</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Text-mount_base.html">947</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Text-mount.html">914</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/TextField-mount_base.html">1933</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/TextField-mount.html">1909</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ThemeProvider-mount_base.html">1811</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ThemeProvider-mount.html">1813</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ThemeProvider-virtual-rerender_base.html">1273</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ThemeProvider-virtual-rerender.html">1277</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2535</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Toggle-mount_base.html">1289</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/Toggle-mount.html">1331</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/buttonNative-mount_base.html">650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25249/perf-test/buttonNative-mount.html">682</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: lage.config.js [hunk 5]
```diff
@@ -8,10 +8,10 @@ module.exports = {
     lint: ['build'],
     clean: [],
     test: ['build'],
+    'type-check': ['build'],
```
Comment (TristanWatanabe) [inline lage.config.js:11]: ensures that before running `type-check` for each package, that all its dependencies have been built

File: apps/stress-test/src/shared/react/TestMount.tsx [hunk 6]
```diff
@@ -18,7 +18,7 @@ const debouncedOnRender: DebouncedOnRender = () => {
       clearTimeout(timeoutId);
     }
 
-    timeoutId = setTimeout(() => {
+    timeoutId = (setTimeout(() => {
```
Comment (Hotell) [inline apps/stress-test/src/shared/react/TestMount.tsx:21]: using globals is antipattern and root of issues not just on type level. use:

```suggestion
    timeoutId = (window.setTimeout(() => {
```

**Review by layershifter — APPROVED** [review]

File: lage.config.js (hunk 5 above)
Comment (Hotell) [reply lage.config.js:11]: while this is a good enough hot fix we need to do better, as this will slow down whole CI. type checks are most expensive operation ATM.

This issues will be mitigated be new task orchestrator in the future, but for now can we create issue to track this ? ty

File: packages/react-migration-v8-v9/src/stories/ThemeShim/createBrandVariants/index.stories.tsx [hunk 7]
```diff
@@ -1,8 +1,8 @@
 import * as React from 'react';
 
-import { createTheme, DefaultPalette } from '@fluentui/react';
+import { DefaultPalette } from '@fluentui/react';
 import { Button, makeStyles, Textarea, TextareaProps, shorthands, RadioGroup, Radio } from '@fluentui/react-components';
-import { createBrandVariants, createV9Theme } from '../../../components/Theme/index';
+import { createBrandVariants } from '../../../components/Theme/index';
```
Comment (Hotell) [inline packages/react-migration-v8-v9/src/stories/ThemeShim/createBrandVariants/index.stories.tsx:5]:
```suggestion
import { createBrandVariants } from '../../../components/Theme';
```

**Review by Hotell — APPROVED** [review]

File: scripts/lint-staged/tsconfig.json [hunk 8]
```diff
@@ -0,0 +1,7 @@
+{
+  "extends": "../tsconfig.scripts.json",
```
Comment (Hotell) [inline scripts/lint-staged/tsconfig.json:2]: **chore:** you need to register this in `tsconfig.scripts.json` and exclude in `scripts/tsconfig.json` to make it work as expected

File: lage.config.js (hunk 5 above)
Comment (TristanWatanabe) [reply lage.config.js:11]: New issue here: #25256

File: packages/react-migration-v8-v9/src/stories/ThemeShim/createBrandVariants/index.stories.tsx (hunk 7 above)
Comment (TristanWatanabe) [reply packages/react-migration-v8-v9/src/stories/ThemeShim/createBrandVariants/index.stories.tsx]: a463052

Comment (TristanWatanabe) [reply packages/react-migration-v8-v9/src/stories/ThemeShim/createBrandVariants/index.stories.tsx:5]: Actually this is being linted like a v8 package so it throws an error, reverted to importing from index explicitly:

```

verb @fluentui/react-migration-v8-v9 lint |  ERROR: 1 import path(s) do not reference physical files. This can break AMD imports. Please ensure the following imports reference physical files:
verb @fluentui/react-migration-v8-v9 lint |  -------------------------------------
verb @fluentui/react-migration-v8-v9 lint |    stories/ThemeShim/createBrandVariants/index.stories.tsx:
verb @fluentui/react-migration-v8-v9 lint |      ../../../components/Theme
verb @fluentui/react-migration-v8-v9 lint |  [2:43:55 PM] x Error detected while running 'lint-imports'
verb @fluentui/react-migration-v8-v9 lint |  [2:43:55 PM] x ------------------------------------
verb @fluentui/react-migration-v8-v9 lint |  [2:43:55 PM] x Errors in imports were found!
verb @fluentui/react-migration-v8-v9 lint |  [2:43:55 PM] x ------------------------------------
verb @fluentui/react-migration-v8-v9 lint |  [2:43:55 PM] x finished 'lint' in 0.09s with errors
verb @fluentui/react-migration-v8-v9 lint |  [2:43:55 PM] x Error previously detected. See above for error messages.
verb @fluentui/react-migration-v8-v9 lint |  [2:43:55 PM] x Other tasks that did not complete: [eslint]
verb @fluentui/react-migration-v8-v9 lint |  npm ERR! code ELIFECYCLE
verb @fluentui/react-migration-v8-v9 lint |  npm ERR! errno 1
verb @fluentui/react-migration-v8-v9 lint |  npm ERR! @fluentui/react-migration-v8-v9@1.0.0-alpha.0 lint: `just-scripts lint`
verb @fluentui/react-migration-v8-v9 lint |  npm ERR! Exit status 1
verb @fluentui/react-migration-v8-v9 lint |  npm ERR! 
verb @fluentui/react-migration-v8-v9 lint |  npm ERR! Failed at the @fluentui/react-migration-v8-v9@1.0.0-alpha.0 lint script.
verb @fluentui/react-migration-v8-v9 lint |  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Review by spmonahan — APPROVED** [review]

**Review by micahgodbolt — APPROVED** [review]
