### PR TITLE
fix: useFocusRects should resolve window inside useEffect

### LINKED ISSUE #14062: @fluentui/react-button: useFocusRects() uses a wrong ref
### Environment Information

- **Package version(s)**: `@fluentui/react-button@0.7.2`
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/summer-feather-13lb5

1. Open a CSB
2. Tab to a frame
3. Mention that frame body doesn't have classes for focus rects

image

#### Actual behavior:

No classes on `body`.

#### Expected behavior:

Classes on `body` 👍 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: Normal
Products/sites affected: N/A

### PR DESCRIPTION
**Pull request by layershifter**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #14062
- [x] Include a change request file using `$ yarn change`

#### Description of changes

1. `useFocusRects` uses a wrong `ref` in `useButton`:

https://github.com/microsoft/fluentui/blob/8247d915e42b98aceeeaaf0061c1ce3773bd17fb/packages/react-button/src/components/Button/useButton.ts#L21

Previously it passed a `ref` from the second param of `React.forwardRef()` which will be `null` a user will provide an input.

2. `useFocusRects` resolved `win` during a render

https://github.com/microsoft/fluentui/blob/8247d915e42b98aceeeaaf0061c1ce3773bd17fb/packages/utilities/src/useFocusRects.ts#L42-L46

The resolution occured during render when `rootRef.current` will be `null` 🧷 

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/react-button/src/components/Button/useButton.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { useImperativeHandle, useRef } from 'react';
```
Comment (layershifter) [inline packages/react-button/src/components/Button/useButton.ts:1]: I suggest to avoid such imports as previously `React` was not imported to this scope however it was used in ` React.RefObject`

File: packages/utilities/src/useFocusRects.ts [hunk 2]
```diff
@@ -40,9 +40,9 @@ type AppWindow = (Window & { FabricConfig?: { disableFocusRects?: boolean } }) |
  * @param rootRef - A Ref object. Focus rectangle can be applied on itself and all its children.
  */
 export function useFocusRects(rootRef?: React.RefObject<HTMLElement>): void {
```
Comment (layershifter) [inline packages/utilities/src/useFocusRects.ts:42]: This is still not enough safe it will be never reexecuted if `rootRef.current` will change
