### PR TITLE
fix(Collapse): handle content padding by animating it to zero

### LINKED ISSUE #32894: [🐞Bug] Padding visible in `Collapse` component when collapsed and visual jump with `unMountOnExit` flag
The padding of the child element remains visible when the `Collapse` component height is set to `0`.
There is a visual jump corresponding to the size of the padding when the `unMountOnExit` flag is set to `true`.

### Steps to Reproduce:

- Create a `Collapse` component with a child element that has padding.
- Set the `visible` state to `false` to trigger the collapse transition.
- Observe that while the height of the `Collapse` component is set to `0`, the padding of the child element remains visible.
- Set the `unMountOnExit` flag to `true`.
- Toggle the `visible` state to `true` and back to `false`.
- Observe the visual jump corresponding to the size of the padding.

### Expected Behavior:
When the `Collapse` component collapses, the entire child element, including its padding, should not be visible. Additionally, there should be no visual jump when the `unMountOnExit` flag is set to `true`.

### PR DESCRIPTION
**Pull request by robertpenner**
## Previous Behavior

- In the web box model, by design, setting the height of an element to zero does not affect the padding.
- Consequently, when `Collapse` has animated the height of the content element to 0, the content's padding remains visible, if `animateOpacity` is `false`.
- Also, when `animateOpacity` is `true` but `unmountOnExit` is `true`, the size of the padding is removed abruptly, causing a visual jump on unmount.
  - The visual issue is visible in the [Collapse Customization story](https://react.fluentui.dev/?path=/docs/motion-components-preview-collapse--docs#customization):
image
  

## New Behavior

- The content's padding is smoothly animated to zero automatically, using keyframes in the web animation.
  - The fix is visible in the [Collapse Customization story in the preview build](https://fluentuipr.z22.web.core.windows.net/pull/33063/public-docsite-v9/storybook/index.html?path=/docs/motion-components-preview-collapse--docs#customization).
- The padding animation produces a slight sliding effect, which varies according to the size of the padding. 
  - Motion Design team gave feedback that this effect is aesthetically pleasing, a happy accident.
  - If the end user doesn't want this effect, they can achieve a clean wipe by wrapping the content in an element with zero padding.

## Related Issue(s)

- Fixes #32894

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports | Baseline (minified/GZIP) | PR    | Change     |
| :---------------- | -----------------------: | ----: | ---------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr> | `105.087 kB`<br />`32.31 kB` | `105.317 kB`<br />`32.37 kB` | `230 B` <br />`60 B` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `218.878 kB`<br />`63.45 kB` | `219.108 kB`<br />`63.51 kB` | `230 B` <br />`60 B` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ReactComponents.fixture.js'>react-components: entire library</abbr> | `1.157 MB`<br />`289.827 kB` | `1.157 MB`<br />`289.895 kB` | `230 B` <br />`68 B` |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `69.14 kB`<br />`20.137 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `44.447 kB`<br />`14.59 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> | `8.39 kB`<br />`2.64 kB` |
| <samp>react-timepicker-compat</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr> | `107.387 kB`<br />`35.758 kB` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/7467ac09e2e6c37f0a9b9d1b49220005d6050516'>7467ac09e2e6c37f0a9b9d1b49220005d6050516</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/Avatar-mount_base.html">644</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/Avatar-mount.html">626</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/Button-mount_base.html">301</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/Button-mount.html">304</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/Field-mount_base.html">1137</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/Field-mount.html">1144</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/FluentProvider-mount_base.html">706</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/FluentProvider-mount.html">696</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/FluentProviderWithTheme-mount_base.html">93</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/FluentProviderWithTheme-mount.html">93</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">38</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">33</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">79</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">82</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/MakeStyles-mount_base.html">866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/MakeStyles-mount.html">851</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/Persona-mount_base.html">1836</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/Persona-mount.html">1742</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/SpinButton-mount_base.html">1442</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/SpinButton-mount.html">1355</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/SwatchPicker-mount_base.html">1688</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/33063/perf-test-react-components/SwatchPicker-mount.html">1693</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts [hunk 1]
```diff
@@ -43,7 +43,19 @@ export const createCollapsePresence: PresenceMotionFnCreator<CollapseVariantPara
     const sizeName = orientation === 'horizontal' ? 'maxWidth' : 'maxHeight';
```
Comment (fabricteam) [inline packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts:43]: ## 🕵🏾‍♀️ [<b data-uid='vrt-gist'></b> visual regressions to review in the fluentuiv9 Visual Regression Report](https://aka.ms/visual-changes-review?organization=uifabric&project=fabricpublic&prId=33063&commitId=73daa73d7b74346debc890992b762dade9cfb47f&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar Converged</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.badgeMask.chromium.png|2| Changed|
|Avatar Converged.Badge Mask RTL.chromium.png|7| Changed|

</details>


  <details><summary><b>Drawer</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Drawer.Full Overlay RTL.chromium.png|3279| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Review by ling1726 — APPROVED** [review]
