### PR TITLE
fix: Avatar shouldn't render an icon when displaying an image

### LINKED ISSUE #25777: Avatar: `PersonRegular` icon is always rendered causes perf issue
The `Avatar` always renders the `PersonRegular` icon even if the `image` prop is used which covers the icon https://github.com/microsoft/fluentui/blob/0df4721efb626b749f2d4962526d9cdde745f53c/packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx#L63

```tsx
<FluentAvatar
    size={64}
    image={{
      src: `https://teams.microsoft.com/api/mt/part/dogfood/beta/users/defaultProfilePictureV2?displayName=${name}`,
  }}
/>
```

image

This icon can increase performance by up to 50% compared to without the icon

| Example                     | min   | avg    | median | max   |
| --------------------------- | ----- | ------ | ------ | ----- |
| AvatarTestV0.perf.tsx       | 53.99 | 133.32 | 142.19 | 198.8 | 
| AvatarTestV9.perf.tsx       | 65.7  | 150.6  | 162.15 | 288.9 | 
| AvatarTestV9NoIcon.perf.tsx | 44.09 | 88.52  | 88.69  | 208.8 | 
| AvatarTestv9Image.perf.tsx  | 26.6  | 60.45  | 59.64  | 159.5 | 

Repro branch here: #25776. To get results from the perf test simply run `yarn cross-env PERF=true gulp perf --times=50 --filter=*AvatarTest*`

Also using chrome devtools on a test repo: https://github.com/ling1726/avatar-perf-bench

image

### PR DESCRIPTION
**Pull request by behowell**
## Previous Behavior

When an Avatar is displaying only an image and isn't displaying initials, it also renders the icon behind the image. This was done to ensure that something is displayed while the image is loading, or if the image fails to load. However, it causes performance issues by always rendering both the icon and image.

These are the results when running the perf tests from @ling1726's PR #25776. Note: **⭐ AvatarTestV9.perf.tsx** is the one testing the scenario in the bug; the others are for comparison.

| Example                     | avg       | description                               |
| --------------------------- | --------- | ----------------------------------------- |
| ⭐ AvatarTestV9.perf.tsx   | 🟥 58.84  | v9 Avatar with `image`                    |
| AvatarTestV9NoIcon.perf.tsx | 🟩 37.93     | v9 Avatar with `image`, and `icon={null}` |
| AvatarTestv9Image.perf.tsx  | 🟩  27.84     | just an `img` (no Avatar)                 |
| AvatarTestV0.perf.tsx       | 🟧 52.54     | v0 Avatar                                 |

## New Behavior

Don't render the icon if there is an image, unless the image fails to load.

Note: This only affects Avatars that don't have the `name` or `initials` properties set: if either of those is set, then the initials will always render behind the image, and they will be visible while the image is loading.

The runtime of **⭐ AvatarTestV9.perf.tsx** from @ling1726's PR #25776 is improved to 38.15 (down from 58.84). Here are the full results:

| Example                     | avg       | description                               |
| --------------------------- | --------- | ----------------------------------------- |
| ⭐ AvatarTestV9.perf.tsx   | 🟩 38.15  | v9 Avatar with `image`                    |
| AvatarTestV9NoIcon.perf.tsx | 🟩 38.89     | v9 Avatar with `image`, and `icon={null}` |
| AvatarTestv9Image.perf.tsx  | 🟩 27.33     | just an `img` (no Avatar)                 |
| AvatarTestV0.perf.tsx       | 🟧 52.15     | v0 Avatar                                 |

## Related Issue(s)

* Fixes #25777

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                            |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                               Change |
| :----------------------------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                      | `82.967 kB`<br />`21.022 kB` | `82.974 kB`<br />`21.028 kB` | `7 B` <br />`6 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                   | `51.076 kB`<br />`14.285 kB` | `51.083 kB`<br />`14.289 kB` | `7 B` <br />`4 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr> | `67.306 kB`<br />`18.581 kB` | `67.313 kB`<br />`18.585 kB` | `7 B` <br />`4 B`  |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                |  `57.113 kB`<br />`15.94 kB` |  `57.12 kB`<br />`15.945 kB` | `7 B` <br />`5 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                                                          |   `15.006 kB`<br />`6.009 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `59.288 kB`<br />`16.435 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `186.264 kB`<br />`52.303 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |   `33.75 kB`<br />`11.101 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/3749722c85c3f7d6ef5e6386b09659aeb8dac6d7'>3749722c85c3f7d6ef5e6386b09659aeb8dac6d7</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/Avatar-mount_base.html">1251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/Avatar-mount.html">1269</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/Button-mount_base.html">925</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/Button-mount.html">918</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/FluentProvider-mount_base.html">1494</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/FluentProvider-mount.html">1478</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/FluentProviderWithTheme-mount_base.html">579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/FluentProviderWithTheme-mount.html">571</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">542</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">551</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">581</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">589</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/MakeStyles-mount_base.html">1974</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/MakeStyles-mount.html">1960</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/Persona-mount_base.html">2833</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/Persona-mount.html">2795</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/SpinButton-mount_base.html">2305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25945/perf-test-react-components/SpinButton-mount.html">2357</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx [hunk 1]
```diff
@@ -44,6 +44,22 @@ export const useAvatar_unstable = (props: AvatarProps, ref: React.Ref<HTMLElemen
     /* excludedPropNames: */ ['name'],
   );
 
+  const [imageHidden, setImageHidden] = React.useState<true | undefined>(undefined);
```
Comment (layershifter) [inline packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx:47]: nit: Can you please clarify why it can't be simply `boolean` with `false` initially?

```suggestion
  const [imageHidden, setImageHidden] = React.useState<boolean>(false);
```

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25945&commitId=84de5a0b86ba38f8a774eb9ea1e1d44f008a5176&env=prod)

✅ There was 1 screenshots added, 0 screenshots removed, 1758 screenshots unchanged, 0 screenshots with different dimensions and 1 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.basic - High Contrast.normal.chromium.png|6| Changed|
|Avatar Converged.image-bad-url+icon.normal.chromium.png|0| Added|

</details>


<div id="vrtCommentfluentuiv9"/>

File: packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx (hunk 1 above)
Comment (behowell) [reply packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx:47]: > To avoid adding DOM attribute?

Yes, that is the reason.
