### PR TITLE
fix(react-utilities, react-provider): Remove colons from generated id and fix hook order error in React 18

### LINKED ISSUE #26651: [Bug]: Dropdown in 9.12 not compatible with React 18 Strict mode
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
none
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/cocky-golick-noknhb?file=/example.tsx

## Actual Behavior
With the recent move of the <Dropdown> component from unstable into the main library, the component is broken. When you click on the dropdown the following error appears.
`Failed to execute 'querySelector' on 'Element': '#fluent-option:r3:' is not a valid selector.`

Interestingly, we discovered that adding an `id` to the `<Option>`s fixes the error.

## Expected Behavior
Dropdown should display a list of options with throwing an exception

I don't know how there isn't already a bug filed. Am I missing something?
Here's a sandbox environment to repro. 
https://codesandbox.io/s/cocky-golick-noknhb?file=/example.tsx

image

### Logs

_No response_

### Requested priority

Blocking

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### LINKED ISSUE #26653: [Bug]: Cards not compatible with React 18
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 16.60 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.70)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/async-wood-bd02mn?file=/src/App.tsx

## Actual Behavior
Page renders blank

## Expected Behavior
Render the UI

### Logs

```shell
Warning: React has detected a change in the order of Hooks called by CardHeader. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useRef                     useRef
3. useContext                 useContext
4. useContext                 useContext
5. useId                      useEffect
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at eval (https://bd02mn.csb.app/node_modules/@fluentui/react-card/lib-commonjs/components/CardHeader/CardHeader.js:15:33)
    at div
    at eval (https://bd02mn.csb.app/node_modules/@fluentui/react-card/lib-commonjs/components/CardPreview/CardPreview.js:15:34)
    at div
    at eval (https://bd02mn.csb.app/node_modules/@fluentui/react-card/lib-commonjs/components/Card/Card.js:16:27)
    at App (https://bd02mn.csb.app/src/App.tsx:29:29)
```

### Requested priority

Blocking

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by sopranopillow**
fixes #26651

## Previous Behavior

When using React 18, our `useId` method calls React's `useId` conditionally.

## New Behavior

Our `useId` method now generates the id first and then returns the string generated conditionally to avoid using the hook conditionally.

Our `useId` method now also removes colons from React 18's generated id to avoid issues when querying in JS or CSS.

## Related Issue(s)

* Fixes #26653

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                 Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `89.627 kB`<br />`22.235 kB` |  `89.703 kB`<br />`22.255 kB` | `76 B` <br />`20 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |   `53.02 kB`<br />`14.654 kB` |  `53.096 kB`<br />`14.676 kB` | `76 B` <br />`22 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                                  |  `69.238 kB`<br />`18.953 kB` |  `69.314 kB`<br />`18.973 kB` | `76 B` <br />`20 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `49.929 kB`<br />`12.295 kB` |  `50.005 kB`<br />`12.319 kB` | `76 B` <br />`24 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `83.225 kB`<br />`23.834 kB` |  `83.301 kB`<br />`23.864 kB` | `76 B` <br />`30 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |   `10.916 kB`<br />`4.487 kB` |   `10.992 kB`<br />`4.512 kB` | `76 B` <br />`25 B`  |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr>                                                                              |  `33.023 kB`<br />`10.293 kB` |  `33.099 kB`<br />`10.311 kB` | `76 B` <br />`18 B`  |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/CheckboxField.fixture.js'>CheckboxField</abbr>                                                                    |  `39.928 kB`<br />`12.181 kB` |  `40.004 kB`<br />`12.205 kB` | `76 B` <br />`24 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                                                 |  `83.086 kB`<br />`26.531 kB` |  `83.162 kB`<br />`26.554 kB` | `76 B` <br />`23 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/ComboboxField.fixture.js'>ComboboxField</abbr>                                                                    |  `79.503 kB`<br />`26.294 kB` |  `79.579 kB`<br />`26.316 kB` | `76 B` <br />`22 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>                                                 |  `81.773 kB`<br />`26.258 kB` |  `81.849 kB`<br />`26.275 kB` | `76 B` <br />`17 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `64.042 kB`<br />`17.543 kB` |  `64.098 kB`<br />`17.553 kB` | `56 B` <br />`10 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `199.591 kB`<br />`55.418 kB` | `199.647 kB`<br />`55.433 kB` | `56 B` <br />`15 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |   `35.006 kB`<br />`11.53 kB` |  `35.062 kB`<br />`11.538 kB` |  `56 B` <br />`8 B`  |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |  `89.651 kB`<br />`26.663 kB` |  `89.727 kB`<br />`26.687 kB` | `76 B` <br />`24 B`  |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `17.042 kB`<br />`6.153 kB` |    `17.118 kB`<br />`6.18 kB` | `76 B` <br />`27 B`  |
| <samp>react-field</samp> <br /> <abbr title='bundle-size/Field.fixture.js'>Field</abbr>                                                                                       |   `17.605 kB`<br />`6.518 kB` |   `17.681 kB`<br />`6.545 kB` | `76 B` <br />`27 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        | `124.779 kB`<br />`37.886 kB` | `124.855 kB`<br />`37.908 kB` | `76 B` <br />`22 B`  |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/InputField.fixture.js'>InputField</abbr>                                                                             |   `34.99 kB`<br />`11.072 kB` |  `35.066 kB`<br />`11.099 kB` | `76 B` <br />`27 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `124.136 kB`<br />`37.879 kB` | `124.212 kB`<br />`37.901 kB` | `76 B` <br />`22 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `127.205 kB`<br />`38.391 kB` | `127.281 kB`<br />`38.412 kB` | `76 B` <br />`21 B`  |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                                                               |   `11.151 kB`<br />`4.245 kB` |   `11.227 kB`<br />`4.284 kB` | `76 B` <br />`39 B`  |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                                                                 |  `59.858 kB`<br />`16.543 kB` |  `59.934 kB`<br />`16.564 kB` | `76 B` <br />`21 B`  |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `111.863 kB`<br />`34.31 kB` |  `111.939 kB`<br />`34.33 kB` | `76 B` <br />`20 B`  |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressField.fixture.js'>ProgressField</abbr>                                                                    |   `23.805 kB`<br />`8.339 kB` |   `23.881 kB`<br />`8.371 kB` | `76 B` <br />`32 B`  |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `17.073 kB`<br />`6.327 kB` |   `17.129 kB`<br />`6.337 kB` | `56 B` <br />`10 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `32.608 kB`<br />`10.589 kB` |  `32.684 kB`<br />`10.613 kB` | `76 B` <br />`24 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |    `14.822 kB`<br />`5.91 kB` |   `14.898 kB`<br />`5.932 kB` | `76 B` <br />`22 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroupField.fixture.js'>RadioGroupField</abbr>                                                                   |   `24.895 kB`<br />`9.045 kB` |   `24.971 kB`<br />`9.069 kB` | `76 B` <br />`24 B`  |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/SelectField.fixture.js'>SelectField</abbr>                                                                          |  `33.316 kB`<br />`10.755 kB` |  `33.392 kB`<br />`10.781 kB` | `76 B` <br />`26 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |  `33.023 kB`<br />`10.523 kB` |  `33.099 kB`<br />`10.553 kB` | `76 B` <br />`30 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/SliderField.fixture.js'>SliderField</abbr>                                                                          |   `42.854 kB`<br />`13.44 kB` |   `42.93 kB`<br />`13.466 kB` | `76 B` <br />`26 B`  |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButtonField.fixture.js'>SpinButtonField</abbr>                                                              |  `54.361 kB`<br />`15.594 kB` |   `54.437 kB`<br />`15.63 kB` | `76 B` <br />`36 B`  |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `20.552 kB`<br />`6.658 kB` |   `20.628 kB`<br />`6.684 kB` | `76 B` <br />`26 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |    `28.157 kB`<br />`8.73 kB` |   `28.233 kB`<br />`8.757 kB` | `76 B` <br />`27 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/SwitchField.fixture.js'>SwitchField</abbr>                                                                          |   `34.942 kB`<br />`10.63 kB` |  `35.018 kB`<br />`10.653 kB` | `76 B` <br />`23 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                                                                                 |  `135.786 kB`<br />`36.67 kB` | `135.862 kB`<br />`36.693 kB` | `76 B` <br />`23 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>                                                                 | `134.221 kB`<br />`34.445 kB` | `134.297 kB`<br />`34.474 kB` | `76 B` <br />`29 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr>                                                         |   `82.14 kB`<br />`20.507 kB` |  `82.216 kB`<br />`20.536 kB` | `76 B` <br />`29 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>                                                                   |  `81.569 kB`<br />`20.356 kB` |  `81.645 kB`<br />`20.386 kB` | `76 B` <br />`30 B`  |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/TextareaField.fixture.js'>TextareaField</abbr>                                                                    |  `36.469 kB`<br />`11.483 kB` |  `36.545 kB`<br />`11.507 kB` | `76 B` <br />`24 B`  |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `43.897 kB`<br />`15.337 kB` |  `43.973 kB`<br />`15.357 kB` | `76 B` <br />`20 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                   |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContext.fixture.js'>createContext</abbr>                          |         `533 B`<br />`341 B` |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContextSelector.fixture.js'>createContextSelector</abbr>          |         `554 B`<br />`348 B` |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr> | `85.867 kB`<br />`26.007 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                |   `15.42 kB`<br />`6.167 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                             |   `23.78 kB`<br />`7.542 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                               |   `24.67 kB`<br />`7.825 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                             |  `25.796 kB`<br />`7.444 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                          |   `36.883 kB`<br />`9.41 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                          | `44.058 kB`<br />`10.884 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                  |  `41.563 kB`<br />`10.74 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                              | `55.247 kB`<br />`11.328 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                | `78.062 kB`<br />`22.413 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                    |    `9.04 kB`<br />`3.807 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                  |   `9.847 kB`<br />`4.159 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                             |  `11.259 kB`<br />`4.473 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                             |  `24.848 kB`<br />`8.136 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                             |   `9.817 kB`<br />`4.067 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                               |  `12.306 kB`<br />`5.073 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                          |  `11.377 kB`<br />`4.179 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>               |   `6.324 kB`<br />`2.129 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePositioning</abbr>                          |  `20.864 kB`<br />`7.776 kB` |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressBar.fixture.js'>ProgressBar</abbr>                              |  `13.573 kB`<br />`5.232 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                          |   `24.14 kB`<br />`8.271 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                              | `45.161 kB`<br />`13.035 kB` |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>                  | `43.771 kB`<br />`12.063 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                              |  `12.261 kB`<br />`4.819 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                            |   `15.571 kB`<br />`5.23 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                    |  `26.331 kB`<br />`8.581 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                             |         `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/cd66dc983d876cfe097e92598e1f002df106edfb'>cd66dc983d876cfe097e92598e1f002df106edfb</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/Avatar-mount_base.html">1672</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/Avatar-mount.html">1686</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/Button-mount_base.html">1159</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/Button-mount.html">1175</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/FluentProvider-mount_base.html">2051</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/FluentProvider-mount.html">2030</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/FluentProviderWithTheme-mount_base.html">738</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/FluentProviderWithTheme-mount.html">726</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">669</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">682</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">756</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">731</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/InfoButton-mount_base.html">643</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/InfoButton-mount.html">649</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/MakeStyles-mount_base.html">2304</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/MakeStyles-mount.html">2286</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/Persona-mount_base.html">3901</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/Persona-mount.html">3946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/SpinButton-mount_base.html">3262</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26745/perf-test-react-components/SpinButton-mount.html">3375</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

**Review by micahgodbolt — APPROVED** [review]

File: packages/react-components/react-utilities/src/hooks/useId.ts [hunk 1]
```diff
@@ -37,7 +37,9 @@ export function useId(prefix: string = 'fui-', providedId?: string): string {
   const _useId: () => string | undefined = (React as never)['use' + 'Id'];
 
   if (_useId) {
-    return providedId || `${idPrefix}${prefix}${_useId()}`;
+    const generatedId = _useId()?.replace(/:/g, '');
```
Comment (marcosmoura) [inline packages/react-components/react-utilities/src/hooks/useId.ts:40]: nit: The replace can happen conditionally, to not replace even when not needed.

Comment (sopranopillow) [reply packages/react-components/react-utilities/src/hooks/useId.ts:40]: Not sure I understand what you mean. If it's that sometimes replace can be executed when there's no colons, that's not the case. From the code that makes the id:
```
function makeId(responseState, treeId, localId) {
    var idPrefix = responseState.idPrefix;
    var id = ':' + idPrefix + 'R' + treeId; // Unless this is the first id at this level, append a number at the end
    // that represents the position of this useId hook among all the useId
    // hooks for this fiber.

    if (localId > 0) {
      id += 'H' + localId.toString(32);
    }

    return id + ':';
  }
```
There will always be a colon. Also the `?` is needed since we don't have the types for use id. If you prefer I could type cast it, but I feel it's not the right way to go.

File: packages/react-components/react-utilities/src/hooks/useId.ts [hunk 2]
```diff
@@ -37,7 +37,9 @@ export function useId(prefix: string = 'fui-', providedId?: string): string {
   const _useId: () => string | undefined = (React as never)['use' + 'Id'];
```
Comment (ling1726) [inline packages/react-components/react-utilities/src/hooks/useId.ts:37]: Are you sure `useId` can return `undefined`? The react docs don't mention this, you could avoid having the null chaining 

https://beta.reactjs.org/reference/react/useId

**Review by ling1726 — APPROVED** [review]

**Comment by elliot-huffman** [comment]
Fixes #26653

File: packages/react-components/react-utilities/src/hooks/useId.ts (hunk 2 above)
Comment (sopranopillow) [reply packages/react-components/react-utilities/src/hooks/useId.ts:37]: yes, that's the case. I'll fix it.

File: packages/react-components/react-utilities/src/hooks/useId.ts [hunk 3]
```diff
@@ -34,10 +34,15 @@ export function useId(prefix: string = 'fui-', providedId?: string): string {
 
   // Checking if useId is available on React, if it is, we use it to generate the id. String concatenation is used to
   // prevent bundlers from complaining with older versions of React.
-  const _useId: () => string | undefined = (React as never)['use' + 'Id'];
+  const _useId = (React as never)['use' + 'Id'] as (() => string) | undefined;
```
Comment (sopranopillow) [inline packages/react-components/react-utilities/src/hooks/useId.ts:37]: Adding a type `_useId: (() => string) | undefined` will not work as it will resolve as `never`, to get around that we have to type cast it to that type instead.

**Review by ling1726 — APPROVED** [review]

**Review by khmakoto — APPROVED** [review]
