### PR TITLE
chore(react-components): fix build:local task

### LINKED ISSUE #21910: tsconfig override in `packages/react-components/config/api-extractor.local.json` is out of date with updates to main tsconfig

### PR DESCRIPTION
**Pull request by Hotell**
## Current Behavior

- after migration of `react-components` to `react-components` parent folder `build:local` is broken

## New Behavior

- `local:build` works
- `move` generator has been updated to accommodate this behaviour for other packages
- updates `react-components` tsConfig override in api extractor config

## Related Issue(s)

Fixes #21910

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/275f5182f8008016c5bad0c00c38c52474a47b8b'>275f5182f8008016c5bad0c00c38c52474a47b8b</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/Avatar-mount_base.html">906</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/Avatar-mount.html">859</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/Button-mount_base.html">550</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/Button-mount.html">503</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/FluentProvider-mount_base.html">1947</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/FluentProvider-mount.html">1991</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/FluentProviderWithTheme-mount_base.html">289</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/FluentProviderWithTheme-mount.html">315</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">241</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">263</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">283</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/MakeStyles-mount_base.html">1590</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22664/perf-test-react-components/MakeStyles-mount.html">1551</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: tools/generators/move-packages/index.ts [hunk 1]
```diff
@@ -154,3 +163,17 @@ function updateCodeOwners(tree: Tree, schema: MovePackagesGeneratorSchema) {
...
 }
+
+function updateApiExtractor(tree: Tree, schema: MovePackagesGeneratorSchema) {
+  const projectConfig = getProjectConfig(tree, { packageName: schema.name! });
+  const apiExtractorLocalPath = joinPathFragments(projectConfig.paths.configRoot, 'api-extractor.local.json');
+  const apiExtractorLocal = readJson(tree, apiExtractorLocalPath);
+  const originalEntryPointPath = apiExtractorLocal.mainEntryPointFilePath;
+  const updatedEntryPointPath = originalEntryPointPath.replace(
+    'packages/<unscopedPackageName>',
+    `packages/${schema.destination}/<unscopedPackageName>`,
```
Comment (TristanWatanabe) [inline tools/generators/move-packages/index.ts:174]: `schema.destination` in the case of v9 moves will be along the lines of `testFolder/react-menu` so adding the whole `destination` will be redundant with `unscopedPackageName`

**Review by TristanWatanabe — COMMENTED** [review]
Thanks for fixing this! I just realized that generator also needs to update the actual `build:local` script in the package json to account for the new path (i.e. this portion: `./dist/packages/react-avatar/src`)

File: tools/generators/move-packages/index.ts (hunk 1 above)
Comment (Hotell) [reply tools/generators/move-packages/index.ts:174]: hmm, right that was bit unclear. so what should we do ? strip the last dirname part from destination ?

Comment (TristanWatanabe) [reply tools/generators/move-packages/index.ts:174]: Yup that should do it since the last part of the destination will always be the package name anyway

Comment (Hotell) [reply tools/generators/move-packages/index.ts]: should be fixed c054783087882b175568f518d668948b4e2d3663

**Comment by Hotell** [comment]
> 

kk pls (the additional update/fix) do, ty!

File: tools/generators/move-packages/index.ts [hunk 2]
```diff
@@ -154,3 +163,18 @@ function updateCodeOwners(tree: Tree, schema: MovePackagesGeneratorSchema) {
     tree.write(codeownersPath, updatedCodeOwnersFile);
   }
 }
+
+function updateApiExtractor(tree: Tree, schema: MovePackagesGeneratorSchema) {
+  const projectConfig = getProjectConfig(tree, { packageName: schema.name! });
+  const apiExtractorLocalPath = joinPathFragments(projectConfig.paths.configRoot, 'api-extractor.local.json');
+  const apiExtractorLocal = readJson(tree, apiExtractorLocalPath);
+  const originalEntryPointPath = apiExtractorLocal.mainEntryPointFilePath;
+  const normalizeFolderDestination = schema.destination.split('/').slice(0, -1);
```
Comment (TristanWatanabe) [inline tools/generators/move-packages/index.ts:172]: This is currently returning an array instead of a string
```suggestion
  const normalizeFolderDestination = schema.destination.split('/').slice(0, -1).join("/");
```
