### PR TITLE
fix(RadioGroupItem): invoke onChange with proper checked state

### LINKED ISSUE #15998: RadioItem onChange broken in @fluentui/react-northstar@0.51.2
### Environment Information

- **@fluentui/react-northstar@0.51.2**

### Please provide a reproduction of the bug in a codepen:

[Correct behaviour in 0.47.13](https://codesandbox.io/s/fluent-ui-example-forked-ccdid)
[Incorrect behaviour in 0.51.2](https://codesandbox.io/s/fluent-ui-example-forked-ccdid)

#### Actual behavior:

`onChange` is not called for `RadioItem` on every state change as in 0.47.13. State changes are also offset, simply toggle the radio items multiple times and observe

#### Expected behavior:

`onChange` is called for `RadioItem` on every state change as in 0.47.13

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #15998
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Using `ref` together with `useEffect` to mimic previously behavior we had with `ComponentDidMount` lifecycle, currently we are invoking `onChange` with outdated checked state. 

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/components/RadioGroup/RadioGroupItem.tsx [hunk 1]
```diff
@@ -118,14 +118,22 @@ export const RadioGroupItem: ComponentWithAs<'div', RadioGroupItemProps> &
...
     _.invoke(props, 'onClick', e, props);
     setChecked(prevChecked => {
-      _.invoke(props, 'onChange', undefined, { ...props, checked: !prevChecked });
       return !prevChecked;
     });
   };
 
+  React.useEffect(() => {
+    if (prevChecked.current !== checked) {
+      _.invoke(props, 'onChange', undefined, { ...props, checked });
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/RadioGroup/RadioGroupItem.tsx:132]: So I think maybe a TODO to make a breaking change and make `onChange` behave natively (only on selection) might make sense, I think @layershifter  would also agree

**Review by ling1726 — APPROVED** [review]
LGTM, but this is a regression where we want a unit test, especially if we decide to change this behaviour in the future

File: packages/fluentui/react-northstar/src/components/RadioGroup/RadioGroupItem.tsx (hunk 1 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/RadioGroup/RadioGroupItem.tsx:134]: Added

Comment (ling1726) [reply packages/fluentui/react-northstar/src/components/RadioGroup/RadioGroupItem.tsx:134]: LGTM

File: packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx [hunk 2]
```diff
@@ -81,6 +82,29 @@ describe('RadioGroup', () => {
...
+      const wrapper = mountWithProvider(<RadioGroup items={items} />);
+      const radioGroupItems = wrapper.find('RadioGroupItem');
+
+      radioGroupItems
+        .first()
+        .find('div')
+        .first()
+        .simulate('click');
+      wrapper.update();
+      const onChange = items[0].onChange || items[0].props.onChange;
```
Comment (layershifter) [inline packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:96]:
```suggestion
```

Let's avoid props usage

File: packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx [hunk 3]
```diff
@@ -81,6 +82,29 @@ describe('RadioGroup', () => {
       expect(onClick).toHaveBeenCalled();
     });
 
+    it('calls onChange handler for item with updated checked state', () => {
+      const items = getItems();
```
Comment (layershifter) [inline packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:86]:
```suggestion
      const onChange = jest.fn();
      const items = [
          {
             name: 'test-name',
             key: 'test-key0',
             label: 'test-label0',
             value: 'test-value0',
             onChange,
           },
        ...getItems(),
      ]
```

File: packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx [hunk 4]
```diff
@@ -81,6 +82,29 @@ describe('RadioGroup', () => {
...
+      const wrapper = mountWithProvider(<RadioGroup items={items} />);
+      const radioGroupItems = wrapper.find('RadioGroupItem');
+
+      radioGroupItems
+        .first()
+        .find('div')
+        .first()
```
Comment (layershifter) [inline packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:93]: Do we need this dive?

File: packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx [hunk 5]
```diff
@@ -81,6 +82,29 @@ describe('RadioGroup', () => {
...
+      wrapper.update();
+      const onChange = items[0].onChange || items[0].props.onChange;
+      expect(onChange).toHaveBeenCalledWith(undefined, expect.objectContaining({ checked: true }));
+
+      radioGroupItems
+        .last()
+        .find('div')
+        .first()
+        .simulate('click');
+      wrapper.update();
```
Comment (layershifter) [inline packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:104]: Should be `act()` used instead?

Comment (ling1726) [reply packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:104]: is it needed ? enzyme should wrap all actions with `act`

Comment (ling1726) [reply packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:104]: might as well try removing the `wrapper.update()`

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:113]: Removing it will not call `onChange`

File: packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx (hunk 4 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:103]: Not really, removed

File: packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx [hunk 6]
```diff
@@ -17,6 +17,7 @@ const getShorthandItems = (props?: { disabledItem?: number }) => [
     value: 'test-value1',
     'data-foo': 'something',
     onClick: jest.fn(),
+    onChange: jest.fn(),
```
Comment (assuncaocharles) [inline packages/fluentui/react-northstar/test/specs/components/RadioGroup/RadioGroup-test.tsx:20]:
```suggestion
```
