### PR TITLE
fix(eslint-plugin): make import/no-extraneous-dependencies work for react config

### LINKED ISSUE #21789: `import/no-extraneous-dependencies` does not work as expected
## Problem

We are using [`import/no-extraneous-dependencies`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) in our ESLint setup:

https://github.com/microsoft/fluentui/blob/59517602a1a93681cde023e37a8b4cab1858755f/packages/eslint-plugin/src/configs/react.js#L105

The idea is that it will save us from extraneous dependencies. This works **only** for third party dependencies.

## Sample issue

We have `@fluentui/react-image` package and it uses `@fluentui/react-theme` package:

https://github.com/microsoft/fluentui/blob/59517602a1a93681cde023e37a8b4cab1858755f/packages/react-image/src/components/Image/useImageStyles.ts#L2

But `@fluentui/react-theme` is not declared as a dependency in `package.json` of `@fluentui/react-image`:

https://github.com/microsoft/fluentui/blob/59517602a1a93681cde023e37a8b4cab1858755f/packages/react-image/package.json#L45-L49

### PR DESCRIPTION
**Pull request by Hotell**
## Current Behavior

- packages being published don't specify proper dependencies
- lint rule checking package.json dependency compliance won't error if there are violations
- we ship packages to npm that may not be usable after install

image

## New Behavior

- all packages specify proper dependencies
- lint rule will error out if there are violations

image
image

### additional feature implemented

- just-scripts `copy` task, adds new api to `copyTo` ( copy and rename )

```jsonc
{
  "copyTo": {
    // greet.jpg file will be copied to hello-world directory
    "hello-world": ["./assets/greet.jpg"],

    // readme.md__tmpl__ file will be copied production directory and renamed to readme.md
   "production/readme.md": "src/one/two/readme.md__tmpl__"
  }
}

```

## Related Issue(s)

Fixes #21789

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `72.822 kB`<br />`22.054 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `44.943 kB`<br />`13.043 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `20.869 kB`<br />`6.549 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `21.737 kB`<br />`6.843 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |   `21.827 kB`<br />`6.519 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `27.982 kB`<br />`8.043 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `33.246 kB`<br />`9.007 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |    `29.65 kB`<br />`8.624 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `36.132 kB`<br />`9.835 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |    `37.28 kB`<br />`8.647 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |   `53.205 kB`<br />`15.27 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `48.898 kB`<br />`14.083 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `7.653 kB`<br />`3.246 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `8.931 kB`<br />`3.689 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `7.626 kB`<br />`3.272 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox</abbr>                                                                              |    `6.813 kB`<br />`2.895 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `171.709 kB`<br />`48.089 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.526 kB`<br />`10.645 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `15.301 kB`<br />`5.532 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |   `10.105 kB`<br />`3.952 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |   `21.538 kB`<br />`7.134 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.341 kB`<br />`3.487 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `11.102 kB`<br />`4.504 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          |  `103.43 kB`<br />`31.858 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `105.785 kB`<br />`32.219 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `96.339 kB`<br />`29.399 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |    `6.267 kB`<br />`2.168 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePopper</abbr>                                                                         |    `23.21 kB`<br />`8.084 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |    `14.009 kB`<br />`5.25 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                                                    |    `7.754 kB`<br />`3.258 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |   `22.975 kB`<br />`7.769 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |    `6.811 kB`<br />`2.895 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `22.598 kB`<br />`7.642 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |    `10.793 kB`<br />`4.23 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `14.107 kB`<br />`4.573 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>                                                        |            `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                                                                  |   `29.426 kB`<br />`6.551 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                                                                |     `18.42 kB`<br />`5.27 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |   `42.76 kB`<br />`14.701 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                                                                       |          `189 B`<br />`161 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b2c50ddff051a104ad6792fee845c587f3705a00'>b2c50ddff051a104ad6792fee845c587f3705a00</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ChatWithPopoverPerf.default | [919](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ChatWithPopoverPerf.default.html) | [331](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 2.78:1
VideoMinimalPerf.default | [1209](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/VideoMinimalPerf.default.html) | [510](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/VideoMinimalPerf.default_base.html) | 2.37:1
SplitButtonMinimalPerf.default | [4344](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3661](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.19:1
PortalMinimalPerf.default | [167](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/PortalMinimalPerf.default.html) | [146](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.14:1
TreeWith60ListItems.default | [175](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TreeWith60ListItems.default.html) | [155](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.13:1
AttachmentMinimalPerf.default | [139](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AttachmentMinimalPerf.default.html) | [124](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.12:1
ChatDuplicateMessagesPerf.default | [275](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [245](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.12:1
ChatMinimalPerf.default | [635](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ChatMinimalPerf.default.html) | [587](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.08:1
HeaderSlotsPerf.default | [639](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/HeaderSlotsPerf.default.html) | [594](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.08:1
CardMinimalPerf.default | [448](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/CardMinimalPerf.default.html) | [417](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.07:1
IconMinimalPerf.default | [523](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/IconMinimalPerf.default.html) | [493](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.06:1
AlertMinimalPerf.default | [246](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AlertMinimalPerf.default.html) | [234](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.05:1
ImageMinimalPerf.default | [332](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ImageMinimalPerf.default.html) | [317](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.05:1
StatusMinimalPerf.default | [596](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/StatusMinimalPerf.default.html) | [569](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.05:1
ToolbarMinimalPerf.default | [802](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ToolbarMinimalPerf.default.html) | [767](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.05:1
AccordionMinimalPerf.default | [141](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AccordionMinimalPerf.default.html) | [136](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.04:1
BoxMinimalPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/BoxMinimalPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.04:1
ButtonMinimalPerf.default | [157](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ButtonMinimalPerf.default.html) | [151](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [487](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ButtonSlotsPerf.default.html) | [470](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
GridMinimalPerf.default | [306](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/GridMinimalPerf.default.html) | [294](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.04:1
ReactionMinimalPerf.default | [343](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ReactionMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.04:1
DatepickerMinimalPerf.default | [5264](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5099](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.03:1
DialogMinimalPerf.default | [661](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DialogMinimalPerf.default.html) | [644](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.03:1
MenuMinimalPerf.default | [737](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/MenuMinimalPerf.default.html) | [717](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.03:1
PopupMinimalPerf.default | [528](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/PopupMinimalPerf.default.html) | [514](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.03:1
SliderMinimalPerf.default | [1415](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/SliderMinimalPerf.default.html) | [1374](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.03:1
CheckboxMinimalPerf.default | [2288](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2241](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.02:1
DividerMinimalPerf.default | [312](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DividerMinimalPerf.default.html) | [307](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.02:1
DropdownMinimalPerf.default | [2634](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DropdownMinimalPerf.default.html) | [2587](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.02:1
FlexMinimalPerf.default | [255](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/FlexMinimalPerf.default.html) | [249](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.02:1
InputMinimalPerf.default | [1132](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/InputMinimalPerf.default.html) | [1105](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.02:1
ListWith60ListItems.default | [573](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ListWith60ListItems.default.html) | [564](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.02:1
RosterPerf.default | [1036](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/RosterPerf.default.html) | [1018](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/RosterPerf.default_base.html) | 1.02:1
AnimationMinimalPerf.default | [472](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AnimationMinimalPerf.default.html) | [466](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.01:1
ListCommonPerf.default | [541](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ListCommonPerf.default.html) | [534](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [589](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/LoaderMinimalPerf.default.html) | [586](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
RefMinimalPerf.default | [206](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/RefMinimalPerf.default.html) | [203](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.01:1
SegmentMinimalPerf.default | [303](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/SegmentMinimalPerf.default.html) | [301](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1624](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TableManyItemsPerf.default.html) | [1615](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TextAreaMinimalPerf.default | [423](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TextAreaMinimalPerf.default.html) | [418](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1448](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1452](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [3528](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/EmbedMinimalPerf.default.html) | [3523](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
LayoutMinimalPerf.default | [319](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/LayoutMinimalPerf.default.html) | [318](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1:1
SkeletonMinimalPerf.default | [301](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/SkeletonMinimalPerf.default.html) | [301](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1:1
TableMinimalPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TableMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TableMinimalPerf.default_base.html) | 1:1
AvatarMinimalPerf.default | [172](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AvatarMinimalPerf.default.html) | [173](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.99:1
FormMinimalPerf.default | [362](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/FormMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.99:1
ListMinimalPerf.default | [435](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ListMinimalPerf.default.html) | [438](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.99:1
MenuButtonMinimalPerf.default | [1410](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1422](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1476](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1498](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
TextMinimalPerf.default | [295](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TextMinimalPerf.default.html) | [299](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.99:1
AttachmentSlotsPerf.default | [904](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AttachmentSlotsPerf.default.html) | [921](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.98:1
DropdownManyItemsPerf.default | [581](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DropdownManyItemsPerf.default.html) | [593](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.98:1
RadioGroupMinimalPerf.default | [379](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [388](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.98:1
CustomToolbarPrototype.default | [3394](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/CustomToolbarPrototype.default.html) | [3583](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.95:1
CarouselMinimalPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/CarouselMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.94:1
HeaderMinimalPerf.default | [311](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/HeaderMinimalPerf.default.html) | [332](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.94:1
ProviderMinimalPerf.default | [987](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ProviderMinimalPerf.default.html) | [1076](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.92:1
LabelMinimalPerf.default | [296](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/LabelMinimalPerf.default.html) | [324](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.91:1
TooltipMinimalPerf.default | [887](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TooltipMinimalPerf.default.html) | [1193](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.74:1
ItemLayoutMinimalPerf.default | [968](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1351](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.72:1
TreeMinimalPerf.default | [700](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TreeMinimalPerf.default.html) | [1254](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.56:1
ListNestedPerf.default | [490](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ListNestedPerf.default.html) | [1436](https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-northstar/ListNestedPerf.default_base.html) | 0.34:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Avatar-mount_base.html">1076</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Avatar-mount.html">1054</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/BaseButton-mount_base.html">1090</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/BaseButton-mount.html">1098</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Breadcrumb-mount_base.html">2853</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Breadcrumb-mount.html">2844</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ButtonNext-mount_base.html">541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ButtonNext-mount.html">541</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Checkbox-mount_base.html">1842</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Checkbox-mount.html">1830</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/CheckboxBase-mount_base.html">1543</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/CheckboxBase-mount.html">1520</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ChoiceGroup-mount_base.html">5501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ChoiceGroup-mount.html">5598</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ComboBox-mount_base.html">1111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ComboBox-mount.html">1114</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/CommandBar-mount_base.html">11131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/CommandBar-mount.html">11253</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ContextualMenu-mount_base.html">9178</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ContextualMenu-mount.html">9087</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DefaultButton-mount_base.html">1312</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DefaultButton-mount.html">1308</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DetailsRow-mount_base.html">4254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DetailsRow-mount.html">4255</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DetailsRowFast-mount_base.html">4251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DetailsRowFast-mount.html">4242</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DetailsRowNoStyles-mount_base.html">4041</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DetailsRowNoStyles-mount.html">4166</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Dialog-mount_base.html">2474</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Dialog-mount.html">2520</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DocumentCardTitle-mount_base.html">192</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/DocumentCardTitle-mount.html">203</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Dropdown-mount_base.html">3735</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Dropdown-mount.html">3712</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FluentProviderNext-mount_base.html">1992</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FluentProviderNext-mount.html">2023</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FluentProviderWithTheme-mount_base.html">186</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FluentProviderWithTheme-mount.html">189</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FluentProviderWithTheme-virtual-rerender.html">126</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">214</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">227</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FocusTrapZone-mount_base.html">2023</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FocusTrapZone-mount.html">2061</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FocusZone-mount_base.html">1950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/FocusZone-mount.html">1942</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/IconButton-mount_base.html">2031</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/IconButton-mount.html">2079</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Label-mount_base.html">401</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Label-mount.html">404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Layer-mount_base.html">3401</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Layer-mount.html">3406</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Link-mount_base.html">572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Link-mount.html">585</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/MakeStyles-mount_base.html">1858</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/MakeStyles-mount.html">1835</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/MenuButton-mount_base.html">1716</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/MenuButton-mount.html">1698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/MessageBar-mount_base.html">2235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/MessageBar-mount.html">2261</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Nav-mount_base.html">3821</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Nav-mount.html">3733</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/OverflowSet-mount_base.html">1263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/OverflowSet-mount.html">1251</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Panel-mount_base.html">2388</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Panel-mount.html">2388</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Persona-mount_base.html">986</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Persona-mount.html">985</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Pivot-mount_base.html">1649</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Pivot-mount.html">1676</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/PrimaryButton-mount_base.html">1505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/PrimaryButton-mount.html">1513</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Rating-mount_base.html">9059</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Rating-mount.html">8943</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/SearchBox-mount_base.html">1607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/SearchBox-mount.html">1566</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Shimmer-mount_base.html">3004</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Shimmer-mount.html">2922</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Slider-mount_base.html">2241</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Slider-mount.html">2258</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/SpinButton-mount_base.html">5760</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/SpinButton-mount.html">5733</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Spinner-mount_base.html">522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Spinner-mount.html">503</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/SplitButton-mount_base.html">3629</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/SplitButton-mount.html">3680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Stack-mount_base.html">648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Stack-mount.html">655</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/StackWithIntrinsicChildren-mount_base.html">2817</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/StackWithIntrinsicChildren-mount.html">2765</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/StackWithTextChildren-mount_base.html">6433</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/StackWithTextChildren-mount.html">6458</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/SwatchColorPicker-mount_base.html">13298</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/SwatchColorPicker-mount.html">13457</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/TagPicker-mount_base.html">3033</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/TagPicker-mount.html">3085</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/TeachingBubble-mount_base.html">14501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/TeachingBubble-mount.html">14656</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Text-mount_base.html">522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Text-mount.html">549</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/TextField-mount_base.html">1650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/TextField-mount.html">1662</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ThemeProvider-mount_base.html">1363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ThemeProvider-mount.html">1355</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ThemeProvider-virtual-rerender_base.html">714</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ThemeProvider-virtual-rerender.html">699</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2158</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2148</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Toggle-mount_base.html">972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/Toggle-mount.html">959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/buttonNative-mount_base.html">167</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test/buttonNative-mount.html">174</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: packages/eslint-plugin/src/configs/react.js [hunk 1]
```diff
@@ -9,35 +8,25 @@ const config = {
...
     'react',
     'react-hooks',
   ],
   settings: {
-    // Some config suggestions copied from https://github.com/alexgorbatchev/eslint-import-resolver-typescript#configuration
-    'import/parsers': {
-      '@typescript-eslint/parser': ['.ts', '.tsx'],
-    },
-    'import/resolver': {
-      typescript: {
```
Comment (Hotell) [inline packages/eslint-plugin/src/configs/react.js:34]: this configuration was breaking `import/no-extraneous-dependencies` to work. now that `typescript` plugin is not being used at all and recommended configuration provided by `import` plugin is being used instead.

File: packages/eslint-plugin/src/configs/react.js [hunk 2]
```diff
@@ -9,35 +8,25 @@ const config = {
   extends: [
     // Provides both rules and some parser options and other settings
     'airbnb',
+    // add typescript support for import plugin
+    'plugin:import/typescript',
     // Extended configs are applied in order, so these configs that turn other rules off should come last
     'prettier',
   ],
   parser: '@typescript-eslint/parser',
+  // parserOptions: {},
```
Comment (Hotell) [inline packages/eslint-plugin/src/configs/react.js:17]: remove

File: packages/eslint-plugin/src/configs/react.js [hunk 3]
```diff
@@ -277,6 +253,30 @@ const config = {
...
+      {
+        // Allow TSDoc tags @remarks and @defaultValue
+        definedTags: ['remarks', 'defaultValue'],
+      },
+    ],
+
+    /**
+     *
+     * import plugin rules
+     * @see https://github.com/import-js/eslint-plugin-import
```
Comment (Hotell) [inline packages/eslint-plugin/src/configs/react.js:267]: aggregated all import plugins to one place so its easier to navigate/read

File: packages/react-theme/package.json [hunk 4]
```diff
@@ -27,6 +27,7 @@
   },
   "devDependencies": {
     "@fluentui/eslint-plugin": "*",
+    "@fluentui/react-utilities": "9.0.0-rc.4",
```
Comment (Hotell) [inline packages/react-theme/package.json:30]: `no-extraneous-dependencies` identified lint error (previously hidden because the rule didnt work)

`react-utilities` is being used in a [story file](https://github.com/microsoft/fluentui/blob/master/packages/react-theme/src/themes/ColorRamp.stories.tsx#L9). 

would be great if we could do similar STAR approach like we do for eslint-plugin, for such a scenarios.

File: apps/pr-deploy-site/package.json [hunk 5]
```diff
@@ -12,7 +12,6 @@
   "license": "MIT",
   "devDependencies": {
     "@fluentui/eslint-plugin": "*",
-    "@fluentui/scripts": "^1.0.0",
-    "@microsoft/eslint-plugin-sdl": "0.1.9"
```
Comment (Hotell) [inline apps/pr-deploy-site/package.json:16]: applied single version policy for devDeps

File: package.json [hunk 6]
```diff
@@ -173,7 +174,6 @@
     "eslint": "7.25.0",
     "eslint-config-airbnb": "18.2.1",
     "eslint-config-prettier": "8.3.0",
-    "eslint-import-resolver-typescript": "2.4.0",
```
Comment (Hotell) [inline package.json:176]: plugin not used anymore

File: packages/react-accordion/package.json [hunk 7]
```diff
@@ -44,6 +44,7 @@
   "dependencies": {
     "@fluentui/react-aria": "9.0.0-rc.5",
     "@fluentui/react-context-selector": "9.0.0-rc.5",
+    "@fluentui/react-shared-contexts": "^9.0.0-rc.4",
```
Comment (Hotell) [inline packages/react-accordion/package.json:47]: no caret yet ( because semver pre releases doesn't follow `^` porperly )

File: packages/react-avatar/package.json [hunk 8]
```diff
@@ -46,7 +46,8 @@
     "@fluentui/react-badge": "9.0.0-rc.5",
     "@fluentui/react-icons": "^2.0.159-beta.10",
     "@fluentui/react-theme": "9.0.0-rc.4",
-    "@fluentui/react-utilities": "9.0.0-rc.5",
+    "@fluentui/react-shared-contexts": "^9.0.0-rc.4",
```
Comment (Hotell) [inline packages/react-avatar/package.json:49]: no caret yet ( because semver pre releases doesn't follow `^` properly )

File: packages/react-conformance-griffel/package.json [hunk 9]
```diff
@@ -22,10 +22,10 @@
   },
   "devDependencies": {
     "@fluentui/eslint-plugin": "*",
-    "@fluentui/scripts": "^1.0.0",
-    "@fluentui/react-conformance": "*"
+    "@fluentui/scripts": "^1.0.0"
   },
   "dependencies": {
+    "@fluentui/react-conformance": "^0.10.1",
```
Comment (Hotell) [inline packages/react-conformance-griffel/package.json:28]: todo: create issue to get rid of v8 deps in v9 tree

File: packages/react-portal/package.json [hunk 10]
```diff
@@ -28,6 +28,7 @@
   "devDependencies": {
     "@fluentui/eslint-plugin": "*",
     "@fluentui/react-conformance": "*",
+    "@fluentui/react-theme": "9.0.0-rc.4",
```
Comment (Hotell) [inline packages/react-portal/package.json:31]: remove - not needed anymore

File: packages/react-input/package.json [hunk 11]
```diff
@@ -29,6 +29,7 @@
     "@fluentui/eslint-plugin": "*",
     "@fluentui/react-conformance": "*",
     "@fluentui/react-conformance-griffel": "9.0.0-beta.3",
+    "@fluentui/react-label": "^9.0.0-beta.9",
```
Comment (Hotell) [inline packages/react-input/package.json:32]: remove - not needed anymore

File: packages/react-tabs/package.json [hunk 12]
```diff
@@ -43,6 +43,7 @@
   },
   "dependencies": {
     "@griffel/react": "1.0.0",
+    "@fluentui/react-context-selector": "^9.0.0-rc.5",
```
Comment (Hotell) [inline packages/react-tabs/package.json:46]: no caret yet ( because semver pre releases doesn't follow `^` properly )

File: packages/react-theme/package.json [hunk 13]
```diff
@@ -27,6 +27,7 @@
   },
   "devDependencies": {
     "@fluentui/eslint-plugin": "*",
+    "@fluentui/react-utilities": "9.0.0-rc.5",
```
Comment (Hotell) [inline packages/react-theme/package.json:30]: remove - not needed anymore

File: packages/react-components/src/unstable/tsconfig.json [hunk 14]
```diff
@@ -1,4 +0,0 @@
-{
```
Comment (Hotell) [inline packages/react-components/src/unstable/tsconfig.json:1]: this file is not needed, `unstable` is already in check path of `tsconfig.lib.json`

File: packages/react-conformance-griffel/package.json (hunk 9 above)
Comment (Hotell) [reply packages/react-conformance-griffel/package.json:28]: https://github.com/microsoft/fluentui/issues/21980

File: scripts/tasks/copy.ts [hunk 15]
```diff
@@ -1,8 +1,8 @@
 import * as fs from 'fs';
 import * as path from 'path';
-import { series, resolveCwd, copyTask } from 'just-scripts';
+import { series, resolveCwd, copyTask, copyInstructionsTask, TaskFunction } from 'just-scripts';
 
-export function expandSourcePath(pattern) {
+export function expandSourcePath(pattern: string): string {
```
Comment (Hotell) [inline scripts/tasks/copy.ts:5]: improved types

File: scripts/tasks/copy.ts [hunk 16]
```diff
@@ -31,25 +31,49 @@ export function expandSourcePath(pattern) {
...
-      destination = path.resolve(process.cwd(), destination);
-      tasks.push(
-        copyTask({
-          paths: sources.map(src => expandSourcePath(src)),
-          dest: destination,
-        }),
-      );
+      const destinationPath = path.resolve(process.cwd(), destination);
+
+      if (Array.isArray(sources)) {
```
Comment (Hotell) [inline scripts/tasks/copy.ts:48]: now there is new api: 
- the old one works as before ( value is a array of string paths/globs)
- the new one is `destination` is the path including new file name + value is only string path (copy + rename)

File: packages/react-components/config/pre-copy.json [hunk 17]
```diff
@@ -1,5 +1,5 @@
 {
   "copyTo": {
-    "unstable": ["./src/unstable/package.json"]
+    "unstable/package.json": "./src/unstable/package.json__tmpl__"
```
[the remark this answers is not in the document]
Comment (Hotell) [reply packages/react-components/config/pre-copy.json:3]: package.json is using `tmpl` suffix used by nx, but there are no variables being interpolated within the file. the main purpose of this is so import/no-extreanous won't check this file ( which would trigger lint errors that are invalid )

**Comment by Hotell** [comment]
had great brainstorming with @layershifter today and we wanna add back `'import/resolver#typescript'` for consistency ( althought import plugin will work in our use case as every package is symlinked to root node_modules because yarn workspaces ), thus moving back to draft, please **don't review yet**

File: apps/pr-deploy-site/tsconfig.json [hunk 18]
```diff
@@ -0,0 +1,8 @@
+{
```
Comment (Hotell) [inline apps/pr-deploy-site/tsconfig.json:1]: needed to remove project config fallback to root `tsconfig,json` if tsconfig was missing in project.

this simplifies linting rules and makes our setup unified ( all packages have tsconfig and type-checking on CI )

File: package.json [hunk 19]
```diff
@@ -179,10 +180,10 @@
...
+    "eslint-import-resolver-typescript": "2.5.0",
```
Comment (Hotell) [inline package.json:183]: bumped for bug fixes

File: package.json [hunk 20]
```diff
@@ -179,10 +180,10 @@
...
     "eslint-plugin-deprecation": "1.2.1",
     "eslint-plugin-es": "4.1.0",
-    "eslint-plugin-import": "2.22.1",
+    "eslint-plugin-import": "2.25.4",
```
Comment (Hotell) [inline package.json:186]: bumped to make properly resolve path aliases

File: packages/cra-template/tsconfig.json [hunk 21]
```diff
@@ -0,0 +1,8 @@
+{
+  "extends": "../../scripts/tsconfig.json",
```
Comment (Hotell) [inline packages/cra-template/tsconfig.json:2]: needed to remove project config fallback to root `tsconfig,json` if tsconfig was missing in project.

this simplifies linting rules and makes our setup unified ( all packages have tsconfig and type-checking on CI )

File: packages/eslint-plugin/src/configs/react.js [hunk 22]
```diff
@@ -1,41 +1,36 @@
...
-      '@typescript-eslint/parser': ['.ts', '.tsx'],
-    },
     'import/resolver': {
+      // @see https://github.com/alexgorbatchev/eslint-import-resolver-typescript#configuration
       typescript: {
-        // always try to resolve types under `<root>@types` directory
         alwaysTryTypes: true,
-        // NOTE: For packages without a tsconfig.json, override with "project": "../../tsconfig.json"
-        project: ['./tsconfig.json', path.join(gitRoot, 'tsconfig.json')],
+        project: './tsconfig.json',
```
Comment (Hotell) [inline packages/eslint-plugin/src/configs/react.js:33]: now every package has tsconfig - no magic resolution needs to be used

File: package.json [hunk 23]
```diff
@@ -93,6 +93,7 @@
     "@griffel/webpack-loader": "2.0.0",
     "@linaria/babel-preset": "3.0.0-beta.14",
     "@microsoft/api-extractor": "7.18.1",
+    "@microsoft/eslint-plugin-sdl": "0.1.9",
```
Comment (Hotell) [inline package.json:96]: single version policy

File: yarn.lock [hunk 24]
```diff
@@ -1668,6 +1668,18 @@
     "@uifabric/set-version" "^7.0.23"
     tslib "^1.10.0"
 
+"@fluentui/react-conformance@^0.10.1":
```
Comment (Hotell) [inline yarn.lock:1671]: interesting behaviour why was this added to yarn.lock as it's a monorepo package

Comment (layershifter) [reply yarn.lock:1671]: Version mismatch, we have `0.11.0` while [packages/react-conformance-griffel/package.json](https://github.com/microsoft/fluentui/pull/21924/files/2f63a341f3f73e26e8612763cfac91a30a5c29f7#diff-74639d9196f568828a4067a1db7b52e57adc8490c38abd4a88540b4c497fe68e) has `0.10.1`. This happen because of a recent release.

https://github.com/microsoft/fluentui/blob/f2ecf6614a11aaf38d2d66bb0f61143487b74e6d/packages/react-conformance/package.json#L3

Until we will use [`workspace:` instead of exact versions](https://yarnpkg.com/features/workspaces#publishing-workspaces) it will happen time to time.

Comment (Hotell) [reply yarn.lock:1671]: damn... right I'm not fan of this DX either. but that feature is not supported by midgard-yarn afaik

Comment (layershifter) [reply yarn.lock]: Correct, it was added in Yarn v2, https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#200

I also don't think that `beachball` supports it...

File: change/@fluentui-react-accordion-a88290b3-b03a-40b9-a8cc-d24ab80c5071.json [hunk 25]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
+  "comment": "fixup! fix(react-accordion): fix missing dependencies",
```
Comment (layershifter) [inline change/@fluentui-react-accordion-a88290b3-b03a-40b9-a8cc-d24ab80c5071.json:3]:
```suggestion
  "comment": "add missing dependencies",
```

_nit_ "fixup!" should not be included, right? We also don't include package names as the changelog is grouped anyway

File: change/@fluentui-react-avatar-c63280cc-55c6-4360-aa31-5ced2bd439ae.json [hunk 26]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
+  "comment": "fixup! fix(react-avatar): fix missing dependencies",
```
Comment (layershifter) [inline change/@fluentui-react-avatar-c63280cc-55c6-4360-aa31-5ced2bd439ae.json:3]:
```suggestion
  "comment": "add missing dependencies",
```

File: change/@fluentui-react-conformance-griffel-7dbc04a7-7597-4437-a96b-cbde034b0fe0.json [hunk 27]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
+  "comment": "fix(react-conformance-griffel): add react-conformance missing dependency",
```
Comment (layershifter) [inline change/@fluentui-react-conformance-griffel-7dbc04a7-7597-4437-a96b-cbde034b0fe0.json:3]:
```suggestion
  "comment": "add react-conformance missing dependency",
```

File: change/@fluentui-react-tabs-7eea6ae2-201d-49d4-8749-15add0838235.json [hunk 28]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
+  "comment": "fix(react-tabs): fix missing dependencies and lint warnings",
```
Comment (layershifter) [inline change/@fluentui-react-tabs-7eea6ae2-201d-49d4-8749-15add0838235.json:3]:
```suggestion
  "comment": "fix missing dependencies and lint warnings",
```

File: yarn.lock [hunk 29]
```diff
@@ -11436,7 +11461,26 @@ eslint-plugin-es@^3.0.0:
     eslint-utils "^2.0.0"
     regexpp "^3.0.0"
 
-eslint-plugin-import@2.22.1, eslint-plugin-import@^2.22.1:
+eslint-plugin-import@2.25.4:
```
Comment (layershifter) [inline yarn.lock:11464]: Do you want to dedupe it with the next `eslint-plugin-import`entry?

File: change/@fluentui-react-components-6b800570-deea-41a1-a565-0987a0589347.json [hunk 30]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
```
Comment (layershifter) [inline change/@fluentui-react-components-6b800570-deea-41a1-a565-0987a0589347.json:2]:
```suggestion
  "type": "none",
```

I don't see any changes in production code:

image

Should it be just `none`?

File: change/@fluentui-react-provider-c610d38f-97b5-4686-ab4d-ec59b20d764a.json [hunk 31]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
+  "comment": "fix(react-provider): fix lint issues",
+  "packageName": "@fluentui/react-provider",
+  "email": "martinhochel@microsoft.com",
+  "dependentChangeType": "patch"
+}
```
Comment (layershifter) [inline change/@fluentui-react-provider-c610d38f-97b5-4686-ab4d-ec59b20d764a.json:7]: I don't see any changes in `react-provider`, is this change file relevant? Or can we just delete it?

**Review by layershifter — APPROVED** [review]
Great job, thanks for fixing this ❤️

**Review by GeoffCoxMSFT — APPROVED** [review]

**Comment by spmonahan** [comment]
Look at your example screenshots, should we have a Prettier/eslint rule that merges the two `from "@fluentui/react-utilitites"` lines into a single line?

**Review by spmonahan — APPROVED** [review]

**Review by khmakoto — APPROVED** [review]

**Comment by Hotell** [comment]
> Look at your example screenshots, should we have a Prettier/eslint rule that merges the two `from "@fluentui/react-utilitites"` lines into a single line?

absolutely yes. it is planned (this/next month) to cover these kind of things (also this one https://github.com/microsoft/fluentui/issues/18594)

File: change/@fluentui-react-provider-c610d38f-97b5-4686-ab4d-ec59b20d764a.json (hunk 31 above)
Comment (Hotell) [reply change/@fluentui-react-provider-c610d38f-97b5-4686-ab4d-ec59b20d764a.json:7]: lemme double check, i might missed something as I was tweaking the changes of both plugin setup and actual changes

File: change/@fluentui-react-tabs-7eea6ae2-201d-49d4-8749-15add0838235.json (hunk 28 above)
Comment (Hotell) [reply change/@fluentui-react-tabs-7eea6ae2-201d-49d4-8749-15add0838235.json:3]: right. for more context: I always use conventional commits which also makes it easy to identify what commit belongs to what change-file. I know its redundant in change-log. would be great to have tooling for that in place.

File: change/@fluentui-react-accordion-a88290b3-b03a-40b9-a8cc-d24ab80c5071.json (hunk 25 above)
Comment (Hotell) [reply change/@fluentui-react-accordion-a88290b3-b03a-40b9-a8cc-d24ab80c5071.json:3]: 2x yes ! provided context below

File: yarn.lock (hunk 29 above)
Comment (Hotell) [reply yarn.lock:11464]: absolutely, thx for reminder!

File: change/@fluentui-react-provider-c610d38f-97b5-4686-ab4d-ec59b20d764a.json (hunk 31 above)
Comment (Hotell) [reply change/@fluentui-react-provider-c610d38f-97b5-4686-ab4d-ec59b20d764a.json]: removed, ty!

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/Avatar-mount_base.html">906</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/Avatar-mount.html">914</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/Button-mount_base.html">531</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/Button-mount.html">566</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/FluentProvider-mount_base.html">1958</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/FluentProvider-mount.html">1814</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/FluentProviderWithTheme-mount_base.html">247</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/FluentProviderWithTheme-mount.html">300</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">226</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">241</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">283</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">303</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/MakeStyles-mount_base.html">1547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21924/perf-test-react-components/MakeStyles-mount.html">1564</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: yarn.lock (hunk 29 above)
Comment (Hotell) [reply yarn.lock]: done

**Review by TristanWatanabe — APPROVED** [review]

**Review by andrefcdias — APPROVED** [review]
