### PR TITLE
ComboBox: Fix React.StrictMode issues

### LINKED ISSUE #14288: ComboBox: strict mode compliance (UNSAFE_)
ComboBox updates the following state in `componentWillReceiveProps`:
- `selectedIndices` is reset if `props.selectedKeys` changes. This can also be set elsewhere in the class (incorrect semi-controlled pattern).
- `currentOptions` is reset if `props.options` changes. This can also be set elsewhere in the class if the user types new options.
- `suggestedDisplayValue` is cleared if `props.selectedKey` is newly null, but can be reset elsewhere in the class

It's likely that this would be easier to fix in-place rather than doing a function component conversion due to the overall complexity of the component.

### PR DESCRIPTION
**Pull request by MLoughry**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #14288 
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Partially migrate `ComboBox` to a functional component in order to mitigate React.StrictMode issues.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/react-next/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -104,34 +97,114 @@ interface IComboBoxOptionWrapperProps extends IComboBoxOption {
...
-@customizable('ComboBox', ['theme', 'styles'], true)
-export class ComboBox extends React.Component<IComboBoxProps, IComboBoxState> {
-  public static defaultProps: IComboBoxProps = {
-    options: [],
-    allowFreeform: false,
-    autoComplete: 'on',
-    buttonIconProps: { iconName: 'ChevronDown' },
-  };
+  React.useEffect(() => {
+    if (defaultSelectedKey === undefined) {
```
Comment (ecraig12345) [inline packages/react-next/src/components/ComboBox/ComboBox.tsx:133]: What's the intent of this check? If it's to check for controlled or uncontrolled, it would be better to check `selectedKeys !== undefined` since the controlled prop should always take precedence (even if they incorrectly provide both).

File: packages/react-next/src/components/ComboBox/ComboBox.tsx [hunk 2]
```diff
@@ -104,34 +97,114 @@ interface IComboBoxOptionWrapperProps extends IComboBoxOption {
...
+      setSelectedIndices(indices);
+    }
+    setCurrentOptions(options);
+  }, [defaultSelectedKey, options, selectedKey]);
+
+  React.useEffect(() => {
+    if (selectedKey === null) {
+      setSuggestedDisplayValue(undefined);
+    }
+  }, [selectedKey]);
```
Comment (ecraig12345) [inline packages/react-next/src/components/ComboBox/ComboBox.tsx:146]: To replicate the previous conditions where this was called, I think you'd need to add `text` and `options` to the dependencies. Though I'm not sure if it will matter.

File: packages/react-next/src/components/ComboBox/ComboBox.tsx [hunk 3]
```diff
@@ -1012,23 +1064,18 @@ export class ComboBox extends React.Component<IComboBoxProps, IComboBoxState> {
...
-            if (onChange) {
-              onChange(submitPendingValueEvent, option, index, undefined);
-            }
-          },
-        );
+        this.props.hoisted.setSelectedIndices(selectedIndices);
+        this.props.hoisted.setCurrentOptions(changedOptions);
+
+        // If ComboBox value is changed, revert preview first
+        if (this._hasPendingValue && onPendingValueChanged) {
```
Comment (ecraig12345) [inline packages/react-next/src/components/ComboBox/ComboBox.tsx:1071]: Similar to Dropdown this is potentially a behavior change since you're now calling onPendingValueChanged and onChange immediately after the setters, instead of in the post-`setState` callback.

**Review by joschect — APPROVED** [review]
