### PR TITLE
CI: Fix unhandled promise rejection in prettier

### LINKED ISSUE #14632: CI: should run Prettier to detect formatting issues
Currently there is no job that will run prettier formatting in CI. 

This allows files with broken formatting (as an example https://github.com/microsoft/fluentui/pull/14625) to pass CI checks and then these changes will come to `master`. Once anyone will merge with `master` there will be unrelated formatting changes (https://github.com/microsoft/fluentui/pull/14441#discussion_r467878616).

### PR DESCRIPTION
**Pull request by ling1726**
Fixes #14632.

Prettier used to swallow unhandled promise rejections and would always pass CI. Now the promise rejections are caught so CI will fail appropriately for prettier.

Also includes a fix for Windows, since `git diff` will always return unix line endings.

[Failing build for reference](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=187985&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=072a33dd-3583-57e6-ff95-c892c0923c97)

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Review by Hotell — APPROVED** [review]

**Comment by Hotell** [comment]
> Prettier used to swallow unhandled promise rejections and would always
pass CI

Note: not prettier rather than our custom abstraction. thx!

**Review by layershifter — APPROVED** [review]

File: scripts/prettier.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ async function runOnChanged(options) {
   const prettierExtRegex = new RegExp(`\\.(${prettierExtensions.join('|')})$`);
   const files = gitDiffOutput
     .toString('utf8')
-    .split(os.EOL)
+    .split('\n')
```
Comment (layershifter) [inline scripts/prettier.js:76]: Just to double mention, `git diff` uses `\n` on Windows, too.

Sample output:
```bash
    'packages/react-examples/src/react-menu/MenuList/MenuList.stories.tsx\n' +
    'packages/react-menu/etc/react-menu.api.md\n' +
    'packages/react-menu/package.json\n' +
    'packages/react-menu/src/MenuDivider.ts\n' +
    'packages/react-menu/src/MenuGroup.ts\n' +

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Avatar-mount_base.html">843</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Avatar-mount.html">817</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/BaseButton-mount_base.html">979</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/BaseButton-mount.html">980</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Breadcrumb-mount_base.html">41584</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Breadcrumb-mount.html">41757</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ButtonNext-mount_base.html">730</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ButtonNext-mount.html">709</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Checkbox-mount_base.html">1551</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Checkbox-mount.html">1597</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/CheckboxBase-mount_base.html">1318</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/CheckboxBase-mount.html">1343</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ChoiceGroup-mount_base.html">4912</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ChoiceGroup-mount.html">5056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ComboBox-mount_base.html">1020</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ComboBox-mount.html">983</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/CommandBar-mount_base.html">10224</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/CommandBar-mount.html">10000</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ContextualMenu-mount_base.html">6127</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ContextualMenu-mount.html">6113</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DefaultButton-mount_base.html">1168</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DefaultButton-mount.html">1151</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DetailsRow-mount_base.html">3783</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DetailsRow-mount.html">3715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DetailsRowFast-mount_base.html">3735</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DetailsRowFast-mount.html">3715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DetailsRowNoStyles-mount_base.html">3493</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DetailsRowNoStyles-mount.html">3556</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Dialog-mount_base.html">1495</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Dialog-mount.html">1523</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DocumentCardTitle-mount_base.html">1795</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/DocumentCardTitle-mount.html">1830</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Dropdown-mount_base.html">3391</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Dropdown-mount.html">3382</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/FocusTrapZone-mount_base.html">1898</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/FocusTrapZone-mount.html">1811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/FocusZone-mount_base.html">1857</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/FocusZone-mount.html">1808</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/IconButton-mount_base.html">1831</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/IconButton-mount.html">1851</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Label-mount_base.html">329</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Label-mount.html">319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Layer-mount_base.html">1843</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Layer-mount.html">1817</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Link-mount_base.html">453</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Link-mount.html">479</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/MakeStyles-mount_base.html">1995</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/MakeStyles-mount.html">1952</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/MenuButton-mount_base.html">1555</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/MenuButton-mount.html">1556</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/MessageBar-mount_base.html">1959</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/MessageBar-mount.html">1979</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Nav-mount_base.html">3407</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Nav-mount.html">3334</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/OverflowSet-mount_base.html">1047</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/OverflowSet-mount.html">1056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Panel-mount_base.html">1476</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Panel-mount.html">1435</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Persona-mount_base.html">842</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Persona-mount.html">837</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Pivot-mount_base.html">1462</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Pivot-mount.html">1450</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/PrimaryButton-mount_base.html">1371</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/PrimaryButton-mount.html">1351</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Rating-mount_base.html">7822</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Rating-mount.html">7985</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/SearchBox-mount_base.html">1384</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/SearchBox-mount.html">1357</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Shimmer-mount_base.html">2645</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Shimmer-mount.html">2590</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Slider-mount_base.html">1973</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Slider-mount.html">2026</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/SpinButton-mount_base.html">5156</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/SpinButton-mount.html">5138</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Spinner-mount_base.html">401</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Spinner-mount.html">434</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/SplitButton-mount_base.html">3272</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/SplitButton-mount.html">3283</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Stack-mount_base.html">518</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Stack-mount.html">526</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1661</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/StackWithIntrinsicChildren-mount.html">1573</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/StackWithTextChildren-mount_base.html">4792</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/StackWithTextChildren-mount.html">4834</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/SwatchColorPicker-mount_base.html">10639</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/SwatchColorPicker-mount.html">10550</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Tabs-mount_base.html">1427</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Tabs-mount.html">1431</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/TagPicker-mount_base.html">2851</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/TagPicker-mount.html">2887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/TeachingBubble-mount_base.html">11652</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/TeachingBubble-mount.html">11831</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Text-mount_base.html">428</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Text-mount.html">420</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/TextField-mount_base.html">1418</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/TextField-mount.html">1439</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ThemeProvider-mount_base.html">1185</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ThemeProvider-mount.html">1206</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ThemeProvider-virtual-rerender_base.html">596</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ThemeProvider-virtual-rerender.html">592</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ThemeProviderNext-mount_base.html">1962</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/ThemeProviderNext-mount.html">1971</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Toggle-mount_base.html">831</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/Toggle-mount.html">838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/buttonNative-mount_base.html">121</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test/buttonNative-mount.html">110</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.19](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Avatar.Fluent.html) | 0.49 | 0.39:1 | 2000 | 382
🦄 | Button.Fluent | [0.13](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Button.Fluent.html) | 0.21 | 0.62:1 | 5000 | 631
🔧 | Checkbox.Fluent | [0.67](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Checkbox.Fluent.html) | 0.37 | 1.81:1 | 1000 | 671
🎯 | Dialog.Fluent | [0.17](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Dialog.Fluent.html) | 0.22 | 0.77:1 | 5000 | 836
🔧 | Dropdown.Fluent | [3.22](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Dropdown.Fluent.html) | 0.44 | 7.32:1 | 1000 | 3223
🔧 | Icon.Fluent | [0.16](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Icon.Fluent.html) | 0.07 | 2.29:1 | 5000 | 783
🦄 | Image.Fluent | [0.09](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Image.Fluent.html) | 0.14 | 0.64:1 | 5000 | 449
🔧 | Slider.Fluent | [1.62](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Slider.Fluent.html) | 0.45 | 3.6:1 | 1000 | 1619
🔧 | Text.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.67:1 | 5000 | 407
🦄 | Tooltip.Fluent | [0.12](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Tooltip.Fluent.html) | 0.92 | 0.13:1 | 5000 | 593
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
PortalMinimalPerf.default | [176](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/PortalMinimalPerf.default.html) | [162](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.09:1
SkeletonMinimalPerf.default | [447](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/SkeletonMinimalPerf.default.html) | [410](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.09:1
BoxMinimalPerf.default | [425](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/BoxMinimalPerf.default.html) | [394](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.08:1
Icon.Fluent | [783](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Icon.Fluent.html) | [723](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Icon.Fluent_base.html) | 1.08:1
ImageMinimalPerf.default | [472](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ImageMinimalPerf.default.html) | [442](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.07:1
RadioGroupMinimalPerf.default | [508](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [475](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.07:1
TextMinimalPerf.default | [404](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TextMinimalPerf.default.html) | [379](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.07:1
AvatarMinimalPerf.default | [226](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AvatarMinimalPerf.default.html) | [213](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.06:1
ButtonSlotsPerf.default | [667](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonSlotsPerf.default.html) | [629](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.06:1
ChatDuplicateMessagesPerf.default | [400](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [378](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.06:1
DropdownManyItemsPerf.default | [827](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DropdownManyItemsPerf.default.html) | [781](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.06:1
FlexMinimalPerf.default | [345](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/FlexMinimalPerf.default.html) | [326](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.06:1
FormMinimalPerf.default | [512](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/FormMinimalPerf.default.html) | [486](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.05:1
GridMinimalPerf.default | [399](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/GridMinimalPerf.default.html) | [381](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.05:1
ItemLayoutMinimalPerf.default | [1376](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1313](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.05:1
ListNestedPerf.default | [665](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ListNestedPerf.default.html) | [632](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ListNestedPerf.default_base.html) | 1.05:1
MenuButtonMinimalPerf.default | [1725](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1640](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.05:1
IconMinimalPerf.default | [752](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/IconMinimalPerf.default.html) | [715](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.05:1
ChatMinimalPerf.default | [704](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ChatMinimalPerf.default.html) | [675](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.04:1
HeaderSlotsPerf.default | [897](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/HeaderSlotsPerf.default.html) | [865](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.04:1
LoaderMinimalPerf.default | [792](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/LoaderMinimalPerf.default.html) | [758](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [551](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TextAreaMinimalPerf.default.html) | [531](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
Avatar.Fluent | [382](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Avatar.Fluent.html) | [366](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Avatar.Fluent_base.html) | 1.04:1
Image.Fluent | [449](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Image.Fluent.html) | [431](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Image.Fluent_base.html) | 1.04:1
AnimationMinimalPerf.default | [465](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AnimationMinimalPerf.default.html) | [450](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.03:1
CheckboxMinimalPerf.default | [2970](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2883](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.03:1
ListCommonPerf.default | [745](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ListCommonPerf.default.html) | [726](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ListCommonPerf.default_base.html) | 1.03:1
ListWith60ListItems.default | [698](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ListWith60ListItems.default.html) | [675](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.03:1
StatusMinimalPerf.default | [840](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/StatusMinimalPerf.default.html) | [813](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.03:1
TreeMinimalPerf.default | [870](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TreeMinimalPerf.default.html) | [847](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.03:1
CardMinimalPerf.default | [628](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/CardMinimalPerf.default.html) | [618](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [865](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DialogMinimalPerf.default.html) | [845](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [4035](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3969](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
VideoMinimalPerf.default | [730](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/VideoMinimalPerf.default.html) | [717](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [854](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TooltipMinimalPerf.default.html) | [844](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
Checkbox.Fluent | [671](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Checkbox.Fluent.html) | [663](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Checkbox.Fluent_base.html) | 1.01:1
Dropdown.Fluent | [3223](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Dropdown.Fluent.html) | [3177](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Dropdown.Fluent_base.html) | 1.01:1
AttachmentSlotsPerf.default | [1280](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1283](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1772](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1770](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
ChatWithPopoverPerf.default | [465](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ChatWithPopoverPerf.default.html) | [463](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [48692](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DatepickerMinimalPerf.default.html) | [48720](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
DividerMinimalPerf.default | [414](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DividerMinimalPerf.default.html) | [415](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1:1
HeaderMinimalPerf.default | [422](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/HeaderMinimalPerf.default.html) | [423](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
InputMinimalPerf.default | [1336](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/InputMinimalPerf.default.html) | [1339](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/InputMinimalPerf.default_base.html) | 1:1
ListMinimalPerf.default | [572](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ListMinimalPerf.default.html) | [571](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
MenuMinimalPerf.default | [958](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/MenuMinimalPerf.default.html) | [960](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [730](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/PopupMinimalPerf.default.html) | [733](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ReactionMinimalPerf.default | [457](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ReactionMinimalPerf.default.html) | [456](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1:1
TableManyItemsPerf.default | [2267](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TableManyItemsPerf.default.html) | [2256](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3805](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/CustomToolbarPrototype.default.html) | [3791](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
Button.Fluent | [631](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Button.Fluent.html) | [628](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Button.Fluent_base.html) | 1:1
AttachmentMinimalPerf.default | [181](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AttachmentMinimalPerf.default.html) | [183](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [3093](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DropdownMinimalPerf.default.html) | [3115](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [4381](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/EmbedMinimalPerf.default.html) | [4422](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
LayoutMinimalPerf.default | [467](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/LayoutMinimalPerf.default.html) | [470](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.99:1
ProviderMinimalPerf.default | [981](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ProviderMinimalPerf.default.html) | [989](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.99:1
ToolbarMinimalPerf.default | [1029](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1039](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.99:1
Text.Fluent | [407](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Text.Fluent.html) | [412](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Text.Fluent_base.html) | 0.99:1
ButtonMinimalPerf.default | [206](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonMinimalPerf.default.html) | [211](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.98:1
ButtonUseCssNestingPerf.default | [1145](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1171](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 0.98:1
LabelMinimalPerf.default | [472](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/LabelMinimalPerf.default.html) | [480](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.98:1
RefMinimalPerf.default | [240](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/RefMinimalPerf.default.html) | [244](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.98:1
Dialog.Fluent | [836](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Dialog.Fluent.html) | [850](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Dialog.Fluent_base.html) | 0.98:1
ButtonUseCssPerf.default | [875](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonUseCssPerf.default.html) | [898](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 0.97:1
CarouselMinimalPerf.default | [517](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/CarouselMinimalPerf.default.html) | [531](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.97:1
RosterPerf.default | [1277](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/RosterPerf.default.html) | [1316](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/RosterPerf.default_base.html) | 0.97:1
TableMinimalPerf.default | [451](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TableMinimalPerf.default.html) | [463](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.97:1
Slider.Fluent | [1619](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Slider.Fluent.html) | [1673](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Slider.Fluent_base.html) | 0.97:1
Tooltip.Fluent | [593](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Tooltip.Fluent.html) | [613](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/Tooltip.Fluent_base.html) | 0.97:1
ProviderMergeThemesPerf.default | [1559](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1627](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.96:1
SliderMinimalPerf.default | [1557](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/SliderMinimalPerf.default.html) | [1622](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.96:1
AccordionMinimalPerf.default | [166](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AccordionMinimalPerf.default.html) | [175](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.95:1
AlertMinimalPerf.default | [333](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AlertMinimalPerf.default.html) | [350](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.95:1
TreeWith60ListItems.default | [195](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TreeWith60ListItems.default.html) | [212](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.92:1
SegmentMinimalPerf.default | [396](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/SegmentMinimalPerf.default.html) | [436](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17009/merge/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.91:1

</details><div id="perfComment9423"/>

File: scripts/prettier.js [hunk 2]
```diff
@@ -29,9 +29,9 @@ async function main() {
   const queue = new PQueue({ concurrency: numberOfCpus });
 
   if (runOnAllFiles) {
-    runOnAll({ queue, paths });
+    await runOnAll({ queue, paths });
   } else {
-    runOnChanged({ queue, paths });
+    await runOnChanged({ queue, paths });
```
Comment (layershifter) [inline scripts/prettier.js:34]: Webstorm warns about await

_Unpaid Webstorm promotion_
