### PR TITLE
fix(react-utilities): adjust IntrinsicElementProps type to properly support void elements

### LINKED ISSUE #27092: Can't use children render function with `image` slot in `Avatar` without typescript error
https://codesandbox.io/s/intelligent-nobel-85byl1?file=/example.tsx

If users want to override the image slot (in this case with an svg image element) they can use the children render function, but triggers a typescript error since the `children` prop of `Image` is typed to `never`.

I think it's caused by a conflict with this utility type

https://github.com/microsoft/fluentui/blob/290bf3854d0bf63135b99531162fff7e98d2baa4/packages/react-components/react-utilities/src/compose/types.ts#L72-L73

### PR DESCRIPTION
**Pull request by bsunderhus**
## Previous Behavior

To disable the usage of `children` as a property on [Void Elements](https://developer.mozilla.org/en-US/docs/Glossary/Void_element) our internal typings would mark `children` as `never`. This would work for the normal use cases of `children` and errors would pop if you tried using `children`, as expected:

image

When supporting slot API, `children` can receive a render function as value to allow the case of [Replacing the entire slot](https://react.fluentui.dev/?path=/docs/concepts-developer-customizing-components-with-slots--page#replacing-the-entire-slot). This is currently broken as void elements `children` props are marked as `never`:

image

## New Behavior

Instead of marking `children` as never, filtering the original children value out of the types solves this problem, allowing the slot API and properly emitting an error on any other cases:

image

image

1. filters children out instead of using `never`
2. fix typo on `IntrinsicElement` types

## Related Issue(s)

- Fixes #27092

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4d536a76b414c5135713127ce707f8676db13fd8'>4d536a76b414c5135713127ce707f8676db13fd8</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/Avatar-mount_base.html">1302</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/Avatar-mount.html">1293</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/Button-mount_base.html">927</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/Button-mount.html">929</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/Field-mount_base.html">1923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/Field-mount.html">1922</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/FluentProvider-mount_base.html">1546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/FluentProvider-mount.html">1559</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/FluentProviderWithTheme-mount_base.html">578</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/FluentProviderWithTheme-mount.html">583</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">555</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">591</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">584</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/InfoButton-mount_base.html">512</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/InfoButton-mount.html">516</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/MakeStyles-mount_base.html">1955</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/MakeStyles-mount.html">1961</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/Persona-mount_base.html">2854</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/Persona-mount.html">2825</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/SpinButton-mount_base.html">2308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/27095/perf-test-react-components/SpinButton-mount.html">2270</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-utilities/src/compose/types.ts [hunk 1]
```diff
@@ -39,16 +39,16 @@ type WithSlotShorthandValue<Props extends { children?: unknown }> =
  * Helper type for {@link Slot}. Takes the props we want to support for a slot and adds the ability for `children`
  * to be a render function that takes those props.
  */
-type WithSlotRenderFunction<Props extends { children?: unknown }> = Props & {
-  children?: Props['children'] | SlotRenderFunction<Props>;
+type WithSlotRenderFunction<Props> = Props & {
```
Comment (ling1726) [inline packages/react-components/react-utilities/src/compose/types.ts:42]: @behowell  as the original author of these types, would you be able to take a look?

Comment (behowell) [reply packages/react-components/react-utilities/src/compose/types.ts:42]: Thanks for adding me--looks good!

**Review by behowell — APPROVED** [review]

**Review by ling1726 — APPROVED** [review]
