### PR TITLE
fix(MenuButton): stop propagation avoiding navigating between cells

### LINKED ISSUE #18067: User can navigate from MenuButton inside of a table cell to other cells without closing the menu
### Environment Information

- **Package version(s)**: 0.54
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/fluent-ui-example-forked-836py?file=/example.js
(without usage of ignoreArrowKeys)

#### Actual behavior:

When menu is open, user can navigate to other cells by pressing left/right arrow keys
#### Expected behavior:

Left/right arrows do not have any effect (unless there is a submenu)

### Priorities and help requested:

Are you willing to submit a PR to fix?

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #18067
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Prevents navigation to cell when navigating in submenu inside table

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/components/MenuButton/MenuButton.tsx [hunk 1]
```diff
@@ -239,6 +239,12 @@ export const MenuButton: ComponentWithAs<'div', MenuButtonProps> &
         handleOpenChange(e, false);
       }
     },
+    onKeyDown: (e: React.KeyboardEvent, itemProps: MenuItemProps) => {
+      _.invoke(predefinedProps, 'onKeyDown', e, itemProps);
+      if (e.key === 'ArrowLeft' || e.key === 'ArrowLeft') {
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/MenuButton/MenuButton.tsx:244]:
```suggestion
      if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
```

A typo?

**Review by layershifter — APPROVED** [review]
