### PR TITLE
Fixed bug where className changes in List props does not cause a rerender

### LINKED ISSUE #23125: [Bug]: List doesn't react to
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 25.29 GB / 48.00 GB
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.47)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/odhanson/pen/ExQvKrO

## Repro
In attached pen example, press the toggle button to change border color from black to red

## Actual Behavior
When changing the className property of the list control, the component does not render and update. Only after typing some text into the filter, which causes a rerender, does the style update.

## Expected Behavior
When changing the className property of the list control, the component should render and update immediately.

Looking at the code, it seems like the shouldComponentUpdate is not checking for changes in style or className properties and thus does not update: https://github.com/microsoft/fluentui/blob/fbed857eb218943dcd08686eca1f469314bb84f6/packages/react/src/components/List/List.tsx#L392

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

Excel

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by odhanson**
## Current Behavior

List component doesn't update when className property changes.

## New Behavior

List component updates when className property changes.

## Related Issue(s)

Fixes #23125

### CODE REVIEW

**Comment by odhanson** [comment]
I wasn't sure how to write a test for this change. If you have some examples I can follow, I will add a test.

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/fbed857eb218943dcd08686eca1f469314bb84f6'>fbed857eb218943dcd08686eca1f469314bb84f6</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/BaseButton-mount_base.html">732</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/BaseButton-mount.html">788</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Breadcrumb-mount_base.html">2328</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Breadcrumb-mount.html">2377</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Checkbox-mount_base.html">1229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Checkbox-mount.html">1221</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/CheckboxBase-mount_base.html">1072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/CheckboxBase-mount.html">1008</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ChoiceGroup-mount_base.html">3718</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ChoiceGroup-mount.html">3790</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ComboBox-mount_base.html">825</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ComboBox-mount.html">838</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/CommandBar-mount_base.html">8967</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/CommandBar-mount.html">8937</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ContextualMenu-mount_base.html">9870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ContextualMenu-mount.html">9543</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DefaultButton-mount_base.html">986</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DefaultButton-mount.html">981</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DetailsRow-mount_base.html">3163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DetailsRow-mount.html">3341</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DetailsRowFast-mount_base.html">3236</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DetailsRowFast-mount.html">3276</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DetailsRowNoStyles-mount_base.html">3100</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DetailsRowNoStyles-mount.html">3116</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Dialog-mount_base.html">1928</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Dialog-mount.html">1958</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DocumentCardTitle-mount_base.html">156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/DocumentCardTitle-mount.html">142</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Dropdown-mount_base.html">2816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Dropdown-mount.html">2816</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/FocusTrapZone-mount_base.html">1610</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/FocusTrapZone-mount.html">1591</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/FocusZone-mount_base.html">1512</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/FocusZone-mount.html">1559</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/IconButton-mount_base.html">1468</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/IconButton-mount.html">1493</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Label-mount_base.html">290</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Label-mount.html">300</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Layer-mount_base.html">2535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Layer-mount.html">2509</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Link-mount_base.html">397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Link-mount.html">382</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/MenuButton-mount_base.html">1205</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/MenuButton-mount.html">1271</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/MessageBar-mount_base.html">1698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/MessageBar-mount.html">1719</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Nav-mount_base.html">2862</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Nav-mount.html">2893</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/OverflowSet-mount_base.html">933</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/OverflowSet-mount.html">912</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Panel-mount_base.html">1893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Panel-mount.html">1874</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Persona-mount_base.html">889</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Persona-mount.html">799</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Pivot-mount_base.html">1266</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Pivot-mount.html">1256</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/PrimaryButton-mount_base.html">1094</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/PrimaryButton-mount.html">996</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Rating-mount_base.html">6581</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Rating-mount.html">6568</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/SearchBox-mount_base.html">1097</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/SearchBox-mount.html">1067</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Shimmer-mount_base.html">2146</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Shimmer-mount.html">1936</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Slider-mount_base.html">1650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Slider-mount.html">1661</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/SpinButton-mount_base.html">3979</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/SpinButton-mount.html">4177</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Spinner-mount_base.html">323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Spinner-mount.html">385</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/SplitButton-mount_base.html">2678</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/SplitButton-mount.html">2697</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Stack-mount_base.html">451</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Stack-mount.html">433</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/StackWithIntrinsicChildren-mount_base.html">1843</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/StackWithIntrinsicChildren-mount.html">1905</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/StackWithTextChildren-mount_base.html">4492</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/StackWithTextChildren-mount.html">4430</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/SwatchColorPicker-mount_base.html">9792</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/SwatchColorPicker-mount.html">9750</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/TagPicker-mount_base.html">2324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/TagPicker-mount.html">2361</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/TeachingBubble-mount_base.html">78531</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/TeachingBubble-mount.html">80882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Text-mount_base.html">324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Text-mount.html">364</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/TextField-mount_base.html">1089</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/TextField-mount.html">1167</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ThemeProvider-mount_base.html">1015</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ThemeProvider-mount.html">1005</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ThemeProvider-virtual-rerender_base.html">560</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ThemeProvider-virtual-rerender.html">490</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1538</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Toggle-mount_base.html">656</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/Toggle-mount.html">683</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/buttonNative-mount_base.html">106</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23126/perf-test/buttonNative-mount.html">114</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: packages/react/src/components/List/List.tsx [hunk 1]
```diff
@@ -403,6 +403,10 @@ export class List<T = any> extends React.Component<IListProps<T>, IListState<T>>
       return true;
     }
 
+    if (newProps.className !== this.props.className) {
```
Comment (spmonahan) [inline packages/react/src/components/List/List.tsx:406]: Would you please add a new test or a new assertion to this [className test](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/List/List.test.tsx#L174) to verify this fix?

Comment (odhanson) [reply packages/react/src/components/List/List.tsx:406]: Done. I updated existing test, which actually was verifying the className being updated, but because it also changed the items, the list would rerender. Now this test fails without my fix.

**Review by spmonahan — APPROVED** [review]

**Comment by odhanson** [comment]
@spmonahan @ThomasMichon can we complete this change ?

**Comment by spmonahan** [comment]
@odhanson Merged! Thank you for the contribution to Fluent UI!
