### PR TITLE
fix(Popup): update offsets computations

### LINKED ISSUE #13003: Popup: pointers broken in Fluent v0
1. Open maximized example locally: http://localhost:8080/maximize/popup-example-pointer-margin-shorthand/false
2. Mention that all pointers are broken.

### Environment Information

- **Package version(s)**: `master`

#### Actual behavior:

image

#### Expected behavior:

image

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: Blocking

### PR DESCRIPTION
**Pull request by layershifter**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #13003

#### Description of changes

In #12577 I fixed sizes of pointers, but during Popper update (#12530) I missed this update. I checked the issue and we should include `padding` when we are computing offsets. It's annoying that Screener can't catch such issues 👎 

### Before

image

### After

image
image

(with `pointerMargin: pxToRem(20)`)

image
image

(with `pointerMargin: pxToRem(30)`)

image
image

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui/pull/13002)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/themes/teams/components/Popup/popupContentStyles.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ const popupContentStyles: ComponentSlotStylesPrepared<PopupContentStylesProps, P
       pointerEvents: 'none',
       ...getContainerStyles({
         placement: p.basePlacement,
-        margin: v.pointerMargin,
+        padding: v.pointerMargin,
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/themes/teams/components/Popup/popupContentStyles.ts:16]: It's actually padding. Decided to keep variable's name to avoid breaking changes
