### PR TITLE
fix(Dialog): remove touch event prevent default

### LINKED ISSUE #16530: Fluent UI - React Northstar. Dialog component doesn't support scroll on touch event
### Environment Information

- @fluentui/react-northstar - 0.51.2
- Google Chrome Version 86.0.4240.183

### Please provide a reproduction of the bug in a codepen:

Cannot scroll content inside dialog on mobile devices. `touchmove` event fires but `scroll` event doesn't fire for some reason.
https://codesandbox.io/s/stoic-moore-nxvjx?file=/src/index.tsx

#### Actual behavior:

Cannot scroll content inside dialog on mobile device

#### Expected behavior:

Can scroll content inside dialog on mobile device

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #16530
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

We din't implemented the solution using `body-scroll-lock` package before because it didn't worked on IE11, we are not currently supporting IE11 for north* components anymore, this solution fixes the bug #16530 and keeps current behavior

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Avatar-mount_base.html">1081</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Avatar-mount.html">1078</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/BaseButton-mount_base.html">894</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/BaseButton-mount.html">863</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Breadcrumb-mount_base.html">43762</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Breadcrumb-mount.html">43515</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ButtonNext-mount_base.html">695</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ButtonNext-mount.html">695</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Checkbox-mount_base.html">1517</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Checkbox-mount.html">1504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/CheckboxBase-mount_base.html">1236</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/CheckboxBase-mount.html">1238</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ChoiceGroup-mount_base.html">4836</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ChoiceGroup-mount.html">4702</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ComboBox-mount_base.html">989</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ComboBox-mount.html">1016</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/CommandBar-mount_base.html">10075</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/CommandBar-mount.html">10142</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ContextualMenu-mount_base.html">6177</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ContextualMenu-mount.html">6196</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DefaultButton-mount_base.html">1100</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DefaultButton-mount.html">1097</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DetailsRow-mount_base.html">3611</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DetailsRow-mount.html">3585</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DetailsRowFast-mount_base.html">3592</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DetailsRowFast-mount.html">3548</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DetailsRowNoStyles-mount_base.html">3426</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DetailsRowNoStyles-mount.html">3430</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Dialog-mount_base.html">1459</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Dialog-mount.html">1472</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DocumentCardTitle-mount_base.html">1823</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/DocumentCardTitle-mount.html">1817</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Dropdown-mount_base.html">3266</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Dropdown-mount.html">3313</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/FocusTrapZone-mount_base.html">1773</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/FocusTrapZone-mount.html">1802</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/FocusZone-mount_base.html">1818</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/FocusZone-mount.html">1830</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/IconButton-mount_base.html">1733</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/IconButton-mount.html">1736</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Label-mount_base.html">342</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Label-mount.html">330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Layer-mount_base.html">1745</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Layer-mount.html">1756</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Link-mount_base.html">454</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Link-mount.html">468</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/MakeStyles-mount_base.html">2017</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/MakeStyles-mount.html">1956</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/MenuButton-mount_base.html">1449</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/MenuButton-mount.html">1438</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/MessageBar-mount_base.html">2022</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/MessageBar-mount.html">1981</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Nav-mount_base.html">3219</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Nav-mount.html">3164</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/OverflowSet-mount_base.html">1033</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/OverflowSet-mount.html">1035</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Panel-mount_base.html">1434</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Panel-mount.html">1418</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Persona-mount_base.html">825</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Persona-mount.html">835</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Pivot-mount_base.html">1372</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Pivot-mount.html">1394</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/PrimaryButton-mount_base.html">1238</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/PrimaryButton-mount.html">1258</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Rating-mount_base.html">7407</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Rating-mount.html">7308</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/SearchBox-mount_base.html">1333</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/SearchBox-mount.html">1305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Shimmer-mount_base.html">2458</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Shimmer-mount.html">2532</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Slider-mount_base.html">1839</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Slider-mount.html">1832</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/SpinButton-mount_base.html">4864</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/SpinButton-mount.html">4898</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Spinner-mount_base.html">420</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Spinner-mount.html">414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/SplitButton-mount_base.html">3168</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/SplitButton-mount.html">3115</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Stack-mount_base.html">509</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Stack-mount.html">477</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1538</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/StackWithIntrinsicChildren-mount.html">1534</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/StackWithTextChildren-mount_base.html">4382</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/StackWithTextChildren-mount.html">4446</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/SwatchColorPicker-mount_base.html">10062</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/SwatchColorPicker-mount.html">9846</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Tabs-mount_base.html">1350</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Tabs-mount.html">1367</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/TagPicker-mount_base.html">2828</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/TagPicker-mount.html">2738</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/TeachingBubble-mount_base.html">11450</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/TeachingBubble-mount.html">11618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Text-mount_base.html">396</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Text-mount.html">425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/TextField-mount_base.html">1332</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/TextField-mount.html">1394</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ThemeProvider-mount_base.html">1198</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ThemeProvider-mount.html">1203</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ThemeProvider-virtual-rerender_base.html">602</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ThemeProvider-virtual-rerender.html">601</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ThemeProviderNext-mount_base.html">1994</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/ThemeProviderNext-mount.html">1987</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Toggle-mount_base.html">812</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/Toggle-mount.html">811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/buttonNative-mount_base.html">100</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test/buttonNative-mount.html">112</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.17](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Avatar.Fluent.html) | 0.47 | 0.36:1 | 2000 | 331
🦄 | Button.Fluent | [0.12](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Button.Fluent.html) | 0.19 | 0.63:1 | 5000 | 585
🔧 | Checkbox.Fluent | [0.65](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Checkbox.Fluent.html) | 0.32 | 2.03:1 | 1000 | 647
🎯 | Dialog.Fluent | [0.16](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Dialog.Fluent.html) | 0.21 | 0.76:1 | 5000 | 786
🔧 | Dropdown.Fluent | [3.04](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Dropdown.Fluent.html) | 0.39 | 7.79:1 | 1000 | 3044
🔧 | Icon.Fluent | [0.15](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Icon.Fluent.html) | 0.06 | 2.5:1 | 5000 | 729
🦄 | Image.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Image.Fluent.html) | 0.12 | 0.67:1 | 5000 | 388
🔧 | Slider.Fluent | [1.59](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Slider.Fluent.html) | 0.43 | 3.7:1 | 1000 | 1592
🔧 | Text.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.67:1 | 5000 | 380
🦄 | Tooltip.Fluent | [0.11](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Tooltip.Fluent.html) | 0.86 | 0.13:1 | 5000 | 549
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
VideoMinimalPerf.default | [682](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/VideoMinimalPerf.default.html) | [613](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.11:1
AttachmentMinimalPerf.default | [177](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AttachmentMinimalPerf.default.html) | [164](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.08:1
RadioGroupMinimalPerf.default | [471](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [446](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.06:1
Icon.Fluent | [729](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Icon.Fluent.html) | [686](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Icon.Fluent_base.html) | 1.06:1
Text.Fluent | [380](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Text.Fluent.html) | [357](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Text.Fluent_base.html) | 1.06:1
AvatarMinimalPerf.default | [210](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AvatarMinimalPerf.default.html) | [200](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.05:1
FormMinimalPerf.default | [436](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/FormMinimalPerf.default.html) | [415](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.05:1
SliderMinimalPerf.default | [1613](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/SliderMinimalPerf.default.html) | [1539](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.05:1
LayoutMinimalPerf.default | [427](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/LayoutMinimalPerf.default.html) | [412](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
RefMinimalPerf.default | [248](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/RefMinimalPerf.default.html) | [238](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.04:1
TableMinimalPerf.default | [433](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TableMinimalPerf.default.html) | [416](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.04:1
AnimationMinimalPerf.default | [420](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AnimationMinimalPerf.default.html) | [409](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.03:1
ChatDuplicateMessagesPerf.default | [387](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [376](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.03:1
DropdownManyItemsPerf.default | [732](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DropdownManyItemsPerf.default.html) | [711](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.03:1
ImageMinimalPerf.default | [385](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ImageMinimalPerf.default.html) | [375](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.03:1
LoaderMinimalPerf.default | [737](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/LoaderMinimalPerf.default.html) | [718](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [388](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/SegmentMinimalPerf.default.html) | [375](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
TextAreaMinimalPerf.default | [487](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TextAreaMinimalPerf.default.html) | [471](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.03:1
Checkbox.Fluent | [647](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Checkbox.Fluent.html) | [629](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Checkbox.Fluent_base.html) | 1.03:1
Dialog.Fluent | [786](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Dialog.Fluent.html) | [764](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Dialog.Fluent_base.html) | 1.03:1
BoxMinimalPerf.default | [374](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/BoxMinimalPerf.default.html) | [368](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
ChatWithPopoverPerf.default | [439](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ChatWithPopoverPerf.default.html) | [432](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.02:1
DatepickerMinimalPerf.default | [46916](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DatepickerMinimalPerf.default.html) | [45848](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [790](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DialogMinimalPerf.default.html) | [772](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
SkeletonMinimalPerf.default | [382](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/SkeletonMinimalPerf.default.html) | [376](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [3703](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3642](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [2040](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TableManyItemsPerf.default.html) | [2007](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
Slider.Fluent | [1592](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Slider.Fluent.html) | [1555](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Slider.Fluent_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1659](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1648](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
ButtonSlotsPerf.default | [585](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonSlotsPerf.default.html) | [582](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.01:1
ButtonUseCssNestingPerf.default | [1103](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1088](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 1.01:1
ChatMinimalPerf.default | [603](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ChatMinimalPerf.default.html) | [599](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.01:1
HeaderSlotsPerf.default | [777](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/HeaderSlotsPerf.default.html) | [770](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.01:1
MenuButtonMinimalPerf.default | [1566](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1554](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.01:1
PortalMinimalPerf.default | [176](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/PortalMinimalPerf.default.html) | [175](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [1660](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1650](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
ProviderMinimalPerf.default | [962](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ProviderMinimalPerf.default.html) | [955](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.01:1
ReactionMinimalPerf.default | [418](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ReactionMinimalPerf.default.html) | [415](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.01:1
TextMinimalPerf.default | [366](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TextMinimalPerf.default.html) | [364](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.01:1
ToolbarMinimalPerf.default | [979](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ToolbarMinimalPerf.default.html) | [967](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [831](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TooltipMinimalPerf.default.html) | [826](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
TreeMinimalPerf.default | [796](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TreeMinimalPerf.default.html) | [786](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.01:1
Avatar.Fluent | [331](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Avatar.Fluent.html) | [329](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Avatar.Fluent_base.html) | 1.01:1
Button.Fluent | [585](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Button.Fluent.html) | [578](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Button.Fluent_base.html) | 1.01:1
AccordionMinimalPerf.default | [163](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AccordionMinimalPerf.default.html) | [163](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2796](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2807](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
DividerMinimalPerf.default | [372](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DividerMinimalPerf.default.html) | [372](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1:1
HeaderMinimalPerf.default | [368](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/HeaderMinimalPerf.default.html) | [368](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [405](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/LabelMinimalPerf.default.html) | [407](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
ListMinimalPerf.default | [510](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ListMinimalPerf.default.html) | [508](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [712](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/StatusMinimalPerf.default.html) | [712](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
Dropdown.Fluent | [3044](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Dropdown.Fluent.html) | [3043](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Dropdown.Fluent_base.html) | 1:1
Tooltip.Fluent | [549](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Tooltip.Fluent.html) | [548](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Tooltip.Fluent_base.html) | 1:1
AlertMinimalPerf.default | [297](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AlertMinimalPerf.default.html) | [300](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.99:1
AttachmentSlotsPerf.default | [1180](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1192](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.99:1
CarouselMinimalPerf.default | [480](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/CarouselMinimalPerf.default.html) | [485](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [3051](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DropdownMinimalPerf.default.html) | [3068](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [4238](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/EmbedMinimalPerf.default.html) | [4271](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
FlexMinimalPerf.default | [308](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/FlexMinimalPerf.default.html) | [312](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/FlexMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1266](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/InputMinimalPerf.default.html) | [1282](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
ItemLayoutMinimalPerf.default | [1189](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1203](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.99:1
ListCommonPerf.default | [649](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ListCommonPerf.default.html) | [653](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ListCommonPerf.default_base.html) | 0.99:1
MenuMinimalPerf.default | [856](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/MenuMinimalPerf.default.html) | [867](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/MenuMinimalPerf.default_base.html) | 0.99:1
ButtonMinimalPerf.default | [183](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonMinimalPerf.default.html) | [187](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.98:1
ButtonUseCssPerf.default | [824](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonUseCssPerf.default.html) | [840](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 0.98:1
CardMinimalPerf.default | [571](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/CardMinimalPerf.default.html) | [582](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.98:1
GridMinimalPerf.default | [357](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/GridMinimalPerf.default.html) | [363](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.98:1
ListNestedPerf.default | [564](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ListNestedPerf.default.html) | [574](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ListNestedPerf.default_base.html) | 0.98:1
PopupMinimalPerf.default | [707](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/PopupMinimalPerf.default.html) | [719](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.98:1
IconMinimalPerf.default | [654](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/IconMinimalPerf.default.html) | [667](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.98:1
CustomToolbarPrototype.default | [3660](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/CustomToolbarPrototype.default.html) | [3718](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.98:1
ListWith60ListItems.default | [605](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ListWith60ListItems.default.html) | [629](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.96:1
Image.Fluent | [388](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Image.Fluent.html) | [403](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/Image.Fluent_base.html) | 0.96:1
RosterPerf.default | [1132](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/RosterPerf.default.html) | [1204](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/RosterPerf.default_base.html) | 0.94:1
TreeWith60ListItems.default | [175](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TreeWith60ListItems.default.html) | [195](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/17054/merge/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.9:1

</details><div id="perfComment9423"/>

**Review by YuanboXue-Amber — APPROVED** [review]

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx [hunk 1]
```diff
@@ -18,7 +18,8 @@ import * as _ from 'lodash';
 import * as PropTypes from 'prop-types';
 import * as React from 'react';
 
-import { lockBodyScroll, unlockBodyScroll } from './utils';
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:21]: Are these removed utils still used in northstar ?

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx [hunk 2]
```diff
@@ -221,15 +222,16 @@ export const Dialog: ComponentWithAs<'div', DialogProps> &
   });
 
   React.useEffect(() => {
+    const target = contentRef?.current;
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:225]: Just curious what is the difference between the old and new targets ?

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx [hunk 3]
```diff
@@ -221,15 +222,16 @@ export const Dialog: ComponentWithAs<'div', DialogProps> &
...
+      disableBodyScroll(target);
     }
     return () => {
       if (open) {
-        unlockBodyScroll(context.target);
+        clearAllBodyScrollLocks(target);
       }
     };
-  }, [context.target, open]);
+  }, [open]);
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:234]: Disclaimer: I'm not 100% sure about this but I think it should be safer to use the ref as a dependency 

```suggestion
  }, [open, contentRef]);
```

**Comment by ling1726** [comment]
once the nightly build for your PR goes in can you please post a working codesandbox of the original issue ?

**Review by ling1726 — APPROVED** [review]

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx (hunk 1 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:21]: Nops

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx (hunk 3 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:234]: I don't think so, if we have to it should be `contentRef.current`

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx (hunk 2 above)
Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:225]: Previously were target to be added `overflow: hidden;` for this package the target is where it should still be possible to scroll.

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx [hunk 4]
```diff
@@ -18,7 +18,8 @@ import * as _ from 'lodash';
 import * as PropTypes from 'prop-types';
 import * as React from 'react';
 
-import { lockBodyScroll, unlockBodyScroll } from './utils';
+// import { lockBodyScroll, unlockBodyScroll } from './utils';
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:21]:
```suggestion
```

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx [hunk 5]
```diff
@@ -221,15 +222,16 @@ export const Dialog: ComponentWithAs<'div', DialogProps> &
...
   React.useEffect(() => {
+    const target = contentRef?.current;
     if (open) {
-      lockBodyScroll(context.target);
+      disableBodyScroll(target);
     }
     return () => {
       if (open) {
-        unlockBodyScroll(context.target);
+        clearAllBodyScrollLocks(target);
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:230]:
```suggestion
        enableBodyScroll(target);
```

This should be `enableBodyScroll()`, according to docs it will clean all locks:

> // 4. Useful if we have called disableBodyScroll for multiple target elements,
> // and we just want a kill-switch to undo all that.
> bodyScrollLock.clearAllBodyScrollLocks();

File: packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx [hunk 6]
```diff
@@ -18,7 +18,7 @@ import * as _ from 'lodash';
 import * as PropTypes from 'prop-types';
 import * as React from 'react';
 
-import { lockBodyScroll, unlockBodyScroll } from './utils';
+import { disableBodyScroll, clearAllBodyScrollLocks } from 'body-scroll-lock';
```
Comment (assuncaocharles) [inline packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx:21]:
```suggestion
import { disableBodyScroll, enableBodyScroll } from 'body-scroll-lock';
```

**Review by layershifter — APPROVED** [review]
