### PR TITLE
react-tabs: fix indicator gap

### LINKED ISSUE #22743: react-tabs: indicator shows inner gap on certain resolution screens
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
unknown - cannot reproduce myself, responding to customer reported issue
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/dashboard/home?workspace=40f693cf-94f8-4e45-8292-2b3db5157b15

## Actual Behavior
indicator shows a small gap on some resolutions

## Expected Behavior
indicator does not have a gap

### Logs

```shell
N/A
```

### Requested priority

Normal

### Products/sites affected

none

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by GeoffCoxMSFT**
## Cause of issue
- Selection indicators are specified to be a particular stroke width.
- We used borders rather than background for selection indicators to allow for system high contrast mode to automatically update border colors.
- The border width of the selection indicators is the stroke width / 2.0.
- Due to some stroke widths being odd numbers, this create sub-pixel border widths.
- When the border widths were rendered they ended up being floor values and so a small gap would show because the height or width was set to the stroke width.

## Changes
- Set the width and height CSS values from the pending and active selection indicator to 0

## Issues

Fixes #22743

### CODE REVIEW

File: packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts [hunk 1]
```diff
@@ -203,7 +203,7 @@ const usePendingIndicatorStyles = makeStyles({
     ':before': {
       bottom: 0,
       ...shorthands.borderWidth(`calc(${tabIndicatorStrokeWidths.mediumHorizontal} / 2.0)`),
-      height: tabIndicatorStrokeWidths.mediumHorizontal,
+      height: 0,
```
Comment (GeoffCoxMSFT) [inline packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts:206]: @smhigley - You mentioned possibly changing the box-siding to be content rather than border.  I investigate this and I need the border to be part of the height/width in order for the animation measurements to be accurate. I didn't find that one or the other made any difference once I set the width/height to zero.

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/27ba5613b1253801c3ae4e2aba0fc9eb2ae464b8'>27ba5613b1253801c3ae4e2aba0fc9eb2ae464b8</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/Avatar-mount_base.html">797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/Avatar-mount.html">823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/Button-mount_base.html">485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/Button-mount.html">491</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/FluentProvider-mount_base.html">1701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/FluentProvider-mount.html">1750</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/FluentProviderWithTheme-mount_base.html">265</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/FluentProviderWithTheme-mount.html">276</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">218</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">248</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">273</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">271</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/MakeStyles-mount_base.html">1392</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22744/perf-test-react-components/MakeStyles-mount.html">1489</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by micahgodbolt — APPROVED** [review]
