### PR TITLE
fix(react-calendar-compat): aria-label for year selection

### LINKED ISSUE #32827: [Bug][calendar-compat] Wrong aria label for year picker in calendar-compat
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 10.07 GB / 31.71 GB
  Browsers:
    Edge: Chromium (127.0.2651.105)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

yes

### Reproduction

https://codesandbox.io/p/sandbox/calendar-compat-m9t2yj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0lwgmbo00063j6jm7lnwxul%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0lwgmbo00023j6jg5l2iw7i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0lwgmbo00033j6j1zrsof59%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0lwgmbo00053j6jmup9ijca%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0lwgmbo00023j6jg5l2iw7i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0lwgmbo00013j6jehl2pkny%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0lwgmbo00023j6jg5l2iw7i%2522%252C%2522activeTabId%2522%253A%2522cm0lwgmbo00013j6jehl2pkny%2522%257D%252C%2522cm0lwgmbo00053j6jmup9ijca%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0lwgmbo00043j6jhy6qq53k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm0lwgmbo00053j6jmup9ijca%2522%252C%2522activeTabId%2522%253A%2522cm0lwgmbo00043j6jhy6qq53k%2522%257D%252C%2522cm0lwgmbo00033j6j1zrsof59%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0lwgmbo00033j6j1zrsof59%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

## Actual Behavior

1. Click on month header in calendar
2. Click on month picker header to go to year picker (which has year range as header)
3. Use any screen reader to narrate year picker header
4. If year picker header is '2024-2035', Screen reader says "2024-2035, change month"

## Expected Behavior

If year picker header is '2024-2035', Screen reader says "2024-2035, change year"

### Logs

_No response_

### Requested priority

High

### Products/sites affected

Loop

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ValentinaKozlova**
## Previous Behavior
After clicking on Year picker header the screen reader says "2024-2035, change month"

## New Behavior
For year picker header screen reader says "2024-2035, change year"

- Fixes #32827

### CODE REVIEW

File: packages/react-components/react-calendar-compat/library/src/components/CalendarMonth/CalendarMonth.tsx [hunk 1]
```diff
@@ -327,7 +327,7 @@ function getYearStrings({
       rangeAriaLabel: yearRangeToString,
       prevRangeAriaLabel: yearRangeToPrevDecadeLabel,
       nextRangeAriaLabel: yearRangeToNextDecadeLabel,
-      headerAriaLabelFormatString: strings.yearPickerHeaderAriaLabel,
+      headerAriaLabelFormatString: strings.monthPickerHeaderAriaLabel,
```
Comment (ValentinaKozlova) [inline packages/react-components/react-calendar-compat/library/src/components/CalendarMonth/CalendarMonth.tsx:330]: MonthHeader is misleading for year selection but this is because of those lines in `dateFormatting.defaults`:
```ts
  monthPickerHeaderAriaLabel: '{0}, change year',
  yearPickerHeaderAriaLabel: '{0}, change month',
```
And those strings are exported so I shouldn't change them. There's a way to add a new string, but I don't think it's a good solution so I just used existing one.
