### PR TITLE
fix(useOnClickOutside): Use capture event handler

### LINKED ISSUE #18793: Popover closes when content updates after click
### Environment Information

- **Package version(s)**: v9 alpha

### Please provide a reproduction of the bug in a codesandbox:

https://codesandbox.io/s/ecstatic-brahmagupta-bbvo8

#### Actual behavior:

When the content of the `Popover` changes after click, the popover closes.

#### Expected behavior:

The content of the `Popover` should change but the `Popover` should stay open

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

### PR DESCRIPTION
**Pull request by ling1726**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #18793
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Updates `useOnClickOutside` hook to allow `capture` event handling.

Adds e2e test for `Popover` to prevent future regression

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Avatar-mount_base.html">774</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Avatar-mount.html">811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/BaseButton-mount_base.html">869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/BaseButton-mount.html">860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Breadcrumb-mount_base.html">2552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Breadcrumb-mount.html">2665</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ButtonNext-mount_base.html">506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ButtonNext-mount.html">498</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Checkbox-mount_base.html">1486</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Checkbox-mount.html">1507</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/CheckboxBase-mount_base.html">1256</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/CheckboxBase-mount.html">1309</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ChoiceGroup-mount_base.html">4736</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ChoiceGroup-mount.html">4707</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ComboBox-mount_base.html">971</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ComboBox-mount.html">949</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/CommandBar-mount_base.html">9878</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/CommandBar-mount.html">10038</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ContextualMenu-mount_base.html">6137</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ContextualMenu-mount.html">6120</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DefaultButton-mount_base.html">1091</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DefaultButton-mount.html">1099</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DetailsRow-mount_base.html">3664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DetailsRow-mount.html">3678</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DetailsRowFast-mount_base.html">3724</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DetailsRowFast-mount.html">3652</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DetailsRowNoStyles-mount_base.html">3444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DetailsRowNoStyles-mount.html">3488</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Dialog-mount_base.html">2142</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Dialog-mount.html">2085</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DocumentCardTitle-mount_base.html">144</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/DocumentCardTitle-mount.html">139</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Dropdown-mount_base.html">3172</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Dropdown-mount.html">3179</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/FluentProviderNext-mount_base.html">7100</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/FluentProviderNext-mount.html">7203</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/FocusTrapZone-mount_base.html">1733</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/FocusTrapZone-mount.html">1773</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/FocusZone-mount_base.html">1744</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/FocusZone-mount.html">1758</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/IconButton-mount_base.html">1720</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/IconButton-mount.html">1689</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Label-mount_base.html">323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Label-mount.html">337</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Layer-mount_base.html">1739</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Layer-mount.html">1733</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Link-mount_base.html">464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Link-mount.html">452</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/MakeStyles-mount_base.html">1763</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/MakeStyles-mount.html">1806</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/MenuButton-mount_base.html">1483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/MenuButton-mount.html">1454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/MessageBar-mount_base.html">1976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/MessageBar-mount.html">1953</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Nav-mount_base.html">3243</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Nav-mount.html">3181</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/OverflowSet-mount_base.html">1000</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/OverflowSet-mount.html">1021</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Panel-mount_base.html">2072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Panel-mount.html">2053</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Persona-mount_base.html">821</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Persona-mount.html">803</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Pivot-mount_base.html">1389</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Pivot-mount.html">1411</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/PrimaryButton-mount_base.html">1253</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/PrimaryButton-mount.html">1254</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Rating-mount_base.html">7628</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Rating-mount.html">7520</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/SearchBox-mount_base.html">1343</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/SearchBox-mount.html">1304</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Shimmer-mount_base.html">2516</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Shimmer-mount.html">2466</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Slider-mount_base.html">1936</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Slider-mount.html">1946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/SpinButton-mount_base.html">5004</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/SpinButton-mount.html">4921</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Spinner-mount_base.html">431</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Spinner-mount.html">414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/SplitButton-mount_base.html">3124</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/SplitButton-mount.html">3065</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Stack-mount_base.html">516</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Stack-mount.html">479</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/StackWithIntrinsicChildren-mount_base.html">1501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/StackWithIntrinsicChildren-mount.html">1537</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/StackWithTextChildren-mount_base.html">4404</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/StackWithTextChildren-mount.html">4407</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/SwatchColorPicker-mount_base.html">10149</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/SwatchColorPicker-mount.html">10112</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Tabs-mount_base.html">1366</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Tabs-mount.html">1367</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/TagPicker-mount_base.html">2351</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/TagPicker-mount.html">2365</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/TeachingBubble-mount_base.html">11810</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/TeachingBubble-mount.html">11710</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Text-mount_base.html">428</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Text-mount.html">402</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/TextField-mount_base.html">1385</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/TextField-mount.html">1379</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ThemeProvider-mount_base.html">1192</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ThemeProvider-mount.html">1183</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ThemeProvider-virtual-rerender_base.html">587</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/ThemeProvider-virtual-rerender.html">598</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Toggle-mount_base.html">793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/Toggle-mount.html">788</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/buttonNative-mount_base.html">108</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test/buttonNative-mount.html">113</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
TreeWith60ListItems.default | [184](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TreeWith60ListItems.default.html) | [161](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.14:1
FormMinimalPerf.default | [403](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/FormMinimalPerf.default.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.08:1
PortalMinimalPerf.default | [186](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/PortalMinimalPerf.default.html) | [173](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.08:1
VideoMinimalPerf.default | [642](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/VideoMinimalPerf.default.html) | [597](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.08:1
AvatarMinimalPerf.default | [192](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AvatarMinimalPerf.default.html) | [180](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.07:1
ChatDuplicateMessagesPerf.default | [299](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [279](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.07:1
ImageMinimalPerf.default | [384](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ImageMinimalPerf.default.html) | [359](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.07:1
PopupMinimalPerf.default | [582](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/PopupMinimalPerf.default.html) | [548](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.06:1
RefMinimalPerf.default | [235](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/RefMinimalPerf.default.html) | [221](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.06:1
ReactionMinimalPerf.default | [370](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ReactionMinimalPerf.default.html) | [354](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.05:1
TextMinimalPerf.default | [355](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TextMinimalPerf.default.html) | [342](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.04:1
AccordionMinimalPerf.default | [150](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AccordionMinimalPerf.default.html) | [145](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.03:1
AlertMinimalPerf.default | [271](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AlertMinimalPerf.default.html) | [264](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.03:1
AnimationMinimalPerf.default | [407](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AnimationMinimalPerf.default.html) | [394](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.03:1
GridMinimalPerf.default | [339](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/GridMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.03:1
LayoutMinimalPerf.default | [360](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/LayoutMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.03:1
ListCommonPerf.default | [623](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ListCommonPerf.default.html) | [603](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ListCommonPerf.default_base.html) | 1.03:1
TableMinimalPerf.default | [397](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TableMinimalPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.03:1
TreeMinimalPerf.default | [790](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TreeMinimalPerf.default.html) | [768](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.03:1
BoxMinimalPerf.default | [334](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/BoxMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
ButtonSlotsPerf.default | [525](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ButtonSlotsPerf.default.html) | [517](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.02:1
LabelMinimalPerf.default | [381](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/LabelMinimalPerf.default.html) | [372](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.02:1
ListNestedPerf.default | [545](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ListNestedPerf.default.html) | [533](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ListNestedPerf.default_base.html) | 1.02:1
MenuButtonMinimalPerf.default | [1559](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1530](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.02:1
ProviderMergeThemesPerf.default | [1669](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1629](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.02:1
ProviderMinimalPerf.default | [971](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ProviderMinimalPerf.default.html) | [951](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.02:1
TextAreaMinimalPerf.default | [488](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TextAreaMinimalPerf.default.html) | [480](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.02:1
CustomToolbarPrototype.default | [3837](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/CustomToolbarPrototype.default.html) | [3770](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.02:1
ToolbarMinimalPerf.default | [934](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ToolbarMinimalPerf.default.html) | [920](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.02:1
ButtonMinimalPerf.default | [162](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ButtonMinimalPerf.default.html) | [160](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.01:1
CardMinimalPerf.default | [539](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/CardMinimalPerf.default.html) | [535](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2730](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2712](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
DialogMinimalPerf.default | [750](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DialogMinimalPerf.default.html) | [743](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [3074](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DropdownMinimalPerf.default.html) | [3032](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
HeaderMinimalPerf.default | [348](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/HeaderMinimalPerf.default.html) | [343](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [826](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/MenuMinimalPerf.default.html) | [815](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
RadioGroupMinimalPerf.default | [446](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [443](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.01:1
SkeletonMinimalPerf.default | [351](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/SkeletonMinimalPerf.default.html) | [349](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3641](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3621](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
StatusMinimalPerf.default | [651](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/StatusMinimalPerf.default.html) | [645](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.01:1
AttachmentMinimalPerf.default | [150](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AttachmentMinimalPerf.default.html) | [150](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1:1
AttachmentSlotsPerf.default | [1042](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1046](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1661](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1657](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
DropdownManyItemsPerf.default | [664](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DropdownManyItemsPerf.default.html) | [663](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4074](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/EmbedMinimalPerf.default.html) | [4091](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
FlexMinimalPerf.default | [272](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/FlexMinimalPerf.default.html) | [272](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1:1
LoaderMinimalPerf.default | [681](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/LoaderMinimalPerf.default.html) | [679](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1:1
RosterPerf.default | [1132](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/RosterPerf.default.html) | [1132](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/RosterPerf.default_base.html) | 1:1
TableManyItemsPerf.default | [1845](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TableManyItemsPerf.default.html) | [1851](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1:1
DividerMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DividerMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.99:1
ItemLayoutMinimalPerf.default | [1188](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1200](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.99:1
SegmentMinimalPerf.default | [330](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/SegmentMinimalPerf.default.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [634](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ChatMinimalPerf.default.html) | [646](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.98:1
DatepickerMinimalPerf.default | [5234](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5351](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.98:1
HeaderSlotsPerf.default | [723](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/HeaderSlotsPerf.default.html) | [740](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.98:1
InputMinimalPerf.default | [1243](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/InputMinimalPerf.default.html) | [1267](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.98:1
ListWith60ListItems.default | [646](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ListWith60ListItems.default.html) | [660](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.98:1
SliderMinimalPerf.default | [1551](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/SliderMinimalPerf.default.html) | [1579](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.98:1
TooltipMinimalPerf.default | [955](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TooltipMinimalPerf.default.html) | [972](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.98:1
ListMinimalPerf.default | [477](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ListMinimalPerf.default.html) | [494](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.97:1
IconMinimalPerf.default | [586](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/IconMinimalPerf.default.html) | [603](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.97:1
ChatWithPopoverPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ChatWithPopoverPerf.default.html) | [360](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.96:1
CarouselMinimalPerf.default | [438](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/CarouselMinimalPerf.default.html) | [463](https://fluentuipr.z22.web.core.windows.net/pull/18792/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.95:1

</details><div id="perfComment9423"/>

File: packages/react-utilities/src/hooks/useOnClickOutside.ts [hunk 1]
```diff
@@ -62,8 +68,8 @@ export const useOnClickOutside = (options: UseOnClickOrScrollOutsideOptions) =>
     };
 
     if (!disabled) {
-      element?.addEventListener('click', conditionalHandler);
-      element?.addEventListener('touchstart', conditionalHandler);
+      element?.addEventListener('click', conditionalHandler, !!capture);
+      element?.addEventListener('touchstart', conditionalHandler, !!capture);
```
Comment (layershifter) [inline packages/react-utilities/src/hooks/useOnClickOutside.ts:72]:
```suggestion
      element?.addEventListener('click', conditionalHandler, true);
      element?.addEventListener('touchstart', conditionalHandler, true);
```

As we are targeting the specific hook I suggest to make `capture` a default thing there 😏 In all cases that we had in Northstar these event handlers should run in `capture` mode to be evaluated before React handlers:

https://github.com/microsoft/fluentui/blob/8de04ed56820cfdb7c13d9c108b0eae596cd3215/packages/fluentui/react-northstar/src/components/Popup/Popup.tsx#L434

I also see the same in React Spectrum:

https://github.com/adobe/react-spectrum/blob/4b75cbe84157bcd735f7097a41f397d2c5c58543/packages/%40react-aria/interactions/src/useInteractOutside.ts#L66-L67

File: packages/react-utilities/src/hooks/useOnScrollOutside.ts [hunk 2]
```diff
@@ -20,13 +20,13 @@ export const useOnScrollOutside = (options: UseOnClickOrScrollOutsideOptions) =>
 
   React.useEffect(() => {
     if (!disabled) {
-      element?.addEventListener('wheel', listener);
-      element?.addEventListener('touchmove', listener);
+      element?.addEventListener('wheel', listener, !!capture);
```
Comment (layershifter) [inline packages/react-utilities/src/hooks/useOnScrollOutside.ts:23]: I don't think that it's required for "wheel" and "touchmove". Do you have repro steps for this case?

Comment (ling1726) [reply packages/react-utilities/src/hooks/useOnScrollOutside.ts:23]: No it's not required, I can revert this one

File: packages/react-utilities/src/hooks/useOnClickOutside.ts (hunk 1 above)
Comment (ling1726) [reply packages/react-utilities/src/hooks/useOnClickOutside.ts:72]: yeah, that does make things simpler

**Review by layershifter — APPROVED** [review]
