### PR TITLE
fix(Embed): set default value {} for `variables` prop

### LINKED ISSUE #15999: Embed client throws when no style variables are passed in @fluentui/react-northstar@0.51.2
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
[Example where embed will throw](https://codesandbox.io/s/fluent-ui-example-forked-54b8m)

#### Actual behavior:

`<Embed />` will throw if there are no style variables passed in

#### Expected behavior:

`<Embed />` should not throw when no style variables are passed in

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by YuanboXue-Amber**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #15999
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

One-liner as described in PR title

#### Focus areas to test

(optional)

### CODE REVIEW

**Review by assuncaocharles — APPROVED** [review]
LGTM

File: packages/fluentui/react-northstar/src/components/Embed/Embed.tsx [hunk 1]
```diff
@@ -241,6 +241,7 @@ Embed.defaultProps = {
   as: 'span',
   accessibility: embedBehavior,
   control: {},
+  variables: {},
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Embed/Embed.tsx:244]: nit: I don't wanna be that guy but since this is a regression, should we add a unit test ?

**Review by ling1726 — APPROVED** [review]
Looks good, if we can add a unit test since this is a regression that would be great

File: packages/fluentui/react-northstar/src/components/Embed/Embed.tsx (hunk 1 above)
Comment (YuanboXue-Amber) [reply packages/fluentui/react-northstar/src/components/Embed/Embed.tsx:244]: we could :) let me
