### PR TITLE
Fix storybook favicon

### LINKED ISSUE #31606: [Bug]: Missing Fluent icon in tab for Storybook
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/

## Actual Behavior
image

## Expected Behavior
image

### Logs

_No response_

### Requested priority

Low

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by hcz**
## Previous Behavior
Favicon was removed or server-side routing was broken
```html
<link rel="shortcut icon" href="https://www.microsoft.com/design/fluent/assets/favicons/favicon-192.png" />
```
This url redirects with 301 to the main page
```bash
curl -Ls -o /dev/null -w %{url_effective} https://www.microsoft.com/design/fluent/assets/favicons/favicon-192.png
https://fluent2.microsoft.design/
```

## New Behavior
fluent2.microsoft.design uses this configuration, so I made similar changes but with own Fluent UI icon
```html
<link rel="shortcut icon" type="image/x-icon" href="/favicons/favicon.ico">
```

Also I fixed url in JSDoc in storybook config

## Related Issue(s)

- Fixes #31606

### CODE REVIEW

**Comment by hcz** [comment]
@microsoft-github-policy-service agree

File: .storybook/main.js [hunk 1]
```diff
@@ -94,7 +94,7 @@ module.exports = /** @type {Omit<StorybookConfig,'typescript'|'babel'>} */ ({
   },
```
Comment (fabricteam) [inline .storybook/main.js:94]: ## [🕵 fluentui-web-components-v3 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=31706&commitId=47a6fcfecc7e2f36b3383bfa334c095420f17043&env=prod&clientType=FLUENTUI)


  <details><summary><b>Accordion</b> 3 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Accordion.Size.normal.chromium.png|2| Changed|
|Accordion.Size - RTL.normal.chromium.png|2| Changed|
|Accordion.Size - Dark Mode.normal.chromium.png|2| Changed|

</details>


  <details><summary><b>Avatar</b> 8 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar.Active Appearance - Dark Mode.normal.chromium.png|2| Changed|
|Avatar.Color - RTL.normal.chromium.png|1| Changed|
|Avatar.Active Appearance.normal.chromium.png|10| Changed|
|Avatar.Colorful.normal.chromium.png|325| Changed|
|Avatar.Colorful - Dark Mode.normal.chromium.png|452| Changed|
|Avatar.Color.normal.chromium.png|1| Changed|
|Avatar.Colorful - RTL.normal.chromium.png|326| Changed|
|Avatar.Active.normal.chromium.png|5| Changed|

</details>


  <details><summary><b>Badge</b> 6 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Badge.Appearance.normal.chromium.png|1| Changed|
|Badge.Appearance - Dark Mode.normal.chromium.png|15| Changed|
|Badge.Shape.normal.chromium.png|1| Changed|
|Badge.Size.normal.chromium.png|6| Changed|
|Badge.Default.normal.chromium.png|1| Changed|
|Badge.Color.normal.chromium.png|1| Changed|

</details>


  <details><summary><b>Button</b> 57 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Button.Large Icon Only - Dark Mode.default.chromium.png|4| Changed|
|Button.Large Icon Only - Dark Mode.pressed.chromium.png|5| Changed|
|Button.Large Icon Only.pressed.chromium.png|3| Changed|
|Button.Large Icon Only.hover.chromium.png|4| Changed|
|Button.Large Icon Only.default.chromium.png|5| Changed|
|Button.Large With Icon - Dark Mode.hover.chromium.png|3| Changed|
|Button.Large Icon Only - Dark Mode.hover.chromium.png|3| Changed|
|Button.Large With Icon - RTL.pressed.chromium.png|3| Changed|
|Button.Large With Icon - RTL.hover.chromium.png|4| Changed|
|Button.Large With Icon - RTL.default.chromium.png|5| Changed|
|Button.Large With Icon.default.chromium.png|5| Changed|
|Button.Large With Icon - Dark Mode.default.chromium.png|4| Changed|
|Button.Outline Disabled - Dark Mode.hover.chromium.png|159| Changed|
|Button.Large With Icon - Dark Mode.pressed.chromium.png|5| Changed|
|Button.Outline Disabled Focusable - Dark Mode.pressed.chromium.png|159| Changed|
|Button.Large With Icon.pressed.chromium.png|3| Changed|
|Button.Large With Icon.hover.chromium.png|4| Changed|
|Button.Primary Disabled - Dark Mode.default.chromium.png|44| Changed|
|Button.Primary Disabled - Dark Mode.hover.chromium.png|44| Changed|
|Button.Primary Disabled Focusable.hover.chromium.png|15| Changed|
|Button.Primary Disabled Focusable.default.chromium.png|15| Changed|
|Button.Primary Disabled Focusable - Dark Mode.hover.chromium.png|44| Changed|
|Button.Primary Disabled Focusable.pressed.chromium.png|15| Changed|
|Button.Primary Disabled.hover.chromium.png|15| Changed|
|Button.Primary Disabled Focusable - Dark Mode.default.chromium.png|44| Changed|
|Button.Primary Disabled.default.chromium.png|15| Changed|
|Button.Primary Disabled - Dark Mode.pressed.chromium.png|44| Changed|
|Button.Subtle Disabled - Dark Mode.default.chromium.png|187| Changed|
|Button.Subtle Disabled Focusable - Dark Mode.pressed.chromium.png|187| Changed|
|Button.Outline Disabled - Dark Mode.pressed.chromium.png|159| Changed|
|Button.Subtle Disabled Focusable - Dark Mode.default.chromium.png|187| Changed|
|Button.Subtle Disabled Focusable - Dark Mode.hover.chromium.png|187| Changed|
|Button.Subtle Disabled.default.chromium.png|25| Changed|
|Button.Subtle Disabled Focusable.pressed.chromium.png|25| Changed|
|Button.Transparent Disabled - Dark Mode.default.chromium.png|199| Changed|
|Button.Transparent Disabled - Dark Mode.hover.chromium.png|199| Changed|
|Button.Subtle Disabled Focusable.default.chromium.png|25| Changed|
|Button.Transparent Disabled - Dark Mode.pressed.chromium.png|199| Changed|
|Button.Primary Disabled.pressed.chromium.png|15| Changed|
|Button.Outline Disabled Focusable - Dark Mode.default.chromium.png|159| Changed|
|Button.Transparent Disabled Focusable.default.chromium.png|27| Changed|
|Button.Transparent Disabled Focusable - Dark Mode.hover.chromium.png|199| Changed|
|Button.Transparent Disabled Focusable.pressed.chromium.png|27| Changed|
|Button.Transparent Disabled Focusable - Dark Mode.pressed.chromium.png|199| Changed|
|Button.Transparent Disabled.pressed.chromium.png|27| Changed|
|Button.Transparent Disabled Focusable.hover.chromium.png|27| Changed|
|Button.Transparent Disabled.hover.chromium.png|27| Changed|
|Button.Subtle Disabled.pressed.chromium.png|25| Changed|
|Button.Transparent Disabled Focusable - Dark Mode.default.chromium.png|199| Changed|
|Button.Primary Disabled Focusable - Dark Mode.pressed.chromium.png|44| Changed|
|Button.Outline Disabled Focusable - Dark Mode.hover.chromium.png|159| Changed|
|Button.Subtle Disabled - Dark Mode.pressed.chromium.png|187| Changed|
|Button.Outline Disabled - Dark Mode.default.chromium.png|159| Changed|
|Button.Subtle Disabled.hover.chromium.png|25| Changed|
|Button.Subtle Disabled Focusable.hover.chromium.png|25| Changed|
|Button.Subtle Disabled - Dark Mode.hover.chromium.png|187| Changed|
|Button.Transparent Disabled.default.chromium.png|27| Changed|

</details>


  <details><summary><b>Checkbox</b> 26 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Checkbox.Checked - Dark Mode.normal.chromium.png|982| Changed|
|Checkbox.Circular Checked - Dark Mode.normal.chromium.png|1080| Changed|
|Checkbox.Circular Disabled Checked - Dark Mode.normal.chromium.png|799| Changed|
|Checkbox.Circular Indeterminate - Dark Mode.indeterminate.chromium.png|1102| Changed|
|Checkbox.Circular Disabled Checked.normal.chromium.png|4728| Changed|
|Checkbox.Circular Indeterminate.indeterminate.chromium.png|4869| Changed|
|Checkbox.Default - Dark Mode.normal.chromium.png|814| Changed|
|Checkbox.Circular.normal.chromium.png|4734| Changed|
|Checkbox.Circular - Dark Mode.normal.chromium.png|792| Changed|
|Checkbox.Circular Indeterminate - Dark Mode.normal.chromium.png|936| Changed|
|Checkbox.Disabled Checked - Dark Mode.normal.chromium.png|777| Changed|
|Checkbox.Default - RTL.normal.chromium.png|4751| Changed|
|Checkbox.Indeterminate.indeterminate.chromium.png|4847| Changed|
|Checkbox.Indeterminate - Dark Mode.normal.chromium.png|877| Changed|
|Checkbox.Default.normal.chromium.png|4751| Changed|
|Checkbox.Indeterminate.normal.chromium.png|4776| Changed|
|Checkbox.Circular Disabled - Dark Mode.normal.chromium.png|760| Changed|
|Checkbox.Disabled Checked.normal.chromium.png|4721| Changed|
|Checkbox.Circular Indeterminate.normal.chromium.png|4786| Changed|
|Checkbox.Circular - RTL.normal.chromium.png|4733| Changed|
|Checkbox.Circular Checked.normal.chromium.png|4883| Changed|
|Checkbox.Circular Disabled.normal.chromium.png|4711| Changed|
|Checkbox.Indeterminate - Dark Mode.indeterminate.chromium.png|993| Changed|
|Checkbox.Disabled.normal.chromium.png|4705| Changed|
|Checkbox.Disabled - Dark Mode.normal.chromium.png|739| Changed|
|Checkbox.Checked.normal.chromium.png|4855| Changed|

</details>


  <details><summary><b>Divider</b> 3 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Divider.With Svg - RTL.normal.chromium.png|3| Changed|
|Divider.With Svg.normal.chromium.png|3| Changed|
|Divider.Vertical With Svg.normal.chromium.png|4| Changed|

</details>


  <details><summary><b>Label</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Label.Required - RTL.normal.chromium.png|11| Changed|
|Label.Size Small.normal.chromium.png|661| Changed|

</details>


  <details><summary><b>Link</b> 10 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Link.Default.default.chromium.png|0| Added|
|Link.Default.hover.chromium.png|0| Added|
|Link.Default.pressed.chromium.png|0| Added|
|Link.Inline.default.chromium.png|0| Added|
|Link.Inline.hover.chromium.png|0| Added|
|Link.Inline.pressed.chromium.png|0| Added|
|Link.Subtle.default.chromium.png|0| Added|
|Link.Subtle.hover.chromium.png|0| Added|
|Link.Subtle.pressed.chromium.png|0| Added|
|Link.With Long Text.default.chromium.png|0| Added|

</details>


  <details><summary><b>MenuList</b> 16 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|MenuList.Checkbox - RTL.2nd selected.chromium.png|1| Changed|
|MenuList.Checkbox With Icons - RTL.normal.chromium.png|4| Changed|
|MenuList.Checkbox With Icons.normal.chromium.png|4| Changed|
|MenuList.Checkbox.2nd selected.chromium.png|1| Changed|
|MenuList.Radio With Icons - RTL.normal.chromium.png|4| Changed|
|MenuList.Checkbox With Icons - RTL.1st selected.chromium.png|4| Changed|
|MenuList.Radio With Icons - RTL.1st selected.chromium.png|4| Changed|
|MenuList.Radio With Icons - RTL.2nd selected.chromium.png|4| Changed|
|MenuList.Radio With Icons.2nd selected.chromium.png|4| Changed|
|MenuList.Checkbox With Icons.1st selected.chromium.png|4| Changed|
|MenuList.With Icons.hover menuitem.chromium.png|3| Changed|
|MenuList.Checkbox With Icons - RTL.2nd selected.chromium.png|5| Changed|
|MenuList.Radio With Icons.normal.chromium.png|4| Changed|
|MenuList.Checkbox With Icons.2nd selected.chromium.png|5| Changed|
|MenuList.With Icons.normal.chromium.png|4| Changed|
|MenuList.Radio With Icons.1st selected.chromium.png|4| Changed|

</details>


  <details><summary><b>Slider</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Slider.Size Small.rightArrow.chromium.png|1| Changed|
|Slider.Size Small.normal.chromium.png|1| Changed|

</details>


  <details><summary><b>Switch</b> 34 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Switch.Checked.normal.chromium.png|5132| Changed|
|Switch.Default - Dark Mode.normal.chromium.png|1019| Changed|
|Switch.Checked - Dark Mode.normal.chromium.png|1130| Changed|
|Switch.Default - RTL.normal.chromium.png|5009| Changed|
|Switch.Disabled - Dark Mode.normal.chromium.png|909| Changed|
|Switch.Checked - Dark Mode.hover.chromium.png|1169| Changed|
|Switch.Disabled - RTL.hover.chromium.png|4914| Changed|
|Switch.Default - RTL.hover.chromium.png|5044| Changed|
|Switch.Disabled Checked.hover.chromium.png|5047| Changed|
|Switch.Disabled - RTL.normal.chromium.png|4914| Changed|
|Switch.Default - Dark Mode.hover.chromium.png|1071| Changed|
|Switch.Disabled.hover.chromium.png|4914| Changed|
|Switch.Checked.hover.chromium.png|5150| Changed|
|Switch.Disabled Checked - Dark Mode.normal.chromium.png|1074| Changed|
|Switch.Disabled.normal.chromium.png|4914| Changed|
|Switch.Checked - RTL.hover.chromium.png|5150| Changed|
|Switch.Default.normal.chromium.png|5009| Changed|
|Switch.Checked - RTL.normal.chromium.png|5132| Changed|
|Switch.Default.hover.chromium.png|5044| Changed|
|Switch.Disabled Checked - Dark Mode.hover.chromium.png|1074| Changed|
|Switch.Disabled - Dark Mode.hover.chromium.png|909| Changed|
|Switch.Disabled Checked.normal.chromium.png|5047| Changed|
|Switch.Label Above - RTL.hover.chromium.png|0| Removed|
|Switch.Label Above - RTL.normal.chromium.png|0| Removed|
|Switch.Label Above.hover.chromium.png|0| Removed|
|Switch.Label Above.normal.chromium.png|0| Removed|
|Switch.Label After - RTL.hover.chromium.png|0| Removed|
|Switch.Label After - RTL.normal.chromium.png|0| Removed|
|Switch.Label After.hover.chromium.png|0| Removed|
|Switch.Label After.normal.chromium.png|0| Removed|
|Switch.Label Before - RTL.hover.chromium.png|0| Removed|
|Switch.Label Before - RTL.normal.chromium.png|0| Removed|
|Switch.Label Before.hover.chromium.png|0| Removed|
|Switch.Label Before.normal.chromium.png|0| Removed|

</details>


  <details><summary><b>Text</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Text.Block.normal.chromium.png|995| Changed|
|Text.Strikethrough.normal.chromium.png|236| Changed|

</details>


  <details><summary><b>TextInput</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|TextInput.Size Large.normal.chromium.png|3| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/Avatar-mount_base.html">642</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/Avatar-mount.html">632</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/Button-mount_base.html">313</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/Button-mount.html">301</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/Field-mount_base.html">1177</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/Field-mount.html">1144</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/FluentProvider-mount_base.html">718</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/FluentProvider-mount.html">724</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/FluentProviderWithTheme-mount_base.html">85</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/FluentProviderWithTheme-mount.html">99</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">36</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">40</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">73</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">77</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/MakeStyles-mount_base.html">859</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/MakeStyles-mount.html">865</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/Persona-mount_base.html">1793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/Persona-mount.html">1717</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/SpinButton-mount_base.html">1409</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/SpinButton-mount.html">1434</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/SwatchPicker-mount_base.html">1638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-react-components/SwatchPicker-mount.html">1659</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
LayoutMinimalPerf.default | [207](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/LayoutMinimalPerf.default.html) | [195](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.06:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/LayoutMinimalPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
LoaderMinimalPerf.default | [214](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/LoaderMinimalPerf.default.html) | [186](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.15:1
PortalMinimalPerf.default | [93](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/PortalMinimalPerf.default.html) | [81](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.15:1
FlexMinimalPerf.default | [160](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/FlexMinimalPerf.default.html) | [142](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.13:1
FormMinimalPerf.default | [237](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/FormMinimalPerf.default.html) | [214](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.11:1
AvatarMinimalPerf.default | [108](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AvatarMinimalPerf.default.html) | [101](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.07:1
TreeWith60ListItems.default | [97](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TreeWith60ListItems.default.html) | [91](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.07:1
AnimationMinimalPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AnimationMinimalPerf.default.html) | [287](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.06:1
ChatDuplicateMessagesPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [147](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.06:1
DividerMinimalPerf.default | [211](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DividerMinimalPerf.default.html) | [200](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.06:1
DropdownManyItemsPerf.default | [400](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DropdownManyItemsPerf.default.html) | [379](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.06:1
CardMinimalPerf.default | [313](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/CardMinimalPerf.default.html) | [297](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.05:1
CarouselMinimalPerf.default | [265](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/CarouselMinimalPerf.default.html) | [252](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.05:1
ListMinimalPerf.default | [307](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ListMinimalPerf.default.html) | [293](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.05:1
RefMinimalPerf.default | [111](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/RefMinimalPerf.default.html) | [106](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.05:1
ButtonSlotsPerf.default | [313](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ButtonSlotsPerf.default.html) | [302](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
PopupMinimalPerf.default | [356](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/PopupMinimalPerf.default.html) | [343](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.04:1
SkeletonMinimalPerf.default | [205](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/SkeletonMinimalPerf.default.html) | [197](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [292](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TextAreaMinimalPerf.default.html) | [282](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
AlertMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AlertMinimalPerf.default.html) | [152](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.03:1
AttachmentSlotsPerf.default | [645](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AttachmentSlotsPerf.default.html) | [625](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.03:1
DialogMinimalPerf.default | [443](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DialogMinimalPerf.default.html) | [432](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.03:1
ProviderMinimalPerf.default | [206](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ProviderMinimalPerf.default.html) | [200](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.03:1
TextMinimalPerf.default | [200](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TextMinimalPerf.default.html) | [195](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.03:1
ChatMinimalPerf.default | [452](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ChatMinimalPerf.default.html) | [442](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.02:1
HeaderMinimalPerf.default | [210](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/HeaderMinimalPerf.default.html) | [206](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.02:1
ListCommonPerf.default | [389](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ListCommonPerf.default.html) | [382](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ListCommonPerf.default_base.html) | 1.02:1
ListNestedPerf.default | [320](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ListNestedPerf.default.html) | [315](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ListNestedPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [2293](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [2247](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
CustomToolbarPrototype.default | [1482](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/CustomToolbarPrototype.default.html) | [1450](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.02:1
ToolbarMinimalPerf.default | [546](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ToolbarMinimalPerf.default.html) | [535](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.02:1
TreeMinimalPerf.default | [488](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TreeMinimalPerf.default.html) | [479](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.02:1
VideoMinimalPerf.default | [428](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/VideoMinimalPerf.default.html) | [419](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.02:1
BoxMinimalPerf.default | [186](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/BoxMinimalPerf.default.html) | [184](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.01:1
ChatWithPopoverPerf.default | [191](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ChatWithPopoverPerf.default.html) | [190](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [3644](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DatepickerMinimalPerf.default.html) | [3608](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
EmbedMinimalPerf.default | [1862](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/EmbedMinimalPerf.default.html) | [1850](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [535](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/InputMinimalPerf.default.html) | [531](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [721](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [711](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [504](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/MenuMinimalPerf.default.html) | [500](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
RosterPerf.default | [1566](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/RosterPerf.default.html) | [1553](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/RosterPerf.default_base.html) | 1.01:1
ReactionMinimalPerf.default | [204](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ReactionMinimalPerf.default.html) | [201](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.01:1
StatusMinimalPerf.default | [390](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/StatusMinimalPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [1153](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/CheckboxMinimalPerf.default.html) | [1158](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
GridMinimalPerf.default | [182](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/GridMinimalPerf.default.html) | [182](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/GridMinimalPerf.default_base.html) | 1:1
ImageMinimalPerf.default | [218](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ImageMinimalPerf.default.html) | [219](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1:1
ListWith60ListItems.default | [367](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ListWith60ListItems.default.html) | [366](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ListWith60ListItems.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [954](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [954](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [637](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [635](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
TableMinimalPerf.default | [235](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TableMinimalPerf.default.html) | [235](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TableMinimalPerf.default_base.html) | 1:1
ButtonMinimalPerf.default | [88](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ButtonMinimalPerf.default.html) | [89](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.99:1
DropdownMinimalPerf.default | [1394](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DropdownMinimalPerf.default.html) | [1405](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.99:1
HeaderSlotsPerf.default | [466](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/HeaderSlotsPerf.default.html) | [473](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.99:1
RadioGroupMinimalPerf.default | [260](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [262](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.99:1
SegmentMinimalPerf.default | [184](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/SegmentMinimalPerf.default.html) | [186](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.99:1
TooltipMinimalPerf.default | [1247](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TooltipMinimalPerf.default.html) | [1261](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.99:1
AttachmentMinimalPerf.default | [79](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AttachmentMinimalPerf.default.html) | [81](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.98:1
LabelMinimalPerf.default | [222](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/LabelMinimalPerf.default.html) | [226](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.98:1
SliderMinimalPerf.default | [736](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/SliderMinimalPerf.default.html) | [752](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.98:1
TableManyItemsPerf.default | [1109](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TableManyItemsPerf.default.html) | [1128](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/TableManyItemsPerf.default_base.html) | 0.98:1
IconMinimalPerf.default | [388](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/IconMinimalPerf.default.html) | [400](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.97:1
ButtonOverridesMissPerf.default | [644](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [676](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.95:1
AccordionMinimalPerf.default | [85](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AccordionMinimalPerf.default.html) | [91](https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.93:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## 🕵 FluentUIV0 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

✅ No changes found
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/BaseButton-mount_base.html">615</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/BaseButton-mount.html">636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Breadcrumb-mount_base.html">1712</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Breadcrumb-mount.html">1686</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Checkbox-mount_base.html">1703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Checkbox-mount.html">1721</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/CheckboxBase-mount_base.html">1483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/CheckboxBase-mount.html">1477</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ChoiceGroup-mount_base.html">2856</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ChoiceGroup-mount.html">2980</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ComboBox-mount_base.html">658</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ComboBox-mount.html">658</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/CommandBar-mount_base.html">6495</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/CommandBar-mount.html">6464</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ContextualMenu-mount_base.html">12735</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ContextualMenu-mount.html">12551</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DefaultButton-mount_base.html">795</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DefaultButton-mount.html">781</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DetailsRow-mount_base.html">2156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DetailsRow-mount.html">2246</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DetailsRowFast-mount_base.html">2219</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DetailsRowFast-mount.html">2176</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DetailsRowNoStyles-mount_base.html">2052</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DetailsRowNoStyles-mount.html">2052</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Dialog-mount_base.html">2787</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Dialog-mount.html">2740</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DocumentCardTitle-mount_base.html">229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/DocumentCardTitle-mount.html">232</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Dropdown-mount_base.html">1996</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Dropdown-mount.html">2033</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/FocusTrapZone-mount_base.html">1136</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/FocusTrapZone-mount.html">1148</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/FocusZone-mount_base.html">1052</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/FocusZone-mount.html">1081</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedList-mount_base.html">37272</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedList-mount.html">41902</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedList-virtual-rerender_base.html">17918</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedList-virtual-rerender.html">19809</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">51104</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedList-virtual-rerender-with-unmount.html">50787</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedListV2-mount_base.html">222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedListV2-mount.html">229</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedListV2-virtual-rerender_base.html">213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedListV2-virtual-rerender.html">211</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">223</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/IconButton-mount_base.html">1134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/IconButton-mount.html">1131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Label-mount_base.html">344</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Label-mount.html">345</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Layer-mount_base.html">2711</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Layer-mount.html">2752</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Link-mount_base.html">395</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Link-mount.html">399</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/MenuButton-mount_base.html">972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/MenuButton-mount.html">970</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/MessageBar-mount_base.html">21603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/MessageBar-mount.html">21580</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Nav-mount_base.html">2064</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Nav-mount.html">2032</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/OverflowSet-mount_base.html">805</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/OverflowSet-mount.html">792</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Panel-mount_base.html">1804</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Panel-mount.html">1823</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Persona-mount_base.html">739</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Persona-mount.html">764</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Pivot-mount_base.html">874</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Pivot-mount.html">885</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/PrimaryButton-mount_base.html">951</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/PrimaryButton-mount.html">919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Rating-mount_base.html">4637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Rating-mount.html">4560</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/SearchBox-mount_base.html">918</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/SearchBox-mount.html">934</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Shimmer-mount_base.html">1878</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Shimmer-mount.html">1882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Slider-mount_base.html">1364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Slider-mount.html">1348</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/SpinButton-mount_base.html">2970</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/SpinButton-mount.html">2896</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Spinner-mount_base.html">383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Spinner-mount.html">400</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/SplitButton-mount_base.html">1864</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/SplitButton-mount.html">1843</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Stack-mount_base.html">421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Stack-mount.html">406</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/StackWithIntrinsicChildren-mount_base.html">857</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/StackWithIntrinsicChildren-mount.html">829</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/StackWithTextChildren-mount_base.html">2693</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/StackWithTextChildren-mount.html">2698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/SwatchColorPicker-mount_base.html">6284</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/SwatchColorPicker-mount.html">6318</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/TagPicker-mount_base.html">1441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/TagPicker-mount.html">1433</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Text-mount_base.html">385</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Text-mount.html">371</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/TextField-mount_base.html">939</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/TextField-mount.html">955</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ThemeProvider-mount_base.html">849</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ThemeProvider-mount.html">835</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ThemeProvider-virtual-rerender_base.html">582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ThemeProvider-virtual-rerender.html">587</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1272</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1256</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Toggle-mount_base.html">607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/Toggle-mount.html">608</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/buttonNative-mount_base.html">180</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31706/perf-test/buttonNative-mount.html">178</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: .storybook/main.js (hunk 1 above)
Comment (fabricteam) [inline .storybook/main.js:94]: ## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=31706&commitId=47a6fcfecc7e2f36b3383bfa334c095420f17043&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar Converged</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.badgeMask - RTL.normal.chromium.png|0| Removed|

</details>


  <details><summary><b>Card Converged</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Card Converged.appearance - High Contrast.normal.chromium.png|0| Added|

</details>


  <details><summary><b>Card Converged - Selectable</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Card Converged - Selectable.appearance selectable - Subtle.click.chromium.png|0| Removed|
|Card Converged - Selectable.appearance selectable - Subtle.hover.chromium.png|0| Removed|
|Card Converged - Selectable.appearance selectable - Subtle.normal.chromium.png|0| Removed|
|Card Converged - Selectable.appearance selectable - Subtle.selected.chromium.png|0| Removed|

</details>


  <details><summary><b>SwatchPicker Converged</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|SwatchPicker Converged.default - RTL.default.chromium.png|0| Removed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by ling1726** [comment]
/

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>
