### PR TITLE
Fix for WindowProvider utilities always returning window/document/undefined

### LINKED ISSUE #31929: [Bug]: Nullish coalescing operator logic in useWindowEx is incorrect
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

See lib/utilities/dom.js on NPM

### Bug Description

The published @fluentui/react package is incorrectly transpiling ES syntax in the module/`lib` builds. Specifically, this seems to affect use of the new nullish coalescing operator, which the transpiler is giving a lower order of operation than the ternary operator. 

I discovered this after troubleshooting why the `useWindow` context didn't appear to be working, when rendering `@fluentui/react` components inside a popup window. 

## Actual Behavior

useWindowEx is transpiled into (beautified):

```
export var useWindowEx = function () {
	var _a;

	// eslint-disable-next-line no-restricted-globals

	return (
		(_a = useWindow()) !== null && _a !== void 0
			? _a
			: typeof window !== 'undefined'
	)
		? window
		: undefined;
};
```

The original code is:

```
useWindow() ?? typeof window !== 'undefined' ? window : undefined
```

which should be executed as: 
```
useWindow() ?? (typeof window !== 'undefined' ? window : undefined)
```

I suspect adding parantheses in `dom.ts` will fix this particular case.  

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by Jamie0**
## Previous Behavior

useWindowEx/useDocumentEx (and related methods) weren't short-circuit returning the value of the useWindow/useDocument hooks 

## New Behavior

useWindowEx/etc now return the WindowProvider value (if set), window (if defined), or undefined (in that order). 

## Related Issue(s)

- Fixes #31929

### CODE REVIEW

**Comment by Jamie0** [comment]
(@spmonahan - sorry, I seemingly don't have permission to add you as a reviewer, so I'll tag you instead)

**Comment by spmonahan** [comment]
> (@spmonahan - sorry, I seemingly don't have permission to add you as a reviewer, so I'll tag you instead)

Thanks!

You need to run `yarn change` from the repo root to add a change file.

File: packages/react/src/utilities/dom.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ import { useDocument, useWindow, WindowProviderProps } from '@fluentui/react-win
  */
 export const useDocumentEx = () => {
   // eslint-disable-next-line no-restricted-globals
-  return useDocument() ?? typeof document !== 'undefined' ? document : undefined;
+  return useDocument() ?? (typeof document !== 'undefined' ? document : undefined);
```
Comment (spmonahan) [inline packages/react/src/utilities/dom.ts:20]: Would be a nice to add tests to cover these but also not a blocking issue.

**Review by spmonahan — APPROVED** [review]

**Comment by Jamie0** [comment]
@microsoft-github-policy-service agree company="@broadcastradio"

File: packages/react/src/utilities/dom.ts (hunk 1 above)
Comment (Jamie0) [reply packages/react/src/utilities/dom.ts:20]: I'd love to contribute a test but I'm sadly not able to build the monorepo on my daily driver box (2019 MBP) to run jest

Comment (spmonahan) [reply packages/react/src/utilities/dom.ts:20]: No worries. Thanks for the contribution!

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports | Baseline (minified/GZIP) | PR    | Change     |
| :---------------- | -----------------------: | ----: | ---------: |
| <samp>react</samp> <br /> <abbr title='bundle-size/Breadcrumb.fixture.js'>Breadcrumb</abbr> | `202.087 kB`<br />`60.438 kB` | `202.085 kB`<br />`60.436 kB` | `-2 B` <br />`-2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr> | `195.543 kB`<br />`56.617 kB` | `195.542 kB`<br />`56.614 kB` | `-1 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ButtonGrid.fixture.js'>ButtonGrid</abbr> | `180.472 kB`<br />`54.65 kB` | `180.471 kB`<br />`54.647 kB` | `-1 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Callout.fixture.js'>Callout</abbr> | `84.236 kB`<br />`27.607 kB` | `84.235 kB`<br />`27.603 kB` | `-1 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ChoiceGroup.fixture.js'>ChoiceGroup</abbr> | `65.404 kB`<br />`21.469 kB` | `65.403 kB`<br />`21.465 kB` | `-1 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Coachmark.fixture.js'>Coachmark</abbr> | `93.065 kB`<br />`29.412 kB` | `93.063 kB`<br />`29.408 kB` | `-2 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ColorPicker.fixture.js'>ColorPicker</abbr> | `133.171 kB`<br />`41.577 kB` | `133.168 kB`<br />`41.574 kB` | `-3 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ComboBox.fixture.js'>ComboBox</abbr> | `251.985 kB`<br />`72.313 kB` | `251.982 kB`<br />`72.311 kB` | `-3 B` <br />`-2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/CommandBar.fixture.js'>CommandBar</abbr> | `203.124 kB`<br />`60.14 kB` | `203.121 kB`<br />`60.136 kB` | `-3 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ContextualMenu.fixture.js'>ContextualMenu</abbr> | `155.014 kB`<br />`48.169 kB` | `155.013 kB`<br />`48.165 kB` | `-1 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DatePicker.fixture.js'>DatePicker</abbr> | `184.109 kB`<br />`56.156 kB` | `184.108 kB`<br />`56.151 kB` | `-1 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DetailsList.fixture.js'>DetailsList</abbr> | `229.727 kB`<br />`65.873 kB` | `229.725 kB`<br />`65.872 kB` | `-2 B` <br />`-1 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog</abbr> | `211.399 kB`<br />`63.147 kB` | `211.397 kB`<br />`63.141 kB` | `-2 B` <br />`-6 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DocumentCard.fixture.js'>DocumentCard</abbr> | `217.08 kB`<br />`64.437 kB` | `217.078 kB`<br />`64.433 kB` | `-2 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DraggableZone.fixture.js'>DraggableZone</abbr> | `34.243 kB`<br />`11.492 kB` | `34.242 kB`<br />`11.488 kB` | `-1 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown</abbr> | `234.032 kB`<br />`68.66 kB` | `234.029 kB`<br />`68.655 kB` | `-3 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Facepile.fixture.js'>Facepile</abbr> | `210.672 kB`<br />`63.201 kB` | `210.67 kB`<br />`63.199 kB` | `-2 B` <br />`-2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/FloatingPicker.fixture.js'>FloatingPicker</abbr> | `242.128 kB`<br />`69.006 kB` | `242.126 kB`<br />`69.004 kB` | `-2 B` <br />`-2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/FocusTrapZone.fixture.js'>FocusTrapZone</abbr> | `16.979 kB`<br />`5.921 kB` | `16.978 kB`<br />`5.916 kB` | `-1 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Grid.fixture.js'>Grid</abbr> | `180.472 kB`<br />`54.65 kB` | `180.471 kB`<br />`54.647 kB` | `-1 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/GroupedList.fixture.js'>GroupedList</abbr> | `134.954 kB`<br />`40.74 kB` | `134.953 kB`<br />`40.737 kB` | `-1 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/GroupedListV2.fixture.js'>GroupedListV2</abbr> | `122.543 kB`<br />`37.84 kB` | `122.542 kB`<br />`37.835 kB` | `-1 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/HoverCard.fixture.js'>HoverCard</abbr> | `97.109 kB`<br />`30.808 kB` | `97.108 kB`<br />`30.803 kB` | `-1 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Keytip.fixture.js'>Keytip</abbr> | `81.61 kB`<br />`26.75 kB` | `81.609 kB`<br />`26.745 kB` | `-1 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/KeytipLayer.fixture.js'>KeytipLayer</abbr> | `103.41 kB`<br />`32.006 kB` | `103.407 kB`<br />`32.001 kB` | `-3 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Keytips.fixture.js'>Keytips</abbr> | `106.178 kB`<br />`33.006 kB` | `106.175 kB`<br />`33.001 kB` | `-3 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/List.fixture.js'>List</abbr> | `39.333 kB`<br />`12.455 kB` | `39.332 kB`<br />`12.454 kB` | `-1 B` <br />`-1 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/MarqueeSelection.fixture.js'>MarqueeSelection</abbr> | `74.473 kB`<br />`22.448 kB` | `74.471 kB`<br />`22.439 kB` | `-2 B` <br />`-9 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/MessageBar.fixture.js'>MessageBar</abbr> | `190.576 kB`<br />`57.086 kB` | `190.575 kB`<br />`57.084 kB` | `-1 B` <br />`-2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Modal.fixture.js'>Modal</abbr> | `93.57 kB`<br />`30.232 kB` | `93.568 kB`<br />`30.226 kB` | `-2 B` <br />`-6 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Nav.fixture.js'>Nav</abbr> | `188.076 kB`<br />`56.538 kB` | `188.074 kB`<br />`56.533 kB` | `-2 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/OverflowSet.fixture.js'>OverflowSet</abbr> | `33.319 kB`<br />`11.317 kB` | `33.318 kB`<br />`11.313 kB` | `-1 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Panel.fixture.js'>Panel</abbr> | `201.135 kB`<br />`60.045 kB` | `201.132 kB`<br />`60.039 kB` | `-3 B` <br />`-6 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr> | `114.755 kB`<br />`36.483 kB` | `114.753 kB`<br />`36.48 kB` | `-2 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/PersonaCoin.fixture.js'>PersonaCoin</abbr> | `114.755 kB`<br />`36.483 kB` | `114.753 kB`<br />`36.48 kB` | `-2 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Pickers.fixture.js'>Pickers</abbr> | `293.963 kB`<br />`82.41 kB` | `293.961 kB`<br />`82.405 kB` | `-2 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Pivot.fixture.js'>Pivot</abbr> | `188.968 kB`<br />`57.254 kB` | `188.967 kB`<br />`57.251 kB` | `-1 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/PositioningContainer.fixture.js'>PositioningContainer</abbr> | `73.775 kB`<br />`23.762 kB` | `73.773 kB`<br />`23.756 kB` | `-2 B` <br />`-6 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/React.fixture.js'>Fluent UI React (entire library)</abbr> | `1.014 MB`<br />`281.888 kB` | `1.014 MB`<br />`281.886 kB` | `-4 B` <br />`-2 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ScrollablePane.fixture.js'>ScrollablePane</abbr> | `55.463 kB`<br />`17.74 kB` | `55.462 kB`<br />`17.736 kB` | `-1 B` <br />`-4 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SearchBox.fixture.js'>SearchBox</abbr> | `188.851 kB`<br />`56.695 kB` | `188.85 kB`<br />`56.692 kB` | `-1 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SelectedItemsList.fixture.js'>SelectedItemsList</abbr> | `232.625 kB`<br />`67.938 kB` | `232.623 kB`<br />`67.93 kB` | `-2 B` <br />`-8 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ShimmeredDetailsList.fixture.js'>ShimmeredDetailsList</abbr> | `240.502 kB`<br />`68.626 kB` | `240.5 kB`<br />`68.626 kB` | `-2 B` <br />|
| <samp>react</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr> | `57.577 kB`<br />`19.194 kB` | `57.576 kB`<br />`19.191 kB` | `-1 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr> | `192.579 kB`<br />`57.798 kB` | `192.578 kB`<br />`57.795 kB` | `-1 B` <br />`-3 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SwatchColorPicker.fixture.js'>SwatchColorPicker</abbr> | `190.798 kB`<br />`58.14 kB` | `190.796 kB`<br />`58.135 kB` | `-2 B` <br />`-5 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/TeachingBubble.fixture.js'>TeachingBubble</abbr> | `205.855 kB`<br />`61.023 kB` | `205.854 kB`<br />`61.024 kB` | `-1 B` <br />`1 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr> | `241.76 kB`<br />`70.063 kB` | `241.758 kB`<br />`70.062 kB` | `-2 B` <br />`-1 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr> | `87.274 kB`<br />`28.206 kB` | `87.272 kB`<br />`28.203 kB` | `-2 B` <br />`-3 B` |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react</samp> <br /> <abbr title='bundle-size/ActivityItem.fixture.js'>ActivityItem</abbr> | `71.147 kB`<br />`23.33 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Announced.fixture.js'>Announced</abbr> | `38.423 kB`<br />`13.289 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Autofill.fixture.js'>Autofill</abbr> | `15.373 kB`<br />`4.746 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Calendar.fixture.js'>Calendar</abbr> | `121.686 kB`<br />`36.985 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Check.fixture.js'>Check</abbr> | `53.091 kB`<br />`17.837 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr> | `59.879 kB`<br />`19.865 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ChoiceGroupOption.fixture.js'>ChoiceGroupOption</abbr> | `58.659 kB`<br />`19.356 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Color.fixture.js'>Color</abbr> | `7.737 kB`<br />`3.106 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DateTimeUtilities.fixture.js'>DateTimeUtilities</abbr> | `5.244 kB`<br />`1.849 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr> | `19.531 kB`<br />`6.862 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/DragDrop.fixture.js'>DragDrop</abbr> | `8.343 kB`<br />`2.724 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ExtendedPicker.fixture.js'>ExtendedPicker</abbr> | `96.737 kB`<br />`27.87 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Fabric.fixture.js'>Fabric</abbr> | `41.665 kB`<br />`14.358 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/FocusZone.fixture.js'>FocusZone</abbr> | `54.988 kB`<br />`17.451 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Icon.fixture.js'>Icon</abbr> | `51.772 kB`<br />`17.252 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Icons.fixture.js'>Icons</abbr> | `66.309 kB`<br />`24.381 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr> | `46.829 kB`<br />`15.701 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/KeytipData.fixture.js'>KeytipData</abbr> | `13.973 kB`<br />`4.573 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr> | `38.266 kB`<br />`13.244 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Layer.fixture.js'>Layer</abbr> | `48.015 kB`<br />`16.337 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Link.fixture.js'>Link</abbr> | `39.616 kB`<br />`13.649 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Overlay.fixture.js'>Overlay</abbr> | `40.822 kB`<br />`14.083 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/PersonaPresence.fixture.js'>PersonaPresence</abbr> | `57.961 kB`<br />`19.359 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Popup.fixture.js'>Popup</abbr> | `12.242 kB`<br />`4.181 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Positioning.fixture.js'>Positioning</abbr> | `22.736 kB`<br />`7.685 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ProgressIndicator.fixture.js'>ProgressIndicator</abbr> | `39.424 kB`<br />`13.548 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Rating.fixture.js'>Rating</abbr> | `81.906 kB`<br />`26.107 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ResizeGroup.fixture.js'>ResizeGroup</abbr> | `13.286 kB`<br />`4.365 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ResponsiveMode.fixture.js'>ResponsiveMode</abbr> | `8.078 kB`<br />`2.95 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/SelectableOption.fixture.js'>SelectableOption</abbr> | `724 B`<br />`413 B` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Selection.fixture.js'>Selection</abbr> | `42.4 kB`<br />`12.278 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Separator.fixture.js'>Separator</abbr> | `35.315 kB`<br />`12.157 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Shimmer.fixture.js'>Shimmer</abbr> | `49.177 kB`<br />`16.256 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr> | `41.706 kB`<br />`14.477 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Stack.fixture.js'>Stack</abbr> | `41.675 kB`<br />`14.283 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Sticky.fixture.js'>Sticky</abbr> | `32.555 kB`<br />`10.494 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Styling.fixture.js'>Styling</abbr> | `45.981 kB`<br />`15.121 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Text.fixture.js'>Text</abbr> | `36.851 kB`<br />`12.828 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/TextField.fixture.js'>TextField</abbr> | `80.709 kB`<br />`25.324 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Theme.fixture.js'>Theme</abbr> | `43.449 kB`<br />`14.169 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/ThemeGenerator.fixture.js'>ThemeGenerator</abbr> | `12.34 kB`<br />`4.106 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Toggle.fixture.js'>Toggle</abbr> | `46.148 kB`<br />`15.96 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Utilities.fixture.js'>Utilities</abbr> | `82.623 kB`<br />`25.106 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/Viewport.fixture.js'>Viewport</abbr> | `23.831 kB`<br />`7.638 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/WeeklyDayPicker.fixture.js'>WeeklyDayPicker</abbr> | `101.84 kB`<br />`31.805 kB` |
| <samp>react</samp> <br /> <abbr title='bundle-size/WindowProvider.fixture.js'>WindowProvider</abbr> | `1.059 kB`<br />`541 B` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b930d555c568dc5038d4f720182e26e613a77cf1'>b930d555c568dc5038d4f720182e26e613a77cf1</a></sub>
<div id="bundleSizeComment9423"/>

File: change/@fluentui-react-cc5ae7ec-1f14-415d-915b-88de6d5cb7f0.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (fabricteam) [inline change/@fluentui-react-cc5ae7ec-1f14-415d-915b-88de6d5cb7f0.json:1]: ## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=31968&commitId=fc6a5a8c2028531231a8bd071fc57366fdbd0d83&env=prod&clientType=FLUENTUI)


  <details><summary><b>Pivot - Overflow</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Added|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/BaseButton-mount_base.html">616</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/BaseButton-mount.html">638</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Breadcrumb-mount_base.html">1683</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Breadcrumb-mount.html">1674</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Checkbox-mount_base.html">1731</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Checkbox-mount.html">1719</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/CheckboxBase-mount_base.html">1479</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/CheckboxBase-mount.html">1496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ChoiceGroup-mount_base.html">2983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ChoiceGroup-mount.html">3021</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ComboBox-mount_base.html">698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ComboBox-mount.html">680</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/CommandBar-mount_base.html">6611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/CommandBar-mount.html">6649</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ContextualMenu-mount_base.html">14903</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ContextualMenu-mount.html">14028</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DefaultButton-mount_base.html">806</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DefaultButton-mount.html">803</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DetailsRow-mount_base.html">2174</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DetailsRow-mount.html">2210</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DetailsRowFast-mount_base.html">2213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DetailsRowFast-mount.html">2270</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DetailsRowNoStyles-mount_base.html">1992</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DetailsRowNoStyles-mount.html">2029</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Dialog-mount_base.html">2811</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Dialog-mount.html">2734</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DocumentCardTitle-mount_base.html">224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/DocumentCardTitle-mount.html">240</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Dropdown-mount_base.html">2037</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Dropdown-mount.html">2041</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/FocusTrapZone-mount_base.html">1145</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/FocusTrapZone-mount.html">1147</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/FocusZone-mount_base.html">1090</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/FocusZone-mount.html">1080</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedList-mount_base.html">42371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedList-mount.html">42812</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedList-virtual-rerender_base.html">18106</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedList-virtual-rerender.html">20218</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">52187</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedList-virtual-rerender-with-unmount.html">52053</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedListV2-mount_base.html">231</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedListV2-mount.html">238</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedListV2-virtual-rerender_base.html">213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedListV2-virtual-rerender.html">225</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">232</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">235</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/IconButton-mount_base.html">1119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/IconButton-mount.html">1110</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Label-mount_base.html">336</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Label-mount.html">349</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Layer-mount_base.html">2737</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Layer-mount.html">2813</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Link-mount_base.html">398</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Link-mount.html">391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/MenuButton-mount_base.html">977</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/MenuButton-mount.html">1000</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/MessageBar-mount_base.html">21337</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/MessageBar-mount.html">21361</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Nav-mount_base.html">2059</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Nav-mount.html">2031</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/OverflowSet-mount_base.html">797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/OverflowSet-mount.html">761</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Panel-mount_base.html">1860</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Panel-mount.html">1844</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Persona-mount_base.html">727</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Persona-mount.html">760</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Pivot-mount_base.html">918</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Pivot-mount.html">900</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/PrimaryButton-mount_base.html">931</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/PrimaryButton-mount.html">956</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Rating-mount_base.html">4685</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Rating-mount.html">4608</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/SearchBox-mount_base.html">906</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/SearchBox-mount.html">942</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Shimmer-mount_base.html">1892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Shimmer-mount.html">1901</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Slider-mount_base.html">1334</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Slider-mount.html">1339</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/SpinButton-mount_base.html">3007</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/SpinButton-mount.html">3052</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Spinner-mount_base.html">393</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Spinner-mount.html">408</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/SplitButton-mount_base.html">1860</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/SplitButton-mount.html">1914</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Stack-mount_base.html">430</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Stack-mount.html">443</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/StackWithIntrinsicChildren-mount_base.html">875</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/StackWithIntrinsicChildren-mount.html">867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/StackWithTextChildren-mount_base.html">2779</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/StackWithTextChildren-mount.html">2761</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/SwatchColorPicker-mount_base.html">6429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/SwatchColorPicker-mount.html">6425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/TagPicker-mount_base.html">1486</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/TagPicker-mount.html">1485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Text-mount_base.html">387</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Text-mount.html">395</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/TextField-mount_base.html">949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/TextField-mount.html">947</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ThemeProvider-mount_base.html">861</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ThemeProvider-mount.html">856</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ThemeProvider-virtual-rerender_base.html">588</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ThemeProvider-virtual-rerender.html">593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1307</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Toggle-mount_base.html">623</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/Toggle-mount.html">636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/buttonNative-mount_base.html">193</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31968/perf-test/buttonNative-mount.html">191</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>
