### PR TITLE
fix: Replacing bottom border styles with text decoration underline in Link

### LINKED ISSUE #24729: [react-link]: use textDecoration instead of border as underline
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
all browsers
```

### Are you reporting Accessibility issue?

No

### Reproduction

Link in all 3 libraries: https://codesandbox.io/s/competent-wood-0hm8xy?file=/src/index.js

### Bug Description

Currently v9 react-link component uses border-bottom for the underline. 
I think it would be better to change it to text-decoration. Both fabric and northstar uses text-decoration for `Link`. It would be easier for migration if v9 does the same.
 

### Logs

_No response_

### Requested priority

Low

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

`Link` uses `border-bottom` styles for its underline.

## New Behavior

`Link` uses `text-decoration: underline` styles for its underline, which is more inline with most implementations out there.

## Related Issue(s)

Fixes #24729

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                     |    Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                   Change |
| :------------------------------------------------------------------------------------ | --------------------------: | --------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr> | `12.254 kB`<br />`4.956 kB` | `12.205 kB`<br />`4.943 kB` | `-49 B` <br />`-13 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `187.656 kB`<br />`51.96 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `33.359 kB`<br />`11.004 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `5.851 kB`<br />`1.964 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6153d03918584e3cec68c5350211da55a5948d29'>6153d03918584e3cec68c5350211da55a5948d29</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/Avatar-mount_base.html">1169</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/Avatar-mount.html">1206</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/Button-mount_base.html">973</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/Button-mount.html">940</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/FluentProvider-mount_base.html">1439</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/FluentProvider-mount.html">1442</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/FluentProviderWithTheme-mount_base.html">631</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/FluentProviderWithTheme-mount.html">628</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">526</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">593</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">562</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/MakeStyles-mount_base.html">1710</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/MakeStyles-mount.html">1783</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/SpinButton-mount_base.html">2281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24734/perf-test-react-components/SpinButton-mount.html">2372</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-link/src/components/Link/useLinkStyles.ts [hunk 1]
```diff
@@ -10,20 +10,14 @@ export const linkClassNames: SlotClassNames<LinkSlots> = {
...
   // Common styles.
   root: {
     backgroundColor: 'transparent',
-    borderTopStyle: 'none',
-    borderLeftStyle: 'none',
-    borderRightStyle: 'none',
-    borderBottomColor: 'transparent',
-    borderBottomStyle: 'solid',
-    borderBottomWidth: tokens.strokeWidthThin,
+    ...shorthands.borderStyle('none'),
```
Comment (YuanboXue-Amber) [inline packages/react-components/react-link/src/components/Link/useLinkStyles.ts:20]: I think this can be removed entirely? The less styles are used, less classnames are generated by griffel; less classname on element reduces style calculation time. Also border style generates 4 classes.

File: packages/react-components/react-link/src/components/Link/useLinkStyles.ts [hunk 2]
```diff
@@ -58,36 +54,36 @@ const useStyles = makeStyles({
...
     },
   },
   // Overrides when the Link is rendered inline within text.
   inline: {
-    borderBottomColor: tokens.colorBrandForegroundLink,
+    textDecorationColor: tokens.colorBrandForegroundLink,
   },
   // Overrides when the Link is rendered inline within text and appears subtle.
   inlineSubtle: {
     borderBottomColor: tokens.colorNeutralForeground2,
```
Comment (YuanboXue-Amber) [inline packages/react-components/react-link/src/components/Link/useLinkStyles.ts:72]:
```suggestion
    textDecorationColor: tokens.colorNeutralForeground2,
```

File: packages/react-components/react-link/src/components/Link/useLinkStyles.ts (hunk 1 above)
Comment (khmakoto) [reply packages/react-components/react-link/src/components/Link/useLinkStyles.ts]: Removed!

File: packages/react-components/react-link/src/components/Link/useLinkStyles.ts (hunk 2 above)
Comment (khmakoto) [reply packages/react-components/react-link/src/components/Link/useLinkStyles.ts]: Good catch! Fixed!

**Review by behowell — COMMENTED** [review]
`textDecorationColor` defaults to `currentcolor`, and it doesn't look like you ever set it to anything other than the same as the color right? (When the underline should be visible.)

I'd propose replacing all of the places that set `textDecorationColor: tokens.color...`, to instead set `textDecorationLine: 'underline'`. And anywhere that sets `textDecorationColor: 'transparent'` to instead set `textDecorationLine: 'none'`.

This should marginally improve perf (fewer css variable lookups). It would also reduce bundle size (fewer griffel classes since all places that use `textDecorationColor: 'transparent'` would share the same class). It would also let you get rid of the `inlineSubtle` class, since you could just use `inline` in all cases. And it might even avoid a potential bug in the future if someone changes the text color without realizing they need to change the underline color too.

I'll add code suggestions in a few places to clarify.

**Review by YuanboXue-Amber — APPROVED** [review]

**Review by behowell — APPROVED** [review]
