### PR TITLE
Pickers: Improving picker tag selection accessibility

### LINKED ISSUE #12406: Name is not defined for "Remove user" button for people picker elements.
User Experience:
Users who depends on screen reader are facing difficulty as name is not defined for "People picker" remove button.

Repro Steps:
Step 1: Open https://fabricweb.z5.web.core.windows.net/oufr/7.105.2/#/examples/peoplepicker 
Step 2: Search for any user in the people picker search edit field.
Step 3: Navigate to "Remove" button and observe the narrator narration.

Actual Result:
Narrator is announcing as "Remove" button when focus is on remove user button.

Expected Result:
Narrator should announce as "Remove <user> button.

[People Picker.zip](https://github.com/microsoft/fluentui/files/4375051/People.Picker.zip)

### PR DESCRIPTION
**Pull request by smhigley**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #12406 and #14776
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Does a bunch of co-dependent updates on the picker's selected tags, since interaction is tied to roles, which is then tied to naming 😅. The changes are:

- FocusZone is removed by default, though the attributes and public methods are left in, so (hopefully) someone could wrap a picker in their own FocusZone if they wanted to
- The selected tag listitems are not focusable or interactive; only the remove buttons are interactive and focusable
- The remove buttons are named by the tag they remove
- The selection list has a property to give it a unique aria-label, and it falls back on the aria-label of the picker, if provided
- All the picker examples are updated to have good names passed in

### CODE REVIEW

File: packages/react/src/components/pickers/TagPicker/TagItem.tsx [hunk 1]
```diff
@@ -33,23 +33,31 @@ export const TagItemBase = (props: ITagItemProps) => {
     disabled,
   });
 
+  const itemId = getId();
```
Comment (joschect) [inline packages/react/src/components/pickers/TagPicker/TagItem.tsx:36]: Since this is a function component, I believe you'll want to use the `useId` hook to prevent this from being regenerated each time it rerenders.

**Review by joschect — APPROVED** [review]

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Avatar-mount_base.html">936</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Avatar-mount.html">919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/BaseButton-mount_base.html">893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/BaseButton-mount.html">901</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Breadcrumb-mount_base.html">43963</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Breadcrumb-mount.html">44509</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ButtonNext-mount_base.html">552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ButtonNext-mount.html">564</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Checkbox-mount_base.html">1516</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Checkbox-mount.html">1518</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/CheckboxBase-mount_base.html">1259</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/CheckboxBase-mount.html">1275</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ChoiceGroup-mount_base.html">4708</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ChoiceGroup-mount.html">4604</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ComboBox-mount_base.html">971</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ComboBox-mount.html">970</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/CommandBar-mount_base.html">10211</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/CommandBar-mount.html">10109</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ContextualMenu-mount_base.html">6176</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ContextualMenu-mount.html">6220</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DefaultButton-mount_base.html">1119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DefaultButton-mount.html">1103</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DetailsRow-mount_base.html">3602</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DetailsRow-mount.html">3603</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DetailsRowFast-mount_base.html">3636</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DetailsRowFast-mount.html">3592</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DetailsRowNoStyles-mount_base.html">3378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DetailsRowNoStyles-mount.html">3498</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Dialog-mount_base.html">1416</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Dialog-mount.html">1413</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DocumentCardTitle-mount_base.html">1829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/DocumentCardTitle-mount.html">1841</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Dropdown-mount_base.html">3149</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Dropdown-mount.html">3177</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/FocusTrapZone-mount_base.html">1764</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/FocusTrapZone-mount.html">1802</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/FocusZone-mount_base.html">1802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/FocusZone-mount.html">1784</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/IconButton-mount_base.html">1694</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/IconButton-mount.html">1681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Label-mount_base.html">332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Label-mount.html">316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Layer-mount_base.html">1784</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Layer-mount.html">1750</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Link-mount_base.html">448</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Link-mount.html">451</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/MakeStyles-mount_base.html">1761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/MakeStyles-mount.html">1764</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/MenuButton-mount_base.html">1433</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/MenuButton-mount.html">1412</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/MessageBar-mount_base.html">2021</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/MessageBar-mount.html">1990</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Nav-mount_base.html">3229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Nav-mount.html">3127</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/OverflowSet-mount_base.html">1014</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/OverflowSet-mount.html">1014</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Panel-mount_base.html">1396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Panel-mount.html">1376</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Persona-mount_base.html">803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Persona-mount.html">809</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Pivot-mount_base.html">1438</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Pivot-mount.html">1417</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/PrimaryButton-mount_base.html">1279</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/PrimaryButton-mount.html">1244</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Rating-mount_base.html">7559</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Rating-mount.html">7521</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/SearchBox-mount_base.html">1280</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/SearchBox-mount.html">1277</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Shimmer-mount_base.html">2477</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Shimmer-mount.html">2480</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Slider-mount_base.html">1943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Slider-mount.html">1962</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/SpinButton-mount_base.html">4890</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/SpinButton-mount.html">4844</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Spinner-mount_base.html">414</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Spinner-mount.html">411</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/SplitButton-mount_base.html">3087</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/SplitButton-mount.html">3141</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Stack-mount_base.html">495</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Stack-mount.html">492</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/StackWithIntrinsicChildren-mount_base.html">1529</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/StackWithIntrinsicChildren-mount.html">1512</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/StackWithTextChildren-mount_base.html">4480</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/StackWithTextChildren-mount.html">4441</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/SwatchColorPicker-mount_base.html">9902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/SwatchColorPicker-mount.html">10035</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Tabs-mount_base.html">1359</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Tabs-mount.html">1366</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/TagPicker-mount_base.html">2802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/TagPicker-mount.html">2332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/TeachingBubble-mount_base.html">11584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/TeachingBubble-mount.html">11674</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Text-mount_base.html">403</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Text-mount.html">409</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/TextField-mount_base.html">1364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/TextField-mount.html">1375</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ThemeProvider-mount_base.html">1163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ThemeProvider-mount.html">1159</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ThemeProvider-virtual-rerender_base.html">600</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ThemeProvider-virtual-rerender.html">596</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ThemeProviderNext-mount_base.html">16301</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/ThemeProviderNext-mount.html">16017</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Toggle-mount_base.html">824</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/Toggle-mount.html">838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/buttonNative-mount_base.html">114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test/buttonNative-mount.html">118</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.17](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Avatar.Fluent.html) | 0.48 | 0.35:1 | 2000 | 338
🦄 | Button.Fluent | [0.11](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Button.Fluent.html) | 0.2 | 0.55:1 | 5000 | 537
🔧 | Checkbox.Fluent | [0.63](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Checkbox.Fluent.html) | 0.36 | 1.75:1 | 1000 | 632
🎯 | Dialog.Fluent | [0.15](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Dialog.Fluent.html) | 0.21 | 0.71:1 | 5000 | 738
🔧 | Dropdown.Fluent | [3.09](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Dropdown.Fluent.html) | 0.39 | 7.92:1 | 1000 | 3092
🔧 | Icon.Fluent | [0.13](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Icon.Fluent.html) | 0.06 | 2.17:1 | 5000 | 630
🦄 | Image.Fluent | [0.08](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Image.Fluent.html) | 0.13 | 0.62:1 | 5000 | 388
🔧 | Slider.Fluent | [1.58](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Slider.Fluent.html) | 0.43 | 3.67:1 | 1000 | 1577
🔧 | Text.Fluent | [0.07](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.33:1 | 5000 | 364
🦄 | Tooltip.Fluent | [0.14](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Tooltip.Fluent.html) | 0.89 | 0.16:1 | 5000 | 723
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ImageMinimalPerf.default | [403](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ImageMinimalPerf.default.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.07:1
VideoMinimalPerf.default | [657](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/VideoMinimalPerf.default.html) | [615](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.07:1
AttachmentMinimalPerf.default | [174](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AttachmentMinimalPerf.default.html) | [164](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.06:1
CardMinimalPerf.default | [575](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/CardMinimalPerf.default.html) | [542](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.06:1
ChatDuplicateMessagesPerf.default | [309](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.06:1
ListWith60ListItems.default | [661](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ListWith60ListItems.default.html) | [626](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.06:1
LayoutMinimalPerf.default | [386](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/LayoutMinimalPerf.default.html) | [367](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.05:1
SegmentMinimalPerf.default | [371](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/SegmentMinimalPerf.default.html) | [354](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.05:1
IconMinimalPerf.default | [634](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/IconMinimalPerf.default.html) | [606](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.05:1
LabelMinimalPerf.default | [407](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/LabelMinimalPerf.default.html) | [390](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.04:1
PortalMinimalPerf.default | [176](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/PortalMinimalPerf.default.html) | [170](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.04:1
Image.Fluent | [388](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Image.Fluent.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Image.Fluent_base.html) | 1.04:1
ChatMinimalPerf.default | [636](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ChatMinimalPerf.default.html) | [617](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.03:1
GridMinimalPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/GridMinimalPerf.default.html) | [343](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.03:1
StatusMinimalPerf.default | [682](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/StatusMinimalPerf.default.html) | [663](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.03:1
TableMinimalPerf.default | [425](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TableMinimalPerf.default.html) | [414](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.03:1
TreeMinimalPerf.default | [791](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TreeMinimalPerf.default.html) | [769](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.03:1
TreeWith60ListItems.default | [190](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TreeWith60ListItems.default.html) | [185](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.03:1
Tooltip.Fluent | [723](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Tooltip.Fluent.html) | [702](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Tooltip.Fluent_base.html) | 1.03:1
AccordionMinimalPerf.default | [163](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AccordionMinimalPerf.default.html) | [160](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.02:1
AnimationMinimalPerf.default | [428](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AnimationMinimalPerf.default.html) | [418](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.02:1
ButtonSlotsPerf.default | [553](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonSlotsPerf.default.html) | [542](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.02:1
ButtonUseCssNestingPerf.default | [1072](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1055](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [742](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DialogMinimalPerf.default.html) | [731](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
ListNestedPerf.default | [557](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ListNestedPerf.default.html) | [544](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ListNestedPerf.default_base.html) | 1.02:1
ReactionMinimalPerf.default | [388](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ReactionMinimalPerf.default.html) | [379](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.02:1
ToolbarMinimalPerf.default | [946](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ToolbarMinimalPerf.default.html) | [929](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.02:1
Text.Fluent | [364](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Text.Fluent.html) | [357](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Text.Fluent_base.html) | 1.02:1
AvatarMinimalPerf.default | [205](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AvatarMinimalPerf.default.html) | [202](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.01:1
BoxMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/BoxMinimalPerf.default.html) | [362](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.01:1
ButtonUseCssPerf.default | [811](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonUseCssPerf.default.html) | [801](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 1.01:1
ChatWithPopoverPerf.default | [393](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ChatWithPopoverPerf.default.html) | [389](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
HeaderMinimalPerf.default | [371](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/HeaderMinimalPerf.default.html) | [366](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.01:1
HeaderSlotsPerf.default | [770](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/HeaderSlotsPerf.default.html) | [763](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [1259](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1242](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
ListCommonPerf.default | [648](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ListCommonPerf.default.html) | [641](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [895](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/MenuMinimalPerf.default.html) | [887](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
RadioGroupMinimalPerf.default | [448](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [445](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3673](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3649](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1881](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TableManyItemsPerf.default.html) | [1869](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TextMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TextMinimalPerf.default.html) | [351](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.01:1
Avatar.Fluent | [338](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Avatar.Fluent.html) | [336](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Avatar.Fluent_base.html) | 1.01:1
Button.Fluent | [537](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Button.Fluent.html) | [532](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Button.Fluent_base.html) | 1.01:1
Checkbox.Fluent | [632](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Checkbox.Fluent.html) | [624](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Checkbox.Fluent_base.html) | 1.01:1
Dialog.Fluent | [738](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Dialog.Fluent.html) | [729](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Dialog.Fluent_base.html) | 1.01:1
Slider.Fluent | [1577](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Slider.Fluent.html) | [1562](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Slider.Fluent_base.html) | 1.01:1
AttachmentSlotsPerf.default | [1159](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1155](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1:1
CarouselMinimalPerf.default | [472](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/CarouselMinimalPerf.default.html) | [473](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2736](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2728](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [46154](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DatepickerMinimalPerf.default.html) | [46298](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
DropdownManyItemsPerf.default | [690](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DropdownManyItemsPerf.default.html) | [687](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [3107](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DropdownMinimalPerf.default.html) | [3112](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4152](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/EmbedMinimalPerf.default.html) | [4135](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
InputMinimalPerf.default | [1254](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/InputMinimalPerf.default.html) | [1259](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/InputMinimalPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1561](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1558](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [710](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/PopupMinimalPerf.default.html) | [710](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [1005](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ProviderMinimalPerf.default.html) | [1005](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1:1
SkeletonMinimalPerf.default | [369](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/SkeletonMinimalPerf.default.html) | [368](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1613](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/SliderMinimalPerf.default.html) | [1605](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3836](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/CustomToolbarPrototype.default.html) | [3852](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
TooltipMinimalPerf.default | [967](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TooltipMinimalPerf.default.html) | [963](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1691](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1713](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
DividerMinimalPerf.default | [363](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DividerMinimalPerf.default.html) | [366](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.99:1
FormMinimalPerf.default | [410](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/FormMinimalPerf.default.html) | [415](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.99:1
ListMinimalPerf.default | [507](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ListMinimalPerf.default.html) | [512](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.99:1
LoaderMinimalPerf.default | [703](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/LoaderMinimalPerf.default.html) | [708](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.99:1
RosterPerf.default | [1155](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/RosterPerf.default.html) | [1162](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/RosterPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1680](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1694](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
TextAreaMinimalPerf.default | [487](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TextAreaMinimalPerf.default.html) | [490](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.99:1
Dropdown.Fluent | [3092](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Dropdown.Fluent.html) | [3110](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Dropdown.Fluent_base.html) | 0.99:1
Icon.Fluent | [630](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Icon.Fluent.html) | [637](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/Icon.Fluent_base.html) | 0.99:1
AlertMinimalPerf.default | [284](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AlertMinimalPerf.default.html) | [290](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.98:1
ButtonMinimalPerf.default | [176](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonMinimalPerf.default.html) | [180](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 0.98:1
FlexMinimalPerf.default | [285](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/FlexMinimalPerf.default.html) | [296](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/FlexMinimalPerf.default_base.html) | 0.96:1
RefMinimalPerf.default | [250](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/RefMinimalPerf.default.html) | [263](https://fluentuipr.z22.web.core.windows.net/pull/17723/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.95:1

</details><div id="perfComment9423"/>

**Review by joschect — APPROVED** [review]

File: packages/react/src/components/pickers/BasePicker.types.ts [hunk 2]
```diff
@@ -192,6 +192,20 @@ export interface IBasePickerProps<T> extends React.Props<any> {
    */
   selectedItems?: T[];
 
+  /**
+   * Aria label for the displayed selection. A good value would be something like "Selected Contacts"
```
Comment (khmakoto) [inline packages/react/src/components/pickers/BasePicker.types.ts:196]: nit:

```suggestion
   * Aria label for the displayed selection. A good value would be something like "Selected Contacts".
```

**Review by khmakoto — APPROVED** [review]
