### PR TITLE
Avatar a11y: Put role="img" on the root, and other a11y fixes

### LINKED ISSUE #16670: Avatar: Finalize accessibility
This issue tracks following up on the accessibility details of the Avatar spec.

https://github.com/microsoft/fluentui/pull/16524#discussion_r560476731

### LINKED ISSUE #21357: Avatar a11y: Should we add an `alt` prop to provide accessible label when there is no name?
Avatar requires the `name` prop to be set to get the accessibility information correct (it either sets the img's alt attribute, or the aria-label of the initials). However, setting `name` also causes the initials to be displayed instead of the icon. It might also be useful to include additional information in the label, such as presence status.

One possible solution would be to add an `alt` attribute, which can be used instead of, or in addition to the `name`.

### PR DESCRIPTION
**Pull request by behowell**
## Current Behavior

Avatar juggles which of its slots (image, initials, icon) is "visible" to screen readers, and has different rules about what a11y props go on each slot. Also, setting `aria-label` on Avatar doesn't have the desired effect.

## New Behavior

*  Avatar's root has `role="img"`, and all of Avatar's other slots have `aria-hidden`.
* If a name is available, it is set as the `aria-label` on Avatar. Otherwise, the root uses `aria-labelledby` the initials slot.
* If a badge is provided, it is included as a second label in `aria-labelledby`.

## Related Issue
* Fixes #21357
* Fixes #16670

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                          |    Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                                                                Change |
| :----------------------------------------------------------------------------------------- | --------------------------: | ---------------------------: | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr> | `43.755 kB`<br />`12.47 kB` | `44.003 kB`<br />`12.544 kB` | `248 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/IncreaseYellow.svg" /><br />`74 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/IncreaseYellow.svg" /> |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `165.834 kB`<br />`46.987 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.489 kB`<br />`10.636 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/a21bfaceecf201d0c984fa84704148a24f956901'>a21bfaceecf201d0c984fa84704148a24f956901</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-mount_base.html">154</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-mount.html">136</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Avatar-mount_base.html">834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Avatar-mount.html">854</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/BaseButton-mount_base.html">804</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/BaseButton-mount.html">802</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Breadcrumb-mount_base.html">2317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Breadcrumb-mount.html">2367</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ButtonNext-mount_base.html">460</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ButtonNext-mount.html">442</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Checkbox-mount_base.html">1338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Checkbox-mount.html">1336</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/CheckboxBase-mount_base.html">1122</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/CheckboxBase-mount.html">1115</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ChoiceGroup-mount_base.html">4077</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ChoiceGroup-mount.html">4112</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ComboBox-mount_base.html">851</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ComboBox-mount.html">843</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/CommandBar-mount_base.html">8924</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/CommandBar-mount.html">8890</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ContextualMenu-mount_base.html">7323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ContextualMenu-mount.html">7380</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DefaultButton-mount_base.html">988</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DefaultButton-mount.html">995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DetailsRow-mount_base.html">3199</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DetailsRow-mount.html">3182</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DetailsRowFast-mount_base.html">3167</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DetailsRowFast-mount.html">3205</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DetailsRowNoStyles-mount_base.html">3083</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DetailsRowNoStyles-mount.html">3071</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Dialog-mount_base.html">2242</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Dialog-mount.html">2231</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DocumentCardTitle-mount_base.html">169</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/DocumentCardTitle-mount.html">167</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Dropdown-mount_base.html">2784</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Dropdown-mount.html">2773</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderNext-mount_base.html">1721</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderNext-mount.html">1691</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-mount_base.html">154</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-mount.html">136</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-virtual-rerender.html">106</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">185</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">169</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FocusTrapZone-mount_base.html">1581</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FocusTrapZone-mount.html">1627</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FocusZone-mount_base.html">1584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/FocusZone-mount.html">1571</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/IconButton-mount_base.html">1508</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/IconButton-mount.html">1510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Label-mount_base.html">325</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Label-mount.html">312</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Layer-mount_base.html">2536</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Layer-mount.html">2576</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Link-mount_base.html">434</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Link-mount.html">432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/MakeStyles-mount_base.html">1476</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/MakeStyles-mount.html">1501</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/MenuButton-mount_base.html">1301</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/MenuButton-mount.html">1296</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/MessageBar-mount_base.html">1756</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/MessageBar-mount.html">1749</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Nav-mount_base.html">2817</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Nav-mount.html">2823</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/OverflowSet-mount_base.html">979</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/OverflowSet-mount.html">991</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Panel-mount_base.html">2146</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Panel-mount.html">2177</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Persona-mount_base.html">740</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Persona-mount.html">745</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Pivot-mount_base.html">1241</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Pivot-mount.html">1242</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/PrimaryButton-mount_base.html">1156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/PrimaryButton-mount.html">1119</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Rating-mount_base.html">6624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Rating-mount.html">6577</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/SearchBox-mount_base.html">1175</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/SearchBox-mount.html">1176</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Shimmer-mount_base.html">2196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Shimmer-mount.html">2224</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Slider-mount_base.html">1717</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Slider-mount.html">1715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/SpinButton-mount_base.html">4290</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/SpinButton-mount.html">4281</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Spinner-mount_base.html">396</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Spinner-mount.html">388</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/SplitButton-mount_base.html">2689</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/SplitButton-mount.html">2696</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Stack-mount_base.html">483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Stack-mount.html">480</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/StackWithIntrinsicChildren-mount_base.html">1987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/StackWithIntrinsicChildren-mount.html">1993</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/StackWithTextChildren-mount_base.html">4506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/StackWithTextChildren-mount.html">4520</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/SwatchColorPicker-mount_base.html">9707</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/SwatchColorPicker-mount.html">9776</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/TagPicker-mount_base.html">2296</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/TagPicker-mount.html">2258</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/TeachingBubble-mount_base.html">11282</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/TeachingBubble-mount.html">11359</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Text-mount_base.html">393</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Text-mount.html">398</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/TextField-mount_base.html">1252</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/TextField-mount.html">1221</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ThemeProvider-mount_base.html">1030</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ThemeProvider-mount.html">1043</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ThemeProvider-virtual-rerender_base.html">555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ThemeProvider-virtual-rerender.html">568</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1625</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1607</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Toggle-mount_base.html">718</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/Toggle-mount.html">715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/buttonNative-mount_base.html">137</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21526/perf-test/buttonNative-mount.html">149</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: No perf measurements available
<div id="perfComment9423"/>

File: packages/react-avatar/src/components/Avatar/useAvatar.tsx [hunk 1]
```diff
@@ -34,26 +48,40 @@ export const useAvatar_unstable = (props: AvatarProps, ref: React.Ref<HTMLElemen
...
 
-  // If there's no image, make either the initials or icon have role="img" and aria-label={alt}
-  if (!image) {
-    const fallbackSlot = initials || icon;
-    if (fallbackSlot) {
-      fallbackSlot.role ??= 'img';
-      fallbackSlot['aria-label'] ??= alt;
-      delete fallbackSlot['aria-hidden'];
+      // Include the badge in labelledby if it exists
+      if (badge) {
```
Comment (khmakoto) [inline packages/react-avatar/src/components/Avatar/useAvatar.tsx:79]: Should this be an `else if` since you shouldn't have both `aria-label` and `aria-labelledby` set at the same time?

Comment (spmonahan) [reply packages/react-avatar/src/components/Avatar/useAvatar.tsx:79]: I think it's okay to have both:

> The purpose of aria-labelledby is the same as that of aria-label. It provides the user with a recognizable, accessible name for an interactive element. If an element has both attributes set, aria-labelledby will be used. aria-labelledby takes precedence over all other methods of providing an accessible name, including aria-label, label, and the element's inner text.

[Source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby)

That said, since this is something we're setting and not the user of the component it might be nice to apply only one.

Comment (behowell) [reply packages/react-avatar/src/components/Avatar/useAvatar.tsx:79]: It's actually deliberately setting both. The aria-label is the user's name, and aria-labelledby is the avatar itself, plus the badge's label. It's effectively concatenating the name and badge status.

The result is a tree like this, and the final label being "Ben Howell busy"
```html
<span id="avatar-42" aria-label="Ben Howell" aria-labelledby="avatar-42  avatar-42__badge">
   <!-- ... -->
   <span id="avatar-42__badge" aria-label="busy" />
</span>
```

**Review by khmakoto — APPROVED** [review]
