### PR TITLE
fix(react-list): Do not crash during roles/elements validation

### LINKED ISSUE #34467: [Bug]: Changing List navigationMode throws exception
### Component

List

### Package version

9.64.0

### React version

18.2

### Environment

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  npmPackages:
    @fluentui/react-components: ^9.0.0 => 9.64.0 
    @fluentui/react-icons: latest => 2.0.300 
    @types/react: ^17 => 17.0.85 
    @types/react-dom: ^17 => 17.0.26 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1
```

### Current Behavior

Changing `navigationMode` on the `List` component throws an error:

"ListItem cannot be rendered as a div when its parent is not a div"

### Expected Behavior

It should not throw an exception -- it should instead wait to do the validation until the parent re-renders.

We do this because we render a list of data that is conditionally interactive. In some cases, it is just a list of items with no actions associated, and sometimes those actions are enabled and interactive. We don't know this until after we have asynchronously rendered the list, so at first the list is "disabled" by using `navigationMode = "items"`, and then IF we get the information needed to render it as interactive we change it to `composite`, but this throws exceptions.

### Reproduction

https://stackblitz.com/edit/xqpmvqqd?file=src%2Fexample.tsx,package.json

### Steps to reproduce

* Open the provided stackblitz
* Toggle the checkbox
* **Expected:** The list items become interactive
* **Actual:** there is an exception

### Are you reporting an Accessibility issue?

no

### Suggested severity

Medium - Has workaround

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by george-cz**
## Previous Behavior

Previously, when the List navigation mode was changed, the app could crash (in dev mode). This was happening in the element/role validation, because of how our context delays updating the value after the layout effect. This caused the List and ListItem roles/elements get out of sync, triggering the logic.

## New Behavior

The critical parts for layout validation have been moved to a separate, standard React context, which is updated immediately, pre render. This results in proper role/element switching for List and ListItems at the same time, fixing the timing issue.

## Related Issue(s)

- Fixes #34467

### CODE REVIEW

File: packages/react-components/react-list/library/src/components/List/useList.ts [hunk 1]
```diff
@@ -70,9 +70,13 @@ export const useList_unstable = (
...
     const focusable = findAllFocusable(listItemEl);
-    validateProperElementTypes(as, listItemEl.tagName.toLocaleLowerCase());
-    validateProperRolesAreUsed(listRole, itemRole, !!selectionMode, focusable.length > 0);
-    validateGridCellsArePresent(listRole, listItemEl);
+    try {
+      validateProperElementTypes(as, listItemEl.tagName.toLocaleLowerCase());
+      validateProperRolesAreUsed(listRole, itemRole, !!selectionMode, focusable.length > 0);
+      validateGridCellsArePresent(listRole, listItemEl);
+    } catch (e) {
+      console.error('@fluentui/react-list [useList]:\n', e);
```
Comment (ling1726) [inline packages/react-components/react-list/library/src/components/List/useList.ts]: I don't think we should do this. It doesn't actually solve the problem because users will still get an incorrect validation error on the switch.

The issue here is that context selector is being used to pass down values that _**will affect all list items**_ such as `navigationMode` and `listitemRole`. Context selector has an unfortunate limitation that it needs to trigger an update in a `useIsomorphicLayoutEffect` before the current values are passed down to the consumer.

1. User updates the navigationMode
2. listItemRole is still `listItem`, navigationMode is still `item`
3. Validator runs in effect
4. 💣

Since the actual value add of context selectors is to pass down state that only affects a subset of items, just use a normal React context to pass down `navigationMode` and `itemRole`. Those values will always be current and your validator will suceed

image

**Review by ling1726 — CHANGES_REQUESTED** [review]
The changes don't fix the root cause

File: packages/react-components/react-list/library/src/components/List/useListContextValues.ts [hunk 2]
```diff
@@ -5,12 +5,17 @@ export function useListContextValues_unstable(state: ListState): ListContextValu
...
     selection,
-    listItemRole,
     navigationMode,
     validateListItem,
   };
 
+  const synchronousContext = {
+    listItemRole,
+    navigationMode,
+  };
```
Comment (ling1726) [inline packages/react-components/react-list/library/src/components/List/useListContextValues.ts]: React contexts use shallow comparison so you'll need to memoize this
```suggestion
  const synchronousContext = React.useMemo(() => ({
    listItemRole,
    navigationMode,
  }), []);
```

**Review by ling1726 — APPROVED** [review]

File: packages/react-components/react-list/library/src/components/List/List.types.ts [hunk 3]
```diff
@@ -33,17 +33,21 @@ export type ListProps = ComponentProps<ListSlots> & {
 };
 
 export type ListContextValue = {
-  navigationMode: ListNavigationMode | undefined;
   selection?: ListSelectionState;
-  listItemRole: string;
   validateListItem: (listItemElement: HTMLElement) => void;
 };
 
+export type SynchronousListContextValue = {
```
Comment (layershifter) [inline packages/react-components/react-list/library/src/components/List/List.types.ts]: Please rename type for consistency (name starts with `Component`):
- => `ListSynchronousContextValue`
- => `ListStaticContextValue`

Comment (george-cz) [reply packages/react-components/react-list/library/src/components/List/List.types.ts]: thats fair, updated
