### PR TITLE
(fix) Enabling Coachmark to follow the target element

### LINKED ISSUE #18149: Coachmark doesn't follow target element
### Environment Information

I've noticed it in "office-ui-fabric-react": "^7.166.1"; however, it's present on the docs site so it's likely present in multiple versions.

#### Actual behavior:

When scrolling (or if an element is displaced from initial load due to page layout changes) the coachmark is stuck at the original placement of the element rather than updating it's location to the new element placement. 
Weird Offset

#### Expected behavior:

I would expect the coachmark to follow the element that it is attached to. The current jumping makes the user confused as to what they should be clicking and as it applies to both the mark itself and the info box, it makes the component difficult to use.

### Priorities and help requested:

Are you willing to submit a PR to fix? I'm not too familiar with the code base, but if there's an easy fix I'd be willing to help

Requested priority: Blocking

Products/sites affected: Internal Analytics site for MS Edge

### PR DESCRIPTION
**Pull request by czearing**
#### Pull request checklist
- [X] Addresses an existing issue: Fixes #18149
- [X] Include a change request file using `$ yarn change`

#### Description of changes
Fixing a bug that caused Coachmark to stay stuck in its original placement while scrolling.

### CODE REVIEW

File: packages/react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx [hunk 1]
```diff
@@ -203,7 +204,7 @@ function useAutoDismissEvents(
   };
 
   const dismissOnScroll = (ev: Event): void => {
-    if (positions && !preventDismissOnScroll) {
+    if (positionsRef && !preventDismissOnScroll) {
```
Comment (ecraig12345) [inline packages/react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx:207]: Should this be `positionsRef.current`?

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Avatar-mount_base.html">858</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Avatar-mount.html">879</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/BaseButton-mount_base.html">975</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/BaseButton-mount.html">959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Breadcrumb-mount_base.html">2683</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Breadcrumb-mount.html">2691</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ButtonNext-mount_base.html">555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ButtonNext-mount.html">550</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Checkbox-mount_base.html">1653</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Checkbox-mount.html">1633</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/CheckboxBase-mount_base.html">1419</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/CheckboxBase-mount.html">1383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ChoiceGroup-mount_base.html">5049</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ChoiceGroup-mount.html">5160</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ComboBox-mount_base.html">1032</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ComboBox-mount.html">1019</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/CommandBar-mount_base.html">10408</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/CommandBar-mount.html">10356</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ContextualMenu-mount_base.html">6421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ContextualMenu-mount.html">6656</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DefaultButton-mount_base.html">1179</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DefaultButton-mount.html">1172</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DetailsRow-mount_base.html">3960</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DetailsRow-mount.html">3925</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DetailsRowFast-mount_base.html">3914</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DetailsRowFast-mount.html">3985</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DetailsRowNoStyles-mount_base.html">3691</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DetailsRowNoStyles-mount.html">3620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Dialog-mount_base.html">2244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Dialog-mount.html">2275</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DocumentCardTitle-mount_base.html">150</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/DocumentCardTitle-mount.html">156</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Dropdown-mount_base.html">3504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Dropdown-mount.html">3637</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/FocusTrapZone-mount_base.html">1863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/FocusTrapZone-mount.html">1873</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/FocusZone-mount_base.html">1837</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/FocusZone-mount.html">1798</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/IconButton-mount_base.html">1913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/IconButton-mount.html">1816</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Label-mount_base.html">333</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Label-mount.html">338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Layer-mount_base.html">1844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Layer-mount.html">1857</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Link-mount_base.html">485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Link-mount.html">485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/MakeStyles-mount_base.html">1834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/MakeStyles-mount.html">1868</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/MenuButton-mount_base.html">1605</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/MenuButton-mount.html">1595</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/MessageBar-mount_base.html">2047</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/MessageBar-mount.html">2058</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Nav-mount_base.html">3513</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Nav-mount.html">3449</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/OverflowSet-mount_base.html">1093</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/OverflowSet-mount.html">1082</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Panel-mount_base.html">2176</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Panel-mount.html">2172</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Persona-mount_base.html">869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Persona-mount.html">852</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Pivot-mount_base.html">1506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Pivot-mount.html">1452</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/PrimaryButton-mount_base.html">1420</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/PrimaryButton-mount.html">1401</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Rating-mount_base.html">8128</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Rating-mount.html">8351</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/SearchBox-mount_base.html">1391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/SearchBox-mount.html">1396</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Shimmer-mount_base.html">2821</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Shimmer-mount.html">2739</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Slider-mount_base.html">2115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Slider-mount.html">2090</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/SpinButton-mount_base.html">5187</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/SpinButton-mount.html">5270</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Spinner-mount_base.html">419</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Spinner-mount.html">432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/SplitButton-mount_base.html">3369</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/SplitButton-mount.html">3300</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Stack-mount_base.html">546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Stack-mount.html">529</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/StackWithIntrinsicChildren-mount_base.html">1751</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/StackWithIntrinsicChildren-mount.html">1675</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/StackWithTextChildren-mount_base.html">4992</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/StackWithTextChildren-mount.html">4998</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/SwatchColorPicker-mount_base.html">10908</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/SwatchColorPicker-mount.html">10722</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Tabs-mount_base.html">1513</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Tabs-mount.html">1474</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/TagPicker-mount_base.html">2656</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/TagPicker-mount.html">2710</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/TeachingBubble-mount_base.html">12206</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/TeachingBubble-mount.html">12324</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Text-mount_base.html">442</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Text-mount.html">484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/TextField-mount_base.html">1498</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/TextField-mount.html">1486</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ThemeProvider-mount_base.html">1217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ThemeProvider-mount.html">1219</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ThemeProvider-virtual-rerender_base.html">599</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ThemeProvider-virtual-rerender.html">610</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ThemeProviderNext-mount_base.html">6809</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/ThemeProviderNext-mount.html">6772</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Toggle-mount_base.html">872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/Toggle-mount.html">828</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/buttonNative-mount_base.html">118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test/buttonNative-mount.html">110</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
BoxMinimalPerf.default | [422](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/BoxMinimalPerf.default.html) | [384](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.1:1
CarouselMinimalPerf.default | [540](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/CarouselMinimalPerf.default.html) | [491](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.1:1
LayoutMinimalPerf.default | [434](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/LayoutMinimalPerf.default.html) | [396](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.1:1
HeaderMinimalPerf.default | [410](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/HeaderMinimalPerf.default.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.09:1
LabelMinimalPerf.default | [429](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/LabelMinimalPerf.default.html) | [393](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.09:1
RefMinimalPerf.default | [244](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/RefMinimalPerf.default.html) | [223](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.09:1
ButtonMinimalPerf.default | [205](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ButtonMinimalPerf.default.html) | [190](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.08:1
FormMinimalPerf.default | [466](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/FormMinimalPerf.default.html) | [434](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.07:1
GridMinimalPerf.default | [376](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/GridMinimalPerf.default.html) | [356](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.06:1
ListCommonPerf.default | [714](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ListCommonPerf.default.html) | [672](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ListCommonPerf.default_base.html) | 1.06:1
DividerMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DividerMinimalPerf.default.html) | [386](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.05:1
HeaderSlotsPerf.default | [863](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/HeaderSlotsPerf.default.html) | [819](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.05:1
ImageMinimalPerf.default | [414](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ImageMinimalPerf.default.html) | [394](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.05:1
SegmentMinimalPerf.default | [385](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/SegmentMinimalPerf.default.html) | [368](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.05:1
TextAreaMinimalPerf.default | [590](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TextAreaMinimalPerf.default.html) | [564](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.05:1
TooltipMinimalPerf.default | [1072](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TooltipMinimalPerf.default.html) | [1023](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.05:1
VideoMinimalPerf.default | [668](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/VideoMinimalPerf.default.html) | [637](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.05:1
AttachmentMinimalPerf.default | [181](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AttachmentMinimalPerf.default.html) | [174](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.04:1
DropdownManyItemsPerf.default | [755](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DropdownManyItemsPerf.default.html) | [726](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.04:1
InputMinimalPerf.default | [1367](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/InputMinimalPerf.default.html) | [1315](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.04:1
PopupMinimalPerf.default | [617](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/PopupMinimalPerf.default.html) | [596](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.04:1
TableMinimalPerf.default | [456](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TableMinimalPerf.default.html) | [438](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.04:1
TextMinimalPerf.default | [378](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TextMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.04:1
TreeWith60ListItems.default | [213](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TreeWith60ListItems.default.html) | [204](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.04:1
ChatMinimalPerf.default | [667](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ChatMinimalPerf.default.html) | [648](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.03:1
ListMinimalPerf.default | [557](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ListMinimalPerf.default.html) | [543](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.03:1
ProviderMinimalPerf.default | [1142](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ProviderMinimalPerf.default.html) | [1108](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.03:1
ButtonSlotsPerf.default | [626](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ButtonSlotsPerf.default.html) | [614](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.02:1
ChatDuplicateMessagesPerf.default | [317](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [311](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.02:1
ItemLayoutMinimalPerf.default | [1363](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1330](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.02:1
ListWith60ListItems.default | [725](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ListWith60ListItems.default.html) | [708](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [736](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/LoaderMinimalPerf.default.html) | [723](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
MenuButtonMinimalPerf.default | [1829](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1797](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.02:1
PortalMinimalPerf.default | [184](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/PortalMinimalPerf.default.html) | [180](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.02:1
ProviderMergeThemesPerf.default | [1741](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1706](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.02:1
SplitButtonMinimalPerf.default | [4067](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4006](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.02:1
StatusMinimalPerf.default | [743](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/StatusMinimalPerf.default.html) | [729](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [2137](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TableManyItemsPerf.default.html) | [2098](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
AttachmentSlotsPerf.default | [1258](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1250](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.01:1
AvatarMinimalPerf.default | [222](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AvatarMinimalPerf.default.html) | [219](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1827](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1805](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2836](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2819](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [3239](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DropdownMinimalPerf.default.html) | [3204](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
FlexMinimalPerf.default | [305](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/FlexMinimalPerf.default.html) | [301](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [930](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/MenuMinimalPerf.default.html) | [923](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
RadioGroupMinimalPerf.default | [484](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [478](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.01:1
IconMinimalPerf.default | [680](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/IconMinimalPerf.default.html) | [674](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.01:1
ToolbarMinimalPerf.default | [1008](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ToolbarMinimalPerf.default.html) | [994](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.01:1
DialogMinimalPerf.default | [823](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DialogMinimalPerf.default.html) | [826](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4381](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/EmbedMinimalPerf.default.html) | [4370](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
ListNestedPerf.default | [591](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ListNestedPerf.default.html) | [591](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ListNestedPerf.default_base.html) | 1:1
SkeletonMinimalPerf.default | [373](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/SkeletonMinimalPerf.default.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3997](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/CustomToolbarPrototype.default.html) | [4010](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
TreeMinimalPerf.default | [847](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TreeMinimalPerf.default.html) | [850](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1:1
AlertMinimalPerf.default | [305](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AlertMinimalPerf.default.html) | [307](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.99:1
DatepickerMinimalPerf.default | [5604](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5648](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.99:1
RosterPerf.default | [1302](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/RosterPerf.default.html) | [1319](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/RosterPerf.default_base.html) | 0.99:1
AnimationMinimalPerf.default | [453](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AnimationMinimalPerf.default.html) | [462](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.98:1
CardMinimalPerf.default | [616](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/CardMinimalPerf.default.html) | [627](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.98:1
SliderMinimalPerf.default | [1640](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/SliderMinimalPerf.default.html) | [1681](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.98:1
AccordionMinimalPerf.default | [159](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AccordionMinimalPerf.default.html) | [165](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.96:1
ReactionMinimalPerf.default | [406](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ReactionMinimalPerf.default.html) | [421](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.96:1
ChatWithPopoverPerf.default | [392](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ChatWithPopoverPerf.default.html) | [439](https://fluentuipr.z22.web.core.windows.net/pull/18559/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.89:1

</details><div id="perfComment9423"/>

File: packages/react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx [hunk 2]
```diff
@@ -239,7 +239,7 @@ function useAutoDismissEvents(
 
     return () => events.dispose();
     // eslint-disable-next-line react-hooks/exhaustive-deps -- should only run on mount
-  }, []);
+  }, [dismissOnScroll]);
```
Comment (ecraig12345) [inline packages/react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx:242]: I don't think this will work as desired either, since `dismissOnScroll` is re-created on every render right now. You could try wrapping it in `React.useCallback`, but that would require doing the same for `dismissOnLostFocus` and everything it uses (which might be fine depending on what the specific deps are and how often they mutate, or might not be practical).

Can you describe what you figured out that the root cause of the bug is? That will help me with reviewing and/or recommending possible solutions.

Comment (czearing) [reply packages/react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx:242]: The root cause of this bug has to do with dismissOnScroll not properly reading `positions`. In its current state `positions` is seen as undefined and `dismissOnLostFocus` is never called.

**Comment by shandysulen** [comment]
Hello, what is the status of this PR?

**Comment by shandysulen** [comment]
> Hello, what is the status of this PR?

My team is looking to release a feature that includes the `Coachmark` component, but we can't do so until this bug is fixed. Is there anything we can do to progress with the code review?

**Review by ecraig12345 — APPROVED** [review]

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/593c44a49aa586c376cf8cc9a695b9109bd5e608'>593c44a49aa586c376cf8cc9a695b9109bd5e608</a></sub>
<div id="bundleSizeComment9423"/>
