### PR TITLE
fix: Popover, Tooltip: RTL arrow positioning broken

### LINKED ISSUE #20622: Popover, Tooltip: RTL arrow positioning broken
### Environment Information

- **Package version(s)**: 9

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/pedantic-water-jpoje?file=/example.tsx

#### Actual behavior:

Arrow does not appear in RTL on positionings of `before` and `after`

#### Expected behavior:

Arrow does appear in RTL  regardless of positioning

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority:  Normal

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by bsunderhus**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #20622
- [x] Include a change request file using `$ yarn change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8cd4834b7147c0b9120178a67a5706d396498db3'>8cd4834b7147c0b9120178a67a5706d396498db3</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-positioning/src/createArrowStyles.ts [hunk 1]
```diff
@@ -67,15 +77,15 @@ export function createArrowStyles(size?: number): MakeStylesStyleRule<Theme> {
       },
 
       ':global([data-popper-placement^="right"])': {
-        left: 0,
+        [dir === 'ltr' ? 'left' : 'right']: 0,
```
Comment (ling1726) [inline packages/react-positioning/src/createArrowStyles.ts:80]: seems like there is enough logic in here now to do a few tests with the makestyles serializer ?

File: packages/react-tooltip/src/components/Tooltip/useTooltipStyles.ts [hunk 2]
```diff
@@ -40,14 +41,16 @@ const useStyles = makeStyles({
 
   // width and height = arrowHeight * sqrt(2)
   // Update arrowHeight in useTooltip.tsx if this changes
-  arrow: createArrowStyles(8.485),
+  arrowLTR: createArrowStyles({ size: 8.485, dir: 'ltr' }),
```
Comment (ling1726) [inline packages/react-tooltip/src/components/Tooltip/useTooltipStyles.ts:44]: nit: duplicated number

```suggestion
  arrowLTR: createArrowStyles({ size: arrowSize, dir: 'ltr' }),
```

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Avatar-mount_base.html">829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Avatar-mount.html">767</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/BaseButton-mount_base.html">866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/BaseButton-mount.html">866</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Breadcrumb-mount_base.html">2380</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Breadcrumb-mount.html">2182</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ButtonNext-mount_base.html">543</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ButtonNext-mount.html">537</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Checkbox-mount_base.html">1391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Checkbox-mount.html">1395</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/CheckboxBase-mount_base.html">1277</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/CheckboxBase-mount.html">1228</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ChoiceGroup-mount_base.html">4188</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ChoiceGroup-mount.html">4171</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ComboBox-mount_base.html">944</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ComboBox-mount.html">945</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/CommandBar-mount_base.html">8820</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/CommandBar-mount.html">8706</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ContextualMenu-mount_base.html">7452</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ContextualMenu-mount.html">7409</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DefaultButton-mount_base.html">1058</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DefaultButton-mount.html">1025</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DetailsRow-mount_base.html">3374</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DetailsRow-mount.html">3315</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DetailsRowFast-mount_base.html">3384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DetailsRowFast-mount.html">3332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DetailsRowNoStyles-mount_base.html">3176</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DetailsRowNoStyles-mount.html">3179</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Dialog-mount_base.html">2211</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Dialog-mount.html">2285</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DocumentCardTitle-mount_base.html">219</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/DocumentCardTitle-mount.html">211</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Dropdown-mount_base.html">2725</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Dropdown-mount.html">2744</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FluentProviderNext-mount_base.html">1636</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FluentProviderNext-mount.html">1576</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FluentProviderWithTheme-mount_base.html">217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FluentProviderWithTheme-mount.html">205</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">158</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FluentProviderWithTheme-virtual-rerender.html">181</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">239</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">253</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FocusTrapZone-mount_base.html">1671</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FocusTrapZone-mount.html">1652</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FocusZone-mount_base.html">1677</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/FocusZone-mount.html">1656</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/IconButton-mount_base.html">1631</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/IconButton-mount.html">1584</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Label-mount_base.html">411</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Label-mount.html">411</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Layer-mount_base.html">2586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Layer-mount.html">2632</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Link-mount_base.html">492</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Link-mount.html">510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/MakeStyles-mount_base.html">1674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/MakeStyles-mount.html">1672</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/MenuButton-mount_base.html">1374</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/MenuButton-mount.html">1361</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/MessageBar-mount_base.html">1754</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/MessageBar-mount.html">1769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Nav-mount_base.html">2883</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Nav-mount.html">2944</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/OverflowSet-mount_base.html">1064</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/OverflowSet-mount.html">1069</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Panel-mount_base.html">2160</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Panel-mount.html">2227</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Persona-mount_base.html">793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Persona-mount.html">832</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Pivot-mount_base.html">1349</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Pivot-mount.html">1334</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/PrimaryButton-mount_base.html">1216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/PrimaryButton-mount.html">1197</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Rating-mount_base.html">6698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Rating-mount.html">6681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/SearchBox-mount_base.html">1239</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/SearchBox-mount.html">1236</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Shimmer-mount_base.html">2263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Shimmer-mount.html">2318</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Slider-mount_base.html">1796</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Slider-mount.html">1749</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/SpinButton-mount_base.html">4360</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/SpinButton-mount.html">4368</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Spinner-mount_base.html">469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Spinner-mount.html">479</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/SplitButton-mount_base.html">2818</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/SplitButton-mount.html">2776</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Stack-mount_base.html">547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Stack-mount.html">550</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/StackWithIntrinsicChildren-mount_base.html">1572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/StackWithIntrinsicChildren-mount.html">1575</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/StackWithTextChildren-mount_base.html">4049</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/StackWithTextChildren-mount.html">4061</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/SwatchColorPicker-mount_base.html">9054</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/SwatchColorPicker-mount.html">9087</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/TagPicker-mount_base.html">2354</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/TagPicker-mount.html">2450</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/TeachingBubble-mount_base.html">11262</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/TeachingBubble-mount.html">11305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Text-mount_base.html">478</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Text-mount.html">491</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/TextField-mount_base.html">1284</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/TextField-mount.html">1232</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ThemeProvider-mount_base.html">1123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ThemeProvider-mount.html">1079</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ThemeProvider-virtual-rerender_base.html">617</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ThemeProvider-virtual-rerender.html">636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1714</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1718</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Toggle-mount_base.html">825</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/Toggle-mount.html">807</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/buttonNative-mount_base.html">212</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test/buttonNative-mount.html">220</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ButtonMinimalPerf.default | [150](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ButtonMinimalPerf.default.html) | [128](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.17:1
LabelMinimalPerf.default | [337](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/LabelMinimalPerf.default.html) | [296](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.14:1
ListNestedPerf.default | [474](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ListNestedPerf.default.html) | [416](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ListNestedPerf.default_base.html) | 1.14:1
CardMinimalPerf.default | [474](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/CardMinimalPerf.default.html) | [436](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.09:1
HeaderMinimalPerf.default | [319](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/HeaderMinimalPerf.default.html) | [294](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.09:1
FormMinimalPerf.default | [357](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/FormMinimalPerf.default.html) | [331](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.08:1
AttachmentMinimalPerf.default | [143](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AttachmentMinimalPerf.default.html) | [134](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.07:1
ChatMinimalPerf.default | [560](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ChatMinimalPerf.default.html) | [521](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.07:1
HeaderSlotsPerf.default | [630](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/HeaderSlotsPerf.default.html) | [592](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.06:1
TreeWith60ListItems.default | [148](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TreeWith60ListItems.default.html) | [140](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.06:1
BoxMinimalPerf.default | [301](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/BoxMinimalPerf.default.html) | [289](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [424](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TextAreaMinimalPerf.default.html) | [408](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
AttachmentSlotsPerf.default | [931](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AttachmentSlotsPerf.default.html) | [908](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.03:1
ButtonSlotsPerf.default | [473](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ButtonSlotsPerf.default.html) | [461](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
DatepickerMinimalPerf.default | [4714](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4564](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.03:1
EmbedMinimalPerf.default | [3453](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/EmbedMinimalPerf.default.html) | [3366](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.03:1
AlertMinimalPerf.default | [237](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AlertMinimalPerf.default.html) | [232](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [407](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/CarouselMinimalPerf.default.html) | [398](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
DividerMinimalPerf.default | [312](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DividerMinimalPerf.default.html) | [307](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.02:1
DropdownManyItemsPerf.default | [554](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DropdownManyItemsPerf.default.html) | [542](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [438](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ListMinimalPerf.default.html) | [428](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
MenuMinimalPerf.default | [741](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/MenuMinimalPerf.default.html) | [728](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.02:1
RadioGroupMinimalPerf.default | [366](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [358](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.02:1
RefMinimalPerf.default | [209](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/RefMinimalPerf.default.html) | [205](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.02:1
ToolbarMinimalPerf.default | [806](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ToolbarMinimalPerf.default.html) | [791](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.02:1
ChatWithPopoverPerf.default | [315](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ChatWithPopoverPerf.default.html) | [311](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [2586](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DropdownMinimalPerf.default.html) | [2562](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
GridMinimalPerf.default | [278](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/GridMinimalPerf.default.html) | [274](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.01:1
ListCommonPerf.default | [539](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ListCommonPerf.default.html) | [533](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
PopupMinimalPerf.default | [509](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/PopupMinimalPerf.default.html) | [504](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.01:1
PortalMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/PortalMinimalPerf.default.html) | [154](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1610](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TableManyItemsPerf.default.html) | [1587](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [884](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TooltipMinimalPerf.default.html) | [875](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
TreeMinimalPerf.default | [680](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TreeMinimalPerf.default.html) | [673](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.01:1
AccordionMinimalPerf.default | [138](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AccordionMinimalPerf.default.html) | [138](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1:1
ChatDuplicateMessagesPerf.default | [251](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [250](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1:1
LayoutMinimalPerf.default | [318](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/LayoutMinimalPerf.default.html) | [318](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1460](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1462](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
ReactionMinimalPerf.default | [323](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ReactionMinimalPerf.default.html) | [323](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1:1
SkeletonMinimalPerf.default | [303](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/SkeletonMinimalPerf.default.html) | [303](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3617](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3621](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [570](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/StatusMinimalPerf.default.html) | [572](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3485](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/CustomToolbarPrototype.default.html) | [3497](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
VideoMinimalPerf.default | [537](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/VideoMinimalPerf.default.html) | [535](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1:1
AvatarMinimalPerf.default | [170](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AvatarMinimalPerf.default.html) | [171](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [2274](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2306](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
FlexMinimalPerf.default | [247](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/FlexMinimalPerf.default.html) | [250](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/FlexMinimalPerf.default_base.html) | 0.99:1
RosterPerf.default | [1004](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/RosterPerf.default.html) | [1018](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/RosterPerf.default_base.html) | 0.99:1
ProviderMinimalPerf.default | [947](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ProviderMinimalPerf.default.html) | [956](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.99:1
SliderMinimalPerf.default | [1425](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/SliderMinimalPerf.default.html) | [1437](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1064](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/InputMinimalPerf.default.html) | [1083](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.98:1
TableMinimalPerf.default | [336](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TableMinimalPerf.default.html) | [342](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.98:1
AnimationMinimalPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AnimationMinimalPerf.default.html) | [356](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.97:1
DialogMinimalPerf.default | [602](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DialogMinimalPerf.default.html) | [620](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.97:1
IconMinimalPerf.default | [520](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/IconMinimalPerf.default.html) | [538](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.97:1
ItemLayoutMinimalPerf.default | [981](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1020](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.96:1
MenuButtonMinimalPerf.default | [1328](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1384](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.96:1
ImageMinimalPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ImageMinimalPerf.default.html) | [320](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.95:1
SegmentMinimalPerf.default | [270](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/SegmentMinimalPerf.default.html) | [283](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.95:1
ListWith60ListItems.default | [506](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ListWith60ListItems.default.html) | [537](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.94:1
TextMinimalPerf.default | [273](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TextMinimalPerf.default.html) | [294](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.93:1
ButtonOverridesMissPerf.default | [1305](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1449](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.9:1
LoaderMinimalPerf.default | [520](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/LoaderMinimalPerf.default.html) | [582](https://fluentuipr.z22.web.core.windows.net/pull/20845/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.89:1

</details><div id="perfComment9423"/>

File: change/@fluentui-react-popover-2129714c-6c71-4177-895a-c93182c16b6a.json [hunk 3]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
+  "comment": "Adds direction styles for RTL on arrow positioning",
```
Comment (ling1726) [inline change/@fluentui-react-popover-2129714c-6c71-4177-895a-c93182c16b6a.json:3]:
```suggestion
  "comment": "Fixes arrow positioning styles in RTL",
```

File: change/@fluentui-react-positioning-fb0302dc-e0d1-4b28-a149-b336b8ad9460.json [hunk 4]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
+  "comment": "Adds direction styles for RTL on arrow positioning",
```
Comment (ling1726) [inline change/@fluentui-react-positioning-fb0302dc-e0d1-4b28-a149-b336b8ad9460.json:3]:
```suggestion
  "comment": "Fixes arrow positioning styles in RTL",
```

File: change/@fluentui-react-tooltip-564e33d1-ea67-4115-8043-dfb3b26cf70e.json [hunk 5]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "prerelease",
+  "comment": "Adds direction styles for RTL on arrow positioning",
```
Comment (ling1726) [inline change/@fluentui-react-tooltip-564e33d1-ea67-4115-8043-dfb3b26cf70e.json:3]:
```suggestion
  "comment": "Fixes arrow positioning styles in RTL",
```

File: packages/react-positioning/src/createArrowStyles.ts [hunk 6]
```diff
@@ -26,7 +34,9 @@ import type { Theme } from '@fluentui/react-theme';
  *
  * @param size - dimensions of the square arrow element in pixels.
  */
-export function createArrowStyles(size?: number): MakeStylesStyleRule<Theme> {
+export function createArrowStyles(options?: ArrowStylesOptions): MakeStylesStyleRule<Theme> {
+  const size = options?.size;
+  const dir = options?.dir ?? 'ltr';
```
Comment (ling1726) [inline packages/react-positioning/src/createArrowStyles.ts:39]: nit: might be cleaner ? 

```suggestion
export function createArrowStyles(options: ArrowStylesOptions = {}): MakeStylesStyleRule<Theme> {
  const { size, dir = ' ltr' } = options; 
```

**Review by ling1726 — APPROVED** [review]

File: packages/react-positioning/src/createArrowStyles.ts [hunk 7]
```diff
@@ -65,15 +74,15 @@ export function createArrowStyles(size?: number): MakeStylesStyleRule<Theme> {
...
+      [dir === 'ltr' ? 'left' : 'right']: 0,
       '--angle': '90deg',
     },
     ':global([data-popper-placement^="bottom"])': {
       top: 0,
       '--angle': '180deg',
     },
     ':global([data-popper-placement^="left"])': {
-      right: 0,
+      [dir === 'ltr' ? 'right' : 'left']: 0,
```
Comment (layershifter) [inline packages/react-positioning/src/createArrowStyles.ts:85]: This should flip automatically, did you check why it's not happening?

Comment (bsunderhus) [reply packages/react-positioning/src/createArrowStyles.ts:85]: The attribute on html is being flipped automatically! The problem is in our styles overrides, they're not flipping

Comment (bsunderhus) [reply packages/react-positioning/src/createArrowStyles.ts:85]: Oh see what you're meaning, yeah. that's actually weird 👀, perhaps a bug on the `:global` selector?

Comment (bsunderhus) [reply packages/react-positioning/src/createArrowStyles.ts:85]: Due to the usage of `useFluent` to programmatically decide the placement of the popper,

https://github.com/microsoft/fluentui/blob/be9d4afa0a0b36f4de36b2b3609d676ebaa424da/packages/react-positioning/src/usePopper.ts#L89

This means that if it's `RTL` the placement that was `left` becomes `right` and vice versa, and that conflicts with the inversion of `make-styles`.

So `make-styles` expects to find `:global([data-popper-placement^="left"])`  on the cases where the placement is in the `right` for `RTL`, but that won't be true.

Comment (layershifter) [reply packages/react-positioning/src/createArrowStyles.ts:85]: @bsunderhus I see, then `@noflip` should help:

`{ left: '5px /* @noflip */' }`

Can you please try?

Comment (bsunderhus) [reply packages/react-positioning/src/createArrowStyles.ts:85]: Turns out that this is a more complex problem to solve (although the current solution in this PR would be a quick fix). Basically the arrow positioning is decided by [arrow modifier](https://popper.js.org/docs/v2/modifiers/arrow) popper, and there's no option of providing a different direction to the arrow positioning mechanism provided by popper.

The real solution would be to stop using popper arrow positioning modifier and create our custom own that understands direction.

Comment (bsunderhus) [reply packages/react-positioning/src/createArrowStyles.ts]: Didn't know about this annotation @layershifter! thx this helped a lot actually.

**Review by layershifter — APPROVED** [review]
