### PR TITLE
fix: do not use outlineStyle: none in createCustomFocusIndicatorStyle

### LINKED ISSUE #26079: [Bug]: HC mode >Tooltip > focus outline inconsistency > Button with tooltip has focus indicator hardly visible
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 17.39 GB / 31.74 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/34dthr?file=/example.tsx

### Bug Description

Repro steps:
1. Change Windows HC mode into "aquatic" or "desert"
2. open example with default tooltip
https://codesandbox.io/s/34dthr?file=/example.tsx
3. Navigate with keyboard on the  button
4. Observe focus outline

## Actual Behavior
there is focus outline around the button, but outline is thin and is hardly visible when user need to see clearly focus on the screen.
Please compare the default tooltip example outline with with other example. Please see screenshots below. This one is thicker.

I see the same issue with thin focus outline as well in following examples:
https://react.fluentui.dev/?path=/docs/components-tooltip--default#appearance--inverted
https://react.fluentui.dev/?path=/docs/components-tooltip--default#with-arrow
https://react.fluentui.dev/?path=/docs/components-tooltip--default#styled
https://react.fluentui.dev/?path=/docs/components-tooltip--default#custom-mount
https://react.fluentui.dev/?path=/docs/components-tooltip--default#positioning

## Expected Behavior
default tooltip example outline is such thick as it is for others tooltip examples, please see enclosed screenshots and codesandbox

Default tooltip with button:
image
image

Others tooltip with button: https://codesandbox.io/s/u0vp8h?file=/example.tsx
image
image

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by smhigley**
> Edited -- now the outlineStyle exists in `createFocusOutlineStyle`, not `createCustomFocusIndicatorStyle`

## Previous Behavior

When `createCustomFocusIndicatorStyle` is called twice within a component's styles hook, the second call creates `:focus`/`:focus-visible` outline styles that override any styles in the first call of the hook, based on the order in which classes are applied to the component.

An example is when the first call does this:
```js
createCustomFocusIndicatorStyle({
    borderColor: tokens.colorTransparentStroke,
    borderRadius: tokens.borderRadiusMedium,
    outlineColor: tokens.colorTransparentStroke,
    outlineStyle: 'solid',
    outlineWidth: tokens.strokeWidthThick,
    boxShadow: `
      ${tokens.shadow4},
      0 0 0 2px ${tokens.colorStrokeFocus2}
    `,
    zIndex: 1,
}),
```
and the second call does this:
```js
// circular border radius
createCustomFocusIndicatorStyle({
    ...shorthands.borderRadius(tokens.borderRadiusCircular),
}),
```

The second call overrides the `outlineStyle` defined in the first call, because the second className is applied after the first. An example of this is in `useButtonStyles`, where the base style calls `createCustomFocusIndicatorStyle` once, and size and appearance variants call it again style adjustments.

This issue shows how using a large button broke the high contrast mode focus indicator: #26079

## New Behavior

This PR removes `outlineStyle: none` from `createCustomFocusIndicatorStyle` and moves it to `createFocusOutlineStyle`, where the `::after` style is created and is visible in high contrast mode.

## Related Issue(s)

Fixes #26079, #26077, #26062

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                  Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `79.294 kB`<br />`24.443 kB` |  `79.307 kB`<br />`24.438 kB` |  `13 B` <br />`-5 B`  |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |    `84.15 kB`<br />`21.28 kB` |   `84.24 kB`<br />`21.289 kB` |   `90 B` <br />`9 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |    `32.923 kB`<br />`8.61 kB` |   `33.013 kB`<br />`8.623 kB` |  `90 B` <br />`13 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `39.953 kB`<br />`9.933 kB` |   `40.043 kB`<br />`9.966 kB` |  `90 B` <br />`33 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `37.611 kB`<br />`9.942 kB` |   `37.701 kB`<br />`9.953 kB` |  `90 B` <br />`11 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `45.057 kB`<br />`11.323 kB` |  `45.159 kB`<br />`11.347 kB` | `102 B` <br />`24 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `48.753 kB`<br />`10.715 kB` |  `48.855 kB`<br />`10.725 kB` | `102 B` <br />`10 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `77.541 kB`<br />`22.325 kB` |  `77.553 kB`<br />`22.319 kB` |  `12 B` <br />`-6 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `72.485 kB`<br />`20.913 kB` |  `72.497 kB`<br />`20.907 kB` |  `12 B` <br />`-6 B`  |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr>                                                                              |     `28.65 kB`<br />`9.09 kB` |   `28.678 kB`<br />`9.087 kB` |  `28 B` <br />`-3 B`  |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/CheckboxField.fixture.js'>CheckboxField</abbr>                                                                    |   `35.067 kB`<br />`10.89 kB` |  `35.095 kB`<br />`10.885 kB` |  `28 B` <br />`-5 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `59.381 kB`<br />`16.465 kB` |  `59.471 kB`<br />`16.479 kB` |  `90 B` <br />`14 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `187.142 kB`<br />`52.51 kB` | `187.258 kB`<br />`52.514 kB` |  `116 B` <br />`4 B`  |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |  `83.036 kB`<br />`24.754 kB` |  `83.049 kB`<br />`24.751 kB` |  `13 B` <br />`-3 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        |  `118.367 kB`<br />`35.48 kB` |  `118.38 kB`<br />`35.482 kB` |   `13 B` <br />`2 B`  |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `11.862 kB`<br />`4.885 kB` |   `11.875 kB`<br />`4.881 kB` |  `13 B` <br />`-4 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `117.863 kB`<br />`36.405 kB` | `117.876 kB`<br />`36.403 kB` |  `13 B` <br />`-2 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `120.932 kB`<br />`36.934 kB` | `120.945 kB`<br />`36.932 kB` |  `13 B` <br />`-2 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `31.827 kB`<br />`10.316 kB` |  `31.849 kB`<br />`10.312 kB` |  `22 B` <br />`-4 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |  `32.091 kB`<br />`10.183 kB` |   `32.103 kB`<br />`10.18 kB` |  `12 B` <br />`-3 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/SliderField.fixture.js'>SliderField</abbr>                                                                          |  `41.113 kB`<br />`12.903 kB` |  `41.125 kB`<br />`12.902 kB` |  `12 B` <br />`-1 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |  `33.427 kB`<br />`10.581 kB` |    `33.44 kB`<br />`10.58 kB` |  `13 B` <br />`-1 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/SwitchField.fixture.js'>SwitchField</abbr>                                                                          |  `39.745 kB`<br />`12.362 kB` |  `39.758 kB`<br />`12.361 kB` |  `13 B` <br />`-1 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |          Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                         |  `51.083 kB`<br />`14.289 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                               |   `15.006 kB`<br />`6.009 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                       |  `67.313 kB`<br />`18.585 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                   |     `8.617 kB`<br />`3.62 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                   |   `10.382 kB`<br />`4.258 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                 |     `9.424 kB`<br />`3.97 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                      |  `78.698 kB`<br />`25.203 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/ComboboxField.fixture.js'>ComboboxField</abbr>                                         |  `75.901 kB`<br />`25.152 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>                      |  `77.946 kB`<br />`25.146 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> |  `33.843 kB`<br />`11.129 kB` |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                                      |   `57.12 kB`<br />`15.945 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                      | `104.111 kB`<br />`32.062 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                         |   `10.697 kB`<br />`3.938 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                              |    `5.857 kB`<br />`1.978 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                       |    `15.91 kB`<br />`5.931 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                  |    `14.304 kB`<br />`5.72 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroupField.fixture.js'>RadioGroupField</abbr>                                        |    `23.604 kB`<br />`8.65 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                      |   `42.143 kB`<br />`14.79 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/64040a4899e338d8e4e11819975b717276702b9c'>64040a4899e338d8e4e11819975b717276702b9c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/Avatar-mount_base.html">1270</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/Avatar-mount.html">1276</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/Button-mount_base.html">911</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/Button-mount.html">933</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/FluentProvider-mount_base.html">1483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/FluentProvider-mount.html">1481</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/FluentProviderWithTheme-mount_base.html">580</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/FluentProviderWithTheme-mount.html">573</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">538</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">540</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">579</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/MakeStyles-mount_base.html">1964</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/MakeStyles-mount.html">1974</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/Persona-mount_base.html">2802</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/Persona-mount.html">2744</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/SpinButton-mount_base.html">2342</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26089/perf-test-react-components/SpinButton-mount.html">2334</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 36 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26089&commitId=183c0df86d745d3493ab8e772eb54022ac29197c&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1724 screenshots unchanged, 0 screenshots with different dimensions and 36 screenshots with visible difference.


  <details><summary><b>unknown</b> 36 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Accordion Converged.visibility+focus - Dark Mode.focus closed.chromium.png|252| Changed|
|Accordion Converged.visibility+focus - Dark Mode.focus opened.chromium.png|824| Changed|
|Accordion Converged.visibility+focus - High Contrast.focus closed.chromium.png|300| Changed|
|Accordion Converged.visibility+focus - High Contrast.focus opened.chromium.png|982| Changed|
|Dialog.nested - Dark Mode.chromium.png|92| Changed|
|Dialog.nested - High Contrast.chromium.png|92| Changed|
|Dialog.nested - RTL.chromium.png|92| Changed|
|Dialog.nested.chromium.png|92| Changed|
|Dialog.no actions - Dark Mode.chromium.png|2031| Changed|
|Dialog.no actions - High Contrast.chromium.png|794| Changed|
|Dialog.no actions - RTL.chromium.png|692| Changed|
|Dialog.no actions.chromium.png|692| Changed|
|Dialog.no title & no actions - Dark Mode.chromium.png|1954| Changed|
|Dialog.no title & no actions - High Contrast.chromium.png|764| Changed|
|Dialog.no title & no actions - RTL.chromium.png|666| Changed|
|Dialog.no title & no actions.chromium.png|666| Changed|
|Dialog.non-modal - Dark Mode.chromium.png|167| Changed|
|Dialog.non-modal - High Contrast.chromium.png|199| Changed|
|Link Converged - Rendered as anchor.Stand-alone - Dark Mode.focused.chromium.png|202| Changed|
|Link Converged - Rendered as anchor.Stand-alone - Dark Mode.pressed.chromium.png|203| Changed|
|Link Converged - Rendered as anchor.Stand-alone - High Contrast.focused.chromium.png|241| Changed|
|Link Converged - Rendered as anchor.Stand-alone - High Contrast.pressed.chromium.png|241| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable - Dark Mode.focused.chromium.png|767| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable - Dark Mode.pressed.chromium.png|767| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable - High Contrast.focused.chromium.png|914| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable - High Contrast.pressed.chromium.png|914| Changed|
|Link Converged - Rendered as button.Inline - RTL.focused.chromium.png|33| Changed|
|Link Converged - Rendered as button.Inline.focused.chromium.png|33| Changed|
|Link Converged - Rendered as button.Stand-alone - RTL.focused.chromium.png|101| Changed|
|Link Converged - Rendered as button.Stand-alone.focused.chromium.png|101| Changed|
|Menu Converged - groups.default - Dark Mode.chromium.png|327| Changed|
|Menu Converged - groups.default - High Contrast.chromium.png|390| Changed|
|Menu Converged - selection.checkbox - Dark Mode.chromium.png|536| Changed|
|Menu Converged - selection.checkbox - Dark Mode.selected.chromium.png|536| Changed|
|Menu Converged - selection.checkbox - High Contrast.chromium.png|638| Changed|
|Menu Converged - selection.checkbox - High Contrast.selected.chromium.png|637| Changed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Review by spmonahan — APPROVED** [review]

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts [hunk 1]
```diff
@@ -108,7 +108,9 @@ const useRootBaseClassName = makeResetStyles({
   ...createCustomFocusIndicatorStyle({
     borderColor: tokens.colorTransparentStroke,
     borderRadius: tokens.borderRadiusMedium,
-    outline: `${tokens.strokeWidthThick} solid ${tokens.colorTransparentStroke}`,
+    outlineColor: tokens.colorTransparentStroke,
```
Comment (ling1726) [inline packages/react-components/react-button/src/components/Button/useButtonStyles.ts:111]: you can just replace this with

```ts
...shorthands.outline(width, style, color)
```

Comment (ling1726) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:111]: at some point in Griffel, we started stripping all shorthands, which is why using `outline`does not work. I guess we never noticed the effect of that in Fluent until we tested in HC again.

File: packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts [hunk 2]
```diff
@@ -31,10 +31,10 @@ export function createCustomFocusIndicatorStyle<TStyle extends GriffelStyle | Gr
 ): TStyle extends GriffelStyle ? GriffelStyle : GriffelResetStyle {
   return {
     ':focus': {
-      outlineStyle: enableOutline ? undefined : 'none',
+      outlineColor: enableOutline ? undefined : 'transparent',
```
Comment (ling1726) [inline packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts:34]: So I just realized this utility is in our public API 😱. 

So I had a thought about both of our utilities: `createFocusOutline` and `createCustomFocusIndicatorStyle`.
We should disable `outline` in the `createFocusOutline` utility only, since the pseudo element based outline should not use the native outline (we don't want 2 focus rings). Whereas I don't see any reason to actually override `outline` at all in the custom focus indicator, and we should let users of `createCustomFocusInidicatorStyle` to do the necessary changes to `outline`

This would mean that `enableOutline` will no longer used, so we can deprecate the option without removing it to avoid breaking the API

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts (hunk 1 above)
Comment (layershifter) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:111]: @ling1726 this call is under `makeResetStyles` that **accepts** shorthands.

@smhigley can you please check if this change is necessary at all?

Comment (ling1726) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:111]: oh yeah I forgot it was using `makeResetStyles` now, then yeah I can't imagine why this change is necessary either

Comment (smhigley) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts:111]: this change isn't necessary for functionality, I just made it for consistency with the other places we write the same styles.

File: packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts (hunk 2 above)
Comment (smhigley) [reply packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts:34]: That makes sense to me -- If someone really needs `outline` styles for some reason (e.g. they're using it for something non-focus-related?), they always have the out of using `createCustomFocusInidicatorStyle`.

File: packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts [hunk 3]
```diff
@@ -24,19 +24,9 @@ export interface CreateCustomFocusIndicatorStyleOptions {
  */
 export function createCustomFocusIndicatorStyle<TStyle extends GriffelStyle | GriffelResetStyle>(
   style: TStyle,
-  {
-    selector = defaultOptions.selector,
-    enableOutline = false,
-  }: CreateCustomFocusIndicatorStyleOptions = defaultOptions,
+  { selector = defaultOptions.selector }: CreateCustomFocusIndicatorStyleOptions = defaultOptions,
```
Comment (smhigley) [inline packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts:27]: @ling1726 / @layershifter is it OK to remove `enableOutline` here entirely, or would you prefer to keep it and mark it deprecated?

Comment (ling1726) [reply packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts:27]: we should deprecate `enableOutline` (totally my fault for not thinking it through completely when it was introduced)  since the utility is a part of the public API .🙃

File: packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts [hunk 4]
```diff
@@ -66,10 +66,18 @@ const getFocusOutlineStyles = (options: FocusOutlineStyleOptions): GriffelStyle
  * @returns focus outline styles object for @see makeStyles
  */
 export const createFocusOutlineStyle = ({
+  enableOutline = false,
```
Comment (ling1726) [inline packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts:69]: we should not add this to `createFocusOutlineStyle`, this utility uses a pseudo element based focus ring which should not be used with browser `outline`. There is currently no way to use the native outline with this utility and I don't think we should introduce a prop to make this possible. If users want to use native outline they should use `createCusomFocusIndicatorStyle`

File: packages/react-components/react-button/src/components/Button/useButtonStyles.ts (hunk 1 above)
Comment (layershifter) [reply packages/react-components/react-button/src/components/Button/useButtonStyles.ts]: @smhigley here it will emit bigger CSS (as we use `makeResetStyles` that produces a single CSS rule), so I suggest to revert it back.

File: packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts (hunk 4 above)
Comment (smhigley) [reply packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts:69]: @ling1726 I was thinking it might be useful if someone is using the outline style for something other than the focus ring. E.g. they want to use `outline` instead of border for whatever reason, and use it as an inner outline or otherwise styled in a way that does not conflict with the focus styling.

It's relatively rare, but I've definitely seen and implemented `outline` for non-focus reasons. There's still the out of using `createCustomFocusIndicatorStyle`, but it seemed potentially frustrating to make someone create a custom focus indicator when they just want the default one + the ability to use `outline`

Comment (ling1726) [reply packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts:69]: the problem here is that the default focus outline is the same thing as what the pseudo element focus outline is actually doing which is to draw an outline around the focused element. We _**should**_ actually make users choose between one or the other in this case, because our default focus indicator _**is an outline**_

Comment (smhigley) [reply packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts:69]: Here's a bit of a contrived example, but one we might actually want to use:

Toggle button needs an on/off indicator in high contrast mode, so we style an inner outline on the button. Since it's an inner outline, it doesn't conflict with the pseudo-element's focus outline style.

If we were actually using an `outline` style on the button to display focus, I'd style the toggle's on/off inner ring with a pseudo element. But since we're already using one pseudo element for focus, I don't really see a reason to limit the use of `outline` for something like this.

Comment (smhigley) [reply packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts:69]: Just noting here what we chatted about separately: I'm going to remove `enableOutline` for now, and we can revisit it if we have a concrete use case in the future

Comment (smhigley) [reply packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts]: Also a second note, since I didn't realize initially -- this does also change the public API and behavior of `createFocusOutlineStyle`, since it previously supported `enableOutline` via `createCustomFocusIndicatorStyle`.

**Review by ling1726 — APPROVED** [review]

**Comment by smhigley** [comment]
updated `createFocusOutlineStyle` to support `enableOutline` again after chatting w/ @ling1726, since we realized it was already part of the public api signature 🙈

File: change/@fluentui-react-tabster-febe226f-524c-446a-a2b1-769b8ba7180f.json [hunk 5]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (fabricteam) [inline change/@fluentui-react-tabster-febe226f-524c-446a-a2b1-769b8ba7180f.json:1]: ## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 32 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26089&commitId=1306708873ca17f5948d290bb288efd9bb4b54d2&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1837 screenshots unchanged, 0 screenshots with different dimensions and 32 screenshots with visible difference.


  <details><summary><b>unknown</b> 32 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Link Converged - Rendered as anchor.Inline - RTL.focused.chromium.png|162| Changed|
|Link Converged - Rendered as anchor.Inline - RTL.pressed.chromium.png|190| Changed|
|Link Converged - Rendered as anchor.Inline Disabled Focusable.focused.chromium.png|623| Changed|
|Link Converged - Rendered as anchor.Inline Disabled Focusable.pressed.chromium.png|623| Changed|
|Link Converged - Rendered as anchor.Inline.focused.chromium.png|162| Changed|
|Link Converged - Rendered as anchor.Inline.pressed.chromium.png|190| Changed|
|Link Converged - Rendered as anchor.Stand-alone - Dark Mode.focused.chromium.png|178| Changed|
|Link Converged - Rendered as anchor.Stand-alone - Dark Mode.pressed.chromium.png|94| Changed|
|Link Converged - Rendered as anchor.Stand-alone - High Contrast.focused.chromium.png|140| Changed|
|Link Converged - Rendered as anchor.Stand-alone - High Contrast.pressed.chromium.png|84| Changed|
|Link Converged - Rendered as anchor.Stand-alone - RTL.focused.chromium.png|353| Changed|
|Link Converged - Rendered as anchor.Stand-alone - RTL.pressed.chromium.png|440| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable - Dark Mode.focused.chromium.png|489| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable - Dark Mode.pressed.chromium.png|489| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable - High Contrast.focused.chromium.png|533| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable - High Contrast.pressed.chromium.png|533| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable.focused.chromium.png|873| Changed|
|Link Converged - Rendered as anchor.Stand-alone Disabled Focusable.pressed.chromium.png|873| Changed|
|Link Converged - Rendered as anchor.Stand-alone.focused.chromium.png|352| Changed|
|Link Converged - Rendered as anchor.Stand-alone.pressed.chromium.png|440| Changed|
|Link Converged - Rendered as button.Inline - RTL.focused.chromium.png|146| Changed|
|Link Converged - Rendered as button.Inline - RTL.pressed.chromium.png|172| Changed|
|Link Converged - Rendered as button.Inline Disabled Focusable.focused.chromium.png|623| Changed|
|Link Converged - Rendered as button.Inline Disabled Focusable.pressed.chromium.png|623| Changed|
|Link Converged - Rendered as button.Inline.focused.chromium.png|146| Changed|
|Link Converged - Rendered as button.Inline.pressed.chromium.png|172| Changed|
|Link Converged - Rendered as button.Stand-alone - RTL.focused.chromium.png|337| Changed|
|Link Converged - Rendered as button.Stand-alone - RTL.pressed.chromium.png|420| Changed|
|Link Converged - Rendered as button.Stand-alone Disabled Focusable.focused.chromium.png|873| Changed|
|Link Converged - Rendered as button.Stand-alone Disabled Focusable.pressed.chromium.png|873| Changed|
|Link Converged - Rendered as button.Stand-alone.focused.chromium.png|337| Changed|
|Link Converged - Rendered as button.Stand-alone.pressed.chromium.png|420| Changed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Review by ling1726 — APPROVED** [review]

File: packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts [hunk 6]
```diff
@@ -24,19 +25,9 @@ export interface CreateCustomFocusIndicatorStyleOptions {
...
 ): TStyle extends GriffelStyle ? GriffelStyle : GriffelResetStyle {
   return {
-    ':focus': {
```
Comment (ling1726) [inline packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts:33]: maybe let's replace at least with `outlineStyle: 'transparent'` so that it will work by default in HC

Comment (smhigley) [reply packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts:33]: Ah, I actually remember why I didn't do this -- the only time `outlineStyle: none` is applied is when `getFocusOutlineStyles` is also applied with the border-based focus, which will also show up in high contrast mode OK.
