### PR TITLE
Fix - DatePicker contentAfter click-to-open fix

### LINKED ISSUE #29745: [Bug]: DatePicker - custom contentAfter element does not open date picker popup when clicked
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.23580
    CPU: (20) x64 Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
    Memory: 12.80 GB / 31.72 GB
  Browsers:
    Edge: Chromium (119.0.2151.42)
    Internet Explorer: 11.0.23580.1000
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/sweet-artem-xpjp9z?file=/src/example.tsx

## Actual Behavior
When passing in a custom icon to the contentAfter prop on the DatePicker compat component, it breaks the ability to click the icon to open the Date Picker popover

## Expected Behavior
Clicking the contentAfter area of the DatePicker input should always open the DatePicker popover, even if a custom element is passed in

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by stevencomsft**
## Previous Behavior

Passing in a custom icon or element to the contentAfter prop breaks the ability to click the contentAfter area to open the popover

## New Behavior

When passing in a custom icon or element to the contentAfter prop of the DatePicker compat component, it will now act like the default icon and open the popover when clicked

## Related Issue(s)[

(https://github.com/microsoft/fluentui/issues/29745)

- Fixes #29745

### CODE REVIEW

File: packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx [hunk 1]
```diff
@@ -353,18 +353,29 @@ export const useDatePicker_unstable = (props: DatePickerProps, ref: React.Ref<HT
...
-      role: 'combobox',
+  const root = slot.always(
+    {
+      ...restOfProps,
+      // wrap contentAfter to apply icon click logic to allow for opening date picker popup on custom icons
+      contentAfter: restOfProps.contentAfter ? (
+        <span onClick={onIconClick} style={{ all: 'inherit' }}>
+          {restOfProps.contentAfter}
+        </span>
+      ) : undefined,
```
Comment (sopranopillow) [inline packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx:364]: Instead of adding it here, you would need to add it after the root shorthands has been resolved. something like this:
```jsx
  root.contentAfter = <span onClick={onIconClick}>{root.contentAfter}</span>;
```

File: packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx [hunk 2]
```diff
@@ -353,18 +353,29 @@ export const useDatePicker_unstable = (props: DatePickerProps, ref: React.Ref<HT
...
     },
-    elementType: Input,
-  });
+    {
+      defaultProps: {
+        appearance: inputAppearance,
+        'aria-controls': open ? popupSurfaceId : undefined,
+        'aria-expanded': open,
+        'aria-haspopup': 'dialog',
+        contentAfter: <CalendarMonthRegular onClick={onIconClick as unknown as React.MouseEventHandler<SVGElement>} />,
```
Comment (sopranopillow) [inline packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx:372]: you also need to update the contentAfter since you are applying that span to all children.

```suggestion
        contentAfter: <CalendarMonthRegular />,
```

File: packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx [hunk 3]
```diff
@@ -353,18 +353,29 @@ export const useDatePicker_unstable = (props: DatePickerProps, ref: React.Ref<HT
     : 'outline';
 
   const [triggerWrapperRef, popupRef] = usePopupPositioning(props);
-  const root = slot.always(restOfProps, {
```
Comment (sopranopillow) [inline packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx:356]: You are missing a change file, you need to run this in root:
```sh
yarn change
```

File: packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx (hunk 1 above)
Comment (stevencomsft) [reply packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx:364]: Sounds good :) will make these changes. Thanks for the quick review!

Comment (stevencomsft) [reply packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx]: @sopranopillow I have made this change :)

File: packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx (hunk 2 above)
Comment (stevencomsft) [reply packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx]: @sopranopillow I have made this change :)

File: packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx (hunk 3 above)
Comment (stevencomsft) [reply packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx]: @sopranopillow I have made this change :)

File: packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx [hunk 4]
```diff
@@ -385,6 +385,11 @@ export const useDatePicker_unstable = (props: DatePickerProps, ref: React.Ref<HT
   root.onKeyDown = useEventCallback(mergeCallbacks(root.onKeyDown, onInputKeyDown));
   root.onFocus = useEventCallback(mergeCallbacks(root.onFocus, onInputFocus));
   root.onClick = useEventCallback(mergeCallbacks(root.onClick, onInputClick));
+  root.contentAfter = (
+    <span onClick={onIconClick} style={{ all: 'inherit' }}>
+      {root.contentAfter}
+    </span>
+  );
```
Comment (sopranopillow) [inline packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx:392]: Tested this locally and looks like this won't work as expected with styles plus adding a layer of DOM is not ideal. What need to be done here is take advantage that contentAfter is already a span. To achieve this we need to do the following:

(image of how the styles get a little messed up)
image

Resolve contentAfter ourselves to override the onClick prop. This isn't where we override it, but we need to resolve it this way so we can ensure the shorthand is not undefined and to add our default icon.
```jsx
    : 'outline';

  const [triggerWrapperRef, popupRef] = usePopupPositioning(props);

  // Resolving shorthand 👇
  const contentAfter = slot.always(props.contentAfter || {}, {
    defaultProps: {
      children: <CalendarMonthRegular />,
    },
    elementType: 'span',
  });

  const root = slot.always(restOfProps, {
    defaultProps: {
      appearance: inputAppearance,
```

next we have to merge the callback that was possibly provided with our icon onclick callback like this:

```jsx
const inputShorthand = slot.always(props.input, {
    elementType: 'input',
  });
  inputShorthand.ref = useMergedRefs(inputShorthand.ref, ref, rootRef);
  // merge callbacks 👇
  contentAfter.onClick = mergeCallbacks(onIconClick, contentAfter.onClick);
  // we replace the resolved shorthand with our contentAfter shorthand 👇
  root.contentAfter = contentAfter;

  root.input = inputShorthand;
  root.onChange = useEventCallback(mergeCallbacks(root.onChange, onInputChange));
```

sorry for having you make the previous change to then make this change 😥 this is a little more work, but it ensures reusability and makes the change in the DOM look cleaner :)

I've tested this locally, so you can go ahead and make these changes if you're still interested in contributing :) otherwise let me know and I can add the changes to your PR

Comment (stevencomsft) [reply packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx:392]: I like this a lot! And I have learned more about how the slots work :) Will make this change now

Comment (stevencomsft) [reply packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx:392]: Actually @sopranopillow I don't really care all that much about getting contributor credit. If you already have the changes, I'm totally ok with you pushing what you have :) Then I can see exactly what you have changed and use it as a learning exercise

Comment (sopranopillow) [reply packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx]: I think you'll still get the contribution :)

**Review by sopranopillow — APPROVED** [review]

File: packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx (hunk 4 above)
Comment (stevencomsft) [reply packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx]: Awesome, looks great :D thanks for the help!

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/baa8387b51ae5e028dd7c2f98827ab9bd749f90e'>baa8387b51ae5e028dd7c2f98827ab9bd749f90e</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>
