### PR TITLE
fix(scripts): fix create-package to use workspace.json as generic sou…

### LINKED ISSUE #22960: `create-package` script not working after package moves
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
-
```

### Are you reporting Accessibility issue?

no

### Reproduction

-

### Bug Description

`yarn-create` package fails for both `node` and `react` targets.
`convergedReferencePackages` point to packages which do not exist in the expected path.

target: `node`
```
❯ yarn create-package
yarn run v1.23.34
$ plop --plopfile ./scripts/create-package/plopfile.ts --dest . --require ./scripts/ts-node-register
? Package name (do NOT include @fluentui prefix): react-theme-sass
? Package target: node
? Package description: wes
? Provide team that owns this package @microsoft/teams-prg
? Will this package have tests? Yes
? Is this a converged package? Yes
✔  +! 2 files added
 -> /packages/react-components/react-theme-sass/.npmignore
 -> /packages/react-components/react-theme-sass/LICENSE
✔  +! 7 files added
 -> /packages/react-components/react-theme-sass/.eslintrc.json
 -> /packages/react-components/react-theme-sass/README.md
 -> /packages/react-components/react-theme-sass/jest.config.js
 -> /packages/react-components/react-theme-sass/just.config.ts
 -> /packages/react-components/react-theme-sass/package.json
 -> /packages/react-components/react-theme-sass/tsconfig.json
 -> /packages/react-components/react-theme-sass/src/index.ts
✖  +- /Users/mistastn/devel/fluentui/packages/babel-make-styles/package.json: ENOENT: no such file or directory, open '/Users/mistastn/devel/fluentui/packages/babel-make-styles/package.json'
✖  +- packages/react-components/react-theme-sass/tsconfig.json Aborted due to previous action failure
✖  -> Aborted due to previous action failure
✖  -> Aborted due to previous action failure
✖  -> Aborted due to previous action failure
✨  Done in 18.56s. Peak memory usage 31.77MB.
```

target: `react`
```
❯ yarn create-package
yarn run v1.23.34
$ plop --plopfile ./scripts/create-package/plopfile.ts --dest . --require ./scripts/ts-node-register
? Package name (do NOT include @fluentui prefix): react-theme-sass
? Package target: react
? Package description: React components for building web experiences
? Provide team that owns this package @microsoft/teams-prg
? Is this a converged package? Yes
✔  +! 2 files added
 -> /packages/react-components/react-theme-sass/.npmignore
 -> /packages/react-components/react-theme-sass/LICENSE
✔  +! 12 files added
 -> /packages/react-components/react-theme-sass/.babelrc.json
 -> /packages/react-components/react-theme-sass/.eslintrc.json
 -> /packages/react-components/react-theme-sass/README.md
 -> /packages/react-components/react-theme-sass/Spec.md
 -> /packages/react-components/react-theme-sass/jest.config.js
 -> /packages/react-components/react-theme-sass/just.config.ts
 -> /packages/react-components/react-theme-sass/package.json
 -> /packages/react-components/react-theme-sass/tsconfig.json
 -> /packages/react-components/react-theme-sass/config/api-extractor.json
 -> /packages/react-components/react-theme-sass/config/tests.js
 -> /packages/react-components/react-theme-sass/etc/react-theme-sass.api.md
 -> /packages/react-components/react-theme-sass/src/index.ts
✖  +- /Users/mistastn/devel/fluentui/packages/react-provider/package.json: ENOENT: no such file or directory, open '/Users/mistastn/devel/fluentui/packages/react-provider/package.json'
✖  +- packages/react-components/react-theme-sass/tsconfig.json Aborted due to previous action failure
✖  -> Aborted due to previous action failure
✖  -> Aborted due to previous action failure
✖  -> Aborted due to previous action failure
✨  Done in 44.94s. Peak memory usage 31.77MB.
```

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by Hotell**
…rce of truth for package metadata

## Current Behavior

`yarn create-package` doesn't work

## New Behavior

`yarn create-package` works

## Related Issue(s)

Fixes #22960

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr>                                                      |    `2.936 kB`<br />`1.212 kB` |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `74.251 kB`<br />`22.683 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |   `45.588 kB`<br />`13.32 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |    `20.985 kB`<br />`6.62 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `21.898 kB`<br />`6.925 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |    `22.21 kB`<br />`6.672 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `32.927 kB`<br />`9.036 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `39.854 kB`<br />`10.26 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |    `35.11 kB`<br />`9.783 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `42.369 kB`<br />`11.085 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `47.52 kB`<br />`10.603 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |   `60.746 kB`<br />`17.41 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `56.031 kB`<br />`16.147 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `7.793 kB`<br />`3.327 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `9.363 kB`<br />`3.841 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |     `7.765 kB`<br />`3.35 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox</abbr>                                                                              |  `61.412 kB`<br />`20.982 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `181.156 kB`<br />`50.603 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `34.078 kB`<br />`11.098 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |    `15.55 kB`<br />`5.595 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |   `10.012 kB`<br />`3.982 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |   `22.163 kB`<br />`7.295 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.546 kB`<br />`3.574 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `11.422 kB`<br />`4.648 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `111.638 kB`<br />`34.054 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `114.813 kB`<br />`34.527 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                                                               |   `10.792 kB`<br />`4.124 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `103.74 kB`<br />`31.544 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |     `6.272 kB`<br />`2.17 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePositioning</abbr>                                                                    |   `23.828 kB`<br />`8.283 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `14.127 kB`<br />`5.299 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `29.483 kB`<br />`10.098 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |   `13.664 kB`<br />`5.486 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                                                    |   `17.138 kB`<br />`6.367 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |   `25.557 kB`<br />`8.266 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |  `42.132 kB`<br />`11.895 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `18.158 kB`<br />`6.029 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `25.439 kB`<br />`8.247 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `10.904 kB`<br />`4.298 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `14.226 kB`<br />`4.714 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                                                              |   `21.207 kB`<br />`7.165 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>                                                        |            `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                                                                  |   `31.363 kB`<br />`7.043 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                                                                |   `19.806 kB`<br />`5.699 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `43.584 kB`<br />`14.992 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                                                                       |          `189 B`<br />`161 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d5f8088dc5bb51cb0579933456d03b551e5b875d'>d5f8088dc5bb51cb0579933456d03b551e5b875d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
TreeWith60ListItems.default | [188](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TreeWith60ListItems.default.html) | [166](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.13:1
FlexMinimalPerf.default | [302](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/FlexMinimalPerf.default.html) | [275](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.1:1
CarouselMinimalPerf.default | [535](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/CarouselMinimalPerf.default.html) | [492](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.09:1
TextMinimalPerf.default | [371](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TextMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.09:1
ButtonSlotsPerf.default | [610](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ButtonSlotsPerf.default.html) | [563](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.08:1
PortalMinimalPerf.default | [168](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/PortalMinimalPerf.default.html) | [156](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.08:1
AttachmentMinimalPerf.default | [158](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AttachmentMinimalPerf.default.html) | [149](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.06:1
ButtonMinimalPerf.default | [189](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ButtonMinimalPerf.default.html) | [179](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.06:1
LabelMinimalPerf.default | [407](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/LabelMinimalPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.06:1
AttachmentSlotsPerf.default | [1147](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1091](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.05:1
TableMinimalPerf.default | [424](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TableMinimalPerf.default.html) | [404](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.05:1
BoxMinimalPerf.default | [357](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/BoxMinimalPerf.default.html) | [342](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.04:1
CardMinimalPerf.default | [632](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/CardMinimalPerf.default.html) | [605](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.04:1
ChatDuplicateMessagesPerf.default | [308](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [297](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.04:1
ListCommonPerf.default | [706](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ListCommonPerf.default.html) | [682](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ListCommonPerf.default_base.html) | 1.04:1
MenuMinimalPerf.default | [901](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/MenuMinimalPerf.default.html) | [866](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.04:1
ProviderMinimalPerf.default | [407](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ProviderMinimalPerf.default.html) | [392](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.04:1
SegmentMinimalPerf.default | [374](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/SegmentMinimalPerf.default.html) | [360](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.04:1
ChatWithPopoverPerf.default | [427](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ChatWithPopoverPerf.default.html) | [414](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.03:1
DatepickerMinimalPerf.default | [6001](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5849](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.03:1
ItemLayoutMinimalPerf.default | [1290](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1257](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
RadioGroupMinimalPerf.default | [479](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [467](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.03:1
CustomToolbarPrototype.default | [2752](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/CustomToolbarPrototype.default.html) | [2678](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.03:1
TreeMinimalPerf.default | [855](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TreeMinimalPerf.default.html) | [830](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.03:1
DialogMinimalPerf.default | [813](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DialogMinimalPerf.default.html) | [794](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
DropdownManyItemsPerf.default | [741](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DropdownManyItemsPerf.default.html) | [729](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.02:1
InputMinimalPerf.default | [1352](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/InputMinimalPerf.default.html) | [1332](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [538](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ListMinimalPerf.default.html) | [528](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [715](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/LoaderMinimalPerf.default.html) | [703](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
RosterPerf.default | [1259](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/RosterPerf.default.html) | [1236](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/RosterPerf.default_base.html) | 1.02:1
RefMinimalPerf.default | [226](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/RefMinimalPerf.default.html) | [221](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.02:1
IconMinimalPerf.default | [628](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/IconMinimalPerf.default.html) | [617](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.02:1
VideoMinimalPerf.default | [694](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/VideoMinimalPerf.default.html) | [681](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.02:1
DividerMinimalPerf.default | [373](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DividerMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.01:1
GridMinimalPerf.default | [359](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/GridMinimalPerf.default.html) | [354](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.01:1
HeaderSlotsPerf.default | [824](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/HeaderSlotsPerf.default.html) | [813](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.01:1
ImageMinimalPerf.default | [410](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ImageMinimalPerf.default.html) | [404](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.01:1
ReactionMinimalPerf.default | [411](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ReactionMinimalPerf.default.html) | [406](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [2065](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TableManyItemsPerf.default.html) | [2043](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [3083](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DropdownMinimalPerf.default.html) | [3082](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
HeaderMinimalPerf.default | [376](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/HeaderMinimalPerf.default.html) | [376](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
LayoutMinimalPerf.default | [366](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/LayoutMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1778](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/SliderMinimalPerf.default.html) | [1780](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [4646](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4651](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1572](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1594](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [790](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ChatMinimalPerf.default.html) | [796](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [2826](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2860](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
ListNestedPerf.default | [559](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ListNestedPerf.default.html) | [564](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ListNestedPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1184](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1194](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
SkeletonMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/SkeletonMinimalPerf.default.html) | [357](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.99:1
StatusMinimalPerf.default | [711](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/StatusMinimalPerf.default.html) | [717](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.99:1
AccordionMinimalPerf.default | [152](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AccordionMinimalPerf.default.html) | [155](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.98:1
AlertMinimalPerf.default | [278](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AlertMinimalPerf.default.html) | [285](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.98:1
EmbedMinimalPerf.default | [4226](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/EmbedMinimalPerf.default.html) | [4291](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.98:1
ListWith60ListItems.default | [637](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ListWith60ListItems.default.html) | [647](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.98:1
MenuButtonMinimalPerf.default | [1743](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1784](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.98:1
PopupMinimalPerf.default | [619](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/PopupMinimalPerf.default.html) | [629](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.98:1
TextAreaMinimalPerf.default | [520](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TextAreaMinimalPerf.default.html) | [528](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.98:1
TooltipMinimalPerf.default | [1208](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TooltipMinimalPerf.default.html) | [1234](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 0.98:1
ToolbarMinimalPerf.default | [979](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1008](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.97:1
AvatarMinimalPerf.default | [195](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AvatarMinimalPerf.default.html) | [205](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.95:1
FormMinimalPerf.default | [436](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/FormMinimalPerf.default.html) | [461](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.95:1
AnimationMinimalPerf.default | [545](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AnimationMinimalPerf.default.html) | [587](https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.93:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/BaseButton-mount_base.html">803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/BaseButton-mount.html">792</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Breadcrumb-mount_base.html">2342</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Breadcrumb-mount.html">2342</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Checkbox-mount_base.html">1281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Checkbox-mount.html">1336</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/CheckboxBase-mount_base.html">1116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/CheckboxBase-mount.html">1078</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ChoiceGroup-mount_base.html">4115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ChoiceGroup-mount.html">4068</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ComboBox-mount_base.html">877</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ComboBox-mount.html">891</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/CommandBar-mount_base.html">9094</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/CommandBar-mount.html">9089</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ContextualMenu-mount_base.html">10608</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ContextualMenu-mount.html">10665</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DefaultButton-mount_base.html">985</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DefaultButton-mount.html">1038</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DetailsRow-mount_base.html">3305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DetailsRow-mount.html">3301</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DetailsRowFast-mount_base.html">3423</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DetailsRowFast-mount.html">3391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DetailsRowNoStyles-mount_base.html">3235</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DetailsRowNoStyles-mount.html">3305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Dialog-mount_base.html">2072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Dialog-mount.html">1966</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DocumentCardTitle-mount_base.html">140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/DocumentCardTitle-mount.html">165</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Dropdown-mount_base.html">2931</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Dropdown-mount.html">2884</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/FocusTrapZone-mount_base.html">1648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/FocusTrapZone-mount.html">1620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/FocusZone-mount_base.html">1601</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/FocusZone-mount.html">1562</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/IconButton-mount_base.html">1522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/IconButton-mount.html">1524</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Label-mount_base.html">309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Label-mount.html">297</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Layer-mount_base.html">2572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Layer-mount.html">2676</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Link-mount_base.html">393</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Link-mount.html">404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/MenuButton-mount_base.html">1326</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/MenuButton-mount.html">1282</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/MessageBar-mount_base.html">1844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/MessageBar-mount.html">1920</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Nav-mount_base.html">2892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Nav-mount.html">2828</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/OverflowSet-mount_base.html">946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/OverflowSet-mount.html">987</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Panel-mount_base.html">1926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Panel-mount.html">1956</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Persona-mount_base.html">869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Persona-mount.html">885</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Pivot-mount_base.html">1254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Pivot-mount.html">1273</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/PrimaryButton-mount_base.html">1091</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/PrimaryButton-mount.html">1136</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Rating-mount_base.html">6814</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Rating-mount.html">6626</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/SearchBox-mount_base.html">1141</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/SearchBox-mount.html">1139</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Shimmer-mount_base.html">2145</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Shimmer-mount.html">2158</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Slider-mount_base.html">1678</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Slider-mount.html">1676</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/SpinButton-mount_base.html">4592</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/SpinButton-mount.html">4478</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Spinner-mount_base.html">367</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Spinner-mount.html">397</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/SplitButton-mount_base.html">2715</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/SplitButton-mount.html">2727</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Stack-mount_base.html">437</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Stack-mount.html">444</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/StackWithIntrinsicChildren-mount_base.html">1942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/StackWithIntrinsicChildren-mount.html">2037</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/StackWithTextChildren-mount_base.html">4541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/StackWithTextChildren-mount.html">4590</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/SwatchColorPicker-mount_base.html">10295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/SwatchColorPicker-mount.html">10270</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/TagPicker-mount_base.html">2458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/TagPicker-mount.html">2428</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/TeachingBubble-mount_base.html">90650</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/TeachingBubble-mount.html">90819</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Text-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Text-mount.html">362</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/TextField-mount_base.html">1200</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/TextField-mount.html">1226</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ThemeProvider-mount_base.html">1008</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ThemeProvider-mount.html">1082</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ThemeProvider-virtual-rerender_base.html">555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ThemeProvider-virtual-rerender.html">550</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1665</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1708</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Toggle-mount_base.html">703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/Toggle-mount.html">681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/buttonNative-mount_base.html">106</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23249/perf-test/buttonNative-mount.html">108</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by TristanWatanabe — APPROVED** [review]
LGTM! Pipeline failure seems to be unrelated to this PR

File: scripts/create-package/plopfile.ts [hunk 1]
```diff
@@ -188,11 +188,21 @@ function replaceVersionsFromReference(
...
+  if (referencePackages.length === 0) {
+    return;
+  }
+
   const depTypes = ['dependencies', 'devDependencies', 'peerDependencies'] as const;
 
   // Read the package.json files of the given reference packages and combine into one object.
   // This way if a dep is defined in any of them, it can easily be copied to newPackageJson.
-  const packageJsons = referencePackages.map(pkg => fs.readJSONSync(path.join(root, 'packages', pkg, 'package.json')));
+  // const packageJsons = referencePackages.map(pkg => fs.readJSONSync(path.join(root, 'packages', pkg, 'package.json')));
```
Comment (TristanWatanabe) [inline scripts/create-package/plopfile.ts:199]: Should this comment be removed?

Comment (Hotell) [reply scripts/create-package/plopfile.ts:199]: it should, thank you! :D #shameOnMe
