### PR TITLE
fix(react) Icon roles for named and unnamed icons

### LINKED ISSUE #12256: Icons set aria-label on generic role
### Environment Information

- **Package version(s)**: latest / 7.101
- **Browser and OS versions**: all

### Describe the issue:

The suggested way to label non-presentational icons is with `aria-label`, but that is currently applied to an `<i>` element without a role. That element maps to a generic role / no role by default, and does not support having an accessible name (https://w3c.github.io/aria/#namefromprohibited).

Image icons with an alt but no aria-label also have an issue -- they're hidden by default even with the `alt`, since `aria-hidden` is applied to its parent.

### Please provide a reproduction of the issue in a codepen:

On the demo page, add `aria-label` to any of the examples: https://fabricweb.z5.web.core.windows.net/oufr/7.101.0/#/examples/icon

#### Actual behavior:

Non-presentational icons do not expose the `img` role, and the name is not consistently announced (or supported by the ARIA spec).

ImageIcons with an `alt` are not exposed

#### Expected behavior:

Meaningful icons are exposed as graphics / `img`'s, with a name defined

### Documentation describing expected behavior

Role mapping for `<i>`: https://w3c.github.io/html-aam/#el-i
Roles supporting name from author: https://w3c.github.io/aria/#namefromauthor

My suggested fixes would be:
- adding `role="img"` to non-presentational icons (and dropping `role="presentation"`, since it does nothing when combined with `aria-hidden`)
- for image icons, dropping `aria-hidden` entirely, and relying on the image `alt` attribute

### PR DESCRIPTION
**Pull request by smhigley**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #12256
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Earlier conversations in PRs #16481 and #12257

This PR handles whether an icon should be presentational or have `role="img"` based on whether an accessible name is defined. Updates were made to `Icon`, `ImageIcon`, `FontIcon`, and `createSvgIcon`:

- FontIcon is the simplest -- it is an image if the author defines a name through `aria-label`, `-labelledby`, or `title`. Otherwise it gets `aria-hidden="true"`
- Icon handles names defined either on the container or through `imageProps`, if used as an image. If it is named and contains an image, nothing changes. If it is named but doesn't contain an image, it gets `role="img"`, and if it has no name it has `aria-hidden="true"`.
- ImageIcon is a little more complex, since any name or description defined through `props` needs to be moved to the image, or it would be invalid. If no name or description is defined either through `props` or `imageProps`, it gets `aria-hidden`.

I removed the extra `role="presentation"` that accompanied `aria-hidden` on all icons. I also updated the examples to remove the `role="img"` that is now added automatically.

(there are quite a lot of snapshot changes in this PR 😅)

### CODE REVIEW

File: packages/react-icons-mdl2/src/utils/createSvgIcon.ts [hunk 1]
```diff
@@ -9,12 +9,14 @@ const createSvgIcon = <TProps = {}>({ svg, displayName }: SvgIconCreateFnParams<
...
-    const containerProps = props['aria-label']
-      ? {}
-      : {
-          role: 'presentation',
-          ['aria-hidden']: true,
-        };
+    const containerProps =
+      props['aria-label'] || props['aria-labelledby'] || props.title
+        ? {
+            role: 'img',
```
Comment (JustSlone) [inline packages/react-icons-mdl2/src/utils/createSvgIcon.ts:15]: @tomi-msft is the new icon owner, and should be aware of this change and it's reason

File: packages/react-internal/etc/react-internal.api.md [hunk 2]
```diff
@@ -7243,23 +7243,24 @@ export const useSlider: (props: ISliderProps, ref: React.Ref<HTMLDivElement>) =>
         tabIndex: number | undefined;
         'data-is-focusable': boolean;
         defaultChecked?: boolean | undefined;
-        defaultValue?: string | number | readonly string[] | undefined;
+        defaultValue?: string | string[] | undefined;
```
Comment (JustSlone) [inline packages/react-internal/etc/react-internal.api.md:7246]: This is a breaking change? If that's intentional, make sure this is captured in the v8 release notes.

File: packages/utilities/etc/utilities.api.md [hunk 3]
```diff
@@ -46,7 +46,7 @@ export function arraysEqual<T>(array1: T[], array2: T[]): boolean;
...
... "param" | "picture" | "pre" | "q" | "rp" | "rt" | "s" | "samp" | "script" | "section" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "big" | React.ComponentClass<any, any> | React.FunctionComponent<any> | "keygen" | "menuitem" | "noindex" | "webview" | "svg" | "animate" | "animateMotion" | "animateTransform" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feDropShadow" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "mpath" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "textPath" | "tspan" | "use" | "view" | undefined;
```
Comment (JustSlone) [inline packages/utilities/etc/utilities.api.md:49]: This change also looks unintentional?

File: packages/web-components/docs/api-report.md [hunk 4]
```diff
@@ -1126,6 +1127,9 @@ export enum PaletteType {
     neutral = "neutral"
 }
 
+// @public
+export function parseColorString(color: string): ColorRGBA64;
```
Comment (JustSlone) [inline packages/web-components/docs/api-report.md:1131]: Will want to review this change with @chrisdholt this is the web-component implementation of Fluent UI

Comment (smhigley) [reply packages/web-components/docs/api-report.md:1131]: I don't know why this change was included, or why the api files changed; the changes don't look caused by any of the code I wrote, I'm looking into what's going on with those now :)

Comment (chrisdholt) [reply packages/web-components/docs/api-report.md:1131]: Yeah this is odd as the API report will typically cause the build to fail, thus, not allowing something to be checked-in. From what I can tell, all of our previous PR's passed the build so it's odd this is being generated. Not sure when you branched for this work but you could try rebasing w/ upstream to see if the report somehow fixed itself?

I'm fine if this change is included (it may have to be or it could prevent the build from passing). If it happens again we'll want to keep an eye on it. The only ask I would have would be to update the change request for it to "none" so that the packages do not update.

Comment (ecraig12345) [reply packages/web-components/docs/api-report.md:1131]: I think the API Extractor reports update if you run a full local build. That's probably how this got in.

Comment (ecraig12345) [reply packages/web-components/docs/api-report.md:1131]: Oh another possibility is that maybe if you had the latest code, but didn't update dependencies (`yarn`) before doing a full local build, that could have caused a bad update.

Comment (smhigley) [reply packages/web-components/docs/api-report.md:1131]: Thanks so much, updating + rebuilding seems to have fixed it. I'm going to double check, then update :)

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Avatar-mount_base.html">890</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Avatar-mount.html">867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/BaseButtonCompat-mount_base.html">978</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/BaseButtonCompat-mount.html">982</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Breadcrumb-mount_base.html">43512</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Breadcrumb-mount.html">44265</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Checkbox-mount_base.html">1584</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Checkbox-mount.html">1588</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/CheckboxBase-mount_base.html">1331</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/CheckboxBase-mount.html">1334</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ChoiceGroup-mount_base.html">5055</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ChoiceGroup-mount.html">4968</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ComboBox-mount_base.html">989</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ComboBox-mount.html">995</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/CommandBar-mount_base.html">10122</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/CommandBar-mount.html">10101</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ContextualMenu-mount_base.html">6168</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ContextualMenu-mount.html">6202</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DefaultButtonCompat-mount_base.html">1185</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DefaultButtonCompat-mount.html">1177</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DetailsRow-mount_base.html">3738</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DetailsRow-mount.html">3715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DetailsRowFast-mount_base.html">3819</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DetailsRowFast-mount.html">3732</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DetailsRowNoStyles-mount_base.html">3509</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DetailsRowNoStyles-mount.html">3514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Dialog-mount_base.html">1518</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Dialog-mount.html">1493</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DocumentCardTitle-mount_base.html">1823</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/DocumentCardTitle-mount.html">1820</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Dropdown-mount_base.html">3521</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Dropdown-mount.html">3409</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/FocusTrapZone-mount_base.html">1828</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/FocusTrapZone-mount.html">1769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/FocusZone-mount_base.html">1854</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/FocusZone-mount.html">1746</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/IconButtonCompat-mount_base.html">1863</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/IconButtonCompat-mount.html">1891</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Label-mount_base.html">349</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Label-mount.html">338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Layer-mount_base.html">1891</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Layer-mount.html">1908</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Link-mount_base.html">481</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Link-mount.html">478</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/MakeStyles-mount_base.html">1995</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/MakeStyles-mount.html">2025</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/MenuButtonCompat-mount_base.html">1635</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/MenuButtonCompat-mount.html">1630</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/MessageBar-mount_base.html">2135</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/MessageBar-mount.html">2091</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Nav-mount_base.html">3564</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Nav-mount.html">3592</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/OverflowSet-mount_base.html">1120</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/OverflowSet-mount.html">1077</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Panel-mount_base.html">1485</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Panel-mount.html">1534</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Persona-mount_base.html">914</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Persona-mount.html">944</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Pivot-mount_base.html">1524</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Pivot-mount.html">1515</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/PrimaryButtonCompat-mount_base.html">1455</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/PrimaryButtonCompat-mount.html">1431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Rating-mount_base.html">8147</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Rating-mount.html">8319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/SearchBox-mount_base.html">1409</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/SearchBox-mount.html">1453</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Shimmer-mount_base.html">2698</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Shimmer-mount.html">2769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Slider-mount_base.html">2008</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Slider-mount.html">2056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/SpinButton-mount_base.html">5362</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/SpinButton-mount.html">5194</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Spinner-mount_base.html">456</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Spinner-mount.html">444</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/SplitButtonCompat-mount_base.html">3410</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/SplitButtonCompat-mount.html">3380</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Stack-mount_base.html">538</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Stack-mount.html">527</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1662</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/StackWithIntrinsicChildren-mount.html">1650</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/StackWithTextChildren-mount_base.html">4954</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/StackWithTextChildren-mount.html">5099</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/SwatchColorPicker-mount_base.html">10738</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/SwatchColorPicker-mount.html">11034</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Tabs-mount_base.html">1478</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Tabs-mount.html">1465</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/TagPicker-mount_base.html">2814</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/TagPicker-mount.html">2891</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/TeachingBubble-mount_base.html">11645</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/TeachingBubble-mount.html">11740</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Text-mount_base.html">443</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Text-mount.html">433</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/TextField-mount_base.html">1425</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/TextField-mount.html">1418</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ThemeProvider-mount_base.html">1407</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ThemeProvider-mount.html">1407</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ThemeProvider-virtual-rerender_base.html">601</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ThemeProvider-virtual-rerender.html">593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ThemeProviderNext-mount_base.html">2176</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/ThemeProviderNext-mount.html">2138</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Toggle-mount_base.html">825</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/Toggle-mount.html">815</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/button-mount_base.html">699</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/button-mount.html">708</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/buttonNative-mount_base.html">111</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test/buttonNative-mount.html">103</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🦄 | Avatar.Fluent | [0.2](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Avatar.Fluent.html) | 0.54 | 0.37:1 | 2000 | 392
🦄 | Button.Fluent | [0.14](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Button.Fluent.html) | 0.22 | 0.64:1 | 5000 | 705
🔧 | Checkbox.Fluent | [0.7](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Checkbox.Fluent.html) | 0.4 | 1.75:1 | 1000 | 698
🎯 | Dialog.Fluent | [0.18](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Dialog.Fluent.html) | 0.23 | 0.78:1 | 5000 | 899
🔧 | Dropdown.Fluent | [3.17](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Dropdown.Fluent.html) | 0.44 | 7.2:1 | 1000 | 3169
🔧 | Icon.Fluent | [0.16](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Icon.Fluent.html) | 0.06 | 2.67:1 | 5000 | 805
🦄 | Image.Fluent | [0.09](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Image.Fluent.html) | 0.14 | 0.64:1 | 5000 | 464
🔧 | Slider.Fluent | [1.69](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Slider.Fluent.html) | 0.48 | 3.52:1 | 1000 | 1689
🔧 | Text.Fluent | [0.09](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Text.Fluent.html) | 0.04 | 2.25:1 | 5000 | 429
🦄 | Tooltip.Fluent | [0.13](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Tooltip.Fluent.html) | 0.94 | 0.14:1 | 5000 | 635
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ListWith60ListItems.default | [708](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ListWith60ListItems.default.html) | [657](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.08:1
TreeWith60ListItems.default | [198](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TreeWith60ListItems.default.html) | [184](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.08:1
ChatDuplicateMessagesPerf.default | [413](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [385](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.07:1
LabelMinimalPerf.default | [494](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/LabelMinimalPerf.default.html) | [460](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.07:1
Button.Fluent | [705](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Button.Fluent.html) | [656](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Button.Fluent_base.html) | 1.07:1
ListNestedPerf.default | [667](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ListNestedPerf.default.html) | [638](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ListNestedPerf.default_base.html) | 1.05:1
RadioGroupMinimalPerf.default | [511](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [487](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.05:1
TreeMinimalPerf.default | [892](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TreeMinimalPerf.default.html) | [851](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.05:1
Image.Fluent | [464](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Image.Fluent.html) | [442](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Image.Fluent_base.html) | 1.05:1
AccordionMinimalPerf.default | [193](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AccordionMinimalPerf.default.html) | [186](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.04:1
AttachmentMinimalPerf.default | [196](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AttachmentMinimalPerf.default.html) | [189](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.04:1
ButtonMinimalPerf.default | [214](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonMinimalPerf.default.html) | [205](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.04:1
CardMinimalPerf.default | [691](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/CardMinimalPerf.default.html) | [662](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.04:1
ListMinimalPerf.default | [580](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ListMinimalPerf.default.html) | [558](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.04:1
VideoMinimalPerf.default | [731](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/VideoMinimalPerf.default.html) | [700](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.04:1
Checkbox.Fluent | [698](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Checkbox.Fluent.html) | [671](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Checkbox.Fluent_base.html) | 1.04:1
Icon.Fluent | [805](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Icon.Fluent.html) | [777](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Icon.Fluent_base.html) | 1.04:1
BoxMinimalPerf.default | [427](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/BoxMinimalPerf.default.html) | [415](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.03:1
ButtonSlotsPerf.default | [670](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonSlotsPerf.default.html) | [650](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
ChatWithPopoverPerf.default | [488](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ChatWithPopoverPerf.default.html) | [473](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.03:1
FlexMinimalPerf.default | [348](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/FlexMinimalPerf.default.html) | [339](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.03:1
FormMinimalPerf.default | [494](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/FormMinimalPerf.default.html) | [479](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.03:1
MenuMinimalPerf.default | [1000](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/MenuMinimalPerf.default.html) | [972](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [412](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/SegmentMinimalPerf.default.html) | [399](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
TableMinimalPerf.default | [472](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TableMinimalPerf.default.html) | [457](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.03:1
Slider.Fluent | [1689](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Slider.Fluent.html) | [1639](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Slider.Fluent_base.html) | 1.03:1
Tooltip.Fluent | [635](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Tooltip.Fluent.html) | [619](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Tooltip.Fluent_base.html) | 1.03:1
AttachmentSlotsPerf.default | [1379](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1351](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.02:1
HeaderMinimalPerf.default | [446](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/HeaderMinimalPerf.default.html) | [438](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.02:1
PortalMinimalPerf.default | [173](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/PortalMinimalPerf.default.html) | [169](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.02:1
ReactionMinimalPerf.default | [471](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ReactionMinimalPerf.default.html) | [463](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [877](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TooltipMinimalPerf.default.html) | [858](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
Text.Fluent | [429](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Text.Fluent.html) | [421](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Text.Fluent_base.html) | 1.02:1
AnimationMinimalPerf.default | [476](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AnimationMinimalPerf.default.html) | [472](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.01:1
AvatarMinimalPerf.default | [225](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AvatarMinimalPerf.default.html) | [222](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1861](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1848](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
ButtonUseCssNestingPerf.default | [1201](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1189](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 1.01:1
ChatMinimalPerf.default | [692](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ChatMinimalPerf.default.html) | [687](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [49793](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DatepickerMinimalPerf.default.html) | [49093](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
DividerMinimalPerf.default | [431](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DividerMinimalPerf.default.html) | [428](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.01:1
EmbedMinimalPerf.default | [4366](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/EmbedMinimalPerf.default.html) | [4324](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.01:1
ImageMinimalPerf.default | [450](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ImageMinimalPerf.default.html) | [447](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [777](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/LoaderMinimalPerf.default.html) | [773](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
RefMinimalPerf.default | [247](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/RefMinimalPerf.default.html) | [245](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.01:1
StatusMinimalPerf.default | [803](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/StatusMinimalPerf.default.html) | [795](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.01:1
TextMinimalPerf.default | [403](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TextMinimalPerf.default.html) | [398](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.01:1
Avatar.Fluent | [392](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Avatar.Fluent.html) | [388](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Avatar.Fluent_base.html) | 1.01:1
DialogMinimalPerf.default | [845](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DialogMinimalPerf.default.html) | [841](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [3078](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DropdownMinimalPerf.default.html) | [3090](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
GridMinimalPerf.default | [401](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/GridMinimalPerf.default.html) | [400](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/GridMinimalPerf.default_base.html) | 1:1
HeaderSlotsPerf.default | [872](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/HeaderSlotsPerf.default.html) | [870](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1:1
InputMinimalPerf.default | [1324](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/InputMinimalPerf.default.html) | [1329](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/InputMinimalPerf.default_base.html) | 1:1
ItemLayoutMinimalPerf.default | [1368](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1365](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [4060](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4052](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
IconMinimalPerf.default | [727](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/IconMinimalPerf.default.html) | [726](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/IconMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3738](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/CustomToolbarPrototype.default.html) | [3754](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
ToolbarMinimalPerf.default | [1058](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1054](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1:1
Dialog.Fluent | [899](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Dialog.Fluent.html) | [899](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Dialog.Fluent_base.html) | 1:1
CarouselMinimalPerf.default | [552](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/CarouselMinimalPerf.default.html) | [556](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.99:1
PopupMinimalPerf.default | [733](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/PopupMinimalPerf.default.html) | [743](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1575](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1593](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
ProviderMinimalPerf.default | [946](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ProviderMinimalPerf.default.html) | [960](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.99:1
TableManyItemsPerf.default | [2251](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TableManyItemsPerf.default.html) | [2270](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TableManyItemsPerf.default_base.html) | 0.99:1
AlertMinimalPerf.default | [354](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AlertMinimalPerf.default.html) | [361](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.98:1
CheckboxMinimalPerf.default | [3008](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/CheckboxMinimalPerf.default.html) | [3056](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.98:1
DropdownManyItemsPerf.default | [790](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DropdownManyItemsPerf.default.html) | [803](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.98:1
MenuButtonMinimalPerf.default | [1675](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1701](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.98:1
ButtonUseCssPerf.default | [933](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonUseCssPerf.default.html) | [958](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 0.97:1
LayoutMinimalPerf.default | [464](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/LayoutMinimalPerf.default.html) | [479](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.97:1
SkeletonMinimalPerf.default | [411](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/SkeletonMinimalPerf.default.html) | [423](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.97:1
Dropdown.Fluent | [3169](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Dropdown.Fluent.html) | [3273](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/Dropdown.Fluent_base.html) | 0.97:1
RosterPerf.default | [1271](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/RosterPerf.default.html) | [1327](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/RosterPerf.default_base.html) | 0.96:1
SliderMinimalPerf.default | [1561](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/SliderMinimalPerf.default.html) | [1625](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.96:1
ListCommonPerf.default | [721](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ListCommonPerf.default.html) | [758](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/ListCommonPerf.default_base.html) | 0.95:1
TextAreaMinimalPerf.default | [546](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TextAreaMinimalPerf.default.html) | [574](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16836/merge/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.95:1

</details><div id="perfComment9423"/>

File: packages/react-examples/src/react/Icon/Icon.ImageSheet.Example.tsx [hunk 5]
```diff
@@ -41,31 +41,28 @@ const classNames = mergeStyleSets({
...
           className: css(classNames.image, classNames.oneImage),
         }}
       />
       <ImageIcon
-        aria-label="Check icon"
-        role="img"
         className={classNames.check}
         imageProps={{
           src: TestImages.iconOne,
+          'aria-label': 'Printer ready',
```
Comment (khmakoto) [inline packages/react-examples/src/react/Icon/Icon.ImageSheet.Example.tsx:60]: Why are you using `alt` above and `aria-label` here? It seems like they are effectively the same.

Comment (smhigley) [reply packages/react-examples/src/react/Icon/Icon.ImageSheet.Example.tsx:60]: It was partly to demo different options for accessible naming, partly so there were snapshot tests for both :D.

I have no idea if examples is the right place for either of those though, so happy to change them to all use `alt`, which is more of a best practice :D

Comment (ecraig12345) [reply packages/react-examples/src/react/Icon/Icon.ImageSheet.Example.tsx:60]: Having snapshot tests (and/or tests explicitly verifying that attributes are applied) for the different accessible name scenarios would actually be a great idea. You can follow the patterns of the other snapshot tests in Icon.test.tsx, FontIcon.test.tsx, and we should probably add ImageIcon.test.tsx.

File: packages/react-examples/src/react/Icon/Icon.Svg.Example.tsx [hunk 6]
```diff
@@ -45,13 +52,13 @@ const BorderBlindsIcon: React.FunctionComponent<{ color1?: string; color2?: stri
...
-  // that conveys the same meaning.
+  // This example demonstrates how to expose the SVG itself as an image with
+  // an accessible name. To do that, set aria-label or aria-labelledby directly
+  // on the SVG, and set aria-hidden to undefined or false on the FontIcon.
   return (
     <FontIcon
-      aria-label="Map icon"
-      role="img"
       iconName="borderblinds-svg"
+      aria-hidden={undefined}
```
Comment (ecraig12345) [inline packages/react-examples/src/react/Icon/Icon.Svg.Example.tsx:61]: What is this meant to do? Generally it's best if we can avoid explicitly setting things to undefined, since it can easily be mixed up with the prop being unspecified depending on  exactly how the props object is used/accessed (which could also change over time).

Comment (smhigley) [reply packages/react-examples/src/react/Icon/Icon.Svg.Example.tsx:61]: It was because the SVG handles the name itself, so I didn't want it to be hidden. I could set it to `aria-hidden="false"`, though that has the potential to cause problems if a parent sets `aria-hidden="true"` (i.e. the child could be interpreted to be shown if it's explicitly "false")

File: change/@fluentui-react-avatar-49c6dd29-15dc-4ba9-bd3a-caef7bdc8a98.json [hunk 7]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
+  "comment": "update Icon, FontIcon, ImageIcon, and createSvgIcon to add the img role, and update examples",
```
[the remark this answers is not in the document]
Comment (smhigley) [reply change/@fluentui-react-avatar-49c6dd29-15dc-4ba9-bd3a-caef7bdc8a98.json]: done!

File: packages/react-examples/src/react/Icon/Icon.ImageSheet.Example.tsx (hunk 5 above)
Comment (smhigley) [reply packages/react-examples/src/react/Icon/Icon.ImageSheet.Example.tsx]: updated! I added tests, and changed the example to use just `alt`

File: packages/react/src/components/Icon/FontIcon.test.tsx [hunk 8]
```diff
@@ -10,6 +10,24 @@ describe('FontIcon', () => {
     expect(tree).toMatchSnapshot();
   });
 
+  it('renders named FontIcon correctly', () => {
+    const component = renderer.create(<FontIcon iconName="CompassNW" aria-label="compass" />);
```
Comment (ecraig12345) [inline packages/react/src/components/Icon/FontIcon.test.tsx:14]: I know I mentioned snapshot tests before, but thinking about it more I wonder if instead or in addition, we ought to have explicit tests for how the text is applied and what other attributes are applied. Let me know if it's unclear what I mean by that (or how to do it--not sure what your level of background is with enzyme/jest tests) and I can go into more detail.

Comment (smhigley) [reply packages/react/src/components/Icon/FontIcon.test.tsx:14]: I updated the tests to use explicit assertions, and kept a couple of the snapshots w/ names in there as well. Let me know what you think!

File: change/@fluentui-react-3a2d2c1d-90af-4cef-971b-d676ce98dab3.json [hunk 9]
```diff
@@ -1,7 +0,0 @@
-{
-  "type": "prerelease",
```
Comment (ecraig12345) [inline change/@fluentui-react-3a2d2c1d-90af-4cef-971b-d676ce98dab3.json:2]: Was this intentionally deleted?

File: change/@fluentui-react-experiments-2021-02-02-09-54-29-perffixes.json [hunk 10]
```diff
@@ -1,8 +0,0 @@
-{
-  "type": "prerelease",
```
Comment (ecraig12345) [inline change/@fluentui-react-experiments-2021-02-02-09-54-29-perffixes.json:2]: Same here

**Comment by ecraig12345** [comment]
@smhigley Thanks for adding the tests! This looks good to me once the issues with change files and merge conflicts are fixed.

File: change/@fluentui-react-3a2d2c1d-90af-4cef-971b-d676ce98dab3.json (hunk 9 above)
Comment (smhigley) [reply change/@fluentui-react-3a2d2c1d-90af-4cef-971b-d676ce98dab3.json:2]: oops, nope, definitely not intentional. I'll go see what happened with these 😅

**Comment by smhigley** [comment]
@ecraig12345 thanks for all the reviews! The change files should now be fixed, and the branch updated w/ master :)

**Review by ecraig12345 — APPROVED** [review]
