### PR TITLE
Accessibility fixes for react-docsite-components

### LINKED ISSUE #16550: [@uifabric/example-app-base] Aria-expanded attribute is not defined for "Settings" button
### Environment Information

Test Environments:
Version:  2004 (OS Build: 20236.1005)
Browser: Edge chromium 
Tool: Developer tool

### Describe the issue:

User Experience:
When navigating to a site using example-app-base, the screen reader will not able to know the state of the control and might miss the functionality present under the control if aria-expanded attribute is not defined for the control.

### Please provide a reproduction of the issue in a codepen:

Unable to use codepen as the issue is located in @uifabric/example-app-base

Navigate on "Settings" button
Inspect it through developer tool
Verify the issue

#### Actual behavior:

Aria-expanded attribute is not defined for "Settings" button due to which screen reader is announcing "Setting button" only.

#### Expected behavior:

Aria-expanded attribute should be defined for "Settings" button.

### Documentation describing expected behavior

N/A

### LINKED ISSUE #16552: [@uifabric/example-app-base] Hamburger menu button is not collapsing through Esc key which appears after resizing the browser up to 200%
### Environment Information

Test Environments:
Version:  2004 (OS Build: 20236.1005)
Browser: Edge chromium 
Tool: Settings

### Describe the issue:

When navigating to a site using example-app-base, low visible user will not able to access the controls of the page efficiently if the hamburger menu item is not collapsing on pressing Esc key which appears after resizing the browser up to 200%

### Please provide a reproduction of the issue in a codepen:

Unable to use codepen as the issue is located in @uifabric/example-app-base

Resize the browser upto 200% and refresh the page.
Navigate on Hamburger menu item and activate it through keyboard.
Press Esc key to collapse the Hamburger menu item
Verify the issue

#### Actual behavior:

When page is resized to 200%, Hamburger menu button is not collapsing through Esc key neither by Enter or Space bar key and on pressing TAB key the focus indicator remains on "Shared Components" button which is appearing under Hamburger menu item

#### Expected behavior:

When page is resized to 200%,, Hamburger menu button should gets collapse through Esc key and on pressing TAB key the focus indicator should move out side of the hamburger menu item

### Documentation describing expected behavior

N/A

### LINKED ISSUE #16612: [@uifabric/example-app-base] Narrator is not reading "Expand all" column header appearing below the interface section
**Environment Information**
Version:  2004 (OS Build: 20236.1005)
Browser: Edge chromium 
Tool: Developer tool
Bug id: 8759558 

**Describe the issue:**
In the package `@uifabric/example-app-base` the interfaces section's "Expand all" column header appearing below the Interface section text is not announcing 'expand all' and is announcing "group expanded" only.

**Please provide a reproduction of the issue in a codepen:**
Unable to use codepen as the issue is located in @uifabric/example-app-base

**Actual Result:**
The screen reader is announcing "group expanded" only.

**Expected Result:**
The screenreader should announce "Expand all".

**Documentation describing expected behavior**
N/A

MAS4 1 2

### PR DESCRIPTION
**Pull request by ecraig12345**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #16552, fixes #16550, fixes #16612
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Fix some accessibility issues with the legacy demo app components (which are also used by a handful of other teams):
- Allow closing nav with escape key (small screens only)
- Add aria-expanded to settings button
- Add label for expand/collapse all button in properties tables
- Allow long issue names in feedback list to wrap

[Try out the changes here](https://fluentuipr.z22.web.core.windows.net/pull/18928/public-docsite-resources/demo/index.html)

### CODE REVIEW

File: packages/react-docsite-components/src/components/Header/Header.tsx [hunk 1]
```diff
@@ -36,7 +36,7 @@ export class HeaderBase extends React.Component<IHeaderProps, IHeaderState> {
     // For screen sizes large down, hide the side links.
     const sideLinks = isLargeDown ? [] : this.props.sideLinks;
 
-    const classNames = getClassNames(styles, { theme });
+    const classNames = getClassNames(styles, { theme, isLargeDown });
```
Comment (ecraig12345) [inline packages/react-docsite-components/src/components/Header/Header.tsx:39]: This is a styling fix using some code which already exists in the header styles (for some reason `isLargeDown` wasn't being passed through previously)

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Avatar-mount_base.html">869</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Avatar-mount.html">907</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/BaseButton-mount_base.html">999</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/BaseButton-mount.html">1015</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Breadcrumb-mount_base.html">2747</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Breadcrumb-mount.html">2771</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ButtonNext-mount_base.html">586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ButtonNext-mount.html">611</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Checkbox-mount_base.html">1689</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Checkbox-mount.html">1682</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/CheckboxBase-mount_base.html">1453</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/CheckboxBase-mount.html">1431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ChoiceGroup-mount_base.html">5106</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ChoiceGroup-mount.html">5130</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ComboBox-mount_base.html">1035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ComboBox-mount.html">1037</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/CommandBar-mount_base.html">10635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/CommandBar-mount.html">10571</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ContextualMenu-mount_base.html">6601</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ContextualMenu-mount.html">6533</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DefaultButton-mount_base.html">1215</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DefaultButton-mount.html">1208</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DetailsRow-mount_base.html">3962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DetailsRow-mount.html">3893</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DetailsRowFast-mount_base.html">4098</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DetailsRowFast-mount.html">4084</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DetailsRowNoStyles-mount_base.html">3742</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DetailsRowNoStyles-mount.html">3852</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Dialog-mount_base.html">2280</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Dialog-mount.html">2302</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DocumentCardTitle-mount_base.html">165</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/DocumentCardTitle-mount.html">164</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Dropdown-mount_base.html">3604</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Dropdown-mount.html">3498</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/FluentProviderNext-mount_base.html">7176</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/FluentProviderNext-mount.html">7007</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/FocusTrapZone-mount_base.html">1893</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/FocusTrapZone-mount.html">1865</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/FocusZone-mount_base.html">1843</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/FocusZone-mount.html">1859</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/IconButton-mount_base.html">1937</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/IconButton-mount.html">1900</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Label-mount_base.html">357</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Label-mount.html">373</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Layer-mount_base.html">1975</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Layer-mount.html">1917</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Link-mount_base.html">494</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Link-mount.html">500</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/MakeStyles-mount_base.html">1932</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/MakeStyles-mount.html">1898</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/MenuButton-mount_base.html">1600</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/MenuButton-mount.html">1631</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/MessageBar-mount_base.html">2075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/MessageBar-mount.html">2105</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Nav-mount_base.html">3705</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Nav-mount.html">3688</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/OverflowSet-mount_base.html">1112</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/OverflowSet-mount.html">1142</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Panel-mount_base.html">2242</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Panel-mount.html">2241</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Persona-mount_base.html">924</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Persona-mount.html">921</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Pivot-mount_base.html">1575</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Pivot-mount.html">1563</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/PrimaryButton-mount_base.html">1372</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/PrimaryButton-mount.html">1424</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Rating-mount_base.html">8338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Rating-mount.html">8387</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/SearchBox-mount_base.html">1442</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/SearchBox-mount.html">1433</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Shimmer-mount_base.html">2801</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Shimmer-mount.html">2745</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Slider-mount_base.html">2057</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Slider-mount.html">2123</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/SpinButton-mount_base.html">5274</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/SpinButton-mount.html">5352</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Spinner-mount_base.html">436</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Spinner-mount.html">432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/SplitButton-mount_base.html">3450</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/SplitButton-mount.html">3400</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Stack-mount_base.html">538</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Stack-mount.html">541</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/StackWithIntrinsicChildren-mount_base.html">1698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/StackWithIntrinsicChildren-mount.html">1686</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/StackWithTextChildren-mount_base.html">5052</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/StackWithTextChildren-mount.html">5134</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/SwatchColorPicker-mount_base.html">12122</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/SwatchColorPicker-mount.html">10976</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Tabs-mount_base.html">1518</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Tabs-mount.html">1515</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/TagPicker-mount_base.html">2673</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/TagPicker-mount.html">2826</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/TeachingBubble-mount_base.html">12338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/TeachingBubble-mount.html">12342</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Text-mount_base.html">471</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Text-mount.html">465</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/TextField-mount_base.html">1524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/TextField-mount.html">1538</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ThemeProvider-mount_base.html">1267</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ThemeProvider-mount.html">1275</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ThemeProvider-virtual-rerender_base.html">626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/ThemeProvider-virtual-rerender.html">627</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Toggle-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/Toggle-mount.html">870</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/buttonNative-mount_base.html">117</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test/buttonNative-mount.html">116</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ButtonMinimalPerf.default | [206](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ButtonMinimalPerf.default.html) | [182](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.13:1
AvatarMinimalPerf.default | [232](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AvatarMinimalPerf.default.html) | [216](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.07:1
ChatDuplicateMessagesPerf.default | [339](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [317](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.07:1
SkeletonMinimalPerf.default | [413](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/SkeletonMinimalPerf.default.html) | [386](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.07:1
ListNestedPerf.default | [630](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ListNestedPerf.default.html) | [595](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ListNestedPerf.default_base.html) | 1.06:1
TextMinimalPerf.default | [394](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TextMinimalPerf.default.html) | [370](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.06:1
BoxMinimalPerf.default | [418](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/BoxMinimalPerf.default.html) | [399](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.05:1
RadioGroupMinimalPerf.default | [517](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [493](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.05:1
VideoMinimalPerf.default | [709](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/VideoMinimalPerf.default.html) | [677](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.05:1
DividerMinimalPerf.default | [408](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DividerMinimalPerf.default.html) | [394](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.04:1
ListMinimalPerf.default | [562](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ListMinimalPerf.default.html) | [540](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.04:1
ProviderMergeThemesPerf.default | [1753](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1692](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.04:1
SliderMinimalPerf.default | [1733](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/SliderMinimalPerf.default.html) | [1674](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.04:1
StatusMinimalPerf.default | [750](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/StatusMinimalPerf.default.html) | [723](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.04:1
AttachmentMinimalPerf.default | [180](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AttachmentMinimalPerf.default.html) | [174](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.03:1
HeaderSlotsPerf.default | [862](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/HeaderSlotsPerf.default.html) | [835](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.03:1
InputMinimalPerf.default | [1373](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/InputMinimalPerf.default.html) | [1335](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.03:1
ItemLayoutMinimalPerf.default | [1351](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1309](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
LabelMinimalPerf.default | [426](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/LabelMinimalPerf.default.html) | [414](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.03:1
PopupMinimalPerf.default | [647](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/PopupMinimalPerf.default.html) | [626](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.03:1
IconMinimalPerf.default | [679](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/IconMinimalPerf.default.html) | [660](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [1065](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1033](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
EmbedMinimalPerf.default | [4514](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/EmbedMinimalPerf.default.html) | [4432](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.02:1
FlexMinimalPerf.default | [329](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/FlexMinimalPerf.default.html) | [321](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [2096](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TableManyItemsPerf.default.html) | [2062](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
TableMinimalPerf.default | [436](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TableMinimalPerf.default.html) | [429](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.02:1
AccordionMinimalPerf.default | [166](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AccordionMinimalPerf.default.html) | [165](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.01:1
AnimationMinimalPerf.default | [449](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AnimationMinimalPerf.default.html) | [443](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5763](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5728](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
DialogMinimalPerf.default | [812](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DialogMinimalPerf.default.html) | [803](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.01:1
GridMinimalPerf.default | [394](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/GridMinimalPerf.default.html) | [389](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.01:1
HeaderMinimalPerf.default | [397](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/HeaderMinimalPerf.default.html) | [392](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.01:1
LayoutMinimalPerf.default | [401](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/LayoutMinimalPerf.default.html) | [398](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [749](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/LoaderMinimalPerf.default.html) | [739](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
ProviderMinimalPerf.default | [1105](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ProviderMinimalPerf.default.html) | [1097](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [4149](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4121](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [1120](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TooltipMinimalPerf.default.html) | [1112](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
ChatMinimalPerf.default | [746](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ChatMinimalPerf.default.html) | [745](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1:1
ChatWithPopoverPerf.default | [408](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ChatWithPopoverPerf.default.html) | [410](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [3265](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DropdownMinimalPerf.default.html) | [3256](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
FormMinimalPerf.default | [469](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/FormMinimalPerf.default.html) | [471](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/FormMinimalPerf.default_base.html) | 1:1
ImageMinimalPerf.default | [409](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ImageMinimalPerf.default.html) | [409](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1:1
MenuMinimalPerf.default | [937](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/MenuMinimalPerf.default.html) | [938](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
TreeMinimalPerf.default | [863](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TreeMinimalPerf.default.html) | [861](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1:1
AttachmentSlotsPerf.default | [1148](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1157](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.99:1
ButtonOverridesMissPerf.default | [1823](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1844](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.99:1
CardMinimalPerf.default | [599](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/CardMinimalPerf.default.html) | [605](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.99:1
CheckboxMinimalPerf.default | [3000](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/CheckboxMinimalPerf.default.html) | [3026](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
DropdownManyItemsPerf.default | [744](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DropdownManyItemsPerf.default.html) | [748](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.99:1
ListCommonPerf.default | [703](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ListCommonPerf.default.html) | [710](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ListCommonPerf.default_base.html) | 0.99:1
MenuButtonMinimalPerf.default | [1798](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1815](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.99:1
SegmentMinimalPerf.default | [369](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/SegmentMinimalPerf.default.html) | [371](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.99:1
TextAreaMinimalPerf.default | [573](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TextAreaMinimalPerf.default.html) | [581](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.99:1
CarouselMinimalPerf.default | [515](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/CarouselMinimalPerf.default.html) | [528](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.98:1
RosterPerf.default | [1268](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/RosterPerf.default.html) | [1292](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/RosterPerf.default_base.html) | 0.98:1
CustomToolbarPrototype.default | [4055](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/CustomToolbarPrototype.default.html) | [4149](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.98:1
TreeWith60ListItems.default | [175](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TreeWith60ListItems.default.html) | [179](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.98:1
RefMinimalPerf.default | [240](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/RefMinimalPerf.default.html) | [249](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.96:1
AlertMinimalPerf.default | [310](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AlertMinimalPerf.default.html) | [327](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.95:1
ListWith60ListItems.default | [679](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ListWith60ListItems.default.html) | [711](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.95:1
ReactionMinimalPerf.default | [421](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ReactionMinimalPerf.default.html) | [445](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.95:1
ButtonSlotsPerf.default | [575](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ButtonSlotsPerf.default.html) | [611](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.94:1
PortalMinimalPerf.default | [179](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/PortalMinimalPerf.default.html) | [190](https://fluentuipr.z22.web.core.windows.net/pull/18928/perf-test-northstar/PortalMinimalPerf.default_base.html) | 0.94:1

</details><div id="perfComment9423"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/57b43a4d07fbccd83fa03a3b7879813be920b91f'>57b43a4d07fbccd83fa03a3b7879813be920b91f</a></sub>
<div id="bundleSizeComment9423"/>

**Review by khmakoto — APPROVED** [review]

**Review by smhigley — APPROVED** [review]
