### PR TITLE
fix(Menu): Submenu state should include `MenuList`

### LINKED ISSUE #18773: Menu: MenuTrigger opens `Menu` with ArrowDown inside MenuList
### Environment Information

- **Package version(s)**: v9

### Please provide a reproduction of the bug in a codesandbox:

https://codesandbox.io/s/jovial-tree-is89l?file=/src/App.js

#### Actual behavior:

When using `MenuTrigger` inside a `MenuList` the nested menu opens with ArrowDown which breaks arrow key navigation inside the `MenuList`

#### Expected behavior:

When using `MenuTrigger` inside a `MenuList` the menu should not open with down arrow since it is a nested menu

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority:  Blocking

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by ling1726**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #18773
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Currently a `Menu` is a submenu if it is within another `MenuContext`. This was incorrect since `MenuListContext` should behave the same way. Adds a helper hook to check both contexts so the submenu state can be evaluated correctly.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Avatar-mount_base.html">786</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Avatar-mount.html">778</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/BaseButton-mount_base.html">892</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/BaseButton-mount.html">871</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Breadcrumb-mount_base.html">2598</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Breadcrumb-mount.html">2539</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ButtonNext-mount_base.html">517</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ButtonNext-mount.html">540</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Checkbox-mount_base.html">1498</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Checkbox-mount.html">1472</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/CheckboxBase-mount_base.html">1289</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/CheckboxBase-mount.html">1262</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ChoiceGroup-mount_base.html">4674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ChoiceGroup-mount.html">4675</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ComboBox-mount_base.html">970</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ComboBox-mount.html">964</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/CommandBar-mount_base.html">9943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/CommandBar-mount.html">9930</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ContextualMenu-mount_base.html">6240</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ContextualMenu-mount.html">6145</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DefaultButton-mount_base.html">1124</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DefaultButton-mount.html">1082</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DetailsRow-mount_base.html">3697</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DetailsRow-mount.html">3710</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DetailsRowFast-mount_base.html">3605</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DetailsRowFast-mount.html">3603</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DetailsRowNoStyles-mount_base.html">3427</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DetailsRowNoStyles-mount.html">3560</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Dialog-mount_base.html">2140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Dialog-mount.html">2097</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DocumentCardTitle-mount_base.html">150</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/DocumentCardTitle-mount.html">135</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Dropdown-mount_base.html">3420</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Dropdown-mount.html">3138</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/FluentProviderNext-mount_base.html">7221</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/FluentProviderNext-mount.html">7175</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/FocusTrapZone-mount_base.html">1815</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/FocusTrapZone-mount.html">1785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/FocusZone-mount_base.html">1793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/FocusZone-mount.html">1811</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/IconButton-mount_base.html">1709</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/IconButton-mount.html">1680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Label-mount_base.html">331</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Label-mount.html">331</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Layer-mount_base.html">1772</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Layer-mount.html">1738</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Link-mount_base.html">454</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Link-mount.html">481</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/MakeStyles-mount_base.html">1816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/MakeStyles-mount.html">1781</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/MenuButton-mount_base.html">1416</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/MenuButton-mount.html">1404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/MessageBar-mount_base.html">1962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/MessageBar-mount.html">1999</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Nav-mount_base.html">3171</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Nav-mount.html">3592</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/OverflowSet-mount_base.html">1024</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/OverflowSet-mount.html">1030</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Panel-mount_base.html">2034</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Panel-mount.html">1996</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Persona-mount_base.html">792</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Persona-mount.html">814</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Pivot-mount_base.html">1417</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Pivot-mount.html">1383</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/PrimaryButton-mount_base.html">1251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/PrimaryButton-mount.html">1274</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Rating-mount_base.html">7534</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Rating-mount.html">7491</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/SearchBox-mount_base.html">1276</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/SearchBox-mount.html">1318</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Shimmer-mount_base.html">2464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Shimmer-mount.html">2499</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Slider-mount_base.html">1931</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Slider-mount.html">1915</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/SpinButton-mount_base.html">4898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/SpinButton-mount.html">4905</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Spinner-mount_base.html">420</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Spinner-mount.html">425</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/SplitButton-mount_base.html">3089</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/SplitButton-mount.html">3083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Stack-mount_base.html">483</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Stack-mount.html">500</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/StackWithIntrinsicChildren-mount_base.html">1521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/StackWithIntrinsicChildren-mount.html">1501</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/StackWithTextChildren-mount_base.html">4461</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/StackWithTextChildren-mount.html">4477</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/SwatchColorPicker-mount_base.html">10110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/SwatchColorPicker-mount.html">10056</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Tabs-mount_base.html">1384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Tabs-mount.html">1403</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/TagPicker-mount_base.html">2420</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/TagPicker-mount.html">2441</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/TeachingBubble-mount_base.html">11778</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/TeachingBubble-mount.html">11753</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Text-mount_base.html">413</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Text-mount.html">408</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/TextField-mount_base.html">1359</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/TextField-mount.html">1329</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ThemeProvider-mount_base.html">1141</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ThemeProvider-mount.html">1173</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ThemeProvider-virtual-rerender_base.html">582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/ThemeProvider-virtual-rerender.html">575</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Toggle-mount_base.html">783</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/Toggle-mount.html">785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/buttonNative-mount_base.html">115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test/buttonNative-mount.html">111</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
PortalMinimalPerf.default | [185](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/PortalMinimalPerf.default.html) | [167](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.11:1
CardMinimalPerf.default | [551](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/CardMinimalPerf.default.html) | [505](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.09:1
AccordionMinimalPerf.default | [155](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AccordionMinimalPerf.default.html) | [143](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.08:1
AlertMinimalPerf.default | [280](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AlertMinimalPerf.default.html) | [263](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.06:1
TextMinimalPerf.default | [345](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TextMinimalPerf.default.html) | [327](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.06:1
TreeWith60ListItems.default | [176](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TreeWith60ListItems.default.html) | [166](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.06:1
AttachmentSlotsPerf.default | [1069](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1022](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.05:1
PopupMinimalPerf.default | [573](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/PopupMinimalPerf.default.html) | [544](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.05:1
RadioGroupMinimalPerf.default | [449](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [428](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.05:1
AvatarMinimalPerf.default | [197](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AvatarMinimalPerf.default.html) | [190](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.04:1
ItemLayoutMinimalPerf.default | [1223](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1177](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.04:1
ListNestedPerf.default | [555](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ListNestedPerf.default.html) | [534](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ListNestedPerf.default_base.html) | 1.04:1
ReactionMinimalPerf.default | [370](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ReactionMinimalPerf.default.html) | [355](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [490](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TextAreaMinimalPerf.default.html) | [470](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
ChatDuplicateMessagesPerf.default | [301](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [291](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.03:1
ListMinimalPerf.default | [506](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ListMinimalPerf.default.html) | [491](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [356](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/SegmentMinimalPerf.default.html) | [344](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [914](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ToolbarMinimalPerf.default.html) | [890](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
ImageMinimalPerf.default | [368](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ImageMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.02:1
TableMinimalPerf.default | [395](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TableMinimalPerf.default.html) | [387](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.02:1
CustomToolbarPrototype.default | [3828](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/CustomToolbarPrototype.default.html) | [3755](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.02:1
AttachmentMinimalPerf.default | [154](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AttachmentMinimalPerf.default.html) | [152](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.01:1
ButtonMinimalPerf.default | [168](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ButtonMinimalPerf.default.html) | [167](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2692](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2673](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5306](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5235](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
DialogMinimalPerf.default | [736](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DialogMinimalPerf.default.html) | [731](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [662](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DropdownManyItemsPerf.default.html) | [657](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.01:1
FlexMinimalPerf.default | [293](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/FlexMinimalPerf.default.html) | [289](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.01:1
HeaderSlotsPerf.default | [740](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/HeaderSlotsPerf.default.html) | [734](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [834](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/MenuMinimalPerf.default.html) | [825](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
ProviderMinimalPerf.default | [978](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ProviderMinimalPerf.default.html) | [968](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.01:1
SkeletonMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/SkeletonMinimalPerf.default.html) | [347](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.01:1
SliderMinimalPerf.default | [1537](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/SliderMinimalPerf.default.html) | [1523](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3670](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3650](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [3081](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DropdownMinimalPerf.default.html) | [3066](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
GridMinimalPerf.default | [331](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/GridMinimalPerf.default.html) | [332](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/GridMinimalPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1568](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1561](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
RefMinimalPerf.default | [228](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/RefMinimalPerf.default.html) | [227](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/RefMinimalPerf.default_base.html) | 1:1
TableManyItemsPerf.default | [1852](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TableManyItemsPerf.default.html) | [1844](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1:1
TooltipMinimalPerf.default | [980](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TooltipMinimalPerf.default.html) | [982](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
VideoMinimalPerf.default | [604](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/VideoMinimalPerf.default.html) | [605](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1:1
CarouselMinimalPerf.default | [435](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/CarouselMinimalPerf.default.html) | [441](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.99:1
ChatMinimalPerf.default | [642](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ChatMinimalPerf.default.html) | [648](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ChatMinimalPerf.default_base.html) | 0.99:1
DividerMinimalPerf.default | [342](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DividerMinimalPerf.default.html) | [344](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [4049](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/EmbedMinimalPerf.default.html) | [4094](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
FormMinimalPerf.default | [380](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/FormMinimalPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.99:1
HeaderMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/HeaderMinimalPerf.default.html) | [349](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1239](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/InputMinimalPerf.default.html) | [1246](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
LoaderMinimalPerf.default | [670](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/LoaderMinimalPerf.default.html) | [680](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.99:1
ProviderMergeThemesPerf.default | [1668](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1680](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 0.99:1
TreeMinimalPerf.default | [774](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TreeMinimalPerf.default.html) | [785](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.99:1
AnimationMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AnimationMinimalPerf.default.html) | [415](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.98:1
LayoutMinimalPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/LayoutMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.98:1
ListWith60ListItems.default | [600](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ListWith60ListItems.default.html) | [615](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.98:1
RosterPerf.default | [1134](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/RosterPerf.default.html) | [1153](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/RosterPerf.default_base.html) | 0.98:1
ButtonOverridesMissPerf.default | [1640](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1688](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.97:1
BoxMinimalPerf.default | [334](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/BoxMinimalPerf.default.html) | [347](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/BoxMinimalPerf.default_base.html) | 0.96:1
ChatWithPopoverPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ChatWithPopoverPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.96:1
LabelMinimalPerf.default | [374](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/LabelMinimalPerf.default.html) | [388](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.96:1
ButtonSlotsPerf.default | [509](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ButtonSlotsPerf.default.html) | [533](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.95:1
StatusMinimalPerf.default | [656](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/StatusMinimalPerf.default.html) | [696](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.94:1
ListCommonPerf.default | [588](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ListCommonPerf.default.html) | [630](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/ListCommonPerf.default_base.html) | 0.93:1
IconMinimalPerf.default | [570](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/IconMinimalPerf.default.html) | [617](https://fluentuipr.z22.web.core.windows.net/pull/18791/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.92:1

</details><div id="perfComment9423"/>

**Review by bsunderhus — APPROVED** [review]
LGTM

File: packages/react-menu/src/components/MenuList/renderMenuList.tsx [hunk 1]
```diff
@@ -28,6 +28,7 @@ export const renderMenuList = (state: MenuListState) => {
         setFocusByFirstCharacter,
         hasIcons,
         hasCheckmarks,
+        hasMenuListContext: true,
```
Comment (layershifter) [inline packages/react-menu/src/components/MenuList/renderMenuList.tsx:31]: This looks a bit strange 🙄

Do I correctly get that the goal is to check is a component is wrapped with `MenuListProvider`? In this case I would suggest to compare with a default value instead:

```ts
const defaultValue = {}
const Context = React.createContext()

//

functio useIsWrapped() {
  return defaultValue !== React.useContext(Context)
}
```

But as we are using context selectors I guess it's more complicated. I am correct?

Comment (ling1726) [reply packages/react-menu/src/components/MenuList/renderMenuList.tsx:31]: yes, I can't find a way to compare default context using context selector

Comment (layershifter) [reply packages/react-menu/src/components/MenuList/renderMenuList.tsx:31]:
```tsx
function useIsWrapped<Value>(context: Context<Value>) {
  const contextValue = React.useContext(
    (context as unknown) as Context<ContextValue<Value>>
  );

  // "-1" is default value for .version, "Provider" will always set it to "0"
  // This will not handle updates, but updates could happen only if we will change
  // React tree, but it means that components will be remounted
  return contextValue.version.current !== -1;
}
```

I made a quick prototype on CodeSandbox: https://codesandbox.io/s/rough-sea-39ssz?file=/src/App.tsx:241-673
I suggest to find a better name for this hook and place it in `context-selector` package as it could useful for other components
