### PR TITLE
fix(useAutoControlled): allow functions update passed to setSate

### LINKED ISSUE #14509: useAutoControlled: when function is passed wrong value will be used
### Environment Information

- **Package version(s)**: `@fluentui/react-bindings`
- **Browser and OS versions**: N/A

CodeSandbox: https://codesandbox.io/s/sharp-resonance-iqyjk?file=/src/App.js

1. Open a CodeSandbox example and open browser's console
2. Click on a header multiple times

#### Actual behavior:

```
App:onClick {prevStateValue: "foo11", value: "bar11"}
App:onClick {prevStateValue: "foo111", value: "bar111"}
```

```jsx
const [value, setValue] = useAutoControlled({
  defaultValue: props.defaultValue,
  value: props.value,

  initialValue: "foo"
});
```

When a function is passed to `setValue()` like in `React.useState`:

```js
setState(prevValue => prevValue + 1)
```

`prevValue` will equal to the `initialValue` 💣 

#### Expected behavior:

```
App:onClick {prevStateValue: "bar11", value: "bar11"}
App:onClick {prevStateValue: "bar111", value: "bar111"}
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High
Products/sites affected: N/A

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #14509
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

`setState` function returned by `useAutoControlled` should allow us to pass an updater function to se new value, e.g `setState(state => newState)`. Currently our hook is not keeping it consistent ( see #14509 ), this PR fixes that.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts [hunk 1]
```diff
@@ -17,7 +17,17 @@ export const useAutoControlled = <Value>(
   options: UseAutoControlledOptions<Value>,
 ): [Value, React.Dispatch<React.SetStateAction<Value>>] => {
   const { defaultValue, initialValue = undefined, value } = options;
-  const [state, setState] = React.useState<Value>(isUndefined(defaultValue) ? (initialValue as Value) : defaultValue);
+  const [_state, _setState] = React.useState<Value>(isUndefined(defaultValue) ? (initialValue as Value) : defaultValue);
 
-  return [isUndefined(value) ? state : value, setState];
+  const state = isUndefined(value) ? _state : value;
+
+  const setState = (newState: Value) => {
```
Comment (layershifter) [inline packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts:24]: This function is unstable

Comment (assuncaocharles) [reply packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts]: Added `useCallback`

File: packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts [hunk 2]
```diff
@@ -17,7 +17,20 @@ export const useAutoControlled = <Value>(
...
+
+  const setState = React.useCallback(
+    (newState: Value) => {
+      if (typeof newState === 'function') {
+        _setState(newState(state));
+      } else {
+        _setState(newState);
+      }
+    },
+    [state],
```
Comment (layershifter) [inline packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts:32]: This means that it will be recreated on each `state` change while `set*` from `React.useState()` is stable for all renders

Comment (assuncaocharles) [reply packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts]: Check now please

File: packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts [hunk 3]
```diff
@@ -17,7 +17,18 @@ export const useAutoControlled = <Value>(
   options: UseAutoControlledOptions<Value>,
 ): [Value, React.Dispatch<React.SetStateAction<Value>>] => {
   const { defaultValue, initialValue = undefined, value } = options;
-  const [state, setState] = React.useState<Value>(isUndefined(defaultValue) ? (initialValue as Value) : defaultValue);
+  const [_state, _setState] = React.useState<Value>(isUndefined(defaultValue) ? (initialValue as Value) : defaultValue);
```
Comment (layershifter) [inline packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts:20]:
```suggestion
  const [stateValue, setStateValue] = React.useState<Value>(isUndefined(defaultValue) ? (initialValue as Value) : defaultValue);
```

_nit_

File: packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts [hunk 4]
```diff
@@ -17,7 +17,18 @@ export const useAutoControlled = <Value>(
...
+  const state = isUndefined(value) ? _state : value;
```
Comment (layershifter) [inline packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts:21]:
```suggestion
  const value = isUndefined(options.value) ? stateValue : value;
```

File: packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts [hunk 5]
```diff
@@ -17,7 +17,18 @@ export const useAutoControlled = <Value>(
...
+  const setState = React.useCallback((newState: Value) => {
+    if (typeof newState === 'function') {
+      stateRef.current = newState(stateRef.current);
+    } else {
+      stateRef.current = newState;
+    }
+    _setState(stateRef.current);
+  }, []);
+
+  return [state, setState];
```
Comment (layershifter) [inline packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts:33]: Small update to naming to make it more clear:

```tsx
export const useAutoControlled = <Value>(
  options: UseAutoControlledOptions<Value>,
): [Value, React.Dispatch<React.SetStateAction<Value>>] => {
  const [stateValue, setStateValue] = React.useState<Value>(
    isUndefined(options.defaultValue) ? (options.initialValue as Value) : options.defaultValue,
  );

  const value = isUndefined(options.value) ? stateValue : options.value;
  // Used to avoid dependencies in "setValue"
  const valueRef = React.useRef(value);

  const setValue = React.useCallback((newState: Value) => {
    if (typeof newState === 'function') {
      // Handles functional updates
      // https://reactjs.org/docs/hooks-reference.html#functional-updates
      valueRef.current = newState(valueRef.current);
    } else {
      valueRef.current = newState;
    }

    setStateValue(valueRef.current);
  }, []);

  return [value, setValue];
};
```

**Review by layershifter — APPROVED** [review]
