### PR TITLE
fix: Making the hidden input on Radio only cover the indicator and not also the label

### LINKED ISSUE #25021: [Bug] react-radio: interactive items within the label are unreachable with a pointer
Same as #24330 but for `Radio` instead of `Checkbox`.

Similar changes to #24638 need to be applied.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

The hidden input in the `Radio` component covers both the indicator and the label, making any interactive elements within the label, like links, impossible to be clicked.

We also noticed that when hovering over the label of disabled `Switches`, it still showed `cursor: pointer` styles.

### Input

image

### Label

image

## New Behavior

The hidden input in the `Radio` component now covers only the indicator and its surrounding space, not the label. This makes any interactive elements within the label, like links, possible to be clicked. We verified that clicking on the label still toggles the state of the component. We also expanded the size of the label so it covers the empty space around it that was previously being covered by the hidden input.

Hovering over the label of disabled `Switches` now shows `cursor: default` instead of `cursor: pointer`.

### Input

image

### Label

image

## Related Issue(s)

Fixes #25021

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                          |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                   Change |
| :----------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>    | `35.769 kB`<br />`11.943 kB` | `36.737 kB`<br />`12.145 kB` | `968 B` <br />`202 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr> | `33.743 kB`<br />`10.654 kB` | `33.818 kB`<br />`10.675 kB` |   `75 B` <br />`21 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.156 kB`<br />`52.385 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |    `33.4 kB`<br />`11.008 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.857 kB`<br />`1.978 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |     `14.248 kB`<br />`5.7 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2e8d044a4ce2c1095f13e08716c3ba13069ebf0d'>2e8d044a4ce2c1095f13e08716c3ba13069ebf0d</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/Avatar-mount_base.html">1535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/Avatar-mount.html">1505</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/Button-mount_base.html">1078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/Button-mount.html">1093</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/FluentProvider-mount_base.html">1850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/FluentProvider-mount.html">1796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/FluentProviderWithTheme-mount_base.html">712</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/FluentProviderWithTheme-mount.html">733</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">677</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">722</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">726</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/MakeStyles-mount_base.html">2184</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/MakeStyles-mount.html">2195</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/SpinButton-mount_base.html">2936</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25025/perf-test-react-components/SpinButton-mount.html">2906</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts [hunk 1]
```diff
@@ -162,17 +173,24 @@ const useLabelStyles = makeStyles({
  * Apply styling to the Radio slots based on the state
  */
 export const useRadioStyles_unstable = (state: RadioState) => {
+  const { label, labelPosition } = state;
```
Comment (behowell) [inline packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts:176]: I don't think `label` is used anywhere? Or am I missing it?

File: packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts [hunk 2]
```diff
@@ -116,6 +115,15 @@ const useInputStyles = makeStyles({
       },
     },
   },
+
+  after: {
+    height: '100%',
+    width: `calc(${indicatorSize} + 2 * ${tokens.spacingHorizontalS})`,
+  },
+  below: {
+    height: `calc(${indicatorSize} + ${tokens.spacingVerticalS})`,
```
Comment (behowell) [inline packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts:124]: Does this need to account for top and bottom padding as well?
```suggestion
    height: `calc(${indicatorSize} + 2 * ${tokens.spacingVerticalS})`,
```

File: packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts [hunk 3]
```diff
@@ -116,6 +115,15 @@ const useInputStyles = makeStyles({
...
+    width: '100%',
+  },
```
Comment (behowell) [inline packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts:126]: The `base` styles specify width and height as 100%, so you only need to override the appropriate one:
```suggestion
  after: {
    width: `calc(${indicatorSize} + 2 * ${tokens.spacingHorizontalS})`,
  },
  below: {
    height: `calc(${indicatorSize} + 2 * ${tokens.spacingVerticalS})`,
  },
```

**Review by behowell — COMMENTED** [review]
I think you'd also need to add the pointer cursor to the label right? 

```diff
    ':enabled': {
      cursor: 'pointer',
+      [`& ~ .${radioClassNames.label}`]: {
+        cursor: 'pointer',
+      },
    },
```

File: packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts (hunk 1 above)
Comment (khmakoto) [reply packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts:176]: Removed.

File: packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts (hunk 3 above)
Comment (khmakoto) [reply packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts]: You're right, removed.

File: packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts (hunk 2 above)
Comment (khmakoto) [reply packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts]: Good catch, changed.

**Review by behowell — APPROVED** [review]
