### PR TITLE
fix: Dismiss Menu when MenuLinkItem is clicked.

### LINKED ISSUE #30442: [Bug]: clicking MenuItemLink does not dismiss Menu
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Window, Mac, Browser
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/cool-chaplygin-l77mvt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls06f2km00063b6i3awz3jvx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls06f2km00023b6iaia5lzrh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls06f2km00033b6ixudyv1g8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls06f2km00053b6ijl448byk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls06f2km00023b6iaia5lzrh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls06f2kl00013b6i8r6oby2s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls06fzic003k3b6ixc7ewdf6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fexample.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls06f2km00023b6iaia5lzrh%2522%252C%2522activeTabId%2522%253A%2522cls06fzic003k3b6ixc7ewdf6%2522%257D%252C%2522cls06f2km00053b6ijl448byk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls06f2km00043b6iipvysrll%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls06f2km00053b6ijl448byk%2522%252C%2522activeTabId%2522%253A%2522cls06f2km00043b6iipvysrll%2522%257D%252C%2522cls06f2km00033b6ixudyv1g8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls06f2km00033b6ixudyv1g8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

## Actual Behavior
Menu still open after clicking MenuItemLink item

## Expected Behavior
Menu should dismissed after clicking MenuItemLink item

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by SantoshPisini**
## Previous Behavior

The menu is still open after clicking the MenuItemLink item.

## New Behavior

Dismissing the Menu when MenuLinkItem is clicked.

- Fixes #30442

### CODE REVIEW

File: packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts [hunk 1]
```diff
@@ -19,6 +20,17 @@ export const useMenuItemLink_unstable = (
...
+  const open = useMenuContext_unstable(context => context.open);
+
+  const _props = { ...props };
+  _props.onClick = useEventCallback(event => {
+    if (open) {
+      setOpen(event, { open: false, type: 'menuItemClick', event });
+    }
+    props.onClick?.(event);
+  });
+
```
Comment (bsunderhus) [inline packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts:33]: `baseState` has a `root` definition that does this already https://github.com/microsoft/fluentui/blob/ec40bb1e90e55b722a57d11182c4110bfce9051e/packages/react-components/react-menu/src/components/MenuItem/useMenuItem.tsx#L74-L87, would be better to try to reuse it

File: packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts [hunk 2]
```diff
@@ -29,7 +41,7 @@ export const useMenuItemLink_unstable = (
       getIntrinsicElementProps('a', {
         ref,
         role: 'menuitem',
-        ...props,
+        ..._props,
```
Comment (bsunderhus) [inline packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts:44]:
```suggestion
       // FIXME: casting because the root slot changes from div to a,
        // ideal solution would be to extract common logic from useMenuItem_unstable
        // and use it in both without assuming element type
        ...(baseState.root as ExtractSlotProps<Slot<'a'>>),
```

File: packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts (hunk 1 above)
Comment (bsunderhus) [reply packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts:33]: Also, we'd need to provide as well `onKeyDown` and `onMouseEnter` handlers

**Review by bsunderhus — CHANGES_REQUESTED** [review]
Thanks for the catch @SantoshPisini! I'm not sure this would be the right way to go though, it seems like you're repeating an incomplete part of the logic from `useMenuItem`.

@ling1726 , please confirm if using `baseState` would be enough to solve this.

Also, would be amazing to add tests to ensure the proper behaviour!

File: packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts (hunk 1 above)
Comment (SantoshPisini) [reply packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts]: Updated!

File: packages/react-components/react-menu/src/components/MenuItemLink/MenuItemLink.test.tsx
Comment (bsunderhus) [inline packages/react-components/react-menu/src/components/MenuItemLink/MenuItemLink.test.tsx:1]: 💪🏻💪🏻

File: packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts [hunk 3]
```diff
@@ -19,6 +19,21 @@ export const useMenuItemLink_unstable = (
...
+  _props.onClick = useEventCallback(event => {
+    (baseState.root as ExtractSlotProps<Slot<'a'>>).onClick?.(event);
+  });
+  _props.onKeyDown = useEventCallback(event => {
+    (baseState.root as ExtractSlotProps<Slot<'a'>>).onKeyDown?.(event);
+  });
+  _props.onMouseEnter = useEventCallback(event => {
+    (baseState.root as ExtractSlotProps<Slot<'a'>>).onMouseEnter?.(event);
+  });
+
```
Comment (bsunderhus) [inline packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts:36]: nit: no need to mutate anything (also, less overrides), just spreading state after props would be enough

```suggestion
  // FIXME: casting because the root slot changes from div to a,
  // ideal solution would be to extract common logic from useMenuItem_unstable root
  // and use it in both without assuming element type
  const _props = { ...props, ...(baseState as ExtractSlotProps<Slot<'a'>>) };
```

**Review by bsunderhus — APPROVED** [review]

**Comment by ling1726** [comment]
> @ling1726 , please confirm if using `baseState` would be enough to solve this.
> 
> Also, would be amazing to add tests to ensure the proper behaviour!

@bsunderhus I agree `baseState` should be used here. The typing is less than convenient, but it makes sense for both kinds of menu items to share behaviour.  The fact that the entire slot was overriden was definitely an oversight on my part

File: packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts [hunk 4]
```diff
@@ -19,20 +19,11 @@ export const useMenuItemLink_unstable = (
...
-    (baseState.root as ExtractSlotProps<Slot<'a'>>).onClick?.(event);
-  });
-  _props.onKeyDown = useEventCallback(event => {
-    (baseState.root as ExtractSlotProps<Slot<'a'>>).onKeyDown?.(event);
-  });
-  _props.onMouseEnter = useEventCallback(event => {
-    (baseState.root as ExtractSlotProps<Slot<'a'>>).onMouseEnter?.(event);
-  });
+  const _props = { ...props, ...(baseState.root as ExtractSlotProps<Slot<'a'>>) };
+  _props.ref = ref;
```
Comment (bsunderhus) [inline packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts:26]:
```suggestion
  const _props = { ...props, ...(baseState.root as ExtractSlotProps<Slot<'a'>>), ref };
```

File: packages/react-components/react-menu/src/components/MenuItemLink/__snapshots__/MenuItemLink.test.tsx.snap [hunk 5]
```diff
@@ -6,6 +6,7 @@ exports[`MenuItemLink renders a default state 1`] = `
     class="fui-MenuItemLink fui-MenuItem"
     href="#"
     role="menuitem"
+    tabindex="0"
```
Comment (bsunderhus) [inline packages/react-components/react-menu/src/components/MenuItemLink/__snapshots__/MenuItemLink.test.tsx.snap:9]: Seems like the `baseState` introduces some extra unnecessary tabIndex=0, we can easily remove it: https://github.com/microsoft/fluentui/pull/30497/files/a7ccbce6deae3edae71f5cd3fe71134c28dc8eb2..b79067e0bcceb977204c59bb03a48166d8c3f614#r1486318397

**Review by bsunderhus — CHANGES_REQUESTED** [review]
It's looking great, let's just ensure `tabIndex` is not unnecessarily introduced here

File: packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts (hunk 4 above)
Comment (SantoshPisini) [reply packages/react-components/react-menu/src/components/MenuItemLink/useMenuItemLink.ts]: Changed!

File: packages/react-components/react-menu/src/components/MenuItemLink/__snapshots__/MenuItemLink.test.tsx.snap (hunk 5 above)
Comment (SantoshPisini) [reply packages/react-components/react-menu/src/components/MenuItemLink/__snapshots__/MenuItemLink.test.tsx.snap]: Changed!

**Review by bsunderhus — APPROVED** [review]

**Comment by SantoshPisini** [comment]
@bsunderhus Do I need to do something to get these pipelines started Fluent UI React - PR and CI & Fluent UI React - Perf-Test?

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/Avatar-mount_base.html">641</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/Avatar-mount.html">644</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/Button-mount_base.html">294</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/Button-mount.html">305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/Field-mount_base.html">1131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/Field-mount.html">1180</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/FluentProvider-mount_base.html">703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/FluentProvider-mount.html">714</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/FluentProviderWithTheme-mount_base.html">76</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/FluentProviderWithTheme-mount.html">72</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">58</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">65</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">71</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">65</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/MakeStyles-mount_base.html">858</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/MakeStyles-mount.html">859</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/Persona-mount_base.html">1756</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/Persona-mount.html">1771</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/SpinButton-mount_base.html">1411</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30497/perf-test-react-components/SpinButton-mount.html">1361</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>
