### PR TITLE
fix(carousel): fix variables propagation

### LINKED ISSUE #15992: Carousel: Width variable not visible in docs site and not propagated to other slots
### Environment Information

- **Package version(s)**: 0.51.x
- **Browser and OS versions**: mac

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/pcrou?module=/example.js
(see lines 126-128)

#### Actual behavior:

It is required to pass width variable to all slots

#### Expected behavior:

width variable should be automatically propagated

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #15992
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

`variables` weren't being passed down to paddles, this is fixed by passing it to `overrideProps`

#### Focus areas to test

(optional)

### CODE REVIEW

**Review by ling1726 — APPROVED** [review]

File: packages/fluentui/react-northstar/src/components/Carousel/Carousel.tsx [hunk 1]
```diff
@@ -364,6 +364,7 @@ export const Carousel: ComponentWithAs<'div', CarouselProps> &
   };
 
   const handlePaddleOverrides = (predefinedProps: CarouselPaddleProps, paddleName: string) => ({
+    variables,
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Carousel/Carousel.tsx:367]: Variables should be merged 

```suggestion
    variables: mergeVariablesOverrides(variables, predefinedProps.variables),
```

**Review by layershifter — CHANGES_REQUESTED** [review]
Please check a comment about `variables`

**Review by layershifter — APPROVED** [review]
