### PR TITLE
fix: use Button to compose FormButton

### LINKED ISSUE #19081: Northstar FormButton cannot be configured as `type='submit'`
### Environment Information

- **Package version(s)**: fluent-ui/react-northstar 0.57.0

#### Actual behavior:

Passing `type='submit'` to `FormButton` throughs type error:

```ts
<FormButton type="submit" />
```

```
Type '{ id: string; "data-testid": string; content: string; disabled: boolean; type: string; }' is not assignable to type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, "as" | keyof FormButtonProps> & { ...; } & FormButtonProps & Pick<...>'.
  Property 'type' does not exist on type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, "as" | keyof FormButtonProps> & { ...; } & FormButtonProps & Pick<...>'.ts(2322)
```

#### Expected behavior:

No type error

### Priorities and help requested:

No, no capacity at the immediate moment

Requested priority: (High)

### PR DESCRIPTION
**Pull request by chassunc**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #19081
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Compose `FormButton`  with button to allow the right props to be passed

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0be0cbcacc5175dbef4445a5e7d7e85e4b75e937'>0be0cbcacc5175dbef4445a5e7d7e85e4b75e937</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Avatar-mount_base.html">850</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Avatar-mount.html">860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/BaseButton-mount_base.html">876</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/BaseButton-mount.html">851</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Breadcrumb-mount_base.html">2522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Breadcrumb-mount.html">2548</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ButtonNext-mount_base.html">400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ButtonNext-mount.html">412</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Checkbox-mount_base.html">1472</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Checkbox-mount.html">1485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/CheckboxBase-mount_base.html">1252</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/CheckboxBase-mount.html">1249</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ChoiceGroup-mount_base.html">4577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ChoiceGroup-mount.html">4555</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ComboBox-mount_base.html">959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ComboBox-mount.html">1020</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/CommandBar-mount_base.html">9870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/CommandBar-mount.html">9854</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ContextualMenu-mount_base.html">6142</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ContextualMenu-mount.html">6099</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DefaultButton-mount_base.html">1103</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DefaultButton-mount.html">1078</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DetailsRow-mount_base.html">3701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DetailsRow-mount.html">3695</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DetailsRowFast-mount_base.html">3674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DetailsRowFast-mount.html">3647</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DetailsRowNoStyles-mount_base.html">3402</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DetailsRowNoStyles-mount.html">3453</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Dialog-mount_base.html">2109</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Dialog-mount.html">2097</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DocumentCardTitle-mount_base.html">135</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/DocumentCardTitle-mount.html">132</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Dropdown-mount_base.html">3163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Dropdown-mount.html">3150</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/FluentProviderNext-mount_base.html">7582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/FluentProviderNext-mount.html">7400</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/FocusTrapZone-mount_base.html">1772</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/FocusTrapZone-mount.html">1840</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/FocusZone-mount_base.html">1810</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/FocusZone-mount.html">1872</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/IconButton-mount_base.html">1756</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/IconButton-mount.html">1642</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Label-mount_base.html">347</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Label-mount.html">328</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Layer-mount_base.html">1757</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Layer-mount.html">1735</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Link-mount_base.html">447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Link-mount.html">447</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/MakeStyles-mount_base.html">1782</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/MakeStyles-mount.html">1791</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/MenuButton-mount_base.html">1434</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/MenuButton-mount.html">1451</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/MessageBar-mount_base.html">1984</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/MessageBar-mount.html">1997</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Nav-mount_base.html">3174</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Nav-mount.html">3314</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/OverflowSet-mount_base.html">1024</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/OverflowSet-mount.html">1027</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Panel-mount_base.html">1330</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Panel-mount.html">2063</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Persona-mount_base.html">812</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Persona-mount.html">795</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Pivot-mount_base.html">1375</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Pivot-mount.html">1379</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/PrimaryButton-mount_base.html">1243</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/PrimaryButton-mount.html">1332</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Rating-mount_base.html">7524</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Rating-mount.html">7545</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/SearchBox-mount_base.html">1290</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/SearchBox-mount.html">1313</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Shimmer-mount_base.html">2537</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Shimmer-mount.html">2495</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Slider-mount_base.html">1918</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Slider-mount.html">1900</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/SpinButton-mount_base.html">4868</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/SpinButton-mount.html">4889</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Spinner-mount_base.html">407</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Spinner-mount.html">403</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/SplitButton-mount_base.html">3075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/SplitButton-mount.html">3093</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Stack-mount_base.html">490</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Stack-mount.html">481</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/StackWithIntrinsicChildren-mount_base.html">1521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/StackWithIntrinsicChildren-mount.html">1520</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/StackWithTextChildren-mount_base.html">4416</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/StackWithTextChildren-mount.html">4421</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/SwatchColorPicker-mount_base.html">10020</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/SwatchColorPicker-mount.html">10042</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Tabs-mount_base.html">1371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Tabs-mount.html">1355</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/TagPicker-mount_base.html">2523</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/TagPicker-mount.html">2489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/TeachingBubble-mount_base.html">11674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/TeachingBubble-mount.html">11686</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Text-mount_base.html">406</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Text-mount.html">399</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/TextField-mount_base.html">1340</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/TextField-mount.html">1306</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ThemeProvider-mount_base.html">1147</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ThemeProvider-mount.html">1149</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ThemeProvider-virtual-rerender_base.html">585</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/ThemeProvider-virtual-rerender.html">605</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Toggle-mount_base.html">810</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/Toggle-mount.html">778</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/buttonNative-mount_base.html">116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test/buttonNative-mount.html">117</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AccordionMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AccordionMinimalPerf.default.html) | [142](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.1:1
AttachmentMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AttachmentMinimalPerf.default.html) | [143](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.09:1
ButtonMinimalPerf.default | [171](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ButtonMinimalPerf.default.html) | [159](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.08:1
ChatDuplicateMessagesPerf.default | [296](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [274](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.08:1
RadioGroupMinimalPerf.default | [444](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [418](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.06:1
SegmentMinimalPerf.default | [342](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/SegmentMinimalPerf.default.html) | [322](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.06:1
ButtonSlotsPerf.default | [559](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ButtonSlotsPerf.default.html) | [537](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
ChatMinimalPerf.default | [651](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ChatMinimalPerf.default.html) | [624](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.04:1
AnimationMinimalPerf.default | [409](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AnimationMinimalPerf.default.html) | [398](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.03:1
ChatWithPopoverPerf.default | [357](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ChatWithPopoverPerf.default.html) | [346](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.03:1
DropdownManyItemsPerf.default | [686](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DropdownManyItemsPerf.default.html) | [669](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.03:1
FlexMinimalPerf.default | [284](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/FlexMinimalPerf.default.html) | [276](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.03:1
HeaderMinimalPerf.default | [359](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/HeaderMinimalPerf.default.html) | [350](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.03:1
LabelMinimalPerf.default | [376](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/LabelMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.03:1
ReactionMinimalPerf.default | [378](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ReactionMinimalPerf.default.html) | [366](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.03:1
SkeletonMinimalPerf.default | [351](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/SkeletonMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.03:1
TextMinimalPerf.default | [343](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TextMinimalPerf.default.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.03:1
VideoMinimalPerf.default | [616](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/VideoMinimalPerf.default.html) | [596](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.03:1
FormMinimalPerf.default | [376](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/FormMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.02:1
HeaderSlotsPerf.default | [735](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/HeaderSlotsPerf.default.html) | [720](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [504](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ListMinimalPerf.default.html) | [492](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
MenuButtonMinimalPerf.default | [1602](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1578](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.02:1
PopupMinimalPerf.default | [588](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/PopupMinimalPerf.default.html) | [574](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.02:1
RefMinimalPerf.default | [239](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/RefMinimalPerf.default.html) | [235](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.02:1
StatusMinimalPerf.default | [669](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/StatusMinimalPerf.default.html) | [654](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.02:1
TooltipMinimalPerf.default | [1000](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TooltipMinimalPerf.default.html) | [985](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.02:1
BoxMinimalPerf.default | [331](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/BoxMinimalPerf.default.html) | [328](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.01:1
ImageMinimalPerf.default | [356](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ImageMinimalPerf.default.html) | [352](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.01:1
ListCommonPerf.default | [625](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ListCommonPerf.default.html) | [620](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [851](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/MenuMinimalPerf.default.html) | [840](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1882](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TableManyItemsPerf.default.html) | [1870](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
ToolbarMinimalPerf.default | [954](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ToolbarMinimalPerf.default.html) | [946](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.01:1
AlertMinimalPerf.default | [265](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AlertMinimalPerf.default.html) | [266](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2679](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2669](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [5245](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5255](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
DialogMinimalPerf.default | [728](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DialogMinimalPerf.default.html) | [725](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
DividerMinimalPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DividerMinimalPerf.default.html) | [347](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4057](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/EmbedMinimalPerf.default.html) | [4065](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
GridMinimalPerf.default | [330](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/GridMinimalPerf.default.html) | [331](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/GridMinimalPerf.default_base.html) | 1:1
LoaderMinimalPerf.default | [671](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/LoaderMinimalPerf.default.html) | [674](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1634](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1639](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3748](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3749](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
TableMinimalPerf.default | [409](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TableMinimalPerf.default.html) | [408](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TableMinimalPerf.default_base.html) | 1:1
TreeMinimalPerf.default | [753](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TreeMinimalPerf.default.html) | [751](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1:1
AttachmentSlotsPerf.default | [1027](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1041](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.99:1
AvatarMinimalPerf.default | [187](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AvatarMinimalPerf.default.html) | [189](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.99:1
ProviderMinimalPerf.default | [964](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ProviderMinimalPerf.default.html) | [972](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.99:1
CustomToolbarPrototype.default | [3829](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/CustomToolbarPrototype.default.html) | [3865](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.99:1
TreeWith60ListItems.default | [168](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TreeWith60ListItems.default.html) | [169](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.99:1
ItemLayoutMinimalPerf.default | [1158](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1177](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.98:1
LayoutMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/LayoutMinimalPerf.default.html) | [356](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.98:1
ListNestedPerf.default | [530](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ListNestedPerf.default.html) | [543](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ListNestedPerf.default_base.html) | 0.98:1
ButtonOverridesMissPerf.default | [1670](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1715](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 0.97:1
CardMinimalPerf.default | [530](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/CardMinimalPerf.default.html) | [546](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.97:1
DropdownMinimalPerf.default | [3047](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DropdownMinimalPerf.default.html) | [3127](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.97:1
InputMinimalPerf.default | [1216](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/InputMinimalPerf.default.html) | [1248](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.97:1
PortalMinimalPerf.default | [163](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/PortalMinimalPerf.default.html) | [168](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/PortalMinimalPerf.default_base.html) | 0.97:1
SliderMinimalPerf.default | [1564](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/SliderMinimalPerf.default.html) | [1614](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.97:1
TextAreaMinimalPerf.default | [467](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TextAreaMinimalPerf.default.html) | [480](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.97:1
CarouselMinimalPerf.default | [444](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/CarouselMinimalPerf.default.html) | [463](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.96:1
IconMinimalPerf.default | [573](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/IconMinimalPerf.default.html) | [601](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.95:1
RosterPerf.default | [1098](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/RosterPerf.default.html) | [1175](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/RosterPerf.default_base.html) | 0.93:1
ListWith60ListItems.default | [582](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ListWith60ListItems.default.html) | [634](https://fluentuipr.z22.web.core.windows.net/pull/19308/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.92:1

</details><div id="perfComment9423"/>

File: packages/fluentui/react-northstar/src/components/Form/FormButton.tsx [hunk 1]
```diff
@@ -16,15 +16,13 @@ export const formButtonClassName = 'ui-form__button';
 /**
  * An FormButton renders a Button wrapped by FormField.
  */
-export const FormButton = compose<'div', FormButtonProps, FormButtonStylesProps, SelectedFormFieldCustomProps, {}>(
-  _FormFieldBase,
+export const FormButton = compose<'button', FormButtonProps, FormButtonStylesProps, SelectedFormFieldCustomProps, {}>(
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Form/FormButton.tsx:19]: Might not be so easy since the styles of the component are determined by component display name if I understand N* styling correctly, you'll need to figure out a way to retain the button styles here.

**Review by ling1726 — DISMISSED** [review]
This seems inconsistent with other form fields, since it would be the only that is not wrapped by a `div`

**Comment by chassunc** [comment]
> This seems inconsistent with other form fields, since it would be the only that is not wrapped by a `div`

Button isn't a form field, I think that makes sense here, but doesn't have label or error message. WDYT @layershifter

File: packages/fluentui/react-northstar/src/components/Form/FormButton.tsx [hunk 2]
```diff
@@ -3,7 +3,9 @@ import { commonPropTypes } from '../../utils';
 import { Button, ButtonProps } from '../Button/Button';
 import { _FormFieldBase, FormFieldBaseProps } from './utils/formFieldBase';
 
-interface FormButtonOwnProps extends ButtonProps {}
+interface FormButtonOwnProps extends ButtonProps {
+  type?: string;
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Form/FormButton.tsx:7]: Interesting, I wonder why this isn't  available in `ButtonProps` it's a valid attr for the native `Button`

File: packages/fluentui/react-northstar/src/components/Form/FormButton.tsx [hunk 3]
```diff
@@ -3,7 +3,9 @@ import { commonPropTypes } from '../../utils';
...
+}
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Form/FormButton.tsx:8]:
```suggestion
```

It's caused by `compose()` config, can we do this change instead:

```diff
-export const FormButton = compose<'div', FormButtonProps, FormButtonStylesProps, SelectedFormFieldCustomProps, {}>(
+export const FormButton = compose<'button', FormButtonProps, FormButtonStylesProps, SelectedFormFieldCustomProps, {}>(
```

**Review by layershifter — APPROVED** [review]
