### PR TITLE
bugfix(react-jsx-runtime): static children problem on render function

### LINKED ISSUE #29144: [Bug]: When slot with children is used then error/warning is shown: React.jsx: Static children should always be an array.
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
PS C:\Projects\fluent-ui-jsx-runtime> npx envinfo --system --npmPackages '{@fluent/*}' --browsers
Need to install the following packages:
  envinfo@7.10.0
Ok to proceed? (y)

  System:
    OS: Windows 10 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 5.75 GB / 31.79 GB
  Browsers:
    Edge: Spartan (44.22621.2262.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/vlaskal/fluent-ui-v9-jsx-runtime-issue

### Bug Description

I want to customize `AccordionHeader` component via [Slot API](https://react.fluentui.dev/?path=/docs/concepts-developer-customizing-components-with-slots--page#customizing-components-with-slots) when we want to override default rendering of `button` slot. I followed the documentation [Replacing-the-entire-slot](https://react.fluentui.dev/?path=/docs/concepts-developer-customizing-components-with-slots--page#replacing-the-entire-slot) and I came with the following code:
```typescript
const headerRenderer = (Inner, innerProps) => {
    return (
        <>
            <Inner {...innerProps} />
            <div ... >
                <Button ... >Insert</Button>
            </div>
        </>
    );
}
<AccordionHeader button={{ children: headerRenderer }} ... > ... </AccordionHeader>
```
More can be found in `InsertItem.tsx` file in linked repository. 

This code works as expected in production build and also works without any problems in development build `npm run dev` on Vite + React based project till version `9.30.1` of `@fluentui/react-components` package. To be more precise, it works without issue till version `9.3.7`of `@fluentui/react-accordion` package.

## Actual Behavior
In version `9.30.2` of `@fluentui/react-components` respectively `9.3.8` of `@fluentui/react-accordion` and later is behavior change in development build. Browser `Console log` is flooded by following error:
```
Warning: React.jsx: Static children should always be an array. You are likely explicitly calling React.jsxs or React.jsxDEV. Use the Babel transform instead.
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:35834:17
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14299:17
    at InsertItem (http://localhost:5174/src/InsertItem.tsx:27:21)
    at InsertActionItem1
    at Provider2 (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:2730:43)
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14202:17
    at App
    at div
    at TextDirectionProvider (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:13884:3)
    at http://localhost:5174/node_modules/.vite/deps/@fluentui_react-components.js?v=40c2882c:1309:17
```
Application works fine but any other errors or warnings are hidden by them. You can check it in attached repository project by following steps:
* npm install
* npm run dev
* Open application in browser
* Open console log in browser
* Refresh it
* A lot of errors are generated

## Expected Behavior
Development build will not produce additional errors or warnings as was in versions `9.30.1` of `@fluentui/react-components` respectively `9.3.7` of `@fluentui/react-accordion`.

This behavior can be checked in attached repository project by following steps:
* Update version of `@fluentui/react-accordion` package to `9.3.7`
* npm install
* npm run dev
* Open application in browser
* Open console log in browser
* Refresh it
* No errors are generated

## Additional Info
I think following PRs #28943, #28959 and #28962 can be source of changed behaviour. 

### Logs

```shell
﻿
installHook.js:251 
 Warning: React.jsx: Static children should always be an array. You are likely explicitly calling React.jsxs or React.jsxDEV. Use the Babel transform instead.
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:35834:17
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14299:17
    at InsertItem (http://localhost:5174/src/InsertItem.tsx:27:21)
    at InsertActionItem1
    at Provider2 (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:2730:43)
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14202:17
    at App
    at div
    at TextDirectionProvider (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:13884:3)
    at http://localhost:5174/node_modules/.vite/deps/@fluentui_react-components.js?v=40c2882c:1309:17
react-jsx-runtime.development.js:87 
 Warning: React.jsx: Static children should always be an array. You are likely explicitly calling React.jsxs or React.jsxDEV. Use the Babel transform instead.
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:35834:17
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14299:17
    at InsertItem (http://localhost:5174/src/InsertItem.tsx:27:21)
    at InsertActionItem2
    at Provider2 (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:2730:43)
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14202:17
    at App
    at div
    at TextDirectionProvider (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:13884:3)
    at http://localhost:5174/node_modules/.vite/deps/@fluentui_react-components.js?v=40c2882c:1309:17
installHook.js:251 
 Warning: React.jsx: Static children should always be an array. You are likely explicitly calling React.jsxs or React.jsxDEV. Use the Babel transform instead.
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:35834:17
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14299:17
    at InsertItem (http://localhost:5174/src/InsertItem.tsx:27:21)
    at InsertActionItem2
    at Provider2 (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:2730:43)
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14202:17
    at App
    at div
    at TextDirectionProvider (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:13884:3)
    at http://localhost:5174/node_modules/.vite/deps/@fluentui_react-components.js?v=40c2882c:1309:17
react-jsx-runtime.development.js:87 
 Warning: React.jsx: Static children should always be an array. You are likely explicitly calling React.jsxs or React.jsxDEV. Use the Babel transform instead.
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:35834:17
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14299:17
    at InsertItem (http://localhost:5174/src/InsertItem.tsx:27:21)
    at InsertActionItem3
    at Provider2 (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:2730:43)
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14202:17
    at App
    at div
    at TextDirectionProvider (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:13884:3)
    at http://localhost:5174/node_modules/.vite/deps/@fluentui_react-components.js?v=40c2882c:1309:17
installHook.js:251 
 Warning: React.jsx: Static children should always be an array. You are likely explicitly calling React.jsxs or React.jsxDEV. Use the Babel transform instead.
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:35834:17
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14299:17
    at InsertItem (http://localhost:5174/src/InsertItem.tsx:27:21)
    at InsertActionItem3
    at Provider2 (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:2730:43)
    at div
    at http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:14202:17
    at App
    at div
    at TextDirectionProvider (http://localhost:5174/node_modules/.vite/deps/chunk-4OIPOZFD.js?v=c1559de4:13884:3)
    at http://localhost:5174/node_modules/.vite/deps/@fluentui_react-components.js?v=40c2882c:1309:17
﻿
```

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by bsunderhus**
## New Behavior

The new React jsx runtime splits the creation of a jsx element into 2, one for static elements and one for dynamic elements.

A static element is an element with a well defined amount of unkeyed children (above one), unkeyed chldren means a set of children where their position does not change, something like these:

```tsx
<div id="parent">
  <div>child 1</div>
  <div>child 2</div>
  <div>child 3</div>
</div>
```

in this case on the newest react runtime this will be transpiled to something like:

```js
jsxs("div", {
  id: "parent",
  children: [
    jsx("div", { children: "child1" }),
    jsx("div", { children: "child2" }),
    jsx("div", { children: "child3" }),
  ],
});
```

Notice that the first `parent` div is rendered by invoking a `jsxs` method meanwhile all it's children are rendered by a `jsx` method.

A static element will always have as it's children an array of unkeyed content. A dynamic element on the other hand cannot understand an array of unkeyed content.

> ❗️ Warning: React.jsx: Static children should always be an array. You are likely explicitly calling React.jsxs or React.jsxDEV. Use the Babel transform instead.

The  problem issued on #29144 shows that on a render function of the `button` slot we're dealing with a case where a static element children is being passed down to a dynamic element. 

This PR solves this by wrapping this children around a single static fragment and then passing it down as the children of the render function, that way the render function (which will probably be a dynamic render) can easily render the children again as either a static or a dynamic content.

## Related Issue(s)

- Fixes #29144

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                  Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `91.384 kB`<br />`27.926 kB` |  `91.495 kB`<br />`27.961 kB` | `111 B` <br />`35 B`  |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |   `84.36 kB`<br />`23.094 kB` |  `84.471 kB`<br />`23.125 kB` | `111 B` <br />`31 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `49.738 kB`<br />`15.631 kB` |  `49.849 kB`<br />`15.661 kB` | `111 B` <br />`30 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                                                          |   `18.584 kB`<br />`7.448 kB` |   `18.695 kB`<br />`7.479 kB` | `111 B` <br />`31 B`  |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                                  |   `64.39 kB`<br />`19.977 kB` |  `64.501 kB`<br />`20.009 kB` | `111 B` <br />`32 B`  |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `25.793 kB`<br />`8.348 kB` |   `25.904 kB`<br />`8.386 kB` | `111 B` <br />`38 B`  |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `26.694 kB`<br />`8.658 kB` |   `26.805 kB`<br />`8.694 kB` | `111 B` <br />`36 B`  |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |     `24.75 kB`<br />`8.96 kB` |   `24.861 kB`<br />`8.994 kB` | `111 B` <br />`34 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |  `39.469 kB`<br />`10.758 kB` |   `39.58 kB`<br />`10.788 kB` | `111 B` <br />`30 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `46.824 kB`<br />`12.259 kB` |  `46.935 kB`<br />`12.287 kB` | `111 B` <br />`28 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |  `43.896 kB`<br />`12.025 kB` |  `44.007 kB`<br />`12.058 kB` | `111 B` <br />`33 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `51.922 kB`<br />`13.596 kB` |  `52.033 kB`<br />`13.623 kB` | `111 B` <br />`27 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `56.557 kB`<br />`12.667 kB` |  `56.668 kB`<br />`12.698 kB` | `111 B` <br />`31 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `91.249 kB`<br />`26.409 kB` |   `91.36 kB`<br />`26.439 kB` | `111 B` <br />`30 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `86.038 kB`<br />`24.868 kB` |  `86.149 kB`<br />`24.901 kB` | `111 B` <br />`33 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |   `11.951 kB`<br />`5.031 kB` |   `12.062 kB`<br />`5.065 kB` | `111 B` <br />`34 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |   `14.237 kB`<br />`5.798 kB` |    `14.348 kB`<br />`5.83 kB` | `111 B` <br />`32 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |   `12.903 kB`<br />`5.408 kB` |   `13.014 kB`<br />`5.441 kB` | `111 B` <br />`33 B`  |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr>                                                                              |  `35.614 kB`<br />`11.771 kB` |  `35.725 kB`<br />`11.807 kB` | `111 B` <br />`36 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                                                 |   `90.383 kB`<br />`29.52 kB` |  `90.494 kB`<br />`29.547 kB` | `111 B` <br />`27 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>                                                 |  `88.738 kB`<br />`29.167 kB` |  `88.849 kB`<br />`29.194 kB` | `111 B` <br />`27 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `69.328 kB`<br />`19.608 kB` |  `69.439 kB`<br />`19.637 kB` | `111 B` <br />`29 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `208.141 kB`<br />`59.349 kB` | `208.252 kB`<br />`59.375 kB` | `111 B` <br />`26 B`  |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `40.713 kB`<br />`13.509 kB` |  `40.824 kB`<br />`13.543 kB` | `111 B` <br />`34 B`  |
| <samp>react-datepicker-compat</samp> <br /> <abbr title='bundle-size/DatePicker.fixture.js'>DatePicker Compat</abbr>                                                          |  `211.441 kB`<br />`58.79 kB` | `211.552 kB`<br />`58.821 kB` | `111 B` <br />`31 B`  |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |  `89.925 kB`<br />`27.453 kB` |  `90.036 kB`<br />`27.483 kB` | `111 B` <br />`30 B`  |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |    `19.704 kB`<br />`7.38 kB` |   `19.815 kB`<br />`7.408 kB` | `111 B` <br />`28 B`  |
| <samp>react-field</samp> <br /> <abbr title='bundle-size/Field.fixture.js'>Field</abbr>                                                                                       |   `21.036 kB`<br />`8.091 kB` |   `21.147 kB`<br />`8.123 kB` | `111 B` <br />`32 B`  |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |    `14.62 kB`<br />`5.869 kB` |   `14.731 kB`<br />`5.897 kB` | `111 B` <br />`28 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoButton.fixture.js'>InfoButton</abbr>                                                                        | `129.602 kB`<br />`40.729 kB` | `129.713 kB`<br />`40.762 kB` | `111 B` <br />`33 B`  |
| <samp>react-infobutton</samp> <br /> <abbr title='bundle-size/InfoLabel.fixture.js'>InfoLabel</abbr>                                                                          | `133.328 kB`<br />`41.913 kB` | `133.439 kB`<br />`41.937 kB` | `111 B` <br />`24 B`  |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |    `25.955 kB`<br />`8.81 kB` |   `26.066 kB`<br />`8.842 kB` | `111 B` <br />`32 B`  |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/DevRuntime.fixture.js'>JSX Dev Runtime</abbr>                                                                  |     `2.775 kB`<br />`1.29 kB` |    `2.886 kB`<br />`1.327 kB` | `111 B` <br />`37 B`  |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/Runtime.fixture.js'>JSX Runtime</abbr>                                                                         |    `3.293 kB`<br />`1.529 kB` |    `3.404 kB`<br />`1.566 kB` | `111 B` <br />`37 B`  |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |   `13.036 kB`<br />`5.405 kB` |    `13.147 kB`<br />`5.44 kB` | `111 B` <br />`35 B`  |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `15.902 kB`<br />`6.506 kB` |   `16.013 kB`<br />`6.543 kB` | `111 B` <br />`37 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          |  `139.629 kB`<br />`43.01 kB` |  `139.74 kB`<br />`43.054 kB` | `111 B` <br />`44 B`  |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `142.365 kB`<br />`43.541 kB` | `142.476 kB`<br />`43.575 kB` | `111 B` <br />`34 B`  |
| <samp>react-persona</samp> <br /> <abbr title='bundle-size/Persona.fixture.js'>Persona</abbr>                                                                                 |  `56.629 kB`<br />`17.505 kB` |   `56.74 kB`<br />`17.535 kB` | `111 B` <br />`30 B`  |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `118.701 kB`<br />`37.361 kB` | `118.812 kB`<br />`37.405 kB` | `111 B` <br />`44 B`  |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressBar.fixture.js'>ProgressBar</abbr>                                                                        |    `16.409 kB`<br />`6.58 kB` |    `16.52 kB`<br />`6.616 kB` | `111 B` <br />`36 B`  |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `21.258 kB`<br />`7.937 kB` |   `21.369 kB`<br />`7.973 kB` | `111 B` <br />`36 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |   `29.318 kB`<br />`9.699 kB` |   `29.429 kB`<br />`9.734 kB` | `111 B` <br />`35 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |   `14.344 kB`<br />`5.942 kB` |   `14.455 kB`<br />`5.975 kB` | `111 B` <br />`33 B`  |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                                                    |   `27.324 kB`<br />`9.773 kB` |   `27.435 kB`<br />`9.811 kB` | `111 B` <br />`38 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |  `36.849 kB`<br />`12.171 kB` |   `36.96 kB`<br />`12.209 kB` | `111 B` <br />`38 B`  |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |   `35.53 kB`<br />`11.367 kB` |  `35.641 kB`<br />`11.405 kB` | `111 B` <br />`38 B`  |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `22.292 kB`<br />`8.113 kB` |   `22.403 kB`<br />`8.147 kB` | `111 B` <br />`34 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |  `31.885 kB`<br />`10.356 kB` |  `31.996 kB`<br />`10.393 kB` | `111 B` <br />`37 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                                                                                 | `156.416 kB`<br />`43.567 kB` |   `156.527 kB`<br />`43.6 kB` | `111 B` <br />`33 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>                                                            |  `42.463 kB`<br />`13.255 kB` |  `42.574 kB`<br />`13.291 kB` | `111 B` <br />`36 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>                                                                 | `129.276 kB`<br />`34.739 kB` | `129.388 kB`<br />`34.768 kB` | `112 B` <br />`29 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr>                                                         |   `74.56 kB`<br />`20.053 kB` |  `74.671 kB`<br />`20.088 kB` | `111 B` <br />`35 B`  |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>                                                                   |  `73.191 kB`<br />`19.649 kB` |  `73.302 kB`<br />`19.684 kB` | `111 B` <br />`35 B`  |
| <samp>react-tags-preview</samp> <br /> <abbr title='bundle-size/InteractionTag.fixture.js'>InteractionTag</abbr>                                                              |    `13.85 kB`<br />`5.626 kB` |   `13.961 kB`<br />`5.661 kB` | `111 B` <br />`35 B`  |
| <samp>react-tags-preview</samp> <br /> <abbr title='bundle-size/tag.fixture.js'>Tag</abbr>                                                                                    |   `29.604 kB`<br />`9.567 kB` |   `29.715 kB`<br />`9.603 kB` | `111 B` <br />`36 B`  |
| <samp>react-tags-preview</samp> <br /> <abbr title='bundle-size/TagGroup.fixture.js'>TagGroup</abbr>                                                                          |  `72.493 kB`<br />`21.628 kB` |  `72.604 kB`<br />`21.657 kB` | `111 B` <br />`29 B`  |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `15.644 kB`<br />`6.223 kB` |   `15.755 kB`<br />`6.256 kB` | `111 B` <br />`33 B`  |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `18.817 kB`<br />`6.546 kB` |   `18.928 kB`<br />`6.583 kB` | `111 B` <br />`37 B`  |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                                                              |  `30.005 kB`<br />`10.156 kB` |  `30.116 kB`<br />`10.188 kB` | `111 B` <br />`32 B`  |
| <samp>react-toast</samp> <br /> <abbr title='bundle-size/Toast.fixture.js'>Toast (including Toaster)</abbr>                                                                   |  `91.601 kB`<br />`27.394 kB` |  `91.712 kB`<br />`27.421 kB` | `111 B` <br />`27 B`  |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |   `51.154 kB`<br />`18.06 kB` |  `51.265 kB`<br />`18.097 kB` | `111 B` <br />`37 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                     |       Size (minified/GZIP) |
| --------------------------------------------------------------------------------------------------------------------- | -------------------------: |
| <samp>react-jsx-runtime</samp> <br /> <abbr title='bundle-size/Classic.fixture.js'>Classic Pragma</abbr>              |    `1.072 kB`<br />`544 B` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> | `6.541 kB`<br />`2.227 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6840cead921e4d30772dd9ab2cd234fe26a690f4'>6840cead921e4d30772dd9ab2cd234fe26a690f4</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/Avatar-mount_base.html">607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/Avatar-mount.html">612</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/Button-mount_base.html">315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/Button-mount.html">322</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/Field-mount_base.html">1118</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/Field-mount.html">1096</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/FluentProvider-mount_base.html">683</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/FluentProvider-mount.html">702</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/FluentProviderWithTheme-mount_base.html">74</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/FluentProviderWithTheme-mount.html">78</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">66</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">69</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">64</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">77</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/InfoButton-mount_base.html">16</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/InfoButton-mount.html">13</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/MakeStyles-mount_base.html">844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/MakeStyles-mount.html">839</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/Persona-mount_base.html">1701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/Persona-mount.html">1708</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/SpinButton-mount_base.html">1332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29162/perf-test-react-components/SpinButton-mount.html">1362</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-jsx-runtime/src/jsx/jsxDEVSlot.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
+import * as React from 'react';
+import { SlotComponentType, UnknownSlotProps } from '@fluentui/react-utilities';
+import { getMetadataFromSlotComponent } from '../utils/getMetadataFromSlotComponent';
+import { DevRuntime } from '../utils/DevRuntime';
+
+export const jsxDEVSlot = <Props extends UnknownSlotProps>(
+  type: SlotComponentType<Props>,
+  overrideProps: Props | null,
+  key?: React.Key,
+  source?: unknown,
```
Comment (ling1726) [inline packages/react-components/react-jsx-runtime/src/jsx/jsxDEVSlot.ts:10]: can `source` be another value apart from boolean?

File: packages/react-components/react-jsx-runtime/src/utils/types.ts [hunk 2]
```diff
@@ -7,3 +8,20 @@ export type JSXRuntime = <P extends {}>(
...
+  overrideProps: Props | null,
+  key?: React.Key,
+  source?: unknown,
+  self?: unknown,
+) => React.ReactElement<Props>;
+
+/**
+ * @internal
+ */
+export enum RuntimeType {
```
Comment (ling1726) [inline packages/react-components/react-jsx-runtime/src/utils/types.ts:23]: I don't see this enum being used anywhere

File: packages/react-components/react-jsx-runtime/src/jsx-runtime.test.tsx [hunk 3]
```diff
@@ -266,20 +266,29 @@ describe('createElement with assertSlots', () => {
...
       type TestComponentState = ComponentState<TestComponentSlots>;
       type TestComponentProps = ComponentProps<Partial<TestComponentSlots>>;
 
       const TestComponent = (props: TestComponentProps) => {
         const state: TestComponentState = {
-          components: { outer: 'div', inner: 'div' },
-          inner: slot.always(props.inner, { defaultProps: { id: 'inner' }, elementType: 'div' }),
+          components: { outer: 'div', inner1: 'div', inner2: 'div' },
+          inner1: slot.always(props.inner1, { defaultProps: { id: 'inner-1' }, elementType: 'div' }),
+          inner2: slot.always(props.inner2, { defaultProps: { id: 'inner-2' }, elementType: 'div' }),
```
Comment (ling1726) [inline packages/react-components/react-jsx-runtime/src/jsx-runtime.test.tsx:284]: do you actually need a second slot here? since the outer slot is rendered with a dynamic element it should always be rendered as a dynamic element

Comment (bsunderhus) [reply packages/react-components/react-jsx-runtime/src/jsx-runtime.test.tsx:284]: Yes. What dictates if an element is rendered with `jsxs` instead of `jsx` is having a fixed amount of children bigger than one, so to force the render of `outer` slot as `jsxs` it need inside of it at least 2 well defined children.

**Review by ling1726 — APPROVED** [review]

File: packages/react-components/react-jsx-runtime/src/jsx-runtime.test.tsx [hunk 4]
```diff
@@ -289,17 +298,33 @@ describe('createElement with assertSlots', () => {
...
-      const result = render(<TestComponent outer={{ children }} inner={{ children: 'Inner children' }} />);
+      const result = render(
+        <TestComponent
+          outer={{ children }}
+          inner1={{ children: 'Inner children 1' }}
+          inner2={{ children: 'Inner children 2' }}
+        />,
+      );
 
+      // your test code here
```
Comment (layershifter) [inline packages/react-components/react-jsx-runtime/src/jsx-runtime.test.tsx:309]: Cruft?
