### PR TITLE
fix(Dropdown): interrupts IME input on controlled search

### LINKED ISSUE #17760: Dropdown component's Search Selection in controlled mode has issue with typing in language using certain IME
### Environment Information

- **Package version(s)**: 0.54.0
- **Browser and OS versions**: any

### Describe the issue:

The Dropdown component's Search Selection in controlled mode has issue with typing in language that relies on IME where composition completes with more than one letter, like Korean. Currently if user types 'r' and 'k' with Korean Microsoft IME, it shows ㄱ가 which is 'r' followed by 'rk'. But the correct character it enters should be only 가 which is 'rk'.

I think the problem is that the Dropdown component is firing the `onSearchQueryChange` before the composition is complete. Or alternatively, it should return the [KeyboardEvent.isComposing](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing) so consumer can detect that composition is not complete and not save the value to state.

#### Actual behavior:

Presses keys 'r' and 'k' in Korean currently shows ㄱ가, which is 'r' followed by 'rk'.

#### Expected behavior:

Presses keys 'r' and 'k' in Korean should show 가, which is 'rk'.

### If applicable, please provide a codepen repro:

1. Go to https://codesandbox.io/s/fluent-ui-example-forked-d9zms?file=/example.js:0-889
2. Switch to Korean Microsoft IME, and in the dropdown search input, type 'r' and 'k'.
3. If you comment out the line `searchQuery={localSearchQuery}` (so it's not in controlled mode), then it works correctly.

Here is the source code for the sandbox
```
import React from "react";
import { Dropdown } from "@fluentui/react-northstar";

const inputItems = [
  "Robert Tolbert",
  "Wanda Howard",
  "Tim Deboer",
  "Amanda Brady",
  "Ashley McCarthy",
  "Cameron Evans",
  "Carlos Slattery",
  "Carole Poland",
  "Robin Counts"
];

const DropdownExampleSearch = () => {
  const [localSearchQuery, setLocalSearchQuery] = React.useState("a");
  const onSearchQueryChange = (_: any, data: any) => {
    setLocalSearchQuery(data?.searchQuery || "");
  };

  return (
    <Dropdown
      search
      searchQuery={localSearchQuery}
      onSearchQueryChange={onSearchQueryChange}
      items={inputItems}
      placeholder="Start typing a name"
      noResultsMessage="We couldn't find any matches."
      getA11ySelectionMessage={{
        onAdd: (item) => `${item} has been selected.`
      }}
    />
  );
};

export default DropdownExampleSearch;

```

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: https://teams.microsoft.com/share, although we have a work around for now, which is to not use controlled mode.

### PR DESCRIPTION
**Pull request by YuanboXue-Amber**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #17760 
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

When Dropdown is controlled, it does not accept IME input properly. IME input were interrupted
beforefix

After fix:
afterfix

Reason for this fix:
IME doesn't play well with controlled input. 
When using controlled input, having input's value as state, 
`<input value={value} onChange={(e) =>  setValue(e.target.value)}` - has no problem with IME
but something like `<input value={value} onChange={(e) =>  setValue(e.target.value + '-')}` - breaks IME
[codesandbox](https://codesandbox.io/s/ime-controlled-input-forked-p55hn?file=/src/App.js)

During investigation, I saw [this issue in downshift](https://github.com/downshift-js/downshift/issues/217#issuecomment-334847328), where it mentions:
>This looks like the `setState` call replaces the value of the text field after typing has finished, essentially overwriting what's in the field...

Downshift js moved `onInputValueChange` to be called before its setState to fix this issue(https://github.com/downshift-js/downshift/blob/ce6c4e1a434bb483cf1f0386937cb9aa313220ab/src/downshift.js#L318)

So I moved our onSearchQuery to be called `onInputValueChange`, instead of `onStateChange` and it resolves our issue with IME.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Avatar-mount_base.html">789</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Avatar-mount.html">797</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/BaseButton-mount_base.html">891</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/BaseButton-mount.html">895</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Breadcrumb-mount_base.html">2624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Breadcrumb-mount.html">2679</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ButtonNext-mount_base.html">469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ButtonNext-mount.html">486</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Checkbox-mount_base.html">1497</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Checkbox-mount.html">1533</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/CheckboxBase-mount_base.html">1236</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/CheckboxBase-mount.html">1264</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ChoiceGroup-mount_base.html">4637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ChoiceGroup-mount.html">4682</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ComboBox-mount_base.html">970</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ComboBox-mount.html">1007</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/CommandBar-mount_base.html">10246</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/CommandBar-mount.html">10178</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ContextualMenu-mount_base.html">6125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ContextualMenu-mount.html">6160</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DefaultButton-mount_base.html">1112</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DefaultButton-mount.html">1117</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DetailsRow-mount_base.html">3708</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DetailsRow-mount.html">3774</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DetailsRowFast-mount_base.html">3761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DetailsRowFast-mount.html">3710</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DetailsRowNoStyles-mount_base.html">3504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DetailsRowNoStyles-mount.html">3488</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Dialog-mount_base.html">2112</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Dialog-mount.html">2121</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DocumentCardTitle-mount_base.html">133</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/DocumentCardTitle-mount.html">145</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Dropdown-mount_base.html">3231</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Dropdown-mount.html">3224</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/FocusTrapZone-mount_base.html">1793</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/FocusTrapZone-mount.html">1814</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/FocusZone-mount_base.html">1809</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/FocusZone-mount.html">1823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/IconButton-mount_base.html">1753</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/IconButton-mount.html">1688</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Label-mount_base.html">329</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Label-mount.html">343</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Layer-mount_base.html">1761</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Layer-mount.html">1772</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Link-mount_base.html">450</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Link-mount.html">455</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/MakeStyles-mount_base.html">1795</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/MakeStyles-mount.html">1781</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/MenuButton-mount_base.html">1449</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/MenuButton-mount.html">1440</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/MessageBar-mount_base.html">1987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/MessageBar-mount.html">2022</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Nav-mount_base.html">3196</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Nav-mount.html">3223</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/OverflowSet-mount_base.html">1017</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/OverflowSet-mount.html">1011</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Panel-mount_base.html">2076</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Panel-mount.html">2062</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Persona-mount_base.html">813</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Persona-mount.html">804</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Pivot-mount_base.html">1399</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Pivot-mount.html">1400</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/PrimaryButton-mount_base.html">1265</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/PrimaryButton-mount.html">1258</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Rating-mount_base.html">7515</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Rating-mount.html">7493</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/SearchBox-mount_base.html">1264</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/SearchBox-mount.html">1293</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Shimmer-mount_base.html">2505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Shimmer-mount.html">2483</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Slider-mount_base.html">1960</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Slider-mount.html">1945</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/SpinButton-mount_base.html">4931</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/SpinButton-mount.html">4972</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Spinner-mount_base.html">414</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Spinner-mount.html">411</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/SplitButton-mount_base.html">3137</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/SplitButton-mount.html">3136</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Stack-mount_base.html">501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Stack-mount.html">489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/StackWithIntrinsicChildren-mount_base.html">1488</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/StackWithIntrinsicChildren-mount.html">1484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/StackWithTextChildren-mount_base.html">4488</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/StackWithTextChildren-mount.html">4398</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/SwatchColorPicker-mount_base.html">10047</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/SwatchColorPicker-mount.html">10091</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Tabs-mount_base.html">1384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Tabs-mount.html">1375</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/TagPicker-mount_base.html">2397</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/TagPicker-mount.html">2403</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/TeachingBubble-mount_base.html">11709</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/TeachingBubble-mount.html">11766</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Text-mount_base.html">417</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Text-mount.html">410</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/TextField-mount_base.html">1332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/TextField-mount.html">1374</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ThemeProvider-mount_base.html">1170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ThemeProvider-mount.html">1174</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ThemeProvider-virtual-rerender_base.html">605</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ThemeProvider-virtual-rerender.html">599</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ThemeProviderNext-mount_base.html">7111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/ThemeProviderNext-mount.html">7103</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Toggle-mount_base.html">823</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/Toggle-mount.html">797</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/buttonNative-mount_base.html">114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test/buttonNative-mount.html">119</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AccordionMinimalPerf.default | [159](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AccordionMinimalPerf.default.html) | [135](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.18:1
AttachmentMinimalPerf.default | [154](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AttachmentMinimalPerf.default.html) | [144](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.07:1
ButtonMinimalPerf.default | [173](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ButtonMinimalPerf.default.html) | [165](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.05:1
ImageMinimalPerf.default | [364](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ImageMinimalPerf.default.html) | [346](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.05:1
VideoMinimalPerf.default | [626](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/VideoMinimalPerf.default.html) | [598](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.05:1
ChatWithPopoverPerf.default | [377](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ChatWithPopoverPerf.default.html) | [363](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.04:1
ListNestedPerf.default | [551](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ListNestedPerf.default.html) | [528](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ListNestedPerf.default_base.html) | 1.04:1
AvatarMinimalPerf.default | [188](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AvatarMinimalPerf.default.html) | [183](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.03:1
FlexMinimalPerf.default | [285](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/FlexMinimalPerf.default.html) | [278](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.03:1
FormMinimalPerf.default | [400](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/FormMinimalPerf.default.html) | [390](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.03:1
LoaderMinimalPerf.default | [693](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/LoaderMinimalPerf.default.html) | [674](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.03:1
PortalMinimalPerf.default | [179](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/PortalMinimalPerf.default.html) | [174](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.03:1
ReactionMinimalPerf.default | [369](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ReactionMinimalPerf.default.html) | [358](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [346](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/SegmentMinimalPerf.default.html) | [337](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
SkeletonMinimalPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/SkeletonMinimalPerf.default.html) | [343](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.03:1
TableMinimalPerf.default | [397](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TableMinimalPerf.default.html) | [384](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.03:1
TreeWith60ListItems.default | [174](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TreeWith60ListItems.default.html) | [169](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.03:1
AttachmentSlotsPerf.default | [1116](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1097](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [458](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/CarouselMinimalPerf.default.html) | [450](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
ChatMinimalPerf.default | [616](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ChatMinimalPerf.default.html) | [603](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.02:1
CheckboxMinimalPerf.default | [2743](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2700](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.02:1
DropdownManyItemsPerf.default | [666](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DropdownManyItemsPerf.default.html) | [653](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.02:1
DropdownMinimalPerf.default | [3073](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DropdownMinimalPerf.default.html) | [3018](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.02:1
EmbedMinimalPerf.default | [4093](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/EmbedMinimalPerf.default.html) | [4019](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.02:1
LabelMinimalPerf.default | [383](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/LabelMinimalPerf.default.html) | [374](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.02:1
RadioGroupMinimalPerf.default | [440](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [431](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.02:1
TextAreaMinimalPerf.default | [490](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TextAreaMinimalPerf.default.html) | [481](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.02:1
CardMinimalPerf.default | [539](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/CardMinimalPerf.default.html) | [536](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.01:1
DialogMinimalPerf.default | [743](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DialogMinimalPerf.default.html) | [736](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.01:1
DividerMinimalPerf.default | [353](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DividerMinimalPerf.default.html) | [349](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [1224](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/InputMinimalPerf.default.html) | [1212](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [1236](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1225](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
PopupMinimalPerf.default | [565](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/PopupMinimalPerf.default.html) | [560](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.01:1
IconMinimalPerf.default | [602](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/IconMinimalPerf.default.html) | [599](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1880](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TableManyItemsPerf.default.html) | [1867](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
AnimationMinimalPerf.default | [406](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AnimationMinimalPerf.default.html) | [407](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1:1
BoxMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/BoxMinimalPerf.default.html) | [345](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1642](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1644](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
ButtonSlotsPerf.default | [540](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ButtonSlotsPerf.default.html) | [541](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1:1
LayoutMinimalPerf.default | [364](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/LayoutMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1:1
MenuMinimalPerf.default | [819](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/MenuMinimalPerf.default.html) | [823](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1547](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1550](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1651](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1650](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [954](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ProviderMinimalPerf.default.html) | [951](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1:1
RefMinimalPerf.default | [232](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/RefMinimalPerf.default.html) | [232](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/RefMinimalPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1535](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/SliderMinimalPerf.default.html) | [1529](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [660](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/StatusMinimalPerf.default.html) | [658](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3773](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/CustomToolbarPrototype.default.html) | [3755](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
TooltipMinimalPerf.default | [967](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TooltipMinimalPerf.default.html) | [969](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3651](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3671](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 0.99:1
ToolbarMinimalPerf.default | [943](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ToolbarMinimalPerf.default.html) | [950](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.99:1
TreeMinimalPerf.default | [778](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TreeMinimalPerf.default.html) | [782](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.99:1
GridMinimalPerf.default | [326](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/GridMinimalPerf.default.html) | [334](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/GridMinimalPerf.default_base.html) | 0.98:1
HeaderMinimalPerf.default | [352](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/HeaderMinimalPerf.default.html) | [360](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.98:1
HeaderSlotsPerf.default | [741](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/HeaderSlotsPerf.default.html) | [760](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.98:1
ListMinimalPerf.default | [507](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ListMinimalPerf.default.html) | [515](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ListMinimalPerf.default_base.html) | 0.98:1
AlertMinimalPerf.default | [259](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AlertMinimalPerf.default.html) | [266](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.97:1
ChatDuplicateMessagesPerf.default | [280](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [288](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.97:1
DatepickerMinimalPerf.default | [5209](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5347](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.97:1
TextMinimalPerf.default | [340](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TextMinimalPerf.default.html) | [352](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.97:1
ListCommonPerf.default | [594](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ListCommonPerf.default.html) | [619](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ListCommonPerf.default_base.html) | 0.96:1
RosterPerf.default | [1115](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/RosterPerf.default.html) | [1167](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/RosterPerf.default_base.html) | 0.96:1
ListWith60ListItems.default | [616](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ListWith60ListItems.default.html) | [668](https://fluentuipr.z22.web.core.windows.net/pull/18478/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.92:1

</details><div id="perfComment9423"/>

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -822,14 +822,26 @@ export const Dropdown: ComponentWithAs<'div', DropdownProps> &
     }
   };
 
+  const handleInputValueChange = (inputValue: string) => {
+    if (multiple) {
+      setStateAndInvokeHandler(['onSearchQueryChange'], null, {
+        searchQuery: '',
```
Comment (miroslavstastny) [inline packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx:828]: This will not work. `searchQuery` is used to filter list of items, see `getFilteredValues()`. It should be cleared only on Esc and when an item is selected (`getSelectedItemAsString()`  in `Downshift.stateChangeTypes.clickItem` which you removed).

To repro, use keyboard to filter items in Search Multiple example.

It scares me that no test is failing :-/

**Review by miroslavstastny — CHANGES_REQUESTED** [review]
This is breaking Multiple Search, see the comment.

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx (hunk 1 above)
Comment (YuanboXue-Amber) [reply packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx]: Thank you Miro for catching this. I made a change and added the filtering case for multiple search in unit test L1413

**Review by miroslavstastny — APPROVED** [review]
lgtm, would appreciate one more pair of eyes - @ling1726?

**Review by ling1726 — APPROVED** [review]
I tested the variants of the dropdown in the docsite and can't identify any obvious issues. I confess that even though the code changes look simple `Downshift` is still a big mystery to me

**Comment by YuanboXue-Amber** [comment]
> I tested the variants of the dropdown in the docsite and can't identify any obvious issues. I confess that even though the code changes look simple `Downshift` is still a big mystery to me

Thanks I feel the same. I'll leave this open until it gets verified in TMP

**Comment by YuanboXue-Amber** [comment]
Reason for commit [59ddffa](https://github.com/microsoft/fluentui/pull/18478/commits/59ddffa2ba40b732bb0cfbcc1f167cdb7f7e4b8a)

Here's a minimum repro of a usage in TMP

```jsx
import React from 'react';
import { Dropdown } from '@fluentui/react-northstar';

const inputItems = [
  'Robert Tolbert',
  'Wanda Howard',
  'Tim Deboer',
  'Amanda Brady',
  'Ashley McCarthy',
  'Cameron Evans',
  'Carlos Slattery',
  'Carole Poland',
  'Robin Counts',
];

const PPContainer = () => {
  const [items, setItems] = React.useState(inputItems);

  const [searchQuery, setSearchQuery] = React.useState('');
  const onSearchChange = (_: any, { searchQuery }) => {
    setSearchQuery(searchQuery);
    if (searchQuery.length === 0) {
      setItems([]);
    }
  };

  const [selectedUsers, setSelectedUsers] = React.useState([]);
  const onSelectionChange = (_: any, { selectedUsers }) => {
    setItems([]);
    setSelectedUsers(selectedUsers);
  };

  return (
    <PPRenderer
      items={items}
      searchQuery={searchQuery}
      onSearchChange={onSearchChange}
      onSelectionChange={onSelectionChange}
      selectedUsers={selectedUsers}
    />
  );
};

const PPRenderer = ({ items, searchQuery, onSearchChange, onSelectionChange, selectedUsers }) => {
  const onSelectedChange = (_, { value }) => {
    if (items.length > 0) {
      onSelectionChange(_, {
        selectedUsers: value,
      });
    }
  };

  return (
    <Dropdown
      search
      multiple
      searchQuery={searchQuery}
      onSearchQueryChange={onSearchChange}
      onChange={onSelectedChange}
      value={selectedUsers}
      items={items}
      placeholder="Start typing a name"
      noResultsMessage="We couldn't find any matches."
      getA11ySelectionMessage={{
        onAdd: item => `${item} has been selected.`,
      }}
    />
  );
};

export default PPContainer;
```

Before this commit, in this example, when an item is selected:
1. Downshift `onInputValueChange` invoke Dropdown `onSearchQueryChange` callback and set state
2. `onSearchChange` is called in PPContainer and sets `items` to empty array
3. Downshift `onStateChange` invoke Dropdown `onChange`
4. `onSelectedChange` is called in PPRender, but since `items` is empty, it does not set any item to be selected

After this commit, in this example, when an item is selected, step 1 and 2 do not happen. So when step 4 is executed, `items` array is not empty, so the item can be selected normally

**Review by miroslavstastny — APPROVED** [review]

**Comment by YuanboXue-Amber** [comment]
Confirmed by people team this is a good fix
