### PR TITLE
fix: avoid infinite loop of setStates in Sticky/ScrollablePane

### LINKED ISSUE #16654: Issue with Scrollable component when scroll bar is at bottom of page
### Environment Information
Package version(s)**: 7.156 (also reproducible in 7.149 and in 8.111.2)
Browser and OS versions**: Chrome

reproduction of the bug in a codepen: : https://codepen.io/goutham-a/pen/JjRVXOJ 

Issue : Scrollable component not working as expected at 80% screen width
Description: When we scroll to the end of the screen using mouse in chrome(all recent versions),a blank screen is displayed and  data in details list is lost.  see error with "maximum update depth exceeded" with scrollable component(on debugging). probably an infinite loop is happening at set state. And I see this issue only at 80% screen size(or zoom) in chrome.It works perfectly fine in all other zoom percentage. I am easily able to replicate this with codepen using Fluentui samples(examples)

Actual behavior:
Scroll bar should work even after scroll is at the bottom at all screen zoom percent\size

 Expected behavior: Once the user scrolls to the bottom of the page and user  clicks on mouse scroll,  data is lost and empty page is displayed- at 80% screen size\zoom

# Priorities and help requested:

Requested priority: Blocking

Products/sites affected: We have implemented controls using scrollable component and power apps component framework and this is failing.

### PR DESCRIPTION
**Pull request by spmonahan**
## Previous Behavior

A `ScrollablePane` with a bottom `Sticky` could fall into an infinite loop and crash React.

## New Behavior

The root of this issue is that certain measurement APIs return fractional values and these values seem to jitter for display settings where the multiples of system display scaling and browser zoom levels don't lend themselves to returning integer values (for example OS scaling of 125% and browser zoom of 67%). These zoom/scaling combinations aren't strictly required but picking "bad" values can make reproducing the issue easier.

In this case querying `scrollTop` would return different fractional values within a pixel of one another but above and below an integer (e.g., 4.99 and 5.6). Critically, applying `Math.ceil()`, `Math.floor()` or `Math.round()` cannot correct for this situation in all cases. For example 4.99 becomes 5, 4 and 5, respectively while 5.6 becomes 6, 5 and 6 respectively 😥

The solution in this PR is to add a wrapper for querying `scrollTop` that will treat values within a certain range as the same. So we can get `getScrollTop(element, 1)` and so long as the values are within a pixel of each other we will return the same value, stabilizing the value within a small range.

## Related Issue(s)

- Fixes #16654

### Repro steps

1. Use Windows or macOS, Chrome or Edge (macOS seems to reproduce the issue more readily but it's possible on both OSes)
2. Test apps
    1. WITH BUG (you should be able to reproduce the bug here): https://codepen.io/seanms/pen/QWzEZGR?editors=0010
    2. WITHOUT BUG (you should not be able to reproduce the bug here): https://codesandbox.io/s/fluentui-react-8-starter-forked-js7q9r?file=/src/index.tsx
4. Set browser zoom to 67%
5. Use the trackpad to scroll up and down repeatedly as fast as possible
6. Eventually the app will blank out. This means you've triggered the bug.
7. Open dev tools to see the error

This video demonstrates how to reproduce the issue prior to this fix

https://github.com/microsoft/fluentui/assets/93940821/21d056b2-5637-47cd-9848-b9d7acfcd9c5

### CODE REVIEW

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/03ff2af91de2dc1cd4bc4f3d60735d39396634a5'>03ff2af91de2dc1cd4bc4f3d60735d39396634a5</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/BaseButton-mount_base.html">636</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/BaseButton-mount.html">679</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Breadcrumb-mount_base.html">1637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Breadcrumb-mount.html">1672</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Checkbox-mount_base.html">1666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Checkbox-mount.html">1675</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/CheckboxBase-mount_base.html">1469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/CheckboxBase-mount.html">1468</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ChoiceGroup-mount_base.html">2943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ChoiceGroup-mount.html">2976</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ComboBox-mount_base.html">663</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ComboBox-mount.html">661</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/CommandBar-mount_base.html">6129</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/CommandBar-mount.html">6182</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ContextualMenu-mount_base.html">12879</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ContextualMenu-mount.html">12655</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DefaultButton-mount_base.html">739</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DefaultButton-mount.html">732</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DetailsRow-mount_base.html">2142</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DetailsRow-mount.html">2145</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DetailsRowFast-mount_base.html">2165</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DetailsRowFast-mount.html">2117</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DetailsRowNoStyles-mount_base.html">2013</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DetailsRowNoStyles-mount.html">1995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Dialog-mount_base.html">2771</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Dialog-mount.html">2622</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DocumentCardTitle-mount_base.html">224</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/DocumentCardTitle-mount.html">228</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Dropdown-mount_base.html">1987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Dropdown-mount.html">1995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/FocusTrapZone-mount_base.html">1097</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/FocusTrapZone-mount.html">1120</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/FocusZone-mount_base.html">1034</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/FocusZone-mount.html">1097</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedList-mount_base.html">41476</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedList-mount.html">41439</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedList-virtual-rerender_base.html">20001</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedList-virtual-rerender.html">19693</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">50832</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedList-virtual-rerender-with-unmount.html">50630</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedListV2-mount_base.html">236</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedListV2-mount.html">228</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedListV2-virtual-rerender_base.html">206</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedListV2-virtual-rerender.html">210</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">225</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">225</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/IconButton-mount_base.html">1053</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/IconButton-mount.html">1083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Label-mount_base.html">325</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Label-mount.html">336</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Layer-mount_base.html">2694</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Layer-mount.html">2697</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Link-mount_base.html">377</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Link-mount.html">392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/MenuButton-mount_base.html">938</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/MenuButton-mount.html">936</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/MessageBar-mount_base.html">21113</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/MessageBar-mount.html">21022</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Nav-mount_base.html">1928</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Nav-mount.html">1929</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/OverflowSet-mount_base.html">772</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/OverflowSet-mount.html">757</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Panel-mount_base.html">2069</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Panel-mount.html">1772</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Persona-mount_base.html">723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Persona-mount.html">752</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Pivot-mount_base.html">863</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Pivot-mount.html">857</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/PrimaryButton-mount_base.html">819</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/PrimaryButton-mount.html">827</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Rating-mount_base.html">4457</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Rating-mount.html">4578</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/SearchBox-mount_base.html">923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/SearchBox-mount.html">913</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Shimmer-mount_base.html">1860</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Shimmer-mount.html">1866</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Slider-mount_base.html">1310</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Slider-mount.html">1324</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/SpinButton-mount_base.html">2814</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/SpinButton-mount.html">2902</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Spinner-mount_base.html">384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Spinner-mount.html">381</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/SplitButton-mount_base.html">1834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/SplitButton-mount.html">1793</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Stack-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Stack-mount.html">424</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/StackWithIntrinsicChildren-mount_base.html">834</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/StackWithIntrinsicChildren-mount.html">846</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/StackWithTextChildren-mount_base.html">2567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/StackWithTextChildren-mount.html">2589</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/SwatchColorPicker-mount_base.html">5984</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/SwatchColorPicker-mount.html">6058</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/TagPicker-mount_base.html">1443</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/TagPicker-mount.html">1460</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Text-mount_base.html">369</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Text-mount.html">358</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/TextField-mount_base.html">925</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/TextField-mount.html">924</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ThemeProvider-mount_base.html">817</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ThemeProvider-mount.html">821</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ThemeProvider-virtual-rerender_base.html">597</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ThemeProvider-virtual-rerender.html">588</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1261</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1260</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Toggle-mount_base.html">605</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/Toggle-mount.html">598</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/buttonNative-mount_base.html">199</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29054/perf-test/buttonNative-mount.html">190</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: packages/react/src/components/Sticky/util/scroll.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+export type GetScrollTopInRange = (el: HTMLElement, range: number) => number;
+
+export type ScrollUtils = {
+  getScrollTopInRange: GetScrollTopInRange;
+};
+
+export const getScrollUtils: () => ScrollUtils = () => {
+  const scrollTopElements = new Map<HTMLElement, number>();
```
Comment (spmonahan) [inline packages/react/src/components/Sticky/util/scroll.ts:8]: This came up in a conversation elsewhere: there is potentially a memory leak here as `Map`'s keys will be HTML elements and the map will maintain a reference to those keys even if the HTML element is otherwise eligible for garbage collection. Ultimately I think this is okay because the map itself will go out of scope when `getScrollUtils()`'s caller goes out of scope and will release its references then.

Definitely would like more input here though!

**Review by micahgodbolt — APPROVED** [review]

**Review by khmakoto — APPROVED** [review]

**Comment by gardnerjr** [comment]
Following.  What's required to complete this?  We've recently found this issue and temporarily are losing sticky headers to avoid it but would love to be back to working!

**Comment by spmonahan** [comment]
> Following. What's required to complete this? We've recently found this issue and temporarily are losing sticky headers to avoid it but would love to be back to working!

@gardnerjr We're validating the change internally before merging. The initial fix worked for the repro case in this thread but didn't handle all the cases of this bug. Since we have a path to validate the issue in the real world we're just waiting on that before merging this change (or continuing work if we uncover another case to handle).

**Comment by gardnerjr** [comment]
> @gardnerjr We're validating the change internally before merging. The initial fix worked for the repro case in this thread but didn't handle all the cases of this bug. Since we have a path to validate the issue in the real world we're just waiting on that before merging this change (or continuing work if we uncover another case to handle).

@spmonahan Sounds good.  Another case that i know of is possibly related to the behavior of the sort icon in the column header when using the Azure fluent theme?  not sure if you're aware of that one?

File: change/@fluentui-react-f18a600f-1e2d-4047-b9c8-7af2f331ad3a.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (fabricteam) [inline change/@fluentui-react-f18a600f-1e2d-4047-b9c8-7af2f331ad3a.json:1]: ## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=29054&commitId=fdad7ff7788a77678c9f3f22d15b1b43a2b9d095&env=prod&clientType=FLUENTUI)


  <details><summary><b>react-charting-VerticalBarChart</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|react-charting-VerticalBarChart.Basic - Secondary Y Axis.default.chromium.png|4| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

Comment (spmonahan) [reply change/@fluentui-react-f18a600f-1e2d-4047-b9c8-7af2f331ad3a.json:1]: Noise. No visible change.
