### PR TITLE
fix(react-card): use resolved slot instead of raw prop object

### LINKED ISSUE #28448: [Bug]: CardHeader header slot with children and props are broken in latest Fluent UI version
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/crazy-tesla-m23yyw?file=/example.tsx

## Actual Behavior
When passing an object with `className` and `children` to the `header` slot in a `CardHeader`, React throws an error.

```tsx
// style the floating action container
<CardHeader
  header={{
    className: styles.header,
    children: <Text />
  }}
>
```

## Expected Behavior
Using an object prop with `children` and other properties like `className` used to allow us to style the container while inserting a custom child. The [Microsoft Loop](https://loop.microsoft.com) logged-in homepage has some examples of this working.

We previously used 9.20.0 and noticed this issue when trying to upgrade to 9.24.0. It may have been introduced in a version between those two, however.

### Logs

_No response_

### Requested priority

Blocking

### Products/sites affected

Microsoft Loop

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by marcosmoura**
This PR fixes an issue with card trying to resolve the header prop before calling `resolveShorthand`. For more information, please refer to the [original bug](https://github.com/microsoft/fluentui/issues/28448#issuecomment-1624167331).

- Fixes #28448

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                |    Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                 Change |
| :----------------------------------------------------------------------------------------------- | --------------------------: | --------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>   | `89.33 kB`<br />`25.271 kB` | `89.36 kB`<br />`25.284 kB` | `30 B` <br />`13 B`  |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr> | `11.622 kB`<br />`4.729 kB` | `11.652 kB`<br />`4.741 kB` | `30 B` <br />`12 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          | `83.778 kB`<br />`23.685 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `9.24 kB`<br />`3.907 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |  `10.048 kB`<br />`4.254 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `65.175 kB`<br />`17.915 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `210.68 kB`<br />`58.781 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `36.409 kB`<br />`12.003 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `6.473 kB`<br />`2.196 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/57de08c18915440cdc54a1242bbdf948e2b0f562'>57de08c18915440cdc54a1242bbdf948e2b0f562</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

File: packages/react-components/react-card/src/components/CardHeader/useCardHeader.ts [hunk 1]
```diff
@@ -62,14 +62,22 @@ export const useCardHeader_unstable = (props: CardHeaderProps, ref: React.Ref<HT
...
   React.useEffect(() => {
     const headerId = !hasChildId.current ? headerRef.current?.id : undefined;
-    const childWithId = getChildWithId(header);
+    const childWithId = getChildWithId(headerSlot?.children);
 
     hasChildId.current = Boolean(childWithId);
 
     setReferenceId(getReferenceId(headerId, childWithId, generatedId));
-  }, [generatedId, header, setReferenceId]);
+  }, [generatedId, header, headerSlot, setReferenceId]);
```
Comment (behowell) [inline packages/react-components/react-card/src/components/CardHeader/useCardHeader.ts:80]: `headerSlot` will be a new object on every render, so using it as a dependency on the effect will cause the effect to run every render.

One thing that should be stable between renders is `childWithId?.props.id`. I don't think(?) you need to wait for the effect to run in order to get that value. You could do something like:

```ts
  const headerSlot = resolveShorthand(header, {
    required: true,
    defaultProps: {
      ref: headerRef,
      id: !hasChildId.current ? referenceId : undefined,
    },
  });

  const headerChildId = getChildWithId(headerSlot?.children)?.props.id;
  hasChildId.current = Boolean(headerChildId);

  React.useEffect(() => {
    const headerId = !hasChildId.current ? headerRef.current?.id : undefined;
    setReferenceId(getReferenceId(headerId, headerChildId, generatedId));
  }, [generatedId, headerChildId, setReferenceId]);
```

Comment (behowell) [reply packages/react-components/react-card/src/components/CardHeader/useCardHeader.ts:80]: And looking through it even further, I'm not sure the effect is necessary? `headerRef.current.id` should be the same as `headerSlot.id`. So this all boils down to: (a) set a generated ID on headerSlot if it doesn't have one, and (b) call setReferenceId with either the child's ID if available, or the header's ID if not.

```ts
  // [delete headerRef, hasChildId, and generatedId]

  const headerSlot = resolveShorthand(header, {
    required: true,
    defaultProps: {
      id: useId(cardHeaderClassNames.header),
    },
  });

  const headerChildId = getChildWithId(headerSlot?.children)?.props.id;

  setReferenceId(headerChildId || headerSlot.id);
```

**Review by behowell — APPROVED** [review]
Added a comment about how to simplify this logic. It's probably better to merge this PR as it is now, and address my comment in a future PR, so as not to delay this bugfix.

**Review by ValentinaKozlova — APPROVED** [review]

File: packages/react-components/react-card/src/components/CardHeader/useCardHeader.ts (hunk 1 above)
Comment (marcosmoura) [reply packages/react-components/react-card/src/components/CardHeader/useCardHeader.ts:80]: That makes sense. I'll look at a way to improve it by refactoring this component.
