### PR TITLE
fix: Picker infinite loop on itemLimit=0 (#25550)

### LINKED ISSUE #25550: [Bug]: PeoplePicker itemLimit=0 can cause an infinite loop
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 9.04 GB / 31.68 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.35)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/RoelVB/pen/LYrbYoK

## Actual Behavior
When the PeoplePicker `itemLimit` is set to 0 and the last item is deleted the page crashes because of an infinite loop.
Seems like the picker keeps trying to reset it's focus, but it can't.

See [this codepen](https://codepen.io/RoelVB/pen/LYrbYoK), it's a copy of the "controlled" example from the docs, but with the `itemLimit` set.

## Expected Behavior
We want to fill the picker controlled, but users should be able to delete people.
Before v8 this worked fine.

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by RoelVB**
## Current Behavior

When setting the `itemLimit` on a picker to 0 and erasing all the items will cause an infinite loop.

## New Behavior

When setting a `itemLimit` of 0 on the picker will not cause an infinite loop.

> I was unable to create a test for this. Even before my change I couldn't get a test to fail on this.

## Related Issue(s)

Fixes #25550

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/169e9b94b0cf741102596f106ed726d9402145cc'>169e9b94b0cf741102596f106ed726d9402145cc</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -413,7 +413,7 @@ export class BasePicker<T, P extends IBasePickerProps<T>>
       if (newEl) {
         newEl.focus();
       }
-    } else if (!this.canAddItems()) {
+    } else if (items.length && !this.canAddItems()) {
```
Comment (smhigley) [inline packages/react/src/components/pickers/BasePicker.tsx:416]: There's another in `onWrapperClick` that could use this check added too, on line 602

**Review by smhigley — COMMENTED** [review]
Thanks so much for making this fix! I just had the one suggestion for the other place `resetFocus` is called (aside from `componentDidUpdate`, which will already not run if items.length === 0).

Additionally, you'll need to run `yarn change` from the repository's root to generate a change file, and when prompted add text like "fix: prevent infinite loop when Picker has itemLimit=0"

**Comment by RoelVB** [comment]
@smhigley 
Thanks. I've added the change file and the check in `onWrapperClick`

**Review by smhigley — APPROVED** [review]

**Comment by smhigley** [comment]
@RoelVB merged, thanks again for the fix! 😊
