### PR TITLE
fix(Menu): Focus on first menu item on click

### LINKED ISSUE #20047: Focus sometimes not going into Menu upon opening with virtual cursor
### Description

When the Menu is opened using the screen reader from the virtual cursor mode, the focus sometimes does not move into the menu, and therefore the screen reader does not switch to the forms mode automatically.

### Repro steps

1. Turn on the screen reader (either JAWS or NVDA).
2. Ensure the screen reader is in the virtual cursor mode (by pressing JAWSkey + Z in case of JAWS or NVDA + spacebar in case of NVDA).
3. Using the Down arrow, navigate to the button for opening the Menu and activate it with spacebar.
4. Use the Down arrow key to navigate the Menu.

#### Actual behavior

Sometimes, the keyboard focus does not get into the Menu and the screen reader does not get switched to the forms mode automatically and stays in the virtual cursor mode instead.

#### Expected behavior

The keyboard focus should always move into the Menu upon opening and the screen reader should always get switched to the forms mode afterwards, so that the Menu items could be navigated in cycle, and that the "X of Y" is announced when navigated from one Menu item to another using the Down or Up arrow keys.

### PR DESCRIPTION
**Pull request by ling1726**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #20047
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Reverts a part of #18618 where the first menu item was not focused on click, but was done for `Enter`

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/91c9bbd9f3f78912671c1a431bf6020a6485e693'>91c9bbd9f3f78912671c1a431bf6020a6485e693</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-menu/src/components/MenuTrigger/useTriggerElement.ts [hunk 1]
```diff
@@ -81,10 +81,6 @@ export const useTriggerElement = (state: MenuTriggerState): MenuTriggerState =>
       focusFirst();
     }
 
-    if (open && key === ArrowDown && !isSubmenu) {
```
Comment (ling1726) [inline packages/react-menu/src/components/MenuTrigger/useTriggerElement.ts:84]: Now this case should never happen, (menu is open and focus is still on the trigger)

File: packages/react-menu/src/components/Menu/useMenu.tsx [hunk 2]
```diff
@@ -213,13 +213,17 @@ const useMenuOpenState = (
   }, [findPrevFocusable, state.triggerRef]);
 
   React.useEffect(() => {
-    if (!shouldHandleKeyboardRef.current) {
-      return;
+    if (open) {
```
Comment (ling1726) [inline packages/react-menu/src/components/Menu/useMenu.tsx:216]: effect is the same as before #18618

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ContextualMenu-mount_base.html">8644</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ContextualMenu-mount.html">17150</a></td>
            <td>1000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ContextualMenu-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Avatar-mount_base.html">899</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Avatar-mount.html">929</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/BaseButton-mount_base.html">942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/BaseButton-mount.html">942</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Breadcrumb-mount_base.html">2692</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Breadcrumb-mount.html">2705</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ButtonNext-mount_base.html">531</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ButtonNext-mount.html">543</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Checkbox-mount_base.html">1575</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Checkbox-mount.html">1580</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/CheckboxBase-mount_base.html">1338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/CheckboxBase-mount.html">1355</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ChoiceGroup-mount_base.html">4891</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ChoiceGroup-mount.html">4876</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ComboBox-mount_base.html">980</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ComboBox-mount.html">989</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/CommandBar-mount_base.html">10335</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/CommandBar-mount.html">10365</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ContextualMenu-mount_base.html">8644</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ContextualMenu-mount.html">17150</a></td>
            <td>1000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ContextualMenu-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DefaultButton-mount_base.html">1194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DefaultButton-mount.html">1169</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DetailsRow-mount_base.html">3890</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DetailsRow-mount.html">3927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DetailsRowFast-mount_base.html">3987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DetailsRowFast-mount.html">3893</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DetailsRowNoStyles-mount_base.html">3696</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DetailsRowNoStyles-mount.html">3716</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Dialog-mount_base.html">2616</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Dialog-mount.html">2615</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DocumentCardTitle-mount_base.html">184</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/DocumentCardTitle-mount.html">184</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Dropdown-mount_base.html">3317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Dropdown-mount.html">3239</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FluentProviderNext-mount_base.html">1815</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FluentProviderNext-mount.html">1767</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FluentProviderWithTheme-mount_base.html">153</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FluentProviderWithTheme-mount.html">158</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FluentProviderWithTheme-virtual-rerender.html">99</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">198</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">193</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FocusTrapZone-mount_base.html">1860</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FocusTrapZone-mount.html">1799</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FocusZone-mount_base.html">1855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/FocusZone-mount.html">1795</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/IconButton-mount_base.html">1769</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/IconButton-mount.html">1835</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Label-mount_base.html">383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Label-mount.html">378</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Layer-mount_base.html">3019</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Layer-mount.html">3038</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Link-mount_base.html">515</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Link-mount.html">504</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/MakeStyles-mount_base.html">1916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/MakeStyles-mount.html">1880</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/MenuButton-mount_base.html">1536</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/MenuButton-mount.html">1536</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/MessageBar-mount_base.html">2013</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/MessageBar-mount.html">2038</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Nav-mount_base.html">3351</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Nav-mount.html">3456</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/OverflowSet-mount_base.html">1155</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/OverflowSet-mount.html">1130</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Panel-mount_base.html">2531</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Panel-mount.html">2580</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Persona-mount_base.html">856</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Persona-mount.html">901</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Pivot-mount_base.html">1495</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Pivot-mount.html">1590</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/PrimaryButton-mount_base.html">1364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/PrimaryButton-mount.html">1311</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Rating-mount_base.html">7832</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Rating-mount.html">7840</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/SearchBox-mount_base.html">1363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/SearchBox-mount.html">1377</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Shimmer-mount_base.html">2662</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Shimmer-mount.html">2600</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Slider-mount_base.html">1989</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Slider-mount.html">1988</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/SpinButton-mount_base.html">5161</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/SpinButton-mount.html">5197</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Spinner-mount_base.html">481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Spinner-mount.html">457</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/SplitButton-mount_base.html">3486</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/SplitButton-mount.html">3279</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Stack-mount_base.html">525</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Stack-mount.html">538</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/StackWithIntrinsicChildren-mount_base.html">1750</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/StackWithIntrinsicChildren-mount.html">1828</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/StackWithTextChildren-mount_base.html">4710</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/StackWithTextChildren-mount.html">4696</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/SwatchColorPicker-mount_base.html">10698</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/SwatchColorPicker-mount.html">10691</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/TagPicker-mount_base.html">2833</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/TagPicker-mount.html">2681</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/TeachingBubble-mount_base.html">13287</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/TeachingBubble-mount.html">13338</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Text-mount_base.html">467</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Text-mount.html">450</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/TextField-mount_base.html">1481</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/TextField-mount.html">1478</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ThemeProvider-mount_base.html">1220</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ThemeProvider-mount.html">1232</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ThemeProvider-virtual-rerender_base.html">635</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ThemeProvider-virtual-rerender.html">646</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1930</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Toggle-mount_base.html">867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/Toggle-mount.html">846</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/buttonNative-mount_base.html">161</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test/buttonNative-mount.html">158</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AttachmentMinimalPerf.default | [173](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AttachmentMinimalPerf.default.html) | [157](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.1:1
BoxMinimalPerf.default | [381](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/BoxMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.09:1
StatusMinimalPerf.default | [722](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/StatusMinimalPerf.default.html) | [668](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.08:1
AnimationMinimalPerf.default | [442](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AnimationMinimalPerf.default.html) | [415](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.07:1
ButtonSlotsPerf.default | [569](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ButtonSlotsPerf.default.html) | [535](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.06:1
SkeletonMinimalPerf.default | [376](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/SkeletonMinimalPerf.default.html) | [354](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.06:1
AccordionMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AccordionMinimalPerf.default.html) | [150](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.04:1
ChatDuplicateMessagesPerf.default | [319](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [307](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.04:1
ChatWithPopoverPerf.default | [392](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ChatWithPopoverPerf.default.html) | [376](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.04:1
LabelMinimalPerf.default | [402](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/LabelMinimalPerf.default.html) | [387](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.04:1
ToolbarMinimalPerf.default | [965](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ToolbarMinimalPerf.default.html) | [929](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.04:1
EmbedMinimalPerf.default | [4259](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/EmbedMinimalPerf.default.html) | [4141](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.03:1
FlexMinimalPerf.default | [294](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/FlexMinimalPerf.default.html) | [285](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.03:1
InputMinimalPerf.default | [1318](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/InputMinimalPerf.default.html) | [1285](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.03:1
ItemLayoutMinimalPerf.default | [1199](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1168](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
AvatarMinimalPerf.default | [215](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AvatarMinimalPerf.default.html) | [210](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.02:1
ButtonMinimalPerf.default | [173](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ButtonMinimalPerf.default.html) | [170](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.02:1
CardMinimalPerf.default | [575](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/CardMinimalPerf.default.html) | [566](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.02:1
GridMinimalPerf.default | [346](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/GridMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.02:1
HeaderMinimalPerf.default | [368](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/HeaderMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.02:1
HeaderSlotsPerf.default | [775](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/HeaderSlotsPerf.default.html) | [759](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.02:1
ListWith60ListItems.default | [648](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ListWith60ListItems.default.html) | [636](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.02:1
MenuButtonMinimalPerf.default | [1674](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1634](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.02:1
PopupMinimalPerf.default | [628](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/PopupMinimalPerf.default.html) | [616](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.02:1
ProviderMergeThemesPerf.default | [1762](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1731](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.02:1
AlertMinimalPerf.default | [278](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AlertMinimalPerf.default.html) | [275](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.01:1
ChatMinimalPerf.default | [668](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ChatMinimalPerf.default.html) | [659](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.01:1
RefMinimalPerf.default | [235](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/RefMinimalPerf.default.html) | [232](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1917](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TableManyItemsPerf.default.html) | [1907](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TreeMinimalPerf.default | [797](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TreeMinimalPerf.default.html) | [793](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.01:1
AttachmentSlotsPerf.default | [1085](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1087](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1:1
ButtonOverridesMissPerf.default | [1713](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1714](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
CarouselMinimalPerf.default | [478](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/CarouselMinimalPerf.default.html) | [476](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1:1
DropdownManyItemsPerf.default | [697](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DropdownManyItemsPerf.default.html) | [696](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [3070](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DropdownMinimalPerf.default.html) | [3070](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
ImageMinimalPerf.default | [364](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ImageMinimalPerf.default.html) | [363](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1:1
LayoutMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/LayoutMinimalPerf.default.html) | [366](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1:1
ListCommonPerf.default | [640](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ListCommonPerf.default.html) | [641](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ListCommonPerf.default_base.html) | 1:1
ListMinimalPerf.default | [516](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ListMinimalPerf.default.html) | [518](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
LoaderMinimalPerf.default | [694](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/LoaderMinimalPerf.default.html) | [694](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1:1
MenuMinimalPerf.default | [852](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/MenuMinimalPerf.default.html) | [855](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [1126](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ProviderMinimalPerf.default.html) | [1124](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1685](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/SliderMinimalPerf.default.html) | [1689](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [4310](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4299](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
TableMinimalPerf.default | [406](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TableMinimalPerf.default.html) | [405](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TableMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [4066](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/CustomToolbarPrototype.default.html) | [4068](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
TooltipMinimalPerf.default | [1035](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TooltipMinimalPerf.default.html) | [1035](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2746](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2765](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 0.99:1
DatepickerMinimalPerf.default | [5495](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5566](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.99:1
DialogMinimalPerf.default | [764](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DialogMinimalPerf.default.html) | [773](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DialogMinimalPerf.default_base.html) | 0.99:1
ReactionMinimalPerf.default | [377](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ReactionMinimalPerf.default.html) | [382](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.99:1
TextMinimalPerf.default | [349](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TextMinimalPerf.default.html) | [352](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.99:1
VideoMinimalPerf.default | [634](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/VideoMinimalPerf.default.html) | [640](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.99:1
DividerMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DividerMinimalPerf.default.html) | [373](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.98:1
PortalMinimalPerf.default | [178](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/PortalMinimalPerf.default.html) | [182](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/PortalMinimalPerf.default_base.html) | 0.98:1
RadioGroupMinimalPerf.default | [446](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [455](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.98:1
TextAreaMinimalPerf.default | [485](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TextAreaMinimalPerf.default.html) | [497](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.98:1
ListNestedPerf.default | [544](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ListNestedPerf.default.html) | [561](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/ListNestedPerf.default_base.html) | 0.97:1
IconMinimalPerf.default | [621](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/IconMinimalPerf.default.html) | [639](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.97:1
RosterPerf.default | [1156](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/RosterPerf.default.html) | [1222](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/RosterPerf.default_base.html) | 0.95:1
TreeWith60ListItems.default | [178](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TreeWith60ListItems.default.html) | [188](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.95:1
FormMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/FormMinimalPerf.default.html) | [430](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.94:1
SegmentMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/SegmentMinimalPerf.default.html) | [376](https://fluentuipr.z22.web.core.windows.net/pull/20955/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.94:1

</details><div id="perfComment9423"/>

**Review by layershifter — APPROVED** [review]
