### PR TITLE
fix: Table header interactive styles

### LINKED ISSUE #25189: [Bug]: v9 Table with non-interactable headers has hover color
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Browsers:
  Firefox: 105.0.3

"@fluidui/react-components": "9.4.0"
```

### Are you reporting Accessibility issue?

_No response_

### Reproduction

https://codesandbox.io/s/049sq8?file=/example.tsx

## Actual Behavior
Header row changes color on hover.

## Expected Behavior
Header row does not change color on hover.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### LINKED ISSUE #25191: [Bug]: v9 Table should only highlight a single column header on hover
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Browsers:
  Firefox: 105.0.3

"@fluidui/react-components": "9.4.0"
```

### Are you reporting Accessibility issue?

_No response_

### Reproduction

https://codesandbox.io/s/6vwioo?file=/example.tsx

## Note
Repro link is currently broken. Its the `Sort Controlled` example here: https://react.fluentui.dev/?path=/docs/preview-components-table--default

## Actual Behavior
Entire header row highlights on hover.

## Expected Behavior
Only the header cell being hovered over should highlight.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ling1726**
Adds an additional context for the table header for children to know that they are the children of the header.

Using this context, the table row will no longer apply interactive styles when it's inside a table header.

Also updates the table header cell styles to use interactive styles only when they are sortable

Before: 
msedge_1NHaBrKBsP

After:
msedge_9DzDZFxf2I

Fixes #25189
Fixes #25191

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `62.827 kB`<br />`17.599 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.299 kB`<br />`52.51 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `33.446 kB`<br />`11.033 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4f46035db0cd28a5987932120c68755e024869c8'>4f46035db0cd28a5987932120c68755e024869c8</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/Avatar-mount_base.html">1317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/Avatar-mount.html">1319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/Button-mount_base.html">953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/Button-mount.html">959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/FluentProvider-mount_base.html">1581</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/FluentProvider-mount.html">1567</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/FluentProviderWithTheme-mount_base.html">636</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/FluentProviderWithTheme-mount.html">633</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">581</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">600</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">639</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/MakeStyles-mount_base.html">1912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/MakeStyles-mount.html">1895</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/SpinButton-mount_base.html">2514</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25201/perf-test-react-components/SpinButton-mount.html">2591</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by bsunderhus — APPROVED** [review]

File: packages/react-components/react-table/src/contexts/tableHeaderContext.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import * as React from 'react';
+
+const tableHeaderContext = React.createContext<string | undefined>(undefined);
+
+const tableHeaderContextDefaultValue = '';
+
+export const TableHeaderContextProvider = tableHeaderContext.Provider;
+export const useIsInTableHeader = () => React.useContext(tableHeaderContext) === tableHeaderContextDefaultValue;
```
Comment (spmonahan) [inline packages/react-components/react-table/src/contexts/tableHeaderContext.ts:8]: Is the provider part of the public API for `Table`?

It feels a little odd for an empty string to mean "this row is in the header", particularly where the value is set on the provider.

Comment (ling1726) [reply packages/react-components/react-table/src/contexts/tableHeaderContext.ts:8]: It could also be a boolean I guess, the value itself isn't that important but rather it should be an indicator that it is inside the header

Comment (spmonahan) [reply packages/react-components/react-table/src/contexts/tableHeaderContext.ts:8]: Is it something we will expose to users or will it only ever be set internally by the component?

After thinking about it some more, if it's only internal I'm not really concerned about this.
