### PR TITLE
fix: v9 Dropdown in Safari gets focus when clicked

### LINKED ISSUE #29576: [Bug]: Two or more dropdown are showed at the same time
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 305.71 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
Browsers:
    Chrome: 118.0.5993.70
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://zw4h7h.csb.app/

[edit -behowell] Also repros on the documentation site: https://react.fluentui.dev/?path=/docs/components-dropdown--default#appearance

## Actual Behavior
[iPhone] Two and more filter dropdowns can be opened

## Expected Behavior
The other opened dropdown is closed when another dropdown is opened

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by smhigley**
## Previous Behavior

Safari has a longstanding behavior where it does not focus links and buttons when they are clicked. For Dropdown, this means that keyboard navigation doesn't work after opening them with a mouse, and that they don't close when clicking outside of the dropdown (since there is no blur event).

## New Behavior

The button has an explicit tabindex, which allows it to get focus when clicked in Safari

## Related Issue(s)

- Fixes #29576

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/Avatar-mount_base.html">645</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/Avatar-mount.html">618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/Button-mount_base.html">305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/Button-mount.html">304</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/Field-mount_base.html">1120</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/Field-mount.html">1121</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/FluentProvider-mount_base.html">711</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/FluentProvider-mount.html">700</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/FluentProviderWithTheme-mount_base.html">71</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/FluentProviderWithTheme-mount.html">80</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">60</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">56</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">75</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">72</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/MakeStyles-mount_base.html">838</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/MakeStyles-mount.html">837</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/Persona-mount_base.html">1758</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/Persona-mount.html">1679</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/SpinButton-mount_base.html">1394</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/29855/perf-test-react-components/SpinButton-mount.html">1391</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                             |     Baseline (minified/GZIP) |                         PR |                                                                                                                                                                                                  Change |
| :---------------------------------------------------------------------------------------------------------------------------- | ---------------------------: | -------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr> | `90.776 kB`<br />`29.779 kB` | `90.9 kB`<br />`29.806 kB` | `124 B` <br />`27 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                                                 |  `92.366 kB`<br />`30.119 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `70.184 kB`<br />`20.225 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `208.155 kB`<br />`59.527 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `42.468 kB`<br />`14.059 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.822 kB`<br />`2.311 kB` |
| <samp>react-timepicker-compat-preview</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr>                                                         |  `93.764 kB`<br />`31.408 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/5103727605543cf631cd50f5348562b763f08ee0'>5103727605543cf631cd50f5348562b763f08ee0</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

File: packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx [hunk 1]
```diff
@@ -104,6 +104,7 @@ export const useDropdown_unstable = (props: DropdownProps, ref: React.Ref<HTMLBu
   triggerSlot = slot.always(props.button, {
     defaultProps: {
       type: 'button',
+      tabIndex: 0,
```
Comment (behowell) [inline packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx:107]: nit: Maybe add a comment why this is needed, with a link to the issue.

**Review by behowell — COMMENTED** [review]
Looks good! Maybe update the description with details about the new tabindex fix, in case someone refers back to this PR when wondering why it has tabindex="0" on a button.

**Review by behowell — APPROVED** [review]

File: change/@fluentui-react-combobox-33ead5c4-7eb4-47ca-bc9f-49ba7aaa8db7.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
+  "comment": "fix: Dropdown button gets focus in Safari when clicked",
```
Comment (behowell) [inline change/@fluentui-react-combobox-33ead5c4-7eb4-47ca-bc9f-49ba7aaa8db7.json:3]: Also update this description.

File: packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx (hunk 1 above)
Comment (smhigley) [reply packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx]: added a comment! There's no issue to link to, since this is Safari's explicit interaction decision, and they don't consider it a bug :/
