### PR TITLE
fix: Making the hidden input on Checkbox and Switch only cover the indicator and not also the label

### LINKED ISSUE #24330: [Bug] react-checkbox: interactive items within the label are unreachable with a pointer
Since the `<input>` element within the checkbox is styled to cover the entire width and height of the control (including the label text), links and other potential interactive items within the label cannot be activated with a pointer.

It looks like the solution would be to style the checkbox input to cover only the visual checkbox indicator, so the label and any nested links/etc. function normally.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

The hidden input in the `Checkbox` and `Switch` components covers both the indicator and the label, making any interactive elements within the label, like links, impossible to be clicked.

### Indicator
image

image

### Label

image

image

## New Behavior

The hidden input in the `Checkbox` and `Switch` components now covers only the indicator and its surrounding space, not the label. This makes any interactive elements within the label, like links, possible to be clicked. We verified that clicking on the label still toggles the state of the component. We also expanded the size of the label so it covers the empty space around it that was previously being covered by the hidden input.

We verified that hover and pressed styling still works as expected and we have added visual regression tests that check for RTL to work correctly as well.

### Indicator

image

image

### Label

image

image

## Related Issue(s)

Fixes #24330

### CODE REVIEW

**Review by behowell — CHANGES_REQUESTED** [review]
This change will also make it so the padding around the control, and the gap between the control and the label are dead zones, which breaks the spec, and is bad for usability.

Interactive content should probably be outside the label? But if it's necessary to do it this way, then we should consider refactoring Checkbox/Switch/Radio so that the `<label>` is the root element, wrapping the indicator and label text.

We should make sure that Radio also works the same way as Checkbox and Switch.

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                          |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                   Change |
| :----------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr> | `32.562 kB`<br />`10.253 kB` | `32.688 kB`<br />`10.242 kB` | `126 B` <br />`-11 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.816 kB`<br />`51.903 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `33.259 kB`<br />`10.952 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/130d5848fa9639db3c7eafcd6845b3e1ee91b1f6'>130d5848fa9639db3c7eafcd6845b3e1ee91b1f6</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/Avatar-mount_base.html">1718</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/Avatar-mount.html">1718</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/Button-mount_base.html">1234</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/Button-mount.html">1244</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/FluentProvider-mount_base.html">1958</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/FluentProvider-mount.html">1978</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/FluentProviderWithTheme-mount_base.html">713</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/FluentProviderWithTheme-mount.html">709</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">677</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">682</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">756</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">783</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/MakeStyles-mount_base.html">2294</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/MakeStyles-mount.html">2390</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/SpinButton-mount_base.html">3431</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24638/perf-test-react-components/SpinButton-mount.html">3252</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by smhigley — APPROVED** [review]
I can't tell what the difference is in the screener

**Comment by smhigley** [comment]
re: @behowell's comment on dead zones -- I agree it'd be better if there weren't, though it doesn't concern me all that much, since the indicator itself combined with the label text itself should end up being a pretty big hit target.

A wrapping label would be nice though :). I forget if there was a reason for not doing that originally for checkbox/switch.

File: packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts [hunk 1]
```diff
@@ -143,6 +141,23 @@ const useInputStyles = makeStyles({
       },
     },
   },
+
+  before: {
+    right: 0,
+  },
+  after: {
+    left: 0,
+  },
```
Comment (behowell) [inline packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts:150]: Could you double check that this still works correctly in RTL? It might be worthwhile to add some RTL variants for some Checkbox screener tests.

File: packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts [hunk 2]
```diff
@@ -193,15 +212,16 @@ const useLabelStyles = makeStyles({
...
-    marginBottom: `calc((${indicatorSizeMedium} - ${tokens.lineHeightBase300}) / 2)`,
+    marginTop: `calc(-1 * ${tokens.spacingVerticalS} + (${indicatorSizeMedium} - ${tokens.lineHeightBase300}) / 2)`,
+    marginBottom: `calc(-1 * ${tokens.spacingVerticalS} + (${indicatorSizeMedium} - ${tokens.lineHeightBase300}) / 2)`,
   },
   large: {
-    marginTop: `calc((${indicatorSizeLarge} - ${tokens.lineHeightBase300}) / 2)`,
-    marginBottom: `calc((${indicatorSizeLarge} - ${tokens.lineHeightBase300}) / 2)`,
+    marginTop: `calc(-1 * ${tokens.spacingVerticalS} + (${indicatorSizeLarge} - ${tokens.lineHeightBase300}) / 2)`,
+    marginBottom: `calc(-1 * ${tokens.spacingVerticalS} + (${indicatorSizeLarge} - ${tokens.lineHeightBase300}) / 2)`,
   },
```
Comment (behowell) [inline packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts:225]: IMO it would be better to remove the padding from root and put it on the individual slots instead of adding padding to both the label AND the root, then adding a negative margin to overlap it.

File: packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts [hunk 3]
```diff
@@ -26,15 +26,13 @@ const useRootStyles = makeStyles({
...
+    cursor: 'pointer',
+    height: '100%',
     ...shorthands.margin(0),
     opacity: 0,
-    cursor: 'pointer',
+    position: 'absolute',
+    top: 0,
 
     // When unchecked, hide the the checkmark icon (child of the indicator slot)
     [`:not(:checked):not(:indeterminate) ~ .${checkboxClassNames.indicator} > *`]: {
```
Comment (behowell) [inline packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts:38]: Followed up offline, but to recap: I don't think the hover/focus/etc. styles below will work anymore when hovering over the label, after this change. I can't think of a simple solution; the best I can think of is adding some additional CSS variables like "hoverLabelColor", which gets set by the input based on its enabled/checked/indeterminate state. Then the label would have a hover selector that sets that color.

(A little background on why the styles are factored like this: It's not necessarily possible to track the checked state for the radio button in javascript, which is one of the reasons this uses css selectors for those states instead of tracking the state in code. The disabled state is also possibly inherited from a parent group/form, so tracking that in code is also not simple.)

File: packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts (hunk 1 above)
Comment (khmakoto) [reply packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts:149]: I've added some RTL VR tests to verify this.

File: packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts (hunk 2 above)
Comment (khmakoto) [reply packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts]: Agreed and done!

File: packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts (hunk 3 above)
Comment (khmakoto) [reply packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts:37]: I double-checked and this is apparently still working. My guess is that the browser treats hovering/pressing over the label that's attached to an input element the same way as it treats hovering/pressing over the input element itself.

File: packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts [hunk 4]
```diff
@@ -143,6 +140,22 @@ const useInputStyles = makeStyles({
...
+  },
+
+  // Calculate the width of the hidden input by taking into account the size of the indicator + the padding around it.
+  // This is done so that clicking on that "empty space" still toggles the checkbox.
+  medium: {
+    width: `calc(${indicatorSizeMedium} + ${tokens.spacingHorizontalS})`,
+  },
+  large: {
+    width: `calc(${indicatorSizeLarge} + ${tokens.spacingHorizontalS})`,
+  },
```
Comment (behowell) [inline packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts:158]: I think you can get rid of `spacingHorizontalS` now that the label is using padding instead of margin for the gap, right?
```suggestion
  medium: {
    width: indicatorSizeMedium,
  },
  large: {
    width: indicatorSizeLarge,
  },
```

File: packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts [hunk 5]
```diff
@@ -69,19 +68,30 @@ const useIndicatorStyles = makeStyles({
...
-    left: 0,
     ...shorthands.margin(0),
     opacity: 0,
     position: 'absolute',
-    top: 0,
-    width: '100%',
+
+    // Calculate the width of the hidden input by taking into account the size of the indicator + the padding around it.
+    // This is done so that clicking on that "empty space" still toggles the switch.
+    width: `calc(${trackWidth}px + ${tokens.spacingHorizontalS})`,
```
Comment (behowell) [inline packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts:94]: I haven't read the switch styles in as much detail, but similar to my comment here in checkbox, does this still need `spacingHorizontalS` included in it?
```suggestion
    width: `${trackWidth}px`,
```

File: packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts [hunk 6]
```diff
@@ -184,17 +194,42 @@ const useInputStyles = makeStyles({
...
+    right: 0,
+    top: 0,
+  },
+  after: {
+    left: 0,
+    top: 0,
+  },
+  above: {
+    bottom: 0,
+    height: `calc(${trackHeight}px + ${tokens.spacingVerticalS})`,
```
Comment (behowell) [inline packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts:208]: Ditto here too
```suggestion
    height: `${trackHeight}px`,
```

**Review by behowell — COMMENTED** [review]
Looks good, thanks for making all of these changes to address my feedback!

**Review by behowell — APPROVED** [review]

File: packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts (hunk 4 above)
Comment (khmakoto) [reply packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts:158]: No, that spacing is to account for the space on the left of the `indicator` (right if `labelPosition` is `before`). You can see that another `tokens.spacingHorizontalM` has been removed already that referred to the gap between the `indicator` and the `label`.

File: packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts (hunk 5 above)
Comment (khmakoto) [reply packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts:94]: Yup, similar reason to the one above.

File: packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts (hunk 6 above)
Comment (khmakoto) [reply packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts:208]: Ditto.

**Comment by khmakoto** [comment]
@microsoft-github-policy-service agree company="Microsoft"
