### PR TITLE
(7.0) ComboBox: fix multi-select checkbox role; improve docs and examples

### LINKED ISSUE #15223: ComboBox multi-select has invalid/missing aria attributes
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/khali007/pen/yLYvOVR

###Prerequisites:
Add [accessibility insights extension for web](https://accessibilityinsights.io/docs/en/web/overview/).
#### Actual behavior:
When automated checks are executed for errors with accessibility insights for web extension, errors are reported as demonstrated below.

image

image

#### Expected behavior:

How to fix 
ARIA attribute is not allowed: aria-selected="true"
No error should be reported in accessibility insights for web.

### LINKED ISSUE #15224: ComboBox multi-select has no children with role="option"
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/khali007/pen/yLYvOVR

###Prerequisites:
Add [Accessibility insights extension for web](https://accessibilityinsights.io/docs/en/web/overview/) .

#### Actual behavior:
When automated checks are executed for errors with accessibility insights for web extension, errors are reported as demonstrated below
image
image

#### Expected behavior:
Fix the following:
Required ARIA child role not present: option
No error should be reported in accessibility insights for web.

### PR DESCRIPTION
**Pull request by ecraig12345**
#### Pull request checklist

- [x] Addresses an existing issue: Related to #16307, fixes #15223, fixes #15224
- [x] Include a change request file using `$ yarn change`

#### Description of changes

ComboBox tries to pass `role="option"` and some `data-*` props as top-level props to an option Checkbox in multi-select mode. As documented in #16307, Checkbox currently doesn't apply most native props, so these props aren't applied. This is definitely a problem (Accessibility Insights flags it) but probably got missed since none of the ComboBox examples on the website used multi-select.

Related changes:
- Fix a minor version of this issue in Dropdown, where `data-*` props are passed as top-level props to the Checkbox (the more significant issue with the role had already been fixed)
- Add multi-select ComboBox examples on the website, and fix the controlled examples to actually work with freeform mode
- Add snapshot tests for ComboBox and Dropdown's open states

(master version: #16331)

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">7.0 Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/BaseButton-mount_base.html">952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/BaseButton-mount.html">981</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Breadcrumb-mount_base.html">41959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Breadcrumb-mount.html">42776</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Checkbox-mount_base.html">1686</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Checkbox-mount.html">1678</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/CheckboxBase-mount_base.html">1386</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/CheckboxBase-mount.html">1361</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/ChoiceGroup-mount_base.html">5218</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/ChoiceGroup-mount.html">5250</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/ComboBox-mount_base.html">933</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/ComboBox-mount.html">950</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/CommandBar-mount_base.html">7858</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/CommandBar-mount.html">7760</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/ContextualMenu-mount_base.html">13488</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/ContextualMenu-mount.html">13617</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DefaultButton-mount_base.html">1216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DefaultButton-mount.html">1228</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DetailsRow-mount_base.html">3799</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DetailsRow-mount.html">3741</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DetailsRowFast-mount_base.html">3832</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DetailsRowFast-mount.html">3759</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DetailsRowNoStyles-mount_base.html">3559</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DetailsRowNoStyles-mount.html">3541</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Dialog-mount_base.html">1553</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Dialog-mount.html">1548</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DocumentCardTitle-mount_base.html">1833</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/DocumentCardTitle-mount.html">1820</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Dropdown-mount_base.html">2641</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Dropdown-mount.html">2655</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/FocusTrapZone-mount_base.html">1725</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/FocusTrapZone-mount.html">1774</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/FocusZone-mount_base.html">1870</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/FocusZone-mount.html">1816</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/IconButton-mount_base.html">1849</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/IconButton-mount.html">1867</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Label-mount_base.html">348</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Label-mount.html">343</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Layer-mount_base.html">1993</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Layer-mount.html">2035</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Link-mount_base.html">458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Link-mount.html">463</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/MenuButton-mount_base.html">1567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/MenuButton-mount.html">1564</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/MessageBar-mount_base.html">2088</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/MessageBar-mount.html">2093</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Nav-mount_base.html">3409</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Nav-mount.html">3394</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/OverflowSet-mount_base.html">1467</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/OverflowSet-mount.html">1477</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Panel-mount_base.html">1503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Panel-mount.html">1463</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Persona-mount_base.html">830</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Persona-mount.html">859</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Pivot-mount_base.html">1494</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Pivot-mount.html">1481</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/PrimaryButton-mount_base.html">1317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/PrimaryButton-mount.html">1348</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Rating-mount_base.html">8129</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Rating-mount.html">8042</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/SearchBox-mount_base.html">1369</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/SearchBox-mount.html">1366</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Shimmer-mount_base.html">2680</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Shimmer-mount.html">2726</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Slider-mount_base.html">1567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Slider-mount.html">1574</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/SpinButton-mount_base.html">5252</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/SpinButton-mount.html">5532</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Spinner-mount_base.html">447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Spinner-mount.html">428</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/SplitButton-mount_base.html">3361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/SplitButton-mount.html">3250</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Stack-mount_base.html">533</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Stack-mount.html">540</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/StackWithIntrinsicChildren-mount.html">1616</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/StackWithTextChildren-mount_base.html">4899</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/StackWithTextChildren-mount.html">4962</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/SwatchColorPicker-mount_base.html">10637</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/SwatchColorPicker-mount.html">10707</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/TagPicker-mount_base.html">2858</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/TagPicker-mount.html">2893</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/TeachingBubble-mount_base.html">50847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/TeachingBubble-mount.html">50853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Text-mount_base.html">437</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Text-mount.html">447</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/TextField-mount_base.html">1478</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/TextField-mount.html">1494</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Toggle-mount_base.html">876</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/Toggle-mount.html">882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/button-mount_base.html">107</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pr-deploy-site/refs/pull/16329/merge/perf-test/button-mount.html">114</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by joschect — APPROVED** [review]

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -1407,8 +1407,8 @@ export class ComboBox extends React.Component<IComboBoxProps, IComboBoxState> {
           onMouseLeave={this._onOptionMouseLeave}
           role="option"
           // aria-selected should only be applied to checked items, not hovered items
-          aria-selected={isSelected ? 'true' : 'false'}
-          ariaLabel={item.ariaLabel}
+          aria-selected={isChecked ? 'true' : 'false'}
+          ariaLabel={this._getPreviewText(item)}
```
Comment (smhigley) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx:1411]: In this one case, I'd suggest leaving this as `ariaLabel={item.ariaLabel}`, since defining it as `item._getPreviewText` means the aria-label will always be set, even if an author hasn't defined `item.ariaLabel`. That actually caused an a11y bug in v8 (fixed now) when a team had different option text in the dropdown than the text used in the input value.

**Review by smhigley — COMMENTED** [review]
Just one change, otherwise it looks good!

**Comment by ecraig12345** [comment]
@smhigley Finally updated this--would you mind taking another look at the core ComboBox and Dropdown changes and ensuring they look correct?

**Review by smhigley — APPROVED** [review]
LGTM!
