### PR TITLE
Apply aria attributes on proper element for Datepicker, Dropdown, Input

### LINKED ISSUE #16093: Form.Dropdown & Form.Datepicker don't apply aria-invalid to correct element
Repro steps:
1. Use example
https://fluentsite.z22.web.core.windows.net/0.51.3/components/form/definition#variants-components
2. Edit example like (each form component has errorMessage prop):
```
<Form>
    <Form.Input label="First name" name="firstName" errorMessage="You can not fix this error" required />
    <Form.Dropdown label="City"  errorMessage="You can not fix this error"items={['prague', 'new york']} />
    <Form.RadioGroup label="Pizza" errorMessage="You can not fix this error" vertical defaultCheckedValue="prosciutto" items={items} />
    <Form.Slider errorMessage="You can not fix this error" label="Bid the price" />
    <Form.Checkbox errorMessage="You can not fix this error" label="I agree to the Terms and Conditions" />
    <Form.Datepicker errorMessage="You can not fix this error" label="Select a date" />
    <Form.Button content="Submit" />
  </Form>
```
3. Use screen reader to navigate through the form components 
4. Observe narration

Actual: Dropdown and Datapicker component is missing narration "invalid entry" as it is missing the "aria-invalid" attribute 
Expected: each component has "aria-invalid" attribute

image

**Comment:**
When I was looking into it a bit I figured out that acc attributes are applied on wrong html element. They are applied on the dropdown "control" slot but in this case it would be applied on the button in dropdown. And similar case for calendar. 
image

### PR DESCRIPTION
**Pull request by kolaps33**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #16093

#### Description of changes

Changes are related to 4 issues:
1. #16093 aria-invalid was not propagated on the proper element
2. Form.Datepicker was missing aria-labelledby on the input element (please see screenshot below)
3. For Form.Input, Form.Datepicker, Form.Dropdown was applying aria props as well to incorrect element, on the form "control" slot (please see screenshot below)
4. when "aria-labelledby" or "aria-invalid" was used on dropdown or datapicker component (not related to the form error message), then these aria attribute was applied on the root of the component. 
More expected behavior would be apply these attributes on the input(for Datepicker) and buton(for Dropdown)

image

#### Focus areas to test
1.Form.Input, Form.Datepicker, Form.Dropdown
test that aria-invalid, aria-labelledby 
- are applied on the proper element
- are not applied on the other element (before it was the control slot)

2. add  "aria-invalid" and "aria-labelledby" for Dropdown and Datepicker component 
- verify these attributes are applied on the input(for Datepicker) and buton(for Dropdown)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx [hunk 1]
```diff
@@ -107,6 +113,13 @@ export type DatepickerStylesProps = Pick<DatepickerProps, 'allowManualInput'>;
 
 export const datepickerClassName = 'ui-datepicker';
 
+export type accProps = {
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx:116]: nit: better name ? `accProps` seems a bit mystic for those who might not be familiar with the codebase

File: packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts [hunk 2]
```diff
@@ -18,4 +26,7 @@ export const datepickerBehavior: Accessibility<DatepickerBehaviorProps> = props
   },
 });
 
-export type DatepickerBehaviorProps = never;
+export type DatepickerBehaviorProps = {
+  'aria-labelledby'?: string;
+  'aria-invalid'?: boolean | 'true' | 'false';
```
Comment (ling1726) [inline packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts:31]: Why do we need to support the string values ?

File: packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx (hunk 1 above)
Comment (ling1726) [reply packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx:116]: a11yProps/ariaProps would be more relevant IMO

File: packages/fluentui/react-northstar/src/utils/htmlPropsUtils.tsx [hunk 3]
```diff
@@ -156,10 +156,13 @@ export const htmlInputEvents: HtmlInputEvents[] = [
 ];
 
 export const htmlInputProps: HtmlInputProps[] = [...htmlInputAttrs, ...htmlInputEvents];
+export interface htmlCustomProps {
+  [index: number]: string;
+}
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/utils/htmlPropsUtils.tsx:161]: What is this for ?

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Avatar-mount_base.html">830</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Avatar-mount.html">835</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/BaseButtonCompat-mount_base.html">924</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/BaseButtonCompat-mount.html">936</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Breadcrumb-mount_base.html">40927</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Breadcrumb-mount.html">40432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Checkbox-mount_base.html">1514</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Checkbox-mount.html">1549</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/CheckboxBase-mount_base.html">1277</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/CheckboxBase-mount.html">1293</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ChoiceGroup-mount_base.html">4791</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ChoiceGroup-mount.html">4817</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ComboBox-mount_base.html">951</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ComboBox-mount.html">951</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/CommandBar-mount_base.html">9811</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/CommandBar-mount.html">9741</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ContextualMenu-mount_base.html">5921</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ContextualMenu-mount.html">5873</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DefaultButtonCompat-mount_base.html">1131</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DefaultButtonCompat-mount.html">1127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DetailsRow-mount_base.html">3607</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DetailsRow-mount.html">3630</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DetailsRowFast-mount_base.html">3619</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DetailsRowFast-mount.html">3642</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DetailsRowNoStyles-mount_base.html">3475</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DetailsRowNoStyles-mount.html">3457</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Dialog-mount_base.html">1459</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Dialog-mount.html">1486</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DocumentCardTitle-mount_base.html">1773</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/DocumentCardTitle-mount.html">1748</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Dropdown-mount_base.html">3330</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Dropdown-mount.html">3325</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/FocusTrapZone-mount_base.html">1757</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/FocusTrapZone-mount.html">1804</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/FocusZone-mount_base.html">1749</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/FocusZone-mount.html">1848</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/IconButtonCompat-mount_base.html">1795</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/IconButtonCompat-mount.html">1785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Label-mount_base.html">329</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Label-mount.html">327</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Layer-mount_base.html">1745</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Layer-mount.html">1768</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Link-mount_base.html">473</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Link-mount.html">473</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/MakeStyles-mount_base.html">1892</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/MakeStyles-mount.html">1923</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/MenuButtonCompat-mount_base.html">1497</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/MenuButtonCompat-mount.html">1471</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/MessageBar-mount_base.html">1921</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/MessageBar-mount.html">1968</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Nav-mount_base.html">3260</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Nav-mount.html">3273</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/OverflowSet-mount_base.html">1028</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/OverflowSet-mount.html">1013</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Panel-mount_base.html">1387</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Panel-mount.html">1422</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Persona-mount_base.html">857</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Persona-mount.html">874</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Pivot-mount_base.html">1410</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Pivot-mount.html">1420</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/PrimaryButtonCompat-mount_base.html">1296</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/PrimaryButtonCompat-mount.html">1251</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Rating-mount_base.html">7657</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Rating-mount.html">7872</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/SearchBox-mount_base.html">1336</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/SearchBox-mount.html">1357</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Shimmer-mount_base.html">2602</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Shimmer-mount.html">2583</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Slider-mount_base.html">1900</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Slider-mount.html">1891</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/SpinButton-mount_base.html">4966</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/SpinButton-mount.html">4943</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Spinner-mount_base.html">414</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Spinner-mount.html">401</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/SplitButtonCompat-mount_base.html">3165</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/SplitButtonCompat-mount.html">3173</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Stack-mount_base.html">521</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Stack-mount.html">510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1530</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/StackWithIntrinsicChildren-mount.html">1531</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/StackWithTextChildren-mount_base.html">4629</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/StackWithTextChildren-mount.html">4658</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/SwatchColorPicker-mount_base.html">10214</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/SwatchColorPicker-mount.html">10061</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Tabs-mount_base.html">1393</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Tabs-mount.html">1398</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/TagPicker-mount_base.html">2829</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/TagPicker-mount.html">2851</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/TeachingBubble-mount_base.html">11364</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/TeachingBubble-mount.html">11358</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Text-mount_base.html">421</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Text-mount.html">428</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/TextField-mount_base.html">1400</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/TextField-mount.html">1393</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ThemeProvider-mount_base.html">2067</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ThemeProvider-mount.html">2177</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ThemeProvider-virtual-rerender_base.html">619</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/ThemeProvider-virtual-rerender.html">636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Toggle-mount_base.html">803</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/Toggle-mount.html">782</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/button-mount_base.html">671</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/button-mount.html">684</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/buttonNative-mount_base.html">97</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test/buttonNative-mount.html">97</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🎯 | Avatar.Fluent | [0.46](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Avatar.Fluent.html) | 0.5 | 0.92:1 | 2000 | 920
🦄 | Button.Fluent | [0.13](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Button.Fluent.html) | 0.2 | 0.65:1 | 5000 | 646
🔧 | Checkbox.Fluent | [0.64](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Checkbox.Fluent.html) | 0.34 | 1.88:1 | 1000 | 638
🎯 | Dialog.Fluent | [0.17](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Dialog.Fluent.html) | 0.22 | 0.77:1 | 5000 | 829
🔧 | Dropdown.Fluent | [2.9](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Dropdown.Fluent.html) | 0.4 | 7.25:1 | 1000 | 2904
🔧 | Icon.Fluent | [0.16](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Icon.Fluent.html) | 0.06 | 2.67:1 | 5000 | 789
🦄 | Image.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Image.Fluent.html) | 0.13 | 0.62:1 | 5000 | 408
🔧 | Slider.Fluent | [1.51](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Slider.Fluent.html) | 0.45 | 3.36:1 | 1000 | 1514
🔧 | Text.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.67:1 | 5000 | 395
🦄 | Tooltip.Fluent | [0.11](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Tooltip.Fluent.html) | 0.86 | 0.13:1 | 5000 | 572
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
PortalMinimalPerf.default | [169](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/PortalMinimalPerf.default.html) | [154](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.1:1
SkeletonMinimalPerf.default | [414](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/SkeletonMinimalPerf.default.html) | [385](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.08:1
IconMinimalPerf.default | [742](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/IconMinimalPerf.default.html) | [684](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.08:1
ChatWithPopoverPerf.default | [503](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ChatWithPopoverPerf.default.html) | [469](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.07:1
ListMinimalPerf.default | [537](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ListMinimalPerf.default.html) | [500](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.07:1
ButtonMinimalPerf.default | [202](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonMinimalPerf.default.html) | [190](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.06:1
GridMinimalPerf.default | [391](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/GridMinimalPerf.default.html) | [370](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.06:1
LayoutMinimalPerf.default | [457](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/LayoutMinimalPerf.default.html) | [432](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.06:1
ListCommonPerf.default | [729](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ListCommonPerf.default.html) | [688](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ListCommonPerf.default_base.html) | 1.06:1
Button.Fluent | [646](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Button.Fluent.html) | [607](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Button.Fluent_base.html) | 1.06:1
Icon.Fluent | [789](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Icon.Fluent.html) | [746](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Icon.Fluent_base.html) | 1.06:1
BoxMinimalPerf.default | [400](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/BoxMinimalPerf.default.html) | [382](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.05:1
CardMinimalPerf.default | [616](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/CardMinimalPerf.default.html) | [589](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.05:1
ChatMinimalPerf.default | [689](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ChatMinimalPerf.default.html) | [657](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.05:1
HeaderMinimalPerf.default | [416](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/HeaderMinimalPerf.default.html) | [398](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.05:1
PopupMinimalPerf.default | [738](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/PopupMinimalPerf.default.html) | [703](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.05:1
AnimationMinimalPerf.default | [422](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AnimationMinimalPerf.default.html) | [407](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [629](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonSlotsPerf.default.html) | [607](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
DialogMinimalPerf.default | [832](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DialogMinimalPerf.default.html) | [801](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.04:1
DropdownManyItemsPerf.default | [809](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DropdownManyItemsPerf.default.html) | [780](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.04:1
ReactionMinimalPerf.default | [448](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ReactionMinimalPerf.default.html) | [430](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.04:1
TableMinimalPerf.default | [456](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TableMinimalPerf.default.html) | [440](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [541](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TextAreaMinimalPerf.default.html) | [519](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
VideoMinimalPerf.default | [688](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/VideoMinimalPerf.default.html) | [660](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.04:1
Text.Fluent | [395](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Text.Fluent.html) | [378](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Text.Fluent_base.html) | 1.04:1
AvatarMinimalPerf.default | [503](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AvatarMinimalPerf.default.html) | [486](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.03:1
FormMinimalPerf.default | [474](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/FormMinimalPerf.default.html) | [461](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.03:1
ListNestedPerf.default | [623](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ListNestedPerf.default.html) | [605](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ListNestedPerf.default_base.html) | 1.03:1
LoaderMinimalPerf.default | [751](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/LoaderMinimalPerf.default.html) | [732](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.03:1
MenuMinimalPerf.default | [938](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/MenuMinimalPerf.default.html) | [914](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.03:1
TableManyItemsPerf.default | [2290](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TableManyItemsPerf.default.html) | [2221](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.03:1
Tooltip.Fluent | [572](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Tooltip.Fluent.html) | [555](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Tooltip.Fluent_base.html) | 1.03:1
ButtonUseCssPerf.default | [866](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonUseCssPerf.default.html) | [847](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [467](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/CarouselMinimalPerf.default.html) | [460](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
DropdownMinimalPerf.default | [2948](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DropdownMinimalPerf.default.html) | [2890](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.02:1
ItemLayoutMinimalPerf.default | [1377](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1347](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.02:1
RefMinimalPerf.default | [243](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/RefMinimalPerf.default.html) | [238](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.02:1
SliderMinimalPerf.default | [1571](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/SliderMinimalPerf.default.html) | [1542](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.02:1
TextMinimalPerf.default | [396](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TextMinimalPerf.default.html) | [390](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.02:1
Dialog.Fluent | [829](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Dialog.Fluent.html) | [816](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Dialog.Fluent_base.html) | 1.02:1
AlertMinimalPerf.default | [328](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AlertMinimalPerf.default.html) | [324](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.01:1
AttachmentSlotsPerf.default | [1182](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1170](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1700](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1679](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
ButtonUseCssNestingPerf.default | [1089](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1074](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [47365](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DatepickerMinimalPerf.default.html) | [47031](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
ListWith60ListItems.default | [964](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ListWith60ListItems.default.html) | [951](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.01:1
RadioGroupMinimalPerf.default | [479](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [475](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [838](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TooltipMinimalPerf.default.html) | [830](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
Avatar.Fluent | [920](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Avatar.Fluent.html) | [915](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Avatar.Fluent_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2898](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2889](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
ImageMinimalPerf.default | [420](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ImageMinimalPerf.default.html) | [420](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [462](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/LabelMinimalPerf.default.html) | [462](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1953](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1959](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3724](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/CustomToolbarPrototype.default.html) | [3732](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
ToolbarMinimalPerf.default | [988](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ToolbarMinimalPerf.default.html) | [989](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1:1
TreeWith60ListItems.default | [211](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TreeWith60ListItems.default.html) | [212](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1:1
Checkbox.Fluent | [638](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Checkbox.Fluent.html) | [640](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Checkbox.Fluent_base.html) | 1:1
AttachmentMinimalPerf.default | [173](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AttachmentMinimalPerf.default.html) | [174](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.99:1
ChatDuplicateMessagesPerf.default | [423](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [427](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [4074](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/EmbedMinimalPerf.default.html) | [4114](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1311](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/InputMinimalPerf.default.html) | [1322](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
ProviderMinimalPerf.default | [972](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ProviderMinimalPerf.default.html) | [984](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.99:1
SegmentMinimalPerf.default | [389](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/SegmentMinimalPerf.default.html) | [392](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.99:1
StatusMinimalPerf.default | [759](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/StatusMinimalPerf.default.html) | [768](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.99:1
TreeMinimalPerf.default | [815](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TreeMinimalPerf.default.html) | [821](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.99:1
Dropdown.Fluent | [2904](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Dropdown.Fluent.html) | [2921](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Dropdown.Fluent_base.html) | 0.99:1
Image.Fluent | [408](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Image.Fluent.html) | [412](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Image.Fluent_base.html) | 0.99:1
FlexMinimalPerf.default | [324](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/FlexMinimalPerf.default.html) | [330](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/FlexMinimalPerf.default_base.html) | 0.98:1
MenuButtonMinimalPerf.default | [1611](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1640](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.98:1
SplitButtonMinimalPerf.default | [3867](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3926](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 0.98:1
HeaderSlotsPerf.default | [849](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/HeaderSlotsPerf.default.html) | [874](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.97:1
Slider.Fluent | [1514](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Slider.Fluent.html) | [1558](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/Slider.Fluent_base.html) | 0.97:1
DividerMinimalPerf.default | [417](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DividerMinimalPerf.default.html) | [433](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.96:1
AccordionMinimalPerf.default | [168](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AccordionMinimalPerf.default.html) | [180](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16324/merge/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.93:1

</details><div id="perfComment9423"/>

File: packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts (hunk 2 above)
Comment (kolaps33) [reply packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts:31]: I was thinking and considering usage, when it is defined like attribute in "html" way:
image

Comment (ling1726) [reply packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts:31]: Since this is really only gonna be used in the context of react, I'd rather only support the boolean. But it's your call

EDIT: letting consumers use strings might negatively impact bundling since the string would probably need to bundled, not entirely sure on this since I haven't tested this but it's a thought

File: packages/fluentui/react-northstar/src/utils/htmlPropsUtils.tsx (hunk 3 above)
Comment (kolaps33) [reply packages/fluentui/react-northstar/src/utils/htmlPropsUtils.tsx:161]: I wanted to separate(define) only my "custom" aria props.
But on the line 165 there was "htmlProps" typed only to HtmlInputProps[], which I don't need. It cause issue, that I got together with my aria props as well "keydown" object/event , and it broke some other behavior, then.
So I added this type to be able set any custom props which I need.
Not sure if this is correct way. Hope so :)

File: packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts (hunk 2 above)
Comment (kolaps33) [reply packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts]: changed only for boolean :)

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx [hunk 4]
```diff
@@ -422,6 +430,9 @@ export const Dropdown: ComponentWithAs<'div', DropdownProps> &
 
   const ElementType = getElementType(props);
   const unhandledProps = useUnhandledProps(Dropdown.handledProps, props);
+  const [unhandledA11yProps, restUnhandledProps] = partitionHTMLProps(unhandledProps, {
+    htmlProps: ['aria-labelledby', 'aria-invalid'],
+  });
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx:435]: This should do what you want without definig custom htmlProps which is just an array in disguise :D

```suggestion
  const [unhandledA11yProps, restUnhandledProps] = partitionHTMLProps(unhandledProps, {
    includeAria: true,
  });
```

File: packages/fluentui/react-northstar/src/utils/htmlPropsUtils.tsx (hunk 3 above)
Comment (ling1726) [reply packages/fluentui/react-northstar/src/utils/htmlPropsUtils.tsx:161]: I've added a suggestion to your usage of `partitionHtmlProps`, you shouldn't need this


also this is just an array in disguise :) there is no difference between this and `string[]`

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx (hunk 4 above)
Comment (kolaps33) [reply packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx:435]: image

I tested it and unfortunately it doesn't help. It adds onKeyDown event into result.

**Review by ling1726 — APPROVED** [review]

File: packages/fluentui/react-northstar/src/utils/htmlPropsUtils.tsx (hunk 3 above)
Comment (ling1726) [reply packages/fluentui/react-northstar/src/utils/htmlPropsUtils.tsx]: As we discussed offline, just add `AriaAttributes` type in a union

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx (hunk 4 above)
Comment (ling1726) [reply packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx:435]: As we discussed offline, just add AriaAttributes type in a union

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx [hunk 5]
```diff
@@ -51,6 +52,13 @@ import {
   partitionPopperPropsFromShorthand,
 } from '../../utils/positioner';
 
+export type unhandledA11yProps = {
```
Comment (pompomon) [inline packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx:55]: Please why do you call the type `unhandledA11yProps` here and `a11yProps` in `Datepicker`?
Is there any difference in how they are handled?

File: packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx [hunk 6]
```diff
@@ -51,6 +52,13 @@ import {
...
+  props: {
+    'aria-invalid': string;
+    'aria-labelledby': string;
```
Comment (pompomon) [inline packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx:58]: Please is that correct that we are extracting `aria-labelledby`, but not using it anywhere below?
Like in https://github.com/microsoft/fluentui/pull/16324/files#diff-0dfcfdca092d43b516fbc6007112238d042697c91fdced73011fa22d664d65f2R549 where we construct final `aria-labelledby`

File: packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts [hunk 7]
```diff
@@ -18,4 +26,7 @@ export const datepickerBehavior: Accessibility<DatepickerBehaviorProps> = props
   },
 });
 
-export type DatepickerBehaviorProps = never;
+export type DatepickerBehaviorProps = {
+  'aria-labelledby'?: string;
+  'aria-invalid'?: boolean;
```
Comment (layershifter) [inline packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts:31]: Let's reuse `AccessibilityAttributes`:

```suggestion
  'aria-labelledby'?: AccessibilityAttributes['aria-labelledby'];
  'aria-invalid'?: AccessibilityAttributes['aria-invalid'];
```

File: packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx [hunk 8]
```diff
@@ -243,6 +260,10 @@ export const Datepicker: ComponentWithAs<'div', DatepickerProps> &
         e.preventDefault();
       },
     },
+    mapPropsToBehavior: () => ({
+      'aria-invalid': a11yProps['aria-invalid'],
+      'aria-labelledby': a11yProps['aria-labelledby'],
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx:265]:
```suggestion
      'aria-invalid': props['aria-invalid'],
      'aria-labelledby': props['aria-labelledby'],
```

We have the same thing in `Image` component:
https://github.com/microsoft/fluentui/blob/46055c7b84750bda3d609ab8bf58bb53e4e952cd/packages/fluentui/react-northstar/src/components/Image/Image.tsx#L21

I suggest to move `aria-labelledby` & `aria-invalid` to `DatepickerProps` instead and add a comment that they will be applied to an another slot. Once they will be under `Datepicker.handledProps` they will not be longer a part of `unhandledProps` and will not need changes in `partitionHTMLProps`.

**Review by pompomon — APPROVED** [review]

**Review by layershifter — APPROVED** [review]
