### PR TITLE
fix: update react-combobox multiselect checkbox styles to match Checkbox

### LINKED ISSUE #26508: Bug: multiselect combo/dropdown should use same check indicator as Checkbox
What the title says, from a chat with design.

### PR DESCRIPTION
**Pull request by smhigley**
Fixes #26508

Based on design feedback, we want the multiselect checkboxes to match the Checkbox component, instead of using the icons.

Also adds a 1px transparent outline to the listbox to improve high contrast mode visibility.

### CODE REVIEW

**Review by GeoffCoxMSFT — APPROVED** [review]

File: packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts [hunk 1]
```diff
@@ -86,18 +86,30 @@ const useStyles = makeStyles({
...
+    height: '16px',
+    width: '16px',
     visibility: 'visible',
   },
 
   selectedMultiselectCheck: {
-    color: tokens.colorBrandBackground,
+    backgroundColor: tokens.colorCompoundBrandBackground,
+    color: tokens.colorNeutralForegroundInverted,
+    ...shorthands.borderColor(tokens.colorCompoundBrandBackground),
```
Comment (khmakoto) [inline packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts:112]: Don't you need to add `:hover` and `:active` styles as well?

**Review by sopranopillow — APPROVED** [review]

File: packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts [hunk 2]
```diff
@@ -86,18 +86,30 @@ const useStyles = makeStyles({
...
-  multiselectCheck: {
-    color: tokens.colorNeutralForeground3,
-    fontSize: tokens.fontSizeBase500,
+  selectedCheck: {
     visibility: 'visible',
   },
 
-  selectedCheck: {
+  multiselectCheck: {
+    ...shorthands.border(tokens.strokeWidthThin, 'solid', tokens.colorNeutralForeground3),
```
Comment (khmakoto) [inline packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts:94]:
```suggestion
    ...shorthands.border(tokens.strokeWidthThin, 'solid', tokens.colorNeutralStrokeAccessible),
```

File: packages/react-components/react-combobox/src/components/Listbox/useListboxStyles.ts [hunk 3]
```diff
@@ -18,6 +18,7 @@ const useStyles = makeStyles({
     flexDirection: 'column',
     minWidth: '160px',
     overflowY: 'auto',
+    ...shorthands.outline('1px', 'solid', tokens.colorTransparentStroke),
```
Comment (spmonahan) [inline packages/react-components/react-combobox/src/components/Listbox/useListboxStyles.ts:21]: Feel free to disregard this since it's outside the scope of this change but I think we can use [makeResetStyles()](https://griffel.js.org/react/api/make-reset-styles) here to minimize class name bloat.

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                             |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                      Change |
| :---------------------------------------------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr> | `80.873 kB`<br />`25.955 kB` | `82.574 kB`<br />`26.394 kB` | `1.701 kB` <br />`439 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/ComboboxField.fixture.js'>ComboboxField</abbr>                    | `78.781 kB`<br />`26.063 kB` | `78.959 kB`<br />`26.136 kB` |     `178 B` <br />`73 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr> | `79.541 kB`<br />`25.685 kB` | `81.246 kB`<br />`26.133 kB` | `1.705 kB` <br />`448 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              | `60.308 kB`<br />`16.821 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.08 kB`<br />`52.847 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `34.665 kB`<br />`11.427 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `6.069 kB`<br />`2.053 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/62c47b1149fe37965f4260ab7aeec8a63b1d870e'>62c47b1149fe37965f4260ab7aeec8a63b1d870e</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts (hunk 1 above)
Comment (smhigley) [reply packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts:112]: It's a bit different, since the Option itself has a hover and active style, rather than the checkbox indicator

File: packages/react-components/react-combobox/src/components/Listbox/useListboxStyles.ts (hunk 3 above)
Comment (smhigley) [reply packages/react-components/react-combobox/src/components/Listbox/useListboxStyles.ts:21]: I kinda want to go through and do some `makeResetStyles` changes in Combobox/Dropdown overall -- might save that for a different PR though

Comment (smhigley) [reply packages/react-components/react-combobox/src/components/Listbox/useListboxStyles.ts:21]: I wrote the initial styles before `makeResetStyles`, and I haven't given it a pass through for splitting out not-super-reusable styles yet.

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/Avatar-mount_base.html">1558</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/Avatar-mount.html">1526</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/Button-mount_base.html">1112</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/Button-mount.html">1114</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/FluentProvider-mount_base.html">1938</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/FluentProvider-mount.html">1888</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/FluentProviderWithTheme-mount_base.html">758</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/FluentProviderWithTheme-mount.html">741</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">704</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">684</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">734</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>InfoButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/InfoButton-mount_base.html">667</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/InfoButton-mount.html">658</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/MakeStyles-mount_base.html">2285</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/MakeStyles-mount.html">2269</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/Persona-mount_base.html">3584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/Persona-mount.html">3551</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/SpinButton-mount_base.html">3043</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26509/perf-test-react-components/SpinButton-mount.html">3051</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts (hunk 1 above)
Comment (smhigley) [reply packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts:112]: I double checked with Yvonne, and she confirmed the hover/active are different from Checkbox because of the changing backplate :)

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>
