### PR TITLE
Fix makestyles to re-register styles for objects upon theme change, and avoid memory leak

### LINKED ISSUE #21710: makeStyles  Object not updated when RTL not changed
### Environment Information

- **Package version(s)**:  8.49.7
- **Browser and OS versions**:  Chrome 97

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/newfuture/pen/wvPeBKK?editors=1010

```tsx
const useStylesObj = makeStyles({ root: { paddingLeft: "100px" } });
const useStylesFun = makeStyles(() => ({ root: { paddingLeft: "100px" } }));

const RtlStyle = () => {
  return (
    <div>
      <div className={useStylesObj().root}>
        paddingLeft:
        {"const useStylesObj = makeStyles({ root: { paddingLeft: '100px' } })"}
      </div>
      <div className={useStylesFun().root}>
        paddingLeft:
        {"const useStylesFun = makeStyles(() => ({ root: { paddingLeft: '100px' } }))"}
      </div>
    </div>
  );
};
```

#### Actual behavior:

image
image

#### Expected behavior:
```
const useStylesObj = makeStyles({ root: { paddingLeft: "100px" } });
```
response to  RTL change. (padding-right)

### LINKED ISSUE #22474: [Bug]: makeStyles causes memory leak when run in component rendered in projection popout window
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 9.79 GB / 31.84 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

We found this bug in OWA projection popout window. When open OWA popout window then close it several times, memory usage keeps increasing.

### Bug Description

I found this is caused by file https://github.com/microsoft/fluentui/blob/master/packages/react/src/utilities/ThemeProvider/makeStyles.ts

The following lines:
```ts
    const win = useWindow();  <=============This will get the window object of popout window, which is correct
    const contextualTheme = useTheme();

    theme = theme || contextualTheme;
    const renderer = mergeStylesRenderer;

    const id = renderer.getId();
    const isStyleFunction = typeof styleOrFunction === 'function';
    const path = isStyleFunction ? [id, win, theme] : [id, win];  <=====window object will be stored into graph object, but never cleaned up
    let value = graphGet(graph, path);
```

I have tried locally to remove "win" from line 72, and make it to be:
```ts
  const path = isStyleFunction ? [id, theme] : [id];  
```
And with some other fixes to the code from our side, then memory leak is gone.

I don't know if removing "win" will cause other issues, but at least I didn't find anywhere it is used.

### Logs

_No response_

### Requested priority

High

### Products/sites affected

OWA, Monarch

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by micahgodbolt**
fixes #22474
fixes #21710

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/4db219d06e9450976364a3f8af4109ae48320237'>4db219d06e9450976364a3f8af4109ae48320237</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DocumentCardTitle-mount_base.html">131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DocumentCardTitle-mount.html">138</a></td>
            <td>1000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DocumentCardTitle-mount.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/BaseButton-mount_base.html">779</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/BaseButton-mount.html">769</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Breadcrumb-mount_base.html">2391</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Breadcrumb-mount.html">2386</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Checkbox-mount_base.html">1286</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Checkbox-mount.html">1271</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/CheckboxBase-mount_base.html">1068</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/CheckboxBase-mount.html">1093</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ChoiceGroup-mount_base.html">3993</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ChoiceGroup-mount.html">4059</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ComboBox-mount_base.html">825</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ComboBox-mount.html">849</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/CommandBar-mount_base.html">9126</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/CommandBar-mount.html">9101</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ContextualMenu-mount_base.html">9888</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ContextualMenu-mount.html">10034</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DefaultButton-mount_base.html">981</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DefaultButton-mount.html">992</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DetailsRow-mount_base.html">3305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DetailsRow-mount.html">3316</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DetailsRowFast-mount_base.html">3307</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DetailsRowFast-mount.html">3333</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DetailsRowNoStyles-mount_base.html">3135</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DetailsRowNoStyles-mount.html">3118</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Dialog-mount_base.html">1902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Dialog-mount.html">1932</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DocumentCardTitle-mount_base.html">131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DocumentCardTitle-mount.html">138</a></td>
            <td>1000</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/DocumentCardTitle-mount.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Dropdown-mount_base.html">2823</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Dropdown-mount.html">2824</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/FocusTrapZone-mount_base.html">1545</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/FocusTrapZone-mount.html">1529</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/FocusZone-mount_base.html">1550</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/FocusZone-mount.html">1554</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/IconButton-mount_base.html">1506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/IconButton-mount.html">1507</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Label-mount_base.html">298</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Label-mount.html">305</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Layer-mount_base.html">2532</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Layer-mount.html">2528</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Link-mount_base.html">406</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Link-mount.html">399</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/MenuButton-mount_base.html">1288</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/MenuButton-mount.html">1254</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/MessageBar-mount_base.html">1796</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/MessageBar-mount.html">1871</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Nav-mount_base.html">2847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Nav-mount.html">2856</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/OverflowSet-mount_base.html">941</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/OverflowSet-mount.html">955</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Panel-mount_base.html">1824</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Panel-mount.html">1844</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Persona-mount_base.html">835</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Persona-mount.html">846</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Pivot-mount_base.html">1229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Pivot-mount.html">1336</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/PrimaryButton-mount_base.html">1127</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/PrimaryButton-mount.html">1109</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Rating-mount_base.html">6583</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Rating-mount.html">6609</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/SearchBox-mount_base.html">1130</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/SearchBox-mount.html">1110</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Shimmer-mount_base.html">2127</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Shimmer-mount.html">2124</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Slider-mount_base.html">1692</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Slider-mount.html">1659</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/SpinButton-mount_base.html">4173</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/SpinButton-mount.html">4200</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Spinner-mount_base.html">371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Spinner-mount.html">374</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/SplitButton-mount_base.html">2699</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/SplitButton-mount.html">2684</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Stack-mount_base.html">450</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Stack-mount.html">390</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/StackWithIntrinsicChildren-mount_base.html">1923</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/StackWithIntrinsicChildren-mount.html">1946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/StackWithTextChildren-mount_base.html">4523</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/StackWithTextChildren-mount.html">4396</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/SwatchColorPicker-mount_base.html">9924</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/SwatchColorPicker-mount.html">9882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/TagPicker-mount_base.html">2320</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/TagPicker-mount.html">2309</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/TeachingBubble-mount_base.html">84790</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/TeachingBubble-mount.html">82745</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Text-mount_base.html">376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Text-mount.html">379</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/TextField-mount_base.html">1161</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/TextField-mount.html">1220</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ThemeProvider-mount_base.html">1000</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ThemeProvider-mount.html">1014</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ThemeProvider-virtual-rerender_base.html">562</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ThemeProvider-virtual-rerender.html">561</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1578</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1588</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Toggle-mount_base.html">697</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/Toggle-mount.html">698</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/buttonNative-mount_base.html">108</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22493/perf-test/buttonNative-mount.html">116</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: packages/react/src/utilities/ThemeProvider/makeStyles.ts [hunk 1]
```diff
@@ -61,15 +62,38 @@ export function makeStyles<TStyleSet extends { [key in keyof TStyleSet]: IStyle
...
+      winId = win.__id__;
+      if (!allWindows.has(winId)) {
+        allWindows.add(winId);
+        win.addEventListener('unload', () => cleanupMapEntries(winId));
+      }
+      // cleanupMapEntries will
+      // 1. remove all the graph branches for the window,
+      // 2. remove the event listener,
+      // 3. delete the allWindows entry.
+      const cleanupMapEntries = (id: string | undefined) => {
```
Comment (dzearing) [inline packages/react/src/utilities/ThemeProvider/makeStyles.ts:80]: This can move up above the return; otherwise I think this will get redefined on every hook call on every render.

File: packages/react/src/utilities/ThemeProvider/makeStyles.ts [hunk 2]
```diff
@@ -61,15 +62,38 @@ export function makeStyles<TStyleSet extends { [key in keyof TStyleSet]: IStyle
   // eslint-disable-next-line deprecation/deprecation
   return (options: UseStylesOptions = {}) => {
     let { theme } = options;
-    const win = useWindow();
+    let winId: string | undefined;
+    // Retain a dictionary of window ids we're tracking
+    const allWindows = new Set<string>();
```
Comment (dzearing) [inline packages/react/src/utilities/ThemeProvider/makeStyles.ts:67]: Can move up above the return. Otherwise it gets redefined on every hook call.

File: packages/react/src/utilities/ThemeProvider/makeStyles.ts [hunk 3]
```diff
@@ -61,15 +62,38 @@ export function makeStyles<TStyleSet extends { [key in keyof TStyleSet]: IStyle
...
+        win.addEventListener('unload', () => cleanupMapEntries(winId));
+      }
+      // cleanupMapEntries will
+      // 1. remove all the graph branches for the window,
+      // 2. remove the event listener,
+      // 3. delete the allWindows entry.
+      const cleanupMapEntries = (id: string | undefined) => {
+        if (id) {
+          graph.delete(winId);
+          win.removeEventListener('unload', () => cleanupMapEntries(id));
```
Comment (dzearing) [inline packages/react/src/utilities/ThemeProvider/makeStyles.ts:83]: This isn't going to work. You're passing in a new function which isn't the same function as the one you hooked up. The `removeEventListener` requires the same function you passed into `addEventListener`.

Instead, above the return, create this function:

```js
const cleanupMapEntries(ev: HTMLUnloadEvent) {
  const win = ev.target as WindowWithId;
  const winId = win.__id__;

  // now clean up using the above.
}
```

This means that add/removing the event listener doesn't require a lambda:

```js
win.addEventListener('unload', cleanupMapEntries)
win.removeEventListener('unload', cleanupMapEntries)
```

File: packages/react/src/utilities/ThemeProvider/makeStyles.ts [hunk 4]
```diff
@@ -61,15 +62,38 @@ export function makeStyles<TStyleSet extends { [key in keyof TStyleSet]: IStyle
   // eslint-disable-next-line deprecation/deprecation
   return (options: UseStylesOptions = {}) => {
     let { theme } = options;
-    const win = useWindow();
+    let winId: string | undefined;
+    // Retain a dictionary of window ids we're tracking
+    const allWindows = new Set<string>();
+    const win = useWindow() as (Window & { __id__: string }) | undefined;
```
Comment (dzearing) [inline packages/react/src/utilities/ThemeProvider/makeStyles.ts:68]: Consider moving this type of a type defined above, so that you can use it in multiple places (see other comments.)

```ts
type WindowWithId = Window & { __id__: string };
```

File: packages/react/src/utilities/ThemeProvider/makeStyles.ts (hunk 3 above)
Comment (micahgodbolt) [reply packages/react/src/utilities/ThemeProvider/makeStyles.ts:83]: Yeah, i was wondering about passing the ID in. It didn't seem right.

**Review by dzearing — APPROVED** [review]
Looks great to me, but I would double check that child windows fire unload events.

**Review by JiuqingSong — APPROVED** [review]
