### PR TITLE
fix: Storybook codesandbox export should use unstable imports

### LINKED ISSUE #23180: [Bug]: unstable exports are broken in codesandbox export
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 3.24 GB / 15.42 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 101.0.4951.54
```

### Reproduction

https://codesandbox.io/s/nm0wuy?file=/example.tsx

### Bug Description

https://codesandbox.io/s/nm0wuy?file=/example.tsx

Export any story from the preview section
image

That sandbox will be broken because  the import should be from the unstable entrypoint

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by ling1726**
Fixes #23180 by picking up changes from microsoft/fluentui-storybook-addons#17

### CODE REVIEW

File: .storybook/main.js [hunk 1]
```diff
@@ -108,3 +110,25 @@ function overrideDefaultBabelLoader(rules) {
...
   loader.options.customize = customLoaderPath;
 }
+
+/**
+ * @returns {import('storybook-addon-export-to-codesandbox').PluginOptions}
+ */
+function getCodesandboxBabelOptions() {
+  const allPackageInfo = getAllPackageInfo();
+
+  /** @type {import('storybook-addon-export-to-codesandbox').PluginOptions}  */
```
Comment (ling1726) [inline .storybook/main.js:120]: can't find a better way to type the `reduce` correctly, any suggestions welcome

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                        |        Size (minified/GZIP) |
| ------------------------------------------------------------------------------------------------------------------------ | --------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr> |  `2.936 kB`<br />`1.212 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                  | `10.012 kB`<br />`3.982 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>   |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>             | `31.363 kB`<br />`7.043 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>           | `19.806 kB`<br />`5.699 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                  |        `189 B`<br />`161 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b01ac1a166a8dc67a6c53409d9fe86977517bae6'>b01ac1a166a8dc67a6c53409d9fe86977517bae6</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/Avatar-mount_base.html">885</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/Avatar-mount.html">910</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/Button-mount_base.html">582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/Button-mount.html">563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/FluentProvider-mount_base.html">1829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/FluentProvider-mount.html">1856</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/FluentProviderWithTheme-mount_base.html">295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/FluentProviderWithTheme-mount.html">316</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">228</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">245</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">286</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">334</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/MakeStyles-mount_base.html">1576</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-react-components/MakeStyles-mount.html">1600</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
AlertMinimalPerf.default | [220](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AlertMinimalPerf.default.html) | [192](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.15:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AlertMinimalPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ButtonMinimalPerf.default | [137](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ButtonMinimalPerf.default.html) | [116](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.18:1
ListNestedPerf.default | [470](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ListNestedPerf.default.html) | [397](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ListNestedPerf.default_base.html) | 1.18:1
CarouselMinimalPerf.default | [399](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/CarouselMinimalPerf.default.html) | [350](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.14:1
FormMinimalPerf.default | [339](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/FormMinimalPerf.default.html) | [299](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.13:1
TooltipMinimalPerf.default | [938](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TooltipMinimalPerf.default.html) | [846](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.11:1
ButtonOverridesMissPerf.default | [1253](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1137](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.1:1
CardMinimalPerf.default | [451](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/CardMinimalPerf.default.html) | [411](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.1:1
ListMinimalPerf.default | [417](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ListMinimalPerf.default.html) | [380](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.1:1
ProviderMergeThemesPerf.default | [1052](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [955](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.1:1
LayoutMinimalPerf.default | [289](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/LayoutMinimalPerf.default.html) | [265](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.09:1
TableManyItemsPerf.default | [1568](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TableManyItemsPerf.default.html) | [1457](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.08:1
StatusMinimalPerf.default | [528](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/StatusMinimalPerf.default.html) | [494](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.07:1
CheckboxMinimalPerf.default | [2218](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2101](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.06:1
GridMinimalPerf.default | [270](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/GridMinimalPerf.default.html) | [254](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.06:1
ListWith60ListItems.default | [472](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ListWith60ListItems.default.html) | [444](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.06:1
AccordionMinimalPerf.default | [117](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AccordionMinimalPerf.default.html) | [111](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.05:1
MenuMinimalPerf.default | [723](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/MenuMinimalPerf.default.html) | [689](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.05:1
DividerMinimalPerf.default | [298](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DividerMinimalPerf.default.html) | [287](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.04:1
InputMinimalPerf.default | [1085](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/InputMinimalPerf.default.html) | [1040](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.04:1
ItemLayoutMinimalPerf.default | [987](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [946](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.04:1
TextAreaMinimalPerf.default | [407](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TextAreaMinimalPerf.default.html) | [392](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.04:1
AvatarMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AvatarMinimalPerf.default.html) | [151](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.03:1
ButtonSlotsPerf.default | [469](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ButtonSlotsPerf.default.html) | [455](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
ListCommonPerf.default | [537](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ListCommonPerf.default.html) | [523](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ListCommonPerf.default_base.html) | 1.03:1
PortalMinimalPerf.default | [146](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/PortalMinimalPerf.default.html) | [142](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.03:1
ProviderMinimalPerf.default | [343](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ProviderMinimalPerf.default.html) | [332](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.03:1
RadioGroupMinimalPerf.default | [380](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.03:1
TableMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TableMinimalPerf.default.html) | [334](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.03:1
ChatMinimalPerf.default | [617](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ChatMinimalPerf.default.html) | [607](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.02:1
ImageMinimalPerf.default | [306](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ImageMinimalPerf.default.html) | [299](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.02:1
MenuButtonMinimalPerf.default | [1415](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1389](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [639](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DialogMinimalPerf.default.html) | [634](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [568](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DropdownManyItemsPerf.default.html) | [560](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3594](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3574](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
ChatWithPopoverPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ChatWithPopoverPerf.default.html) | [303](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1:1
FlexMinimalPerf.default | [234](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/FlexMinimalPerf.default.html) | [234](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1:1
HeaderMinimalPerf.default | [296](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/HeaderMinimalPerf.default.html) | [297](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1:1
SegmentMinimalPerf.default | [279](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/SegmentMinimalPerf.default.html) | [281](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.99:1
TextMinimalPerf.default | [277](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TextMinimalPerf.default.html) | [280](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.99:1
ToolbarMinimalPerf.default | [785](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ToolbarMinimalPerf.default.html) | [789](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.99:1
AttachmentSlotsPerf.default | [850](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AttachmentSlotsPerf.default.html) | [871](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.98:1
DatepickerMinimalPerf.default | [4602](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4693](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.98:1
DropdownMinimalPerf.default | [2365](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DropdownMinimalPerf.default.html) | [2406](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 0.98:1
RosterPerf.default | [890](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/RosterPerf.default.html) | [905](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/RosterPerf.default_base.html) | 0.98:1
RefMinimalPerf.default | [194](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/RefMinimalPerf.default.html) | [197](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/RefMinimalPerf.default_base.html) | 0.98:1
AnimationMinimalPerf.default | [444](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AnimationMinimalPerf.default.html) | [457](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.97:1
ChatDuplicateMessagesPerf.default | [236](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [243](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.97:1
PopupMinimalPerf.default | [485](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/PopupMinimalPerf.default.html) | [502](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.97:1
VideoMinimalPerf.default | [523](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/VideoMinimalPerf.default.html) | [538](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.97:1
HeaderSlotsPerf.default | [603](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/HeaderSlotsPerf.default.html) | [626](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 0.96:1
EmbedMinimalPerf.default | [3278](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/EmbedMinimalPerf.default.html) | [3436](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.95:1
LabelMinimalPerf.default | [293](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/LabelMinimalPerf.default.html) | [307](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/LabelMinimalPerf.default_base.html) | 0.95:1
TreeWith60ListItems.default | [109](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TreeWith60ListItems.default.html) | [116](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TreeWith60ListItems.default_base.html) | 0.94:1
CustomToolbarPrototype.default | [2146](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/CustomToolbarPrototype.default.html) | [2309](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.93:1
TreeMinimalPerf.default | [603](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TreeMinimalPerf.default.html) | [658](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.92:1
LoaderMinimalPerf.default | [504](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/LoaderMinimalPerf.default.html) | [553](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.91:1
SliderMinimalPerf.default | [1280](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/SliderMinimalPerf.default.html) | [1401](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/SliderMinimalPerf.default_base.html) | 0.91:1
BoxMinimalPerf.default | [251](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/BoxMinimalPerf.default.html) | [278](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/BoxMinimalPerf.default_base.html) | 0.9:1
ReactionMinimalPerf.default | [271](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ReactionMinimalPerf.default.html) | [303](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 0.89:1
SkeletonMinimalPerf.default | [254](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/SkeletonMinimalPerf.default.html) | [285](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.89:1
AttachmentMinimalPerf.default | [110](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AttachmentMinimalPerf.default.html) | [125](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.88:1
IconMinimalPerf.default | [428](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/IconMinimalPerf.default.html) | [499](https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.86:1

</details><div id="perfComment9424"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/BaseButton-mount_base.html">800</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/BaseButton-mount.html">812</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Breadcrumb-mount_base.html">2662</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Breadcrumb-mount.html">2486</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Checkbox-mount_base.html">1350</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Checkbox-mount.html">1334</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/CheckboxBase-mount_base.html">1098</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/CheckboxBase-mount.html">3416</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ChoiceGroup-mount_base.html">4107</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ChoiceGroup-mount.html">4098</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ComboBox-mount_base.html">867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ComboBox-mount.html">897</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/CommandBar-mount_base.html">10293</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/CommandBar-mount.html">9781</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ContextualMenu-mount_base.html">12510</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ContextualMenu-mount.html">13490</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DefaultButton-mount_base.html">995</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DefaultButton-mount.html">998</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DetailsRow-mount_base.html">3400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DetailsRow-mount.html">3404</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DetailsRowFast-mount_base.html">3360</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DetailsRowFast-mount.html">3326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DetailsRowNoStyles-mount_base.html">3306</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DetailsRowNoStyles-mount.html">3259</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Dialog-mount_base.html">2016</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Dialog-mount.html">2061</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DocumentCardTitle-mount_base.html">152</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/DocumentCardTitle-mount.html">175</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Dropdown-mount_base.html">2943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Dropdown-mount.html">2875</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/FocusTrapZone-mount_base.html">1644</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/FocusTrapZone-mount.html">1659</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/FocusZone-mount_base.html">1610</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/FocusZone-mount.html">1609</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/IconButton-mount_base.html">1611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/IconButton-mount.html">1590</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Label-mount_base.html">332</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Label-mount.html">326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Layer-mount_base.html">2611</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Layer-mount.html">2575</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Link-mount_base.html">424</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Link-mount.html">431</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/MenuButton-mount_base.html">1321</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/MenuButton-mount.html">1319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/MessageBar-mount_base.html">2074</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/MessageBar-mount.html">2014</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Nav-mount_base.html">3138</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Nav-mount.html">3130</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/OverflowSet-mount_base.html">961</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/OverflowSet-mount.html">968</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Panel-mount_base.html">2008</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Panel-mount.html">1996</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Persona-mount_base.html">916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Persona-mount.html">911</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Pivot-mount_base.html">1320</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Pivot-mount.html">1335</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/PrimaryButton-mount_base.html">1168</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/PrimaryButton-mount.html">1138</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Rating-mount_base.html">6858</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Rating-mount.html">7090</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/SearchBox-mount_base.html">1121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/SearchBox-mount.html">1155</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Shimmer-mount_base.html">2137</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Shimmer-mount.html">2131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Slider-mount_base.html">1701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Slider-mount.html">1686</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/SpinButton-mount_base.html">4361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/SpinButton-mount.html">4312</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Spinner-mount_base.html">376</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Spinner-mount.html">385</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/SplitButton-mount_base.html">2740</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/SplitButton-mount.html">2762</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Stack-mount_base.html">451</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Stack-mount.html">452</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/StackWithIntrinsicChildren-mount_base.html">1983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/StackWithIntrinsicChildren-mount.html">1952</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/StackWithTextChildren-mount_base.html">4506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/StackWithTextChildren-mount.html">4477</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/SwatchColorPicker-mount_base.html">10080</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/SwatchColorPicker-mount.html">10186</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/TagPicker-mount_base.html">2310</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/TagPicker-mount.html">2377</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/TeachingBubble-mount_base.html">112786</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/TeachingBubble-mount.html">83772</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Text-mount_base.html">373</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Text-mount.html">367</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/TextField-mount_base.html">1228</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/TextField-mount.html">1252</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ThemeProvider-mount_base.html">1045</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ThemeProvider-mount.html">1064</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ThemeProvider-virtual-rerender_base.html">552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ThemeProvider-virtual-rerender.html">577</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1683</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Toggle-mount_base.html">686</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/Toggle-mount.html">677</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/buttonNative-mount_base.html">115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23317/perf-test/buttonNative-mount.html">115</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: .storybook/main.js [hunk 2]
```diff
@@ -108,3 +110,25 @@ function overrideDefaultBabelLoader(rules) {
...
   loader.options.customize = customLoaderPath;
 }
+
+/**
+ * @returns {import('storybook-addon-export-to-codesandbox').BabelPluginOptions}
+ */
+function getCodesandboxBabelOptions() {
+  const allPackageInfo = getAllPackageInfo();
+
+  /** @type {import('storybook-addon-export-to-codesandbox').BabelPluginOptions}  */
```
Comment (ling1726) [inline .storybook/main.js:120]: can't find a better way to type the `reduce` in the next line... any suggestions welcome

Comment (Hotell) [reply .storybook/main.js:120]: you can assert initializer (similar is being done in TS actually):

```
return Object.values(allPackageInfo).reduce(
(acc, cur) => {},
/** @type import('storybook-addon-export-to-codesandbox').BabelPluginOptions*/ ({}))
)
```

 unfortunately there is no way to instantiate generic directly from within function call like `.reduce<ReturnValue>`

File: .storybook/main.js [hunk 3]
```diff
@@ -108,3 +110,25 @@ function overrideDefaultBabelLoader(rules) {
...
+  const initialValue = {};
+  return Object.values(allPackageInfo).reduce((acc, cur) => {
+    if (isConvergedPackage(cur.packageJson)) {
```
Comment (Hotell) [inline .storybook/main.js:123]: is this check needed ? this storybook is used only for v9

File: .storybook/main.js [hunk 4]
```diff
@@ -108,3 +110,25 @@ function overrideDefaultBabelLoader(rules) {
...
+      const prereleaseTags = semver.prerelease(cur.packageJson.version);
```
Comment (Hotell) [inline .storybook/main.js:124]: can we simplify this ? maybe to something like:

```js
.reduce((acc, packageInfo) => {
    // not sure if this check is needed, as this config is only for v9
    if (!isConvergedPackage(packageInfo.packageJson)) {
      return acc
   }

   const prereleaseTags = semver.prerelease(packageInfo.packageJson.version) ?? [];
   const packageImport =  prereleaseTags[0].includes('rc') ? '@fluentui/react-components' : '@fluentui/react-components/unstable'

   acc[packageInfo.packageJson.name] = {replace: packageImport }

  return acc;
}, 
{}
)

```

File: .storybook/main.js [hunk 5]
```diff
@@ -108,3 +110,25 @@ function overrideDefaultBabelLoader(rules) {
...
+      if (prereleaseTags && !prereleaseTags[0].includes('rc')) {
```
Comment (Hotell) [inline .storybook/main.js:125]: when we will ship stable this will need to be manually changed ?

File: .storybook/main.js [hunk 6]
```diff
@@ -1,6 +1,8 @@
 const path = require('path');
 const fs = require('fs');
 const { TsconfigPathsPlugin } = require('tsconfig-paths-webpack-plugin');
+const { getAllPackageInfo, isConvergedPackage } = require('@fluentui/scripts/monorepo');
```
Comment (Hotell) [inline .storybook/main.js:4]: can we avoid creeping scripts low level api's to storybook ? It would be great if we could encapsulate this logic somewhere

File: .storybook/main.js (hunk 5 above)
Comment (ling1726) [reply .storybook/main.js:125]: not at all the condition is rather if prerelease tags exist and they are not `rc` which should only cover `beta`  and `alpha`

File: .storybook/main.js (hunk 6 above)
Comment (ling1726) [reply .storybook/main.js:4]: but where to encapsulate it ? `main.js` is the entrypoint into storybook

File: .storybook/main.js (hunk 4 above)
Comment (ling1726) [reply .storybook/main.js:124]: it's to avoid having non v9 dependencies in the configuration... it's not that important but I would prefer not to have `@fluentui/react` in the babel plugin config of a v9 storybook addon :)

File: .storybook/main.js (hunk 3 above)
Comment (ling1726) [reply .storybook/main.js:123]: it's to avoid having non v9 dependencies in the configuration... it's not that important but I would prefer not to have @fluentui/react in the babel plugin config of a v9 storybook addon :)

File: .storybook/main.js (hunk 4 above)
Comment (ling1726) [reply .storybook/main.js:124]: That would actually mean we have to manually change it when we release out of rc. The code currently is more future proof since it applies `react-components/unstable` for anything not rc if it has a prerelease tag

File: .storybook/main.js (hunk 2 above)
Comment (ling1726) [reply .storybook/main.js:120]: FML I tried putting the comment above and after the empty object and the only combination I **didn't try was before !!!**

File: .storybook/main.js (hunk 5 above)
Comment (ling1726) [reply .storybook/main.js]: I've modified the code to make this point clearer

File: .storybook/main.js (hunk 6 above)
Comment (Hotell) [reply .storybook/main.js:4]: not sure TBH, somewhere in scripts or so?, lets keep it as is for now

**Review by Hotell — APPROVED** [review]

File: .storybook/main.js (hunk 6 above)
Comment (Hotell) [reply .storybook/main.js:4]: > assuming the primary goal 

primary goal is to have standardized codebase that follows right boundaries, which goes hand in hand with extraction/encapsulation etc
