### PR TITLE
fix: react-field does not wrap SVG in inline parent

### LINKED ISSUE #26061: [Bug]: <InputField> in <DialogContent> causes a vertical scrollbar being rendered
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components: v9.7.4
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/inputfield-in-dialog-di3b13?file=/example.tsx

## Actual Behavior
image

## Expected Behavior
There shouldn't be a vertical scrollbar in the dialog.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by smhigley**
Fixes #26061

## Previous Behavior

Because an SVG was wrapped in a parent with `display: inline`, it caused odd layout issues, despite the SVG also being styled `display: inline`. Specifically, when used within a dialog, it would trigger a vertical scrollbar in the dialog (example in the issue).

We also previously styled status text to wrap like this:
screenshot of success status message text wrapping below a check mark icon

## New Behavior

The scrollbar issue no longer happens, and now text wraps like this (checked with design, and this was the desired behavior):
sreenshot of input field with icon in its own column, and text wrapping in a block adjacent to the icon column

screenshot of a horizontal field with the same layout but the label appearing to the left of the input and all messages

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                  Change |
| :--------------------------------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/CheckboxField.fixture.js'>CheckboxField</abbr>       |  `35.51 kB`<br />`11.026 kB` |  `35.74 kB`<br />`11.077 kB` | `230 B` <br />`51 B`  |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/ComboboxField.fixture.js'>ComboboxField</abbr>       | `77.155 kB`<br />`25.536 kB` | `77.385 kB`<br />`25.594 kB` | `230 B` <br />`58 B`  |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/InputField.fixture.js'>InputField</abbr>                |  `33.839 kB`<br />`10.73 kB` | `34.069 kB`<br />`10.782 kB` | `230 B` <br />`52 B`  |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressField.fixture.js'>ProgressField</abbr>       |  `22.892 kB`<br />`8.057 kB` |  `23.122 kB`<br />`8.112 kB` | `230 B` <br />`55 B`  |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroupField.fixture.js'>RadioGroupField</abbr>      |  `24.024 kB`<br />`8.796 kB` |  `24.254 kB`<br />`8.834 kB` | `230 B` <br />`38 B`  |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/SelectField.fixture.js'>SelectField</abbr>             | `32.162 kB`<br />`10.406 kB` | `32.392 kB`<br />`10.434 kB` | `230 B` <br />`28 B`  |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/SliderField.fixture.js'>SliderField</abbr>             | `41.544 kB`<br />`13.046 kB` | `41.774 kB`<br />`13.108 kB` | `230 B` <br />`62 B`  |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButtonField.fixture.js'>SpinButtonField</abbr> | `53.229 kB`<br />`15.232 kB` | `53.459 kB`<br />`15.284 kB` | `230 B` <br />`52 B`  |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/SwitchField.fixture.js'>SwitchField</abbr>             | `40.176 kB`<br />`12.514 kB` | `40.406 kB`<br />`12.575 kB` | `230 B` <br />`61 B`  |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/TextareaField.fixture.js'>TextareaField</abbr>       |  `35.38 kB`<br />`11.157 kB` |  `35.61 kB`<br />`11.212 kB` | `230 B` <br />`55 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-checkbox</samp> <br /> <abbr title='bundle-size/Checkbox.fixture.js'>Checkbox</abbr>                                                                              |   `29.081 kB`<br />`9.258 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                                                 |  `79.959 kB`<br />`25.572 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>                                                 |  `79.205 kB`<br />`25.496 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `59.888 kB`<br />`16.652 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `188.856 kB`<br />`53.066 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `34.379 kB`<br />`11.322 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |   `24.617 kB`<br />`8.059 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.069 kB`<br />`2.053 kB` |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/ProgressBar.fixture.js'>ProgressBar</abbr>                                                                        |   `13.578 kB`<br />`5.235 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `32.247 kB`<br />`10.468 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |   `14.718 kB`<br />`5.886 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                                                    |   `23.902 kB`<br />`8.187 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |   `32.52 kB`<br />`10.357 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |   `44.933 kB`<br />`12.97 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |  `33.865 kB`<br />`10.735 kB` |
| <samp>react-textarea</samp> <br /> <abbr title='bundle-size/Textarea.fixture.js'>Textarea</abbr>                                                                              |   `26.156 kB`<br />`8.508 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/5b9042fea309185404fb2c8b8986d46381af8241'>5b9042fea309185404fb2c8b8986d46381af8241</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/Avatar-mount_base.html">1631</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/Avatar-mount.html">1599</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/Button-mount_base.html">1148</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/Button-mount.html">1177</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/FluentProvider-mount_base.html">2033</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/FluentProvider-mount.html">1919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/FluentProviderWithTheme-mount_base.html">760</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/FluentProviderWithTheme-mount.html">743</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">694</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">690</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">733</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">739</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/MakeStyles-mount_base.html">2216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/MakeStyles-mount.html">2333</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/Persona-mount_base.html">3529</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/Persona-mount.html">3546</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/SpinButton-mount_base.html">2968</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26150/perf-test-react-components/SpinButton-mount.html">3025</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv9"/>

File: packages/react-components/react-field/src/components/Field/useFieldStyles.ts [hunk 1]
```diff
@@ -59,12 +59,18 @@ const useSecondaryTextStyles = makeStyles({
   },
 });
 
-const useValidationMessageIconStyles = makeStyles({
+const useValidationMessageStyles = makeStyles({
   base: {
+    display: 'flex',
+  },
```
Comment (behowell) [inline packages/react-components/react-field/src/components/Field/useFieldStyles.ts:65]: The `useSecondaryTextStyles` is the one that's used for the validation message (and hint) styles. You should put this there instead, and keep this one for the icon only (revert the name to `useValidationMessageIconStyles`).

Comment (smhigley) [reply packages/react-components/react-field/src/components/Field/useFieldStyles.ts:65]: Just commenting here what we discussed in chat:

We're switching to grid from flexbox, since that allows the icon to be in its own column without needing to wrap it in another node. The reason for moving away from `display: flex` is that it interferes with layout of nested items, e.g. links within hint or validation message text.

File: packages/react-components/react-field/src/components/Field/useFieldStyles.ts [hunk 2]
```diff
@@ -19,16 +19,23 @@ const useRootStyles = makeStyles({
...
+
+  fullWidth: {
+    gridColumnStart: '1',
+    gridColumnEnd: '-1',
   },
 
   secondColumn: {
     gridColumnStart: '2',
+    gridColumnEnd: '-1',
   },
```
Comment (behowell) [inline packages/react-components/react-field/src/components/Field/useFieldStyles.ts:39]: This layout is getting complex enough that it might warrant using gridTemplateAreas instead of the fullWidth and secondColumn classes, and adding `gridArea` to each of the slots.

WDYT? This might just be trading one complexity for another, but it is easier to understand IMO.

```ts
vertical: {
  gridTemplateColumns: 'auto 1fr',
  gridTemplateAreas: `
    "label label"
    "control control"
    "validationIcon validationMessage"
    "hint hint"
  `,
},

horizontal: {
  gridTemplateColumns: '1fr auto 2fr',
  gridTemplateAreas: `
    "label control control"
    "label validationIcon validationMessage"
    "label hint hint"
    "label . ."
  `,
}
```

If you do that, you can take out `gridAutoFlow: 'row',` and `gridTemplateRows: 'auto auto auto auto',` since they're no longer needed.

**Review by behowell — APPROVED** [review]

File: packages/react-components/react-field/src/components/Field/useFieldStyles.ts (hunk 2 above)
Comment (smhigley) [reply packages/react-components/react-field/src/components/Field/useFieldStyles.ts:39]: I like it! I think it ends up being marginally more CSS/generated classnames since then the child nodes can't share the column-start/column-end values, but I agree it's still worth it b/c it is much easier to read :D.

File: packages/react-components/react-field/src/components/Field/useFieldStyles.ts [hunk 3]
```diff
@@ -19,16 +19,23 @@ const useRootStyles = makeStyles({
...
     display: 'grid',
     gridAutoFlow: 'row',
+    gridTemplateColumns: 'auto 1fr',
     justifyItems: 'start',
   },
 
   horizontal: {
     gridTemplateRows: 'auto auto auto auto',
-    gridTemplateColumns: '1fr 2fr',
+    gridTemplateColumns: '1fr auto 2fr',
```
Comment (behowell) [inline packages/react-components/react-field/src/components/Field/useFieldStyles.ts:28]: Just thought of a potential issue here. Since it's using `auto` for the validation message column and the `fr` unit for the other columns, it might cause misalignment between fields that do and don't have a validation message (or movement when a validation message appears).

For example, if the fields are 312px wide, then with no validation icon, there's 312px to split between the other columns, making the label column 104px wide. But with a validation icon, the second column will be 12px, leaving 300px to split, making the label column 100px wide.

Test case:
```jsx
<div style={{ display: 'grid', width: '312px' }}>
  <InputField label="First Name" orientation="horizontal" />
  <InputField label="Last Name" orientation="horizontal" validationState="error" validationMessage="test" />
</div>
```

Probably the best way to fix it is to change the columns to make the label a percentage of the grid width, not the free space:
```suggestion
    gridTemplateColumns: '33% auto 1fr',
```

Comment (smhigley) [reply packages/react-components/react-field/src/components/Field/useFieldStyles.ts:28]: oooo, good catch 👍

File: packages/react-components/react-field/src/components/Field/useFieldStyles.ts [hunk 4]
```diff
@@ -19,16 +19,51 @@ const useRootStyles = makeStyles({
...
+  },
+
+  validationMessage: {
+    gridColumnStart: 'validationMessage',
+    gridColumnEnd: 'validationMessage',
+  },
+
+  hint: {
+    gridColumnStart: 'hint',
+    gridColumnEnd: 'hint',
```
Comment (smhigley) [inline packages/react-components/react-field/src/components/Field/useFieldStyles.ts:66]: I put all the grid layout styles under `useRootStyles` just to make it easier to skim and understand.

I ended up not specifying row-start/row-end values for the single-row items. It's not quite the same as `grid-area`, but I figured it's not worth the extra classes to do so

**Review by behowell — APPROVED** [review]
