### PR TITLE
fix: Field should use aria-describedby instead of aria-errormessage

### LINKED ISSUE #25579: fix: Field should use aria-describedby instead of aria-errormessage
Field currently sets the validationMessage as its `aria-errormessage` when it is an error. However, that is not well supported by screen readers. We should be using `aria-describedby` instead.

### PR DESCRIPTION
**Pull request by behowell**
## Current Behavior

Field currently sets the validationMessage as its `aria-errormessage` when it is an error. However, that is not well supported by screen readers.

## New Behavior

Field sets `aria-describedby` to the validationMessage regardless of the validationState. It no longer sets `aria-errormessage`.

## Related Issue(s)

* Fixes #25579

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `62.941 kB`<br />`17.678 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.948 kB`<br />`52.993 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `33.446 kB`<br />`11.033 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/023737b640281434710caecc55270838895b50bc'>023737b640281434710caecc55270838895b50bc</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/Avatar-mount_base.html">1282</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/Avatar-mount.html">1288</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/Button-mount_base.html">925</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/Button-mount.html">927</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/FluentProvider-mount_base.html">1511</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/FluentProvider-mount.html">1486</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/FluentProviderWithTheme-mount_base.html">576</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/FluentProviderWithTheme-mount.html">575</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">539</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">542</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">580</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">573</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/MakeStyles-mount_base.html">1983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/MakeStyles-mount.html">1980</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/SpinButton-mount_base.html">2375</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25580/perf-test-react-components/SpinButton-mount.html">2358</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Review by khmakoto — APPROVED** [review]

File: packages/react-components/react-field/src/components/Field/useField.tsx [hunk 1]
```diff
@@ -118,20 +118,14 @@ export const useField_unstable = <T extends FieldComponent>(
     control['aria-labelledby'] ??= label.id;
   }
 
+  if (validationMessage || hint) {
+    // The control is described by the validation message, or hint, or both
+    control['aria-describedby'] ??=
+      validationMessage && hint ? `${validationMessage.id} ${hint.id}` : validationMessage?.id || hint?.id;
```
Comment (smhigley) [inline packages/react-components/react-field/src/components/Field/useField.tsx:124]: Would we want to prepend the validation message id to an existing `aria-describedby` if one is present?

I understand not wanting to append or overwrite in the case of `hint`, since a hint is probably equivalent in purpose to most use cases of author-provided `aria-describedby`. Error messages seem different, since the most common use case would be using the error in addition to the provided descriptive text. I actually can't easily think of a case where one wouldn't want that to happen.

If we don't add the validation id to an existing attribute value, is there an easy way for an author provide both a custom `aria-describedby` and a validation message?

**Review by smhigley — COMMENTED** [review]
+1 to using `aria-describedby`, but I have a question on merging the validation `id` and a custom `aria-describedby`

**Review by sopranopillow — APPROVED** [review]

File: packages/react-components/react-field/src/components/Field/useField.tsx (hunk 1 above)
Comment (behowell) [reply packages/react-components/react-field/src/components/Field/useField.tsx:124]: We've generally used the approach that if someone explicitly sets a prop like `aria-describedby="foo"`, we let that override anything that the component would set internally. Otherwise, there's no way for them to specify the value if they truly want to replace what the component sets.

If someone wanted to append something else to a field's aria-describedby, they can set their own ID on the validationMessage, and reference that ID in aria-describedby.

```jsx
<InputField
  validationMessage={{ id: 'my-validation-message', children: '...' }}
  aria-describedby="my-validation-message foo"
/>
```

That is a bit complicated. I don't really expect people to need to do it, but at least it's possible.

Comment (behowell) [reply packages/react-components/react-field/src/components/Field/useField.tsx:124]: Talked to @smhigley offline, and we decided to make Field append any user-supplied `aria-describedby` to the validationMessage and hint, rather than override it:
1. Users may have custom descriptions outside the field, but we don't want that to unexpectedly override the error message.
2. If someone adds a Tooltip to a field, then that could set `aria-describedby`, but it shouldn't override the error message.
3. The failure condition is safer: in the case where the user supplies a custom `aria-descibedby`, then the worst case is that there is some redundant information in the description.
4. It is still technically possible to completely override via `<InputField control={{ 'aria-describedby': 'my-description' }} />`

**Comment by fabricteam** [comment]
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-tool-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25580&commitId=2a0043133276cc030f74f27eaf2ddf2f25f184a1&env=prod)

✅ There was 0 screenshots added, 0 screenshots removed, 1749 screenshots unchanged, 0 screenshots with different dimensions and 2 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.size+active+badge.normal.chromium.png|2| Changed|
|Avatar Converged.size+active+ring-shadow.normal.chromium.png|3| Changed|

</details>


<div id="vrtCommentfluentuiv9"/>

**Review by smhigley — APPROVED** [review]
