### PR TITLE
fix(Menu, Popover): Clone ref correctly

### LINKED ISSUE #19380: MenuTrigger, PopoverTrigger: Child ref is not retained
### Environment Information

- **Package version(s)**: v9

### Please provide a reproduction of the bug in a codepen:

When passing a ref to the child of a `MenuTrigger` or `PopoverTrigger` it is lost and never assigned to the actual DOM element. This is because 

`child.props.ref` is incorrect and `child.ref` (undocumented) should be used instead

https://codesandbox.io/s/admiring-cohen-of81g?file=/src/App.js

#### Actual behavior:

Original ref is lost, console never logs the HTML element value

#### Expected behavior:

Original ref is not lost, console logs the HTML element value

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

### PR DESCRIPTION
**Pull request by ling1726**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #19380
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Previously trigger refs were cloned incorrectly using `child.props.ref`.
The correct property should be `child.ref` which is not correctly typed
by React

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                                                    Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `176.831 kB`<br />`50.072 kB` | `176.843 kB`<br />`50.073 kB` | `-12 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/Decrease.svg" /><br />`-1 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/Decrease.svg" /> |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `114.495 kB`<br />`34.518 kB` | `114.501 kB`<br />`34.518 kB` |                                                                                                                   `-6 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/Decrease.svg" /><br /> |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `117.177 kB`<br />`35.064 kB` | `117.183 kB`<br />`35.064 kB` |                                                                                                                   `-6 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/Decrease.svg" /><br /> |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `124.166 kB`<br />`36.12 kB` | `124.172 kB`<br />`36.121 kB` |  `-6 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/Decrease.svg" /><br />`-1 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/Decrease.svg" /> |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |         Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `36.237 kB`<br />`11.596 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/f773a1bc4e1aaea6e6145e3a8c04eaefb5ac9bde'>f773a1bc4e1aaea6e6145e3a8c04eaefb5ac9bde</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Avatar-mount_base.html">912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Avatar-mount.html">897</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/BaseButton-mount_base.html">887</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/BaseButton-mount.html">887</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Breadcrumb-mount_base.html">2576</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Breadcrumb-mount.html">2599</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ButtonNext-mount_base.html">424</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ButtonNext-mount.html">423</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Checkbox-mount_base.html">1484</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Checkbox-mount.html">1481</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/CheckboxBase-mount_base.html">1337</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/CheckboxBase-mount.html">1242</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ChoiceGroup-mount_base.html">4689</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ChoiceGroup-mount.html">4691</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ComboBox-mount_base.html">949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ComboBox-mount.html">985</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/CommandBar-mount_base.html">10012</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/CommandBar-mount.html">10085</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ContextualMenu-mount_base.html">6031</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ContextualMenu-mount.html">6066</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DefaultButton-mount_base.html">1100</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DefaultButton-mount.html">1090</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DetailsRow-mount_base.html">3713</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DetailsRow-mount.html">3736</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DetailsRowFast-mount_base.html">3674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DetailsRowFast-mount.html">3638</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DetailsRowNoStyles-mount_base.html">3505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DetailsRowNoStyles-mount.html">3445</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Dialog-mount_base.html">2119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Dialog-mount.html">2086</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DocumentCardTitle-mount_base.html">146</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/DocumentCardTitle-mount.html">152</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Dropdown-mount_base.html">3185</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Dropdown-mount.html">3211</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/FluentProviderNext-mount_base.html">7603</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/FluentProviderNext-mount.html">7336</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/FocusTrapZone-mount_base.html">1777</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/FocusTrapZone-mount.html">1751</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/FocusZone-mount_base.html">1803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/FocusZone-mount.html">1804</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/IconButton-mount_base.html">1722</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/IconButton-mount.html">1702</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Label-mount_base.html">341</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Label-mount.html">336</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Layer-mount_base.html">1731</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Layer-mount.html">1755</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Link-mount_base.html">464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Link-mount.html">455</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/MakeStyles-mount_base.html">1833</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/MakeStyles-mount.html">1830</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/MenuButton-mount_base.html">1446</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/MenuButton-mount.html">1448</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/MessageBar-mount_base.html">1994</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/MessageBar-mount.html">2003</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Nav-mount_base.html">3213</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Nav-mount.html">3182</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/OverflowSet-mount_base.html">1072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/OverflowSet-mount.html">1052</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Panel-mount_base.html">2060</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Panel-mount.html">2071</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Persona-mount_base.html">845</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Persona-mount.html">806</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Pivot-mount_base.html">1395</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Pivot-mount.html">1385</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/PrimaryButton-mount_base.html">1248</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/PrimaryButton-mount.html">1283</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Rating-mount_base.html">7457</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Rating-mount.html">7542</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/SearchBox-mount_base.html">1275</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/SearchBox-mount.html">1290</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Shimmer-mount_base.html">2505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Shimmer-mount.html">2484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Slider-mount_base.html">1904</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Slider-mount.html">1953</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/SpinButton-mount_base.html">4946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/SpinButton-mount.html">4858</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Spinner-mount_base.html">423</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Spinner-mount.html">409</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/SplitButton-mount_base.html">3131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/SplitButton-mount.html">3074</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Stack-mount_base.html">485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Stack-mount.html">499</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/StackWithIntrinsicChildren-mount_base.html">1537</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/StackWithIntrinsicChildren-mount.html">1534</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/StackWithTextChildren-mount_base.html">4390</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/StackWithTextChildren-mount.html">4422</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/SwatchColorPicker-mount_base.html">10002</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/SwatchColorPicker-mount.html">9881</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Tabs-mount_base.html">1379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Tabs-mount.html">1373</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/TagPicker-mount_base.html">2515</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/TagPicker-mount.html">2514</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/TeachingBubble-mount_base.html">11662</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/TeachingBubble-mount.html">11674</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Text-mount_base.html">405</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Text-mount.html">415</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/TextField-mount_base.html">1336</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/TextField-mount.html">1339</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ThemeProvider-mount_base.html">1151</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ThemeProvider-mount.html">1172</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ThemeProvider-virtual-rerender_base.html">594</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/ThemeProvider-virtual-rerender.html">586</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Toggle-mount_base.html">791</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/Toggle-mount.html">772</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/buttonNative-mount_base.html">119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test/buttonNative-mount.html">99</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
TextMinimalPerf.default | [337](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TextMinimalPerf.default.html) | [331](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.02:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TextMinimalPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AlertMinimalPerf.default | [276](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AlertMinimalPerf.default.html) | [259](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.07:1
CarouselMinimalPerf.default | [474](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/CarouselMinimalPerf.default.html) | [445](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.07:1
TreeWith60ListItems.default | [180](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TreeWith60ListItems.default.html) | [168](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.07:1
HeaderMinimalPerf.default | [373](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/HeaderMinimalPerf.default.html) | [351](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.06:1
ChatMinimalPerf.default | [660](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ChatMinimalPerf.default.html) | [626](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.05:1
ChatWithPopoverPerf.default | [368](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ChatWithPopoverPerf.default.html) | [352](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.05:1
PortalMinimalPerf.default | [185](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/PortalMinimalPerf.default.html) | [177](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.05:1
RefMinimalPerf.default | [227](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/RefMinimalPerf.default.html) | [217](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.05:1
VideoMinimalPerf.default | [619](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/VideoMinimalPerf.default.html) | [590](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.05:1
RadioGroupMinimalPerf.default | [433](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [418](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.04:1
HeaderSlotsPerf.default | [749](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/HeaderSlotsPerf.default.html) | [727](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.03:1
LayoutMinimalPerf.default | [359](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/LayoutMinimalPerf.default.html) | [350](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.03:1
ReactionMinimalPerf.default | [373](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ReactionMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.03:1
AnimationMinimalPerf.default | [403](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AnimationMinimalPerf.default.html) | [396](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.02:1
AttachmentMinimalPerf.default | [156](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AttachmentMinimalPerf.default.html) | [153](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1708](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1676](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [746](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DialogMinimalPerf.default.html) | [733](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
DropdownManyItemsPerf.default | [653](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DropdownManyItemsPerf.default.html) | [639](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.02:1
FlexMinimalPerf.default | [282](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/FlexMinimalPerf.default.html) | [277](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.02:1
GridMinimalPerf.default | [335](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/GridMinimalPerf.default.html) | [328](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.02:1
ListWith60ListItems.default | [634](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ListWith60ListItems.default.html) | [624](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.02:1
MenuMinimalPerf.default | [827](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/MenuMinimalPerf.default.html) | [813](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.02:1
ProviderMinimalPerf.default | [982](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ProviderMinimalPerf.default.html) | [967](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.02:1
AvatarMinimalPerf.default | [195](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AvatarMinimalPerf.default.html) | [194](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.01:1
BoxMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/BoxMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.01:1
ButtonMinimalPerf.default | [165](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ButtonMinimalPerf.default.html) | [164](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.01:1
CardMinimalPerf.default | [551](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/CardMinimalPerf.default.html) | [545](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.01:1
ChatDuplicateMessagesPerf.default | [295](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [292](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.01:1
DatepickerMinimalPerf.default | [5365](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5305](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.01:1
DividerMinimalPerf.default | [355](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DividerMinimalPerf.default.html) | [353](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.01:1
ImageMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ImageMinimalPerf.default.html) | [361](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [1249](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/InputMinimalPerf.default.html) | [1231](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
ListMinimalPerf.default | [490](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ListMinimalPerf.default.html) | [487](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [678](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/LoaderMinimalPerf.default.html) | [670](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [1661](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1647](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
SkeletonMinimalPerf.default | [349](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/SkeletonMinimalPerf.default.html) | [346](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.01:1
SliderMinimalPerf.default | [1560](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/SliderMinimalPerf.default.html) | [1551](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1852](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TableManyItemsPerf.default.html) | [1826](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TableMinimalPerf.default | [396](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TableMinimalPerf.default.html) | [392](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.01:1
ToolbarMinimalPerf.default | [915](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ToolbarMinimalPerf.default.html) | [907](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.01:1
TreeMinimalPerf.default | [791](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TreeMinimalPerf.default.html) | [781](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.01:1
ButtonSlotsPerf.default | [532](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ButtonSlotsPerf.default.html) | [533](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2719](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2724](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [3035](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DropdownMinimalPerf.default.html) | [3030](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
EmbedMinimalPerf.default | [4054](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/EmbedMinimalPerf.default.html) | [4046](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1:1
LabelMinimalPerf.default | [376](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/LabelMinimalPerf.default.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1:1
ListCommonPerf.default | [604](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ListCommonPerf.default.html) | [603](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ListCommonPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1612](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1605](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3704](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3719](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [657](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/StatusMinimalPerf.default.html) | [655](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
IconMinimalPerf.default | [607](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/IconMinimalPerf.default.html) | [604](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/IconMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3794](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/CustomToolbarPrototype.default.html) | [3787](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
TooltipMinimalPerf.default | [976](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TooltipMinimalPerf.default.html) | [978](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
ItemLayoutMinimalPerf.default | [1183](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1200](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.99:1
PopupMinimalPerf.default | [581](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/PopupMinimalPerf.default.html) | [584](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.99:1
SegmentMinimalPerf.default | [333](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/SegmentMinimalPerf.default.html) | [336](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 0.99:1
AttachmentSlotsPerf.default | [1032](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1051](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.98:1
FormMinimalPerf.default | [390](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/FormMinimalPerf.default.html) | [396](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.98:1
TextAreaMinimalPerf.default | [491](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TextAreaMinimalPerf.default.html) | [499](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.98:1
AccordionMinimalPerf.default | [147](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AccordionMinimalPerf.default.html) | [151](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.97:1
ListNestedPerf.default | [528](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ListNestedPerf.default.html) | [549](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/ListNestedPerf.default_base.html) | 0.96:1
RosterPerf.default | [1119](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/RosterPerf.default.html) | [1175](https://fluentuipr.z22.web.core.windows.net/pull/19375/perf-test-northstar/RosterPerf.default_base.html) | 0.95:1

</details><div id="perfComment9423"/>

File: packages/react-menu/src/components/MenuTrigger/useTriggerElement.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ export const useTriggerElement = (state: MenuTriggerState): MenuTriggerState =>
 
   state.children = React.cloneElement(child, {
     ...triggerProps,
-    ref: useMergedRefs(child.props.ref, triggerRef),
+    ref: useMergedRefs(((child as unknown) as { ref: React.Ref<unknown> }).ref, triggerRef),
```
Comment (layershifter) [inline packages/react-menu/src/components/MenuTrigger/useTriggerElement.ts:138]: Oops, yeah, `.ref` is not a prop 😅

---

- Ideally we should use there `React.ReactElement` the problem is that it does not contain `ref` 😯
- nit: I suggest to use `React.ReactElement` & `React.RefAttributes`

```suggestion
    ref: useMergedRefs(((child as unknown) as React.ReactElement & React.RefAttributes<unknown>).ref, triggerRef),
```

As `forwardRef()` in types uses similar definition:

```
    function forwardRef<T, P = {}>(render: ForwardRefRenderFunction<T, P>): ForwardRefExoticComponent<PropsWithoutRef<P> & RefAttributes<T>>;
```

**Review by layershifter — APPROVED** [review]
