### PR TITLE
fix: Adding 'aria-expanded=false' to collapsed MenuButtons

### LINKED ISSUE #21409: MenuButton screen reader access issues
The a11y review of the v9 `MenuButton` component (#20917) identified a bunch of screen reader access issues that need to be fixed:

- `aria-expanded` missing from `MenuButton` when collapsed.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

While open `MenuButtons` have `aria-expanded` set to `true`, collapsed `MenuButtons` do not have `aria-expanded` set to `false`, and instead have it `undefined`. This can create some problems regarding screen reader access where users of screen readers do not realize `MenuButtons` have collapsed menus.

## New Behavior

Collapsed `MenuButtons` now have `aria-expanded` set to `false`, correctly indicating this information for all screen readers.

## Related Issue(s)

Fixes #21409

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                    |     Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                  Change |
| :--------------------------------------------------------------------------------------------------- | ---------------------------: | ---------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>   | `38.737 kB`<br />`10.521 kB` | `38.821 kB`<br />`10.552 kB` |  `84 B` <br />`31 B`  |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr> |   `46.136 kB`<br />`11.9 kB` | `46.236 kB`<br />`11.938 kB` | `100 B` <br />`38 B`  |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |         Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------: |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       | `83.511 kB`<br />`20.921 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |  `36.119 kB`<br />`9.647 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `43.144 kB`<br />`10.86 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        | `51.888 kB`<br />`11.127 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                | `67.002 kB`<br />`19.261 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          | `62.684 kB`<br />`18.177 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |   `8.561 kB`<br />`3.601 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `9.604 kB`<br />`3.94 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |   `8.662 kB`<br />`3.656 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `187.939 kB`<br />`52.05 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            | `33.359 kB`<br />`11.004 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |   `5.851 kB`<br />`1.964 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/e0a0ab1481d0fb64f2a9804376ad17e4f4f8ea01'>e0a0ab1481d0fb64f2a9804376ad17e4f4f8ea01</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/Avatar-mount_base.html">1292</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/Avatar-mount.html">1295</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/Button-mount_base.html">960</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/Button-mount.html">956</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/FluentProvider-mount_base.html">1598</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/FluentProvider-mount.html">1578</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/FluentProviderWithTheme-mount_base.html">627</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/FluentProviderWithTheme-mount.html">634</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">594</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">599</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">639</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">637</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/MakeStyles-mount_base.html">1897</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/MakeStyles-mount.html">1905</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/SpinButton-mount_base.html">2554</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24782/perf-test-react-components/SpinButton-mount.html">2489</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-button/src/components/MenuButton/useMenuButton.tsx [hunk 1]
```diff
@@ -26,6 +27,10 @@ export const useMenuButton_unstable = (
       menuIcon: 'span',
     },
 
+    root: {
+      ...buttonState.root,
+      'aria-expanded': props['aria-expanded'] ?? false,
+    },
```
Comment (behowell) [inline packages/react-components/react-button/src/components/MenuButton/useMenuButton.tsx:33]: Could you assign `buttonState.root['aria-expanded'] ??= false` above, instead of doing a spread here?

**Review by behowell — APPROVED** [review]
