### PR TITLE
fix(react): No pointer events on focus ring

### LINKED ISSUE #20608: When Split button has focus, can't use mouse to choose the dropdown
### Environment Information

- **Package version(s)**: 8.41.4
- **Browser and OS versions**: Chrome and Edge on Windows 10

### Please provide a reproduction of the bug in a codepen:

https://developer.microsoft.com/en-us/fluentui#/controls/web/button

Scroll down to the "Split Button" examples. Click "Primary" to get the focus there. Then Shift+Tab to move focus to "Standard". Now, with the mouse, attempt to click on the down/chevron to pop open the menu. Notice how the button is pressed but the menu won't pop open.

#### Actual behavior:

Clicking with mouse on the down/chevron causes default button behavior to happen.

#### Expected behavior:

Should always be able to click on the down/chevron regardless of whether the split button has the focus.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

### Notes

I am going to have to abandon usage of the split button because of this. I put the default focus there so the user can quickly click Enter to make the action happen. But I want the user to be able to choose the alternate options from the split. Using Alt+Downarrow works but many people won't know about this. I expect users to use the mouse but there is no way to make the split open unless the button does NOT have the focus.

### PR DESCRIPTION
**Pull request by miroslavstastny**
## Current Behavior

`SplitButton` renders two `button` elements inside a `div`:
```html
div
  button
  button
```

When the `SplitButton` is focused, `:after` pseudoelement is added to the wrapping `div` to display a focus ring around both buttons - this now captures all the events:
- when hovered, arrow mouse cursor is used instead of the pointer
- it is not possible to click the secondary button

## New Behavior

I've added `pointer-events: none` to the focus styles so that it passes through all the mouse events.

For `SplitButton`, that means that when it is focused:
- the focus ring is displayed as before
- user can press Enter or Space to press the primary button (as before)
- user can press Alt/Option + Down Arrow to open the Menu (as before)
- user can click primary button (as before)
- user can click the secondary button (fix)
- correct pointer cursor is used when hovering on either primary or secondary button (fix)

## Related Issue(s)

Fixes #20608

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/443c503b94e602e55857e4e311413c6257d60766'>443c503b94e602e55857e4e311413c6257d60766</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/BaseButton-mount_base.html">1193</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/BaseButton-mount.html">1195</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Breadcrumb-mount_base.html">2790</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Breadcrumb-mount.html">2800</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Checkbox-mount_base.html">2651</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Checkbox-mount.html">2637</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/CheckboxBase-mount_base.html">2355</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/CheckboxBase-mount.html">2367</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ChoiceGroup-mount_base.html">4239</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ChoiceGroup-mount.html">4239</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ComboBox-mount_base.html">1176</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ComboBox-mount.html">1182</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/CommandBar-mount_base.html">9259</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/CommandBar-mount.html">9303</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ContextualMenu-mount_base.html">10064</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ContextualMenu-mount.html">10164</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DefaultButton-mount_base.html">1364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DefaultButton-mount.html">1383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DetailsRow-mount_base.html">3399</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DetailsRow-mount.html">3459</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DetailsRowFast-mount_base.html">3403</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DetailsRowFast-mount.html">3372</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DetailsRowNoStyles-mount_base.html">3202</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DetailsRowNoStyles-mount.html">3314</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Dialog-mount_base.html">2937</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Dialog-mount.html">2927</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DocumentCardTitle-mount_base.html">576</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/DocumentCardTitle-mount.html">575</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Dropdown-mount_base.html">3144</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Dropdown-mount.html">3171</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/FocusTrapZone-mount_base.html">1974</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/FocusTrapZone-mount.html">1976</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/FocusZone-mount_base.html">1894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/FocusZone-mount.html">1961</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedList-mount_base.html">48386</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedList-mount.html">52935</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedList-virtual-rerender_base.html">23366</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedList-virtual-rerender.html">22955</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">82904</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedList-virtual-rerender-with-unmount.html">82025</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedListV2-mount_base.html">564</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedListV2-mount.html">554</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedListV2-virtual-rerender_base.html">531</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedListV2-virtual-rerender.html">528</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">554</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">555</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/IconButton-mount_base.html">1773</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/IconButton-mount.html">1772</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Label-mount_base.html">766</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Label-mount.html">765</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Layer-mount_base.html">4158</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Layer-mount.html">4109</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Link-mount_base.html">844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Link-mount.html">861</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/MenuButton-mount_base.html">1604</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/MenuButton-mount.html">1605</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/MessageBar-mount_base.html">2368</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/MessageBar-mount.html">2412</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Nav-mount_base.html">3128</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Nav-mount.html">3038</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/OverflowSet-mount_base.html">1448</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/OverflowSet-mount.html">1419</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Panel-mount_base.html">2515</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Panel-mount.html">2483</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Persona-mount_base.html">1286</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Persona-mount.html">1267</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Pivot-mount_base.html">1535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Pivot-mount.html">1542</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/PrimaryButton-mount_base.html">1502</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/PrimaryButton-mount.html">1521</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Rating-mount_base.html">7011</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Rating-mount.html">6961</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/SearchBox-mount_base.html">1498</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/SearchBox-mount.html">1481</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Shimmer-mount_base.html">2921</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Shimmer-mount.html">2921</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Slider-mount_base.html">2115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Slider-mount.html">2128</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/SpinButton-mount_base.html">4320</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/SpinButton-mount.html">4311</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Spinner-mount_base.html">833</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Spinner-mount.html">823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/SplitButton-mount_base.html">2856</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/SplitButton-mount.html">2882</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Stack-mount_base.html">916</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Stack-mount.html">896</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/StackWithIntrinsicChildren-mount_base.html">2251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/StackWithIntrinsicChildren-mount.html">2205</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/StackWithTextChildren-mount_base.html">4917</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/StackWithTextChildren-mount.html">4924</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/SwatchColorPicker-mount_base.html">9473</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/SwatchColorPicker-mount.html">10414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/TagPicker-mount_base.html">2361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/TagPicker-mount.html">2392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/TeachingBubble-mount_base.html">74633</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/TeachingBubble-mount.html">76194</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Text-mount_base.html">807</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Text-mount.html">813</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/TextField-mount_base.html">1548</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/TextField-mount.html">1550</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ThemeProvider-mount_base.html">1450</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ThemeProvider-mount.html">1444</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ThemeProvider-virtual-rerender_base.html">1156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ThemeProvider-virtual-rerender.html">1136</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1985</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1995</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Toggle-mount_base.html">1115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/Toggle-mount.html">1136</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/buttonNative-mount_base.html">540</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25088/perf-test/buttonNative-mount.html">531</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: packages/style-utilities/src/styles/getFocusStyle.ts [hunk 1]
```diff
@@ -92,6 +93,7 @@ function _getFocusStyleInternal(theme: ITheme, options: IGetFocusStylesOptions =
       [`.${IsFocusVisibleClassName} &${isFocusedOnly ? ':focus' : ''}:after`]: {
         content: '""',
         position: 'absolute',
+        pointerEvents,
```
Comment (miroslavstastny) [inline packages/style-utilities/src/styles/getFocusStyle.ts:96]: I originally set `pointerEvents: none` here, similar to `getInputFocusStyle()` function in the same file.
Even though that should be intended and not break anything, it affects a lot of components in the whole library.
For that reason I decided to go the safer path making the `pointerEvents` configurable and set them to `none` only in the `SplitButton`.

File: packages/style-utilities/src/interfaces/IGetFocusStyles.ts [hunk 2]
```diff
@@ -47,4 +47,10 @@ export interface IGetFocusStylesOptions {
    * If the style should include a rounded border.
    */
   borderRadius?: string | number | undefined;
+
+  /**
+   * If default pointer events should be overriden.
```
Comment (dzearing) [inline packages/style-utilities/src/interfaces/IGetFocusStyles.ts:52]:
```suggestion
   * If default pointer events should be overridden.
```

**Review by dzearing — APPROVED** [review]

**Comment by fabricteam** [comment]
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 4 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25088&commitId=b714f3a24a7d0ca28ce2acecaf8eaac6af9950e9&env=prod)

✅ There was 4 screenshots added, 0 screenshots removed, 1041 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Added|

</details>


<div id="vrtCommentfluentuiv8"/>

**Review by khmakoto — APPROVED** [review]
