### PR TITLE
 Fix website and legacy demo in IE 11

### LINKED ISSUE #19222: Website and demos broken in IE 11
Webpack 5 upgrade broke our demos and website in IE 11. This is because it switched to emitting ES6 (lambdas etc) by default for smaller bundle sizes.

### PR DESCRIPTION
**Pull request by ecraig12345**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #19222
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Webpack 5 started using ES6 syntax in its output by default for smaller bundle sizes, which breaks IE 11. Fix is to add a `target` option [as mentioned in the migration guide](https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11).

I also updated `webpack-dev-server` to `4.0.0-rc.0` because the previous version used `Symbol` (not supported in IE 11), and updated `webpack-cli` to work around another issue.

Unfortunately there's still a manual workaround required for local testing in IE 11: apparently something changed in `webpack-dev-server` version 4 such that it exceeds [IE 11's limit of 6 open web socket connections](https://stackoverflow.com/questions/52549799/securityerror-on-ie11-when-initializing-websocket). I could potentially dig into this more, but since debugging local changes in IE 11 is not very common at this point, a manual workaround to edit the registry setting (mentioned in that link) may be acceptable. Save the following into a `.reg` file and run it:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WEBSOCKET_MAXCONNECTIONSPERSERVER]
"iexplore.exe"=dword:00000012


```

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |   `78.506 kB`<br />`23.21 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `54.242 kB`<br />`14.662 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `24.343 kB`<br />`7.165 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `27.156 kB`<br />`7.851 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenseBadge</abbr>                                                                       |          `237 B`<br />`177 B` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `24.934 kB`<br />`8.001 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `30.226 kB`<br />`8.878 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `26.521 kB`<br />`8.509 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `34.531 kB`<br />`8.637 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `179.799 kB`<br />`50.935 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `36.237 kB`<br />`11.596 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `15.889 kB`<br />`5.747 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |   `10.642 kB`<br />`4.264 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `9.397 kB`<br />`3.839 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `14.715 kB`<br />`6.012 kB` |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStaticStyles-runtime.fixture.js'>makeStaticStyles (runtime)</abbr>                                         |     `7.59 kB`<br />`3.321 kB` |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStyles-runtime.fixture.js'>makeStyles + mergeClasses (runtime)</abbr>                                      |   `22.135 kB`<br />`8.356 kB` |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStyles.fixture.js'>makeStyles + mergeClasses (build time)</abbr>                                           |    `2.557 kB`<br />`1.202 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          |  `114.61 kB`<br />`34.554 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             |  `116.71 kB`<br />`34.824 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `124.181 kB`<br />`36.121 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |     `7.78 kB`<br />`2.672 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePopper</abbr>                                                                         |   `23.157 kB`<br />`7.942 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `16.235 kB`<br />`5.972 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                                                                  |   `32.941 kB`<br />`6.674 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                                                                |   `20.247 kB`<br />`5.662 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |   `45.281 kB`<br />`15.45 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                                                                       |          `213 B`<br />`170 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/c55f2388771a2e169c5f8cf0a1f1441e6ef28d15'>c55f2388771a2e169c5f8cf0a1f1441e6ef28d15</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Avatar-mount_base.html">841</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Avatar-mount.html">881</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/BaseButton-mount_base.html">969</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/BaseButton-mount.html">975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Breadcrumb-mount_base.html">2768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Breadcrumb-mount.html">2684</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ButtonNext-mount_base.html">469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ButtonNext-mount.html">463</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Checkbox-mount_base.html">1674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Checkbox-mount.html">1694</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/CheckboxBase-mount_base.html">1399</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/CheckboxBase-mount.html">1392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ChoiceGroup-mount_base.html">5099</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ChoiceGroup-mount.html">5114</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ComboBox-mount_base.html">1048</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ComboBox-mount.html">1057</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/CommandBar-mount_base.html">10399</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/CommandBar-mount.html">10487</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ContextualMenu-mount_base.html">6419</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ContextualMenu-mount.html">6442</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DefaultButton-mount_base.html">1209</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DefaultButton-mount.html">1225</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DetailsRow-mount_base.html">3873</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DetailsRow-mount.html">3948</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DetailsRowFast-mount_base.html">4022</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DetailsRowFast-mount.html">4009</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DetailsRowNoStyles-mount_base.html">3665</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DetailsRowNoStyles-mount.html">3745</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Dialog-mount_base.html">2264</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Dialog-mount.html">2227</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DocumentCardTitle-mount_base.html">139</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/DocumentCardTitle-mount.html">164</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Dropdown-mount_base.html">3466</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Dropdown-mount.html">3485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/FluentProviderNext-mount_base.html">7035</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/FluentProviderNext-mount.html">7054</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/FocusTrapZone-mount_base.html">1829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/FocusTrapZone-mount.html">1856</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/FocusZone-mount_base.html">1902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/FocusZone-mount.html">1839</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/IconButton-mount_base.html">1906</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/IconButton-mount.html">1873</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Label-mount_base.html">378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Label-mount.html">352</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Layer-mount_base.html">1853</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Layer-mount.html">1860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Link-mount_base.html">476</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Link-mount.html">466</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/MakeStyles-mount_base.html">1774</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/MakeStyles-mount.html">1757</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/MenuButton-mount_base.html">1586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/MenuButton-mount.html">1587</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/MessageBar-mount_base.html">2120</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/MessageBar-mount.html">2120</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Nav-mount_base.html">3463</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Nav-mount.html">3428</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/OverflowSet-mount_base.html">1083</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/OverflowSet-mount.html">1126</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Panel-mount_base.html">2163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Panel-mount.html">2173</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Persona-mount_base.html">855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Persona-mount.html">875</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Pivot-mount_base.html">1401</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Pivot-mount.html">1472</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/PrimaryButton-mount_base.html">1361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/PrimaryButton-mount.html">1386</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Rating-mount_base.html">8440</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Rating-mount.html">8315</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/SearchBox-mount_base.html">1535</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/SearchBox-mount.html">1440</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Shimmer-mount_base.html">2666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Shimmer-mount.html">2694</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Slider-mount_base.html">2094</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Slider-mount.html">2057</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/SpinButton-mount_base.html">5334</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/SpinButton-mount.html">5285</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Spinner-mount_base.html">435</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Spinner-mount.html">420</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/SplitButton-mount_base.html">3269</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/SplitButton-mount.html">3344</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Stack-mount_base.html">533</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Stack-mount.html">523</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/StackWithIntrinsicChildren-mount_base.html">1687</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/StackWithIntrinsicChildren-mount.html">1715</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/StackWithTextChildren-mount_base.html">5080</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/StackWithTextChildren-mount.html">5014</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/SwatchColorPicker-mount_base.html">10816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/SwatchColorPicker-mount.html">10684</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Tabs-mount_base.html">1447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Tabs-mount.html">1473</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/TagPicker-mount_base.html">2808</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/TagPicker-mount.html">2850</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/TeachingBubble-mount_base.html">12073</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/TeachingBubble-mount.html">12035</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Text-mount_base.html">449</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Text-mount.html">435</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/TextField-mount_base.html">1486</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/TextField-mount.html">1467</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ThemeProvider-mount_base.html">1218</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ThemeProvider-mount.html">1219</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ThemeProvider-virtual-rerender_base.html">622</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/ThemeProvider-virtual-rerender.html">610</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Toggle-mount_base.html">908</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/Toggle-mount.html">823</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/buttonNative-mount_base.html">119</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test/buttonNative-mount.html">113</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
TreeWith60ListItems.default | [192](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TreeWith60ListItems.default.html) | [166](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.16:1
LabelMinimalPerf.default | [439](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/LabelMinimalPerf.default.html) | [396](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.11:1
BoxMinimalPerf.default | [393](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/BoxMinimalPerf.default.html) | [356](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.1:1
ButtonMinimalPerf.default | [187](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ButtonMinimalPerf.default.html) | [173](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.08:1
TextMinimalPerf.default | [383](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TextMinimalPerf.default.html) | [356](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.08:1
ImageMinimalPerf.default | [422](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ImageMinimalPerf.default.html) | [393](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.07:1
DialogMinimalPerf.default | [827](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DialogMinimalPerf.default.html) | [781](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.06:1
FormMinimalPerf.default | [474](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/FormMinimalPerf.default.html) | [449](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.06:1
SkeletonMinimalPerf.default | [394](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/SkeletonMinimalPerf.default.html) | [370](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.06:1
AttachmentMinimalPerf.default | [175](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AttachmentMinimalPerf.default.html) | [167](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.05:1
ChatDuplicateMessagesPerf.default | [331](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [314](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.05:1
HeaderSlotsPerf.default | [857](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/HeaderSlotsPerf.default.html) | [819](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.05:1
PortalMinimalPerf.default | [184](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/PortalMinimalPerf.default.html) | [176](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.05:1
RefMinimalPerf.default | [238](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/RefMinimalPerf.default.html) | [226](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.05:1
SegmentMinimalPerf.default | [388](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/SegmentMinimalPerf.default.html) | [371](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.05:1
StatusMinimalPerf.default | [752](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/StatusMinimalPerf.default.html) | [719](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.05:1
FlexMinimalPerf.default | [310](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/FlexMinimalPerf.default.html) | [298](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.04:1
ListWith60ListItems.default | [705](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ListWith60ListItems.default.html) | [681](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.04:1
LoaderMinimalPerf.default | [716](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/LoaderMinimalPerf.default.html) | [691](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.04:1
AnimationMinimalPerf.default | [452](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AnimationMinimalPerf.default.html) | [437](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.03:1
ButtonSlotsPerf.default | [608](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ButtonSlotsPerf.default.html) | [588](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.03:1
EmbedMinimalPerf.default | [4358](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/EmbedMinimalPerf.default.html) | [4238](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.03:1
LayoutMinimalPerf.default | [395](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/LayoutMinimalPerf.default.html) | [384](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.03:1
MenuMinimalPerf.default | [924](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/MenuMinimalPerf.default.html) | [898](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.03:1
ReactionMinimalPerf.default | [410](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ReactionMinimalPerf.default.html) | [397](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.03:1
TreeMinimalPerf.default | [865](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TreeMinimalPerf.default.html) | [836](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.03:1
CardMinimalPerf.default | [610](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/CardMinimalPerf.default.html) | [600](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.02:1
CarouselMinimalPerf.default | [499](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/CarouselMinimalPerf.default.html) | [487](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.02:1
ListNestedPerf.default | [592](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ListNestedPerf.default.html) | [579](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ListNestedPerf.default_base.html) | 1.02:1
RosterPerf.default | [1339](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/RosterPerf.default.html) | [1315](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/RosterPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [2080](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TableManyItemsPerf.default.html) | [2030](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
TableMinimalPerf.default | [434](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TableMinimalPerf.default.html) | [427](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.02:1
VideoMinimalPerf.default | [677](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/VideoMinimalPerf.default.html) | [663](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.02:1
AttachmentSlotsPerf.default | [1155](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1142](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.01:1
ChatWithPopoverPerf.default | [389](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ChatWithPopoverPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [3163](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DropdownMinimalPerf.default.html) | [3144](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
GridMinimalPerf.default | [367](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/GridMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [1306](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/InputMinimalPerf.default.html) | [1296](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
ItemLayoutMinimalPerf.default | [1316](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1301](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.01:1
PopupMinimalPerf.default | [603](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/PopupMinimalPerf.default.html) | [595](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.01:1
RadioGroupMinimalPerf.default | [487](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [481](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1805](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1805](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
ChatMinimalPerf.default | [716](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ChatMinimalPerf.default.html) | [716](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1:1
CheckboxMinimalPerf.default | [2849](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2844](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [5729](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5738](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
DividerMinimalPerf.default | [374](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DividerMinimalPerf.default.html) | [375](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1:1
ListMinimalPerf.default | [546](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ListMinimalPerf.default.html) | [544](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
ProviderMergeThemesPerf.default | [1637](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1643](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1613](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/SliderMinimalPerf.default.html) | [1614](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [4014](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3998](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
TooltipMinimalPerf.default | [1088](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TooltipMinimalPerf.default.html) | [1084](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1:1
AlertMinimalPerf.default | [308](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AlertMinimalPerf.default.html) | [312](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AlertMinimalPerf.default_base.html) | 0.99:1
DropdownManyItemsPerf.default | [734](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DropdownManyItemsPerf.default.html) | [741](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.99:1
ListCommonPerf.default | [691](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ListCommonPerf.default.html) | [699](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ListCommonPerf.default_base.html) | 0.99:1
CustomToolbarPrototype.default | [3942](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/CustomToolbarPrototype.default.html) | [3984](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 0.99:1
AccordionMinimalPerf.default | [158](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AccordionMinimalPerf.default.html) | [162](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.98:1
ProviderMinimalPerf.default | [1052](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ProviderMinimalPerf.default.html) | [1069](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.98:1
TextAreaMinimalPerf.default | [538](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TextAreaMinimalPerf.default.html) | [549](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.98:1
ToolbarMinimalPerf.default | [980](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ToolbarMinimalPerf.default.html) | [997](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 0.98:1
MenuButtonMinimalPerf.default | [1717](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1777](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.97:1
IconMinimalPerf.default | [644](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/IconMinimalPerf.default.html) | [667](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.97:1
AvatarMinimalPerf.default | [200](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AvatarMinimalPerf.default.html) | [209](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.96:1
HeaderMinimalPerf.default | [379](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/HeaderMinimalPerf.default.html) | [404](https://fluentuipr.z22.web.core.windows.net/pull/19237/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.94:1

</details><div id="perfComment9423"/>

File: apps/test-bundles/webpackUtils.js [hunk 1]
```diff
@@ -69,6 +70,11 @@ function createWebpackConfig(entries) {
       true,
       true,
     )[0];
+    if (packageName === '@fluentui/react-northstar') {
+      // This is used most of the configs for IE 11 compat, which northstar doesn't need
+      delete config.target;
+    }
```
Comment (behowell) [inline apps/test-bundles/webpackUtils.js:76]: This seems a little hacky and potentially confusing if someone tries to add a `target` to northstar in the future, or if we want to configure other packages like react-components?
I'm not familiar with how this config works, but would it be possible for each package that needs ie11 compat to explicitly provide the `target` (e.g. perhaps with a public constant, `target: ie11CompatTarget`).

Feel free to ignore this comment if I'm misunderstanding how this config works -- I haven't read the code to understand how it all works.

Comment (ecraig12345) [reply apps/test-bundles/webpackUtils.js:76]: This config is only used for generating the bundles analyzed by size auditor (which we're about to move away from anyway). So I don't think it's a concern.

**Comment by ecraig12345** [comment]
Note that the size auditor changes are expected (due to the test bundles using `function` instead of lambdas) and shouldn't reflect an increase in real-world bundle size.

**Comment by behowell** [comment]
> Unfortunately there's still a manual workaround required for local testing in IE 11: apparently something changed in `webpack-dev-server` version 4 such that it exceeds [IE 11's limit of 6 open web socket connections](https://stackoverflow.com/questions/52549799/securityerror-on-ie11-when-initializing-websocket). I could potentially dig into this more, but since debugging local changes in IE 11 is not very common at this point, a manual workaround to edit the registry setting (mentioned in that link) may be acceptable. Save the following into a `.reg` file and run it:

Could this be captured in a wiki article for debugging IE11?

**Comment by ecraig12345** [comment]
> > Unfortunately there's still a manual workaround required for local testing in IE 11: apparently something changed in `webpack-dev-server` version 4 such that it exceeds [IE 11's limit of 6 open web socket connections](https://stackoverflow.com/questions/52549799/securityerror-on-ie11-when-initializing-websocket). I could potentially dig into this more, but since debugging local changes in IE 11 is not very common at this point, a manual workaround to edit the registry setting (mentioned in that link) may be acceptable. Save the following into a `.reg` file and run it:
> 
> Could this be captured in a wiki article for debugging IE11?

Good point, I put it on the browser support page for now but could make a separate page if desired. https://github.com/microsoft/fluentui/wiki/Browser-Support#testing-fluentuireact-version-8-in-ie-11

File: apps/test-bundles/webpackUtils.js [hunk 2]
```diff
@@ -29,7 +30,7 @@ function createWebpackConfig(entries) {
           modules: true,
 
           builtAt: false,
-          outputPath: false,
+          .../** @type {*} */ ({ outputPath: false }),
```
Comment (Hotell) [inline apps/test-bundles/webpackUtils.js:33]: - can we use `any` rather than `*` ( which is the same in JSDoc context )
- why is this needed ? to allow proper assignment which is not valid from type perspective ? if that's the case we probably should assert whole assignment

File: apps/test-bundles/webpackUtils.js (hunk 1 above)
Comment (Hotell) [reply apps/test-bundles/webpackUtils.js:76]: @behowell  vNext is not supporting ie11 nor will use these  webpack configs

**Review by Hotell — APPROVED** [review]

File: apps/test-bundles/webpackUtils.js (hunk 2 above)
Comment (ecraig12345) [reply apps/test-bundles/webpackUtils.js:33]: I'm actually not sure if `outputPath` is a valid option here--probably either it was valid in a previous version but isn't now, or is undocumented/missing from types. I was just changing the types to get rid of a warning in the editor and didn't want to dig into the actual options used. (All the other options appear to be valid, hence not casting the whole thing.)

Comment (ecraig12345) [reply apps/test-bundles/webpackUtils.js:33]: Okay looks like `outputPath` is a valid option, just missing from `webpack-bundle-analyzer`'s types. https://webpack.js.org/configuration/stats/#statsoutputpath
