### PR TITLE
fix(react-combobox): Remove _getAriaActiveDescendantValue, compute aria-activedescendantvalue in state, and update currentPendingValue when the options change

### LINKED ISSUE #25932: [Bug]: Crash in Combobox when allowFreeform true and options are changed
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Commit 3c754611eccb854647820ce5b5fd8b5f6b0cf1c0 introduced a bug causing a crash in the ComboBox component when allowFreeform is set to true, and the user of the Combobox is asynchronously filtering/populating the ComboBox options using the user input.


Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at ComboBoxInternal._getAriaActiveDescendantValue (ComboBox.tsx:2368:1)
    at ComboBoxInternal._this._renderComboBoxWrapper (ComboBox.tsx:624:1)
    at ComboBoxInternal.render
```

I have added on comment on the MR that introduced the crash: https://github.com/microsoft/fluentui/commit/3c754611eccb854647820ce5b5fd8b5f6b0cf1c0#r92388055

The line to blame is

```
descendantText = options[currentPendingValueValidIndex].id ?? this._id + '-list' + currentPendingValueValidIndex;

`currentPendingValueValidIndex` is checked to see if it is -1, but not checked to ensure it is within the bounds of the options array.  As a consequence, if the options are changed after `_processInputChangeWithFreeform` has executed, such that `currentPendingValueValidIndex` is greater than the length of the options array, the component will crash.
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/react-fiddle-forked-yujk10?file=/src/index.tsx

## Actual Behavior
If options are changed based on the ComboBox text, ComboBox crashes.

## Expected Behavior
ComboBox shouldn't crash

### Logs

```shell
TypeError
options[currentPendingValueValidIndex] is undefined
$csb$eval/ComboBoxInternal.prototype._getAriaActiveDescendantValue@https://yujk10.csb.app/node_modules/
fluentui/react/lib-commonjs/components/ComboBox/ComboBox.js:1689:13
ComboBoxInternal/_this._renderComboBoxWrapper@https://yujk10.csb.app/node_modules/
fluentui/react/lib-commonjs/components/ComboBox/ComboBox.js:202:877
$csb$eval/ComboBoxInternal.prototype.render@https://yujk10.csb.app/node_modules/
fluentui/react/lib-commonjs/components/ComboBox/ComboBox.js:942:36
finishClassComponent
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17485:31
updateClassComponent
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17435:44
beginWork
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19073:16
callCallback
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3945:14
invokeGuardedCallbackDev
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3994:16
invokeGuardedCallback
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4056:31
beginWork$1
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23964:28
performUnitOfWork
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22776:12
workLoopSync
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22707:22
renderRootSync
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22670:7
performSyncWorkOnRoot
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22293:18
flushSyncCallbackQueueImpl/<
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11327:26
unstable_runWithPriority
https://yujk10.csb.app/node_modules/scheduler/cjs/scheduler.development.js:468:12
runWithPriority$1
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11276:10
flushSyncCallbackQueueImpl
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11322:26
flushSyncCallbackQueue
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11309:3
flushPassiveEffectsImpl
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23620:3
unstable_runWithPriority
https://yujk10.csb.app/node_modules/scheduler/cjs/scheduler.development.js:468:12
runWithPriority$1
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11276:10
flushPassiveEffects
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23447:14
flushDiscreteUpdates
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22356:3
finishEventHandler
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3714:5
batchedEventUpdates
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3748:5
dispatchEventForPluginEventSystem
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:8507:22
attemptToDispatchEvent
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:6005:36
dispatchEvent
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:5924:41
unstable_runWithPriority
https://yujk10.csb.app/node_modules/scheduler/cjs/scheduler.development.js:468:12
runWithPriority$1
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11276:10
discreteUpdates$1
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22413:14
discreteUpdates
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3756:12
dispatchDiscreteEvent
https://yujk10.csb.app/node_modules/react-dom/cjs/react-dom.development.js:5889:18
```

### Requested priority

Blocking

### Products/sites affected

Meetingflow.com

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by sopranopillow**
## Previous Behavior

When the options of a combobox are filtered, `_getAriaActiveDescendantValue` will break the runtime since the `currentPendingValueValidIndex` is not updated to the latest options.

## New Behavior

`_getAriaActiveDescendantValue` now checks if the `currentPendingValueValidIndex` is not out of bounds and if the selected value is correct. If that's not the case, the value is updated to match the latest options.

## Related Issue(s)

* Fixes #25932

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/77ceacdb9b546c5ca4bc223de24b2ad227f14875'>77ceacdb9b546c5ca4bc223de24b2ad227f14875</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -2367,8 +2371,25 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
...
+    // change.
+    if (
+      currentPendingValue &&
+      (currentPendingValueValidIndex >= options.length ||
+        options[currentPendingValueValidIndex].text.indexOf(currentPendingValue) < 0)
+    ) {
+      currentPendingValueValidIndex =
+        this.props.allowFreeform || this.props.allowFreeInput
+          ? this._processInputChangeWithFreeform(currentPendingValue)
+          : this._processInputChangeWithoutFreeform(currentPendingValue);
```
Comment (sopranopillow) [inline packages/react/src/components/ComboBox/ComboBox.tsx:2390]: Having these functions here is an issue, since we are updating the state in the render function. One possible solution could be to add `aria-activedescendant` to the state and update its value in `componentDidUpdate` that way we could also update based on the options changing.

@smhigley and @khmakoto what do you think?

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

File: change/@fluentui-react-12283c65-5330-4f04-9ce2-532900d9be76.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (fabricteam) [inline change/@fluentui-react-12283c65-5330-4f04-9ce2-532900d9be76.json:1]: ## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 5 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26574&commitId=a96140d4aa54f4112a260ee6ffbbd78a1eea3a7e&env=prod)

✅ There was 0 screenshots added, 5 screenshots removed, 1040 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 5 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Image.Maximize frame, landscape container.default.chromium.png|0| Removed|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

File: change/@fluentui-react-12283c65-5330-4f04-9ce2-532900d9be76.json (hunk 2 above)
Comment (fabricteam) [inline change/@fluentui-react-12283c65-5330-4f04-9ce2-532900d9be76.json:1]: ## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26574&commitId=aed287105f5e3b90ed2688bfddf80a165deac62a&env=prod)

✅ There was 0 screenshots added, 2 screenshots removed, 1043 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 3]
```diff
@@ -347,9 +353,9 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
       text,
       onMenuOpen,
       onMenuDismissed,
-      hoisted: { selectedIndices },
+      hoisted: { selectedIndices, currentOptions },
```
Comment (khmakoto) [inline packages/react/src/components/ComboBox/ComboBox.tsx:356]: _nit:_

```suggestion
      hoisted: { currentOptions, selectedIndices },
```

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 4]
```diff
@@ -347,9 +353,9 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
...
     } = this.props;
-    const { isOpen, currentPendingValueValidIndex } = this.state;
+    const { isOpen, currentPendingValueValidIndex, currentPendingValue } = this.state;
```
Comment (khmakoto) [inline packages/react/src/components/ComboBox/ComboBox.tsx:358]: _nit:_

```suggestion
    const { currentPendingValue, currentPendingValueValidIndex, isOpen } = this.state;
```

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 5]
```diff
@@ -579,7 +614,7 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
       hoisted: { suggestedDisplayValue },
     } = this.props;
 
-    const { isOpen } = this.state;
+    const { isOpen, ariaActiveDescendantValue } = this.state;
```
Comment (khmakoto) [inline packages/react/src/components/ComboBox/ComboBox.tsx:617]: _nit:_

```suggestion
    const { ariaActiveDescendantValue, isOpen } = this.state;
```

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 6]
```diff
@@ -404,6 +410,35 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
...
+    let descendantText = undefined;
+
+    if (isOpen && selectedIndices.length) {
+      descendantText = options[selectedIndices[0]]?.id ?? this._id + '-list' + selectedIndices[0];
+    } else if (isOpen && this._hasFocus() && newCurrentPendingValueValidIndex !== -1) {
+      descendantText =
+        options[newCurrentPendingValueValidIndex].id ?? this._id + '-list' + newCurrentPendingValueValidIndex;
+    } else {
+      descendantText = undefined;
+    }
```
Comment (khmakoto) [inline packages/react/src/components/ComboBox/ComboBox.tsx:435]: You don't need this `else` statement since you're already setting `descendantText` to `undefined`.

```suggestion
    }
```

**Review by khmakoto — APPROVED** [review]

**Review by smhigley — APPROVED** [review]

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 7]
```diff
@@ -913,7 +951,7 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
         this._autoCompleteTimeout = this._async.setTimeout(() => {
           this._autoCompleteTimeout = undefined;
         }, ReadOnlyPendingAutoCompleteTimeout);
-        return;
+        return items[0].index;
```
[the remark this answers is not in the document]
Comment (smhigley) [reply packages/react/src/components/ComboBox/ComboBox.tsx]: oops ignore this, I went to approve, and it looks like github saved an old comment I'd started from before the most recent changes :P

**Comment by ivywei0125** [comment]
Hi @sopranopillow , I'm using "8.13.19" and I met the same issue about this `currentPendingValueValidIndex`
https://github.com/microsoft/fluentui/issues/25932
From **which version**, this fix is merged?
