### PR TITLE
fix(Calendar): aria-label format to day, month, year

### LINKED ISSUE #16072: Calendar should announce the date in the order day, month, year (most specific information first).
Calendar lists the month first in the aria-label for the days in the grid. This means that as a user navigates around the grid they hear the month over and over again. e.g. November 25th 2020, November 18th 2020, November 11th 2020. This requires the user to wait until the long month is announced before knowing what the date is. 

#### Actual behavior:

Currently Calendar has the aria-label attribute in this format: `aria-label="November 25, 2020"`. 

#### Expected behavior:

Calendar should have the aria-label attribute in this format: `aria-label="25 November 2020"`. day -> month -> year

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

### PR DESCRIPTION
**Pull request by tringakrasniqi**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #16072 
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Changed the ariaLabel creation from using the dateTimeFormatter to a static string that is formed in this way: [day], [month], [year].

#### Focus areas to test

Aria lables of the calendar component

### CODE REVIEW

File: packages/react/src/components/CalendarDayGrid/CalendarGridDayCell.tsx [hunk 1]
```diff
@@ -207,7 +207,13 @@ export const CalendarGridDayCell: React.FunctionComponent<ICalendarGridDayCellPr
     }
   };
 
-  let ariaLabel = dateTimeFormatter.formatMonthDayYear(day.originalDate, strings);
+  let ariaLabel =
+    day.originalDate.getDate() +
+    ',' +
```
Comment (khmakoto) [inline packages/react/src/components/CalendarDayGrid/CalendarGridDayCell.tsx:212]: nit:

```suggestion
    ', ' +
```

File: packages/react/src/components/CalendarDayGrid/CalendarGridDayCell.tsx [hunk 2]
```diff
@@ -207,7 +207,13 @@ export const CalendarGridDayCell: React.FunctionComponent<ICalendarGridDayCellPr
...
+    strings.months[day.originalDate.getMonth()] +
+    ',' +
```
Comment (khmakoto) [inline packages/react/src/components/CalendarDayGrid/CalendarGridDayCell.tsx:214]: nit:
```suggestion
    ', ' +
```

**Review by khmakoto — APPROVED** [review]
Left some very very minor comments but otherwise looks good. Thanks for doing this!

**Review by lorejoh12 — APPROVED** [review]
