### PR TITLE
Virtualized datagrid columns overflowing

### LINKED ISSUE #27737: [Bug]: DataGrid with virtualization and resizable columns always shows horizontal scrollbar when vertical scrollbar is visible
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.64)

"@fluentui/react-components": "^9.18.9",
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/async-breeze-ocq66p?file=/example.tsx

## Actual Behavior

The above code sandbox link is based on the example here, with `resizableColumns` added: https://react.fluentui.dev/iframe.html?viewMode=docs&id=components-datagrid--default#virtualization

In codesandbox, ensure that there is sufficient horizontal space for all colums (i.e. increase the browser panel size). Even though all columns fit into the horizontal space, a horizontal scrollbar appears.

Notes: 

- In Firefox, this is not an issue because vertical scrollbars seem to be overlayed without changing the available size for the `DataGrid`; use Edge or Chrome to reproduce the issue.

## Expected Behavior

There should be no horizontal scrollbar.

### Logs

```shell
N/A
```

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by george-cz**
## Previous Behavior

Previously the width of the scrollbar wasn't subtracted from the available space for column resizing, resulting in columns in total being wider than its container and scrollbar showing up.

Screenshot 2023-05-24 at 15 19 45

## New Behavior

The width of the scrollbar is now subtracted, fixing the issue with vertical scrollbar always being present

## Related Issue(s)

- Fixes #27737

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8ec648d4060906a32bad46a16e0eae13a7aa5959'>8ec648d4060906a32bad46a16e0eae13a7aa5959</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-components/react-data-grid-react-window/src/components/DataGrid/DataGrid.tsx [hunk 1]
```diff
@@ -4,12 +4,24 @@ import {
...
 } from '@fluentui/react-table';
 import type { DataGridProps } from '@fluentui/react-table';
-import type { ForwardRefComponent } from '@fluentui/react-utilities';
+import { ForwardRefComponent, useScrollbarWidth } from '@fluentui/react-utilities';
+import { useFluent } from '@fluentui/react-components';
 
 export const DataGrid: ForwardRefComponent<DataGridProps> = React.forwardRef((props, ref) => {
-  const state = useDataGrid_unstable(props, ref);
+  const { targetDocument } = useFluent();
+  const scrollbarWidth = useScrollbarWidth({ targetDocument });
```
Comment (ling1726) [inline packages/react-components/react-data-grid-react-window/src/components/DataGrid/DataGrid.tsx:15]: Since you're going to be using scrollbar width internally now, could you also try to get rid of this usage? https://github.com/microsoft/fluentui/blob/8ec648d4060906a32bad46a16e0eae13a7aa5959/packages/react-components/react-table/stories/DataGrid/Virtualization.stories.tsx#L159

File: packages/react-components/react-table/src/components/DataGrid/DataGrid.tsx [hunk 2]
```diff
@@ -6,12 +6,14 @@ import type { DataGridProps } from './DataGrid.types';
...
 import { useDataGridContextValues_unstable } from './useDataGridContextValues';
 import { useCustomStyleHook_unstable } from '@fluentui/react-shared-contexts';
+import { CELL_WIDTH } from '../../TableSelectionCell';
 
 /**
  * DataGrid component
  */
 export const DataGrid: ForwardRefComponent<DataGridProps> = React.forwardRef((props, ref) => {
-  const state = useDataGrid_unstable(props, ref);
+  const containerWidthOffset = props.containerWidthOffset ?? (props.selectionMode ? -CELL_WIDTH : 0);
```
Comment (ling1726) [inline packages/react-components/react-table/src/components/DataGrid/DataGrid.tsx:15]: why are you hoisting this out of the state hook? 

This kind of pre-processing also breaks our composition API 😅

File: packages/react-components/react-data-grid-react-window/src/components/DataGrid/DataGrid.tsx (hunk 1 above)
Comment (george-cz) [reply packages/react-components/react-data-grid-react-window/src/components/DataGrid/DataGrid.tsx:15]: yup, make sense:)

Comment (george-cz) [reply packages/react-components/react-data-grid-react-window/src/components/DataGrid/DataGrid.tsx:15]: follow up ticket https://github.com/microsoft/fluentui/issues/28027

File: packages/react-components/react-table/src/index.ts [hunk 3]
```diff
@@ -98,6 +98,7 @@ export {
   useTableSelectionCell_unstable,
   renderTableSelectionCell_unstable,
   tableSelectionCellClassNames,
+  CELL_WIDTH as TableSelectionCellWidth,
```
Comment (ling1726) [inline packages/react-components/react-table/src/index.ts:101]: This is just personal opinion, but I think that the virtualized data grid could be responsible for hard coding this constant itself.

In my 'ideal world' thinking, people who are recomposing our components should be aware of its internals, and to know about the width of the selection cell to offset should be 'known'.

Comment (ling1726) [inline packages/react-components/react-table/src/index.ts:101]: I think every time I've used constants I've always all capsed them, but I think it's not consistent in the repo anyway

**Review by ling1726 — APPROVED** [review]

File: packages/react-components/react-table/src/index.ts (hunk 3 above)
Comment (george-cz) [reply packages/react-components/react-table/src/index.ts:101]: makes sense, I'll remove this export
