### PR TITLE
fix: v8 Combobox role and accname for non-hidden icon button

### LINKED ISSUE #26897: [Bug]: ComboBox Caret Button fails FastPass a11y audit
### Library

React / v8 (@fluentui/react)

### System Info

```shell
all browsers
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/v-grfisher/pen/wvEaOWq

## Actual Behavior
Multiple FastPass automated check failures on the Caret button in ComboBox
- *aria-allowed-role* ARIA role presentation is not allowed for given element
- *button-name* Ensures buttons have discernible text
- *presentation-role-conflict* Elements marked as presentational should not have global ARIA or tabindex to ensure all screen readers ignore them

## Expected Behavior
No FastPass automated check failures

### Logs

_No response_

### Requested priority

Low

### Products/sites affected

https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by smhigley**
When the Combobox icon button isn't hidden, it should have an appropriate role and accname

- Fixes #26897

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/486ea4a2c7eaa7d4d7566a3d90d72c4e07d92c60'>486ea4a2c7eaa7d4d7566a3d90d72c4e07d92c60</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/BaseButton-mount_base.html">1193</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/BaseButton-mount.html">1204</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Breadcrumb-mount_base.html">2979</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Breadcrumb-mount.html">2991</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Checkbox-mount_base.html">2626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Checkbox-mount.html">2638</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/CheckboxBase-mount_base.html">2377</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/CheckboxBase-mount.html">2350</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ChoiceGroup-mount_base.html">4419</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ChoiceGroup-mount.html">4426</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ComboBox-mount_base.html">1251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ComboBox-mount.html">1274</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/CommandBar-mount_base.html">9667</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/CommandBar-mount.html">9769</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ContextualMenu-mount_base.html">16202</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ContextualMenu-mount.html">15976</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DefaultButton-mount_base.html">1400</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DefaultButton-mount.html">1392</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DetailsRow-mount_base.html">3488</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DetailsRow-mount.html">3502</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DetailsRowFast-mount_base.html">3503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DetailsRowFast-mount.html">3508</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DetailsRowNoStyles-mount_base.html">3296</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DetailsRowNoStyles-mount.html">3253</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Dialog-mount_base.html">3121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Dialog-mount.html">3074</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DocumentCardTitle-mount_base.html">586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/DocumentCardTitle-mount.html">587</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Dropdown-mount_base.html">3234</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Dropdown-mount.html">3215</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/FocusTrapZone-mount_base.html">2018</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/FocusTrapZone-mount.html">1999</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/FocusZone-mount_base.html">1954</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/FocusZone-mount.html">1987</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedList-mount_base.html">53443</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedList-mount.html">59044</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedList-virtual-rerender_base.html">24326</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedList-virtual-rerender.html">24230</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedList-virtual-rerender-with-unmount_base.html">92203</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedList-virtual-rerender-with-unmount.html">92414</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedListV2-mount_base.html">563</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedListV2-mount.html">560</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedListV2-virtual-rerender_base.html">552</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedListV2-virtual-rerender.html">542</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedListV2</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedListV2-virtual-rerender-with-unmount_base.html">559</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/GroupedListV2-virtual-rerender-with-unmount.html">556</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/IconButton-mount_base.html">1907</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/IconButton-mount.html">1912</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Label-mount_base.html">726</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Label-mount.html">728</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Layer-mount_base.html">4330</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Layer-mount.html">4358</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Link-mount_base.html">828</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Link-mount.html">825</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/MenuButton-mount_base.html">1699</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/MenuButton-mount.html">1680</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/MessageBar-mount_base.html">2267</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/MessageBar-mount.html">2319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Nav-mount_base.html">3225</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Nav-mount.html">3298</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/OverflowSet-mount_base.html">1333</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/OverflowSet-mount.html">1376</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Panel-mount_base.html">2589</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Panel-mount.html">2559</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Persona-mount_base.html">1300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Persona-mount.html">1311</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Pivot-mount_base.html">1645</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Pivot-mount.html">1637</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/PrimaryButton-mount_base.html">1506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/PrimaryButton-mount.html">1512</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Rating-mount_base.html">6973</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Rating-mount.html">7008</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/SearchBox-mount_base.html">1487</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/SearchBox-mount.html">1512</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Shimmer-mount_base.html">2888</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Shimmer-mount.html">2876</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Slider-mount_base.html">2095</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Slider-mount.html">2093</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/SpinButton-mount_base.html">4659</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/SpinButton-mount.html">4645</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Spinner-mount_base.html">803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Spinner-mount.html">810</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/SplitButton-mount_base.html">3077</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/SplitButton-mount.html">3072</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Stack-mount_base.html">829</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Stack-mount.html">825</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/StackWithIntrinsicChildren-mount_base.html">2314</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/StackWithIntrinsicChildren-mount.html">2331</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/StackWithTextChildren-mount_base.html">4779</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/StackWithTextChildren-mount.html">4758</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/SwatchColorPicker-mount_base.html">10290</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/SwatchColorPicker-mount.html">10489</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/TagPicker-mount_base.html">2609</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/TagPicker-mount.html">2671</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/TeachingBubble-mount_base.html">88068</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/TeachingBubble-mount.html">87499</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Text-mount_base.html">778</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Text-mount.html">796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/TextField-mount_base.html">1579</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/TextField-mount.html">1594</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ThemeProvider-mount_base.html">1529</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ThemeProvider-mount.html">1542</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ThemeProvider-virtual-rerender_base.html">1077</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ThemeProvider-virtual-rerender.html">1085</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2138</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2156</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Toggle-mount_base.html">1092</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/Toggle-mount.html">1121</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/buttonNative-mount_base.html">539</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/26905/perf-test/buttonNative-mount.html">547</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -643,8 +646,9 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
         <IconButton
           className={'ms-ComboBox-CaretDown-button'}
           styles={this._getCaretButtonStyles()}
-          role="presentation"
+          role={isButtonAriaHidden ? 'presentation' : undefined}
           aria-hidden={isButtonAriaHidden}
+          {...(isButtonAriaHidden ? {} : labelProps)}
```
Comment (spmonahan) [inline packages/react/src/components/ComboBox/ComboBox.tsx:651]: I believe this should work and it will avoid (potentially) creating an object every render.

```suggestion
          {...(!isButtonAriaHidden ? labelProps : undefined)}
```

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 2]
```diff
@@ -591,6 +591,10 @@ class ComboBoxInternal extends React.Component<IComboBoxInternalProps, IComboBox
         : placeholderProp;
 
     const labelledBy = [this.props['aria-labelledby'], label && this._id + '-label'].join(' ').trim();
+    const labelProps = {
```
Comment (spmonahan) [inline packages/react/src/components/ComboBox/ComboBox.tsx:594]: This looks like the same code as before just pulled out into an object. How does this change help resolve the issue?

Comment (micahgodbolt) [reply packages/react/src/components/ComboBox/ComboBox.tsx:594]: makes it spreadable below

**Review by micahgodbolt — APPROVED** [review]
other than Sean's suggestion, this looks good

File: packages/react/src/components/ComboBox/ComboBox.tsx (hunk 2 above)
Comment (smhigley) [reply packages/react/src/components/ComboBox/ComboBox.tsx:594]: yup, and also it's now used in two separate places, so I pulled it out.
