### PR TITLE
fix(SplitButton): Fix primary hover styles

### LINKED ISSUE #13623: SplitButton hover style is wrong
# Environment Information

- **Package version(s)**: 0.49
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:
docs site / SplitButton component:
http://g.recordit.co/xTP7BSqvmz.gif

### PR DESCRIPTION
**Pull request by assuncaocharles**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #13623
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Fix primary hover styles for `SplitButton`:

ezgif-4-1e2a9d682c2b

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/fluentui/react-northstar/src/themes/teams/components/SplitButton/splitButtonToggleStyles.ts [hunk 1]
```diff
@@ -84,7 +84,7 @@ const splitButtonToggleStyles: ComponentSlotStylesPrepared<SplitButtonToggleStyl
       ':focus-visible': {
         backgroundColor: v.toggleButtonBackgroundColorFocus,
         borderColor: v.toggleButtonBorderColorFocus,
-        color: v.toggleButtonColorFocus,
+        // color: v.toggleButtonColorFocus,
```
Comment (layershifter) [inline packages/fluentui/react-northstar/src/themes/teams/components/SplitButton/splitButtonToggleStyles.ts:87]:
```suggestion
        color: v.toggleButtonColorFocus,
```

???

Comment (assuncaocharles) [reply packages/fluentui/react-northstar/src/themes/teams/components/SplitButton/splitButtonToggleStyles.ts]: My bad :)
