### PR TITLE
fix(makeStyles): fix insertion of keyframes

### LINKED ISSUE #20050: makeStyles: animations not working
Animations (css, keyframes) are not working with makestyles. I have tried various types of animation and I keep getting this error on the console: 

image

#### Actual behavior:

CodeSandbox: https://codesandbox.io/s/new-fog-w496y

### PR DESCRIPTION
**Pull request by layershifter**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #20050
- [x] Include a change request file using `$ yarn change`

#### Description of changes

This PR fixes insertion of keyframes to `style`. CSS rules that were generated previously contained multiple rules (due prefixing), that caused failures in `.insertRule()` calls.

This PR updates `compileKeyframesCSS()` to generate atomic rules instead:

```js
// Before
const rules = [
  "@-webkit-keyframes foo{from{height:10px;}to{height:50px;}} @keyframes foo{from{height:10px;}to{height:50px;}}"
];
// After
const rules = [
  "@-webkit-keyframes foo{from{height:10px;}to{height:50px;}}",
  "@keyframes foo{from{height:10px;}to{height:50px;}}"
];
```

### CODE REVIEW

File: packages/make-styles/src/runtime/compileKeyframeCSS.ts [hunk 1]
```diff
@@ -1,19 +1,37 @@
...
 
   // eslint-disable-next-line guard-for-in
-  for (const percentage in frames) {
-    css += `${percentage}{${cssifyObject(frames[percentage])}}`;
+  for (const percentage in keyframeObject) {
+    css += `${percentage}{${cssifyObject(keyframeObject[percentage])}}`;
   }
 
   return css;
 }
```
Comment (layershifter) [inline packages/make-styles/src/runtime/compileKeyframeCSS.ts:14]: Just renaming

File: packages/make-styles/src/runtime/compileKeyframeCSS.ts [hunk 2]
```diff
@@ -1,19 +1,37 @@
...
 
-export function compileKeyframesCSS(animationName: string, framesCSS: string): string {
-  const cssRule = `@keyframes ${animationName} {${framesCSS}}`;
-  return serialize(compile(cssRule), middleware([prefixer, stringify]));
+/**
+ * Creates CSS rules for insertion from passed CSS.
+ */
+export function compileKeyframesCSS(keyframeName: string, keyframeCSS: string): string[] {
```
Comment (layershifter) [inline packages/make-styles/src/runtime/compileKeyframeCSS.ts:19]: Now this function returns an array of atomic rules to solve insertion problem.

File: packages/make-styles/src/runtime/resolveStyleRules.test.ts [hunk 3]
```diff
@@ -682,6 +666,22 @@ describe('resolveStyleRules', () => {
...
+          }
+        }
+        @keyframes f5j8bii {
+          from {
+            opacity: 0;
+          }
+          to {
+            opacity: 1;
+          }
+        }
```
Comment (layershifter) [inline packages/make-styles/src/runtime/resolveStyleRules.test.ts:684]: ⚠ All changes in snapshots are just reordering

File: packages/react-make-styles/README.md [hunk 4]
```diff
@@ -129,6 +129,29 @@ const useStyles = makeStyles({
 });
 ```
 
+### 🎞 `keyframes` (animations)
```
Comment (layershifter) [inline packages/react-make-styles/README.md:132]: I added a new section as we didn't have it before 🙄

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports                                                                                                                        |    Baseline (minified/GZIP) |                           PR |                                                                                                                                                                                                                                               Change |
| :--------------------------------------------------------------------------------------------------------------------------------------- | --------------------------: | ---------------------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                  | `31.28 kB`<br />`11.294 kB` | `31.317 kB`<br />`11.305 kB` | `37 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/IncreaseYellow.svg" /><br />`11 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/IncreaseYellow.svg" /> |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStyles-runtime.fixture.js'>makeStyles + mergeClasses (runtime)</abbr> | `22.136 kB`<br />`8.357 kB` |  `22.173 kB`<br />`8.366 kB` |  `37 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/IncreaseYellow.svg" /><br />`9 B` <img aria-hidden="true" src="https://microsoft.github.io/sizeAuditor-website/images/icons/IncreaseYellow.svg" /> |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `55.059 kB`<br />`17.394 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `54.953 kB`<br />`15.667 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `23.182 kB`<br />`6.986 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `25.642 kB`<br />`7.682 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenseBadge</abbr>                                                                       |          `237 B`<br />`177 B` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `23.224 kB`<br />`7.219 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `28.481 kB`<br />`8.173 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `25.249 kB`<br />`7.895 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `30.737 kB`<br />`8.955 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |    `32.45 kB`<br />`7.868 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |   `13.471 kB`<br />`5.068 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |    `9.317 kB`<br />`3.925 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `8.468 kB`<br />`3.557 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |     `9.695 kB`<br />`3.99 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `8.783 kB`<br />`3.741 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `161.95 kB`<br />`46.181 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.188 kB`<br />`10.658 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `15.342 kB`<br />`5.585 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |    `9.771 kB`<br />`3.975 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.952 kB`<br />`3.708 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |    `11.402 kB`<br />`4.59 kB` |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStaticStyles-runtime.fixture.js'>makeStaticStyles (runtime)</abbr>                                         |     `7.59 kB`<br />`3.321 kB` |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStyles.fixture.js'>makeStyles + mergeClasses (build time)</abbr>                                           |    `2.558 kB`<br />`1.204 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `103.316 kB`<br />`31.501 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `105.592 kB`<br />`31.866 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `101.153 kB`<br />`30.37 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |    `6.725 kB`<br />`2.237 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `15.147 kB`<br />`5.573 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/RangedSlider.fixture.js'>RangedSlider</abbr>                                                                        |  `35.092 kB`<br />`10.615 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |  `32.072 kB`<br />`10.166 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |    `23.89 kB`<br />`7.842 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `11.338 kB`<br />`4.418 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `14.407 kB`<br />`4.724 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `45.543 kB`<br />`15.541 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/a3391fbf4643431624961121002c512b130a1126'>a3391fbf4643431624961121002c512b130a1126</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Avatar-mount_base.html">724</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Avatar-mount.html">810</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/BaseButton-mount_base.html">797</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/BaseButton-mount.html">786</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Breadcrumb-mount_base.html">2244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Breadcrumb-mount.html">2258</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ButtonNext-mount_base.html">434</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ButtonNext-mount.html">429</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Checkbox-mount_base.html">1313</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Checkbox-mount.html">1327</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/CheckboxBase-mount_base.html">1102</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/CheckboxBase-mount.html">1092</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ChoiceGroup-mount_base.html">3962</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ChoiceGroup-mount.html">4010</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ComboBox-mount_base.html">1018</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ComboBox-mount.html">1005</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/CommandBar-mount_base.html">8904</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/CommandBar-mount.html">8904</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ContextualMenu-mount_base.html">5745</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ContextualMenu-mount.html">5651</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DefaultButton-mount_base.html">981</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DefaultButton-mount.html">966</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DetailsRow-mount_base.html">3227</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DetailsRow-mount.html">3240</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DetailsRowFast-mount_base.html">3223</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DetailsRowFast-mount.html">3232</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DetailsRowNoStyles-mount_base.html">3240</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DetailsRowNoStyles-mount.html">3095</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Dialog-mount_base.html">2124</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Dialog-mount.html">2177</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DocumentCardTitle-mount_base.html">156</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/DocumentCardTitle-mount.html">175</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Dropdown-mount_base.html">2805</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Dropdown-mount.html">2785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FluentProviderNext-mount_base.html">2934</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FluentProviderNext-mount.html">2918</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FluentProviderWithTheme-mount_base.html">197</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FluentProviderWithTheme-mount.html">199</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">93</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FluentProviderWithTheme-virtual-rerender.html">92</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">234</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">226</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FocusTrapZone-mount_base.html">1586</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FocusTrapZone-mount.html">1551</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FocusZone-mount_base.html">1561</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/FocusZone-mount.html">1591</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/IconButton-mount_base.html">1544</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/IconButton-mount.html">1538</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Label-mount_base.html">299</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Label-mount.html">317</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Layer-mount_base.html">2583</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Layer-mount.html">2620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Link-mount_base.html">412</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Link-mount.html">420</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/MakeStyles-mount_base.html">1588</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/MakeStyles-mount.html">1561</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/MenuButton-mount_base.html">1254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/MenuButton-mount.html">1254</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/MessageBar-mount_base.html">1750</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/MessageBar-mount.html">1775</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Nav-mount_base.html">2854</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Nav-mount.html">2835</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/OverflowSet-mount_base.html">966</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/OverflowSet-mount.html">958</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Panel-mount_base.html">2026</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Panel-mount.html">2048</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Persona-mount_base.html">739</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Persona-mount.html">742</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Pivot-mount_base.html">1221</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Pivot-mount.html">1250</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/PrimaryButton-mount_base.html">1123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/PrimaryButton-mount.html">1127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Rating-mount_base.html">6660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Rating-mount.html">6591</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/SearchBox-mount_base.html">1158</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/SearchBox-mount.html">1169</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Shimmer-mount_base.html">2194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Shimmer-mount.html">2193</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Slider-mount_base.html">1682</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Slider-mount.html">1648</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/SpinButton-mount_base.html">4317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/SpinButton-mount.html">4278</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Spinner-mount_base.html">380</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Spinner-mount.html">371</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/SplitButton-mount_base.html">2732</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/SplitButton-mount.html">2705</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Stack-mount_base.html">445</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Stack-mount.html">438</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/StackWithIntrinsicChildren-mount_base.html">1489</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/StackWithIntrinsicChildren-mount.html">1485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/StackWithTextChildren-mount_base.html">3984</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/StackWithTextChildren-mount.html">4002</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/SwatchColorPicker-mount_base.html">9047</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/SwatchColorPicker-mount.html">9025</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Tabs-mount_base.html">1229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Tabs-mount.html">1240</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/TagPicker-mount_base.html">2292</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/TagPicker-mount.html">2278</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/TeachingBubble-mount_base.html">11123</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/TeachingBubble-mount.html">11267</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Text-mount_base.html">388</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Text-mount.html">373</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/TextField-mount_base.html">1188</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/TextField-mount.html">1194</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ThemeProvider-mount_base.html">1043</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ThemeProvider-mount.html">1040</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ThemeProvider-virtual-rerender_base.html">537</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ThemeProvider-virtual-rerender.html">537</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1614</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1618</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Toggle-mount_base.html">699</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/Toggle-mount.html">716</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/buttonNative-mount_base.html">116</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test/buttonNative-mount.html">122</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
MenuButtonMinimalPerf.default | [1390](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1397](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 0.99:1 | [analysis](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/MenuButtonMinimalPerf.default.regression.txt)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
TreeWith60ListItems.default | [154](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TreeWith60ListItems.default.html) | [136](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.13:1
RadioGroupMinimalPerf.default | [403](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.09:1
VideoMinimalPerf.default | [538](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/VideoMinimalPerf.default.html) | [495](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.09:1
ChatWithPopoverPerf.default | [349](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ChatWithPopoverPerf.default.html) | [323](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.08:1
ButtonMinimalPerf.default | [149](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ButtonMinimalPerf.default.html) | [139](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.07:1
SegmentMinimalPerf.default | [310](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/SegmentMinimalPerf.default.html) | [289](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.07:1
AlertMinimalPerf.default | [239](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AlertMinimalPerf.default.html) | [226](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.06:1
ImageMinimalPerf.default | [330](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ImageMinimalPerf.default.html) | [310](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.06:1
AvatarMinimalPerf.default | [180](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AvatarMinimalPerf.default.html) | [171](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.05:1
PortalMinimalPerf.default | [161](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/PortalMinimalPerf.default.html) | [153](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.05:1
SkeletonMinimalPerf.default | [311](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/SkeletonMinimalPerf.default.html) | [296](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.05:1
FormMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/FormMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.04:1
GridMinimalPerf.default | [295](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/GridMinimalPerf.default.html) | [283](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.04:1
TreeMinimalPerf.default | [673](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TreeMinimalPerf.default.html) | [650](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.04:1
ItemLayoutMinimalPerf.default | [1039](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1011](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
LayoutMinimalPerf.default | [318](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/LayoutMinimalPerf.default.html) | [310](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.03:1
RefMinimalPerf.default | [212](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/RefMinimalPerf.default.html) | [205](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.03:1
SliderMinimalPerf.default | [1478](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/SliderMinimalPerf.default.html) | [1441](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.03:1
ToolbarMinimalPerf.default | [807](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ToolbarMinimalPerf.default.html) | [783](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.03:1
AnimationMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AnimationMinimalPerf.default.html) | [348](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.02:1
ButtonSlotsPerf.default | [477](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ButtonSlotsPerf.default.html) | [467](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.02:1
LabelMinimalPerf.default | [333](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/LabelMinimalPerf.default.html) | [325](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.02:1
ReactionMinimalPerf.default | [324](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ReactionMinimalPerf.default.html) | [318](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.02:1
ChatMinimalPerf.default | [556](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ChatMinimalPerf.default.html) | [553](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2326](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2308](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
DialogMinimalPerf.default | [644](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DialogMinimalPerf.default.html) | [637](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [588](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DropdownManyItemsPerf.default.html) | [585](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.01:1
EmbedMinimalPerf.default | [3641](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/EmbedMinimalPerf.default.html) | [3600](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.01:1
FlexMinimalPerf.default | [247](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/FlexMinimalPerf.default.html) | [244](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.01:1
HeaderMinimalPerf.default | [314](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/HeaderMinimalPerf.default.html) | [311](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.01:1
HeaderSlotsPerf.default | [642](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/HeaderSlotsPerf.default.html) | [636](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [1127](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/InputMinimalPerf.default.html) | [1120](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
ListNestedPerf.default | [471](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ListNestedPerf.default.html) | [468](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ListNestedPerf.default_base.html) | 1.01:1
LoaderMinimalPerf.default | [609](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/LoaderMinimalPerf.default.html) | [601](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [1489](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1476](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
IconMinimalPerf.default | [532](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/IconMinimalPerf.default.html) | [529](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/IconMinimalPerf.default_base.html) | 1.01:1
TextMinimalPerf.default | [297](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TextMinimalPerf.default.html) | [293](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.01:1
CustomToolbarPrototype.default | [3558](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/CustomToolbarPrototype.default.html) | [3527](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [883](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TooltipMinimalPerf.default.html) | [878](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
ButtonOverridesMissPerf.default | [1515](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1509](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1:1
DropdownMinimalPerf.default | [2718](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DropdownMinimalPerf.default.html) | [2715](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1:1
ListMinimalPerf.default | [434](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ListMinimalPerf.default.html) | [433](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ListMinimalPerf.default_base.html) | 1:1
ListWith60ListItems.default | [547](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ListWith60ListItems.default.html) | [546](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ListWith60ListItems.default_base.html) | 1:1
MenuMinimalPerf.default | [717](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/MenuMinimalPerf.default.html) | [720](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [3632](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3632](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
StatusMinimalPerf.default | [582](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/StatusMinimalPerf.default.html) | [580](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1:1
AccordionMinimalPerf.default | [133](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AccordionMinimalPerf.default.html) | [135](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 0.99:1
AttachmentMinimalPerf.default | [133](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AttachmentMinimalPerf.default.html) | [134](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 0.99:1
BoxMinimalPerf.default | [294](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/BoxMinimalPerf.default.html) | [297](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/BoxMinimalPerf.default_base.html) | 0.99:1
CardMinimalPerf.default | [466](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/CardMinimalPerf.default.html) | [469](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.99:1
CarouselMinimalPerf.default | [395](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/CarouselMinimalPerf.default.html) | [397](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.99:1
ChatDuplicateMessagesPerf.default | [262](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [264](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 0.99:1
DatepickerMinimalPerf.default | [4720](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DatepickerMinimalPerf.default.html) | [4762](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 0.99:1
RosterPerf.default | [1002](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/RosterPerf.default.html) | [1010](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/RosterPerf.default_base.html) | 0.99:1
PopupMinimalPerf.default | [503](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/PopupMinimalPerf.default.html) | [510](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/PopupMinimalPerf.default_base.html) | 0.99:1
ProviderMinimalPerf.default | [965](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ProviderMinimalPerf.default.html) | [972](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 0.99:1
TableManyItemsPerf.default | [1585](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TableManyItemsPerf.default.html) | [1599](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TableManyItemsPerf.default_base.html) | 0.99:1
DividerMinimalPerf.default | [303](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DividerMinimalPerf.default.html) | [309](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.98:1
TableMinimalPerf.default | [343](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TableMinimalPerf.default.html) | [350](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TableMinimalPerf.default_base.html) | 0.98:1
TextAreaMinimalPerf.default | [429](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TextAreaMinimalPerf.default.html) | [436](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.98:1
ListCommonPerf.default | [516](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ListCommonPerf.default.html) | [531](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/ListCommonPerf.default_base.html) | 0.97:1
AttachmentSlotsPerf.default | [907](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AttachmentSlotsPerf.default.html) | [953](https://fluentuipr.z22.web.core.windows.net/pull/20095/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.95:1

</details><div id="perfComment9423"/>

File: packages/react-make-styles/README.md [hunk 5]
```diff
@@ -129,6 +129,29 @@ const useStyles = makeStyles({
...
+
+`keyframes` are supported via `animationName` property that can be defined as an object or an array of objects:
+
+```tsx
+import { makeStyles } from '@fluentui/react-components';
+
+const useStyles = makeStyles({
+  root: {
+    animationIterationCount: 'infinite',
```
Comment (ling1726) [inline packages/react-make-styles/README.md:141]: nit: add an example for the array of objects

**Review by ling1726 — APPROVED** [review]

File: packages/react-make-styles/README.md (hunk 5 above)
Comment (layershifter) [reply packages/react-make-styles/README.md:141]: Good call, added in e2f93e4.

---

I also discovered another problem when I was creating an example, we used `" "` (space) as a delimiter, but we should use comma (48f14a5).

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-name
