### PR TITLE
fix: Scope focus visible classnames and event listeners to ThemeProvider by default, and to the window body as a fallback

### LINKED ISSUE #23378: [Bug]: useFocusRects code triggers on keyboard/mouse behavior outside of Fluent components
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 16.29 GB / 31.90 GB
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53), ChromiumDev (91.0.838.3)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/kelseyyoung/pen/qBxKaEp

## Actual Behavior
In the codepen linked there are two Fluent Buttons followed by non-Fluent HTML elements. Buttons include the code from useFocusRects/the `<FocusRects>` component  in BaseButton.tsx

```
    return (
      <>
        {Content}
        <FocusRects />
      </>
    );
```

This code will toggle two classnames on the body element of the page, `ms-Fabric--isFocusVisible` and `ms-Fabric--isFocusHidden`, when toggling between mouse and "focus keyboard" events. However, these handlers are attached to the window, and so this code fires on events not using Fluent components. To mimic this behavior in the codepen, the repro steps are:

1. Place your mouse cursor inside the input box via click
2. Hit the right or left arrow key
3. Observe the classname on the body of the codepen changes the classname

(Gif below shows the classname changing while toggling between mouse clicks and arrow keys)

useFocusRects

Changing this classname causes a style recalculation in the browser despite these events happening on non-Fluent components. If no Fluent components are involved, the code in useFocusRects shouldn't need to fire

## Expected Behavior
We believe the behavior of useFocusRects could change in these ways, or other equivalent solutions:

1. Constrain its behavior to only trigger on events where Fluent components are involved (either by default or 
2. Attach the classnames to a more scoped element instead of the body of the entire document

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by khmakoto**
## Current Behavior

Currently, `useFocusRects` will toggle between two classnames attached on the body element of the page, `ms-Fabric--isFocusVisible` and `ms-Fabric--isFocusHidden`. The two states are toggled via event listeners on the window, making the focus rectangles visible on keydown and making them hidden on mousedown and pointerdown. Because the listeners are attached to the window, however, this code fires on interactions on non-Fluent components, which can cause a big style recalculation in the browser despite these events happening on non-Fluent components.

__The classname, attached to the body, changes when switching between mouse and keyboard on everything, including non-Fluent elements:__

useFocusRects

## New Behavior

This PR makes a couple of changes to alleviate this issue:
- It adds a `FocusRectsContext` that passes in a `ref` to an element. `useFocusRects` then checks the `current` value of this `ref`, and if the `ref` is defined, it attaches the classnames and listeners to the element pointed to by the `ref`. If the `current` value of the `ref` is `undefined`, then the hook falls back to attaching the classnames and listeners to the document body.
- It wraps `children` of `ThemeProvider` in a `FocusRectsProvider` and passes it a `ref` to its root element. This ensures that the classnames and listeners are always attached to the closest `ThemeProvider` available.
- It also adds a `FocusRectsProvider` wrapper to `Layers` so that elements in portals also have a focus rects provider at their root, to avoid unintentionally attaching them to the document body.
- It adds a `keyup` event listener in addition to the `keydown` one. This allows us to ensure that we listen to the event once the focus has changed from outside of a focus rects zone into a focus rects zone (for example, from non-Fluent components outside of a `ThemeProvider` into Fluent components within a `ThemeProvider`), while keeping the scenario of keeping tab pressed to move rapidly between components and have the visible focus move with it intact. There is no problem with double classnames or the like because `classList.add` is smart enough to not duplicate it if it already exists on the element.

_Note:_ This change makes use of the assumption that the `onKeyUp` events fire after `onFocus` has been fired fired. As far as I know, while HTML5 has a [recommendation on event loops](https://html.spec.whatwg.org/multipage/webappapis.html#event-loops), it is up to the browser implementation to determine which events will be grouped together and processed in order, as well as the priority given to any particular type of event. This could make this particular solution not work for all browsers. However, it works as expected on the following browsers I tested: Chrome, Edge and Firefox on Windows 11. I'd need someone else to test Safari since I don't have access to a MacOS machine.

__The classname, attached to the provider, changes when switching between mouse and keyboard only on elements inside of the `ThemeProvider`:__

useFocusRects

## Related Issue(s)

Fixes #23378

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/b7a17b43445a791305e0a3edb9a518ac35f66dd8'>b7a17b43445a791305e0a3edb9a518ac35f66dd8</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react/src/utilities/ThemeProvider/ThemeProvider.tsx [hunk 1]
```diff
@@ -22,9 +22,6 @@ export const ThemeProvider: React.FunctionComponent<ThemeProviderProps> = React.
   // Render styles.
   useThemeProviderClasses(state);
 
-  // Apply focus rect class on key presses.
-  useFocusRects(state.ref);
-
```
Comment (khmakoto) [inline packages/react/src/utilities/ThemeProvider/ThemeProvider.tsx:27]: This is removed because it was actually never needed in this component, since it has no styles relying on `isFocusVisible` or `isFocusHidden`.

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/BaseButton-mount_base.html">784</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/BaseButton-mount.html">775</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Breadcrumb-mount_base.html">2371</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Breadcrumb-mount.html">2398</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Checkbox-mount_base.html">2247</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Checkbox-mount.html">2242</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/CheckboxBase-mount_base.html">1928</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/CheckboxBase-mount.html">1964</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ChoiceGroup-mount_base.html">4070</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ChoiceGroup-mount.html">4058</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ComboBox-mount_base.html">840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ComboBox-mount.html">901</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/CommandBar-mount_base.html">8998</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/CommandBar-mount.html">9111</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ContextualMenu-mount_base.html">9917</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ContextualMenu-mount.html">9911</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DefaultButton-mount_base.html">967</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DefaultButton-mount.html">964</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DetailsRow-mount_base.html">3349</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DetailsRow-mount.html">3348</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DetailsRowFast-mount_base.html">3303</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DetailsRowFast-mount.html">3273</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DetailsRowNoStyles-mount_base.html">3175</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DetailsRowNoStyles-mount.html">3101</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Dialog-mount_base.html">2413</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Dialog-mount.html">2433</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DocumentCardTitle-mount_base.html">140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/DocumentCardTitle-mount.html">157</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Dropdown-mount_base.html">3114</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Dropdown-mount.html">2863</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/FocusTrapZone-mount_base.html">1639</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/FocusTrapZone-mount.html">1636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/FocusZone-mount_base.html">1567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/FocusZone-mount.html">1573</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/IconButton-mount_base.html">1527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/IconButton-mount.html">1510</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Label-mount_base.html">309</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Label-mount.html">312</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Layer-mount_base.html">2555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Layer-mount.html">2687</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Link-mount_base.html">406</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Link-mount.html">414</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/MenuButton-mount_base.html">1268</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/MenuButton-mount.html">1295</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/MessageBar-mount_base.html">1865</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/MessageBar-mount.html">1829</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Nav-mount_base.html">2840</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Nav-mount.html">2828</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/OverflowSet-mount_base.html">936</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/OverflowSet-mount.html">962</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Panel-mount_base.html">1885</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Panel-mount.html">1887</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Persona-mount_base.html">872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Persona-mount.html">881</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Pivot-mount_base.html">1248</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Pivot-mount.html">1250</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/PrimaryButton-mount_base.html">1139</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/PrimaryButton-mount.html">1114</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Rating-mount_base.html">6675</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Rating-mount.html">6663</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/SearchBox-mount_base.html">1115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/SearchBox-mount.html">1108</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Shimmer-mount_base.html">2140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Shimmer-mount.html">2132</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Slider-mount_base.html">1668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Slider-mount.html">1714</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/SpinButton-mount_base.html">4363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/SpinButton-mount.html">4363</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Spinner-mount_base.html">365</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Spinner-mount.html">379</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/SplitButton-mount_base.html">2722</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/SplitButton-mount.html">2768</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Stack-mount_base.html">441</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Stack-mount.html">451</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/StackWithIntrinsicChildren-mount_base.html">1994</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/StackWithIntrinsicChildren-mount.html">1975</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/StackWithTextChildren-mount_base.html">4495</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/StackWithTextChildren-mount.html">4490</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/SwatchColorPicker-mount_base.html">9946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/SwatchColorPicker-mount.html">10024</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/TagPicker-mount_base.html">2315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/TagPicker-mount.html">2342</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/TeachingBubble-mount_base.html">78415</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/TeachingBubble-mount.html">79678</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Text-mount_base.html">379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Text-mount.html">371</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/TextField-mount_base.html">1223</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/TextField-mount.html">1199</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ThemeProvider-mount_base.html">1021</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ThemeProvider-mount.html">1096</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ThemeProvider-virtual-rerender_base.html">555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ThemeProvider-virtual-rerender.html">625</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1653</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1585</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Toggle-mount_base.html">681</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/Toggle-mount.html">688</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/buttonNative-mount_base.html">110</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24025/perf-test/buttonNative-mount.html">117</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by jspurlin — APPROVED** [review]
:shipit:

File: packages/react/src/utilities/ThemeProvider/renderThemeProvider.tsx [hunk 2]
```diff
@@ -1,17 +1,21 @@
...
   const rootProps = typeof state.as === 'string' ? getNativeElementProps(state.as, state) : omit(state, ['as']);
 
   return (
     <ThemeContext.Provider value={theme}>
       <CustomizerContext.Provider value={customizerContext}>
-        <Root {...rootProps} />
+        <FocusRectsProvider value={focusRectsContext}>
+          <div>
+            <Root {...rootProps} />
+          </div>
```
Comment (behowell) [inline packages/react/src/utilities/ThemeProvider/renderThemeProvider.tsx:17]: Is this extra div needed?

File: packages/utilities/src/useFocusRects.ts [hunk 3]
```diff
@@ -40,33 +67,50 @@ type AppWindow = (Window & { FabricConfig?: { disableFocusRects?: boolean } }) |
...
     }
 
-    let count = setMountCounters(win, 1);
+    let el: Window | HTMLElement = win;
+    let onMouseDown: (ev: MouseEvent) => void;
+    let onPointerDown: (ev: PointerEvent) => void;
+    let onKeyUp: (ev: KeyboardEvent) => void;
+    if (providerRef && providerRef.current) {
+      el = providerRef.current;
+      const callbacks = setCallBackMap(el as HTMLElement);
```
[the remark this answers is not in the document]
Comment (khmakoto) [reply packages/utilities/src/useFocusRects.ts:85]: If I do that it gives me this error

image

File: packages/react/src/utilities/ThemeProvider/renderThemeProvider.tsx (hunk 2 above)
Comment (khmakoto) [reply packages/react/src/utilities/ThemeProvider/renderThemeProvider.tsx:17]: Not needed, it is a remnant from when I was testing things, removing it 😄

File: packages/utilities/src/useFocusRects.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (khmakoto) [reply packages/utilities/src/useFocusRects.ts:85]: Full screenshot of the error. It freaks out because of the `useEffect` return callback using `el`:

image

File: packages/utilities/src/useFocusRects.ts [hunk 4]
```diff
@@ -78,19 +129,26 @@ export const FocusRects: React.FunctionComponent<{ rootRef?: React.RefObject<HTM
...
 }
 
-function _onKeyDown(ev: KeyboardEvent): void {
+function _onKeyUp(ev: KeyboardEvent, providerElem?: Element): void {
   // eslint-disable-next-line deprecation/deprecation
   if (isDirectionalKeyCode(ev.which)) {
-    setFocusVisibility(true, ev.target as Element);
+    setFocusVisibility(true, ev.target as Element, providerElem);
   }
 }
```
Comment (behowell) [inline packages/utilities/src/useFocusRects.ts:154]: Maybe add a comment about why you need to listen for both onKeyDown and onKeyUp (and why both functions do the same thing)?

**Review by behowell — APPROVED** [review]

File: packages/utilities/src/useFocusRects.ts (hunk 4 above)
Comment (khmakoto) [reply packages/utilities/src/useFocusRects.ts:163]: This is a good suggestion, just added it.

**Comment by brandonthomas** [comment]
@khmakoto looks like we're hitting breaks with this behavior in some components. Even though the API wasn't removed I am wondering if a change like this should have been marked major since it regressed accessibility in components like ComboBox and ContextualMenu. Took me a few days of debugging on and off to track down what exactly was happening here. Have there been other reports of consuming teams losing focus rects on components that previously had it? Our particular case is a menu wrapped in a Callout. Because it renders outside the DOM of the fabric component it lost `ms-Fabric-isFocusHidden` in its ancestor tree. I should be able to patch now but definitely threw me for a bit of a loop.
