### PR TITLE
fix(scripts): update create-component generator to adhere to latest changes

### LINKED ISSUE #20960: create-package/create-component generates incorrect tsconfig file
### Environment Information

- **Package version(s)**: The `create-package` and `create-component` scripts at git commit `d5d3ef6592218c4876fa351d22b7b717b82e7602`
- **Browser and OS versions**: N/A. This is a bug in a command line program.

### Please provide a reproduction of the bug in a codepen:

1. [Follow the instructions in the wiki for scaffolding a new converged component](https://github.com/microsoft/fluentui/wiki/Component-Convergence-Guide#component-package). Values to enter provided below
2. `create-package`
    1. Use `react-test` for the package name
    2. Use `react` for the package target
    3. Use the default for the package description
    4. Choose `Y` for "is this a converged package?"
3. `create-component` 
    1. Select `@fluentui/react-test` for the package in which to create a component
    2. Enter `Test` for component name
    3. Choose `Y` to run a test build
4. Run `yarn workspace @fluentui/react-test type-check`

Note the many errors about no types for Jest functions like `it` and `afterEach`.

The `tsconfig.lib.json` file for the generated "test" package has the following line for `excludes`: https://github.com/microsoft/fluentui/blob/9307cee4dff21cd798640e911dbb79eca386460d/packages/react-spinbutton/tsconfig.lib.json#L10

Looking at other converged packages like `react-button` you'll see a different list of `excludes`: https://github.com/microsoft/fluentui/blob/master/packages/react-button/tsconfig.lib.json#L10-L18

Copying the `react-button` excludes to the "test" config fixes the issue with type checking.

#### Actual behavior:

Many type checking errors related to missing type definitions.

#### Expected behavior:

Type checking in a freshly generated package/component should pass without any issues.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: N/A

### PR DESCRIPTION
**Pull request by Hotell**
## Current Behavior

- generator produces invalid code ( type check fails, tests fail )
- generator asks if user wants to run post-processing. if user opts out he will get invalid code
- post-processing invokes unnecessary build chain

## New Behavior

-  no asking if user want's to run post-processing
- component/package is updated and ready to go after generator run

**🎬 DEMO:**

https://user-images.githubusercontent.com/1223799/151839581-0b938baa-83b4-494d-9b5f-d4d65e7b527c.mov

## Related Issue(s)

Fixes #20960

### CODE REVIEW

File: scripts/create-component/plop-templates/src/components/{{componentName}}/use{{componentName}}Styles.ts.hbs [hunk 1]
```diff
@@ -1,6 +1,8 @@
 import { makeStyles, mergeClasses } from '@griffel/react';
 import type { {{componentName}}State } from './{{componentName}}.types';
 
+
+export const {{componentNames.propertyName}}ClassName = 'fui-{{componentName}}'
```
Comment (Hotell) [inline scripts/create-component/plop-templates/src/components/{{componentName}}/use{{componentName}}Styles.ts.hbs:5]: handlebars has build in `camelCase` helper which doesn't work. dropped in nx helpers. see https://github.com/helpers/handlebars-helpers/issues/363

File: scripts/create-component/plop-templates/src/components/{{componentName}}/{{componentName}}.tsx.hbs [hunk 2]
```diff
@@ -6,7 +6,7 @@ import type { {{componentName}}Props } from './{{componentName}}.types';
 import type { ForwardRefComponent } from '@fluentui/react-utilities';
 
 /**
- * {{componentName}} component
+ * {{componentName}} component - TODO: add more docs
```
Comment (Hotell) [inline scripts/create-component/plop-templates/src/components/{{componentName}}/{{componentName}}.tsx.hbs:9]: this also makes one of conformance test pass - previously this was failing

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `54.888 kB`<br />`17.524 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `44.266 kB`<br />`12.603 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `20.828 kB`<br />`6.533 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `21.696 kB`<br />`6.832 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |   `22.507 kB`<br />`6.587 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `27.942 kB`<br />`8.023 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `33.239 kB`<br />`8.981 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |   `29.863 kB`<br />`8.658 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |   `35.938 kB`<br />`9.728 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |   `37.219 kB`<br />`8.634 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `48.488 kB`<br />`14.347 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `43.997 kB`<br />`13.195 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `7.618 kB`<br />`3.232 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `8.885 kB`<br />`3.673 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `7.811 kB`<br />`3.361 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `165.834 kB`<br />`46.987 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.489 kB`<br />`10.636 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `15.269 kB`<br />`5.523 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |   `10.075 kB`<br />`3.942 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |   `21.474 kB`<br />`7.118 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.323 kB`<br />`3.479 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `11.072 kB`<br />`4.496 kB` |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStaticStyles-runtime.fixture.js'>makeStaticStyles (runtime)</abbr>                                         |    `8.161 kB`<br />`3.564 kB` |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStyles-runtime.fixture.js'>makeStyles + mergeClasses (runtime)</abbr>                                      |   `19.554 kB`<br />`7.446 kB` |
| <samp>react-make-styles</samp> <br /> <abbr title='bundle-size/makeStyles.fixture.js'>makeStyles + mergeClasses (build time)</abbr>                                           |    `2.793 kB`<br />`1.267 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `103.149 kB`<br />`31.833 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             |   `105.4 kB`<br />`32.191 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `95.348 kB`<br />`29.017 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |    `6.249 kB`<br />`2.163 kB` |
| <samp>react-positioning</samp> <br /> <abbr title='bundle-size/usePopper.fixture.js'>usePopper</abbr>                                                                         |   `22.808 kB`<br />`7.935 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `13.972 kB`<br />`5.237 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |   `22.936 kB`<br />`7.751 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |    `6.787 kB`<br />`2.887 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `25.397 kB`<br />`8.208 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                                        |   `10.769 kB`<br />`4.224 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Wrappers.fixture.js'>Text - Wrappers</abbr>                                                                      |   `14.077 kB`<br />`4.565 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>                                                        |            `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>                                                                  |   `29.426 kB`<br />`6.551 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>                                                                |     `18.42 kB`<br />`5.27 kB` |
| <samp>react-tooltip</samp> <br /> <abbr title='bundle-size/Tooltip.fixture.js'>Tooltip</abbr>                                                                                 |  `42.008 kB`<br />`14.478 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                                                                       |          `189 B`<br />`161 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/beb7b60c639989b1d6fb4b518bee632963023e44'>beb7b60c639989b1d6fb4b518bee632963023e44</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Avatar-mount_base.html">1002</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Avatar-mount.html">956</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/BaseButton-mount_base.html">926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/BaseButton-mount.html">946</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Breadcrumb-mount_base.html">2681</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Breadcrumb-mount.html">2648</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ButtonNext-mount_base.html">518</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ButtonNext-mount.html">528</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Checkbox-mount_base.html">1546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Checkbox-mount.html">1512</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/CheckboxBase-mount_base.html">1300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/CheckboxBase-mount.html">1320</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ChoiceGroup-mount_base.html">4715</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ChoiceGroup-mount.html">4796</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ComboBox-mount_base.html">987</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ComboBox-mount.html">1011</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/CommandBar-mount_base.html">10333</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/CommandBar-mount.html">10283</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ContextualMenu-mount_base.html">8447</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ContextualMenu-mount.html">8280</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DefaultButton-mount_base.html">1149</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DefaultButton-mount.html">1183</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DetailsRow-mount_base.html">3918</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DetailsRow-mount.html">3904</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DetailsRowFast-mount_base.html">3785</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DetailsRowFast-mount.html">3815</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DetailsRowNoStyles-mount_base.html">3657</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DetailsRowNoStyles-mount.html">3644</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Dialog-mount_base.html">2645</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Dialog-mount.html">2686</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DocumentCardTitle-mount_base.html">194</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/DocumentCardTitle-mount.html">187</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Dropdown-mount_base.html">3281</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Dropdown-mount.html">3298</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FluentProviderNext-mount_base.html">1929</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FluentProviderNext-mount.html">1864</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FluentProviderWithTheme-mount_base.html">178</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FluentProviderWithTheme-mount.html">167</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FluentProviderWithTheme-virtual-rerender_base.html">111</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FluentProviderWithTheme-virtual-rerender.html">112</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FluentProviderWithTheme-virtual-rerender-with-unmount.html">212</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FocusTrapZone-mount_base.html">1902</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FocusTrapZone-mount.html">1889</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FocusZone-mount_base.html">1874</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/FocusZone-mount.html">1877</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/IconButton-mount_base.html">1953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/IconButton-mount.html">1824</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Label-mount_base.html">377</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Label-mount.html">386</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Layer-mount_base.html">3052</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Layer-mount.html">3019</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Link-mount_base.html">491</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Link-mount.html">501</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/MakeStyles-mount_base.html">1721</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/MakeStyles-mount.html">1782</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/MenuButton-mount_base.html">1493</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/MenuButton-mount.html">1533</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/MessageBar-mount_base.html">2062</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/MessageBar-mount.html">2038</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Nav-mount_base.html">3323</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Nav-mount.html">3356</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/OverflowSet-mount_base.html">1140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/OverflowSet-mount.html">1125</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Panel-mount_base.html">2558</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Panel-mount.html">2490</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Persona-mount_base.html">883</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Persona-mount.html">857</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Pivot-mount_base.html">1469</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Pivot-mount.html">1459</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/PrimaryButton-mount_base.html">1317</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/PrimaryButton-mount.html">1331</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Rating-mount_base.html">7746</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Rating-mount.html">7652</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/SearchBox-mount_base.html">1318</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/SearchBox-mount.html">1319</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Shimmer-mount_base.html">2503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Shimmer-mount.html">2460</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Slider-mount_base.html">1943</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Slider-mount.html">1931</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/SpinButton-mount_base.html">4958</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/SpinButton-mount.html">4920</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Spinner-mount_base.html">458</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Spinner-mount.html">466</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/SplitButton-mount_base.html">3238</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/SplitButton-mount.html">3298</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Stack-mount_base.html">546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Stack-mount.html">565</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/StackWithIntrinsicChildren-mount_base.html">2266</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/StackWithIntrinsicChildren-mount.html">2324</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/StackWithTextChildren-mount_base.html">5188</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/StackWithTextChildren-mount.html">5131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/SwatchColorPicker-mount_base.html">11310</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/SwatchColorPicker-mount.html">11499</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/TagPicker-mount_base.html">2605</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/TagPicker-mount.html">2676</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/TeachingBubble-mount_base.html">13501</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/TeachingBubble-mount.html">13324</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Text-mount_base.html">460</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Text-mount.html">454</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/TextField-mount_base.html">1421</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/TextField-mount.html">1448</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ThemeProvider-mount_base.html">1246</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ThemeProvider-mount.html">1260</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ThemeProvider-virtual-rerender_base.html">679</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ThemeProvider-virtual-rerender.html">641</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1941</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1954</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Toggle-mount_base.html">816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/Toggle-mount.html">873</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/buttonNative-mount_base.html">163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test/buttonNative-mount.html">151</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
ButtonMinimalPerf.default | [199](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ButtonMinimalPerf.default.html) | [175](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.14:1
AccordionMinimalPerf.default | [153](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AccordionMinimalPerf.default.html) | [140](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.09:1
AvatarMinimalPerf.default | [205](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AvatarMinimalPerf.default.html) | [191](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.07:1
ListMinimalPerf.default | [564](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ListMinimalPerf.default.html) | [529](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.07:1
PortalMinimalPerf.default | [196](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/PortalMinimalPerf.default.html) | [183](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.07:1
ChatMinimalPerf.default | [756](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ChatMinimalPerf.default.html) | [715](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.06:1
AlertMinimalPerf.default | [263](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AlertMinimalPerf.default.html) | [250](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.05:1
BoxMinimalPerf.default | [351](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/BoxMinimalPerf.default.html) | [335](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.05:1
CarouselMinimalPerf.default | [501](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/CarouselMinimalPerf.default.html) | [475](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.05:1
DialogMinimalPerf.default | [781](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DialogMinimalPerf.default.html) | [754](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.04:1
RadioGroupMinimalPerf.default | [465](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [445](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.04:1
FlexMinimalPerf.default | [297](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/FlexMinimalPerf.default.html) | [289](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.03:1
ListWith60ListItems.default | [647](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ListWith60ListItems.default.html) | [631](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.03:1
PopupMinimalPerf.default | [638](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/PopupMinimalPerf.default.html) | [620](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.03:1
RefMinimalPerf.default | [242](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/RefMinimalPerf.default.html) | [235](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.03:1
SegmentMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/SegmentMinimalPerf.default.html) | [339](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.03:1
TreeMinimalPerf.default | [773](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TreeMinimalPerf.default.html) | [754](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.03:1
AttachmentMinimalPerf.default | [158](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AttachmentMinimalPerf.default.html) | [155](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.02:1
DropdownManyItemsPerf.default | [699](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DropdownManyItemsPerf.default.html) | [683](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.02:1
DropdownMinimalPerf.default | [3051](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DropdownMinimalPerf.default.html) | [2992](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.02:1
FormMinimalPerf.default | [412](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/FormMinimalPerf.default.html) | [403](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.02:1
HeaderSlotsPerf.default | [766](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/HeaderSlotsPerf.default.html) | [751](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [697](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/LoaderMinimalPerf.default.html) | [685](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
MenuButtonMinimalPerf.default | [1658](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1623](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.02:1
ProviderMergeThemesPerf.default | [1754](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1724](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.02:1
ReactionMinimalPerf.default | [374](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ReactionMinimalPerf.default.html) | [366](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.02:1
TableManyItemsPerf.default | [1887](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TableManyItemsPerf.default.html) | [1855](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.02:1
TreeWith60ListItems.default | [170](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TreeWith60ListItems.default.html) | [166](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1667](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1658](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2675](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2652](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
LabelMinimalPerf.default | [397](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/LabelMinimalPerf.default.html) | [392](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.01:1
ListCommonPerf.default | [650](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ListCommonPerf.default.html) | [646](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
MenuMinimalPerf.default | [870](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/MenuMinimalPerf.default.html) | [861](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.01:1
ProviderMinimalPerf.default | [1131](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ProviderMinimalPerf.default.html) | [1122](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.01:1
ToolbarMinimalPerf.default | [900](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ToolbarMinimalPerf.default.html) | [895](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [1005](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TooltipMinimalPerf.default.html) | [998](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
ChatDuplicateMessagesPerf.default | [304](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [303](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1:1
DatepickerMinimalPerf.default | [5461](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DatepickerMinimalPerf.default.html) | [5434](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1:1
GridMinimalPerf.default | [339](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/GridMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/GridMinimalPerf.default_base.html) | 1:1
ListNestedPerf.default | [557](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ListNestedPerf.default.html) | [556](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ListNestedPerf.default_base.html) | 1:1
SliderMinimalPerf.default | [1683](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/SliderMinimalPerf.default.html) | [1683](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1:1
SplitButtonMinimalPerf.default | [4368](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4349](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1:1
TableMinimalPerf.default | [421](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TableMinimalPerf.default.html) | [422](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TableMinimalPerf.default_base.html) | 1:1
CustomToolbarPrototype.default | [3949](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/CustomToolbarPrototype.default.html) | [3939](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1:1
AttachmentSlotsPerf.default | [1042](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1050](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 0.99:1
ButtonSlotsPerf.default | [561](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ButtonSlotsPerf.default.html) | [565](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 0.99:1
EmbedMinimalPerf.default | [4117](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/EmbedMinimalPerf.default.html) | [4173](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 0.99:1
HeaderMinimalPerf.default | [363](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/HeaderMinimalPerf.default.html) | [365](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1294](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/InputMinimalPerf.default.html) | [1312](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.99:1
ItemLayoutMinimalPerf.default | [1192](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1207](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 0.99:1
TextAreaMinimalPerf.default | [521](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TextAreaMinimalPerf.default.html) | [530](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 0.98:1
AnimationMinimalPerf.default | [529](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AnimationMinimalPerf.default.html) | [543](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 0.97:1
CardMinimalPerf.default | [545](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/CardMinimalPerf.default.html) | [561](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/CardMinimalPerf.default_base.html) | 0.97:1
DividerMinimalPerf.default | [369](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DividerMinimalPerf.default.html) | [381](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.97:1
SkeletonMinimalPerf.default | [342](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/SkeletonMinimalPerf.default.html) | [353](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 0.97:1
StatusMinimalPerf.default | [671](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/StatusMinimalPerf.default.html) | [691](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/StatusMinimalPerf.default_base.html) | 0.97:1
TextMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TextMinimalPerf.default.html) | [360](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.97:1
LayoutMinimalPerf.default | [365](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/LayoutMinimalPerf.default.html) | [382](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 0.96:1
ImageMinimalPerf.default | [362](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ImageMinimalPerf.default.html) | [381](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ImageMinimalPerf.default_base.html) | 0.95:1
VideoMinimalPerf.default | [577](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/VideoMinimalPerf.default.html) | [609](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/VideoMinimalPerf.default_base.html) | 0.95:1
RosterPerf.default | [1159](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/RosterPerf.default.html) | [1237](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/RosterPerf.default_base.html) | 0.94:1
IconMinimalPerf.default | [613](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/IconMinimalPerf.default.html) | [654](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.94:1
ChatWithPopoverPerf.default | [347](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ChatWithPopoverPerf.default.html) | [380](https://fluentuipr.z22.web.core.windows.net/pull/21505/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.91:1

</details><div id="perfComment9423"/>

**Review by andrefcdias — APPROVED** [review]
As always, great stuff. We really should start updating our templates FIRST when new standards are introduced to avoid creating these issues.
