### PR TITLE
v8 misc TS fixes for react 18

### LINKED ISSUE #24040: V8 Components do not all specify children in their types
In react 18, React.FC no longer assumes children as a prop, so they will need to be specified manually

https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc

### PR DESCRIPTION
**Pull request by micahgodbolt**
After temporarily changing react and TS version of React and Utilities to v18, I ran builds and looked at errors that will impact consumption. 

This was first pass to resolve some of those issues. 

resolves #24040

### CODE REVIEW

File: packages/react/src/components/Button/BaseButton.tsx [hunk 1]
```diff
@@ -482,7 +482,7 @@ export class BaseButton extends React.Component<IBaseButtonProps, IBaseButtonSta
 
   private _onRenderDescription = (props: IButtonProps) => {
     // eslint-disable-next-line deprecation/deprecation
-    const { secondaryText = this.props.description } = props;
```
Comment (micahgodbolt) [inline packages/react/src/components/Button/BaseButton.tsx:485]: this.props.description is of type IStyle. No idea why it was ever allowed as a default.

File: packages/react/src/components/Callout/CalloutContent.base.tsx [hunk 2]
```diff
@@ -425,7 +425,7 @@ export const CalloutContentBase: React.FunctionComponent<ICalloutProps> = React.
 
     const hostElement = React.useRef<HTMLDivElement>(null);
     const [calloutElement, setCalloutElement] = React.useState<HTMLDivElement | null>(null);
-    const calloutCallback = React.useCallback(calloutEl => {
+    const calloutCallback = React.useCallback((calloutEl: any) => {
```
Comment (micahgodbolt) [inline packages/react/src/components/Callout/CalloutContent.base.tsx:428]: v18 typings wasn't happy with this any being assumed

File: packages/react/src/components/DocumentCard/DocumentCardActions.base.tsx [hunk 3]
```diff
@@ -44,8 +44,10 @@ export class DocumentCardActionsBase extends React.Component<IDocumentCardAction
 
         {views! > 0 && (
           <div className={this._classNames.views}>
-            <Icon iconName="View" className={this._classNames.viewsIcon} />
-            {views}
+            <>
```
Comment (micahgodbolt) [inline packages/react/src/components/DocumentCard/DocumentCardActions.base.tsx:47]: This perplexed me a bit as the parent div only wanted a single child when views was a child

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/e6bec62689022606e64b56b90506c6d75cbdcfce'>e6bec62689022606e64b56b90506c6d75cbdcfce</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react/src/components/Button/BaseButton.tsx (hunk 1 above)
Comment (SahilTara) [reply packages/react/src/components/Button/BaseButton.tsx:485]: https://github.com/microsoft/fluentui/pull/4843 <-- seems to be from back then in case you were curious.

Comment (khmakoto) [reply packages/react/src/components/Button/BaseButton.tsx:485]: It seems like the more correct fix is to change the type of `description` to `string` in `Button.types.ts`. It seems like there was a mistake in typing it as `IStyle` since the PR @SahilTara points out based on the usage of the prop in `BaseButton`.

File: packages/react/src/components/Callout/CalloutContent.base.tsx (hunk 2 above)
Comment (micahgodbolt) [reply packages/react/src/components/Callout/CalloutContent.base.tsx:428]: no, it was okay with explicit anys, just not implicit ones

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/BaseButton-mount_base.html">938</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/BaseButton-mount.html">951</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Breadcrumb-mount_base.html">2784</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Breadcrumb-mount.html">2904</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Checkbox-mount_base.html">2672</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Checkbox-mount.html">2640</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/CheckboxBase-mount_base.html">2338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/CheckboxBase-mount.html">2353</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ChoiceGroup-mount_base.html">5017</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ChoiceGroup-mount.html">4923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ComboBox-mount_base.html">971</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ComboBox-mount.html">1016</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/CommandBar-mount_base.html">10959</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/CommandBar-mount.html">10892</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ContextualMenu-mount_base.html">12207</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ContextualMenu-mount.html">12226</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DefaultButton-mount_base.html">1195</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DefaultButton-mount.html">1186</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DetailsRow-mount_base.html">4018</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DetailsRow-mount.html">4064</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DetailsRowFast-mount_base.html">3946</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DetailsRowFast-mount.html">4069</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DetailsRowNoStyles-mount_base.html">3820</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DetailsRowNoStyles-mount.html">3779</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Dialog-mount_base.html">2899</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Dialog-mount.html">3000</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DocumentCardTitle-mount_base.html">186</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/DocumentCardTitle-mount.html">169</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Dropdown-mount_base.html">3490</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Dropdown-mount.html">3396</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/FocusTrapZone-mount_base.html">1911</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/FocusTrapZone-mount.html">1988</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/FocusZone-mount_base.html">1907</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/FocusZone-mount.html">1870</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/IconButton-mount_base.html">1847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/IconButton-mount.html">1873</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Label-mount_base.html">372</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Label-mount.html">384</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Layer-mount_base.html">3262</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Layer-mount.html">3184</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Link-mount_base.html">494</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Link-mount.html">494</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/MenuButton-mount_base.html">1521</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/MenuButton-mount.html">1522</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/MessageBar-mount_base.html">2232</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/MessageBar-mount.html">2214</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Nav-mount_base.html">3434</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Nav-mount.html">3412</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/OverflowSet-mount_base.html">1178</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/OverflowSet-mount.html">1152</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Panel-mount_base.html">2251</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Panel-mount.html">2251</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Persona-mount_base.html">1075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Persona-mount.html">1050</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Pivot-mount_base.html">1527</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Pivot-mount.html">1543</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/PrimaryButton-mount_base.html">1338</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/PrimaryButton-mount.html">1368</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Rating-mount_base.html">8038</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Rating-mount.html">8016</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/SearchBox-mount_base.html">1361</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/SearchBox-mount.html">1329</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Shimmer-mount_base.html">2555</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Shimmer-mount.html">2586</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Slider-mount_base.html">2004</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Slider-mount.html">1978</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/SpinButton-mount_base.html">5229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/SpinButton-mount.html">5198</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Spinner-mount_base.html">457</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Spinner-mount.html">464</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/SplitButton-mount_base.html">3271</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/SplitButton-mount.html">3576</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Stack-mount_base.html">546</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Stack-mount.html">563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/StackWithIntrinsicChildren-mount_base.html">2356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/StackWithIntrinsicChildren-mount.html">2350</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/StackWithTextChildren-mount_base.html">5503</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/StackWithTextChildren-mount.html">5463</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/SwatchColorPicker-mount_base.html">12078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/SwatchColorPicker-mount.html">12045</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/TagPicker-mount_base.html">2849</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/TagPicker-mount.html">2767</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/TeachingBubble-mount_base.html">97000</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/TeachingBubble-mount.html">95860</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Text-mount_base.html">438</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Text-mount.html">445</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/TextField-mount_base.html">1514</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/TextField-mount.html">1484</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ThemeProvider-mount_base.html">1247</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ThemeProvider-mount.html">1250</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ThemeProvider-virtual-rerender_base.html">682</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ThemeProvider-virtual-rerender.html">713</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">1842</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">1822</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Toggle-mount_base.html">809</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/Toggle-mount.html">832</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/buttonNative-mount_base.html">127</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24148/perf-test/buttonNative-mount.html">132</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

**Review by khmakoto — APPROVED** [review]
