### PR TITLE
fix: update implementation of getReactFiberFromNode to be compatible with React 17

### LINKED ISSUE #16192: Popper: throws an error in dev check
```
TypeError
Cannot read property 'pendingProps' of undefined
    at hasAutofocusProp (https://1xhm3.csb.app/node_modules/
fluentui/react-northstar/dist/es/utils/positioner/Popper.js:31:165
    at Object.hasAutofocusFilter [as acceptNode] (https://1xhm3.csb.app/node_modules/
fluentui/react-northstar/dist/es/utils/positioner/Popper.js:34:10
    at eval (https://1xhm3.csb.app/node_modules/
fluentui/react-northstar/dist/es/utils/positioner/Popper.js:46:27
```

### Environment Information

- **Package version(s)**: @fluentui/react-northstar@0.51.3 & react@17
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

Open a CodeSandbox: https://codesandbox.io/s/dry-hooks-1xhm3
Click on an input.

#### Actual behavior:
Throws an error.

#### Expected behavior:
Opens a Datepicker.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #16192.

---

In React 17 internal keys were changed (https://github.com/facebook/react/pull/18377), I performed a small refactor to extract shared code (`Popper` and `FiberNavigator`) to a single place and added unit tests. Also manually tested with React 17.

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Avatar-mount_base.html">898</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Avatar-mount.html">900</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/BaseButtonCompat-mount_base.html">1015</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/BaseButtonCompat-mount.html">1025</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Breadcrumb-mount_base.html">44490</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Breadcrumb-mount.html">43942</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Checkbox-mount_base.html">1581</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Checkbox-mount.html">1645</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/CheckboxBase-mount_base.html">1355</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/CheckboxBase-mount.html">1360</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ChoiceGroup-mount_base.html">4996</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ChoiceGroup-mount.html">5001</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ComboBox-mount_base.html">1022</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ComboBox-mount.html">1003</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/CommandBar-mount_base.html">10262</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/CommandBar-mount.html">10208</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ContextualMenu-mount_base.html">6176</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ContextualMenu-mount.html">6106</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DefaultButtonCompat-mount_base.html">1179</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DefaultButtonCompat-mount.html">1238</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DetailsRow-mount_base.html">3846</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DetailsRow-mount.html">3820</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DetailsRowFast-mount_base.html">3863</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DetailsRowFast-mount.html">3948</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DetailsRowNoStyles-mount_base.html">3622</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DetailsRowNoStyles-mount.html">3702</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Dialog-mount_base.html">1512</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Dialog-mount.html">1510</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DocumentCardTitle-mount_base.html">1883</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/DocumentCardTitle-mount.html">1860</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Dropdown-mount_base.html">3587</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Dropdown-mount.html">3541</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/FocusTrapZone-mount_base.html">1887</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/FocusTrapZone-mount.html">1861</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/FocusZone-mount_base.html">1882</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/FocusZone-mount.html">1960</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/IconButtonCompat-mount_base.html">1989</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/IconButtonCompat-mount.html">1983</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Label-mount_base.html">346</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Label-mount.html">366</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Layer-mount_base.html">1951</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Layer-mount.html">1969</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Link-mount_base.html">503</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Link-mount.html">496</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/MakeStyles-mount_base.html">2008</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/MakeStyles-mount.html">2126</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/MenuButtonCompat-mount_base.html">1639</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/MenuButtonCompat-mount.html">1642</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/MessageBar-mount_base.html">2152</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/MessageBar-mount.html">2195</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Nav-mount_base.html">3667</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Nav-mount.html">3508</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/OverflowSet-mount_base.html">1122</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/OverflowSet-mount.html">1155</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Panel-mount_base.html">1529</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Panel-mount.html">1487</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Persona-mount_base.html">945</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Persona-mount.html">954</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Pivot-mount_base.html">1538</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Pivot-mount.html">1558</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/PrimaryButtonCompat-mount_base.html">1418</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/PrimaryButtonCompat-mount.html">1440</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Rating-mount_base.html">8488</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Rating-mount.html">8391</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/SearchBox-mount_base.html">1504</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/SearchBox-mount.html">1495</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Shimmer-mount_base.html">2820</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Shimmer-mount.html">2822</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Slider-mount_base.html">1960</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Slider-mount.html">2120</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/SpinButton-mount_base.html">5177</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/SpinButton-mount.html">5236</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Spinner-mount_base.html">424</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Spinner-mount.html">433</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/SplitButtonCompat-mount_base.html">3278</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/SplitButtonCompat-mount.html">3360</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Stack-mount_base.html">520</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Stack-mount.html">530</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/StackWithIntrinsicChildren-mount_base.html">1662</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/StackWithIntrinsicChildren-mount.html">1635</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/StackWithTextChildren-mount_base.html">4747</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/StackWithTextChildren-mount.html">4853</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/SwatchColorPicker-mount_base.html">10752</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/SwatchColorPicker-mount.html">10568</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Tabs</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Tabs-mount_base.html">1470</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Tabs-mount.html">1439</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/TagPicker-mount_base.html">2886</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/TagPicker-mount.html">2895</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/TeachingBubble-mount_base.html">12127</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/TeachingBubble-mount.html">11980</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Text-mount_base.html">462</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Text-mount.html">445</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/TextField-mount_base.html">1498</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/TextField-mount.html">1497</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ThemeProvider-mount_base.html">2166</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ThemeProvider-mount.html">2181</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ThemeProvider-virtual-rerender_base.html">638</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/ThemeProvider-virtual-rerender.html">652</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Toggle-mount_base.html">832</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/Toggle-mount.html">838</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>button</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/button-mount_base.html">725</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/button-mount.html">676</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/buttonNative-mount_base.html">126</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test/buttonNative-mount.html">114</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

## Perf Analysis (Fluent)
:warning: 1 potential perf regressions detected

### Potential regressions comparing to master

Scenario | Current PR Ticks | Baseline Ticks | Ratio | Regression Analysis
:--- | ---:| ---:| ---: | ---: 
PortalMinimalPerf.default | [170](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/PortalMinimalPerf.default.html) | [169](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.01:1 | [analysis](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/PortalMinimalPerf.default.regression.txt)
<details><summary>Perf comparison</summary>

Status | Scenario | Fluent TPI | Fabric TPI | Ratio | Iterations | Ticks
:---: | :--- | ---:| ---:| ---:| ---:| ---:
🎯 | Avatar.Fluent | [0.5](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Avatar.Fluent.html) | 0.56 | 0.89:1 | 2000 | 990
🦄 | Button.Fluent | [0.14](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Button.Fluent.html) | 0.23 | 0.61:1 | 5000 | 708
🔧 | Checkbox.Fluent | [0.73](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Checkbox.Fluent.html) | 0.4 | 1.83:1 | 1000 | 726
🎯 | Dialog.Fluent | [0.18](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Dialog.Fluent.html) | 0.24 | 0.75:1 | 5000 | 894
🔧 | Dropdown.Fluent | [3.12](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Dropdown.Fluent.html) | 0.44 | 7.09:1 | 1000 | 3123
🔧 | Icon.Fluent | [0.15](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Icon.Fluent.html) | 0.06 | 2.5:1 | 5000 | 767
🦄 | Image.Fluent | [0.09](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Image.Fluent.html) | 0.13 | 0.69:1 | 5000 | 437
🔧 | Slider.Fluent | [1.64](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Slider.Fluent.html) | 0.47 | 3.49:1 | 1000 | 1641
🔧 | Text.Fluent | [0.08](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Text.Fluent.html) | 0.03 | 2.67:1 | 5000 | 421
🦄 | Tooltip.Fluent | [0.12](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Tooltip.Fluent.html) | 0.91 | 0.13:1 | 5000 | 621
>🔧 Needs work &nbsp; &nbsp; 🎯 On target &nbsp; &nbsp; 🦄 Amazing

</details>
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
Icon.Fluent | [767](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Icon.Fluent.html) | [706](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Icon.Fluent_base.html) | 1.09:1
ButtonMinimalPerf.default | [210](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonMinimalPerf.default.html) | [194](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.08:1
ImageMinimalPerf.default | [473](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ImageMinimalPerf.default.html) | [439](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.08:1
Button.Fluent | [708](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Button.Fluent.html) | [662](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Button.Fluent_base.html) | 1.07:1
AnimationMinimalPerf.default | [453](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AnimationMinimalPerf.default.html) | [426](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AnimationMinimalPerf.default_base.html) | 1.06:1
AttachmentSlotsPerf.default | [1318](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1247](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.06:1
StatusMinimalPerf.default | [867](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/StatusMinimalPerf.default.html) | [815](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.06:1
Tooltip.Fluent | [621](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Tooltip.Fluent.html) | [585](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Tooltip.Fluent_base.html) | 1.06:1
AccordionMinimalPerf.default | [187](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AccordionMinimalPerf.default.html) | [178](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.05:1
ChatMinimalPerf.default | [704](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ChatMinimalPerf.default.html) | [673](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.05:1
FlexMinimalPerf.default | [336](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/FlexMinimalPerf.default.html) | [320](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.05:1
ListNestedPerf.default | [647](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ListNestedPerf.default.html) | [618](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ListNestedPerf.default_base.html) | 1.05:1
Checkbox.Fluent | [726](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Checkbox.Fluent.html) | [694](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Checkbox.Fluent_base.html) | 1.05:1
AttachmentMinimalPerf.default | [187](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AttachmentMinimalPerf.default.html) | [179](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.04:1
ButtonSlotsPerf.default | [664](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonSlotsPerf.default.html) | [641](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
ButtonUseCssPerf.default | [867](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonUseCssPerf.default.html) | [836](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonUseCssPerf.default_base.html) | 1.04:1
HeaderMinimalPerf.default | [451](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/HeaderMinimalPerf.default.html) | [435](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.04:1
SliderMinimalPerf.default | [1680](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/SliderMinimalPerf.default.html) | [1618](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.04:1
TableMinimalPerf.default | [492](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TableMinimalPerf.default.html) | [472](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.04:1
Dialog.Fluent | [894](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Dialog.Fluent.html) | [863](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Dialog.Fluent_base.html) | 1.04:1
Slider.Fluent | [1641](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Slider.Fluent.html) | [1574](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Slider.Fluent_base.html) | 1.04:1
Text.Fluent | [421](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Text.Fluent.html) | [404](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Text.Fluent_base.html) | 1.04:1
ItemLayoutMinimalPerf.default | [1450](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1402](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.03:1
ProviderMergeThemesPerf.default | [1620](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1569](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.03:1
ReactionMinimalPerf.default | [470](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ReactionMinimalPerf.default.html) | [455](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.03:1
RefMinimalPerf.default | [266](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/RefMinimalPerf.default.html) | [258](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.03:1
VideoMinimalPerf.default | [739](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/VideoMinimalPerf.default.html) | [719](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.03:1
Dropdown.Fluent | [3123](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Dropdown.Fluent.html) | [3042](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Dropdown.Fluent_base.html) | 1.03:1
ButtonOverridesMissPerf.default | [1774](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1740](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.02:1
DatepickerMinimalPerf.default | [49570](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DatepickerMinimalPerf.default.html) | [48427](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DatepickerMinimalPerf.default_base.html) | 1.02:1
GridMinimalPerf.default | [397](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/GridMinimalPerf.default.html) | [390](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.02:1
LayoutMinimalPerf.default | [472](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/LayoutMinimalPerf.default.html) | [462](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [548](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ListMinimalPerf.default.html) | [535](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
AlertMinimalPerf.default | [332](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AlertMinimalPerf.default.html) | [329](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.01:1
BoxMinimalPerf.default | [419](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/BoxMinimalPerf.default.html) | [413](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.01:1
ButtonUseCssNestingPerf.default | [1139](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonUseCssNestingPerf.default.html) | [1131](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ButtonUseCssNestingPerf.default_base.html) | 1.01:1
CardMinimalPerf.default | [622](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/CardMinimalPerf.default.html) | [618](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/CardMinimalPerf.default_base.html) | 1.01:1
CheckboxMinimalPerf.default | [2973](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2937](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.01:1
DropdownMinimalPerf.default | [3091](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DropdownMinimalPerf.default.html) | [3047](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.01:1
EmbedMinimalPerf.default | [4341](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/EmbedMinimalPerf.default.html) | [4313](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/EmbedMinimalPerf.default_base.html) | 1.01:1
LabelMinimalPerf.default | [481](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/LabelMinimalPerf.default.html) | [474](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/LabelMinimalPerf.default_base.html) | 1.01:1
ListCommonPerf.default | [717](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ListCommonPerf.default.html) | [708](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
SkeletonMinimalPerf.default | [428](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/SkeletonMinimalPerf.default.html) | [423](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [2372](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TableManyItemsPerf.default.html) | [2342](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
CustomToolbarPrototype.default | [4032](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/CustomToolbarPrototype.default.html) | [3990](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.01:1
ToolbarMinimalPerf.default | [1086](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ToolbarMinimalPerf.default.html) | [1074](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ToolbarMinimalPerf.default_base.html) | 1.01:1
TooltipMinimalPerf.default | [909](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TooltipMinimalPerf.default.html) | [904](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TooltipMinimalPerf.default_base.html) | 1.01:1
ChatDuplicateMessagesPerf.default | [440](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [440](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1:1
DialogMinimalPerf.default | [884](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DialogMinimalPerf.default.html) | [880](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1:1
HeaderSlotsPerf.default | [912](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/HeaderSlotsPerf.default.html) | [914](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1:1
MenuButtonMinimalPerf.default | [1733](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1726](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1:1
PopupMinimalPerf.default | [747](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/PopupMinimalPerf.default.html) | [747](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1:1
ProviderMinimalPerf.default | [945](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ProviderMinimalPerf.default.html) | [946](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1:1
SegmentMinimalPerf.default | [412](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/SegmentMinimalPerf.default.html) | [414](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1:1
TextAreaMinimalPerf.default | [601](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TextAreaMinimalPerf.default.html) | [601](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1:1
TreeWith60ListItems.default | [227](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TreeWith60ListItems.default.html) | [227](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1:1
CarouselMinimalPerf.default | [476](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/CarouselMinimalPerf.default.html) | [481](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 0.99:1
ChatWithPopoverPerf.default | [488](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ChatWithPopoverPerf.default.html) | [491](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 0.99:1
DropdownManyItemsPerf.default | [801](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DropdownManyItemsPerf.default.html) | [809](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 0.99:1
LoaderMinimalPerf.default | [749](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/LoaderMinimalPerf.default.html) | [757](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 0.99:1
MenuMinimalPerf.default | [939](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/MenuMinimalPerf.default.html) | [949](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/MenuMinimalPerf.default_base.html) | 0.99:1
SplitButtonMinimalPerf.default | [4109](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [4135](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 0.99:1
IconMinimalPerf.default | [780](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/IconMinimalPerf.default.html) | [788](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/IconMinimalPerf.default_base.html) | 0.99:1
TextMinimalPerf.default | [419](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TextMinimalPerf.default.html) | [422](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TextMinimalPerf.default_base.html) | 0.99:1
InputMinimalPerf.default | [1386](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/InputMinimalPerf.default.html) | [1420](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/InputMinimalPerf.default_base.html) | 0.98:1
ListWith60ListItems.default | [962](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ListWith60ListItems.default.html) | [983](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/ListWith60ListItems.default_base.html) | 0.98:1
TreeMinimalPerf.default | [864](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TreeMinimalPerf.default.html) | [880](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/TreeMinimalPerf.default_base.html) | 0.98:1
Avatar.Fluent | [990](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Avatar.Fluent.html) | [1016](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Avatar.Fluent_base.html) | 0.97:1
FormMinimalPerf.default | [463](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/FormMinimalPerf.default.html) | [488](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/FormMinimalPerf.default_base.html) | 0.95:1
RadioGroupMinimalPerf.default | [492](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [516](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 0.95:1
AvatarMinimalPerf.default | [501](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AvatarMinimalPerf.default.html) | [531](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 0.94:1
DividerMinimalPerf.default | [430](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DividerMinimalPerf.default.html) | [457](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/DividerMinimalPerf.default_base.html) | 0.94:1
Image.Fluent | [437](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Image.Fluent.html) | [485](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16392/merge/perf-test-northstar/Image.Fluent_base.html) | 0.9:1

</details><div id="perfComment9423"/>

File: packages/fluentui/react-northstar/src/utils/getReactFiberFromNode.ts [hunk 1]
```diff
@@ -0,0 +1,259 @@
...
+  for (const k in elm) {
+    // React 16 uses "__reactInternalInstance$" prefix
+    // React 17 uses "__reactFiber$" prefix
+    // https://github.com/facebook/react/pull/18377
+    if (k.indexOf('__reactInternalInstance$') === 0 || k.indexOf('__reactFiber$') === 0) {
+      return elm[k];
+    }
+  }
+
+  throw new Error('getReactFiber(): Failed to find a React Fiber on a node');
```
Comment (ling1726) [inline packages/fluentui/react-northstar/src/utils/getReactFiberFromNode.ts:258]: nit: consider having a test case for the throw

**Review by ling1726 — APPROVED** [review]

File: packages/fluentui/react-northstar/src/utils/getReactFiberFromNode.ts (hunk 1 above)
Comment (layershifter) [reply packages/fluentui/react-northstar/src/utils/getReactFiberFromNode.ts:258]: Added 👍

**Comment by sushruth** [comment]
Which version of @fluentui/react-northstar will have this fix? Currently this is affecting unit tests when using react 17.
