### PR TITLE
Details list fix exports

### LINKED ISSUE #22989: DetailsList missing export of DetailColumn
## Problem
DetailsColumn and some other types, constants, and methods were previously implicitly exported from the react package.  They could be deep imported.  With https://github.com/microsoft/fluentui/pull/21508 exports had to be explicit.

This prevents customers from using previously exported parts of DetailsList.

### PR DESCRIPTION
**Pull request by GeoffCoxMSFT**
https://github.com/microsoft/fluentui/pull/21508 moved to explicit exports, this removed some exports from v8 components that could previously be deep imported.

## Change
- Updated to explicitly export previously exported for  deep imports
- Because DetailsRow exported styles, exported other styles.  Renamed getStyles to specific names to avoid collisions.  This will allow for custom styled extended components to be authored.

## Issues
Fixes #22989

### CODE REVIEW

File: packages/react/src/components/DetailsList/index.ts [hunk 1]
```diff
@@ -2,18 +2,25 @@ export * from '../../Selection';
 export * from '../GroupedList/GroupedList.types';
 export * from './DetailsHeader';
 export * from './DetailsHeader.base';
+export * from './DetailsHeader.styles';
```
Comment (GeoffCoxMSFT) [inline packages/react/src/components/DetailsList/index.ts:5]: Because DetailsRow exported styles, I exported the other styles for consistency and to ensure callers could use those style functions if they want to extend the base class with styled<>.  I had to rename the getStyles calls to be specific to the component to avoid name collisions.

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/12994b576bd9d9e5d7a29fc4fc7ccf2123115a8f'>12994b576bd9d9e5d7a29fc4fc7ccf2123115a8f</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/BaseButton-mount_base.html">1072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/BaseButton-mount.html">1052</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Breadcrumb-mount_base.html">3025</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Breadcrumb-mount.html">3016</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Checkbox-mount_base.html">1752</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Checkbox-mount.html">1690</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/CheckboxBase-mount_base.html">1459</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/CheckboxBase-mount.html">1469</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ChoiceGroup-mount_base.html">5435</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ChoiceGroup-mount.html">5429</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ComboBox-mount_base.html">1078</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ComboBox-mount.html">1154</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/CommandBar-mount_base.html">11179</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/CommandBar-mount.html">11208</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ContextualMenu-mount_base.html">12098</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ContextualMenu-mount.html">11988</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DefaultButton-mount_base.html">1305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DefaultButton-mount.html">1309</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DetailsRow-mount_base.html">4363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DetailsRow-mount.html">4279</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DetailsRowFast-mount_base.html">4392</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DetailsRowFast-mount.html">4326</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DetailsRowNoStyles-mount_base.html">4022</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DetailsRowNoStyles-mount.html">4030</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Dialog-mount_base.html">2464</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Dialog-mount.html">2475</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DocumentCardTitle-mount_base.html">206</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/DocumentCardTitle-mount.html">199</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Dropdown-mount_base.html">3690</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Dropdown-mount.html">3752</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/FocusTrapZone-mount_base.html">2082</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/FocusTrapZone-mount.html">2043</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/FocusZone-mount_base.html">1973</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/FocusZone-mount.html">1989</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/IconButton-mount_base.html">2025</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/IconButton-mount.html">2024</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Label-mount_base.html">370</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Label-mount.html">389</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Layer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Layer-mount_base.html">3277</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Layer-mount.html">3307</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Link</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Link-mount_base.html">547</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Link-mount.html">533</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MenuButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/MenuButton-mount_base.html">1733</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/MenuButton-mount.html">1697</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>MessageBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/MessageBar-mount_base.html">2364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/MessageBar-mount.html">2315</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Nav</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Nav-mount_base.html">3651</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Nav-mount.html">3751</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>OverflowSet</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/OverflowSet-mount_base.html">1212</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/OverflowSet-mount.html">1222</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Panel</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Panel-mount_base.html">2346</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Panel-mount.html">2342</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Persona-mount_base.html">1149</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Persona-mount.html">1168</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Pivot</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Pivot-mount_base.html">1626</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Pivot-mount.html">1601</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>PrimaryButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/PrimaryButton-mount_base.html">1505</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/PrimaryButton-mount.html">1467</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Rating</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Rating-mount_base.html">8949</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Rating-mount.html">9111</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SearchBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/SearchBox-mount_base.html">1541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/SearchBox-mount.html">1577</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Shimmer</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Shimmer-mount_base.html">2875</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Shimmer-mount.html">2797</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Slider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Slider-mount_base.html">2131</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Slider-mount.html">2187</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/SpinButton-mount_base.html">5692</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/SpinButton-mount.html">5542</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Spinner</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Spinner-mount_base.html">500</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Spinner-mount.html">473</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SplitButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/SplitButton-mount_base.html">3572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/SplitButton-mount.html">3544</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Stack</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Stack-mount_base.html">607</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Stack-mount.html">595</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithIntrinsicChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/StackWithIntrinsicChildren-mount_base.html">2940</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/StackWithIntrinsicChildren-mount.html">2814</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>StackWithTextChildren</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/StackWithTextChildren-mount_base.html">6301</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/StackWithTextChildren-mount.html">6247</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchColorPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/SwatchColorPicker-mount_base.html">12788</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/SwatchColorPicker-mount.html">12894</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TagPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/TagPicker-mount_base.html">2999</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/TagPicker-mount.html">3161</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TeachingBubble</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/TeachingBubble-mount_base.html">99666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/TeachingBubble-mount.html">100569</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Text</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Text-mount_base.html">474</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Text-mount.html">511</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>TextField</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/TextField-mount_base.html">1624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/TextField-mount.html">1659</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ThemeProvider-mount_base.html">1318</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ThemeProvider-mount.html">1288</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ThemeProvider-virtual-rerender_base.html">694</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ThemeProvider-virtual-rerender.html">707</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ThemeProvider</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ThemeProvider-virtual-rerender-with-unmount_base.html">2105</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/ThemeProvider-virtual-rerender-with-unmount.html">2171</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Toggle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Toggle-mount_base.html">917</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/Toggle-mount.html">883</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>buttonNative</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/buttonNative-mount_base.html">134</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22990/perf-test/buttonNative-mount.html">141</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9423"/>

File: packages/react/src/components/DetailsList/index.ts (hunk 1 above)
Comment (sopranopillow) [reply packages/react/src/components/DetailsList/index.ts:5]: Should these also have _unstable? like `useTextareaStyles_unstable`

**Review by sopranopillow — APPROVED** [review]

File: packages/react/src/components/DetailsList/index.ts (hunk 1 above)
Comment (GeoffCoxMSFT) [reply packages/react/src/components/DetailsList/index.ts:5]: No - that is a v9 thing.  These are all stable.

**Review by spmonahan — APPROVED** [review]
