### PR TITLE
fix(react-combobox): close controlled dropdown by clicking outside

### LINKED ISSUE #30045: [Bug]: open-state-controlled Dropdown cannot get dismissed by clicking outside the dropdown button
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components": "^9.42.0",

Using CodeSandbox
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/sandbox/open-controlled-dropdown-w4rfn4?file=%2Fpackage.json%3A5%2C5-5%2C45

## Actual Behavior
Recording_20231212T204611

## Expected Behavior

I should be able to dismiss the dropdown box by clicking outside the dropdown component, even if it is opened by clicking "Open dropdown" button.

### Logs

_No response_

### Requested priority

Normal

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by dmytrokirpa**
## Previous Behavior

Controlled dropdown & combobox cannot get dismissed by clicking outside

## New Behavior

Controlled dropdown & combobox get dismissed by clicking outside

## Related Issue(s)

- Fixes #30045

### CODE REVIEW

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/Avatar-mount_base.html">642</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/Avatar-mount.html">623</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/Button-mount_base.html">305</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/Button-mount.html">299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/Field-mount_base.html">1154</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/Field-mount.html">1133</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/FluentProvider-mount_base.html">715</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/FluentProvider-mount.html">709</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/FluentProviderWithTheme-mount_base.html">80</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/FluentProviderWithTheme-mount.html">83</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">32</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">31</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">75</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">70</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/MakeStyles-mount_base.html">885</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/MakeStyles-mount.html">864</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/Persona-mount_base.html">1759</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/Persona-mount.html">1777</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/SpinButton-mount_base.html">1366</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/SpinButton-mount.html">1463</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/SwatchPicker-mount_base.html">1624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31786/perf-test-react-components/SwatchPicker-mount.html">1679</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

**Comment by fabricteam** [comment]
## 📊 Bundle size report

| Package & Exports | Baseline (minified/GZIP) | PR    | Change     |
| :---------------- | -----------------------: | ----: | ---------: |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr> | `101.39 kB`<br />`33.324 kB` | `103.465 kB`<br />`33.926 kB` | `2.075 kB` <br />`602 B` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr> | `102.028 kB`<br />`33.263 kB` | `104.092 kB`<br />`33.849 kB` | `2.064 kB` <br />`586 B` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ReactComponents.fixture.js'>react-components: entire library</abbr> | `1.094 MB`<br />`270.597 kB` | `1.094 MB`<br />`270.66 kB` | `191 B` <br />`63 B` |
| <samp>react-timepicker-compat</samp> <br /> <abbr title='bundle-size/TimePicker.fixture.js'>TimePicker</abbr> | `104.384 kB`<br />`34.782 kB` | `106.453 kB`<br />`35.451 kB` | `2.069 kB` <br />`669 B` |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports | Size (minified/GZIP) |
| ----------------- | -------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr> | `69.141 kB`<br />`20.157 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `211.741 kB`<br />`60.957 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `44.442 kB`<br />`14.607 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr> | `8.39 kB`<br />`2.64 kB` |
| <samp>react-tag-picker</samp> <br /> <abbr title='bundle-size/Package.fixture.js'>@fluentui/react-tag-picker - package</abbr> | `181.135 kB`<br />`54.462 kB` |
</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/d4173353dcf956e12700add74e1d258c24b4112b'>d4173353dcf956e12700add74e1d258c24b4112b</a></sub>
<div id="bundleSizeComment9423"/>

File: packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx [hunk 1]
```diff
@@ -9,11 +9,13 @@ import {
   useId,
```
Comment (fabricteam) [inline packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx:9]: ## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=31786&commitId=0d4952ba12ba081a20045ae8de95db30700a3e6b&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar Converged</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.size+image+badge.normal.chromium.png|0| Added|

</details>


  <details><summary><b>Card Converged - Interactive</b> 12 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Card Converged - Interactive.appearance interactive - Filled Alternative - High Contrast.click.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled Alternative - High Contrast.hover.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled Alternative - High Contrast.normal.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled Alternative.click.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled Alternative.hover.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled Alternative.normal.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled - High Contrast.click.chromium.png|0| Removed|
|Card Converged - Interactive.appearance interactive - Filled - High Contrast.hover.chromium.png|0| Removed|
|Card Converged - Interactive.appearance interactive - Filled - High Contrast.normal.chromium.png|0| Removed|
|Card Converged - Interactive.appearance interactive - Filled Alternative - Dark Mode.click.chromium.png|0| Removed|
|Card Converged - Interactive.appearance interactive - Filled Alternative - Dark Mode.hover.chromium.png|0| Removed|
|Card Converged - Interactive.appearance interactive - Filled Alternative - Dark Mode.normal.chromium.png|0| Removed|

</details>


  <details><summary><b>SwatchPicker Converged</b> 3 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|SwatchPicker Converged.Spacing.default.chromium.png|0| Added|
|SwatchPicker Converged.default - RTL.default.chromium.png|0| Added|
|SwatchPicker Converged.spacing.default.chromium.png|0| Added|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

**Comment by mainframev** [comment]
@dmytrokirpa 

I think storybook example should be adjusted with focus, in controlled case it's not automatically focused, so later key navigation is not possible and when hitting ESC it's not closing  🙂

**Comment by dmytrokirpa** [comment]
> @dmytrokirpa
> 
> I think storybook example should be adjusted with focus, in controlled case it's not automatically focused, so later key navigation is not possible and when hitting ESC it's not closing 🙂

Nice catch, thank you @mainframev. I've aded focus management to new stories.

File: packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts [hunk 2]
```diff
@@ -178,6 +178,7 @@ export const useListbox_unstable = (props: ListboxProps, ref: React.Ref<HTMLElem
     };
 
     // this should only be run once in the lifecycle of the Listbox
+    // eslint-disable-next-line react-compiler/react-compiler
```
Comment (dmytrokirpa) [inline packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts:181]: The issue i unrelated to the PR changes; it's likely that the eslint configuration or dependencies were updated.

File: packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx [hunk 3]
```diff
@@ -112,6 +115,15 @@ export const useCombobox_unstable = (props: ComboboxProps, ref: React.Ref<HTMLIn
     ...baseState,
   };
 
+  const { targetDocument } = useFluent();
+
+  useOnClickOutside({
```
Comment (ling1726) [inline packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx:120]: @smhigley  now that outside click handling is a requirement, is there still a need to handle open/close with focus/blur?

File: packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+  const ref = React.useRef<HTMLInputElement>(null);
+  const [open, setOpen] = React.useState(false);
+  const handleOpenChange: ComboboxProps['onOpenChange'] = (e, data) => setOpen(data.open || false);
+
+  const onChange: CheckboxProps['onChange'] = (e, { checked }) => {
+    const isOpen = Boolean(checked) || false;
+    setOpen(isOpen);
+
+    if (isOpen) {
+      ref.current?.focus();
```
Comment (ling1726) [inline packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx:30]: If the requirement is that users focus on the combobox after opening it from another trigger element, then the changes in this PR are actually not required. The combobox/dropdown already handles closing with blur.

You can actually remove your changes and notice that this example still functions as expected

File: packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+        open={open}
+        onOpenChange={handleOpenChange}
+      >
+        {options.map(option => (
+          <Option key={option} disabled={option === 'Ferret'}>
+            {option}
+          </Option>
+        ))}
+      </Combobox>
+      <Checkbox value="open" name="state" label="open" checked={open} onChange={onChange} />
```
Comment (ling1726) [inline packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx:52]: I'd move the checkbox above or to the side of the combobox since it's immediately covered when opening for me
combobox covering

File: packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts (hunk 2 above)
Comment (ling1726) [reply packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts:181]: it could be merge race condition, if you revert this change will the build break?

File: packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx (hunk 4 above)
Comment (dmytrokirpa) [reply packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx]: This change is related to [a this comment](https://github.com/microsoft/fluentui/pull/31786#issuecomment-2183909714)

I removed the blur part, thought.

File: packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx (hunk 5 above)
Comment (dmytrokirpa) [reply packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx]: Updated

File: packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx (hunk 4 above)
Comment (ling1726) [reply packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx]: if moving focus is a requirement, then is `onClickOutside` needed at all? Are there any legit use cases where you would open a dropdown from another trigger and not move focus? 

since a click outside will immediately blur the control and close it currently

Comment (dmytrokirpa) [reply packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx]: > if moving focus is a requirement, then is onClickOutside needed at all? Are there any legit use cases where you would open a dropdown from another trigger and not move focus?

The decision to move focus rests with the component consumer. The `onClickOutside` handler is necessary when the combobox/dropdown is open but not in focus, akin to the behavior of a popover as demonstrated [here](https://react.fluentui.dev/?path=/docs/components-popover--default#controlling-open-and-close).

File: packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts (hunk 2 above)
Comment (spmonahan) [reply packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts]: This is fixed by #31795

For future reference we're using the `'use no memo'` directive as that instructs React Compiler to ignore this code and also disables the linter. This is nice because it better ensures no breakage for downstream Compiler users and gives us a nice, findable string for potential future improvements/fixes.

File: packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx [hunk 6]
```diff
@@ -112,6 +115,18 @@ export const useCombobox_unstable = (props: ComboboxProps, ref: React.Ref<HTMLIn
...
+    element: targetDocument,
+    callback: event => {
+      event.preventDefault();
+      setOpen(event as unknown as ComboboxOpenEvents, false);
```
Comment (marcosmoura) [inline packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx:124]: Is this typecast necessary? The event param that the `callback` exposes has a `MouseEvent` type and that should be compatible with `ComboboxOpenEvents`, no?

File: packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx [hunk 7]
```diff
@@ -59,6 +62,18 @@ export const useDropdown_unstable = (props: DropdownProps, ref: React.Ref<HTMLBu
     },
   });
 
+  const { targetDocument } = useFluent();
+
+  useOnClickOutside({
+    element: targetDocument,
+    callback: event => {
+      event.preventDefault();
+      setOpen(event as unknown as ComboboxOpenEvents, false);
```
Comment (marcosmoura) [inline packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx:71]: Same here

File: packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx (hunk 6 above)
Comment (marcosmoura) [reply packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx:124]: Fair enough. :)

**Review by marcosmoura — APPROVED** [review]

File: packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx (hunk 4 above)
Comment (ling1726) [reply packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx]: Yeah it makes sense when you remove the `.focus`. I was confused as to whether it's a requirement for users to do focusing in this scenario at all.

If it's not then I agree with the change :)

File: packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx [hunk 8]
```diff
@@ -59,6 +62,18 @@ export const useDropdown_unstable = (props: DropdownProps, ref: React.Ref<HTMLBu
     },
   });
 
+  const { targetDocument } = useFluent();
+
+  useOnClickOutside({
```
Comment (ling1726) [inline packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx:67]: Please add a cypress tests for this change. There are none currently, and it would be nice to start building them up because this control is getting more complex and still has no e2e testing.

No need to do test everything! just this behaviour

**Review by ling1726 — APPROVED** [review]

File: packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx (hunk 8 above)
Comment (ling1726) [reply packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx:67]: Setting it up should be quite easy https://github.com/microsoft/fluentui/tree/master/tools/workspace-plugin/src/generators/cypress-component-configuration

File: packages/react-components/react-combobox/stories/src/utils/useDebounce.ts [hunk 9]
```diff
@@ -0,0 +1,15 @@
+import * as React from 'react';
```
Comment (spmonahan) [inline packages/react-components/react-combobox/stories/src/utils/useDebounce.ts:1]: Seems like a good thing to add to [react-utilities](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-utilities/src/hooks).

:)

**Review by spmonahan — APPROVED** [review]

File: packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx [hunk 10]
```diff
@@ -0,0 +1,63 @@
+import * as React from 'react';
+import { Checkbox, Combobox, makeStyles, Option, useId } from '@fluentui/react-components';
+import type { CheckboxProps, ComboboxProps } from '@fluentui/react-components';
+
+import { useDebounce } from '../utils/useDebounce';
```
Comment (layershifter) [inline packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx:5]: FYI This will be a broken story on Stackblitz as we export only a story file itself:

image

Comment (ling1726) [reply packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx:5]: This seems to be added in  5975186c3f2b74e645a8e1d6bce98f3e73aabe95 under addressing PR issues. @dmytrokirpa why was this added?

Comment (dmytrokirpa) [reply packages/react-components/react-combobox/stories/src/Combobox/ComboboxControllingOpenAndClose.stories.tsx:5]: This modification was implemented to tackle a problem similar to [this one](https://github.com/microsoft/fluentui/issues/30045#issuecomment-1854465903), where opening the combobox/dropdown and clicking on the checkbox triggers two simultaneous actions: the dropdown closes due to an outside click, and then reopens because of the checkbox click.

I'm open to suggestions for a better options than `useDebounce`, or I could transfer it to `react-utilities` as @spmonahan  suggested, and it should solve the issue @layershifter raised. @ling1726 WDYT?

File: packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx (hunk 8 above)
Comment (dmytrokirpa) [reply packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx:67]: Added e2e tests to both Combobox and Dropdown components

File: packages/react-components/react-combobox/stories/src/utils/useDebounce.ts (hunk 9 above)
Comment (dmytrokirpa) [reply packages/react-components/react-combobox/stories/src/utils/useDebounce.ts]: Done
