### PR TITLE
fix: update FluentProvider to fix text direction in styles

### LINKED ISSUE #22930: [Bug]: direction is not respected by FluentProvider styles
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

### Bug Description

Add `textAlign` in `useStyles` (`packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderStyles.ts`) 

```diff
const useStyles = makeStyles({
  root: {
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground1,
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightRegular,
+   textAlign: 'left',
  },
});
```

Add a test:

```tsx
  describe('applies "dir" attribute', () => {
    it('ltr', () => {
      const { getByText } = render(<FluentProvider dir="ltr">Test</FluentProvider>);
      const element = getByText('Test');

      expect(element).toHaveAttribute('dir', 'ltr');
      expect(element).toHaveStyle({ textAlign: 'left' });
    });

    it('rtl', () => {
      const { getByText } = render(<FluentProvider dir="rtl">Test</FluentProvider>);
      const element = getByText('Test');

      expect(element).toHaveAttribute('dir', 'rtl');
      expect(element).toHaveStyle({ textAlign: 'right' });
    });
  });
```

## Actual Behavior

Test fails ❌

```
Error: expect(element).toHaveStyle()

- Expected
- textAlign: right;
```

As flipping of `textAlign` is not happening.

## Expected Behavior

Test should pass ✅

### Logs

_No response_

### Requested priority

High

### Products/sites affected

_No response_

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### PR DESCRIPTION
**Pull request by layershifter**
`FluentProvider` as other components may apply direction dependant styles, but it will not properly apply them (see "Current" & "New" behavior).

https://github.com/microsoft/fluentui/blob/abe8510e6cf939183a1acc00050c4100fb4acd6c/packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderStyles.ts#L25-L28

This happens because `useStyles()` is executed in a parent context and ignored `dir` value from `props`. [But it's expected and how React hooks work ¯\_(ツ)_/¯](https://codesandbox.io/s/hidden-shape-b1vdx4?file=/src/App.js:102-268)

The fix is to use `makeStyles()` from `@griffel/core` and pass proper values to it. This PR also adds `textAlign` to styles to match v0 behavior (that's also required to look properly in RTL):

https://github.com/microsoft/fluentui/blob/abe8510e6cf939183a1acc00050c4100fb4acd6c/packages/fluentui/react-northstar/src/themes/teams/components/Provider/providerStyles.ts#L5-L8

## Current Behavior

```tsx
function App() {
  return <FluentProvider dir="rtl" />;
}
```

```css
.css {
  /* ❌ this should be "right" */
  text-align: left;
}
```

## New Behavior

```tsx
function App() {
  return <FluentProvider dir="rtl" />;
}
```

```css
.css {
  text-align: right;
}
```

## Related Issue(s)

Fixes #22930.
Needed for #22933.

### CODE REVIEW

**Comment by fabricteam** [comment]
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/abe8510e6cf939183a1acc00050c4100fb4acd6c'>abe8510e6cf939183a1acc00050c4100fb4acd6c</a></sub>
<div id="bundleSizeComment9423"/>

**Comment by fabricteam** [comment]
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/Avatar-mount_base.html">1283</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/Avatar-mount.html">1297</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/Button-mount_base.html">765</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/Button-mount.html">785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/FluentProvider-mount_base.html">2430</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/FluentProvider-mount.html">2456</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/FluentProviderWithTheme-mount_base.html">383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/FluentProviderWithTheme-mount.html">403</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">353</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">354</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">452</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">458</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/MakeStyles-mount_base.html">2030</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/22936/perf-test-react-components/MakeStyles-mount.html">1996</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

File: packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.tsx [hunk 1]
```diff
@@ -14,4 +16,17 @@ export const FluentProvider = React.forwardRef<HTMLElement, FluentProviderProps>
...
 });
 
+export const FluentProvider = React.forwardRef<HTMLElement, FluentProviderProps>((props, ref) => {
+  const { dir } = useFluent();
+
+  // "FluentProvider" is a wrapper component that renders to ensure that "TextDirectionProvider" will be applied
+  // Otherwise "useStyles" hook inside "useFluentProviderStyles" will return styles for an incorrect direction
+
+  return (
+    <TextDirectionProvider dir={props.dir || dir}>
```
Comment (miroslavstastny) [inline packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.tsx:26]: I don't like how the `Inner` component adds complexity here, especially considering re-compose scenario.
It would be great if we could encapsulate this deep into the component.

Have you considered not adding this extra layer and instead updating `useFluentProviderStyles`?
- we can have `left` and `right` setting `textAlign` with `@noflip` slots in `makeStyles` there
- apply `left` or `right` based on `state.dir`

Comment (miroslavstastny) [reply packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.tsx:26]: btw `makeStyles` typings cry when you use `@noflip` on `textAlign` :-/

Comment (layershifter) [reply packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.tsx:26]: > I don't like how the Inner component adds complexity here, especially considering re-compose scenario.

I also don't like that option.

Another option would be to make `TextDirectionProvider` (coming from `@fluentui/react-components`) public API instead of `dir` prop on `FluentProvider`. Then the problem is solved, but it's not intuitive at all.

> Have you considered not adding this extra layer and instead updating `useFluentProviderStyles`?

Yes, but then in #22933 I have:

```tsx
  const classes = useStyles();
  const themeClassName = useThemeClassName();

  const className = mergeClasses(themeClassName, classes.root);
```

And as `themeClassName` contains classes from `useFluentProviderStyles()` it logs an error because of direction mismatch in `mergeClasses()`:

https://github.com/microsoft/griffel/blob/007d25262e5f0f9924db915cb531a7071f05bb87/packages/core/src/mergeClasses.ts#L109-L113

Comment (layershifter) [reply packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.tsx]: Refactored to use `@griffel/core` and `makeStyles()` from there.

Comment (miroslavstastny) [reply packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.tsx]: Much cleaner now, thanks!

**Comment by layershifter** [comment]
> We still have one issue (which is probably separate) - `FluentProvider` sets initial styles on its element, how can I override those?
>
> Overriding using `makeStyles` works on the nested provider, but fails if `dir` is different between the two. Obviously, it completely fails on top level provider.
>
> Do I need to recompose for this or should I use `style` in this case?

Yes, this part is the worst. We faced it in the application already.

- ❌ `style` is not passed down to portals elements (that could a good option in some cases)
- ❌/✅ recomposition will not work in this case **until it uses `@griffel/core` as in this PR** (that is not obvious at all)

---

The only working solution without hacks is wrapping + additional provider:

```tsx
import { TextDirectionProvider } from "@griffel/react";
import { makeStyles, FluentProvider } from "@fluentui/react-components";

const useClasses = makeStyles(/* ... */);

function CustomProvider() {
  const classes = useClasses();
  return <FluentProvider className={classes.provider}></FluentProvider>;
}

function App() {
  return (
    <TextDirectionProvider>
      <CustomProvider>
        <div />
      </CustomProvider>
    </TextDirectionProvider>
  );
}
```

**Comment by miroslavstastny** [comment]
> The only working solution without hacks is wrapping + additional provider:

Wouldn't this justify `FluentProvider` having a style overrides prop?

**Comment by layershifter** [comment]
> > The only working solution without hacks is wrapping + additional provider:
> 
> Wouldn't this justify `FluentProvider` having a style overrides prop?

Sorry, didn't get this. You can do `<FluentProvider style={{ color: 'red' }} />` currently

File: packages/react-components/react-provider/config/tests.js [hunk 2]
```diff
@@ -1 +1,3 @@
 /** Jest test setup file. */
+
+require('@testing-library/jest-dom');
```
Comment (ling1726) [inline packages/react-components/react-provider/config/tests.js:3]: is this for the extra matchers ?

Comment (layershifter) [reply packages/react-components/react-provider/config/tests.js:3]: Yup
